### ISSUE TITLE
[469a] "Cosmetic" change in the 2d Shape Editor

### ISSUE THREAD

**Issue by Snuggx** [OldUnreal/UnrealTournamentPatches#1]
Hi,

i thought it could be handy if the value in the Extrude windows would be high lighted when u open it. 
![2dshape](https://user-images.githubusercontent.com/8658549/88945646-882c1200-d28e-11ea-855a-5baf53f045ca.jpg)

**Comment by SeriousBuggie** [comment]
Partially fixed for v469b: `Extrude` and `Extrude to Point` - fine. Revolve - no:
![screen](https://user-images.githubusercontent.com/70026933/98255673-5362e180-1f86-11eb-85c6-54cefa5db3db.png)
First edit content not selected at form open.
