### ISSUE TITLE
[469c-RC3] Cursor mouse + D3D9 fullscreen not usable from second monitor

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1000]
Reproduce:
1. Start UT with any map.
2. Press Alt+Enter for make it windowed.
3. Move window to second monitor.
4. Ensure you use mouse input = Cursor, and render d3d9.
5. Press alt+Enter for goes to fullscreen.
6. Try move mouse.

Expected result: Mouse look work as usual.
Actual result: Mouse look not work at all - rotate as crazy.

Reason: exclusive full screen window d3d9 open on 1st monitor, window for take input on 2nd monitor.
Cursor moved by game to 1st monitor. As result relative coordinates of cursor goes be wrong all time.

Note: Broken can be only X axis if monitors placed side-by-side.
If they place one below (above) another, then must be broken only Y axis

Why this important:
Now UT save and restore windows position on exit. This is not be before v469c. So if you exit from UT when it be windowed on second monitor, then it start in fullscreen mode from it, and input will be broken.
So this is regression.

**Comment by SeriousBuggie** [comment]
As I see there can be few solutions:
1. On fullscreen move window to proper monitor (possible best solution).
2. On fullscreen move mouse on second monitor (possible cursor be visible or toggle hover events and it be annoying).
3. Open fullscreen mode on second monitor and use mouse here. Maybe it solution too. Also allow open UT in fullscreen mode on second screen. Currently this impossible, Which too can be count as bug.

**Comment by an-eternity** [comment]
Cursor behavior in this issue is very similar as with another issue that occurs if value of WindowedViewportX or WindowedViewportY is too small. Probably, both might have the same reason...
