### ISSUE TITLE
[469c-RC3] XOpenGL: Canvas rendering glitch with DrawActor and ClearZ=False (NW3)

### ISSUE THREAD

**Issue by Feralidragon** [OldUnreal/UnrealTournamentPatches#1005]
Check the following test map:
[DM-NW3-NukeTest.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9277719/DM-NW3-NukeTest.zip)

**Note:** you need to have NW3 installed in order to test the map and reproduce this glitch.
You can download it here: https://www.moddb.com/mods/nali-weapons-3/downloads/nali-weapons-3-client-zip-version

It seems that XOpenGL is having trouble in rendering meshes through `Canvas.DrawActor` when the last argument ( `ClearZ` ) is set to `False` .

Basically, when the mesh is rendered relatively far away, it seems to sink in the BSP surface and even disappear.
The farther the mesh is rendered from you, the more it sinks into the BSP itself, and the closer you are, the closer it is to the BSP surface.

This does not happen if `ClearZ` is given as `True` instead (since it resets the Z-buffer), meaning this is likely a Z issue of some kind.

At first this seemed the same issue as reported in #996 , however it doesn't seem to be same since that other issue was isolated to AMD cards, and I use an Nvidia RTX 3080 instead.

The following images demonstrate the problem:

![nw3_ultima_xopengl](https://user-images.githubusercontent.com/6334764/183315786-272ac865-cbca-41cc-aafe-43d2f3282e95.jpg)
![nw3_ultima_opengl](https://user-images.githubusercontent.com/6334764/183315785-c39b625b-0043-4c5e-9984-983135367511.jpg)
![nw3_ionizer_xopengl_01](https://user-images.githubusercontent.com/6334764/183315802-7cab22cd-f288-41bc-b868-2c2562b052fb.jpg)
![nw3_ionizer_xopengl_02](https://user-images.githubusercontent.com/6334764/183315803-7ebd9bf7-f79c-4341-8b9a-da1d1fe2ecc3.jpg)
![nw3_ionizer_opengl_01](https://user-images.githubusercontent.com/6334764/183315808-456163f2-02bf-422b-992f-4265f3f76a9b.jpg)
![nw3_ionizer_opengl_02](https://user-images.githubusercontent.com/6334764/183315809-2e9e2fc6-076b-4330-be97-23007b5d6b3d.jpg)
![nw3_ionizer_zoom](https://user-images.githubusercontent.com/6334764/183315814-7765d01e-517e-4ed1-9762-8a66d5d5baf7.jpg)

**Comment by stijn-volckaert** [comment]
Fixed in the 469c release version
