### ISSUE TITLE
EZ to read interface

### ISSUE THREAD

**Issue by VirgileVILE** [OldUnreal/UnrealTournamentPatches#1008]
Love the idea of overlaying the French text over the options.
https://i.imgur.com/SZHBZGI.png

**Comment by NeonKnightOA** [comment]
This belongs on https://github.com/NeonKnightOA/unreal-localization. And I'm not even close to fluent on French, so suggestions about better lines are welcome there.

**Comment by VirgileVILE** [comment]
Ok.

**Comment by VirgileVILE** [comment]
I will be grateful if you don't try to patch a game if you don't know how to do it without damaging the base product, thanks. ;)
