### ISSUE TITLE
[469c] ucc-bin on arm processors

### ISSUE THREAD

**Issue by fbraz3** [OldUnreal/UnrealTournamentPatches#1013]
There are plans to port ucc-bin to arm platform?

Would be amazing to start servers on arm-based hardware like raspberry pi

**Comment by thiagoobr** [comment]
Good Man 👏👏

**Comment by stijn-volckaert** [comment]
If there's sufficient interest, this is something we could definitely do.

**Comment by K0ntrast** [comment]
I'd certainly be interested in seeing UT run on armhf and aarch64. ☺ I see Unreal 227j has added Linux ARM support.

**Comment by nickbailuc** [comment]
> I'd certainly be interested in seeing UT run on armhf and aarch64. relaxed I see Unreal 227j has added Linux ARM support.

Thats Unreal/Unreal Gold? Damn, i gotta try that on my PineBook
But yeah I was just thinking about that today, would be awesome to see. Since Epic doesnt wanna publish source to the engine like id software did with Quake, our only solution would be if oldunreal can do it. 

I would be MORE than happy to conduct regular testing if OldUnreal can compile some builds to test @stijn-volckaert

**Comment by stijn-volckaert** [comment]
We have an aarch64 build available for internal testers. Come talk to us on Discord if you want to join the program

**Comment by fbraz3** [comment]
Amazing news @stijn-volckaert ill be in touch on oldunreal discord channels

**Comment by MrFistoon** [comment]
> We have an aarch64 build available for internal testers. Come talk to us on Discord if you want to join the program

Hi @stijn-volckaert How can i join your discord and where can i find your aarch64 build in order to test UT v469d on a rpi4 ?

**Comment by jm2** [comment]
@MrFistoon v469d already has an arm64 (aarch64) build hence why this issue is closed.

**Comment by SeriousBuggie** [comment]
@MrFistoon 

Build available here: https://github.com/OldUnreal/UnrealTournamentPatches/releases/latest

Discord here: http://discord.gg/thURucxzs6
