### ISSUE TITLE
[469c-RC3] Unable to change HUD and crosshair color with sliders

### ISSUE THREAD

**Issue by ReykerBlack** [OldUnreal/UnrealTournamentPatches#1014]
When trying to change the color using the sliders, it resets to RED.

![bug](https://user-images.githubusercontent.com/110085062/184423851-ce99dbdf-4e3d-471e-a27d-39f33f0de677.png)

**Comment by SeriousBuggie** [comment]
Not able reproduce. Need more info. Possible better record video.

**Comment by SeriousBuggie** [comment]
Confirmed.

**Comment by SeriousBuggie** [comment]
UTMenu.rut
```ini
; EN: HUDColorValues[10]="cust"
HUDColorValues[10]="цвет"
```
This value must be not translated.

**Comment by NeonKnightOA** [comment]
Already merged into the localization repo, will push a fix for main v469 repo as well.
