### ISSUE TITLE
[469c-RC3] XOpenGL does not work on macOS

### ISSUE THREAD

**Issue by gfvh** [OldUnreal/UnrealTournamentPatches#1018]
ut99 ver: v469c-rc3
mac osx: catalina

![Screen Shot 2022-08-20 at 10 35 37](https://user-images.githubusercontent.com/33219851/185734520-6f11a4de-5c2e-46df-8555-655e8d3415ca.png)

**Comment by gfvh** [comment]
Same issue is with v469c-rc4 when XOpenGL under mac os x: failed to create creating OpenGL context of version requested

**Comment by stijn-volckaert** [comment]
I've pushed a fix for the final release. As a temporary workaround, you can set UseShaderDrawParameters and UseBindlessTextures to false under [XOpenGLDrv.XOpenGLRenderDevice]. You could also simply switch to OpenGLDrv, which performs much better than XOpenGLDrv on mac.

**Comment by gfvh** [comment]
Hi

Thank you. Got it working and if i try plain OpenGL then this lags. I use now Macosx high sierra. Also both XOpenGL and OpenGL have low brightness level. System menu reacts to brightness level change but still.. i have set it to max but everything is very dark

**Comment by stijn-volckaert** [comment]
Fixed in the 469c release version. XOpenGLDrv's performance on Mac is not great, however
