### ISSUE TITLE
[469a] UnrealEd: builder brush can be hidden with bHiddenEd=True

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#102]
Reproduce:
1. Load map MH-TheFifthVortexBeta1 in UnrealEd.
[MH-TheFifthVortexBeta1.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5365970/MH-TheFifthVortexBeta1.zip)
2. Use Cube builder for make cube.
3. Enter command `BRUSH MOVETO x=0 y=0 z=0` for move brush to coords (0, 0 ,0).

Expected result: Red builder brush look like cube and appear at coords (0, 0 ,0).
Actual result: No red builder brush.

I can not bring it back with any manipulation.
`BRUSH RESET` for example.
Or with copy polys from another to brush.

v469a: bugged.
v436: bugged.

**Comment by SeriousBuggie** [comment]
Hmm. I find reason and solution. in some way `bHiddenEd=True` on builder brush.
It is ridiculous.
Need deselect all, Press control and move mouse with LMB for select Active Brush.
Open Actor properties and make `bHiddenEd=False`.

What interesting - press button "show all actors" not affect bHiddenEd for active brush.

**Comment by SeriousBuggie** [comment]
Also this menu
![img](https://user-images.githubusercontent.com/70026933/173316401-970a30a0-c214-4c0e-ab22-ec4e65705075.png)
too not deal with bHiddenEd flag.

**Comment by stijn-volckaert** [comment]
I have pushed a change that makes UnrealEd always render the builder brush when it's active, even if it has bHiddenEd set to true.
