### ISSUE TITLE
[469c-RC4] First-Time Configuration window shows duplicate renderers

### ISSUE THREAD

**Issue by unrealtitle99** [OldUnreal/UnrealTournamentPatches#1021]
After installing the 469c Release Candidate 4 patch on Windows 10, the First-Time Configuration window shows duplicate entries in the list of for most of the renderers.

![ut99 469c-rc4 1](https://user-images.githubusercontent.com/109927433/185963280-76187b9e-1941-4856-bf8d-d84ddac10955.PNG)

![ut99 469c-rc4 2](https://user-images.githubusercontent.com/109927433/185963340-c465b863-f681-4995-ab58-a6961fdef294.PNG)

**Comment by SeriousBuggie** [comment]
Workaround: delete `.int` files from `System` folder if there already present in `SystemLocalized\int` folder

**Comment by stijn-volckaert** [comment]
Fixed in the 469c release version
