### ISSUE TITLE
Solved : UT469  all version  : Fonction screenshot doesn't work any more

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1022]
with UTv469 we cannot take a screenshot  with F9 fonction or since  Nexgen with option auto screenshot enable.
that work on UTv436

**Comment by SeriousBuggie** [comment]
I constantly use `shot` function in v469. All work.
Need provide more info for say why it not work for you.

Used render? What command bind on F9? Is there folder Screenshots in System?

**Comment by SeriousBuggie** [comment]
PlayerPawn.uc:
```unrealscript
exec function SShot()
{
	local float b;
	b = float(ConsoleCommand("get ini:Engine.Engine.ViewportManager Brightness"));
	ConsoleCommand("set ini:Engine.Engine.ViewportManager Brightness 1");
	ConsoleCommand("flush");
	ConsoleCommand("shot");
	ConsoleCommand("set ini:Engine.Engine.ViewportManager Brightness "$string(B));
	ConsoleCommand("flush");
}
```
Nexgen code:
```unrealscript
		// Automatically take a screenshot.
		if (gameEndTime > 0 && timeSeconds - gameEndTime >= autoScreenShotDelay &&
		    !bScreenShotTaken && player.bShowScores) {
			if (timeSeconds > autoSSMinGameTime &&
			    (gc.get(SSTR_AutoSSNormalGame, "false") ~= "true" ||
			     gc.get(SSTR_AutoSSMatch, "true") ~= "true" && sConf.matchModeActivated)) {
				player.sShot();
			}
			bScreenShotTaken = true;
		}
```
All must work.

**Comment by Letylove49** [comment]
> I constantly use `shot` function in v469. All work. Need provide more info for say why it not work for you.
> 
> Used render? What command bind on F9? Is there folder Screenshots in System?

i use Opengl renderr  and the commande   F9=Sshot.  i'am suprising  because with utv436 that work well and the screenshot come into system folder.   Must i to creat a Sshot folder for that work ?

**Comment by Letylove49** [comment]
i have make a new install of ut and now the screenshot go to Sreenshot folder instead system of   jpg format instead bmp

my  ut install was probabely corrupted afher  multi pach install.

the problem  is now solved thanks for your help.

**Comment by Letylove49** [comment]
issue solved by new install of the game.
