### ISSUE TITLE
[469c-RC4] Menu entries multiplied

### ISSUE THREAD

**Issue by mkardi** [OldUnreal/UnrealTournamentPatches#1025]
Each game type is showing up three times in Start Practice Session window.
This happens after installing 469c-rc4 over 469b

![duplicate_entries](https://user-images.githubusercontent.com/81050091/186264012-86b3cfc9-8e09-4677-b3f1-77c6f50266c9.png)

**Comment by stijn-volckaert** [comment]
This is the same bug as #1021. It will be fixed in the final release.

**Comment by Letylove49** [comment]
this happening with the skin too
![Shot00169](https://user-images.githubusercontent.com/110738647/192087861-306200f2-76b7-471e-ab17-ea6d527a5ff0.png)

**Comment by An0th3rOne** [comment]
![UnrealTournament_hpOI1xT7kb](https://user-images.githubusercontent.com/24214072/192123104-fe1f6639-28e0-47b6-8955-fbf40f8bd8ae.png)
same thing here...
