### ISSUE TITLE
[469b] Save map after import map crash UnrealEd

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1028]
Reproduce:
1. Start UnrealEd
2. Import t3d file: [crash.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9418870/crash.zip)
3. Save map.

Expected result: Map saved.
Actual result: UnrealEd crashed.

**Comment by SeriousBarbie** [comment]
Some additional findings: 
- Same happens when Mover is inserted by GUI
- Same happens when a cube mover instead of a sheet is used
- Same happens when map was rebuild
- If any CSG_Subtract Brush is added (Sheet or Brush), even distracted from mover, map can be saved. If that additional brush is removed, UnrealEd crashed again at saving.
- If any CSG_Subtract Brush is added (Sheet or Brush), UnrealEd crashes at saving.

**Comment by SeriousBuggie** [comment]
In exact this case rebuild not help. But in few other cases I use rebuild map fully and this help.

But since it is not normal crash, it more look like memory corruption, so it can be lucky coincident.

**Comment by SeriousBuggie** [comment]
Able reproduce it as:
1. Start UnrealEd.
2. Select cube via cube builder.
3. Add it as mover.
4. Try save map.

Look like broken editor itself. Input file not really relevant.

**Comment by SeriousBuggie** [comment]
`Exception thrown at 0x6A130CF7 (Core.dll) in UnrealEd.exe: 0xC0000005: Access violation reading location 0x00B40000.`

**Comment by SeriousBuggie** [comment]
Crash inside __alloca_probe.
So look like some variable try _alloca (which is [deprecated](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-170) "because a more secure version is available; see [_malloca](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/malloca?view=msvc-170).") and this hit unallocated memory.

**Comment by SeriousBuggie** [comment]
Current situation on call stack
Core.dll:
__alloca_probe <-- unalloc memory hit here
void appUnwindf(const unsigned __int16 *, ...) <-- obviously try unwind stack.
Engine.dll:
void __thiscall UModel::PrecomputeSphereFilter(UModel *this, const struct FPlane *) <-- real crash goes here

**Comment by stijn-volckaert** [comment]
Should be fixed now

**Comment by SeriousBuggie** [comment]
Confirmed fixed.
