### ISSUE TITLE
Mouse sense changes dramatically between Fullscreen and window modes

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1032]
Mouse sense changes dramatically between Fullscreen and window modes.
Don't remember there being a problem in 469b

**Comment by SeriousBuggie** [comment]
What UT version you use? 
What mouse input you use?
![img](https://user-images.githubusercontent.com/70026933/187026100-1794b73b-f89e-4dca-b7c3-44e396ca70f9.png)

**Comment by An0th3rOne** [comment]
https://i.imgur.com/wSf0uhN.png

i use 0.80 when in window mode.

**Comment by SeriousBuggie** [comment]
If set Cursor mode it helps? Installed any other software with can alter mouse sensitivity in fullscreen mode? What OS you use?

**Comment by An0th3rOne** [comment]
i use this: http://donewmouseaccel.blogspot.com/2010/03/markc-windows-7-mouse-acceleration-fix.html

**Comment by An0th3rOne** [comment]
windows 10

**Comment by An0th3rOne** [comment]
somehow resetting opengl settings also fixed this problem.. also i noticed it was D3D9 that i had it set to previously.
