### ISSUE TITLE
[469c-RC4] Critical Error when running installer as unprivileged user

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1034]
It looks like the application crashes because there is no or a not valid registry key - I'm afraid on that machine is no registry entry for UT, because the UT installation has been taken over for years by copying the files only.
Or there might be an error because a key cannot be created under HKLM, because I'm running the application with reduced privileges.
![OldUnreal-UTPatch469c-Windows-RC4 exe-CriticalError](https://user-images.githubusercontent.com/81397053/187036286-b4e6fe6a-ca0b-4ebc-888f-286143deebd8.jpg)

**Comment by SeriousBuggie** [comment]
Second one. You need run it from Administrator.

**Comment by SeriousBarbie** [comment]
But there was no hint to that when starting the application.
Suggestions:
* give a helpful message at that exception
* skip creating reg values in HKLM
