### ISSUE TITLE
openGL 469c RC4 , weird Colours when getting belt. if red player gets belt then they are red..

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1036]
https://i.imgur.com/NyXhWKX.jpeg

**Comment by SeriousBuggie** [comment]
You need some options. HighDetailedActors, ShinySurfaces, maybe something other.

**Comment by An0th3rOne** [comment]
yeah used to look like this;

https://imgur.com/LcMqQRX

not sure what happened ive made no changes to .ini

**Comment by An0th3rOne** [comment]
ahh i reset defaults and its back to normal.. dont know what changed these settings.
