### ISSUE TITLE
[469b] Ued: Make Vertex Editing points render on top of everything

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1037]
When you select brushes and you try to Vertex Edit them, you will notice the points are not always rendering on top of other brushes, which is based on the Order arrangement of the actual brushes.

This causes visual issues when mapping, but there is also a technical issue, because you cant Left Click on the vertex to select it. My idea is to ignore the Order of the brushes and always render the gray and white Vertex Editing points on top of everything, so you can select them without any issues.

![Screenshot_55](https://user-images.githubusercontent.com/58362332/187079057-8ff1c9a6-e261-4805-b615-a0fe1fc219eb.png)

**Comment by SeriousBuggie** [comment]
Select vertex by click dangerous. Instead of it use rectangle tool for select it.
Rectangle tool not affected by Z order, so it is fine here.

**Comment by BerserkerBG** [comment]
> Select vertex by click dangerous. Instead of it use rectangle tool for select it. Rectangle tool not affected by Z order, so it is fine here.

Well sure, even tho I never have any major issues by single vertex click.

But lets say you are right and box select is the only way to go, there is still the issue that you cant see the vertex in order to box select it.

![Screenshot_56](https://user-images.githubusercontent.com/58362332/187084377-8d120007-df80-4dcd-a958-c27778d1a948.png)

Can you see where the gray vertex points are? You can barely see it. They must render on top.

**Comment by SeriousBuggie** [comment]
This in all renders? I not remember such in d3d9 render for example.

**Comment by BerserkerBG** [comment]
> This in all renders? I not remember such in d3d9 render for example.

Yes, this is in all renderers. I've made a special test map to showcase this issue.

![Screenshot_57](https://user-images.githubusercontent.com/58362332/187088296-d5dac188-4023-49e6-8935-743a25a939b4.png)
[VertexEditTest.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9440203/VertexEditTest.zip)

This subtracted brush can be used as an example. If you select it and use Vertex Edit mode, you cant see the gray vertex points, they are invisible. And its confusing because you cant know where the brush is in top view, so you can box select it - impossible to know where the points are.
