### ISSUE TITLE
[469a] Incorrect display of mesh in a fog zone

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#104]
This only happens with one custom mesh in all renders except D3D7 and Software (no problem on 436). Class and texture don't matter.
Software/D3D7:
![software](https://user-images.githubusercontent.com/10724977/95778105-15003c80-0cd0-11eb-8a81-4b04b9669a8c.jpg)

Other renders:
![other](https://user-images.githubusercontent.com/10724977/95778134-23e6ef00-0cd0-11eb-9e6f-50f17c0ab37b.jpg)

Example map: 
[mushroom_test.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5366878/mushroom_test.zip)

**Comment by stijn-volckaert** [comment]
Which of these images shows the correct rendering?

**Comment by stijn-volckaert** [comment]
Confirmed and fixed for 469b
