### ISSUE TITLE
[469c-RC4] HUD ammo bar covers only 3/4

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1042]
I noticed that every ammo bar covers only 3/4 of its range although the ammo is at its limit. On [my server](https://www.gametracker.com/server_info/85.214.243.170:7777/) I increase _MaxAmmo_ by 10 (except WarheadLauncher):
![469cRC4-ammo-bar-too-short](https://user-images.githubusercontent.com/81397053/188023429-7704170c-51a3-453f-a1d0-5d69edcbbaa6.jpg)

With v436 it shows the correct length.

FYI the corresponding code line in HUDSB.uc, function DrawWeapons(Canvas Canvas):
`AmmoScale = FClamp(94.0 * WeapScale * WeaponSlot[i].AmmoType.AmmoAmount/(WeaponSlot[i].AmmoType.MaxAmmo * MaxAmmoScale), 0, 94);`

**Comment by SeriousBuggie** [comment]
What values of MaxAmmoScale and WeapScale? MaxAmmoScale is not stock code.

**Comment by SeriousBarbie** [comment]
WeapScale is unchanged and
`WeapScale = WeaponScale * Scale;`
as in ChallengeHUD.DrawWeapons().
_MaxAmmoScale_ is 10 as I mentioned above.

**Comment by SeriousBuggie** [comment]
Not able reproduce:

1920x1080 - fullscreen d3d9
1280x720 - windowed d3d9
![Shot00068](https://user-images.githubusercontent.com/70026933/188103294-6f978402-c0ba-4682-9fdb-48fa0308b041.png)
![Shot00067](https://user-images.githubusercontent.com/70026933/188103320-2cc274f9-7ecc-4c59-b7f3-383c90a0562f.png)
![Shot00066](https://user-images.githubusercontent.com/70026933/188103343-91f1867c-00e1-4110-86dc-96f5e46f36da.png)
![Shot00065](https://user-images.githubusercontent.com/70026933/188103352-b25c1c98-4203-4ec1-ae7b-7f719b26ac04.png)
Settings:
![img](https://user-images.githubusercontent.com/70026933/188103572-61b77e55-aceb-4249-a056-1cec2c4633e3.png)
![img](https://user-images.githubusercontent.com/70026933/188103656-ace13245-affb-44c2-a292-c3b27ca039fd.png)

**Comment by SeriousBarbie** [comment]
No change with a new created UnrealTournament.ini and user.ini:
![469cRC4-ammo-bar-too-short#2](https://user-images.githubusercontent.com/81397053/188106773-764d2108-1e6a-437a-82e7-d54eda064d2c.jpg)

**Comment by SeriousBuggie** [comment]
Now stock code:
`AmmoScale = FClamp(88.0 * WeapScale * WeaponSlot[i].AmmoType.AmmoAmount/WeaponSlot[i].AmmoType.MaxAmmo, 0, 88 * WeapScale);`
So your copied hardcode about 64.0 not work properly. 64.0/88.0 = 0.72 which close to 3/4 = 0.75.

**Comment by SeriousBuggie** [comment]
Oh 94. not 64. Then idk why you show in this way. But if you play with grow/shrink hud, it can set WeaponScale to 0.8.

**Comment by SeriousBuggie** [comment]
Able reproduce. But only on your server.
Need set hud size above middle.
![img](https://user-images.githubusercontent.com/70026933/188129031-d20767c7-46dd-488c-aa71-3ef5280c8d51.png)
![Shot00071](https://user-images.githubusercontent.com/70026933/188128871-ca73becb-bae6-4983-9e94-2d13265c852f.png)
![Shot00070](https://user-images.githubusercontent.com/70026933/188128890-dd7d891c-0f84-4bf8-a305-083c78f40d32.png)
![Shot00069](https://user-images.githubusercontent.com/70026933/188128908-2ebfb6e6-c94c-457f-b38c-ab0a377dc2a7.png)

**Comment by SeriousBuggie** [comment]
When slider `HUD Size` at left, field HUDScale = 0.2.
When at middle - 0.6 (no bug here).
When at right - 1.0.
Between 0.6 - 1.0 - bug appear.

WeaponScale always 1.0

Windowed mode: 1280x720
![img](https://user-images.githubusercontent.com/70026933/188166106-f3ba3db9-1400-48f9-87a6-e6700ae6dedf.png)
Fullscreen mode: 1920x1080
![img](https://user-images.githubusercontent.com/70026933/188167157-b0e7474b-a0db-4f49-a276-aa99f2f187e2.png)
Windowed mode, close to 3840x1080
![img](https://user-images.githubusercontent.com/70026933/188167532-87528c67-f531-4ade-9dd9-58c8e401be77.png)

**Comment by SeriousBuggie** [comment]
This happen because Clamp value not scaled in your code.
`AmmoScale = FClamp(94.0 * WeapScale * WeaponSlot[i].AmmoType.AmmoAmount/(WeaponSlot[i].AmmoType.MaxAmmo * MaxAmmoScale), 0, 94);`
Clamp must be scaled to. `94.0 * WeapScale` instead of `94` at end (3rd param).

**Comment by SeriousBuggie** [comment]
Also by same reason bar can overflow tile:
![img](https://user-images.githubusercontent.com/70026933/188168926-65d85151-07cd-4a96-bf74-ea8e49149011.png)

**Comment by an-eternity** [comment]
What is the way to enable these additional HUD elements (such as Time), and how to determine their presence, size and location on the screen in order to draw another elements around (game type icon, players list and so on) properly without overlapping? (This is old problem i still can not find solution for)

**Comment by SeriousBuggie** [comment]
Time is nexgen stuff,, 

No way determine place which already used.

**Comment by SeriousBuggie** [comment]
I still see you not fixed this in your controller latest build 4375:
```unrealscript
				AmmoScale = FClamp(94.0 * WeapScale * WeaponSlot[i].AmmoType.AmmoAmount/(WeaponSlot[i].AmmoType.MaxAmmo * MaxAmmoScale), 0, 100);
/*
				if (Level.TimeSeconds > LastLogged + 1)
				{
					log("scale=" $ scale $ ", WeapScale=" $ WeapScale $ ", WeaponSlot[" $ i $ "].AmmoType.AmmoAmount=" $ WeaponSlot[i].AmmoType.AmmoAmount $ ", WeaponSlot[" $ i $ "].AmmoType.MaxAmmo=" $ WeaponSlot[i].AmmoType.MaxAmmo $ ", MaxAmmoScale=" $ MaxAmmoScale);
					LastLogged = Level.TimeSeconds;
				}
*/

				//AmmoScale = FClamp(94.0 * WeapScale * WeaponSlot[i].AmmoType.AmmoAmount/(WeaponSlot[i].AmmoType.MaxAmmo), 0, 94);
				// v469c RC4: AmmoScale = FClamp(88.0 * WeapScale * WeaponSlot[i].AmmoType.AmmoAmount/WeaponSlot[i].AmmoType.MaxAmmo, 0, 88 * WeapScale);
```

Anyway, this issue related exactly to your HUDSB, and not related to game itself. Need fix your mod. Closed.
