### ISSUE TITLE
[469b] Projectiles don't explode when touched by instigator

### ISSUE THREAD

**Issue by BearBeardgh** [OldUnreal/UnrealTournamentPatches#1048]
https://user-images.githubusercontent.com/86536022/188993359-449acd63-9acf-448c-a7b4-a1557099d477.mp4

i shot a deemer and after i used my trans  i was hoping for the hit but it went right through me.

Same with secondary ripper

https://user-images.githubusercontent.com/86536022/188994507-62ced19d-5d27-4f6a-90e7-24ff5f7a6904.mp4

Same with secondary shock

https://user-images.githubusercontent.com/86536022/188994906-d469287d-77c8-4320-8186-ea544926a754.mp4

same with primary rocket

https://user-images.githubusercontent.com/86536022/188995271-3a59d147-64c0-4b97-b12b-644e066dab30.mp4

**Comment by BearBeardgh** [comment]
this situation happens using amp too

**Comment by SeriousBuggie** [comment]
> i shot a deemer and after i used my trans i was hoping for the hit but it went right through me.
It is feature:
```
	function ProcessTouch (Actor Other, Vector HitLocation)
	{
		if ( Other != instigator ) 
			Explode(HitLocation,Normal(HitLocation-Other.Location));
	}
```

**Comment by SeriousBuggie** [comment]
> Same with secondary ripper

Same here.
```unrealscript
	simulated function ProcessTouch (Actor Other, Vector HitLocation)
	{
		local RipperPulse s;

		if ( Other != Instigator ) 
		{
			if ( Role == ROLE_Authority )
			{
				Other.TakeDamage(damage, instigator,HitLocation,
					(MomentumTransfer * Normal(Velocity)), MyDamageType );
			}
			s = spawn(class'RipperPulse',,,HitLocation);	
 			s.RemoteRole = ROLE_None;
			MakeNoise(1.0);
 			Destroy();
		}
	}
```

**Comment by SeriousBuggie** [comment]
> Same with secondary shock

again:
```unrealscript
	function ProcessTouch (Actor Other, vector HitLocation)
	{
		If ( (Other!=Instigator) && (!Other.IsA('Projectile') || (Other.CollisionRadius > 0)) )
			Explode(HitLocation,Normal(HitLocation-Other.Location));
	}
```

**Comment by SeriousBuggie** [comment]
> same with primary rocket

Same:
```unrealscript
	simulated function ProcessTouch (Actor Other, Vector HitLocation)
	{
		if ( (Other != instigator) && !Other.IsA('Projectile') ) 
			Explode(HitLocation,Normal(HitLocation-Other.Location));
	}
```

**Comment by stijn-volckaert** [comment]
I can confirm that this is a feature and not a bug
