### ISSUE TITLE
[469b] XOpenGL looks like a nightclub using NVIDIA GeForce 930M/PCIe/SSE2 on Toshiba Laptop.

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1055]
not sure why but heres some screenshots;

![UnrealTournament_UaEZaLo7JP](https://user-images.githubusercontent.com/24214072/189472406-841b7323-18ba-4eed-bfa3-09b2c21ef2b8.jpg)
![UnrealTournament_xiN95x5w2Y](https://user-images.githubusercontent.com/24214072/189472410-86b4931f-4231-4b7e-b6f5-45c386873d42.jpg)
![UnrealTournament_YEiLZtDi3F](https://user-images.githubusercontent.com/24214072/189472411-e105c95a-2b3b-47d1-b745-5e710d55c52a.jpg)

colors rapidly changing as i move mouse around.

**Comment by stijn-volckaert** [comment]
I have never seen this issue before. Could you upload your XOpenGLDrv settings and game log please?
