### ISSUE TITLE
[469b] Auto-Taunts not working

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1058]
Description below;

**Comment by An0th3rOne** [comment]
ok to be more descriptive , when i set AutoTaunt to on and other players have it set on also... i can hear their auto-taunts but not my own.. they also hear my autotaunts . but i can't hear my own autotaunts. this is online. just checked also not working offline in practice session.

**Comment by SeriousBuggie** [comment]
For me all work in practice mode. But you need turn on hear auto taunts in config
![img](https://user-images.githubusercontent.com/70026933/192202410-be5759d8-4f35-46f7-a4e9-5e3adb072f76.png)
Auto-taunt must be turned on:
![img](https://user-images.githubusercontent.com/70026933/192202494-bcf0ed5c-d6ff-410e-a858-db6220f84229.png)
From you must be no voice messages for at least 5 seconds.
And this must be not headshot.

If all this conditions met, I hear my own auto taunt. If there headshot, I think announcer message suppressed my auto taunt.

**Comment by stijn-volckaert** [comment]
No problems here either. Please note that you only hear taunts when several conditions are met, as described in #1096
