### ISSUE TITLE
[469b] Why do fonts scale BOLDER in 469?

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1059]
we're making a chat mod UTChat where the players are able to scale the fonts between different sizes from 14-24
however once you jump from size 16 to 18 the fonts almost double in width.. looking fatter.
for example this is size 16;
![UnrealTournament_GddelwtYZ2](https://user-images.githubusercontent.com/24214072/189479682-db71caa3-acb8-4c32-b165-93fd233615a5.png)
and this is size 18;
![UnrealTournament_a9wuCljaSj](https://user-images.githubusercontent.com/24214072/189479684-5c844e4d-725b-4ba7-b6f8-599e9072e922.png)
Proasm assures me that he has not made them BOLDER... and blames 469 for this as 451 they look normal.

**Comment by Calinou** [comment]
The font looks bolder because the larger font size means the font can be represented more accurately. At small sizes, the font rendering is *less* accurate because the font rasterizer can only draw a 1-pixel wide line or 2-pixel wide line. It can't draw 1.5 pixel wide lines.

**Comment by stijn-volckaert** [comment]
> This is not a bug – it's done by design.
> 
> The font looks bolder because the larger font size means the font can be represented more accurately. At small sizes, the font rendering is _less_ accurate because the font rasterizer can only draw a 1-pixel wide line or 2-pixel wide line. It can't draw 1.5 pixel wide lines, for instance.
> 
> Some font rasterizers allow you to change the hinting to make differently sized fonts look more consistent with each other, but this comes at the cost of crispness. Fonts looking closer to their intended form but blurrier isn't always preferable, especially on low-resolution displays.
> 
> PS: I'd argue the bolder font is more readable here, especially since it lacks an outline or shadow 🙂

I fully agree with this comment!
