### ISSUE TITLE
[469c RC4]Bug in "Search for Actor"

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1063]
In map MH-ArcaneTempleLords_R.unr I searched for Event "spw" and got beside correct "Squid9" the "Dispatcher0" which has none Event but a Tag with "spw".
![Bug_SearchForActors](https://user-images.githubusercontent.com/81397053/189734588-0cdf46e5-dd85-491e-9eaa-213427c7bcd7.jpg)

**Comment by SeriousBarbie** [comment]
Probably not a bug: Dispatcher0-OutEvents[0] has the value "Spw2a" what means that it can raise an event which name has the pattern "Spw" in it.

**Comment by SeriousBuggie** [comment]
Yes. It search in additional fields. Not only in Event/Tag.

**Comment by SeriousBarbie** [comment]
What to do with this "feature report"? Remove it?

**Comment by SeriousBuggie** [comment]
If you about issue - close it, as you do.
