### ISSUE TITLE
[469c-RC4] 'Level.Millisecond' variable contains invalid value...

### ISSUE THREAD

**Issue by an-eternity** [OldUnreal/UnrealTournamentPatches#1064]
Expected behavior:
`Level.Millisecond` is properly synchronized with another current time variables (`Level.Second`, etc.)

Actual behavior:
`Level.Millisecond` value is a few milliseconds ahead of another current time variables (`Level.Second`, etc.), which means `Level.Second` value gets incremented not in the same moment when `Level.Millisecond` value is equal to 0, but when it is equal to, for example, 5 or more.

This issue produces errors in calculations that use these variables as a time source.

Only Linux builds are affected.
Windows builds have been tested as well, result: such issue was not found.

**Comment by an-eternity** [comment]
If this issue is up to Linux OS and a fix for it is not practically doable, then need to add a "won't fix" tag and to close this issue.

And maybe consider to add a warning notification in compiler for the case if the compiled script accesses `Level.Millisecond`, so that to warn UScript coders `Level.Millisecond` is unreliable...

**Comment by SeriousBuggie** [comment]
Linux use two calls. When Windows use one. 
However Linux use Bad implementation. All can be done via single call, and this resolve this issue.

Need change in appSystemTime
```c++
	gettimeofday( &Tv, NULL );
	CurTime = time( NULL );
	St = localtime( &CurTime );
```
to
```c++
	gettimeofday( &Tv, NULL );
	St = localtime( &Tv.tv_sec );
```
