### ISSUE TITLE
Kicker with Sprite texture value assigned is not visible in-game

### ISSUE THREAD

**Issue by shai-ut99** [OldUnreal/UnrealTournamentPatches#1067]
Many BunnyTrack maps use Kickers with Display->Sprite set to a particular texture to make the kicker visible in-game (e.g., [BT+(Roel)OrbField-SE](http://www.i4games.eu/maps/CTF-BT%2B%28Roel%29OrbField-SE) and [SuddenDeath](http://www.i4games.eu/maps/CTF-BT-SuddenDeath-v2)).

These Sprite textures are visible in the 469c editor (see here: https://www.mediafire.com/view/medet5w63gf8alk - the glowing letters are kicker sprites), but they're not visible in the game. However they _are_ visible in-game when such a map is played on a 451 or 436 server.

**Comment by SeriousBarbie** [comment]
Here the numbers were visible,  in UnrealEd as well as when running map from editor:
![CTF-BT+(Roel)OrbField-SE](https://user-images.githubusercontent.com/81397053/190380434-c895e9af-343c-4770-903c-a0ad2aa39b79.jpg)

**Comment by shai-ut99** [comment]
Thanks SeriousBarbie, that's helpful. I admit I hadn't checked this out using my 469 client, only my 436 client. When connecting to our BT 469c server with a 469c client (and that same map) the sprites were visible.

So the issue is most likely with the renderer I'm using with 436 (which I think is "OpenGL renderer version 3.5 for UT" from this page https://www.cwdohnal.com/utglr/) and NOT a problem with 469, so I'll close this "issue".

**Comment by shai-ut99** [comment]
...having said that. With the same renderer, on the same map, on a 451 server I AM able to see the sprites. So I don't know what's going on, or whether it's something that requires attention, but it's a little odd.

**Comment by SeriousBuggie** [comment]
Which render?

**Comment by shai-ut99** [comment]
Sorry, I should have been more specific. When I join a UT server running build 451 with my UT 436 client and OpenGL renderer 3.5 (from the link above), I see the kicker sprites (for example, in [BT+(Roel)OrbField-SE](http://www.i4games.eu/maps/CTF-BT%2B%28Roel%29OrbField-SE)).

But when I join a 469c server with my 436 client (and the OpenGL 3.5 renderer) on the same map, I don't see the kicker sprites.

**Comment by SeriousBuggie** [comment]
Can confirm. On v469c server clients v469c and v469b see kicker icons, but v436 - no. 

v436 not see because on kicker set bOnlyOwnerSee and you (obviously) not owner.

For v469 bOnlyOwnerSee not set.

In Editor v469c on map bOnlyOwnerSee not set.

**Comment by SeriousBuggie** [comment]
For more faster download:
[CTF-BT+(Roel)OrbField-SE.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9591367/CTF-BT%2B.Roel.OrbField-SE.zip)

I check on v469b server: v469c client see. v436 - not see.
When server on v436, both clients (v469c and v436) see all.

**Comment by shai-ut99** [comment]
Thank you for the investigation work, SeriousBuggie, it's good to have an explanation for what's going on.

**Comment by SeriousBuggie** [comment]
Anthrax currently found reason of issue. It is very complicated and rare bug in engine. Now devs search ways for fix it.

**Comment by shai-ut99** [comment]
Appreciate the update, thanks to both you and AnthraX for exploring further. That sounds like a really difficult issue to fix, hope it won't divert too much attention away from more pressing problems.

**Comment by SeriousBuggie** [comment]
Fix pushed into pending release and will be available soon.
