### ISSUE TITLE
[469a] The group browser in the Unreal Editor ignores that the groups are not activated.

### ISSUE THREAD

**Issue by Snuggx** [OldUnreal/UnrealTournamentPatches#107]
f I save a map with deactivated groups, close the editor, then open the map again, the groups are still deactivated. But the content of the groups is visible. I have to click twice on the affected groups to make them disappear again.
In addition, the group browser sometimes does not save which groups are active and which are not.

I hope the vid shows what i mean.

https://youtu.be/deYuOOroK70 

Additionally:

When I start the editor and load the map, the actors of deactivated groups are visible. If I then reload the map they are gone.

https://youtu.be/pp4H7lrt_v0

**Comment by SeriousBuggie** [comment]
It is strange. Especially if actors in two groups. One enabled, second no. I not find any logical explanation how it is work.
And on load you see actors, blink, applied some rules and now its not visible.

**Comment by SeriousBuggie** [comment]
> f I save a map with deactivated groups, close the editor, then open the map again, the groups are still deactivated. But the content of the groups is visible. I have to click twice on the affected groups to make them disappear again.

There no error. Editor must load map in state which be on save. So if there group deactivated but content shown, before save same must be on load map.
On load Editor must not change visibility.

> In addition, the group browser sometimes does not save which groups are active and which are not.

Need reproducible example for that. For me such not happen or I not notice it.

> When I start the editor and load the map, the actors of deactivated groups are visible. If I then reload the map they are gone.

This clearly error. As I say above editor must restore saved state and not mess with apply groups visibility at map load.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1709996916](https://github.com/stijn-volckaert/UnrealTournament/assets/70026933/aeb39d6a-5b5d-4d39-b6fa-85456a7dd15c)
![scr_1709996927](https://github.com/stijn-volckaert/UnrealTournament/assets/70026933/70a33e54-36de-4773-8369-eb164a84867e)
![scr_1709996935](https://github.com/stijn-volckaert/UnrealTournament/assets/70026933/51e3c825-963f-414e-a0c7-ebecfb918f4d)
