### ISSUE TITLE
[469c-RC4] UnrealEd: Textures cannot be selected when the group name contains a space

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1072]
1) open/create a map in UnrealEd
2) load attached Texture package "TextureWithSpace.utx"
3) assign the texture "TextureWithSpace.Test this group.AirWindow" to a surface

v436: works as expected
469c RC4: texture cannot be selected and therefore is not assigned to a surface
[TextureWithSpace.utx.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9595242/TextureWithSpace.utx.zip)

**Comment by stijn-volckaert** [comment]
Since you have access to preview builds, would you mind testing this with RC6 please?

**Comment by SeriousBuggie** [comment]
RC6 issue in place.

Workaround:
1. select texture via right click.
2. apply selected texture to selected surfaces via context menu
3. or use alt+left click for set texture on clicked surface.

**Comment by stijn-volckaert** [comment]
Same issue as #1124

**Comment by stijn-volckaert** [comment]
Turns out to be a different bug!

**Comment by SeriousBuggie** [comment]
Fixed on v469d Preview 9
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0d1ad877-942d-4e38-a1b3-81cebab0f9fe)
