### ISSUE TITLE
[469c-RC4] key-mapped taunt, failing...

### ISSUE THREAD

**Issue by thiagoobr** [OldUnreal/UnrealTournamentPatches#1073]
hi,

i send taunt "TOMA!" the third time it works, twice he fails....

video erro exemple:

https://youtu.be/cnZUqlzOFEM

**Comment by SeriousBuggie** [comment]
Duplicate of #278

**Comment by stijn-volckaert** [comment]
Confirmed duplicate of #278. This issue will be fixed in the release version of 469c
