### ISSUE TITLE
[469c-RC4] UTDC crash with some demos

### ISSUE THREAD

**Issue by AzuraUT99** [OldUnreal/UnrealTournamentPatches#1074]
I have a demo that is still crashing because of UTDC.

Please find it attached below.

OS is Linux and version is the latest Ubuntu.
UT version is Windows and patch is 469b.
Running on Steam Proton.
Mods used in the match were AnthCheckerC_v131, BDBMapVote304, MODOSUtilsV25, PureStat7G, UTDCv17, UTDCv17, UTPureRC7G.

[DM_Tempest_mye_vs_jag.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9597884/DM_Tempest_mye_vs_jag.zip)

**Comment by stijn-volckaert** [comment]
I can confirm the crash, but we've already built a workaround into the game. You should simply delete UTDCv17.dll before playing the demo. When you then start the demo, you will get the window that asks you to install UTDC. You can simply close this window. The demo should play fine afterwards.

Feel free to comment/reopen the issue if this doesn't work.
