### ISSUE TITLE
[469c] Output version info to the log

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1075]
I have several Servers all running different versions of 469b , 469c , 469cRC4 etc...
could we make it so that in future revisions it outputs to top of log file what version we are running please.

**Comment by SeriousBuggie** [comment]
```
Init: Version: 469
Init: Compiled: Sep 18 2022 12:35:01
```
Such not enough?

**Comment by An0th3rOne** [comment]
no , need Init: Version: 469c RC4
and date

**Comment by An0th3rOne** [comment]
also where is this Init: Version: located?

`[2022-09-22 21:03:53] ucc.init: soft-start
WARNING: Not using preference directory
WARNING: Using system ini file: /blah/System/UnrealTournament.ini
WARNING: Using user ini file: /blah/System/User.ini
=======================================
ucc.exe: UnrealOS execution environment
Copyright 1999 Epic Games Inc
=======================================

Executing Class Engine.ServerCommandlet`

is not at top.

**Comment by An0th3rOne** [comment]
no where in server log does it have version like you posted.

**Comment by SeriousBuggie** [comment]
At server.log start.
Linux server 64-bit:
```
Log: Log file open, Thu Sep 22 01:07:48 2022
Init: Name subsystem initialized
Init: Version: 469
Init: Compiled: Sep 18 2022 04:35:20
```

**Comment by An0th3rOne** [comment]
https://i.imgur.com/xvHzNpt.png

**Comment by SeriousBuggie** [comment]
> Init: Version: 469c RC4

Currently RC version labeled only by date. Even in GUI you not see anywhere RC# words.

One from RC:
![img](https://user-images.githubusercontent.com/70026933/191858521-d4d16ba9-c828-49c0-a360-350697a38f4b.png)

**Comment by SeriousBuggie** [comment]
Possible you use some log rotator, which strip file log from start with time. Try restart server and look at first lines in the log..

**Comment by An0th3rOne** [comment]
yes I use ucc.init to start server.
have sent you log via discord

**Comment by SeriousBuggie** [comment]
It is not server.log. It is dump for console from server. it is different thing. Such info written only in server log, not in console out.

**Comment by An0th3rOne** [comment]
ok `MYEXECMD="./ucc server $TMP --nohomedir --lanplay log=server.log"`
in ucc.init produces the server.log file

**Comment by an-eternity** [comment]
Is there any console command (or new constant) to get a build date? For example, admin may want it to show in ServerInfo or in UdpServerQuery...

**Comment by SeriousBuggie** [comment]
LevelInfo.EngineRevision is max what you can get here.
For not release it contain date. For release - release letter,

**Comment by an-eternity** [comment]
Looks like for some reason it is empty on the client side, - is this bug or is normal?
On the server side it works properly.
Getting it by `GetPropertyText()`.

**Comment by SeriousBuggie** [comment]
GetPropertyText work only for ROLE_Authority. So on client you need swap roles for use it.

**Comment by stijn-volckaert** [comment]
Our next build will output the engine revision to the log file. It will be under the version line.

As of 469c, UdpServerQuery also advertises the game revision using a \\gamerevision\\ tag.

**Comment by stijn-volckaert** [comment]
Log info added in the 469c release version
