### ISSUE TITLE
UT469c any RC release  (FRT Version)  Jailbreak Gold   hud don't display the nomber of player  ( that work with the INT version) (that work with the patch469b)

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1077]
Jailnbreak gold sp2 don't display the nomber of player  who are [captured
![Shot00168](https://user-images.githubusercontent.com/110738647/192065971-c45666a6-ef8c-4429-9ddd-1e74202ddf77.png)

you can see the bug on the screensshot-  This happenning both  offlne and online

this work with UT436

**Comment by SeriousBuggie** [comment]
What about RC4?

**Comment by Letylove49** [comment]
i will test it

**Comment by SeriousBuggie** [comment]
You need provide link to exact version with which you experience problems.
I see too many of it:
http://medor.no-ip.org/index.php?dir=&search=jailbreak&search_mode=f

**Comment by SeriousBuggie** [comment]
According to official site of jailbreak there no such thing as "Jailnbreak gold sp2"
https://jailbreak.beyondunreal.com/download/mod/
![img](https://user-images.githubusercontent.com/70026933/192127987-7ea7f463-72ef-4b97-bc0f-c5a8aba44aab.png)
Or gold, or sp2 for Jailbreak 3.

**Comment by SeriousBuggie** [comment]
Practice session in JB3Gold. HUD numbers in place.
![img](https://user-images.githubusercontent.com/70026933/192128170-b58ea0e0-bc9d-4149-96b8-7be5c87d3f93.png)

**Comment by SeriousBuggie** [comment]
Dedicated server. HUD numbers in place. JB3Gold:
![img](https://user-images.githubusercontent.com/70026933/192128256-218e6fd9-992f-48ed-b491-879a0c35278b.png)

**Comment by Letylove49** [comment]
this  happenning with this 2 archives : jailbreakiii-gold-zip.zip and jailbreakiii-sp2-zip.zip

**Comment by Letylove49** [comment]
OK  i have fund why for you that work, you are using  UT in int version and my  i use the FRT version . that don't work with the Frt version.

**Comment by SeriousBuggie** [comment]
Confirmed.

**Comment by SeriousBuggie** [comment]
Bad news here. It is not patch fault. it is mod fault.
Mod try get values from int files and process them. On this process it strictly bind to "int" lang.
JailBreak.JBSkinManager.GetValue (logging added by me):
```unrealscript
  TextValue = "<?int?";

  if (!SkinOverrideMap)
    TextValue = Localize("Default", Name, GetPackage());
log(1 @ TextValue);  
  if (Len(SkinCurrent) > 0 && Left(TextValue, 6) == "<?int?") {
    IndexCharSeparator = InStr(SkinCurrent $ ".", ".");
    TextPackage = Left(SkinCurrent, IndexCharSeparator);
    TextPrefix  = Mid (SkinCurrent, IndexCharSeparator + 1);

    if (Len(TextPrefix) > 0)
      TextValue = Localize(TextPrefix, Name, TextPackage);
    
    if (Left(TextValue, 6) == "<?int?")
      TextValue = Localize("Default", Name, TextPackage);
    }
log(2 @ TextValue);
```
Out on int:
```
Localization: No localization: JB-Alcatraz.Default.CHColor (int)
ScriptLog: 1 <?int?JB-Alcatraz.Default.CHColor?>
ScriptLog: 2 <?int?JB-Alcatraz.Default.CHColor?>
Localization: No localization: JB-Alcatraz.Default.StatusR (int)
ScriptLog: 1 <?int?JB-Alcatraz.Default.StatusR?>
ScriptLog: 2 <?int?JB-Alcatraz.Default.StatusR?>
Localization: No localization: JB-Alcatraz.Default.StatusB (int)
ScriptLog: 1 <?int?JB-Alcatraz.Default.StatusB?>
ScriptLog: 2 <?int?JB-Alcatraz.Default.StatusB?>
```
Out on rut:
```
Localization: No localization: JB-Alcatraz.Default.CHColor (rut)
ScriptLog: 1 <?rut?JB-Alcatraz.Default.CHColor?>
ScriptLog: 2 <?rut?JB-Alcatraz.Default.CHColor?>
Localization: No localization: JB-Alcatraz.Default.StatusR (rut)
ScriptLog: 1 <?rut?JB-Alcatraz.Default.StatusR?>
ScriptLog: 2 <?rut?JB-Alcatraz.Default.StatusR?>
Localization: No localization: JB-Alcatraz.Default.StatusB (rut)
ScriptLog: 1 <?rut?JB-Alcatraz.Default.StatusB?>
ScriptLog: 2 <?rut?JB-Alcatraz.Default.StatusB?>
```
OFC first part not match `<?int?`, condition `Left(TextValue, 6) == "<?int?"` not met, FlagNone not set, Default value not return.

This produce Black color, instead of White. Render with Black color and Style STY_Translucent mean render fully transparent.
So digits renders, but transparent.  So not visible.

Workaround: Use "int" language.
Solution: Ask maintainers of mod for fix code. Possible change condition to `Left(TextValue, 2) == "<?" && Mid(TextValue, 4, 2) == "t?"` will be enough.

**Comment by Letylove49** [comment]
I’m surprised in this case I should have the same error with UT v436? if it comes exclusively from mode. So I don’t have that problem with UT436. That’s weird, right?

**Comment by SeriousBuggie** [comment]
Are you use in v436 frt translation? I think you use here int. Since v436 never be properly translated.
Not use frt. Use int same as in v436. And ll must work fine.

You must compare versions in same conditions. Not one in frt lang, another in int lang.

**Comment by Letylove49** [comment]
that work fine with the preview patch 469b. i think is realy a 469c bug because this happening only with this patch

no necessary to set to int.  I'm a Frensh player and i want to play in frensh.

**Comment by stijn-volckaert** [comment]
Confirmed and fix pushed for the final 469c version
