### ISSUE TITLE
[469a] Save bug

### ISSUE THREAD

**Issue by Snuggx** [OldUnreal/UnrealTournamentPatches#108]
Sometimes a map cannot be saved.
I then have to give the map a different number so that I can save it. If I press save then a message comes up the editor would load the map that I could not save before. When I want to close the editor, the window appears asking whether it should be saved with the correct number.
Unfortunately, I have not yet recognized a pattern when that happens.

https://youtu.be/deYuOOroK70 

![save1](https://user-images.githubusercontent.com/8658549/96017854-c7f4a580-0e4a-11eb-9cf2-c9c4062ed6e2.jpg)
![save2](https://user-images.githubusercontent.com/8658549/96017857-c88d3c00-0e4a-11eb-94b9-b46b287fb88c.jpg)

**Comment by SeriousBuggie** [comment]
As far I understand pattern is next:
1. Map must be big. And not loaded fully.
2. When you try save with same name, it try load and this block file for save. So save fail.
Workaround - save with different name.

**Comment by Snuggx** [comment]
The map is not so big tbh. 
I have a map that reaches the limit of uED, and it can be saved without any problems.

![warn](https://user-images.githubusercontent.com/8658549/96025676-c2e92380-0e55-11eb-85ec-16e2ac92fb4c.png)

I thought it might have something to do with the "group browser problem".
The editor may not load everything, or not properly.

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Open [MH-TheFifthVortexBeta5.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5417840/MH-TheFifthVortexBeta5.zip)
2. Try save.

Expected result: Map save with same name.
Actual result: Map not save with message:
```
---------------------------
Message
---------------------------
Failed to save file \Maps\MH-TheFifthVortexBeta5.unr
---------------------------
ОК   
---------------------------
```

v469: bugged.
v436: not bugged.

**Comment by SeriousBuggie** [comment]
v469b 7 nov - fixed. Confirmed.
