### ISSUE TITLE
[469c-RC6] Brush not rotate on v436 client

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1085]
Reproduce:
1. Start on dedic server: [DM-test-weapon-delay.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9663372/DM-test-weapon-delay.zip)
2. Connect with v436 client.

Expected result: Brush rotate, same as if client v469c.
Actual result: Brush not rotate.

I check again, and this issue appear for v436 clients with any server.
Tested servers: v436, v469b, v469c.

**Comment by SeriousBuggie** [comment]
Work only for v469c client. Doesnot matter for which server. Clients v436 and v469b not work. On any server.

**Comment by stijn-volckaert** [comment]
This happens because RotatingMovers didn't replicate properly prior to 469c. Unfortunately, there's nothing we can do to fix the problem for older clients. Our recommendation would be to copy our updated RotatingMover code into a standalone package.
