### ISSUE TITLE
[469c-RC6] XOpenGL not contain description for choose render

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1089]
Reproduce:
1. Start `UnrealTournent.exe -video`
2. Select XOpenGL in list.

Expected result: On dialog appear description which explain difference between OpenGL and XOpenGL.
Actual result: Nothing.
![img](https://user-images.githubusercontent.com/70026933/193866321-b8b3fa03-cc01-4970-9c3f-c2d4e64fa8c6.png)
![img](https://user-images.githubusercontent.com/70026933/193866383-b6a02c6d-e95d-4def-8d8a-781790b1302b.png)

**Comment by jharrison03** [comment]
Agreed.  I even have an open thread here about this:

https://github.com/OldUnreal/UnrealTournamentPatches/discussions/1078

What exactly this is, is not explained anywhere, AFAIK, either here on this site or in any documentation shipped with program.  The sole explanation in my discussion thread doesn't really answer my question or provide any addition insight as to what "XOpenGL" is (only that it's "different" -- vs. what, exactly??), or why I should or shouldn't use it vs. any other render.

**Comment by stijn-volckaert** [comment]
This will be fixed in the 469c release version

**Comment by SeriousBuggie** [comment]
Confirmed fixed.
