### ISSUE TITLE
[469c-RC6] Cluster audio crash game/editor on specific song

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1090]
Reproduce:
1. Start UnrealEd.
2. Open [Complian_b.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9709963/Complian_b.zip)
3. Ensure you use Cluster audio driver.
4. Start play music in music browser.

Expected result: No crash.
Actual result: Crash (you need wait near 1:48).

`Exception thrown at 0x07CAFDD9 (fmod.dll) in UnrealEd.exe: 0xC0000005: Access violation reading location 0x0000014C.`
`mov     ecx, [esi+14Ch]`
esi = 0
Esi is `this` here.
![img](https://user-images.githubusercontent.com/70026933/193908449-d450b5a6-b079-4002-ae49-4a3608a0165f.png)

OpenAL and Galaxy is fine.
I play in OpenAL and on 1:48 music play normally. It is not end. End at 3.35. So this is not #481.
It must be some bad notes, which fmod not able properly play.

---

@SeriousBarbie
Issue happen on MH-DarkWhite map. For solve it need disable MusicEvent0 or change song in it.

**Comment by SeriousBuggie** [comment]
Related report: https://forum.barbies.world/viewtopic.php?t=1802

**Comment by SeriousBuggie** [comment]
In OpenMPT It be 23 (maybe part of previous 22) pattern. There some interesting reverb in sound.
![img](https://user-images.githubusercontent.com/70026933/193914317-bc7696b9-5004-4cdb-ad34-70f64d89b18e.png)
![img](https://user-images.githubusercontent.com/70026933/193914385-febb6bfd-939f-46aa-a1cf-551e9e6180a4.png)

**Comment by SeriousBuggie** [comment]
Foreground MPT, Background UnrealEd. Started almost in same time (UnrealEd little later).

https://user-images.githubusercontent.com/70026933/193927936-7c70fb5e-f99e-4668-baf3-89c82417d465.mp4

**Comment by SeriousBuggie** [comment]
22 Look like OK.
23 Look like broken.
Diff:

https://user-images.githubusercontent.com/70026933/193928663-418735e5-8474-40e7-b1b8-bbf1b6601a6a.mp4

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/193937271-0933c085-e8ae-4d2c-b5dc-2c017cad9333.png)

If I delete this note, then it not crash here. It crash on next pattern, because such note appear in next 12 patterns or more.

**Comment by SeriousBuggie** [comment]
3F0 mean
https://wiki.openmpt.org/Manual:_Effect_Reference
![img](https://user-images.githubusercontent.com/70026933/193938525-956421a9-69f8-4698-a4ca-95f3270bed6b.png)
I try 301 in hope it cause by big step F0, but such file too crash.
If I remove effect entirely, then crash happen lately, not here.

**Comment by an-eternity** [comment]
+Two more maps...
`MH-RiseOfEvil_Beta1.unr`
`MH-TrickyV3.unr`

**Comment by stijn-volckaert** [comment]
Bug reported upstream

**Comment by SeriousBuggie** [comment]
Yes, I see: https://qa.fmod.com/t/crash-when-playing-mod-tracker-file/19363
Maybe need provide link to this issue? There a lot internal info which can help narrow down issue faster.

**Comment by stijn-volckaert** [comment]
We will include the updated FMOD in 469c

**Comment by SeriousBuggie** [comment]
Confirmed fixed with fmod.dll x86 2.2.10.
