### ISSUE TITLE
[469c] ability to have 100 custom bots

### ISSUE THREAD

**Issue by An0th3rOne** [OldUnreal/UnrealTournamentPatches#1092]
just wondering if at all possible to extend the 32 bots limit to 100?

cheers

**Comment by SeriousBarbie** [comment]
Do you want to use more than 32 bots in a match or do you want more than 32 different bots? If the latter is should be possible to patch UnrealTorunament.ini where IMO the but definitions are stored.

**Comment by SeriousBuggie** [comment]
Bot definitions stored in User.INI. And there max is 32 entries. I think he want more items in this arrays for bots pickup among not 32 preset, but in bigger count.

**Comment by Engineer9736** [comment]
If it's just about having 100 bots, afaik you can just use the addbots command with any number? I remember typing in addbots 999 and the whole pc lagged for a second, entire map flooded with bots and flying flesh and screams 😅

If you want to customize all 100 of them (i wouldn't really see why, when i'm fragging i'm not really looking at their name or skin or whatever) then idk. (see comments above)

**Comment by no0nehere** [comment]
user.ini 100 definable bots be good. 32 is not enough variety :/

**Comment by SeriousBarbie** [comment]
So my idea is to replace the bot definitions either by a mutator on game startup or by an external program in in USER.INI before UT starts.
Ofc first you need a list of 100 (?) customized bots at another place in order to have a replacement source. The core of that program would be like this:
```
for (i = 0; i < 32 <++)
	if (DoReplaceBotDefinition(BotNames[i]))
		if (GetNextRandomBotIndex(j))
			ReplaceBotDefinition(i, j);
```

**Comment by SeriousBuggie** [comment]
Yes, you for sure can do this on mutator level. For example in PreBeginPlay modify class defaults.

But possible you can hit offset limit when access latest items in array. need check it.

**Comment by stijn-volckaert** [comment]
This is something we **definitely** cannot do in the patch. While ```addbots``` can add more than 32 bots, there are many places throughout the gameplay code where the limit of 32 players is hardcoded. Raising this limit in the base game could have lots of side effects for mods that rely on the limit being 32.

To support more than 32 players, we recommend to just write a mod that replaces Botpack.

**Comment by SeriousBuggie** [comment]
Mod XBots already allow you have more customized bots.
