### ISSUE TITLE
[469b] Localized booleans in User.ini

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1094]
[NexgenCC.GeneralConfig]
Settings[0]=(Name="ClientKey",Value="")
Settings[1]=(Name="ClientID",Value="")
Settings[2]=(Name="RunCount",Value="2178")
Settings[3]=(Name="FlashMessages",Value="True")
Settings[4]=(Name="AlreadyVisitedUrS",Value="True")
Settings[5]=(Name="iTSHUDType",Value="1")
Settings[6]=(Name="MapVoteWindowLoadScreens",Value="False")
Settings[7]=(Name="autoLogSpecialEvent",Value="True")
Settings[8]=(Name="enablePlayernameHUD",Value="True")
Settings[9]=(Name="EnableStartCountDown",Value="True")
**Settings[10]=(Name="HUDSettings",Value="CCount=3,CSize=2,CColor=3,OCount=5,OSize=2,OColor=7,useUTHUDColor=Faux")**
Settings[11]=(Name="ShowPlayerLoc",Value="True")
Settings[12]=(Name="UseNexgenHUD",Value="True")
Settings[13]=(Name="TeamName",Value="MHA")
Settings[14]=(Name="KillMessages",Value="True")
Settings[15]=(Name="AutoSSNormalGame",Value="True")
Settings[16]=(Name="ShowPingStatusBox",Value="False")
Settings[17]=(Name="ShowTimeStatusBox",Value="False")
**Settings[18]=(Name="EnableGoodLuckWarrior",Value="Vrai")**
Settings[19]=(Name="PlayEndGameMusic",Value="True")
Settings[20]=(Name="AutoSSMatch",Value="Faux")
Settings[21]=(Name="",Value="")
Settings[22]=(Name="",Value="")
Settings[23]=(Name="",Value="")
Settings[24]=(Name="",Value="")
Settings[25]=(Name="",Value="")
Settings[26]=(Name="",Value="")
Settings[27]=(Name="",Value="")
Settings[28]=(Name="",Value="")
Settings[29]=(Name="",Value="")
Settings[30]=(Name="",Value="")
Settings[31]=(Name="",Value="")
Settings[32]=(Name="",Value="")
Settings[33]=(Name="",Value="")
Settings[34]=(Name="",Value="")
Settings[35]=(Name="",Value="")
Settings[36]=(Name="",Value="")
Settings[37]=(Name="",Value="")
Settings[38]=(Name="",Value="")
Settings[39]=(Name="",Value="")
Settings[40]=(Name="",Value="")
Settings[41]=(Name="",Value="")
Settings[42]=(Name="",Value="")
Settings[43]=(Name="",Value="")
Settings[44]=(Name="",Value="")
Settings[45]=(Name="",Value="")
Settings[46]=(Name="",Value="")
Settings[47]=(Name="",Value="")
Settings[48]=(Name="",Value="")
Settings[49]=(Name="",Value="")
Settings[50]=(Name="",Value="")
Settings[51]=(Name="",Value="")
Settings[52]=(Name="",Value="")
Settings[53]=(Name="",Value="")
Settings[54]=(Name="",Value="")
Settings[55]=(Name="",Value="")
Settings[56]=(Name="",Value="")
Settings[57]=(Name="",Value="")
Settings[58]=(Name="",Value="")
Settings[59]=(Name="",Value="")
Settings[60]=(Name="",Value="")
Settings[61]=(Name="",Value="")
Settings[62]=(Name="",Value="")
Settings[63]=(Name="",Value="")

he game set " Vrai instead of "True" and the setting is not taking in counpt

**Comment by stijn-volckaert** [comment]
There are two separate issues here, but neither of them are bugs:
1. If you save the configuration of an object that has array properties, UT will save the entire array, including empty entries. That is why you're seeing lots of empty Settings lines here.
2. Boolean values get localized when you save them to a config. It looks like some of your settings were saved by a UT server/client that has its locale set to 'frt'. In this case, all of the following values represent true: "1", "true", "vrai". Similarly, all of the following represent false: "0", "false", "faux". The only problem here is that you cannot share your ini with non-french clients/servers because the only universal values for booleans are 0,1,true, and false.

Feel free to comment on or reopen the issue if I'm missing something here.

**Comment by Letylove49** [comment]
if you want to reproduce this  try tp set your game with the frt localized file and go to a server who use Nexgen  and try o change the option flash message an reconnect to see if your setting has been taken . If tha work for you that will be i  must probaly rinstalle  ut since the the 436 version en try to set thet patch 469b again to see if the problem still or not.

**Comment by SeriousBuggie** [comment]
Not able reproduce.

Steps:
1. Change language to frt
2. Connect to nexgen server.
3. Toggle flash new message in nexgn hud.
4. reconnect to server.
5. repeat last two steps again.

No any flaws.
v469c RC6

**Comment by Letylove49** [comment]
Have you copy the frt file to your system folder  for dot the test ?


ok i have make a new install of UT in 436 and that fixe the issue. ( i can't test the 469cRC6 because this version has not been released to the public  for the moment.

**Comment by SeriousBuggie** [comment]
No. I have frt files in my SystemLocalized folder. And I see most labels in french.

You can test v469cRC4 latest public RC.

**Comment by stijn-volckaert** [comment]
Could you come to our [Discord ](https://discord.com/invite/thURucxzs6) server and highlight AnthraX please?

**Comment by Letylove49** [comment]
are on  your discord tonight  21h00  Paris-time ? i can't come before tonight i have not time. ( my nick will be Shado)

**Comment by Letylove49** [comment]
this issue is fixed now.
