### ISSUE TITLE
[436-469c]  AutoTaunt doesn't work Online

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1096]
AutoTaunt doesn't'work correctly online

**Comment by thiagoobr** [comment]
Not to mention that the normal taunt is not stopping the other taunt, we can hear 2 at the same time

**Comment by stijn-volckaert** [comment]
I just tested this on 469c, but couldn't confirm the bug. Keep in mind that:
- There's a global limit of one auto-taunt per second
- Auto-taunts generate a voice message, but no text messages in chat
- The game doesn't generate auto-taunts when the killer uses a weapon that inflicts the 'gibbed' DamageType (e.g., the instagib rifle)
- Players can choose not to receive auto-taunts
- Gametypes can disable auto-taunts
