### ISSUE TITLE
[469c-RC6] Crash on map with broken reach specs

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1097]
Reproduce:
1. Start map https://unrealarchive.org/maps/unreal-tournament/monster-hunt/M/mh-mg-monopolymonstersfixed2_e38955fa.html
2. Add few bots.

Expected result: No crash.
Actual result: Crash.

Reason: Broken reachspecs (none):
```
ScriptLog: PathNode69
    upstreamPaths[0] = 68 (None, MyLevel.PathNode69, 1, 364)
    Paths[1] = 924 (MyLevel.PathNode69, None, 1, 364)
ScriptLog: PathNode70
    PrunedPaths[2] = 935 (MyLevel.PathNode70, None, 1, 707)
ScriptLog: PathNode107
    PrunedPaths[4] = 1338 (MyLevel.PathNode107, None, 1, 746)
ScriptLog: PathNode108
    upstreamPaths[1] = 138 (None, MyLevel.PathNode108, 1, 394)
    Paths[1] = 1349 (MyLevel.PathNode108, None, 1, 394)
ScriptLog: PathNode109
    upstreamPaths[2] = 139 (None, MyLevel.PathNode109, 1, 134)
    Paths[2] = 1358 (MyLevel.PathNode109, None, 1, 134)
ScriptLog: PathNode110
    PrunedPaths[3] = 1364 (MyLevel.PathNode110, None, 1, 456)
ScriptLog: PathNode111
    PrunedPaths[3] = 1370 (MyLevel.PathNode111, None, 1, 807)
ScriptLog: PathNode122
    PrunedPaths[1] = 1429 (MyLevel.PathNode122, None, 1, 732)
ScriptLog: PathNode123
    upstreamPaths[0] = 83 (None, MyLevel.PathNode123, 1, 380)
    Paths[0] = 1435 (MyLevel.PathNode123, None, 1, 380)
```

Wokaround: rebuild paths.

Solution: in `FSortedPathList::expandAnchor` make check against Null in spec:

`if ( spec->End && spec->Start && spec->supports(iRadius, iHeight, moveFlags) )`

**Comment by an-eternity** [comment]
It seems v469c final release will have this crash not fixed, so nothing left for now but to apply a runtime workaround that overwrites invalid paths by "-1".

**Comment by SeriousBuggie** [comment]
Another way of fix. 

In place were we validate and fix navigationpoint chain, need check and fix reachspecs too.
There few ways. 
1. Make instead of null same point as second point, set distance to infinite, and size to zero. 
2. Also this reachspec can be erased, and link to it set -1. Need only store list of erased specs, for reset other usages.
3. Or not reset it, but just reset any link to wrong reachspec.

1 and 2 or 3 can be combined.
