### ISSUE TITLE
[469c-RC4] UMOD installation on linux

### ISSUE THREAD

**Issue by groundflyer** [OldUnreal/UnrealTournamentPatches#1098]
There is no way to install *.umod files on linux.

- ucc-bin-amd64 doesn't create files with updateumod command.

- umodpack is unmaintained and doesn't work.

Can we solve this problem?

Thanks.

**Comment by uralets** [comment]
A fixed umodpack here you go
[umodpack.tar.gz](https://github.com/OldUnreal/UnrealTournamentPatches/files/9831343/umodpack.tar.gz)

**Comment by stijn-volckaert** [comment]
updateumod is not the most user-friendly commandlet, but it does work for me on AMD64. Keep in mind that the default output path for extracted files is ~/.utpg/System on Linux systems. Example:

```
➜  System64 git:(master) ✗ ls -al ~/.utpg/System 
total 120
drwx------ 2 stijn stijn  4096 Oct 23 03:58 .
drwx------ 9 stijn stijn  4096 Aug 11 02:03 ..
-rw-rw-r-- 1 stijn stijn  1213 Oct 23 03:56 ucc.log
-rw-rw-r-- 1 stijn stijn   917 Aug 11 02:54 udemo.ini
-rw-rw-r-- 1 stijn stijn 77193 Oct 13 07:42 UnrealTournament.ini
-rw-rw-r-- 1 stijn stijn  8532 Oct 13 07:42 UnrealTournament.log
-rw-rw-r-- 1 stijn stijn 16316 Oct 13 07:42 User.ini
➜  System64 git:(master) ✗ ./ucc-bin-amd64 updateumod ~/GameDev/NeoCairo-v300.umod extract TO-Temple.utx
WARNING: using preference directory: /home/stijn/.utpg/System/
WARNING: Using system ini file: /home/stijn/.utpg/System/UnrealTournament.ini
WARNING: Using user ini file: /home/stijn/.utpg/System/User.ini
=======================================
ucc.exe: UnrealOS execution environment
Copyright 1999 Epic Games Inc
=======================================

Executing Class Editor.UpdateUModCommandlet
Loading Archive: /home/stijn/GameDev/NeoCairo-v300.umod
Saved TO-Temple.utx
➜  System64 git:(master) ✗ ls -al ~/.utpg/System                                                        
total 912
drwx------ 2 stijn stijn   4096 Oct 23 03:58 .
drwx------ 9 stijn stijn   4096 Aug 11 02:03 ..
-rw-rw-r-- 1 stijn stijn 808944 Oct 23 03:58 TO-Temple.utx
-rw-rw-r-- 1 stijn stijn   1444 Oct 23 03:58 ucc.log
-rw-rw-r-- 1 stijn stijn    917 Aug 11 02:54 udemo.ini
-rw-rw-r-- 1 stijn stijn  77193 Oct 13 07:42 UnrealTournament.ini
-rw-rw-r-- 1 stijn stijn   8532 Oct 13 07:42 UnrealTournament.log
-rw-rw-r-- 1 stijn stijn  16316 Oct 13 07:42 User.ini
```

You can add ```-nohomedir``` to your ucc command line to extract to the current directory instead:

```
➜  System64 git:(master) ✗ ./ucc-bin-amd64 updateumod ~/GameDev/NeoCairo-v300.umod extract TO-Temple.utx -nohomedir
```

Again, this is not the most user-friendly installation experience, but the commandlet should work just fine.

**Comment by uralets** [comment]
> Keep in mind that the default output path for extracted files is
> ~/.utpg/System on Linux systems.

I was wondering, why ucc-bin cannot be instructed to use the
installation path instead. eg for extracting compressed maps

**Comment by stijn-volckaert** [comment]
> Keep in mind that the default output path for extracted files is ~/.utpg/System on Linux systems.
> I was wondering, why ucc-bin cannot be instructed to use the installation path instead. eg for extracting compressed maps

You can add -nohomedir as a command line parameter to do that
