### ISSUE TITLE
[469a] XOpenGL displays one detail texture layer instead of two

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#11]
**XOpenGL:**
![Shot00000](https://user-images.githubusercontent.com/10724977/94029069-1b805000-fdc5-11ea-9a2e-36498e79445c.jpg)

**D3D9:**
![Shot00001](https://user-images.githubusercontent.com/10724977/94029118-26d37b80-fdc5-11ea-8fe0-b5dbe13f457c.jpg)

**Comment by CacoFFF** [comment]
The multiple layers of detail textures was something that came out of the UTGLR Renderers, and we've only kept it on those because it's already there.
It's likely that more updated versions of UTGLR OpenGL may have this gone too.

**Comment by sn260591** [comment]
> The multiple layers of detail textures was something that came out of the UTGLR Renderers

But it originally appeared in D3D7.

What were the reasons why it was decided to abandon multilayer detail textures?

**Comment by mkardi** [comment]
I confirm same XOpenGL behavior in 469c-RC2
Since issue was opened almost 2 years ago I am curious if there is any plan to fix it?

**Comment by stijn-volckaert** [comment]
The release version of 469c will enable detail textures for all renderers that support them
