### ISSUE TITLE
graphics bug 

### ISSUE THREAD

**Issue by ghost** [OldUnreal/UnrealTournamentPatches#1103]
Main Menu logos look cut up i guess i am on version 469-c aug 10 2022 preview of Unreal Tournament 1999

![UnrealTournament_hQE3QqpTgB](https://user-images.githubusercontent.com/114490042/198891352-c81d3e20-b575-431d-847b-e7f7eb61b080.png)
![UnrealTournament_A2K8hq37os](https://user-images.githubusercontent.com/114490042/198891360-443ac9cc-6f43-4350-a277-29532de0ee48.jpg)

**Comment by SeriousBuggie** [comment]
Please check it on latest release.

**Comment by freesoftwarerocks** [comment]
all good now
