### ISSUE TITLE
[469c] Armor points issue after picking up thighpads & body armor after shieldbelt

### ISSUE THREAD

**Issue by darkbarrage99** [OldUnreal/UnrealTournamentPatches#1105]
I understand that there's supposed to be a fix to show the actual number of total armor points, but I'm getting this instead and I haven't been able to find anything regarding the subject.  

body armor + thighpads = 150
shieldbelt alone = 150
shieldbelt, followed by body armor + thighpads = 151
shieldbelt, body armor and thighpads (151), followed by another shieldbelt = 150

![armorissue](https://user-images.githubusercontent.com/117120777/199104864-d29851d2-dece-4df5-b671-24a423db3dfe.jpg)

I'm using the most current version of Windows 10.  No Mutators, stock maps.

**Comment by SeriousBuggie** [comment]
This is always be in such way. You just not see it, because HUD armor point be limited to 150. All above show as a50. Now it show real value, so you can see it.

**Comment by SeriousBarbie** [comment]
I think he means the different values depending of the order picking up armor. The reason is that the shieldbelt removes all other armor when it is picked up:

```
function PickupFunction(Pawn Other) {
...
	// remove other armors
	for ( I=Owner.Inventory; I!=None; I=I.Inventory )
		if ( I.bIsAnArmor && (I != self) )
			I.Destroy();
}
```
AFAIK that has not changed since v436.

**Comment by darkbarrage99** [comment]
> This is always be in such way. You just not see it, because HUD armor point be limited to 150. All above show as 150. Now it show real value, so you can see it.

> Yes. This not changed since v436. And there complicated system about that. result of which depends of order of pickup items, and how many point on them.
> 
> It is well know game "feature" which used by pro gamers. They able get 199 armor AFAIK.

gotcha.  so the 151 total is still incorrect?

**Comment by SeriousBuggie** [comment]
No. It is still correct. 
I can explain by each case:

1. body armor + thighpads = 150 -- just simple sum
2. shieldbelt alone = 150 
3. shieldbelt, body armor and thighpads (151), followed by another shieldbelt = 150 -- last shieldbelt destroy any other armors
#461 
so it is just shield. And it same as 2 case
4. shieldbelt, followed by body armor + thighpads = 151
There happens next:
When you pickup armor it found shield in inventory. After that apply next code:
```unrealscript
	Copy = Super.SpawnCopy(Other);
	S = Other.FindInventoryType(class'UT_Shieldbelt');	
	if ( S != None )
	{
		Copy.Charge = Min(Copy.Charge, S.Default.Charge - S.Charge);
		if ( Copy.Charge <= 0 )
		{ 
			S.Charge -= 1;
			Copy.Charge = 1;
		}
	}
```
This mean: 
search shield. 
If it found calculate how shield damaged.
If it damaged, set armor amount of this amount.
If not damaged (0 difference) just damage shield to 1 point and add 1 point armor.

So now you have 149 shield + 1 armor.

After that you pickup pads.
Pads use same code as above. But there shield damaged.
So it goes to add pads with 1 amount.

So finally you get shield 149 + armor 1 + pads 1 = 151.

All of this code is look like poorly managed attempt not allow stacking armor and shield. Which bad work in some cases.

Now it is turn to feature, used by pro gamers.
You can take shield, damage it to 100-50 points. After take pads and armor (order not matter) and there be 200 total point of armor.

In best case it 100 shield + 50 armor + 50 pads.

**Comment by darkbarrage99** [comment]
Wow that is bonkers.  Learn something new every day in UT lol.  Thanks for the explanation!

**Comment by stijn-volckaert** [comment]
Buggie's explanation is correct.
