### ISSUE TITLE
[469c Release] Accessed None 'ParentWindow'

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#1108]
Playing several DM maps off-line, I found the following ScriptWarning in the log - have never seen this warning before :

ScriptWarning: UWindowComboList Transient.UWindowComboList12 (Function UWindow.UWindowComboList.FocusOtherWindow:002A) Accessed None 'ParentWindow'

It looks like it happened when I ceased playing the first map I played (the game hadn't 'ended') and opened the menu with the list of DM maps to start another (the second) map.  There was no similar ScriptWarning when I ceased playing the second map and opened the menu to start a third map. 

Using OpenGL renderer in the WIndows XP version of 469cRelease running in Windows 5.1.2600 in a Wineskin wrapper on a Mac. 

Presumably this is not a significant issue (did not have any impact that I noticed) but I thought I would raise it as I have not seen it before in 436, 451 and any of the previous 469 versions.

**Comment by SeriousBuggie** [comment]
`UWindow.UWindowComboList.FocusOtherWindow` not changed in v469c.

**Comment by OjitroC** [comment]
So it's just a random happening - could happen in any version of UT?

**Comment by SeriousBuggie** [comment]
Can't say for sure. Maybe it caused by another change, Need reproduce issue for say something.

Need exact steps for reproduce. Can you provide such steps?

Currently I not get full way.
"first map"? it is map list in rotation list?

Or you just open "start new practice session"?

Possible video of reproduce can be handful.

**Comment by OjitroC** [comment]
I've played quite a few maps since I posted the issue - playing three or four in a session before exiting the game - playing off-line, open 'start new practice session', play a map for a while, press escape, open the map list, choose another map and play - these are the basic steps - it looks from the log as though the ScriptWarning appeared when pressing escape to pause the map I was playing and then opening the map list to choose another map - but I haven't had the ScriptWarning again 

I don't think that I can set out any steps to reproduce the warning.  I'll close the issue but if I get the Script Warning again I'll reopen it and try to get a clearer idea of what produced the warning.
