### ISSUE TITLE
[469a][QoL] Make weapon FOV fixed (like it is in Unreal 227)

### ISSUE THREAD

**Issue by AtifArshad1995** [OldUnreal/UnrealTournamentPatches#111]
In Unreal 227, weapon FOV does not change by changing FOV or resolution widescreen ratio. This feature would be great to have in UT as some weapons block view too much at high FOV (like above 110 FOV).

**Comment by Xanious** [comment]
UT99 is the only unreal engine game that seems to have this weird viewmodel issue. Deus Ex and Unreal 1 don't have it at all. Not only that but apparently its possible to get rid of this in UT99 via custom playerpawns. I can't imagine an option to disable this causing issues. For reference, Unreal 1 is top, UT99 is bottom.  Both these screenshots were taken at FOV 120

![2021_1_13_16_16_33_380-nyleve](https://user-images.githubusercontent.com/77414568/104512351-0f124400-55bc-11eb-8239-1ed3a4652477.png)
![Shot0041](https://user-images.githubusercontent.com/77414568/104512354-11749e00-55bc-11eb-8679-13768adf5612.png)

**Comment by Calinou** [comment]
I can still reproduce this on 469c RC2 (Linux 64-bit).

Hiding the weapon model in the game settings makes the game much more playable with high FOV. I wish there was a per-weapon crosshair option so I didn't have to look at the weapons bar to see my current weapon though :slightly_smiling_face:

**Comment by an-eternity** [comment]
Unfortunately, there is no simple solution for this problem...
HUD scaling in UT has been implemented with no assumption some days in future it will be used with wide aspect ratios and high screen resolutions.
Moreover, a lot of mods have copy-pasted/inherited this problem.

Even if this is going to be fixed in the next patch versions (which is highly unlikely), all of those mods have to be rewritten as well (which is also unlikely is going to happen).

**Comment by AtifArshad1995** [comment]
That really sucks.

I don't know how feasible this is, but maybe if there is a toggle option that forces the weapon viewmodel to how it is positioned at 4:3 resolution/90 FOV?

Or how the [foxWSFix-UT99 mod](https://github.com/alexstrout/foxWSFix-UT99) does things?

**Comment by stijn-volckaert** [comment]
I have merged Masterkent's [proposed implementation](https://ut99.org/viewtopic.php?t=15862) for a widescreen FOV fix and added some menu options to configure the fix:
![afbeelding](https://github.com/OldUnreal/UnrealTournamentPatches/assets/10390414/ef679950-94b3-4b8e-8f78-8087994fb383)

This will be available in an upcoming 469e preview build
