### ISSUE TITLE
[469c] XOpenGL corona rendering issues

### ISSUE THREAD

**Issue by senneschall** [OldUnreal/UnrealTournamentPatches#1112]
Freshly installed UT GOTY with Patch 469c applied, no settings changed at all, so default rendering settings are kept. Specs can be found in the log file: 
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/9941890/UnrealTournament.log)

The coronas have issues, seems like there are lines where there are edges on the world:
![20221104_xopenglrenderingerror](https://user-images.githubusercontent.com/14364389/200072945-a3a95cef-90ad-4449-a698-e8eda5cb5aa8.jpg)

You see on the bottem right, those lines don't appear on the lantern when it doesn't show coronas. On the other lanterns the lines are visible. Those lines seem oddly familiar to me, i suspect those are antialiasing artifacts. Disabling AA removes those lines

**Comment by SeriousBuggie** [comment]
Duplicate of #965

**Comment by senneschall** [comment]
Difference to #965 is: this is a screenshot on Win10 with the AMD drivers, not the mesa drivers on Linux.

**Comment by SeriousBuggie** [comment]
Look like AMD screwed drivers on all platforms. Weird.

**Comment by an-eternity** [comment]
This issue is platform-independent, which has already been mentioned in #965, as well as that no workarounds will be applied because it is up to driver developers to fix it.

As said in #965, Mesa driver has already fixed this issue.
It would be useful to provide information here whether it is also fixed in the latest driver version 22.10.3 for Windows...

**Comment by mkardi** [comment]
As a workaround you can set following value to false in UnrealTournament.ini

[OpenGLDrv.OpenGLRenderDevice]
**NoAATiles=False**

**Comment by senneschall** [comment]
Driver version 22.10.3 resolves the issue (the screenshots were made with 22.08.2)

Thanks for all the help!
