### ISSUE TITLE
[469c] When clicking new map button does not prompt to save existing map

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#1114]
If you have spent hours on a map and accidentally click on the New Map button (top left)

The editor does not prompt to save existing map .so all work is lost.

Dangerous.

**Comment by SeriousBuggie** [comment]
Only if you have empty undo history. Like build geometry/paths/lights recently. on other cases it is ask.

**Comment by SeriousBarbie** [comment]
That _I-have-been-modified-since-last-save_ flag still seems broken. Sometimes UnrealEd ignores changes (in case above), in other cases UnrealEd asks for saving a just saved map when closing.

**Comment by SeriousBuggie** [comment]
No such flag.
As flag used fact empty undo buffer or no. And undo buffer erased on any build. And not altered when you rebuild scripts on map.

**Comment by SeriousBarbie** [comment]
Thanks for the explanation. "flag" is meant here not as variable but more as a modified state.
My (and probably most user ones) expectation is that when map's representation in memory is different from persistent stored representation it should be indicated by such a "modified" flag or state, and consequently reflect this in enabling/disabling saving commands and asking for save on closing if modified.

**Comment by no0nehere** [comment]
To fix , unrealed should ask to save your work regardless of already been saved or not if user clicks on the New Map button.

It always asks to save if you Load a Map.. so why not if you wish to create a new one?

**Comment by SeriousBuggie** [comment]
It behave exactly same when you open new map or when you load any existing map.
Both ways is bugged in same way. And both not ask in some cases (not all time).

**Comment by stijn-volckaert** [comment]
Confirmed, but this will take a while to fix.

**Comment by SeriousBuggie** [comment]
Fixed for 469e. If this still happen for you, please make new issue with exact steps for reproduce.
