### ISSUE TITLE
[469c] Block bots / pawns from seeing through movers

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#1118]
I've built a map which has 2 large movers (exploding glass).

I have 2 of these in DM-Boundaries_noMonsters map.

What happens is Bots/Monsters behind the movers try attacking each other.

Can we make it so that these pawns (Don't) see each other UNTIL the movers have moved out of the way?

**Comment by SeriousBuggie** [comment]
Duplicate of #559

**Comment by stijn-volckaert** [comment]
Confirmed duplicate
