### ISSUE TITLE
UnrealScript | SourceCode request

### ISSUE THREAD

**Issue by oreleraki** [OldUnreal/UnrealTournamentPatches#1120]
I'm building UScript packages and it will greatly help if the current code on github\releases will available in it's `.uc` form.
I have Visual Studio Code with Intellisense and I would rather use the newest form on source code for Intelli.

**Comment by SeriousBuggie** [comment]
What about SDK archive? 
![img](https://user-images.githubusercontent.com/70026933/201480310-3c28a805-fe39-43d0-a08f-6d06435313e9.png)
It is not what you looking for?

**Comment by oreleraki** [comment]
Sorry my bad. Thanks for the quick response.
