### ISSUE TITLE
Cant edit more than the first 16 bots 

### ISSUE THREAD

**Issue by Zentor98** [OldUnreal/UnrealTournamentPatches#1123]
Hi 
i dont know if this is intended or a bug
but whenever i want to edit a bot, i can only edit the first 16 and can only play with those 16 
 
in UT99 version 436 i can edit all 32 of them

**Comment by SeriousBuggie** [comment]
If you use 16 bots (or 8, or 3) you able tune only them.
For make able tune all 32 bots you need set count to 32, or check mark `Random Order`.

**Comment by Zentor98** [comment]
thx
i somehow thought i had that option ticked on 
i didnt
