### ISSUE TITLE
[469c]  Sound Browser won't assign sounds in Groups whose name is enclosed by [ ] square brackets

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#1124]
A variation on the ( ) bug now fixed.  Steps to reproduce

1 Download and install the Shang voicepack from http://medor.no-ip.org/index.php?dir=Voices/&file=romkaboutervoicepack.zip
2 Open up the Editor - create a subclass of a pawn - say SkaarjTrooper
3 In the Sound Browser open Shang.uax
4 Open up the SkaarjTrooper Properties -> Sounds
5 In the Sound Browser select any of the sounds in any of the groups in Shang.uax
6 Try to assign this sound to any of the SKTrooper sounds, say Acquire or Threaten

I am unable to assign a sound - on trying the 'sound space' simply reverts to None.

All four Groups of sounds in Shang.uax have names enclosed by square brackets [ ] - I assume that this is the issue as I have not any other issues assigning sounds in UEd in 469c Release with the ( ) issue having now been fixed. 

Note - this voicepack is in a umod from which it will need to be extracted - I do this manually but use whatever method is appropriate.

**Comment by OjitroC** [comment]
I forgot to add that I am able to assign sounds from Shang.uax when using UEd in 436 so it does appear to be a 469c issue rather than an issue with the voicepack.

**Comment by SeriousBuggie** [comment]
Uploaded [Shang.uax](https://github.com/OldUnreal/UnrealTournamentPatches/files/11581676/Shang.zip) here for not mess with slow download and umod file.

**Comment by stijn-volckaert** [comment]
We will start testing a fix for this in the next 469d preview

**Comment by SeriousBuggie** [comment]
Fixed on v469d preview 9
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/afdcb61e-3f89-42cf-8184-8dcfcdd12057)
