### ISSUE TITLE
[469c] Linux 64: Custom paths no longer work

### ISSUE THREAD

**Issue by shrimpza** [OldUnreal/UnrealTournamentPatches#1127]
After upgrading to 469c and using the 64bit binary, it seems the game no longer recognises my custom content paths as defined in `UnrealTournament.ini`.

For example, I'm using the following:

```ini
[Core.System]
...
Paths=../System/*.u
Paths=../Maps/*.unr
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Paths=../Others/System/*.u
Paths=../Others/Maps/*.unr
Paths=../Others/Textures/*.utx
Paths=../Others/Sounds/*.uax
Paths=../Others/Music/*.umx
...
```

Where custom content goes into the `Others` directory.

Booting up 469b 32bit, everything shows up. Booting up 469c 64bit, only the stock content is recognised.

Nothing in the log file seems to indicate errors or anything.

[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/10099585/UnrealTournament.log)

I cannot verify with 469c 32bit, since that no longer seems to launch, but that's a separate bug for another day.

I have also confirmed this `.ini` file is the one in use, since changing parameters like the `LocalMap` or renderer reflect on next startup.

**Comment by SeriousBuggie** [comment]
You sure used this config? 64-bit version located in folder System64 use own config in System64, not one which in System.

**Comment by shrimpza** [comment]
> You sure used this config? 64-bit version located in folder System64 use own config in System64, not one which in System.

Yes, as I stated in my report, I verified that changes to this INI file show changes in game indicating that it's being used.

My `UnrealTournament.ini` is located in `~/.utpg/UnrealTournament.ini` where it has always been, not in the System directory.

**Comment by shrimpza** [comment]
I did some additional checking. It looks like maps for standard gametypes do in fact appear from the paths specified.

I've also tried adding a `System64` directory with the `.u` and `.int` content within my `Others` directory, and adding that to the `Paths`, but that doesn't work either (though it shouldn't be necessary since the `Paths` reference the `System` directory only).

It seems it's just not finding any `.int` files outside of the standard `System` directory.

**Comment by stijn-volckaert** [comment]
This is probably a side effect of the localization changes we made for 469c. Localization files now get loaded from the ```../SystemLocalized/<your language>/``` and ```../System/``` folders by default. You can override these paths in the ini. Under [Core.System], you can add:
```
LangPaths=../SystemLocalized/<lang>/*.<lang>
LangPaths=*.<lang>
```

**Comment by shrimpza** [comment]
Cool, that seems to work!

I added these (not sure if `<lang>` was intended as a literal, but I just added literal `int`):

```
LangPaths=../SystemLocalized/int/*.int
LangPaths=../Others/System/*.int
```

I assume in previous versions it implicitly looked for localisation/int files alongside the `*.u` paths or something? I'm just curious to know why/how it worked before.

I prefer the new explicit configuration even if in this scenario it was a bit of a gotcha.

Thanks!

**Comment by NeonKnightOA** [comment]
Before every localization file was located in System. For some things it made things convenient, but we've planned 16 languages, 11 of which are already implemented (v469d will come with Greek, v469c comes with Russian, Portuguese, Catalan, German and Dutch in addition to the MULTI5 languages). Every language is roughly 116-155 files long, depending on version and official stuff installed. Multiply that by amount of languages. Too many files, and some OSes have lots of troubles with folders with +1000 files.

So now all .int files go in ´/SystemLocalized/int´ and every language has its dedicated folder. IMHO more convenient this way.
