### ISSUE TITLE
[469c] amp; in menu (ptt translation)

### ISSUE THREAD

**Issue by UBIr4** [OldUnreal/UnrealTournamentPatches#1129]
![ut amp](https://user-images.githubusercontent.com/93230125/207198316-01f1b78d-b18a-4343-aa3a-703f6af632b2.jpg)

Fonts ptt ok, but appears "amp;" in menu.

**Comment by stijn-volckaert** [comment]
Confirmed. This will be fixed in 469d. In the meantime, you could apply the fix yourself using this pull request as a guide:
https://github.com/NeonKnightOA/unreal-localization/pull/75

**Comment by NeonKnightOA** [comment]
It's already fixed in PR #1151.
