### ISSUE TITLE
UT436 and 469 Bad colors textures   on a Map  

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1133]
that should be:

![Shot00000](https://user-images.githubusercontent.com/110738647/208174785-71abec69-9df0-4075-9bb4-bd28b512cad5.png)

Result :

![Shot00001](https://user-images.githubusercontent.com/110738647/208174865-dbed3386-489a-4c29-9e87-905e0cb5c222.png)

 somoene have a idéa  why i got this ?   this is vers strange

**Comment by SeriousBuggie** [comment]
Any clues in log file? It look as textures not load, but used default texture instead.
Can you attach map here? With all necessary assets.

**Comment by Letylove49** [comment]
[DM-BloodyBlocks.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/10249124/DM-BloodyBlocks.zip)

here the map

**Comment by SeriousBuggie** [comment]
For me it fine. 

There used Lego.utx.
Ensure you not have other Lego.* files, like Lego.u, Lego.uax, Lego.umx and so on.

**Comment by Letylove49** [comment]
ok i have fund the problem:   i have a file Lego.u.  I have remove this file and this solve the problem . The map work fine now.
Thanks for your help.
