### ISSUE TITLE
[469c] Ued bug: When you try to import a texture and click "Cancel", whole texture package disappears.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1135]
1. Open texture browser and import any texture
2. Click Cancel
3. Whole texture package disappears

https://user-images.githubusercontent.com/58362332/208255750-51093f65-eaf3-4af9-9514-2b439d50897c.mp4

**Comment by SeriousBuggie** [comment]
It is called "select none", Not disappear. You still can select package in list.

**Comment by BerserkerBG** [comment]
Well yes, but it looks like it suddenly disappeared, which forces you to select it again from package list. But I can see how it can surprise or confuse regular users.
