### ISSUE TITLE
[469c] Ued issue: 2D Shape editor needs a proper working Cancel function

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1136]
Issue 1:
When you close (or accidentally close) the 2D Shape Editor, a prompt box appears if you want to save your 2D Shape or not. The problem with it is that it's missing a "Cancel" button. When you accidentally close the 2D Shape window it forces you to save the 2D Shape, so you will have to re-open it again from the File Browser.
![Screenshot_150](https://user-images.githubusercontent.com/58362332/208263282-770c47b3-0c98-4215-bb95-bd924770882f.png)

Issue 2:
When you close the 2D Shape editor and click on "Yes" from the Save prompt (as shown in the image above), the File Browser shows up so you can save your 2D Shape. But when you click on cancel, you can't recover your 2D Shape and it is gone forever:
![Screenshot_151](https://user-images.githubusercontent.com/58362332/208263652-4f4a4816-dbba-405f-b4c4-0a52a2038106.png)

**Comment by SeriousBuggie** [comment]
No need such button. In fact no need change anything in current flow when editor destroyed. Need destroy only on UnrealEd close. So if you not save in 2d editor some stuff, you can ave it or discard, but not cancel UnrealEd closing.

When you click close button it must be hidden like other browsers do, with keep you work. And when you later goes bring it again - it be here. Same as for minimized state. As requested in #1137.

So both issues can be closed with one change - not destroy editor on close, just hide. And on bring back, not recreate it, just bring to front/show again.
