### ISSUE TITLE
[469c] Ued issue: Minimized Ued windows stack are covering the console area

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1138]
Minimized windows stack in Ued are getting in the way of using the bottom left area of Ued.

1. Open Texture browser
2. Open 2D Shape editor
3. Open Script editor
4. Minimize all windows
5. They cover the entire bottom left area

![Screenshot_175](https://user-images.githubusercontent.com/58362332/208265226-90fb7ccd-1128-42dc-bd65-a1c8509445f1.png)

There is a lot of free space on the bottom right, the minimized windows could stack from bottom right to left.

**Comment by SeriousBuggie** [comment]
yea. It is annoying. I just drag them in minimized state, little up. It remember position for next minimize.

**Comment by BerserkerBG** [comment]
It could be nice to remember the window positions after exit.

**Comment by SeriousBuggie** [comment]
If you use different screen size or two screen with move editor between screens it can be problem.
