### ISSUE TITLE
[469c] Ued Issue: Minimized windows in Ued are not recognizable (modern Windows theme)

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1139]
Minimized windows in Ued (such as Texture browser, Actor browser, etc..) are not recognizable when they are minimized. This is because of the modern Windows Theme, which I'm using (Windows 10). Apparently in older classic Windows themes, the minimized windows have labels and you can easily recognize them.

Here is how it looks like on modern Windows theme, there are no labels:
![Screenshot_176](https://user-images.githubusercontent.com/58362332/208265514-6fcfd49c-b407-4c91-8d3c-dfc3fab381d6.png)

Here is how it looks like on classic theme, you can see each window is labeled and you can easily recognize what you have minimized:
![Screenshot_177](https://user-images.githubusercontent.com/58362332/208265650-27a1a867-7e91-46df-80e9-b753b81dc0ac.png)

Lets think of a way to solve this for the modern theme users, what can we do to make the minimized windows easier to recognize?

**Comment by SeriousBuggie** [comment]
Possible implementation:
Win10.
Before:
![img](https://cdn.discordapp.com/attachments/820604832153993267/1059072675772911616/image.png)
After:
![img](https://cdn.discordapp.com/attachments/820604832153993267/1059072442955468800/image.png)
Maximized view is same.
![img](https://cdn.discordapp.com/attachments/820604832153993267/1059073032313917481/image.png)
