### ISSUE TITLE
[469c] Ued Enhancement: Add Rotation info in Surface Properties

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1140]
Rotation info in surface properties could be a nice feature.

![Screenshot_178](https://user-images.githubusercontent.com/58362332/208269844-707e80d8-f8ab-43b5-a89b-b1b198679b6d.png)

**Comment by SeriousBuggie** [comment]
Rotation not exists. Exists U and V. Vectors. If they located somehow you can see it as rotation or skew. It can be even not coplanar to surface. No way determine for all combination rotation. One vector can be rotated, when second - no.

**Comment by BerserkerBG** [comment]
Not possible
