### ISSUE TITLE
[469c] Tree9 has no Mesh

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1141]
```
class Tree9 extends Tree;

...
defaultproperties {
     Mesh=None
     CollisionRadius=15.000000
     CollisionHeight=39.000000
}

```

Although there exists a mesh "UnrealShare.Tree9M"

**Comment by SeriousBuggie** [comment]
Can't  be fixed without break network compatibility.
What can be done - new class in OldUnreal469d package.

**Comment by stijn-volckaert** [comment]
Correct. This is the result of a typo in the Tree9 source code. We tried to fix it in an earlier version of the patch but had to roll the fix back because it broke replication of Tree9 actors.
