### ISSUE TITLE
[469b] Ued Enhancement: Prevent "Show Selected Actors Only" from de-selecting your selected actors

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1142]
1. Open any map
2. Select actors
3. Click on "Show Selected Actors Only" ![Screenshot_179](https://user-images.githubusercontent.com/58362332/208679167-e84a10d2-d816-45ce-a448-483c28bd05aa.png)
4. Your actor selection is de-selected, so you will have to select your actors again

https://user-images.githubusercontent.com/58362332/208678943-ba47ef42-4020-4851-95e8-8f1e91482d93.mp4

As a side node, I would also like to point out that if you use "Show All Actors"  ![Screenshot_180](https://user-images.githubusercontent.com/58362332/208679667-0d426005-a996-4ef0-a6ae-89813bf481a0.png) to reveal all hidden actors, if you have a current selection while using it, the actors you've selected are not de-selected, which is the way it should be.

**Comment by SeriousBuggie** [comment]
Duplicate of #1039

**Comment by BerserkerBG** [comment]
Forgot about this one tnx buggie
