### ISSUE TITLE
[469c] Linux Release for ARMv8 architecture (aarch64)

### ISSUE THREAD

**Issue by jm2** [OldUnreal/UnrealTournamentPatches#1145]
With Apple Silicon Macs now having experimental OpenGL 2.x GPU hardware acceleration support under Asahi Linux, it'd be nice to have an AArch64 (ARMv8) release of UT. This would also benefit other ARMv8 devices, e.g. https://archlinuxarm.org/platforms/armv8

**Comment by stijn-volckaert** [comment]
We've had UT up and running on the raspberry pi 3b and 4 for a while now (although we've only tested armv7hf). Several features are missing, though, and performance is rather poor. I can check how well it runs on armv8
