### ISSUE TITLE
[469c] Ued Enhancement: Allow to use multiple [UserDefinedGroup] buttons.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1147]
![Screenshot_182](https://user-images.githubusercontent.com/58362332/209352930-67142816-d465-4d94-be2b-b73dbfd8652e.png)

Ued allows you to have a custom group list of buttons called [UserDefinedGroup] in UnrealEd ini. For reference, here is a short example of what it looks like:
```
[UserDefinedGroup]
NumButtons=3
Button0=Mirror X,MirrorX, ACTOR MIRROR X=-1
Button1=Mirror Y,MirrorY, ACTOR MIRROR Y=-1
Button2=Mirror Z,MirrorZ, ACTOR MIRROR Z=-1
```

The problem, is that you can do only one group and you are forced to clutter all of your extra buttons into that one group. It would be great if we can be able to make more groups and not just one.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/210200759-b307c99a-81e3-4a9a-8dc3-5ca5a3853921.png)
```ini
[UserDefinedGroup]
NumButtons=10
Button0=Align Camera on Selected Actor,AlignCam,CAMERA ALIGN
Button1=FaceDrag Mode,ModeFaceDrag,MODE FACEDRAG
Button2=Mover Key 0(Base),Key0,Actor KEYFRAME NUM=0
Button3=Mover Key 1,Key1,Actor KEYFRAME NUM=1
Button4=Mover Key 2,Key2,Actor KEYFRAME NUM=2
Button5=Mover Key 3,Key3,Actor KEYFRAME NUM=3
Button6=Mover Key 4,Key4,Actor KEYFRAME NUM=4
Button7=Mover Key 5,Key5,Actor KEYFRAME NUM=5
Button8=Mover Key 6,Key6,Actor KEYFRAME NUM=6
Button9=Mover Key 7,Key7,Actor KEYFRAME NUM=7

[UserDefinedGroup3]
NumButtons=9
Button4=Align Camera on Selected Actor,AlignCam,CAMERA ALIGN
Button2=FaceDrag Mode,ModeFaceDrag,MODE FACEDRAG
Button3=Mover Key 0(Base),Key0,Actor KEYFRAME NUM=0
Button1=Mover Key 1,Key1,Actor KEYFRAME NUM=1
Button6=Mover Key 2,Key2,Actor KEYFRAME NUM=2
Button8=Mover Key 3,Key3,Actor KEYFRAME NUM=3
Button0=Mover Key 4,Key4,Actor KEYFRAME NUM=4
Button7=Mover Key 5,Key5,Actor KEYFRAME NUM=5
Button5=Mover Key 6,Key6,Actor KEYFRAME NUM=6
```

Can be used UserDefinedGroup or UserDefinedGroupN where N is 1..9.
I think 10 sections more from enough.
If not it can be easy turned in bigger count.
