### ISSUE TITLE
UnrealEd not able handle files with path longer from 80 chars

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1148]
> "Warning: Failed loading package: Can't find file 'C:\Games\Steam\steamapps\common\Unreal Tournament\Textures\commandoskins_kits.u'" 
It's cutting off at .u rather than .utx. 

If count count of chars for `C:\Games\Steam\steamapps\common\Unreal Tournament\Textures\commandoskins_kits.u` it be 79 chars. 1 char reserved for null-terminator.

This come from UEditorEngine::SafeExec where located next code:
`TCHAR TempFname[256], TempStr[256], TempName[NAME_SIZE];`
`if( Parse( Str, TEXT("FILE="), TempFname, 80 ) )`
`if ( Parse( Str, TEXT("STARTBONE="), TempFname, 80 ) )`
`Parse( Str, TEXT("BONE="), TempFname, 80 ) )`
`Parse( Str, TEXT("FILE="), TempFname, 80 )`
`if( Parse( Str, TEXT("FILE="), TempFname, 80 ) )`

This effectively limit used path for load any file to 80 symbols, because any package loaded via `OBJ LOAD FILE=...`
Need fix this 80 limit to 256.

**Comment by stijn-volckaert** [comment]
Is this in 469c? We removed these size limits a long time ago.

**Comment by SeriousBuggie** [comment]
This code from HP2 v433. I not have code for v469c for check. If so issue can be closed. I think this issue appear on v469c. Possible I wrong.

Now check for v469c. 
`de_with_super_long_filename_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789_123456789.u` open fine form System dir.

v469c already fixed.
