### ISSUE TITLE
[469c] UTWindow Limits Upgrade

### ISSUE THREAD

**Issue by KAZY369** [OldUnreal/UnrealTournamentPatches#1150]
There is a mod, which is called WORM (Weapon Object Replacement Mod)
**WORM V1.90**
https://www.moddb.com/games/unreal-tournament/downloads/worm-v190
If you check the picture, each *.int files (plugins) are a weapon/ammo/pickup package which I made manually.
https://media.discordapp.net/attachments/227151487044681730/1056894872101068851/WORMSucks1.png?width=684&height=609
The problem is, when I open the mod there is a huge problem, because there is a limit for the window, and it can't load the files.
This is the *.log file message:
`ScriptWarning: WormOtherPage Transient.WormOtherPage1 (Function WORMmenu.WormOtherPage.Notify:000C) Accessed None 'WeaponAddBox'`
I you guys see, only one package is loaded, and the others are hidden.
https://media.discordapp.net/attachments/227151487044681730/1056894872570822687/WORMSucks2.png?width=1036&height=609
There is already a mod, called ModMenuExtension by Wormbo:
http://www.koehler-homepage.de/Wormbo/download/UT/ModMenuExtension111.zip

> The mod menu can become quite big when you have installed many mods. Sometimes it gets too large to fit on the screen. The mod menu extension ensures that every mod is visible by creating submenus when the list gets larger than the available space for displaying.
> Some players also have problems with the Payer Setup window not showing all of the installed models. The Mod Menu Extension comes with a fix for this problem.

I'm not a coder guy,  so the question is, is that possible to fix the UTWindow limits in the next patch update?

**Comment by smcv** [comment]
> Some players also have problems with the Payer Setup window not showing all of the installed models. The Mod Menu Extension comes with a fix for this problem.

Back in 2002 I released a mod with fixes for the Player Setup and Bot Setup windows, which overlaps with that: https://www.pseudorandom.co.uk/2002/paradox/ut/marginal/

I don't remember the full details of how it works, but full source code is included, and OldUnreal developers would be very welcome to scavenge fixes from there.

**Comment by SeriousBuggie** [comment]
I not see any limits in code of mutator for load int files. However, mutator affected by #1351, so if you have broken int file, it can stop load full mutators lisr.
This issue must be fixed in upcoming v469d RC.

Or maybe I got problem wrong and this related not to load int files.

**Comment by SeriousBuggie** [comment]
I even not sure if this good int file:
```ini
[PUBLIC]

//WEAPONS
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.ENFORCER2X,AWM-ENFORCER2X")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.UT_EIGHTBALL2,AWM-UT_EIGHTBALL2")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.ADVANCEDRIPPER,AWM-ADVANCEDRIPPER")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.RIPPER2,AWM-RIPPER2")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.DISPERSIONGUN,AWM-DISPERSIONGUN")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.MULTIROCKETLAUNCHER,AWM-MULTIROCKETLAUNCHER")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.UT_BIORIFLE2,AWM-UT_BIORIFLE2")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.ADVANCEDSHOCKRIFLE,AWM-ADVANCEDSHOCKRIFLE")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.SHOCKRIFLE2,AWM-SHOCKRIFLE2")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.ADVANCEDFLAKCANNON,AWM-ADVANCEDFLAKCANNON")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.FLAKCANNON2,AWM-FLAKCANNON2")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.MINIGUN_2X,AWM-MINIGUN_2X")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.SNIPERRIFLE2X,AWM-SNIPERRIFLE2X")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.MONSTERSTINGER,AWM-MONSTERSTINGER")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="AWM_BETA1.LAVARIFLE,AWM-LAVARIFLE")
```

All of this lines is duplicates. Game store only one item, since all names is same.

Some other int file:
```ini
[PUBLIC]

//WEAPONS
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="RATPACKAGE.GRENADEGUN,RATPACKAGE-GRENADEGUN")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="RATPACKAGE.COWRIFLE,RATPACKAGE-COWRIFLE")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="RATPACKAGE.TRANSRIFLE,RATPACKAGE-TRANSRIFLE")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="RATPACKAGE.JUMPGUN,RATPACKAGE-JUMPGUN")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="RATPACKAGE.RATBIORIFLE,RATPACKAGE-RATBIORIFLE")
OBJECT=(NAME=WORMREPLACER.WORMWEAPCONFIG,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="RATPACKAGE.UT_DEATHCANNON,RATPACKAGE-UT_DEATHCANNON")
```

Code in mod, which read it:
```unrealscript
	GetPlayerOwner().GetNextIntDesc("WORMreplacer.WormWeapConfig", 0, NextWeapon, NextDesc);
	while( (NextWeapon != "") )
	{
		k = InStr(NextDesc, ",");

		ItemString = Left(NextDesc, k);
		Description = Mid(NextDesc, k+1);

		If (Description == "") Description = ItemString;


		If (NotADuplicate(ItemString)) weaponcontrol[slot].AddItem(Description, ItemString);

		NumWeaponClasses++;

		GetPlayerOwner().GetNextIntDesc("WORMreplacer.WormWeapConfig", NumWeaponClasses, NextWeapon, NextDesc);
	}
```

**Comment by SeriousBuggie** [comment]
Yes, it is wrong craft int files.
I fix one, and weapons appear in list:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/43796a62-4a99-4248-a8d3-4537d46ef2b9)
```ini
[PUBLIC]

//WEAPONS
OBJECT=(NAME=SAMURAI.MASMUNE,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.MASMUNE,SAMURAI-MASMUNE")
OBJECT=(NAME=SAMURAI.SABER,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.SABER,SAMURAI-SABER")
OBJECT=(NAME=SAMURAI.RAGRANOK,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.RAGRANOK,SAMURAI-RAGRANOK")
OBJECT=(NAME=SAMURAI.EXCALIBER,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.EXCALIBER,SAMURAI-EXCALIBER")
OBJECT=(NAME=SAMURAI.RAPIER,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.RAPIER,SAMURAI-RAPIER")
OBJECT=(NAME=SAMURAI.DAGGER,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.DAGGER,SAMURAI-DAGGER")
OBJECT=(NAME=SAMURAI.KUTTER,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.KUTTER,SAMURAI-KUTTER")
OBJECT=(NAME=SAMURAI.SLAYER,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.SLAYER,SAMURAI-SLAYER")
OBJECT=(NAME=SAMURAI.BLADE,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.BLADE,SAMURAI-BLADE")
OBJECT=(NAME=SAMURAI.SHORTSWORD,CLASS=CLASS,METACLASS=WORMREPLACER.WORMWEAPCONFIG,DESCRIPTION="SAMURAI.SHORTSWORD,SAMURAI-SHORTSWORD")
```
You need specify in field Name actual weapon name with package, not same line for all of it.

**Comment by KAZY369** [comment]
After 10 year, this problem solved - lol! I'm gonna fix all my plugins, hope it will works fine now, thanks @SeriousBuggie !

**Comment by KAZY369** [comment]
I installed every plugin, and than this happend: 

![WORMPLUG-WINDOW-ERROR](https://github.com/OldUnreal/UnrealTournamentPatches/assets/121546970/d947a6cd-a1b0-4170-b17d-0cacc4924708)

**Comment by SeriousBuggie** [comment]
Too many items in lists. You need use v469d or use less plugins (move some.int files away from System dir).

Such runaway loop already fixed in v469d.

**Comment by KAZY369** [comment]
Well, than I will check it with the compatible XC release.
