### ISSUE TITLE
[469c] Ued bug: Pressing F4 is resetting the drawscale for Actor

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1152]
1. Open Ued
2. Make a red cube brush and subtract it
3. Place any actor inside of the cube
4. Edit the Drawscale property of your actor (for example make it Drawscale 4.0)
5. Then select your Actor from the viewport and press F4 (which is the current shortcut to bring Actor properties browser)
Result: Your drawscale value is reset to 1.0

https://user-images.githubusercontent.com/58362332/210187091-d452dc6f-e9ce-4218-bd33-05ce5abb7a07.mp4

In my case this bug is preventing me from using the F4 shortcut to open actor properties, because it resets the drawscale of my meshes and they become small when I press F4.

**Comment by SeriousBuggie** [comment]
What you bind for f4? I can't reproduce. Also look in log, which commands here?

**Comment by BerserkerBG** [comment]
> What you bind for f4? I can't reproduce. Also look in log, which commands here?

I had "Actor Reset Scale" bind on F4, which I never knew I had on all of my UTs. Seems to be my own problem, closing issue.
