### ISSUE TITLE
[469c] Singleplayer broken: can't continue old game

### ISSUE THREAD

**Issue by senneschall** [OldUnreal/UnrealTournamentPatches#1157]
Freshly installed UT99, Patch 469c release applied.

I start a new singleplayer campaign, play a few maps, then exit.
Next time I start singleplayer, I can't continue the previous campaign, it forces me to create a new compaign.

After 5 times, singleplayer completely stops working with the following error:
![20230110_singleplayererror](https://user-images.githubusercontent.com/14364389/211641342-34a7e3ab-fe11-4632-93f3-a7e01e594be5.jpg)

Some research shows, that the new session is saved in User.ini in the secion `[UTMenu.SlotWindow]` und `Saves[0]=2\3\1\2\0\-1\0\-1\0\-1\0\0\M\0\senneschall`
Once all 5 available slots are full, the error message appears and singleplayer breaks down.

So I guess the bug is that loading those old savegames is broken.

**Comment by SeriousBuggie** [comment]
What written UnrealTournament.log when you just try start exists UT ladder? For me it work ok. On which step it stop work and with which message?

What your OS and what version of patch you apply?

**Comment by senneschall** [comment]
Ahh, it was an user mistake from my side. I didn't resume, but start a new tournament each time without noticing. Sorry for opening a ticket with my stupidity.
