### ISSUE TITLE
[469x] Couldn't create SDL window: Window is too large.

### ISSUE THREAD

**Issue by Luvbrothel** [OldUnreal/UnrealTournamentPatches#1158]
Tried a bunch of new installs, same thing pops up:

Couldn't create SDL window: Window is too large.

History: USDLViewport::ResizeViewport 
<- UOpenGLRenderDevice::SetRes <-
 UOpenGLRenderDevice::Init <-
 USDLViewport::TryRenderDevice <-
 USDLViewport::OpenWindow <-
 UGameEngine::Init <- InitEngine <- main

Don't know how or why, worked fine until this.  Any ideas?

**Comment by stijn-volckaert** [comment]
Which game version are you running? Could you open ~/Library/Application Support/Unreal Tournament/System/UnrealTournament.ini and check what you have under [SDLDrv.SDLClient]? I suspect the resolution listed in that section is not supported.

FYI: The 469a and b patches had issues with Retina displays. 469c improves support dramatically. 469d will have some additional Retina fixes. We have a preview available for testing. Come talk to us on Discord if you want to join our tester group: https://discord.gg/thURucxzs6

**Comment by Luvbrothel** [comment]
Hey, thanks for answering this - I’ve gone through all the 469 versions with the same results, which is weird since all the versions worked before this SDL thing came up.  I don’t see any SDL settings
in the .ini file.  Only SDL files I have are in the library/frameworks folder.  Any help is appreciated

Retina 5K, 27-inch, 2020
3.1 GHz 6-Core Intel Core i5
AMD Radeon Pro 5300 4 GB
Ventura 13.1

**Comment by Is3** [comment]
I now have the same problem after force close app (I tried to minimise and it hanged).
I have the M2 Max.

I removed these three lines:
FullscreenViewportX=100000
FullscreenViewportY=1027
FullscreenColorBits=32

From UnrealTournament.ini and game started with default resolution.

Maybe when I tried to minimise game something gone crazy and put these high values there.

**Comment by Luvbrothel** [comment]
Thanks for the input.  Still a no-go.  Initially the new version started up, but then went all wack when I 
did a resolution adjustment.  Even after wiping everything clean and starting over, still the same problem.

**Comment by Luvbrothel** [comment]
> On my M1 Mac this problem appears to be related to HiDPI or at least in my case they are related. When I set my display to a non-HiDPI resolution in game resolution switching works as expected. After in game resolution configuration I can set my resolution back to HiDPI and the previously selected in game resolution / full screen continue to work. So it appears to me the maximum allowable resolution is getting miscalculated on HiDPI displays.
> 
> If you're having this problem a potential workaround is to temporarily set your display to a non-HiDPI display mode, configure the game, then switch back to your preferred HiDPI resolution.
> 
> Steps:
> 
> 1. When my display is set to a HiDPI resolution of 2855x1195 I am able to select up to 2048x858 in game. A higher in game resolution results in the window disappearing and a crash ('too large') error on next startup.
> 2. When my display is set to native non-HiDPI resolution of 3440x1440 I am able to select higher in game resolutions successfully. Although during the in game resolution switch the game goes into window mode. This is fixed by restarting the game then it works in full screen at the selected resolution.
> 3. When I set my display back to HiDPI 2855x1195 the game configuration continues to work fine at the selected (2) resolution in full screen

Hey, thanks for the input.  I will keep this on hand in case it happens again.  I somehow solved my problem without knowing how it happened by recreating situation  - When starting up UT, before the full screen, I right clicked on my browser icon to close it, which made everything go whack.  Then I did the same thing and everything went back to normal.  Don't know how or why, but that's what it did.  Thanks again for responding.  Cheers!

**Comment by stijn-volckaert** [comment]
This will be fixed in the next 469e preview
