### ISSUE TITLE
[win][469a] XOpenGL mouse cursor red atrifact while opening voice menu in-game

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#116]
As per this incident: https://ut99.org/viewtopic.php?p=123376#p123376

I have no intention of spamming.
Just recreating the issue to keep integrity of the bug tracker.
Can't restore comments coz nobody remembers them, 
but it was a medium-long thread: several comments,
from 2-3 people experiencing the issue,
and the thread / issue has been labeled as `video` + `fixed for 469b`

The artifact:
![Shot00004](https://user-images.githubusercontent.com/72945564/96874550-867d7f00-1476-11eb-8f35-270f4e6c0a6a.png)

![Shot00005](https://user-images.githubusercontent.com/72945564/96874801-d1979200-1476-11eb-8c83-6cab3b4183c3.png)

**Comment by SeriousBuggie** [comment]
Fixed in v469b. Confirmed.
