### ISSUE TITLE
[469c] Ued issue: Transform Permanently destroys texture alignment

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1166]
When you Transform Permanently a brush, it ruins your texture alignment even when Texture Lock is on.

Example map: [TransformPermanentlyTextureIssue.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/10448552/TransformPermanentlyTextureIssue.zip)
Steps to reproduce with example map:
1. Open TransformPermanentlyTextureIssue.unr in Ued
2. Select the 4 Arch Ceiling brushes
3. Right click -> Transform -> Transform Permanently
4. Rebuild geometry
Result: Textures are misaligned after Transform Permanently is applied (even with Texture Lock on)

Before Transform Permanently:
![Screenshot_199](https://user-images.githubusercontent.com/58362332/213239646-934105e0-454d-4bab-b733-1b941b41ca9d.png)

After Transform Permanently:
![Screenshot_200](https://user-images.githubusercontent.com/58362332/213239794-0ec92f64-e6e5-48e4-ab8d-ba4ac86ea19e.png)

**Comment by SeriousBuggie** [comment]
Another example:
[TransformBug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/12772486/TransformBug.zip)
Before Transform:
![scr_1696027296](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/d4da9118-5b8d-471e-9936-d8911a128baf)
After Transform + Rebuild:
![scr_1696027312](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0acc3b1c-20e9-4a14-a0b7-cfad24d45866)
