### ISSUE TITLE
[469a] X/OpenGL stat fps command font too small + mixed colors, thus unreadable

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#117]
As per https://ut99.org/viewtopic.php?p=123376#p123376
 
I have no intention of spamming.
Just recreating the issue to keep integrity of the bug tracker.
Can't restore comments coz nobody remembers them, 
but it was a medium-long thread: 12 comments,
from several people experiencing the issue,
and the thread / issue has been labeled as `video`,
not sure whether it has been labeled as `fixed for 469b`

The issue has been derivied from another issue: `https://github.com/OldUnreal/UnrealTournamentPatches/issues/114` as we have been using `stat fps` command to measure the XOpenGL performance issue, some other commands might be affected as well.

1680X1050 (a res similiar to most popular FullHD 1920x1080)

![Shot00000](https://user-images.githubusercontent.com/72945564/96875239-49fe5300-1477-11eb-90b0-b48fd1eb159f.png)

![Shot00000b](https://user-images.githubusercontent.com/72945564/96875250-4c60ad00-1477-11eb-94eb-6c9534e5e00b.png)

**Comment by garry-ut99** [comment]
@SeriousBuggie @Chamberly 
- would you guys mind to recreate your comments, after github doing shit here
- I rememeber SeriousBuggie saying about some more stat commands being affected
- and Chamberly has commented with a 800x600 screenshoot and the font has been looking fine on such res

**Comment by stijn-volckaert** [comment]
stat fps is not really meant to be used in the menu...

**Comment by garry-ut99** [comment]
- in theory, but in practice, it turned out to be very useful to diagnose the XopenGL low fps / perfromance problem in the menu...
- the font is too small anyway, even in the game, it requires Windows Magnifier tool to read it on 1680x1050... It seems the font of fps stat command was designed to support screen resolutions of old times when the game appeared on the scene many years ago: 800:600 - 1024:768, nowadays it nees to be adapted to 2020 resolution standards like 1680x1050 - 1920x1080 and new 2k & 4k.

**Comment by stijn-volckaert** [comment]
The stats font will dynamically scale with your window resolution in 469b, but the fact that the text is not visible is not easy to fix. The potential fixes could have some nasty side effects.

**Comment by SeriousBuggie** [comment]
Just draw black text first. Four times. Fith offset on each coordinate to 1 pixel. +1 and -1. After that draw text wait above. So you get black outline around it.

**Comment by stijn-volckaert** [comment]
Will this work?
![image](https://user-images.githubusercontent.com/10390414/145824882-729c3136-c2de-42b3-9785-3cf96a5babac.png)

**Comment by SeriousBuggie** [comment]
As for me look as great solution for white text on white background.

**Comment by stijn-volckaert** [comment]
New options added in 469c-RC2

**Comment by garry-ut99** [comment]
Reopen request:
- because font size of `stat fps` and `F6` commands is still too small and requires Windows Magnifier tool to read it on 1680x1050...
- another issue is that F6 statistics interferes with chat messages

![Shot00252](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/047ade1d-4b5c-426a-9e2a-e38852613190)

**Comment by SeriousBuggie** [comment]
https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/ReleaseNotes.md

> - StatOffsetX (Integer - Default Value: 0): Overrides the default horizontal offset of the stats text
> - StatOffsetY (Integer - Default Value: 16): Overrides the default vertical offset of the stats text
> - StatDrawOutline (Boolean - Default Value: True): If True, stats text will be rendered with a black outline
> - StatScaleFont (Boolean - Default Value: True): If True, the stats font will be scaled up at higher resolutions
> - StatScaleFactor (Float - Default Value: -1): If -1, Render will automatically determine an appropriate scaling factor. If positive, Render will apply the user-specified scaling factor to the stats font

![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/8f291630-9312-4ecf-a7d4-78bda6d59862)
```ini
[Render.Render]
StatOffsetX=200
StatOffsetY=400
StatDrawOutline=True
StatScaleFont=True
StatScaleFactor=2
```

**Comment by garry-ut99** [comment]
OK, I was misleaded by the earlier comment, which suggested it'll be scaled automatically, thus I thought it failed to scale :
> stijn-volckaert : https://github.com/OldUnreal/UnrealTournamentPatches/issues/117#issuecomment-722557003 The stats font will dynamically scale with your window resolution

After adding the ini settings, it does work as expected, but I still think it would be better to put the last 2 settings in ini by default after installing the patch, to avoid experiencing too small fonts at all.
