### ISSUE TITLE
[469c] Attempted to use illegal skin

### ISSUE THREAD

**Issue by redeyedancer** [OldUnreal/UnrealTournamentPatches#1179]
I changed the bot skins in my server using textures from the game .
All the bots have used custom textures for years .

Example botpack.skins.exp5_a0 
I recently upgraded to the 469c patch from  the 436 patch
I am getting eras 
 ScriptLog: Attempted to use illegal skin from package decayeds for Commando
The server is forcing default skins for all the bots . Is there something I can do to allow this t work again .
This only happens while in the server . I start up a practice game all the skins work

**Comment by stijn-volckaert** [comment]
UTPG added the illegal skin check in one of their patches. The idea is that you can only use skins from packages that are on the serverpackages list. I'll check if I can make the skin check more configurable in 469d

**Comment by redeyedancer** [comment]
Thank yuo
