### ISSUE TITLE
[win][469a] software rendering window mode Aero glitch

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#118]
As per this incident: https://ut99.org/viewtopic.php?p=123376#p123376

I have no intention of spamming.
Just recreating the issue to keep integrity of the bug tracker.
Can't restore comments coz nobody remembers them, 
the thread / issue has been labeled as `video`.

1680x1050x32, nVidia GeForce GTS 250, , Win 7 SP1 Pro v7601,
the latest nVidia GPU driver:  `342.01  WHQL 2016.12.14`
It was related to / derivied from another issue: `https://github.com/OldUnreal/UnrealTournamentPatches/issues/114`
While investigating the above issue, `stijn-volckaert` wanted us to change / check some settings:
```
[Engine.Engine]
GameRenderDevice=SoftDrv.SoftwareRenderDevice
WindowedRenderDevice=SoftDrv.SoftwareRenderDevice

[WinDrv.WindowsClient]
StartupFullscreen=False
```

Additionally my res settings:
```
[WinDrv.WindowsClient]
WindowedViewportX=1680
WindowedViewportY=1050
WindowedColorBits=32
FullscreenViewportX=1680
FullscreenViewportY=1050
FullscreenColorBits=32
```

After doing so, and running game, following glitch appears (after disabling Aero Theme, the glitch disappears):

![glitch](https://user-images.githubusercontent.com/72945564/96864768-364bf000-1469-11eb-97be-aecea6782769.png)

**Comment by stijn-volckaert** [comment]
Can you remind me what the issue was? I had not actually looked into this yet. I just tested SoftDrv in windowed mode on Windows 7 and see no immediate problems.

**Comment by garry-ut99** [comment]
@stijn-volckaert Sure, I've updated the [first comment](https://github.com/OldUnreal/UnrealTournamentPatches/issues/118?_pjax=%23js-repo-pjax-container#issue-722944733) with the issue's description.

**Comment by stijn-volckaert** [comment]
![afbeelding](https://user-images.githubusercontent.com/10390414/96866585-cee36f80-146b-11eb-8077-649d699c20ae.png)

This is as close as I can get to your setup. This is UT v469a with SoftDrv, Aero, Win 7 Pro SP1 7601, and the same resolution you are using. I've never seen this glitch before. Is there any way you could test a different graphics card? Also, do you happen to be running UT in some sort of compatibility mode?

**Comment by garry-ut99** [comment]
I've checked on different (lower) resolutions in `[WinDrv.WindowsClient]` and the glitch doesn't occur, so it occurs only when resolution is equal to the monitor's native resolution, so could you try to reproduce on a resolution which is equal to your monitor native res, before I start to restarting my pc to switch to Intel GPU...?

> Is there any way you could test a different graphics card? 

Yep, the glitch might depends on specific GPU vendors (nVidia, AMD, Intel) or particular driver versions.

Yes, I have an integrated Intel HD 4400 as well, so I can switch from nVidia to Intel in BIOS/UEFI, but I hate restarting PC as it is a painful / nasty process because it closes all the stuff / applications running / documents opened, what is the most annoying PC-related thing in the world, but it seems the glitch has left me no choice lol...omg so I'll try l8er.

> Also, do you happen to be running UT in some sort of compatibility mode?

No.

**Comment by stijn-volckaert** [comment]
Thanks, that worked. The bug will be fixed in 469b.
