### ISSUE TITLE
16x9 Aspect ratio stretches badly on ultrawide monitors

### ISSUE THREAD

**Issue by boldc** [OldUnreal/UnrealTournamentPatches#1181]
There are a few issues involving player view and ultrawide monitors

**Issue 1**
Resolution settings for ultrawide monitors (21:9 aspect ratio) removes a lot vertical space from the player's view. That is, the top and bottom of the player's view is cropped, leaving them at a disadvantage during gameplay.

**Issue 2**
Selecting a 16:9 aspect ratio on an ultrawide monitor stretches the player'v view horizontally. It looks bad and can be distracting - also putting the player at a disadvantage during gameplay.

**Recommended Mitigation**
When a 16:9 aspect ration is selected on an ultrawide monitor, display that view correctly (no horizontal stretching): centered on the screen with black space on either side.

Roughly the equivalent of running a 16:9 resolution in windowed mode, but without the chunky windowed UI elements or the distraction of items that might be on the player's (Windows) desktop underneath.

Ultrawide monitors are a small percentage of marketshare but will increase over time, so it's something to consider for maintaining the longevity of Unreal/UT.

If this can be done, I recommend providing a new resolution: 2560x1440 (a 16:9 option for 3440x1440 monitors, which seems to be the most common ultrawide resolution at the moment).

**Comment by prom6** [comment]
??

21:9 to 16:9 comparison:

![21_9_16_9](https://user-images.githubusercontent.com/71797130/215168612-0be9f1ed-f14c-45c6-9397-e609b29698fc.jpg)

thats (almost) seamless

**Comment by boldc** [comment]
@prom6 In game I don't have an resolution option for 2560x1440 ... ?

I'm on 469c running D3D9

When I set my resolution to 3440x1440 this is what my view looks like
![ultrawide](https://user-images.githubusercontent.com/15841527/215171911-91a75c1e-9b1a-4ea3-8253-88bfc7a0097c.jpg)

When I switch to Windowed mode and run in 2560x1440 this wis what my view looks like
![16x9windowed-on-ultrawide](https://user-images.githubusercontent.com/15841527/215171932-5213411f-127a-4530-9b2a-678388a42b08.jpg)

If I overlay the images, look at how much is cropped on the top and bottom.
![difference](https://user-images.githubusercontent.com/15841527/215171955-c1346afa-0b04-49db-94f9-7b58c26e8348.jpg)

But if I canfigure out how to run at 2560x1440, then problem solved, I think

**Comment by prom6** [comment]
no idea what you have to change in your setup, I'm running on opengl. Shouldnt be something FoV related according to your screenshots I guess
i can also choose the right resolution from ingame menu, maybe thats some weird driver or monitor issue or a d3d setting

**Comment by boldc** [comment]
Looks like this is a monitor/driver issue
