### ISSUE TITLE
UnrealEd > Surface Properties > Custom Rotation broken?

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1184]
The "Custom Rotation" seems not to work: no matter what value I enter, it rotates about 90°:
![UnrealEd-CustomSurfaceRotation](https://user-images.githubusercontent.com/81397053/216296146-08de4e41-7e6e-4d5d-b3d0-19783bed619f.jpg)
Also the buttons for rotating 1°, 11.25°, 22.5° do not work as expected.
Editor version: 
> UnrealEd2.2, original Version copyright 2000, Epic Games Inc. Updated to Version 2.2 by [www.oldunreal.com])

Test map attached: [TestSurfaceRotation-Testmap.unr.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/10567729/TestSurfaceRotation-Testmap.unr.zip)
(See also [crossposting in UT99.org](https://ut99.org/viewtopic.php?f=5&t=15703).)

**Comment by SeriousBuggie** [comment]
Little better test map: [TestSurfaceRotation.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/10575618/TestSurfaceRotation.zip)
