### ISSUE TITLE
[469c] UT Bot Improvement/Changes

### ISSUE THREAD

**Issue by Annonymous5542** [OldUnreal/UnrealTournamentPatches#1185]
Out of curiosity, any chance we will see some added features/improvements for the stock UT bots? Played Unreal for a while and did notice that v227i did improve a few aspects. 

Features listed below are from changelog v227i here: 
From https://www.oldunreal.com/wiki/index.php?title=227_release_notes/v227i

- Added option for AI strafing movement while moving along paths (AI: bDoAutoSerpentine, also in NavigationPoint: bNoStrafeTo to stop AI from walking to this node like that). Which means AI will strafe left/right while moving along paths making them harder to hit. This will be enabled on higher difficulty bots.

- Added pathfinding option HuntOffDistance, which when combined with bHunting, AI will try to find closest path to a visible point to their enemy which is inside that distance, rather than trying to find path leading to the actual enemy (will also now be used by higher difficulty bots).

**Comment by stijn-volckaert** [comment]
Unfortunately, changes to game/bot behaviour are not really within the scope of our UT project. If you want to see this implemented for UT, you would have to find a modder to work on an improved (standalone) AI.
