### ISSUE TITLE
[469a] "oldunreal-utpatch469.exe is not a valid win32 application"

### ISSUE THREAD

**Issue by AntiSol** [OldUnreal/UnrealTournamentPatches#119]
I just tried out the windows installer on my WinXP VM, and got this:

Thoughts?

**Comment by AntiSol** [comment]
...and for some reason gitlab is acting screwy and won't let me attach a screenshot, so: https://imagebin.ca/v/5e0kOVGrlMsB

**Comment by stijn-volckaert** [comment]
That is odd. I test all of the releases in Windows XP myself. Do you have SP1 installed?

**Comment by AntiSol** [comment]
It's SP3, apparently.
I'm not sure what the MD5 of the file should be? I checked it against a freshly downloaded copy on my Linux box and got the same md5 (which you can see in the attached screenshot, along with some other stuff)
![Screenshot from 2020-11-03 20:16:24](https://user-images.githubusercontent.com/351169/97968217-766c8480-1e12-11eb-8754-d4755b10e3f6.jpg)

**Comment by Dr-Flay** [comment]
Yes the MD5 hash is ce0d3b8a131ac073ba856918c2f9e860
