### ISSUE TITLE
[469c] Demo manager - ScriptWarning

### ISSUE THREAD

**Issue by alsosed** [OldUnreal/UnrealTournamentPatches#1190]
Client log:
ScriptWarning: AutoRecorder Transient.AutoRecorder0 (Function udemo.AutoRecorder.NotifyLevelChange:0043) Accessed None 'PlayerReplicationInfo'
ScriptWarning: AutoRecorder Transient.AutoRecorder0 (Function udemo.AutoRecorder.NotifyLevelChange:004B) Attempt to assign variable through None

**Comment by alsosed** [comment]
> Possible it need move to https://github.com/stijn-volckaert/udemo
as far as me know, udemo is now part of the patch

**Comment by SeriousBuggie** [comment]
Duplicate of #314
