### ISSUE TITLE
libunwind.so.8: cannot open shared object file: no such file or directory

### ISSUE THREAD

**Issue by PepsimanX** [OldUnreal/UnrealTournamentPatches#1192]
Ubuntu 20.04.5 LTS

./ut-bin: error while loading shared libraries: libunwind.so.8: cannot open shared object file: No such file or directory.

sudo apt-get install -y libunwind-dev (did not help. )

**Comment by SeriousBuggie** [comment]
You need 32-bit library. What about this: `sudo apt-get install -y libunwind-dev:i386` ?

**Comment by PepsimanX** [comment]
> You need 32-bit library. What about this: `sudo apt-get install -y libunwind-dev:i386` ?

user@pc:~/utlinux/System$ ./ut-bin
WARNING: using preference directory: /home/user/.utpg/System/
WARNING: Using system ini file: /home/user/utlinux/System/UnrealTournament.ini
WARNING: Using user ini file: /home/user/utlinux/System/User.ini

Developer Backtrace:
[ 1]  /home/user/utlinux/System/Core.so(_Z12HandleSignali+0x20b) [0xf75bb78b]
[ 2]  linux-gate.so.1(__kernel_sigreturn+0) [0xf7fb2560]
Signal: SIGSEGV [segmentation fault]
Aborting.

Ошибка сегментирования (стек памяти сброшен на диск)

**Comment by SeriousBuggie** [comment]
Did you try Linux 64-bit build? For 32-bit you need install a lot of 32-bit libs.

Usually you can copy contents from System64 to System and use it as before 32-bit, but now it be 64-bit.

**Comment by PepsimanX** [comment]
> Did you try Linux 64-bit build? For 32-bit you need install a lot of 32-bit libs.
> 
> Usually you can copy contents from System64 to System and use it as before 32-bit, but now it be 64-bit.

Yes x64. Right now everything is working thank you very much. Love like you is the future.

**Comment by PepsimanX** [comment]
and also in the game how to remove lines on objects?

**Comment by SeriousBuggie** [comment]
Bug in AMD drivers: #965

**Comment by PepsimanX** [comment]
> Bug in AMD drivers: #965

Thank you.
