### ISSUE TITLE
[469a] Unreal Editor keyboard shortcuts have been changed

### ISSUE THREAD

**Issue by sapphire-bt** [OldUnreal/UnrealTournamentPatches#12]
Keyboard shortcuts within Unreal Editor have been changed. This breaks the workflow of mappers who have been used to using the default keys for years. Please provide an option to change the key mapping back to default, or provide custom key mapping.

The "Select All Actors" command, for example, has been changed from Shift+A to Ctrl+A. While this reflects today's de facto standards for keyboard shortcuts in other programs, it now results in a poor user experience for the reason mentioned above.

**Comment by stijn-volckaert** [comment]
These changes happened when we ported over Unreal 227's editor. We're planning to make the key binds configurable in an upcoming update.

**Comment by stijn-volckaert** [comment]
Small update: the next UEd snapshot will most likely include an option that lets you choose between different keybinding schemes.
