### ISSUE TITLE
[linux server][469a] Misc. seg faults

### ISSUE THREAD

**Issue by Sizzl** [OldUnreal/UnrealTournamentPatches#120]
Unable to reproduce exact scenario so can't provide strace logs, but leaving backtrace logs here in case it helps.

Will update issue entry if repro steps become available. Note - this crash may not be anything new introduced in 469, as similar crashes have been seen over the years.

Crash is typically encountered shortly after transitioning maps, in 4v4 or 6v6 matches (League Assault); two different traces (most common is first).

>Developer Backtrace:
>[ 1]  ./Core.so(_Z12HandleSignali+0x208) [0xf7da3d08]
>[ 2]  linux-gate.so.1(__kernel_sigreturn+0) [0xf7fc0a30]
>[ 3]  ./Engine.so(_ZN11UGameEngine14GetMaxTickRateEv+0x36) [0xf7719816]
>[ 4]  ./Engine.so(_ZN17UServerCommandlet4MainEPKw+0x613) [0xf77065b3]
>[ 5]  ./ucc-bin(main+0x71e) [0x804ddce]
>[ 6]  /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0xf79f0ee5]
>[ 7]  ./ucc-bin() [0x804d4bf]
>Signal: SIGSEGV [segmentation fault]
>Aborting.

>Developer Backtrace:
>[ 1]  ./Core.so(_Z12HandleSignali+0x208) [0xf7cbfd08]
>[ 2]  linux-gate.so.1(__kernel_sigreturn+0) [0xf7edca30]
>[ 3]  ./Engine.so(_ZN17UServerCommandlet4MainEPKw+0x564) [0xf7622504]
>[ 4]  ./ucc-bin(main+0x71e) [0x804ddce]
>[ 5]  /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0xf790cee5]
>[ 6]  ./ucc-bin() [0x804d4bf]
>Signal: SIGSEGV [segmentation fault]
>Aborting.

**Comment by stijn-volckaert** [comment]
Confirmed. This was a thread safety bug. Will be fixed in 469b.

**Comment by Sizzl** [comment]
Had another today; will this be covered by the thread safety bug already fixed?

> Developer Backtrace:
> [ 1]  ./Core.so(_Z12HandleSignali+0x208) [0xf7cfbd08]
> [ 2]  linux-gate.so.1(__kernel_sigreturn+0) [0xf7f18a30]
> [ 3]  ./ucc-bin(_ZN11FMallocAnsi7ReallocEPvjPKw+0x21) [0x804f411]
> [ 4]  ./Core.so(_ZN6FArray7ReallocEi+0x68) [0xf7cda138]
> [ 5]  ./ucc-bin(_ZN7FStringD2Ev+0x27) [0x804efe7]
> [ 6]  ./ucc-bin(_ZN6TArrayI7FStringED2Ev+0x2c) [0x804f16c]
> [ 7]  ./Engine.so(_ZN11UGameEngine4TickEf+0x119c) [0xf7672d7c]
> [ 8]  ./Engine.so(_ZN17UServerCommandlet4MainEPKw+0x5ab) [0xf765e54b]
> [ 9]  ./ucc-bin(main+0x71e) [0x804ddce]
> [10]  /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0xf7948ee5]
> [11]  ./ucc-bin() [0x804d4bf]
> Signal: SIGSEGV [segmentation fault]
> Aborting.
