### ISSUE TITLE
Error Splash logo bmp

### ISSUE THREAD

**Issue by OliverHD9** [OldUnreal/UnrealTournamentPatches#1201]
Hello I downloaded the Windows exe patch for my pc, the setup worked fine until I hit play and an error popped up saying  
       
    CRITICAL ERROR
   
    Could not load splash logo: ..\Help\Logo.bmp   

    History:      

I dont know what to do and how to fix this critical error problem. Any assistance would be great!

**Comment by SeriousBuggie** [comment]
Patch is patch. Not whole game. So you still need game for apply patch. You can't install patch to empty folder and try run it like it full game.
