### ISSUE TITLE
[469c] XOpenGL is too dark!

### ISSUE THREAD

**Issue by noskill24** [OldUnreal/UnrealTournamentPatches#1208]
Maximum brightness:

![image](https://user-images.githubusercontent.com/35011774/222803741-59624a49-de83-4346-81fc-0322d213b773.png)

**Comment by SeriousBuggie** [comment]
In future updates, such options be accessible in game from what I know. Special button with additional options.

**Comment by garry-ut99** [comment]
> Yes, I confirm... This video driver is very dark by default.

Me too confirm.

**Comment by stijn-volckaert** [comment]
Confirmed duplicate of #1002
