### ISSUE TITLE
[469a] Dodging or launching into sloped surfaces from a distance no longer gives you momentum to slide up the surface

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#121]
Tested on Windows 469a client running D3D9, playing online on a 469a-patched Linux server.

In UT v451, a player who is launched into a sloped surface from a distance would use the momentum to slide up the surface.
In v469a, the momentum is no longer conserved. Launching into a ramp makes you simply crash into the ramp and stop dead.

The launch could be from a kicker which kicks you horizontally into a slope, or it could be from side dodging across a gap into a slope.

I'll try to find a good example map (or make one) for testing purposes and will post back here when I do.

One map I have confirmed as "broken" by this behaviour is `CTF-BT-Synthesisv2`, where the room made by `OwYeaW` is no longer passable as intended.

**Comment by dizzy-egg** [comment]
Here's a demo map (made by NuLL and modified poorly by me) to illustrate the problem.

1. Open the map and try side dodging across the lava pit.
    * In v451 this would be possible (see BT-Synthesis).
    * In v469a, it's not possible.

2. Now try using each of the three kickers to crash into the three slopes. 
    * In v451 all slopes would propel you upwards vertically.
    * In v469 at least two of the three slopes result in you stopping instantly and not moving upwards.

[CTF-BT-KickerSlopeDemo.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5396036/CTF-BT-KickerSlopeDemo.zip)

**Comment by stijn-volckaert** [comment]
Thanks for the map. This was _extremely_ helpful. We already had a fix for this problem in v469a but it had some nasty side effects and it didn't work for very steep slopes. I've updated the fix for v469b. Note: the underlying problem exists in most Unreal Engine 1,2, and 3 games but you only notice it at very high framerates.

Here's a short clip that compares the physics code for UT v400-451, v469a, and v469b:
https://www.youtube.com/watch?v=PXStgkGI5WM&feature=youtu.be

**Comment by zero-khan** [comment]
In DM-Fractal, if you crouch when falling in the hole, you can get stuck in it.

**Comment by dizzy-egg** [comment]
> 
> 
> In DM-Fractal, if you crouch when falling in the hole, you can get stuck in it.

I don't get stuck in it, however I do often slide over the lasers or collide with them, rather than being killed by them. 

Not sure if that's a pre-existing "bug" or a problem with the map or what.
