### ISSUE TITLE
[469c] Framerate-dependent flickering for lights with LT_Flicker

### ISSUE THREAD

**Issue by Sergiut99** [OldUnreal/UnrealTournamentPatches#1216]
If vertical sync is off, then we have a graphical artifact - flickering shadows (see  this place on Deck16 ][  take a look at screenshot) and no stuttering.
```
[XOpenGLDrv.XOpenGLRenderDevice]
UseVSync=Off
```
![Shot00000](https://user-images.githubusercontent.com/100404282/226916008-7017c582-000c-4af9-a30d-1b18fd3bc954.png)

If to enable vertical sync, then playing with these render is impossible and unpleasant due to stuttering in the game
But it helps with the problem of flickering shadows
```
[XOpenGLDrv.XOpenGLRenderDevice]
UseVSync=On
```

In older versions of this render for game version 436, the stuttering issue could be fixed as follows:
www.oldunreal.com/betatest/XOpenGL1.1.0.1_UT4.36.zip
```
[XOpenGLDrv.XOpenGLRenderDevice]
SyncToDraw=True
```
now this variable doesn't help...
This issue was seen on Windows 7 with a 60Hz monitor

**Comment by stijn-volckaert** [comment]
This has nothing to do with V-Sync or XOpenGLDrv. The light you're pointing at has LT_Flicker set as its LightType: 
![afbeelding](https://user-images.githubusercontent.com/10390414/235640689-554bee49-6cc9-4ea5-9921-0b84880d849e.png)

LT_Flicker lights change intensity once per rendered frame. This means the fast flickering you're seeing is the direct result of uncapping your frame rate. I agree this is annoying and it was almost certainly not intentionally designed this way. A potential solution could be to make LT_Flicker lights flicker at a fixed pace. I'll leave this ticket open while we think about a solution.

**Comment by Calinou** [comment]
>  A potential solution could be to make LT_Flicker lights flicker at a fixed pace. I'll leave this ticket open while we think about a solution.

There should be a way to disable flickering entirely for people sensitive to light flickering.

As for making flickering FPS-independent, pick a random value a fixed amount of times per second (e.g. 10 times per second) and interpolate towards this value every frame.

**Comment by DeluxeIncorporated** [comment]
I'm having an issue with the sky/stars flickering intensely on maps like Face & LavaGiant. It only occurs while moving around. Using Windows 11 with 165hz monitor. If I cap frames at 60hz the flickering is less dramatic but then I lose smoothness of movement.

**Comment by stijn-volckaert** [comment]
> I'm having an issue with the sky/stars flickering intensely on maps like Face & LavaGiant. It only occurs while moving around. Using Windows 11 with 165hz monitor. If I cap frames at 60hz the flickering is less dramatic but then I lose smoothness of movement.

This is probably a different issue. Could you perhaps record this using OBS (or a similar program)?

**Comment by DeluxeIncorporated** [comment]
> > I'm having an issue with the sky/stars flickering intensely on maps like Face & LavaGiant. It only occurs while moving around. Using Windows 11 with 165hz monitor. If I cap frames at 60hz the flickering is less dramatic but then I lose smoothness of movement.
> 
> This is probably a different issue. Could you perhaps record this using OBS (or a similar program)?

https://www.youtube.com/watch?v=hwOx9AVRPeo

I see my flickering issue in the video when I watch on my monitor and TV, but it's not there when I watch on my phone. Maybe my display is the culprit? The severity of the flickering lessens when I lower the framerate limit in UT.

**Comment by Calinou** [comment]
> I see my flickering issue in the video when I watch on my monitor and TV, but it's not there when I watch on my phone. Maybe my display is the culprit? The severity of the flickering lessens when I lower the framerate limit in UT.

I don't see any flickering on my display (LG C2 42").

The issue likely comes from one of two sources:

- Your monitor has poor response times especially with dark pixels, which is typical of displays with VA panels. Lowering FPS limit gives it proportionally more time to respond to each frame, which lessens the issue. This can't be completely resolved, but adjusting your display's overdrive settings in its OSD can help.
- You have high but unstable framerate (stutter/jitter) which causes the gamma curve to jump around when variable refresh rate (G-Sync/FreeSync) is enabled. You can resolve this by disabling VRR.

**Comment by DeluxeIncorporated** [comment]
> > I see my flickering issue in the video when I watch on my monitor and TV, but it's not there when I watch on my phone. Maybe my display is the culprit? The severity of the flickering lessens when I lower the framerate limit in UT.
> 
> I don't see any flickering on my display (LG C2 42"), even at 120 FPS.
> 
> The issue likely comes from one of two sources:
> 
> * Your monitor has poor response times especially with dark pixels, which is typical of displays with VA panels. Lowering FPS limit gives it proportionally more time to respond to each frame, which lessens the issue. This can't be completely resolved, but adjusting your display's overdrive settings in its OSD can help.

Yes, it's a VA panel. Indeed, no combination of settings seems to resolve the issue. I don't suppose there's a way to remove that particular skybox from the game so it just shows blank black? It's the only thing ruining my experience.

**Comment by an-eternity** [comment]
> I'm having an issue with the sky/stars flickering intensely on maps like Face & LavaGiant. It only occurs while moving around. Using Windows 11 with 165hz monitor. If I cap frames at 60 the flickering is less dramatic but then I lose smoothness of movement.

This problem with stars always occurs on slow displays, no matter the type VA/IPS/TN or framerate - i have seen this problem on all LCD display types. Slow displays have too long time on pixels switching from 0 to some middle levels... Some monitors have options to mitigate it, e.g. by increasing a black level - you lose black color but get faster transitions from "black" to grays...
I just watched that video from YT on slow display - stars got dimmed on moving of course, and then rewatched this same video on faster display - stars got only barely noticeable dimmed on moving. So, it's normal.

**Comment by cweiske** [comment]
I also had the flickering problem, and it was because my frame rate was at ~2500 fps. After reducing it to max 60fps it flickers ok.

**Comment by SeriousBuggie** [comment]
We push fix for that. In 469e Flicker must be at 30 FPS equivalent.

https://github.com/stijn-volckaert/UnrealTournament/commit/cf6f204e6a651fc71f6f5c69108b31db070a5d3d
