### ISSUE TITLE
[469c] Need universal HWID built into UT99

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#1217]
can we get a Universal HWID system built into UT99 for identifying clients?

then coders can create banning systems based off this inbuilt HWID.

**Comment by SeriousBuggie** [comment]
No. Since old clients come without it, this already impossible. Or 436 ignored, and you want ban only v469d+?

**Comment by no0nehere** [comment]
build into servers , not clients

**Comment by SeriousBuggie** [comment]
It not make any sense. How servers will know HWID from client? Exists only one way - client must tell it. No any other way.

**Comment by stijn-volckaert** [comment]
This is well outside the scope of our project. Generating reliable hardware ids is also a notoriously tricky technical problem, and submitting hardware ids to the server has legal ramifications that we do not want to deal with either. This means we will not (and cannot) implement this in our patches.
