### ISSUE TITLE
[win][469a] Game freezes and crashes when launching a map directly/locally

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#122]
*Client UT Version:* 469a
*Server UT Version:* N/A
*OS:* Windows 7 x64
*Renderer:* D3Dv9

When attempting to open any map file directly (from my local hard drive) by double-clicking on the `.unr` and opening with `UnrealTournament.exe`, the following happens:

1. UT starts loading as normal
2. The map loads, the start screen is shown (i.e. "Click fire when ready"), and the map's music plays
3. I am unable to give any mouse or keyboard input to the game. For all intents and purposes it is "frozen".
4. When I press Ctrl+Alt+Delete (the only thing I can do) the following error occurs:
    ![image](https://user-images.githubusercontent.com/28424385/96347958-4fd1ee00-109d-11eb-83cc-e1e0cb342906.png)

**Comment by Chamberly** [comment]
I'm using D3D9 and I do not have this issue... but I did it in windowed mode so I can load a map.

**Comment by SeriousBuggie** [comment]
No issue for me. Win7 x64, D3D9, drag and drop .unr file to .lnk for UnrealTournament.exe. All fine. Input is fine.

Possible other application take input focus after UT. So all input goes not in UT.

**Comment by stijn-volckaert** [comment]
This normally only happens if some other application has exclusive access to the D3D adapter while D3D9Drv is initializing. The problem is that UT tries to shut down the current renderer and initialize a new renderer when you alttab or toggle into fullscreen mode. I made a change that should fix this in 469b.
