### ISSUE TITLE
[469c] Ued: Surface sampling and applying with CTRL+ALT+LMB / CTRL+ALT+RMB

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1220]
Surface sampling and applying feature in Ued works only if the surfaces are facing the same orientation.

Many people don't know about this feature, so I will explain it briefly what it does. It is an old feature which is also present in 436. Basically what it does, is it copies the properties of a surface (texture, scale, pan) and then you can apply them to other surfaces. You copy surface properties in the 3D viewport by clicking on the surface using CTRL+ALT+RMB, then you apply it to other surfaces with CTRL+ALT+LMB.

The main issue with this feature is that, for some reason, if you copy a surface and apply it to another surface, which has a different orientation than the copied surface - it will break and smear the texture. Here is an example:

https://user-images.githubusercontent.com/58362332/227259706-d15ce469-4c7d-49f5-b400-68058def810e.mp4

Reproduce:
1. Open this map in Ued: [Ctrl+Alt+(RMB)-(LMB).zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11053145/Ctrl%2BAlt%2B.RMB.-.LMB.zip)
2. Sample one of the trim surfaces with CTRL+ALT+RMB
3. Apply it to a different surface, which is facing perpendicular of the sampled surface using CTRL+ALT+LMB.

Result: Texture will be smeared.

**Comment by SeriousBuggie** [comment]
It do exactly next thing: it copy all stuff, include U and V vectors. U And V vectors is vectors. And describe how place texture in such surface. So if surface not coplanar to source it pasted and you distortion of texture. 

Not sure what there can be done. Rotate one surface to another can be done in different ways. There no any obvious way for that.

**Comment by SeriousBuggie** [comment]
Hm. As another idea - use surface normals for determine transformation for U and V vectors. There only one problem - rotation of texture can't be determined by normal.
