### ISSUE TITLE
[469c] Ued: Include patch version name on the top right bar.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1221]
A cool idea would be to include the patch version on the top right corner of Ued.
![Screenshot_242](https://user-images.githubusercontent.com/58362332/227488907-fbc3fb19-5d35-4436-9ef2-bf6484bf5aba.png)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1682849776](https://user-images.githubusercontent.com/70026933/235347842-20f0f5fe-320c-42e8-b71f-837eea8b21c6.png)
