### ISSUE TITLE
[469c] Practice Session Bots Base Skill

### ISSUE THREAD

**Issue by KAZY369** [OldUnreal/UnrealTournamentPatches#1225]
This is just a little bug.
I noticed when I'm playing in Practice Session, and set the Bots to any **_Base Skill_**, after one or two match the Bots **_Base Skill_** changes to Godlike.

**Comment by NeonKnightOA** [comment]
Do you have auto bot skill activated in the Bots tab?

**Comment by KAZY369** [comment]
Yeah it's activated, so that was the problem. I didn't noticed that after 20 years, lol!
