### ISSUE TITLE
[469c] Broken float values from VSize of vector from non-simulated call on client

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1226]
Reproduce:
1. Run on dedic [CheckVector.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11116605/CheckVector.zip)
2. Connect as client.

used code:
```unrealscript
class MyActor expands Actor;

simulated function PreBeginPlay() {
	local vector V;
	local float S;
	
	V = X();
	S = Vsize(X());
	Log("Test:" @ V @ VSize(V) @ VSize(X()) @ S);
}

function vector X() {
	return vect(1,2,3);
}
```

Expected result: In client log:
`ScriptLog: Test: 0.000000,0.000000,0.000000 0.000000 0.000000 0.000000`
Actual result: In client log:
`ScriptLog: Test: 0.000000,0.000000,0.000000 0.000000 0.000000 inf`

In similar case I get instead of `inf` - `nan` or `-nan`.
It be `inf` from stored variable and `-nan` from direct call.

**Comment by SeriousBarbie** [comment]
Hmm, shouldn't function vector() also be simulated?

**Comment by SeriousBuggie** [comment]
No. It is test case for show bugged behavior.

**Comment by SeriousBuggie** [comment]
Hmmm. I now can't reproduce it in v469d, v469c. Possible because it rely to unallocated memory, or access random memory located/uninitialized one.

**Comment by SeriousBuggie** [comment]
From Marco:
> that would be thanks to this macro for not initializing struct to zero:
> `#define P_GET_STRUCT(typ,var)         typ   var;                           Stack.Step( Stack.Object, &var    );` and then with `ProcessInternal` not writing return value:
> 
```c++
// Internal function call processing.
//!!might not write anything to Result if singular or proper type isn't returned.
//
void UObject::ProcessInternal( FFrame& Stack, RESULT_DECL )
```
> 
> so VSize native function ends up with retriving size of uninitialized vector

**Comment by stijn-volckaert** [comment]
We applied the same fix as UE3. 469d will zero out return values of absorbed function calls
