### ISSUE TITLE
[469c] Framerate cap behaviour

### ISSUE THREAD

**Issue by mkardi** [OldUnreal/UnrealTournamentPatches#1227]
I observed interesting behaviour with OpenGL on 469c
When I set FrameRateLimit=60 and enable timedemo statistics during gameplay then framerate is not locked at 60

It fluctuates somewhere around 58-59.xx fps mark, see screenshot.
If I increase cap to 61 then floats around 60.xx fps instead.

Can someone explain why ini value does not translate 1:1 in game cap?
![framerate](https://user-images.githubusercontent.com/81050091/229204149-f515691b-e2e5-4e18-9013-ebe1e7681a0e.png)

**Comment by SeriousBuggie** [comment]
Because it is not hard cap. It depends from stats. Stats collected with delay. This make fluctuation. Time for process each tick (frame) depends from game situation it not same all time.

Also timedemo number too not precise. 
`stat fps` can show different numbers.

**Comment by mkardi** [comment]
thanks, stat fps shows bit higher (accurate?) values which is around 59.x fps

**Comment by garry-ut99** [comment]
> It fluctuates somewhere around 58-59.xx fps mark, see screenshot.

For me timedemo shows 57 fps
