### ISSUE TITLE
[469] HD sniper rifle crosshair/reticle texture not being rendered by DX11 renderer.

### ISSUE THREAD

**Issue by Xon2** [OldUnreal/UnrealTournamentPatches#1228]
Patch 469 apparently contains a HD sniper rifle crosshair when zooming in as a BC3 compressed texture inside botpack.u placed in the system folder. The following renderers display that HD texture correctly:
DX9
openGL
XopenGL

The DX11 renderer version 1.61 from moddb does not, it still displays the old lowres texture. Could this particular texture be repackaged so the DX11 renderer can call it up?

**Comment by thiagoobr** [comment]
That would be really nice, even for all crosshair, convert them to 4k

**Comment by stijn-volckaert** [comment]
Unfortunately, there is nothing we can do on our end to make D3D11Drv render this texture correctly. It looks like the developer of this renderer never implemented (or enabled?) support for compressed textures with alpha channels. We can't convert the texture to one of the formats D3D11Drv supports either
