### ISSUE TITLE
[469a] UMenu.UMenuVideoClient.ScaleCombo missing

### ISSUE THREAD

**Issue by gattovicentino** [OldUnreal/UnrealTournamentPatches#123]
I had already mentioned this question in another thread but that thread is related to a different question, so it's better to open a specific thread here:
it would be nice if you could add a lot more serverpackages lines in unrealtournament.ini file without UT crashing. 
It's not a v.469a issue, since any UT version crashes when lots or serverpackages lines are present, but that would be great if a future patch could fix it.

**Comment by stijn-volckaert** [comment]
What exactly does this crash look like? Can you share your ServerPackages list with us?

**Comment by gattovicentino** [comment]
It crashes when loading a DM or MH game, if I put a lot of serverpackages lines. Not a specific number of lines... so I suppose it's more a matter of memory than a matter of number of lines itself. I attached a text file with serverpackages lines.
And here below: the last lines of Unrealtournament.log (there are many other "Log: Server Package: something" lines, I pasted the last ones only):

Log: Server Package: gorok
Log: Server Package: r2d2
Log: Server Package: r2d2skins
Log: Server Package: UT2004CharactersV2.int
Critical: FUnrealfileSummary<<
Critical: LoadSummary
Critical: ULinkerLoad::ULinkerLoad
Critical: UObject::GetPackageLinker
Critical: UGameEngine::BuildServerMasterMap
Critical: ULevel::Listen
Critical: Listen
Critical: UGameEngine::LoadMap
Critical: LocalMapURL
Critical: UGameEngine::Browse
Critical: ClientTravel
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: ALAudio subsystem shut down.
Exit: UALAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: XOpenGL: ShutdownAfterError
Exit: Exiting.

[serverpackages.txt](https://github.com/OldUnreal/UnrealTournamentPatches/files/5474325/serverpackages.txt)

**Comment by stijn-volckaert** [comment]
.int files are not valid serverpackages. That is what it's crashing on right now.

**Comment by gattovicentino** [comment]
Correct, I had not noticed the presence of the .int extension in some lines, sorry.

I deleted them, but UT still crashes. 
I don't know if it's due to the TeamOrbit stuff, since the "ObjectProperty" failed import issue happens immediately after loading TeamOrbit package. 

In unrealtournament.ini file there are more serverpackages lines after the TeamOrbit ones (as you can see in the serverpackages.txt file I have attached in my previous message), 
but, looking at unrealtournament.log file (I pasted its last lines here below), it seems that those serverpackages lines are not loaded, because UT crashes before loading them: 

.....
Log: Server Package: cero
Log: Server Package: ceroskins
Log: Server Package: fudd
Log: Server Package: fuddskins
Log: Server Package: karrot
Log: Server Package: karrotskins
Log: Server Package: TeamOrbitMedia
Log: Server Package: TeamOrbit
Log: Failed import: ObjectProperty ObjectProperty UMenu.UMenuVideoClientWindow.ScaleCombo (file ../System/UMenu.u)
Critical: ULinkerLoad::VerifyImport
Critical: ValidateImports
Critical: ULinkerLoad::Verify
Critical: ULinkerLoad::ULinkerLoad
Critical: UObject::GetPackageLinker
Critical: UGameEngine::BuildServerMasterMap
Critical: ULevel::Listen
Critical: Listen
Critical: UGameEngine::LoadMap
Critical: LocalMapURL
Critical: UGameEngine::Browse
Critical: ClientTravel
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: ALAudio subsystem shut down.
Exit: UALAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: XOpenGL: ShutdownAfterError
Exit: Exiting.

**Comment by stijn-volckaert** [comment]
TeamOrbit seems to depend on a property we had removed from UMenu. I've put it back in for 469b.

**Comment by gattovicentino** [comment]
> TeamOrbit seems to depend on a property we had removed from UMenu. I've put it back in for 469b.

Thank you. 
On v.436, I use some TeamOrbit (NeoCairo) machines models as bots in normal DM or MH games. They are not perfect as bots and not created for the purpose of playing outside that mod, but on v.436 they work as bots, anyway.
They don't work on v.469a (UT crashes loading the game, in both practice and multiplayer games) and, looking at Unrealtournament.log, it has to do with the Umenu issue too. 

Glad to know that v469b will fix it too ! :-)


Log: Failed import: ObjectProperty ObjectProperty UMenu.UMenuVideoClientWindow.ScaleCombo (file ../System/UMenu.u)
Critical: ULinkerLoad::VerifyImport
Critical: ValidateImports
Critical: ULinkerLoad::Verify
Critical: ULinkerLoad::ULinkerLoad
Critical: UObject::GetPackageLinker
Critical: UObject::StaticLoadObject
Critical: (Core.Class TeamOrbit.SelkBot NULL)
Critical: (MH-RuinsofHarobed.XBotsBotRandomInfo1 Botpack.ChallengeBotInfo.CHGetBotClass)
Critical: (MH-RuinsofHarobed.MonsterHunt0 Botpack.DeathMatchPlus.SpawnBot)
Critical: (MH-RuinsofHarobed.MonsterHunt0 Botpack.TeamGamePlus.AddBot)
Critical: (MH-RuinsofHarobed.MonsterHunt0 Botpack.DeathMatchPlus.PostLogin)
Critical: UObject::ProcessEvent
Critical: (MonsterHunt MH-RuinsofHarobed.MonsterHunt0, Function Botpack.TeamGamePlus.PostLogin)
Critical: Accept
Critical: ULevel::SpawnPlayActor
Critical: MatchViewportsToActors
Critical: (MH-RuinsofHarobed.unr)
Critical: ClientInit
Critical: UGameEngine::LoadMap
Critical: LocalMapURL
Critical: UGameEngine::Browse
Critical: ClientTravel
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: ALAudio subsystem shut down.
Exit: UALAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: XOpenGL: ShutdownAfterError
Exit: Exiting.
