### ISSUE TITLE
[469c] DefUser.ini contains unknown keybinds

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1230]
```ini
LeftBracket=hook
RightBracket=hookup
O=Toggle bExtra0
i=turretchangeweapon
O=mutate Kick
U=kamikaze
```

Later in file appear duplicates, which valid keybinds:
```ini
LeftBracket=InventoryPrevious
RightBracket=InventoryNext
```

**Comment by NeonKnightOA** [comment]
Keybinds should've been ordered alphabetically. That would prevent the apparition of duplicates.

As for the other commands, they look like mod commands.

**Comment by OjitroC** [comment]
Those are all Chaos UT controls
Hook/HookUp for the Grapple
Toggle for the Gravity Belt - toggle on/off
TurretChangeWeapon for the turret - switch to the other weapon/ammo
Kick - to "kick things" says the Readme
Kamikaze - blow yourself up!!

**Comment by NeonKnightOA** [comment]
Makes sense, considering Chaos is a semiofficial mod of sorts for UT99.

**Comment by stijn-volckaert** [comment]
I've removed these binds from DefUser.ini.
