### ISSUE TITLE
[469c] Client failed MD5 check for MultiMesh.u / Relics.u

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1236]
```
Checking file MultiMesh.u
Client XXX.XXX.X.XXX:YYYYY failed MD5 check for MultiMesh.u
Level server received: JOIN
Missing required MD5 for MultiMesh.u
Join failure: Missing MD5 checksums.
```

After enabling [MD5 anti-cheat functionality](https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/ReleaseNotes.md#anti-cheat) in 469c server, 469c clients are unable to connect anymore.
[The old incompatible file](https://github.com/OldUnreal/UnrealTournamentPatches/files/11264461/multimesh.zip) comes default with GOTY (v436) and as far I know it originally was included in Bonus Pack.
Currently 469c patch doesn't contain the requested / new file, neither any of the older releases from [the Release page](https://github.com/OldUnreal/UnrealTournamentPatches/releases) do. Neither the Packages.md5 file contains the signature, thus MD5 check fails.

Currently the only solutions for 469c clients to join MD5 servers, are:
   - to manually find the new compatible file on 469 patch github page using github search functionality and then manually replace the old file with the new file
   - to remove the old file and rejoin a server in a hope a server can serve the new compatible file directly or via redirect server
  
Both of the above workaarounds require technical knowledge of which many of players are unaware, which will cause them to not do so, so they won't join the server, which with the small number of players in UT99 is unacceptable, making the MD5 function currently broken and useless which needs to be deactivated until fixed.

Either:
- [the file with MD5 checksums](https://github.com/OldUnreal/UnrealTournamentMD5) should be updated with old versions of the file allowed
- or [the new / compatible file](https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/System/MultiMesh.u) should be included into the official release

Related: https://ut99.org/viewtopic.php?f=33&t=15531

Also:
- possible the same happens for other file: `Client failed MD5 check for Relics.u` but I didn't investigated so far.
- the whole 469c MD5 issue reminds me [the same issue with ACE MD5 whitelist file](https://ut99.org/viewtopic.php?t=12633).
- I'm not sure whether it's also related to https://github.com/OldUnreal/UnrealTournamentPatches/issues/942 (in case the solution will be to include the requested file in the patch itself, instead in the MD5 file).
- I'm aware of existence of [the separate issue tracker for MD5](https://github.com/OldUnreal/UnrealTournamentMD5) but since I don't know where is this going to be fixed (in the patch or in the MD5 file) I decided to create issue on the patch tracker.
- I'm not sure whether the native 469 MD5 functionality is needed at all if the server is already protected by ACE which already uses MD5 checking.

**Comment by stijn-volckaert** [comment]
Fix pushed. Your server will automatically receive the updated list if you have auto-updates enabled. If not, you can download the updated list here: https://github.com/OldUnreal/UnrealTournamentMD5/tree/master/38

I've also updated our build scripts so relics and multimesh will be included with the next patch.
