### ISSUE TITLE
[469c] Ued: Remove the "Hide" button from Surface Properties to save space.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1245]
With the great new additions to the Surface Properties window, it became a little bigger in scale. I suggest removing the useless "Hide" button from the window, in order to save a little bit of space. Here is the new and old Surface Properties window for scale comparison. If we remove the "Hide" button, at least we will match the height dimensions of the old window.

![Screenshot_26](https://user-images.githubusercontent.com/58362332/235369588-edd8a440-037d-42e3-9fb8-6f0b20e84db2.png)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/236667831-d8ef51b2-9262-40ed-a518-25f7e0628101.png)
![img](https://user-images.githubusercontent.com/70026933/236667837-8d1a06fe-280e-42f6-b91d-ed29cccbc0db.png)
![img](https://user-images.githubusercontent.com/70026933/236667843-9d11188e-3b9d-478c-b7e4-702783d3fd86.png)
