### ISSUE TITLE
Could not load splash logo error?

### ISSUE THREAD

**Issue by Paraclete316** [OldUnreal/UnrealTournamentPatches#1247]
Thoughts?

Init: Memory total: Phys=4194303K Pagef=4194303K Virt=4194176K
Init: Working set: 32000 / 159000
Init: CPU Page size=4096, Processors=4
Init: CPU Detected: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (GenuineIntel)
Init: CPU Features: INVARIANT_TSC CMov FPU RDTSC PAE MMX SSE SSE2 SSE3 SSSE3 SSE4_1 SSE4_2 AVX AVX2
Init: Timer Frequency=2399.999300 MHz - Timing Source = RDTSC
Critical: appError called:
Critical: Could not load splash logo: ..\Help\Logo.bmp
Critical: Windows GetLastError: The system cannot find the file specified. (2)
Exit: Executing UObject::StaticShutdownAfterError
Exit: Exiting.
Log: Log file closed, 05/01/23 23:21:06

**Comment by SeriousBuggie** [comment]
Did you try run game with applied patch?
Or you unpack patch in empty dir and try run it?

Patch is like addon to original Game. You still need original game for able use patch.

**Comment by stijn-volckaert** [comment]
As @SeriousBuggie said, you only get this error if you don't install the patch on top of an existing installation.
