### ISSUE TITLE
[469c] Optimize append strings in UdpServerQuery

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1249]
As I recently found - some IPs flood to query port with query `\status\` 10 times per second.

It create huge load. Inside UdpServerQuery often used append as create new strings:
`ResultSet = ResultSet$"\\maptitle\\"$StrReplace(Level.Title, "\\", "");`
such thing must be rewrite as:
`ResultSet $= "\\maptitle\\"$StrReplace(Level.Title, "\\", "");`
For reduce load by processing incoming queries.

**Comment by SeriousBuggie** [comment]
Also this story can be extended to GameInfo Classes or even whole stock code.

**Comment by an-eternity** [comment]
I have fixed this problem in modified UdpServerQuery a long time ago - it updates the result string once per specific time interval, not per each query.
But then found another problem, on the native part - in case of some flood types `ReceivedText()` event won't be called at all (for any queries from any addresses), which makes UC level filters to be useless...

**Comment by an-eternity** [comment]
I have fixed this problem in modified UdpServerQuery a long time ago - it updates the result strings once per specific time interval, not per each query.
But then found another problem, on the native part - in case of some flood types ReceivedText() event won't be called at all (for any queries from any addresses), which makes UC level filters to be useless...

**Comment by an-eternity** [comment]
And one else problem:

>  $= 

This operator is not supported...

**Comment by SeriousBuggie** [comment]
$= supported after v451 AFAIK.
