### ISSUE TITLE
[469c] GPF in UnrealEd when unaligning a "broken" surface

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1254]
In a map are a few "broken" surfaces, and when I select them and choose "Unalign", UnrealEd throws an GPF.
Details, Download link and Screenshots see https://ut99.org/viewtopic.php?p=142866

**Comment by SeriousBuggie** [comment]
Well all ok here if not use Software render.

D3D9:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0d19264b-0961-4cc8-babf-b93a250ecb0c)
xOpenGL;
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/15add7d5-4a39-4f6c-87f7-7dd7910a6261)
OpenGL:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/9de83a21-f418-4c52-8687-34906a022c30)
Software:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/5542e3a4-1208-40c1-ab62-9c230e97f220)

I think time move to use something different from Software render. It bugged itself and can mislead you to problems, which not exists.

It near ASMDAmmo0 if someone search this point.

Crash info:
```
History: ABrush::BuildCoords <- UEditorEngine::polyTexAlign <- (Type=0,Texels=0) <- UEditorEngine::Exec <- (POLY TEXALIGN DEFAULT)
SE(C0000005) @ 6C3E91EE
fl=0 rec=0 n=1817246576 i[0]=0 i[1]=240
eax=013dd588 ebx=013dd798 ecx=013dd4c8 edx=01727a14 esi=013dd4c8 edi=00000234 eip=6c3e91ee
ebp=013dd4b8 esp=013dd47c cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010206
In module 'Z:\UT_469c\System\Core.dll' at address 000191ee
 <- WEditorFrame::OnCommand <- WM_COMMAND
```

**Comment by SeriousBuggie** [comment]
Crash happens inside `[FCoords::operator*=](public: class FCoords & __thiscall FCoords::operator*=(class FScale const &))`
at `movss   xmm0, dword ptr [edi+0Ch]`
edi is first argument passed via stack. 

```c++
	FLOAT BuildCoords( FModelCoords* Coords, FModelCoords* Uncoords )
	{
		guard(ABrush::BuildCoords);
		if( Coords )
		{
			Coords->PointXform    = (GMath.UnitCoords * PostScale * Rotation * MainScale);
			Coords->VectorXform   = (GMath.UnitCoords / MainScale / Rotation / PostScale).Transpose();
		}
		if( Uncoords )
		{
			Uncoords->PointXform  = (GMath.UnitCoords / MainScale / Rotation / PostScale);
			Uncoords->VectorXform = (GMath.UnitCoords * PostScale * Rotation * MainScale).Transpose();
		}
		return MainScale.Orientation() * PostScale.Orientation();
		unguard;
	}
```
So I guess BuildCoords just called on NULL or Brush with NULL in PostScale or MainScale.

Possible need check this case in `UEditorEngine::polyTexAlign`.

```c++
							case TEXALIGN_Default:
								Orientation = Poly->Actor->BuildCoords(&Coords, &Uncoords);
```
So there neec check if `Poly->Actor` is not NULL, before start do something.

`Poly->Actor` used in other textures align as well, so I guess need fix all at once.

**Comment by SeriousBarbie** [comment]
I changed renderer to Direct3D9 and tried also XOpenGL but GPF still happens when trying to unalign one of the surfaces of that brush.

**Comment by SeriousBuggie** [comment]
Yes. I describe above why for devs.
