### ISSUE TITLE
[469c] Add more ServerActors for UdpServerUplink in patch

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1256]
Near same as #1255 but for report on master servers

```
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.newbiesplayground.net MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.gonespy.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master-uk.unrealarchive.org MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master-de.unrealarchive.org MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master2.qtracker.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.frag-net.com MasterServerPort=27900
```

**Comment by garry-ut99** [comment]
Too many Uplink servers can cause server lagging like a hell, I experienced it on my own server.
I had 20 uplink servers in my server's ini, and a a result, in a client in-game's server browser the ping was over 1000, and after a while it was going to 9999 and unreachable.
Then I removed several uplink servers from ini, ping has reduced to 800 and not going to 9999 anymore.
Then I removed another bunch of uplink servers from ini, ping has reduced further and so on.
Until I left only a small hand of uplink servers, my server's ping was reducted to 30 then.
Still, I decided to leave only 1 uplink server, and didn't check whether 2, 3 or 4 would incerase server's ping over 30, but I preferred not to take the risk.

Also I remember someone else already speaking about it somewhere, but I can't find it.

**Comment by SeriousBuggie** [comment]
It related to how many your server ping itself. possible your server affect to this issue #1218 

Itself uplink actors must not affect server ping it all. 

But if your server affected by #1218, then less uplinks means your server is less visible in net, less pinged and less lagged. But this not good for your server, because less players can find it.

**Comment by garry-ut99** [comment]
> then less uplinks means your server is less visible in net  
> But this not good for your server, because less players can find it.

Not true, https://333networks.com/faq#how-do-i-select-a-masterserver:
they clearly say that 333networks is designed to work with multiple (affiliated) masterservers that synchronise with each other, which means that adding any random single 333network master server to server ini and client ini is sufficient to see each other. 

The only purpose of having more than 1 master server, is in case one or more of them will down, in that case I think having 3 is sufficient, as it's unlikely to more than 2 different server being down at the same moment.
