### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by CaptChaos1994** [OldUnreal/UnrealTournamentPatches#126]
Hey There! 
i'm having issues if i launch new Patch469a
it crash my game all the time.

it says { MissingIni} History Appinit

can anyone help me already Thank you

Greetings CC

**Comment by NeonKnightOA** [comment]
Do you have Core.int in the System folder? If not, copy the .int files of the folder SystemLocalized into the folder System.

**Comment by CaptChaos1994** [comment]
ehm i will look for it but OS windows right Windows 10 👍

**Comment by CaptChaos1994** [comment]
core.int is in it

**Comment by CaptChaos1994** [comment]
i have copy all things in system folder to new system folder and get new error

assertin failed:bimap.loadfile(filename)
[File:..\..Engine\Inc\UnEngineWin.h] [Line: 55]
History

**Comment by stijn-volckaert** [comment]
You are supposed to install the patch on top of an existing installation of UT. The assertion error triggers because the launcher doesn't find the splash bitmaps in the help folder
