### ISSUE TITLE
[469c] CRASH - Critical Error - General protection fault ! 

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1260]
Happened two times already:

![CrashToDesktop](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/27e2fe02-11bd-490e-aaf1-f988d3d1fa70)

**Comment by SeriousBuggie** [comment]
Also now i notice there ACE stuff. Possible it related to ACE. And after update it (there not latest version AFAIK) issue gone.

**Comment by Chamberly** [comment]
What server it was on?

**Comment by garry-ut99** [comment]
> Is there any steps for reproduce?
> What server it was on?

LONDON server, the crash occured after a map/game ended and while we're waiting for the next map/game to load, unfortunately my `UnrealTournament.log` was overwritten since then.

**Comment by stijn-volckaert** [comment]
This is an ACE bug. I fixed this in ACE v1.3, but I haven't released the update to the public yet. I'm planning to do that soon

**Comment by garry-ut99** [comment]
![crash22](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/356e6687-1543-437f-892a-ce5f091a278d)
