### ISSUE TITLE
[469c] Mouse cursor hidden (not visible) if first press Escape when mouse out of game window

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1261]
Reproduce steps:
1. Ensure in UnrealTournament.ini
`LocalMap=CityIntro.unr`, not something else.
2. Start game in windowed mode (`StartupFullscreen=False` in ini)
3. Place mouse outside of game window.
4. Press Escape.

Expected result: Mouse cursor visible when mouse over game window.
Actual result: Mouse cursor visible when mouse outside game window, and hide if mouse over game window.

I use Cursor input, but I guess this happen on any type of input.
Same with Windows version. I use Win7.

There video from Chamberly about it: https://www.youtube.com/watch?v=qJ06Q7D3WNI

**Comment by Chamberly** [comment]
I use Windows Server 2012 R2.

I notice if the window is on the specific alignment to the far right, it will capture it. If the window is on the left it'll catch it ok. But anytime a gap is between on the right, it can't display the mouse in game. The video will demonstrate that kind of detail but I'm mentioning it here so it'll be easier to look for what's going on.

**Comment by SeriousBuggie** [comment]
If game capture mouse, then need use complicated way:

During game start, fast switch to any other app.
After that cursor will be handled in rectangle. Use alt-tab for switch back to ut.
And you got free cursor, which can be away when you press esc and issue happen.
