### ISSUE TITLE
[469c] Game is lanuched with distorted sound

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1265]
Ocassionally when I launch UT99, the game runs with distorted sound since the beginning.
In that case I need to restart the game again or several times to make the distortion go away.
The same was happening very often in old 436, now happens not so often, but still happens from time to time.
My audio settings: Galaxy 3D: [Screenshoot](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/d6b023b1-92cf-4cfa-b499-681a84e01de6), My Sound Card: Realtek High Definition Audio

**Comment by SeriousBuggie** [comment]
Galaxy is outdated audio driver. Suggest you switch to OpenAL or Cluster.
Not sure if all issues of Galaxy can be fixed.

**Comment by garry-ut99** [comment]
The problem is the other audio drivers sound strange and different, and also too quiet. (shoots etc) and I can't get used to them, once I switch back to Galaxy, everything is great and loud.

**Comment by SeriousBuggie** [comment]
Well, just for clarify, Galaxy bugs can make sounds over-loud with great distortion effects. So it can be issue itself, and sometimes need introduce hacks in mods, which not always possible if mods not update anymore.

**Comment by garry-ut99** [comment]
Lol OK, I think I think I'll have to get used to OpenAL or Cluster then, instead of complaining, I should act like a man with balls ! I can handle that ! Thx.
