### ISSUE TITLE
[469c] Crash To Desktop (Critical Error) when trying to switch to FMOD audio driver

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1266]
I've been switching to other audio drivers as advised / suggested [HERE](https://github.com/OldUnreal/UnrealTournamentPatches/issues/1265#issuecomment-1562880438), and one of them (FMOD) has crashed while trying to switch to: [SCREENSHOOT](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/e39baa5b-8ca8-44cc-90d4-7b5c5cd3c2a4) , maybe I have some files missing? By the way also I've found another crash with FMOD https://github.com/OldUnreal/UnrealTournamentPatches/issues/139.

**Comment by garry-ut99** [comment]
Oh ok, so a small summarision:
- FMOD uadio driver is unsupported anymore
- and Galaxy driver is problematic
- so we should use OpenAL or Cluster

**Comment by stijn-volckaert** [comment]
We still fix stability problems in Galaxy, but are not doing anything else with it. ALAudio and Cluster both have an active maintainer. Cluster is based on the modern version of FMOD by the way...
