### ISSUE TITLE
469c file Engine.u

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1269]
i got this error with a map 

Log: Failed import: ArrayProperty ArrayProperty Engine.Weapon.bTossedOut (file ../System/Engine.u)
Log: Failed import: BoolProperty BoolProperty Engine.Weapon.bTossedOut (file ../System/Engine.u)
Warning: Failed to load SP_XidiaMPack: Can't find BoolProperty in file BoolProperty Engine.Weapon.bTossedOut..
Warning: Failed to load MH-[SP]HardstyleFacility: Can't find BoolProperty in file BoolProperty Engine.Weapon.bTossedOut..
Warning: Failed to load "Texture MH-[SP]HardstyleFacility.Screenshot": Can't find BoolProperty in file BoolProperty Engine.Weapon.bTossedOut..
Log: Failed import: ArrayProperty ArrayProperty Engine.Weapon.bTossedOut (file ../System/Engine.u)
Log: Failed import: BoolProperty BoolProperty Engine.Weapon.bTossedOut (file ../System/Engine.u)
Warning: Failed to load SP_XidiaMPack: Can't find BoolProperty in file BoolProperty Engine.Weapon.bTossedOut..
Warning: Failed to load MH-[SP]HardstyleFacility: Can't find BoolProperty in file BoolProperty Engine.Weapon.bTossedOut..
Warning: Failed to load "LevelSummary MH-[SP]HardstyleFacility.LevelSummary": Can't find BoolProperty in file BoolProperty Engine.Weapon.bTossedOut..

**Comment by stijn-volckaert** [comment]
Unreal Tournament 432 (and later) never had an Engine.Weapon.bTossedOut property. It looks like this is an Unreal-only map

**Comment by SeriousBuggie** [comment]
in UT bTossedOut is field of Inventory, not Weapon.

Also usually `[SP]` in map name pointed to "unreal-only" map.

**Comment by Letylove49** [comment]
thanks you  that help me to understant why i got this,
