### ISSUE TITLE
[469a] Player not fall after teleport if use Crouch or Walk

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#127]
Reproduce:
1. Start map
[DM-AAA_Tele.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5403583/DM-AAA_Tele.zip)
2. Crouch or Walk and enter to teleport.

Expected result: Player fall to ground.
Actual result: Player stuck on air until release Walk or Crouch key.

v469a: bugged.
v436: bugged.

**Comment by PPeltzer** [comment]
I would like to add that this used rather as a feature in BT maps. Some of them will become uncapable if this is fixed.

**Comment by Sp0ngeb0b** [comment]
I would like to add that fixing this behavior will break some BT maps which will become uncapable.

**Comment by an-eternity** [comment]
This is general behavior, not only teleport related.
For example, if crouching/walking player is located right upon another colliding actor that has some non-zero collision size, and then that actor is destroyed, player will not fall down, will hang 'in the air' as long as Walk or Crouch key is pressed.

**Comment by zero-khan** [comment]
This isn't a bug. It's this way since ever. Some maps are made with this behavior in mind.

**Comment by Chamberly** [comment]
This one can have some arguments. There are maps that are made with using that mostly in BT, and there are other maps like sniper maps that are designed not to use that but it get super annoying when Bots are stuck in the tele and no one can go through it. Not only that but some people use the teleporter glitch just to do the image dropping glitch to take advantage of owning more frags than other which is another downside in the DM/TDM games. So as I'm speaking of what I've seen for the most part, it may not be exactly as it is as other players from other game know where it has been abused the most or so.

If anything, I would rather suggest it should be toggleable on/off to use it or not. Siege has implemented it's own anti-image dropping from it as well and to stop players from staying in the tele.

**Comment by OjitroC** [comment]
I think that altering this behaviour might break the Matrix Moves mutator as this includes the ability to 'freeze' in mid-air using Crouch.

Sektor2111 at UT99.org has a mutator that prevents bots/players getting stuck or camping in teleporters.

**Comment by stijn-volckaert** [comment]
I don't think it makes sense to change this behavior given that several maps and mods rely on it. I'm marking this as wontfix
