### ISSUE TITLE
[469c] Game nullify sounds embed into map on save as filesave if used Blank.umx music

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1275]
Reproduce:
1. Start map  [TestSaveWithEmbedSound.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11603198/TestSaveWithEmbedSound.zip) (for example open in Editor and press Play)
2. In console input `savegame 0`
3. Try play it in game via `start ..\Save\Save0.usa` (Windows)

Expected result: Start play in game.
Actual result: Crash in game.
```
History: FWaveModInfo::ReadWaveInfo <- FSoundData::GetPeriod <- FSoundData::Load <- TLazyArray<< <- USound::Serialize <- 
LoadObject <- (Sound save0.Package1.growl1 6907==6907/9608 6901 7) <- ULinkerLoad::Preload <- PreLoadObjects <- 
UObject::EndLoad <- UObject::StaticLoadObject <- (Engine.Level None.MyLevel ..\save\save0.usa) <- LoadLevel <- 
UGameEngine::LoadMap <- LocalMapURL <- UGameEngine::Browse <- ClientTravel <- UGameEngine::Tick
SE(C0000005) @ 017D61D1
fl=0 rec=0 n=269302656 i[0]=0 i[1]=8
eax=0107e624 ebx=0107e64c ecx=0107e64c edx=00000000 esi=00000000 edi=0baedb98 eip=017d61d1
ebp=0107e630 esp=0107e604 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010246
In module 'Z:\UT_469c\System\Engine.dll' at address 001361d1
 <- UpdateWorld <- MainLoop
```

Reason: On map embed wav files. It nullified when save. Look like lazy load arrays not properly init on dump map to file.

Note. This happen only if music on level set to Blank.umx. Look like this manually crafted file, which so bad, so destroy lazy loaders for load actual sound data.

**Comment by stijn-volckaert** [comment]
I made SaveGame force-load all lazy-loaded MyLeveled content to fix this
