### ISSUE TITLE
UnrealEd: 'Select All UnrealShare.ScriptedPawns' does not work

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1278]
Map setup with at least 3 ScriptedPawns of 2 different types. Select ScriptedPawn of type 1 AND ScriptedPawn of type 2. Right click on it shows the context menu (see  screenshot). Choosing "Select All UnrealShare.ScriptedPawns" should select more ScriptedPawns but selection does not change.
![Select_All_UnrealSchare ScriptedPawns](https://github.com/OldUnreal/UnrealTournamentPatches/assets/81397053/826dd672-b3eb-4862-887e-7ff7af00b85f)

**Comment by SeriousBuggie** [comment]
This menu do exact what it say - it try select UnrealShare.ScriptedPawn Actors. There no such actors, so this not change selection.

Pay attention to difference between "select UnrealShare.ScriptedPawn Actors" and "select Actors of subclass".
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/36de2850-2f35-4a98-a498-29e9a6a6c107)

It is different things.

For example when you select NavigationPoint on map and use this menu item, you expect select items which Exact NavigationPoint, not all subclasses of it.

So when you select PathNode + LiftExit, editor determine base common class and show here. And it be "select NavigationPoint Actors", like above. Same thing must act same. So if it say Select Actor of Class, this never count subclass.

**Comment by SeriousBarbie** [comment]
Thanks for answer.
This is a great example of different understanding of action: Obviously I expected that Actors that are ScriptedPawns will be treated. And a Pupae is a ScriptedPawn, like in understanding of function IsA().

May I ask what the sense of the current implementation of the context menu is?

And what I noticed from your screen shot: I didn't know that it is possible to select Actors _in map_ from the Actor Class Browser. (In my understanding and experience a context menu affects things that you selected, in this case an item in the Actor Class Browser.)
But nice that such a feature exists; so this case may be closed.

**Comment by SeriousBuggie** [comment]
> May I ask what the sense of the current implementation of the context menu is?

IDK. But we must keep things which exists, since it important for users which grown up on previous versions.

I same as you, already stuck on this problem, but later realize reasons explained above. So we simple can't change it, not ruin old habits.

Because of that added new items on actor class tree context menu.
