### ISSUE TITLE
texture bug in xtortion?

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#128]
This has been noticed by me for a long time. eb_floor1 is pixelated in game, as if filtering was disabled. But in editor it's filtered, not pixelated.

Is there a bug in xtortion.utx??

![Untitled-1](https://user-images.githubusercontent.com/72151582/96785444-31356500-13c5-11eb-97f4-f7a8b905db40.jpg)

**Comment by sn260591** [comment]
This is likely the same problem https://github.com/OldUnreal/UnrealTournamentPatches/issues/64
