### ISSUE TITLE
[469c] Command 'Reconnect' after play demo crash game

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1280]
Reproduce:
1. start play any demo with full path and quotes, like this one: `demoplay "Z:\UT_469c\Demos\CTF-XV-GooYou-MiAv1_06-01_00-15-56.dem"`.
2. Stop play demo, via disconnect.
3. Call reconnect from console or menu item.

Expected result: Demo start play again.
Actual result: Crash.
```
---------------------------
Critical Error
---------------------------
Assertion failed: InPos<=Size [File:z:\ut_469c\core\inc\ffilemanagerwindows.h] [Line: 90]

History: FArchiveFileReader::Seek <- ULinkerLoad::Seek <- FUnrealfileSummary<< <- LoadSummary <- 
ULinkerLoad::ULinkerLoad <- UObject::GetPackageLinker <- UObject::StaticLoadObject <- 
(Engine.Level None.MyLevel Z:\UT_469c\Demos\CTF-XV-GooYou-MiAv1_06-01_00-15-56.dem) <- 
VerifyPackages <- UGameEngine::LoadMap <- LocalMapURL <- UGameEngine::Browse <- ClientTravel <- 
UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```

Look like game try use demo file as map file.

**Comment by stijn-volckaert** [comment]
I cannot reproduce this

**Comment by SeriousBuggie** [comment]
You need  play demo with demo manager and path like mine: `demoplay "Z:\UT_469c\Demos\CTF-XV-GooYou-MiAv1_06-01_00-15-56.dem"`.

Attempt play demo via `demoplay 1` will not reproduce issue.
