### ISSUE TITLE
[469c] Tactical Ops crashes when joining online game

### ISSUE THREAD

**Issue by fabiangebert** [OldUnreal/UnrealTournamentPatches#1283]
On macOS, when I use an exact copy of the TO350 folder (from https://tactical-ops.eu Fixed Pack 469c) as the contents for the `Unreal Tournament` folder in `Application Support` (and rename `TacticalOps.ini` with the `System` folder to `UnrealTournament.ini`), I can start Unreal Tournament using the `.app` file from the 469c macOS patch, effectively starting Tactical Ops and start a practice session.
However, once I join the actual game, it crashes with the following message:

`History: ArrayElementCopySingleValue <- UObject::execArrayElement <- UObject::ProcessEvent <- UObject::GotoState <- UObject::ProcessEvent <- UEngine::InputEvent <- USDLViewport::CauseInputEvent <- USDLViewport::UpdateInput <- UViewport::ReadInput <- AActor::Tick <- TickAllActors <- ULevel::Tick <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- MainLoopIteration <- MainLoop <- main`

Using macOS 13.4 on an M1 Apple Silicon machine, 64-bit.

**Comment by fabiangebert** [comment]
It works with the following method:
* copy TO3.5 folder from TO Fixed Pack with 469c patch included to `~/Library/Application Support/Unreal Tournament`
* rename `~/Library/Application Support/Unreal Tournament/System/TacticalOps.ini` to `UnrealTournament.ini`
* replace all files in ~/Library/Application Support/Unreal Tournament/System` except `BotPack.u` and `UTMenu.u` with the updated files from `UnrealTournament.app` 469d patch
* launch `UnrealTournament.app` (469d patch version)

**Comment by drkdw** [comment]
HI @fabiangebert, I want to try TO on Mac. But first things first, where do I get Unreal Tournament itself to be able to replace it with TO?

**Comment by SeriousBuggie** [comment]
Buy CD/DVD on second market, like ebay.

**Comment by fabiangebert** [comment]
@drkdw you don't need Unreal Tournament for that.

**Comment by drkdw** [comment]
@fabiangebert I'm confused. I downloaded TO but this is just a zip and exe files. This works on my windows but wanted to play on Mac. But I'm probably missing some info/steps as I also don't have 'UnrealTournament.app'.

**Comment by fabiangebert** [comment]
OK, let me update the instructions *how to play Tactical Ops 3.40/3.50 on macOS* reflecting the most recent update:
1) download _TO Fixed Pack_ from [tactical-ops.eu](https://tactical-ops.eu/to-aot-fixed-pack.php) version v469d RC4 (the v469c version requires patching)
2) extract _TO Fixed Pack_
3) create folder `~/Library/Application Support/Unreal Tournament/`
4) move all contents from the TO350 or TO340 folders from the extracted _TO Fixed Pack_ to `~/Library/Application Support/Unreal Tournament/`
5) download UnrealTournament executable for macOS from [here](https://github.com/OldUnreal/UnrealTournamentPatches/releases/tag/v469d-rc4) (it's a `dmg` file that contains the `app` file to launch the game)
6) rename `TacticalOps.ini` in `~/Library/Application Support/Unreal Tournament/System/` to `UnrealTournament.ini`

Hope that helps @drkdw

**Comment by drkdw** [comment]
Thanks for clarifying. I just tried it but get the follow error on starting UnrealTournament.app

Failed to enter Entry: Can't find file Entry.
History: UGameEngine::Init <- InitEngine <- main

**Comment by fabiangebert** [comment]
The folder will be created by the `.app`, so make sure to delete the contents before repeating the instructions from above.

**Comment by drkdw** [comment]
Hi @fabiangebert, thanks again for folowing up. Still getting errors. I add them below but I understand if you can't help.

Also not sure why it says "File:/Users/stijn/" I don't have a useraccount named that way.

`Assertion failed: GetPropertiesSize()>=sizeof(UObject) [File:/Users/stijn/UnrealTournament/Core/Src/UnClass.cpp] [Line: 1241]

History: UClass::Serialize <- LoadObject <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::CreateExport <- IndexToObject <- ULinkerLoad<<UObject <- ULevelBase::Serialize <- ULevel::Serialize <- LoadObject <- ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- LoadLevel <- UGameEngine::LoadMap <- UGameEngine::Init <- InitEngine <- main`

**Comment by fabiangebert** [comment]
@drkdw I guess that refers to a file on the computer where the app was 
compiled, not sure however.

What's your OS version and hardware?

I'm running macOS 14 on a M1 Apple Silicon.

**Comment by drkdw** [comment]
@fabiangebert that's odd, because there is no user 'stijn'.

I am also on Mac OS 14.1.1 and M1 Apple Silicon.

I'll repeat my steps here what I did now:
- Download and install: OldUnreal-UTPatch469d-macOS.dmg (this creates a "System" folder in 
- "/Users/drkdw/Library/Application Support/Unreal Tournament/"
- Download, unzip and overwrited TO340 contents to /Users/drkdw/Library/Application Support/Unreal Tournament/
- Renamed "UnrealTournament.ini" to "OG_UnrealTournament.ini" and renamed "TacticalOps.ini" to "OG_UnrealTournament.ini'
- Open UnrealTournament.app via finder
- Get errros

**Comment by stijn-volckaert** [comment]
TO has a custom version of Botpack.u and UTMenu.u. You might want to move those back into the Application Support folder.

All other stock UT .u files should be deleted, though, since the application bundle contains updated versions of those files. Concretely, you do not want any of the following files in your Application Support/Unreal Tournament/System folder:
* Core.u
* Editor.u
* Engine.u
* Fire.u
* IpDrv.u
* IpServer.u
* UBrowser.u
* UMenu.u
* UTBrowser.u
* UTServerAdmin.u
* UWeb.u
* UWindow.u
* UnrealI.u
* UnrealShare.u
* WinDrv.u
* Window.u
* udemo.u
* epiccustommodels.u
* relics.u
* multimesh.u

Sorry for the outrageously complicated installation process. We cannot legally distribute a proper application bundle for tactical ops, so you need to piece it together yourself.

**Comment by drkdw** [comment]
No worries, I'm glad you're sticking with me for now ;)

I removed the suggested .u files, I only don't have these:

- WinDrv.u
- Window.u
- udemo.u
- epiccustommodels.u
- relics.u
- multimesh.u

I also put back  Botpack.u and UTMenu.u from the TO folder. 

Not sure we are close but this is the next error:

```
Failed to enter CityIntro.unr: Can't find file CityIntro.unr.

History: UGameEngine::Init <- InitEngine <- main
```

**Comment by stijn-volckaert** [comment]
Your UnrealTournament.ini file (that should be in ~/Library/Application Support/Unreal Tournament/System) probably specifies CityIntro.unr as the intro map. You can switch to another intro map by changing the LocalMap property in the [URL] section. I recommend that you look at your TacticalOps.ini file and copy the value for LocalMap from that file.

**Comment by drkdw** [comment]
Hmm, I tought I used the TacticalOps.ini and renamed it to UnrealTournament.ini. But I did this step again and what do you know, It's working now! Thank you @stijn-volckaert and @fabiangebert for your patience. I look forward to encountering you on the TO servers someday.

**Comment by drkdw** [comment]
Any idea why I can't join a team? Happends on only a specific server. Another server I tried has no issue. On windows I can join the specific server without a problem.

**Comment by Tragio** [comment]
@drkdw talk with LuckyDog on the Discord server and say you are playing on Mac, he will give you a key to bypass a server protection that is not compatible with Mac/Linux. 🙂 

https://discord.gg/EHMfnqr

**Comment by drkdw** [comment]
Thanks for the tip ;) I contacted Luckydog and got it to work!
