### ISSUE TITLE
[469a] UnrealEd make too many paths between PathNodes

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#129]
Reproduce:
1. Open [DM-Pathes](https://github.com/OldUnreal/UnrealTournamentPatches/files/5413392/DM-Pathes.zip) in UnrealEd.
2. Show paths.
3. Build paths.

Expected result: Reasonable amount of paths.
Actual result: Hell of paths:
![scr_1603256953](https://user-images.githubusercontent.com/70026933/96676176-67e38f00-1375-11eb-89a4-6afc89557c98.png)

v469a: bugged.
v436: bugged.

**Comment by CacoFFF** [comment]
There's two ways of "fixing" this:
1 - Rewriting the paths rebuilder from scratch
2 - Using dynamic temporary buffers for path rebulding and then discarding anything over "16".

I've been experimenting with option 1 for a while lately in XC_Engine, this doesn't make maps incompatible at all.
![imagen](https://user-images.githubusercontent.com/15526924/96685765-93ea1a80-134b-11eb-9283-b0f74b8763b0.png)

**Comment by SeriousBuggie** [comment]
I not search way for fix this. I report bug. Building paths on UEd definitely bad do that job. Need fix algorithms.
Not create thousand workarounds over editor for good results.
This like write in manual: "Do not press button A after B or editor crash" instead of find and fix reason.

Such things must work like this: drop pathnodes or even press special button for UEd place this PathNodes for you, build paths and get reasonable network in few clicks. From box. Not install third party tools and so on.

It same as map CTF-Blice-Alpha - it is do brushes semi-solid because its must be there semi-sold. It is produce bad result in current UEd, and can not be fixed (or improved) by change some to solid, but this not goal of author.
Author do not want make map which good run in exists (bad) condition. He want have map which properly builded for find and fix bugs in UEd and make things how they can be.

Same here.

**Comment by CacoFFF** [comment]
I mention it because this will affect the path builder's behaviour significantly, to the point mappers would have to change how they place path nodes.

**Comment by SeriousBuggie** [comment]
I do not see any reason why UnrealEd can not build network like on your picture out of box.

Of course proper mapping is important but UnrealEd must fine work with such pathnodes. I do not see something very bad on it.

Of course if task too hard, for example NP-full, this can not be done, but I think this not that case.

**Comment by SeriousBuggie** [comment]
Another example: 
![scr_1603558271](https://user-images.githubusercontent.com/70026933/97087378-6397ca00-1632-11eb-9f86-a10038ad5020.png)
Map: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/A/mh-airportterrorsb_1ccd2bf1.html

This is a purely algorithmic task - building a flat graph with some restrictions. I don't see any difficulties in its implementation.

**Comment by SeriousBuggie** [comment]
There a few problems.
1. When UnrealEd build paths it leave all pruned paths in PrunedPaths array.
2. UnrealEd draw PrunedPaths same as usual paths. In fact PrunedPaths only use for APawn::CanMoveTo and only after usual paths list fail. So no any harm about big count pruned paths.
3. UnrealEd just draw all exists reachspecs, even if it not referenced by any node.
4. UnrealEd prune only paths which can be replaced with one intermediate point. If point two or more this paths not pruned.

**Comment by SeriousBuggie** [comment]
Also something going wrong with path creation:
I see `upstreamPaths` which not listed in `Paths` on start node.
Because algorithm for prune paths walks only by `Paths` - this reachspecs leaved unchecked.
But UnrealEd for draw just walk on entire reachspecs lists, doesn't matter listed path for start and/or end node or not.

**Comment by SeriousBuggie** [comment]
For reproduce you can build paths on map from first post and watch paths between PathNode918 and PathNode824. I drag its outside for show: paths exists in both ways:
![img](https://user-images.githubusercontent.com/70026933/127733287-fe74f3be-af4b-45d5-9363-83da639e6cf1.png)
After that you can copy both actor to clipboard.
Each path must be listed in two places `Paths` and `upstreamPaths`. So for this case you must see same number in PathNode918.Paths and PathNode824.upstreamPaths.
Same for vice versa.
But there no same numbers.

**Comment by SeriousBuggie** [comment]
```
Log: Fix reachspecs
Log: Fixed 327 reachspecs: use pruned - 0, path without upstream - 16, upstream without path - 311
```
![img](https://user-images.githubusercontent.com/70026933/127734811-f75e4709-4561-4255-be8e-2fc475135b13.png)
Even without improve prune paths.

There as fix use prune for any wrong state.

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/127735275-832a17f7-5cc0-451f-9090-4788b418ccac.png)
```
Log: Fixed 15131 reachspecs: use pruned - 0, path without upstream - 139, upstream without path - 14992
```
![img](https://user-images.githubusercontent.com/70026933/127735293-bb16bd99-49d7-4326-a4c2-81cdfec01d5b.png)

**Comment by SeriousBuggie** [comment]
With check for full lost paths:
`Log: Fixed 15131 reachspecs: use pruned - 0, path without upstream - 139, upstream without path - 1474, lost path - 13518`

This situation very bad.
Possible this is reason why paths stop work on some cases.

Also this mean map can be with broken network in inconsistent state. So some fixes must be done at runtime on load map.

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/127736096-aea74007-044e-4c45-8747-c9eb97bcf884.png)
```
Log: Fix reachspecs
Log: Fixed 327 reachspecs: use pruned - 0, path without upstream - 16, upstream without path - 114, lost path - 197
Log: Prune reachspecs
Log: Pruned 242 reachspecs
Log: Fix reachspecs
Log: Fixed 0 reachspecs: use pruned - 0, path without upstream - 0, upstream without path - 0, lost path - 0
```
More proper way. we repair all damaged paths instead of prune it. After it make proper search for prune pathes.

![img](https://user-images.githubusercontent.com/70026933/127736230-483edb51-cda3-4b68-912a-74f8abf5e959.png)
```
Log: Fix reachspecs
Log: Fixed 15131 reachspecs: use pruned - 0, path without upstream - 139, upstream without path - 1474, lost path - 13518
Log: Prune reachspecs
Log: Pruned 5841 reachspecs
Log: Fix reachspecs
Log: Fixed 0 reachspecs: use pruned - 0, path without upstream - 0, upstream without path - 0, lost path - 0
```

**Comment by SeriousBuggie** [comment]
Summarize:
1. UnrealEd built not consistent path network - need apply fix during built paths.
2. Loaded map can contain saved not consistent path network - need apply fix during load map process.

Possible breakable change: some mods or "smart" mapmakers can oriented to bugged implementation and use reachspecs, which not listed anywhere, for later dynamically switch paths by some event.

If fix do something about unlisted paths, then this hack stop work.
If fix do nothing about unlisted paths, then UnrealEd able show fake paths which not exists in game.

**Comment by SeriousBuggie** [comment]
If we decide not fix not listed paths, then need fix display code in UnrealEd. And not show this paths. 
Or show with special color. But not clear for what, because currently there no any tool for edit it.
But in anyway UnrealEd must built fully consistent paths network without any unlisted reachspecs.
