### ISSUE TITLE
[469c] Can't find file for package

### ISSUE THREAD

**Issue by kairos63** [OldUnreal/UnrealTournamentPatches#1293]
When i try to connect to one of the online games:
Evils Freestyle Sniper Deathmatch

Connection failed:
Can't find file for package ACEv12e_C.  

I also then tried a fresh 469c install and hit play : exact same error

and also screen for UT is much darker since i re ran the 369c patch!
I changed nothing else on my machine.
PC windows pro 10
UT 469c

**Comment by stijn-volckaert** [comment]
Could you attach your UnrealTournament.log please? I suspect this happens because the game server is trying to force you to download the file from a redirect server that is either offline or that doesn't host the file (anymore)

**Comment by kairos63** [comment]
Thank you for responding! Here is my  log file for you to look at - most appreciative.

**Comment by kairos63** [comment]
Does anyone have an idea why i can no longer access server:
 [-=][-=NFR=-][=-Evil's Freestyle Sniper Deathmatch]

It was working fine for years.
Now i get Connection failed:
Can't find file for package ACEv12e_C.

Thanks in advance for any tips ;)

**Comment by kairos63** [comment]
attached above thank you

**Comment by kairos63** [comment]
> Could you attach your UnrealTournament.log please? I suspect this happens because the game server is trying to force you to download the file from a redirect server that is either offline or that doesn't host the file (anymore)

please see attached log above, thanks!!

**Comment by SeriousBuggie** [comment]
Try delete ACEv12e_C.u and ACEv12e_C.dll from System folder and connect again to server. It must download it again.

**Comment by kairos63** [comment]
Hi - thank you - this worked! 
there was no ACEv12e_C.u file. But I deleted ACEv12e_C.dll from System folder .
Many thanks for the help !

**Comment by kairos63** [comment]
thanks for your response gentleman.
