### ISSUE TITLE
Server advises to install client version 469f

### ISSUE THREAD

**Issue by jharrison03** [OldUnreal/UnrealTournamentPatches#1295]
That message shows up periodically on more than one server I frequent (appears like all the chatter or 't'-type messages).  That seems bogus to me.  I'm not sure it's malicious because there's no link to that supposed 469f, just an advisory to install 'it'.

**Comment by SeriousBuggie** [comment]
It sounds as some custom mod and not related to this patch.

**Comment by SeriousBarbie** [comment]
Is "f" (test) version out at all?

**Comment by SeriousBuggie** [comment]
No. Test versions marked as `469d - %date% Preview`.

**Comment by stijn-volckaert** [comment]
Advising players to update their clients is not a feature of our patches
