### ISSUE TITLE
[469c] "EditActor Class" console command needs to automatically togglefullscreen

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1296]
If you try the "EditActor Class" console command while UT is in fullscreen, UT will minimize and not show the properties window until you exit out of Fullscreen using togglefullscreen.

Steps to reproduce:
1. Launch UT and open the console
2. Type and enter "**EditActor Class=Pawn**"

Current result: UT minimizes and does not show the properties window.

My fix request: UT needs to automatically "togglefullscreen" when entering "EditActor Class". This way it will properly show the properties window. This is also similar to how the "preferences" command is being executed right now. When you type "preferences" in the console, UT will automatically togglefullscreen and show the preferences window correctly. "EditActor Class" should behave like this as well.

Here is a video as well:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/c86fad71-d77d-4f5d-8cb2-ea1c27b4f569

**Comment by stijn-volckaert** [comment]
I cannot reproduce this in the latest 469d previews. My client just exits fullscreen mode and shows the editactor window as expected

**Comment by BerserkerBG** [comment]
> I cannot reproduce this in the latest 469d previews. My client just exits fullscreen mode and shows the editactor window as expected

Which test version are you referring to? Buggie recently pushed a fix for this in his latest test releases and it has fixed this issue. I have tested this issue again with your last preview build, here are the results:

**May 30 v469d Preview 10** - Issue is still there.
**June 30 v469d UnrealEd Test 227** - Issue is fixed.
