### ISSUE TITLE
Issues found so far Font - Lack of movement on sniper zoom - Skins

### ISSUE THREAD

**Issue by NBK-XtremE** [OldUnreal/UnrealTournamentPatches#13]
Running Directx9 on a Windows 10, RTX 2070, i5-9600k 16gb ddr4.

1. Font is not smooth for me, looks bugged. I can get around this by setting res to 4k and changing scale of font... but defaults are not clear. I have a 1080p monitor. Pic added. 
![Shot00010](https://user-images.githubusercontent.com/71785754/94050938-d6611b80-fdce-11ea-83c4-f773a8ebb6bf.png)
![Shot00009](https://user-images.githubusercontent.com/71785754/94050270-f0e6c500-fdcd-11ea-81e9-dc1130f00911.png)

2. Custom weapon issues. - When zooming in on a custom sniper server you can not precisely change your aim. Moving the mouse slowly will not move your cross hair on map. This becomes an issue when you have zoomed anywhere between 4x and 100x .... the standard sniper rifle does not have this issue and goes to 8x. I have tried this on multiple sniper servers (Camping in the extreme, [EST] Sniper Server, [SV] Sniper Server, -]NBK[- Sniper Server) I have tried every setting for mouse input and mouse smoothness and the same issue remains. It feels like when zooming in there is artificial mouse acceleration which stops you from moving your mouse without pushing it fast.

**EDIT:** I've just tried this on version 436....... and it does the same thing, I guess I just never looked out for it before. This is not a patch issue but game engine issue..... still would be amazing if it could be fixed but yeah,
 

Text breakup over bright textures
![Shot00013](https://user-images.githubusercontent.com/71785754/94052614-16290280-fdd1-11ea-9ab5-1ae873168a11.png)
![Shot00014](https://user-images.githubusercontent.com/71785754/94052623-17f2c600-fdd1-11ea-93f9-9e5b9bad6a44.png)

full screen
![Shot00013](https://user-images.githubusercontent.com/71785754/94052663-29d46900-fdd1-11ea-92a2-3e8787a43bd1.png)
![Shot00014](https://user-images.githubusercontent.com/71785754/94052674-2b9e2c80-fdd1-11ea-9728-fbf183437171.png)

**Comment by stijn-volckaert** [comment]
Can you give us the ips of the servers that run these mods?

**Comment by NBK-XtremE** [comment]
Sure,
173.199.79.211:7777 MoS server
144.76.120.111:7766 SV
74.91.116.23:7777 CITE (these are used by the snipers for ladder matches)

Just zoom a bit and slowly move your mouse to see.

**Comment by CacoFFF** [comment]
As a workaround you'll have to limit your game's framerate to something around 120 or under.

**Comment by NBK-XtremE** [comment]
> As a workaround you'll have to limit your game's framerate to something around 120 or under.

Same issues when I cap frames to 60

**Comment by NBK-XtremE** [comment]
edit: i've just tried the sniper issue on 436... I jumped the gun a bit here, the issue is also in 436 so it is not a patch issue but instead an original game engine issue.... my bad.

**Comment by stijn-volckaert** [comment]
What are the mouse settings you're playing with? Are you using a mouse with a very high DPI and/or polling rate? What is your mouse sensitivity?

**Comment by stijn-volckaert** [comment]
The font problems seem odd. Which renderer are you using? Is there any scaling setting that works at 1080p?

**Comment by NBK-XtremE** [comment]
hmm.. I've since reinstalled ut99 and the patch and all is working well.. I think I had a conflict with the old ini and what engine it was using... I can't seem to replicate the font issue, all is fine now. I had a very big ut folder with many mods and ini's etc so maybe it was that.
The sniper issue will happen on all mouses, the game wasn't designed to have 45+ multiplier of zoom... 
It acts as if you are zooming in on a rendered image... it moves 1 big 'pixel' in the direction you aim, it can never be smooth

**Comment by NBK-XtremE** [comment]
The font issue can be resolved in the ini. 
I am using the Unrealshots ini from ooper's site. The line SmoothMaskedTextures=False is what was causing the font issues.

This also led to dark shadows around scopes and other textures. Setting it to True resolves all the issues.

I'm going to close with this comment as I ended up addressing everything myself ha.

Thanks!
