### ISSUE TITLE
[469a] Galaxy crash - Update music

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#130]
Two crashes using the Galaxy Audio device in 469 and playing locally - one when switching from one map to another.   Log entries are the same for each :

Critical: UpdateMusic
Critical: UGalaxyAudioSubsystem::Update
Critical: UGameEngine::Draw
Critical: UWindowsViewport::Repaint
Critical: UWindowsClient::Tick
Critical: ClientTick
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: UGalaxyAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: UOpenGLRenderDevice::ShutdownAfterError

Not an error I've had in 436/451 playing the same maps.

**Comment by stijn-volckaert** [comment]
I am aware of this crash but have not found any way to reproduce it so far. If you find a reliable way to reproduce this crash, then please let us know. Be sure to include a copy of your UnrealTournament.ini file.

Also, if you want, you could help us out by testing a preview of 469b. Come talk to me on Discord for further information.

**Comment by OjitroC** [comment]
I've found that I can reproduce the crash - at least it happens at or around the same point in a particular map.  This is the map (https://www.sendspace.com/file/n07rlb - from here https://ut99.org/viewtopic.php?f=5&t=14166&start=15#p123495).  The point it happens at for me is close to the start - from the start area go to the first courtyard, find the Nali to open the 'secret' area, follow the path to the left taking out the numerous predators, open the gate, turn right, there is a group of Skaarj Warriors a little way away, start to attack these and at this point I get the Update Music crash.

Sorry I can't add my UT.ini here as my browser is barely supported by GitHub but will PM it to you at UT99.org if that is OK?

**Comment by SeriousBuggie** [comment]
Map here: [MH-TheFifthVortexBeta5.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5417840/MH-TheFifthVortexBeta5.zip)

I try reproduce 3 times with OpenGL render and Galaxy sound on v469a locally and all times not crash for me.

**Comment by SeriousBuggie** [comment]
Here test map: [DM-Music.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5417947/DM-Music.zip)
With relevant Skaarj + MusicEvent. Try load map and kill Skaarj. No crash for me even with Galaxy and OpenGL.
It is from original map.
If no crush for you I can make another copy related things from Beta5.

**Comment by OjitroC** [comment]
No, so it's not related to the map per se but possibly more to do with my settings for Galaxy.  I think by the second crash I had switched to the D3D9 renderer not, I suppose, that that is related to the crash.

**Comment by SeriousBuggie** [comment]
Second map: [DM-Music2.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5418000/DM-Music2.zip)

Lot of spam:
```
DevMusic: MTRAN Botmca9 CurrentSection 0 Song Botmca9 SongSection 0 -- Transition 5
```
But no crash for me again.
There actors copied from Beta5.

**Comment by OjitroC** [comment]
Test map DM-Music crashed after killing the Skaarj - no log spam just the details of the Update Music crash as before.

Test map DM-Music2 crashed almost immediately - after I spawned and the Skaarj started to move and 'say' something. Again same crash details in the log.

**Comment by SeriousBuggie** [comment]
DM-Music2 almost the same as DM-Music except more count of tagged skaarj linked to MusicEvent. Also here independent MusicEvent which not linked with anything. IDK what this mean. Such things appear on original map.
Maybe author forget add appropriate trigger.
In any case it can be reason of immediately crash. I hardly believe about crash produced by increase count of skaarj.
But as far as I know MusicEvent not work like trigger, and can not be activated by Touch. Only by trigger by Event. Maybe I do not know something.

Also both MusicEvent have Song None. IDK what authors want to do with this. Maybe strange way to make silence.
Or switch music back from Action part to Calm part.

Floating MusicEvent change music to action part. Look like kill skaarj must change it back to Calm mood.

**Comment by stijn-volckaert** [comment]
Do you even hear any music at all?

**Comment by stijn-volckaert** [comment]
Fixed. In the meantime, set UseDigitalMusic to true under [Galaxy.GalaxyAudioSubsystem] and lower the music volume to 0 if you don't want to hear music.
