### ISSUE TITLE
Botpack.FlagBase.Checker and Botpack.FlagBase.SpawnFlag accessed nones

### ISSUE THREAD

**Issue by shai-ut99** [OldUnreal/UnrealTournamentPatches#1300]
I noticed that our 469c Linux UT server log had swelled substantially overnight, and opened it to reveal tens of thousands of lines as below:

> FlagBase BT-TwoCastlesCB.FlagBase0 (Function Botpack.FlagBase.SpawnFlag:0051) Accessed None 'myFlag'
> FlagBase BT-TwoCastlesCB.FlagBase0 (Function Botpack.FlagBase.SpawnFlag:0059) Attempt to assign variable through None
> FlagBase BT-TwoCastlesCB.FlagBase0 (Function Botpack.FlagBase.SpawnFlag:0061) Accessed None 'myFlag'
> FlagBase BT-TwoCastlesCB.FlagBase0 (Function Botpack.FlagBase.SpawnFlag:0069) Attempt to assign variable through None
> FlagBase BT-TwoCastlesCB.FlagBase0 (Function Botpack.FlagBase.SpawnFlag:009B) Accessed array 'FlagList' out of bounds (102/4)
> FlagBase BT-TwoCastlesCB.FlagBase0 (State Botpack.FlagBase.Checker:00E8) Accessed array 'FlagList' out of bounds (102/4)
> FlagBase BT-TwoCastlesCB.FlagBase0 (State Botpack.FlagBase.Checker:00E8) Accessed None 'FlagList'
> FlagBase BT-TwoCastlesCB.FlagBase0 (State Botpack.FlagBase.Checker:011F) Accessed array 'FlagList' out of bounds (102/4)
> FlagBase BT-TwoCastlesCB.FlagBase0 (State Botpack.FlagBase.Checker:011F) Accessed None 'FlagList'
> FlagBase BT-TwoCastlesCB.FlagBase1 (State Botpack.FlagBase.Checker:0078) Accessed array 'FlagList' out of bounds (102/4)

I see that the Checker state is new to the FlagBase class in 469; I've no idea what circumstances might bring about a FlagBase "Team" value above 3 in that state script, but though that scenario shouldn't ever occur, it's nevertheless managing to occur.

Adding a check on the Team variable (in the SpawnFlag function and Checker state) to ensure it's < 4 before attempting to access the FlagList array in CTFReplicationInfo (or to assign values to myFlag in SpawnFlag(), if myFlag is none because the Team value is above 1) looks like a superficial solution. But then it leaves the question of what to do about a Team variable value that's way out of the expected range. I have no suggestions for dealing with this.

This is the map that was running on the server at the time:

https://www.mediafire.com/file/sm3xp30wcuzj20e/TwoCastlesCB.7z/file

**Comment by SeriousBuggie** [comment]
Bad mapping. FlagBase used as decoration for flag. With weird team like 102.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0ac93509-c4e6-4687-a4aa-f9a3b27dfbea)
Map must be fixed. For display flag mesh must be used some classes like Decoration, not FlagBase.

**Comment by SeriousBarbie** [comment]
Switching timer off for these flags will stop the Access-None log entries.

**Comment by shai-ut99** [comment]
@SeriousBuggie Understood, thanks for investigating the root of the issue. I'll close this ticket now.
