### ISSUE TITLE
[win][469] UnrealEd wrong count mover nodes

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#131]
Look at this message:
```
---------------------------
Message
---------------------------
WARNING: This map has 56417 static BSP nodes and at least 9119 mover nodes. The movers in this map might be (partially) invisible in game.
---------------------------
ОК   
---------------------------
```
56417 + 9119 = 65536
Coincidence? No. I rebuilt map and get: 
```
---------------------------
Message
---------------------------
WARNING: This map has 55296 static BSP nodes and at least 10240 mover nodes. The movers in this map might be (partially) invisible in game.
---------------------------
ОК   
---------------------------
```
55296 + 10240 = 65536
Again.

So something wrong with this math. I think here used 2-bytes integer and some overflow occurs.

You can use [MH-TheFifthVortexBeta5.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5417840/MH-TheFifthVortexBeta5.zip) for easy get such messages on try save map with different name.

**Comment by stijn-volckaert** [comment]
The fix will be included in the next 469b snapshot.

**Comment by SeriousBuggie** [comment]
IDK, I not get this message at all for Beta11.
Maybe it counted properly because in game i not experience any Node issues with movers. 55k static nodes.

I try test later with rebuilt map for push to limits.

**Comment by SeriousBuggie** [comment]
Rebuilt map with 64232 static node s and get this message:
```
---------------------------
Message
---------------------------
WARNING: This map has 64232 static BSP nodes and at least 1304 mover nodes. The movers in this map might be (partially) invisible in game.
---------------------------
ОК   
---------------------------
```
Again 64232 + 1304 = 65536.
But take in account my message above about Beta11 I can not really say fixed this issue or no.

**Comment by SeriousBuggie** [comment]
New build. 
```
---------------------------
Message
---------------------------
WARNING: This map has 61442 static BSP nodes and at least 4094 mover nodes. The movers in this map might be (partially) invisible in game.
---------------------------
ОК   
---------------------------
```
Sum again is 61442 + 4094 = 65536. it is normal?

**Comment by stijn-volckaert** [comment]
Indeed. The maximum number of nodes is capped at 65536, so if your static node count is close to the limit, we can only see if adding movers pushed you over the limit

**Comment by SeriousBuggie** [comment]
Maybe better write something like?

WARNING: This map has 61442 static BSP nodes and at near 6000 mover nodes. In total 67442, which over total possible limit of 65536 nodes. The movers in this map might be (partially) invisible in game.

This message better because provide some additional info - how bad all things here.
For example  60k static nodes + 10k movers nodes is one situation.
60k static nodes + 30k movers nodes is totally another situation.
