### ISSUE TITLE
can no longer reach : Evil's Freestyle Sniper Deathmatch

### ISSUE THREAD

**Issue by kairos63** [OldUnreal/UnrealTournamentPatches#1311]
Does anyone have an idea why i can no longer access server:
 [-=][-=NFR=-][=-Evil's Freestyle Sniper Deathmatch]

It was working fine for years.
Now i get Connection failed:
Can't find file for package ACEv12e_C.

Thanks in advance for any tips ;)

**Comment by stijn-volckaert** [comment]
duplicate of #1293
