### ISSUE TITLE
[XConsole 3.5.0rc71/72] Fix two critical bugs

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1314]
XConsole is a great replacement for shitty default vanilla console, but there are problems: 
**SEE HERE**: [LINK 1](https://eatsleeput.com/d/192-chatdiamond/30) + [LINK 2](https://eatsleeput.com/d/192-chatdiamond/41) + [LINK 3](http://www.unrealkillers.com/archive/index.php/t-3108.html)

The latest version of XConsole: 3.5.0rc71/72 ([LINK](http://medor.no-ip.org/Utilities/xconsole/xconsole3.5.0rc71.rar)) compared to version 3.4.8, apart from many other fixes/enhancements, contains:
- one critical must-have feature:
   - an ability to just see players's chat and hide the rest of the crap (kill messages etc)
-  and two critical bugs:
   - a double font size bug, which causes the text input field dissappear (unable to chat/type)
   - very slow/long loading time (fails to load properly when run with `UnrealTournament.exe -111.222.333.444`)

It causes further the following problems:
- version 3.4.8 is useless due to a lack of the critical must-have feature
- version 3.5.0rc71/72 is useless due to the two critical bugs

And one more problem:
- XConsole is abandoned by the devs, which simply means they will not fix the two critical bugs

I know it might be out of scope for the PATCH 469, but:
- console/chat display is a very important core feature of the game
- XConsole is abandoned by devs, which means the devs won't fix the bugs
- there is no useful console at the moment:
   - default vanilla console is a garbage
   - and ChatDiamond is a castrated version of XConsole which lacks many useful feature XConsole has

It would be so great if devs of PATCH 469 could take a look at XConsole: 3.5.0rc71 or 72 and try to fix the TWO CRITICAL BUGS, of course, you can prefer to decline the request and label it as "won't fix" (or whatever) and close it, I'm just asking, not forcing.

**Comment by SeriousBuggie** [comment]
Not related to the patch.

**Comment by garry-ut99** [comment]
Console is a core part and is related to the game, and that it is as a separate file/mutator doesn't change that fact.
