### ISSUE TITLE
Evils Freestyle Sniper Deathmatch kicked me out each time

### ISSUE THREAD

**Issue by kairos63** [OldUnreal/UnrealTournamentPatches#1315]
weirdest message:
[ACEv12e]: You have been kicked because of a timeout during the ACE checks.
[ACEv12e]: This is usually caused by severe connection problems.
[ACEv12e]: Try shutting down all programs that use a lot of bandwidth, memory or 
CPU time.

this has never happened before....ACE is always glitching on me - any ideas anyone?

**Comment by kairos63** [comment]
I tried  changing texture res to med then low... still kicked out after about a minute...

**Comment by stijn-volckaert** [comment]
Sorry, this is not an issue with the patch. The ACE support channel is on ut99.org's Discord server

**Comment by kairos63** [comment]
So why is the message saying:
[ACEv12e]: You have been kicked because of a timeout during the ACE checks.
[ACEv12e]: This is usually caused by severe connection problems.
[ACEv12e]: Try shutting down all programs that use a lot of bandwidth, memory or 
CPU time.
