### ISSUE TITLE
[469c] Variable fontsize for UnrealEd code window

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1317]
We all get older and our eyes, too. Maybe it is possible to implement changing the font size of UnrealEd's code window?

**Comment by SeriousBuggie** [comment]
Possible implementation:
- edit UnreralEd.ini [Options] CodeFontSize
- or via mouse wheel with Ctrl.

![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/9f850b87-4b94-493c-8815-c6b6f96d5d0f)

**Comment by SeriousBarbie** [comment]
Also common is STRG+'+' / STRG+'-'

**Comment by SeriousBuggie** [comment]
I guess Ctrl+Wheel more then from enough. Ctrl++ and Ctrl+- can interfere with some hotkeys, if it be used in future.
