### ISSUE TITLE
[469c] Add Actor instance name to UnrealEd's log when adding an Actor

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1318]
Instead of 
> Log: Added actor successfully

use more informative
> Log: Added actor "Fly123" successfully

Because sometimes Actors are added by accident and if name was given, finding and removing it would be easier.

**Comment by SeriousBuggie** [comment]
This appear to be in `UEditorEngine::AddActor`.

**Comment by stijn-volckaert** [comment]
Implemented for 469d RC3
