### ISSUE TITLE
[469a] Spawn in with no weapons or xloc

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#132]
Hi,
I have been playing on SOP sniper server and on Teamspeak with several people who were mixed... some having upgraded and some having not upgraded to V469a patch.  On some maps, anyone with the patch was put into the map with no weapons or xloc.  After getting killed and respawning, there was no change.  The common thread was the patch.  Only people who have installed the patch had this issue.  
As I also have a backup folder with v436 patch installed, I opened from there and spawned into the map with the correct weapons and xloc.
I did not note the map(s) that it happened on, but I will add that information the next time it occurs.

**Comment by stijn-volckaert** [comment]
This is a network compatibility error. One of the packages on that server was probably built against unconformed packages. Do you have the URL of the server?

**Comment by OMA-Bite-Me** [comment]
Here is the link to gametracker info on that server
https://www.gametracker.com/server_info/108.61.238.86:9123/

It only happens on a very few maps and I don't recall the names.  If/when it happens again, I'll post back here.

**Comment by stijn-volckaert** [comment]
I'm reviewing some old issues and saw this one is still open. We discovered one (rather specific) situation where the 469a and b encountered a problem like the one you described. 469c includes a fix. Feel free to comment/reopen if this still happens in >469c
