### ISSUE TITLE
[469c] option to scale UI?

### ISSUE THREAD

**Issue by MaddTheSane** [OldUnreal/UnrealTournamentPatches#1322]
Is there a way to set the UI scale? As a user of a Retina MacBook Pro, the UI of the in-game menus, etc. are too small to be easily read/chosen.

**Comment by SeriousBuggie** [comment]
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/0349fefc-ae5c-4654-b99a-428f99f4b5c0)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/fbdef94b-9ab6-4544-bfde-4373dddc9c00)

**Comment by MaddTheSane** [comment]
I'm not seeing that option.

My UT files are from the Mac GOTY edition. Would that matter?

**Comment by SeriousBuggie** [comment]
No, this not matter. But if you not see this options, then v469c patch not installed, or applied for wrong folder.

**Comment by MaddTheSane** [comment]
Fixed it.
