### ISSUE TITLE
[469c] Ued: Force polygons merge on surfaces that dont share the same values.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1323]
![Screenshot_44](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/5fa57fa0-ee36-4a8d-9410-ffbc1bcbd8da)

Polygons merge is a really nice tool, which allows you to merge 2 or more surfaces into one. Polygons merge will only work if all of the surfaces share the exact same properties. For example - texture needs to be the same on all surfaces, it also needs to have the same scale/rotation/pan, same UVs, Origin points, etc. Polygons merge will not work on surfaces that have different properties.

Suggestion:
Allow Polygons merge to force-merge surfaces that don't have the same properties as I listed above. The drawback of this is that it will destroy texture alignment for some of the surfaces you want to merge. If this is a problem for some people, a warning popup can appear when you try to merge 2 or more surfaces that don't share the same properties - this should let people know that merging surfaces is destructive. When you select surfaces to merge, the very first surface you select should act as a "parent" guide for the texture and alignment of the final merged surface.

**Comment by SeriousBuggie** [comment]
There no concept as "order of select surfaces:". So it be random surface as parent. This lead to unpredictable results.
How such better from "Align WallXY + Merge"?

**Comment by SeriousBuggie** [comment]
What must match for merge:
1. Actor.
2. Texture.
3. Normal.
4. Polygon origin must be in same plane - polygon is coplanar.
5. Polygon Flags.
6. Texture U
7. Texture V

Pan not checked.

I guess all except last two never must be forced to merge.
So there can be option for ignore mismatch in Texture UV.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/721f7085-d2b4-4185-bc10-30089b555171)
