### ISSUE TITLE
[win][469a] UnrealEd lie about fix compability when you choose "yes"

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#134]
I try compile script with next code:
```
//=============================================================================
// MyAnim.
//=============================================================================
class MyAnim expands Car01;

simulated function PostBeginPlay()
{
	Super.PostBeginPlay();
	LoopAnim(AnimSequence, AnimRate);
}
```
Get next dialog:
```
---------------------------
Question
---------------------------
Function MyLevel.MyAnim.PostBeginPlay has superfield Engine.Decoration.PostBeginPlay.  
This superfield was not present in UT v436, so this package will not work on UT v436 clients or servers. 
Do you want to use Engine.Actor.PostBeginPlay as the superfield to fix this compatibility problem?
---------------------------
Yes   No   
---------------------------
```
Select yes.

And now map stop load on v451 and lower.

For reproduce you can subclass Car01 with own class in v469a. Compile. Save. Say yes. And try load map in v436.

**Comment by an-eternity** [comment]
This also happens (at least in my tests) if imported package contains conflicting inherited functions.

**Comment by SeriousBuggie** [comment]
Not fixed in v469b (preview 2 nov).

I subclass car. Save. Get message. Answer yes.

When try load in v436 fail:
```
Log: New File, Existing Package (Package MyLevel, Package Test_compat)
Log: Failed import: Function Function Engine.Decoration.PostBeginPlay (file ../System/Engine.u)
Warning: Failed to load 'Z:\UT_469\Maps\Test_compat.unr': Can't find Function in file 'Function Engine.Decoration.PostBeginPlay'
Warning: Failed loading package: Can't find Function in file 'Function Engine.Decoration.PostBeginPlay'
Warning: Failed loading package: Can't find Function in file 'Function Engine.Decoration.PostBeginPlay'
```

**Comment by stijn-volckaert** [comment]
Can you try to compile this with ucc instead?

**Comment by SeriousBuggie** [comment]
Good news:
v469b 7 nov - issue fixed.

Bad news:
If you choose "yes" UEd will ask again and again. Even two times. First when compile, second when save. This is right.
Also I did not check cases when answer is differents. I supposed if user answer then he answer same in both cases.

If you choose "no" UEd never ask you again until you not reload UEd.
Need new issue for this?
