### ISSUE TITLE
[469c] Build light, after apply polygons from brush, can move or rotate mover

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1342]
Reproduce:
1. Open in UnrealEd [CubeMover.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/12902048/CubeMover.zip)
2. Right click on mover and choose `Polygons -> From Brush`.
3. Build light.

https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/27c94cf0-3641-471a-880a-d9a938e49f2d

Expected result: Mover left in place where it be before build light.
Actual result: Mover jump to some other position and/or change rotation.

Possible reason: Pivot point not updated, so it goes be in desync. So when editor build light and move mover, it return mover back in wrong position.

Issue disappear if deselect + select mover again. This update pivot point.

**Comment by Marco888** [comment]
Short fix (ABrush.h):
```
	virtual void CopyPosRotScaleFrom( ABrush* Other )
	{
		guard(ABrush::CopyPosRotScaleFrom);
		check(Brush);
		check(Other);
		check(Other->Brush);

		Location    = Other->Location;
		Rotation    = Other->Rotation;
		PrePivot	= Other->PrePivot;
		MainScale	= Other->MainScale;
		PostScale	= Other->PostScale;

		Brush->BuildBound();
		
		+PostEditMove();
		unguard;
	}
```
