### ISSUE TITLE
[469c] CRASH - Critical Error - General protection fault ! (ACE / ChatDiamond)

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1347]
- https://github.com/ravimohan1991/ChatDiamond/issues/14#issuecomment-1676405518

I'm not sure whether it's another same kind of crash caused by ACE like in:
- https://github.com/OldUnreal/UnrealTournamentPatches/issues/1260

, or a different crash caused by the mutator.

**Comment by garry-ut99** [comment]
By the way, it also suffers another bug: 
- https://github.com/stijn-volckaert/udemo/issues/28#issuecomment-1676398987

**Comment by SeriousBuggie** [comment]
This issue related to ChatDiamond, not game itself. Must be addressed to this mod. Closed.

**Comment by garry-ut99** [comment]
Lol, damn it, sounds like I didn't know, I feel enlightened, you must be a genius, despite actually it's you who know it from me: [LINK](https://eatsleeput.com/d/192-chatdiamond/89).
