### ISSUE TITLE
[469d-RC2] Direct input+Mouse Wheel=loop

### ISSUE THREAD

**Issue by donizettilorenzo** [OldUnreal/UnrealTournamentPatches#1353]
With "Direct Input" option the mousewheel up/down reading keeps looping until you change the rotation direction.
No issue with "Cursor"

469d RC2 package

And yes, I'm using the old DDraw renderer, it's still in perfect shape :D

**Comment by stijn-volckaert** [comment]
This will be fixed in RC3
