### ISSUE TITLE
[469d-RC2] Broken lighting on CTF-Bleak][UGN Movers

### ISSUE THREAD

**Issue by scottadkin** [OldUnreal/UnrealTournamentPatches#1355]
I saw this posted on a forum and also had the same issue, when the mover is in it's default position it's pure black.

I tried it with OpenGL, XOpenGL, and Direct3D9 with different settings and it still looks the same when it was fine in previous patches.

![Shot00673](https://github.com/OldUnreal/UnrealTournamentPatches/assets/25456246/c7ba13f5-81aa-42f4-85d4-4c6e1b21d11b)

Map: [https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/B/ctf-bleakugn_0c9bdb54.html](https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/B/ctf-bleakugn_0c9bdb54.html)

Forum Post: [https://eatsleeput.com/d/349-unreal-tournament-v469d-release-candidate-2-rc2-public-released/10](https://eatsleeput.com/d/349-unreal-tournament-v469d-release-candidate-2-rc2-public-released/10)

**Comment by stijn-volckaert** [comment]
I've reverted the fix that caused this problem

**Comment by SeriousBarbie** [comment]
Mover's pivot point in KeyNum 0 position is too low and in the void. I think all Mover surfaces are not lightened then.
