### ISSUE TITLE
[469d-RC2] OpenGL vs XOpenGL Input latency

### ISSUE THREAD

**Issue by guitronimo** [OldUnreal/UnrealTournamentPatches#1356]
Game: TactialOps 3.4
WIndows 10 20.‎02.‎2021
Latest GHUB and NVidea Drivers. 
Mouse MX518

OpenGL
When i first started the game i was like - Yes! Finally its how its supposed to be. It felt snappy, like virtually no latency at all in IO. 
Then during gameplay i feel that either mouse input or video output tend to lag behind. 
Its a bit hard to describe of course because we talk about a portion of a few ms.

XOpenGL on the 469D 11 Beta package was fine, Dropping the RC2 package on top of my working Beta 11 the XOpenGL becomes completely unplayable. Its darkish, barely reaches 100 FPS.  
I will further test, go though various settings and will report back.

**Comment by stijn-volckaert** [comment]
Make sure you reset your XOpenGLDrv config before testing

**Comment by garry-ut99** [comment]
> guitronimo : https://github.com/OldUnreal/UnrealTournamentPatches/issues/1356#issue-1862268726 : XOpenGL becomes completely unplayable. Its darkish, barely reaches 100 FPS.
> guitronimo : https://github.com/OldUnreal/UnrealTournamentPatches/issues/1356#issuecomment-1689905037 : My settings now at least allow 288 FPS which works fine for my system but the UT settings barely reach 100 today.

Might be related similiar issue: [LINK 1](
https://eatsleeput.com/d/349-unreal-tournament-v469d-release-candidate-2-rc2-public-released/2) + [LINK 2](https://eatsleeput.com/d/349-unreal-tournament-v469d-release-candidate-2-rc2-public-released/6)

**Comment by guitronimo** [comment]
Thanks i will check the link. 

I have tested both my versions on a different computer and it was like yesterday. 
First 469d RC2 worked flawlessly then suddenly after some map it dropped from stable 288 FPS down to about 200 to 220. 
Restarting game doesnt solve the problem
Restarting computer doesnt solve the problem. 

On both computers same issue now and configuration didnt change at all. 

469C RC4 Init: Compiled: Jul  4 2022 21:55:41 - works flawlessly on both machines with same config. 

It is possible tho that my computer is a bit warm at the moment. Pretty hot day today. But then again why would the older version run with same config? Does 469d require more juice out of smth?

**Comment by garry-ut99** [comment]
> guitronimo : https://github.com/OldUnreal/UnrealTournamentPatches/issues/1356#issue-1862268726 : Its darkish

Here same issue reported :

> UM-Hitman : https://github.com/OldUnreal/UnrealTournamentPatches/issues/1358#issue-1864986628 : Some also rapport that the xopenGL turned way to dark after install and have to shift to D3D9

**Comment by SeriousBuggie** [comment]
It is not same. Please stop link unlinked issues. This issue named as `[469d-RC2] OpenGL vs XOpenGL Input latency`, when what you quote, talk about 
> the xopenGL turned way to dark

> Its darkish

**Comment by garry-ut99** [comment]
> It is not same. 

How they are not same?
By the way, it's this issue: https://github.com/OldUnreal/UnrealTournamentPatches/issues/1002#issuecomment-1691594699

**Comment by stijn-volckaert** [comment]
Please stop linking completely unrelated issues

**Comment by garry-ut99** [comment]
> SeriousBuggie : https://github.com/OldUnreal/UnrealTournamentPatches/issues/1358#issuecomment-1691566706: Please use one issue, for one problem.

> stijn-volckaert : `https://github.com/OldUnreal/UnrealTournamentPatches/issues/1356#issuecomment-1691597410` : Please stop linking completely unrelated issues

And who is doing it? The OPs, not me, I wasn't linking the main issues, I was linking the secondary issues  ("too dark") which are related / same, not my fault they put several unrelated issues in each thread, wonder why I am being scolded for their faulty acting and became the victim, however I agree that I could put all links in a quote to avoid references. 

> `#1356` : guitronimo : Its darkish
> `#1358` : UM-Hitman :  xopenGL turned way to dark 

<hr>

And why my comment was still removed  after I put it in an appropriate thread here: `https://github.com/OldUnreal/UnrealTournamentPatches/issues/1002` Isn't it the same "too dark" issue which seems to be back again in 469D RC2? At least it looks like so, even if not, no need to remove my comment because it informs of similar reports.

<hr>

If you are going to keep blaming and removing comments, instead of answering questions, it doesn't make any sense to contribute here.

**Comment by guitronimo** [comment]
Well i found one issue that i cannot explain myself. 

It appears that non of the 469D builds actually using my NVidia device instead of they go directly UHD regardless of if i tell the NVidia Controlpanel to explicitly use the exe from the 469D Folder. 

This is also the case for another laptop that i own. 
I updated both machines to latest NVidia software including controlpanel. 
Oddly, 469C RC4 and Release execute without any issue on my NVidia card. 

Maybe i have to clean out some stuff in NVidia, could it be an issue that the Controlpanel knows too many same .exe files? I test pretty much all builds of you guys. 

Before that isnt fixed, i think i cannot state any performance of 469 :/

**Comment by guitronimo** [comment]
Sure enough... Tested around a bit directly with unreal tournament without having third party Tactical Ops involved. 

If i drop 469C whatever version into my Unreal Tournament System Folder its executing fine on my Internal NVidia GFX
None of the 469D patches that i downloaded (RC2 and beta 11 for example) work on my NVidia device - theyre alway being displayed on the UHD Interface... 
I have reinstalled everything and made the big clean out until NVidia Controlpanel was compeltely Reset. 

Maybe one can verify this issue?

**Comment by garry-ut99** [comment]
> stijn-volckaert: https://github.com/OldUnreal/UnrealTournamentPatches/issues/1356#issuecomment-1691597410 : Please stop linking completely unrelated issues

Piss off, like explained here: `https://github.com/OldUnreal/UnrealTournamentPatches/issues/1002#issuecomment-1691895147` and you both stop shitty acting, removing comments, not answering questions.

**Comment by guitronimo** [comment]
@stijn-volckaert  maybe its best dropping this issue completely anyway because it seems i got fooled by setting up stuff. 

To resolve this issue it was almost completely related to the fact that UnrealTournament.exe doesnt write all stuff to the default ini. 

In my Case the problem was that GL driver now has a new fetature that i wasnt even able to see:
PreferDedicatedGPU=True
It did not appear in console->Preferences also not in .ini when i made my first .ini file. 

This is working for now but i need to do all testing again. 
Sorry for the invonvenience.

**Comment by stijn-volckaert** [comment]
That setting currently defaults to False and it is not in Default.ini (yet). I'll update Default.ini right away and then discuss with @CacoFFF if we should change the default value.

**Comment by guitronimo** [comment]
Alright! Top job anyway.

**Comment by CacoFFF** [comment]
What I added was this:
(https://docs.nvidia.com/gameworks/content/technologies/desktop/optimus.htm)

> 
> Global Variable NvOptimusEnablement (new in Driver Release 302)
> 
> Starting with the Release 302 drivers, application developers can direct the Optimus driver at runtime to use the High Performance Graphics to render any application —- even those applications for which there is no existing application profile. They can do this by exporting a global variable named NvOptimusEnablement. The Optimus driver looks for the existence and value of the export. Only the LSB of the DWORD matters at this time. A value of 0x00000001 indicates that rendering should be performed using High Performance Graphics. A value of 0x00000000 indicates that this method should be ignored.

"A value of 0x00000000 indicates that this method should be ignored."
Looks like the value of 0 isn't being ignored at all, and nvidia purposely selects the integrated GPU now, bah.

**Comment by noskill24** [comment]
I have a large input lag with OpenGL and XOpenGL.
The third party OpenGL v1.37 works better for me but it also has a large Input lag.
I have latest Win10 and latest NVidia drivers.

**Comment by guitronimo** [comment]
Sorry i wasnt aware of me being able to close issues. 

I will take care of that in the future.. 
I close this one as it was completly related to this Setting thing above. 

Cheers
