### ISSUE TITLE
[469d-RC2] Non Fullscreen loosing focus during gameplay

### ISSUE THREAD

**Issue by guitronimo** [OldUnreal/UnrealTournamentPatches#1357]
Game: TactialOps 3.4
WIndows 10 20.‎02.‎2021
Latest GHUB and NVidea Drivers. 
Mouse MX518

I think this is an old one but i couldnt find any issue tagged to this anymore. 

When i am not palying fullscreen, during gameplay mouse is losing focus from the gamewindow. 
OpenGL and XOpenGL

**Comment by guitronimo** [comment]
Ive tested a bit. 

WinDrv.dll vers. (04.07.2022- 228.112 Bytes) appears to not lose focus of the game window but has overall terrible performance. Not only that it feels laggier, it also turns my player to the right when i use scroll wheel for chaning weapon. 

Is there possibly a chance of getting an experimental version of the most recent where the screen is not always on top? I think this might solve my issue then - although i would imagine it might affect performance. 

Greez! LuckyDog

**Comment by SeriousBuggie** [comment]
Try mouse different input types. Cursor and Raw, for example. Not only DirectInput.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/a55ae5f4-6612-403f-9360-268e853ba65e)

**Comment by stijn-volckaert** [comment]
What is the problem here exactly? Is your cursor escaping from the game window?

**Comment by guitronimo** [comment]
I am using Raw input since introduction. Yes the cursor is escaping game window and clicking random stuff on whatever it is on then.

**Comment by guitronimo** [comment]
Oddly... Tested on a different computer with simiar HW, same mouse same driver versions and i dont have this problem with escaping mouse.... Any tip for me what may cause this then?

**Comment by guitronimo** [comment]
I think you can mark this as not existing. 

I tested two other computers and the issue is not there. 
So i suppose that just smth. with my laptop doesnt work.

**Comment by guitronimo** [comment]
Must pull this up again - sorry! 

Tested on 3 different machines for a while now with different configs. 

NV GTX1660 TI Win 11 - upgraded to win 11 today - MX518 - GHub installed
NV GTX2080 TI Win 10 - Different MX518 no GHub installed
NV GTX780 TI Win 10 - random mouse
All on OpenGL same settings, stable fps of 200 set for now

During windowed gameplay mouse is leaving  game window or displaying moving mousepointer over game area.

There appear to be two related but differnt issues here:
1.)
If it shows the mousepointer it does this only as long as you dont hit a mouse button. At the time when mousepointer is visible, the player is not moving. 
Mousepointer is not able to leave area of the game window. 
One click, mousepointer vanishes and you can move player again

2.) During infight mouse leaves game window and by pressing fire you hit random things on whatever is there. 
Only clicking game window recovers this. 

I must admit that this issue was there in 469c aswell. I believe it came with the change in WinDrv.dll somewhen after RC4 was released. I never used the new WinDrv.dll which holds the game window up front as it caused this problem for me and then i stick to 469c RC4 pretty much until 469D Beta11. 

The problem does not occur as often as in 469C but its definately there. In a 20 minute match roughly 4 times. 

Maybe this helps as info.

**Comment by SeriousBuggie** [comment]
Do you use few monitors? If so, any chance game window located not on primary monitor?

**Comment by guitronimo** [comment]
One of the computers does have a secondary monitor yes but i execute the game always on Primary, i can check this again without second monitor. The other computers dont have secondary display attached. 
 
I am also not using any windows scaling - they are all 1920x1080 px @ 100%.

One thing i notice is that on windows 11 now (just updated yesterday) the issue appears to feel different. As if there is just sometimes between two clicks a stuck in movement. So it may be that OS and Drivers may have an impact on the problem:
Thats pretty much all i can report to this unfortunately. There is no special key combination that triggers this i believe. It happens randomly. I would assume that it has to do with wide or hectical mouse movement but thats just guess.

**Comment by guitronimo** [comment]
Would like to report back and close this here. 

There is an issue but this may also be related of the way Windows deals with it or how my setup / software has effect on it... 
Its a bit hard to explain. 
The issue is there clearly. The mouse escapes the gamewindow, when i play not fullscreen. But only, when the gamewindow itself is not tagged to bottom of screen. 

In windows you have this wonderful snap to left or right screen which then works just fine. 
Also found that it doesnt matter if i snap left or right side. It appears that only bottom is required. 

Hope youll understand :d 

Thanks anyway. Maybe helps one or another. 

Cheers
