### ISSUE TITLE
[469d RC2]"Search for Actors" finds also Event strings in Teleporter.URL

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1367]
Maybe it is even a feature?
Search in text field "Event" for a (sub)string that exists in any teleporter's URL -> match.
![SearchInURL](https://github.com/OldUnreal/UnrealTournamentPatches/assets/81397053/c27e7fce-2a74-4c71-a261-54dee3f9a6b3)

**Comment by SeriousBuggie** [comment]
It is feature, and done especially.
