### ISSUE TITLE
[469a] This brush here causes ued to crash

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#137]
> Begin Map
> Begin Actor Class=Mover Name=Mover0
>      KeyNum=2
>      bDynamicLightMover=True
>      OpenedSound=Sound'doorsmod.General.mdoorE22'
>      ClosedSound=Sound'doorsmod.General.mdoorE22'
>      MoveAmbientSound=Sound'doorsmod.General.mdoorL22'
>      KeyPos(1)=(Z=336.000000)
>      BasePos=(X=448.000000,Y=-1248.000000,Z=112.000000)
>      SavedPos=(X=-12345.000000,Y=-12345.000000,Z=-12345.000000)
>      SavedRot=(Pitch=123,Yaw=456,Roll=789)
>      MainScale=(SheerAxis=SHEER_ZX)
>      PostScale=(SheerAxis=SHEER_ZX)
>      InitialState="StandOpenTimed"
>      Level=LevelInfo'MyLevel.LevelInfo0'
>      Tag="lift3"
>      Region=(Zone=ZoneInfo'MyLevel.ZoneInfo22',iLeaf=951,ZoneNumber=6)
>      Location=(X=448.000000,Y=-1248.000000,Z=112.000000)
>      OldLocation=(X=448.000000,Y=-1248.000000,Z=112.000000)
>      bSelected=True
>     Begin Brush Name=Model1105
>        Begin PolyList
>           Begin Polygon Texture=eb_floor1 Link=0
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   -00152.000000,-00112.000000,-00056.000000
>              Vertex   -00152.000000,-00080.000000,-00056.000000
>              Vertex   +00104.000000,-00080.000000,-00056.000000
>              Vertex   +00104.000000,-00112.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=1
>              Origin   -00008.000000,+00096.000000,-00424.000000
>              Normal   +00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,-00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00008.000000,+00096.000000,-00424.000000
>              Vertex   -00008.000000,+00096.000000,-00056.000000
>              Vertex   -00008.000000,+00064.000000,-00056.000000
>              Vertex   -00008.000000,+00064.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=2
>              Origin   +00056.000000,+00000.000000,-00424.000000
>              Normal   +00000.000000,-00001.000000,+00000.000000
>              TextureU -00001.000000,-00000.000000,-00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   +00056.000000,+00000.000000,-00424.000000
>              Vertex   +00056.000000,+00000.000000,-00056.000000
>              Vertex   +00024.000000,+00000.000000,-00056.000000
>              Vertex   +00024.000000,+00000.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=3
>              Origin   +00024.000000,+00000.000000,-00424.000000
>              Normal   -00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,+00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   +00024.000000,+00000.000000,-00424.000000
>              Vertex   +00024.000000,+00000.000000,-00056.000000
>              Vertex   +00024.000000,+00032.000000,-00056.000000
>              Vertex   +00024.000000,+00032.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=4
>              Origin   +00024.000000,+00032.000000,-00424.000000
>              Normal   +00000.000000,+00001.000000,+00000.000000
>              TextureU +00001.000000,-00000.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   +00024.000000,+00032.000000,-00424.000000
>              Vertex   +00024.000000,+00032.000000,-00056.000000
>              Vertex   +00056.000000,+00032.000000,-00056.000000
>              Vertex   +00056.000000,+00032.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=5
>              Origin   +00056.000000,+00032.000000,-00424.000000
>              Normal   +00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,-00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   +00056.000000,+00032.000000,-00424.000000
>              Vertex   +00056.000000,+00032.000000,-00056.000000
>              Vertex   +00056.000000,+00000.000000,-00056.000000
>              Vertex   +00056.000000,+00000.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=6
>              Origin   +00024.000000,+00000.000000,-00424.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   +00024.000000,+00000.000000,-00424.000000
>              Vertex   +00024.000000,+00032.000000,-00424.000000
>              Vertex   +00056.000000,+00032.000000,-00424.000000
>              Vertex   +00056.000000,+00000.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=7
>              Origin   -00072.000000,+00000.000000,-00424.000000
>              Normal   +00000.000000,-00001.000000,+00000.000000
>              TextureU -00001.000000,-00000.000000,-00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00072.000000,+00000.000000,-00424.000000
>              Vertex   -00072.000000,+00000.000000,-00056.000000
>              Vertex   -00104.000000,+00000.000000,-00056.000000
>              Vertex   -00104.000000,+00000.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=8
>              Origin   -00008.000000,-00064.000000,-00424.000000
>              Normal   +00000.000000,-00001.000000,+00000.000000
>              TextureU -00001.000000,-00000.000000,-00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00008.000000,-00064.000000,-00424.000000
>              Vertex   -00008.000000,-00064.000000,-00056.000000
>              Vertex   -00040.000000,-00064.000000,-00056.000000
>              Vertex   -00040.000000,-00064.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=9
>              Origin   -00040.000000,-00064.000000,-00424.000000
>              Normal   -00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,+00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00040.000000,-00064.000000,-00424.000000
>              Vertex   -00040.000000,-00064.000000,-00056.000000
>              Vertex   -00040.000000,-00032.000000,-00056.000000
>              Vertex   -00040.000000,-00032.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=10
>              Origin   -00040.000000,-00032.000000,-00424.000000
>              Normal   +00000.000000,+00001.000000,+00000.000000
>              TextureU +00001.000000,-00000.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00040.000000,-00032.000000,-00424.000000
>              Vertex   -00040.000000,-00032.000000,-00056.000000
>              Vertex   -00008.000000,-00032.000000,-00056.000000
>              Vertex   -00008.000000,-00032.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=11
>              Origin   -00040.000000,-00064.000000,-00424.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   -00040.000000,-00064.000000,-00424.000000
>              Vertex   -00040.000000,-00032.000000,-00424.000000
>              Vertex   -00008.000000,-00032.000000,-00424.000000
>              Vertex   -00008.000000,-00064.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=12
>              Origin   -00040.000000,+00064.000000,-00424.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   -00040.000000,+00064.000000,-00424.000000
>              Vertex   -00040.000000,+00096.000000,-00424.000000
>              Vertex   -00008.000000,+00096.000000,-00424.000000
>              Vertex   -00008.000000,+00064.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=13
>              Origin   -00104.000000,+00032.000000,-00424.000000
>              Normal   +00000.000000,+00001.000000,+00000.000000
>              TextureU +00001.000000,-00000.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00104.000000,+00032.000000,-00424.000000
>              Vertex   -00104.000000,+00032.000000,-00056.000000
>              Vertex   -00072.000000,+00032.000000,-00056.000000
>              Vertex   -00072.000000,+00032.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=14
>              Origin   -00040.000000,+00064.000000,-00424.000000
>              Normal   -00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,+00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00040.000000,+00064.000000,-00424.000000
>              Vertex   -00040.000000,+00064.000000,-00056.000000
>              Vertex   -00040.000000,+00096.000000,-00056.000000
>              Vertex   -00040.000000,+00096.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=15
>              Origin   -00008.000000,+00064.000000,-00424.000000
>              Normal   +00000.000000,-00001.000000,+00000.000000
>              TextureU -00001.000000,-00000.000000,-00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00008.000000,+00064.000000,-00424.000000
>              Vertex   -00008.000000,+00064.000000,-00056.000000
>              Vertex   -00040.000000,+00064.000000,-00056.000000
>              Vertex   -00040.000000,+00064.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=16
>              Origin   -00104.000000,+00000.000000,-00424.000000
>              Normal   -00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,+00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00104.000000,+00000.000000,-00424.000000
>              Vertex   -00104.000000,+00000.000000,-00056.000000
>              Vertex   -00104.000000,+00032.000000,-00056.000000
>              Vertex   -00104.000000,+00032.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=17
>              Origin   -00072.000000,+00032.000000,-00424.000000
>              Normal   +00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,-00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00072.000000,+00032.000000,-00424.000000
>              Vertex   -00072.000000,+00032.000000,-00056.000000
>              Vertex   -00072.000000,+00000.000000,-00056.000000
>              Vertex   -00072.000000,+00000.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=18
>              Origin   -00104.000000,+00000.000000,-00424.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   -00104.000000,+00000.000000,-00424.000000
>              Vertex   -00104.000000,+00032.000000,-00424.000000
>              Vertex   -00072.000000,+00032.000000,-00424.000000
>              Vertex   -00072.000000,+00000.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=19
>              Origin   -00008.000000,-00032.000000,-00424.000000
>              Normal   +00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,-00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00008.000000,-00032.000000,-00424.000000
>              Vertex   -00008.000000,-00032.000000,-00056.000000
>              Vertex   -00008.000000,-00064.000000,-00056.000000
>              Vertex   -00008.000000,-00064.000000,-00424.000000
>           End Polygon
>           Begin Polygon Texture=eb_girder2 Link=20
>              Origin   +00104.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,-00001.000000,+00000.000000
>              TextureU -00001.000000,-00000.000000,-00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   +00104.000000,-00112.000000,-00056.000000
>              Vertex   +00104.000000,-00112.000000,-00024.000000
>              Vertex   -00152.000000,-00112.000000,-00024.000000
>              Vertex   -00152.000000,-00112.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_girder2 Link=21
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   -00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,+00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00152.000000,-00112.000000,-00056.000000
>              Vertex   -00152.000000,-00112.000000,-00024.000000
>              Vertex   -00152.000000,+00144.000000,-00024.000000
>              Vertex   -00152.000000,+00144.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_girder2 Link=22
>              Origin   +00104.000000,+00144.000000,-00056.000000
>              Normal   +00001.000000,+00000.000000,+00000.000000
>              TextureU +00000.000000,+00001.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,+00001.000000
>              Vertex   +00104.000000,-00112.000000,-00024.000000
>              Vertex   +00104.000000,-00112.000000,-00056.000000
>              Vertex   +00104.000000,+00144.000000,-00056.000000
>              Vertex   +00104.000000,+00144.000000,-00024.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=23
>              Origin   -00152.000000,+00144.000000,-00024.000000
>              Normal   +00000.000000,+00000.000000,+00001.000000
>              TextureU +00000.000000,+00001.000000,-00000.000000
>              TextureV -00001.000000,+00000.000000,+00000.000000
>              Vertex   -00152.000000,-00112.000000,-00024.000000
>              Vertex   +00104.000000,-00112.000000,-00024.000000
>              Vertex   +00104.000000,+00144.000000,-00024.000000
>              Vertex   -00152.000000,+00144.000000,-00024.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=24
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,+00001.000000,+00000.000000
>              Vertex   +00104.000000,+00096.000000,-00056.000000
>              Vertex   +00104.000000,+00032.000000,-00056.000000
>              Vertex   -00008.000000,+00032.000000,-00056.000000
>              Vertex   -00008.000000,+00096.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=25
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   +00056.000000,-00080.000000,-00056.000000
>              Vertex   +00056.000000,+00032.000000,-00056.000000
>              Vertex   +00104.000000,+00032.000000,-00056.000000
>              Vertex   +00104.000000,-00080.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=26
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,+00001.000000,+00000.000000
>              Vertex   +00056.000000,+00000.000000,-00056.000000
>              Vertex   +00056.000000,-00080.000000,-00056.000000
>              Vertex   +00024.000000,-00080.000000,-00056.000000
>              Vertex   +00024.000000,+00000.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=27
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00000.000000,+00001.000000,+00000.000000
>              TextureV +00001.000000,+00000.000000,+00000.000000
>              Vertex   -00104.000000,-00080.000000,-00056.000000
>              Vertex   -00152.000000,-00080.000000,-00056.000000
>              Vertex   -00152.000000,+00144.000000,-00056.000000
>              Vertex   -00104.000000,+00144.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=28
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,+00001.000000,+00000.000000
>              Vertex   -00072.000000,+00000.000000,-00056.000000
>              Vertex   -00072.000000,-00080.000000,-00056.000000
>              Vertex   -00104.000000,-00080.000000,-00056.000000
>              Vertex   -00104.000000,+00000.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=29
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00000.000000,-00001.000000,-00000.000000
>              TextureV -00001.000000,+00000.000000,+00000.000000
>              Vertex   -00072.000000,+00032.000000,-00056.000000
>              Vertex   -00040.000000,+00032.000000,-00056.000000
>              Vertex   -00040.000000,-00080.000000,-00056.000000
>              Vertex   -00072.000000,-00080.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=30
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU +00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,-00001.000000,+00000.000000
>              Vertex   -00040.000000,-00032.000000,-00056.000000
>              Vertex   -00040.000000,+00032.000000,-00056.000000
>              Vertex   +00024.000000,+00032.000000,-00056.000000
>              Vertex   +00024.000000,-00032.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=31
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00000.000000,-00001.000000,-00000.000000
>              TextureV -00001.000000,+00000.000000,+00000.000000
>              Vertex   -00008.000000,-00032.000000,-00056.000000
>              Vertex   +00024.000000,-00032.000000,-00056.000000
>              Vertex   +00024.000000,-00080.000000,-00056.000000
>              Vertex   -00008.000000,-00080.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=32
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00000.000000,-00001.000000,-00000.000000
>              TextureV -00001.000000,+00000.000000,+00000.000000
>              Vertex   -00040.000000,-00064.000000,-00056.000000
>              Vertex   -00008.000000,-00064.000000,-00056.000000
>              Vertex   -00008.000000,-00080.000000,-00056.000000
>              Vertex   -00040.000000,-00080.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=33
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00000.000000,+00001.000000,+00000.000000
>              TextureV +00001.000000,+00000.000000,+00000.000000
>              Vertex   -00040.000000,+00032.000000,-00056.000000
>              Vertex   -00104.000000,+00032.000000,-00056.000000
>              Vertex   -00104.000000,+00144.000000,-00056.000000
>              Vertex   -00040.000000,+00144.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=34
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,+00001.000000,+00000.000000
>              Vertex   -00008.000000,+00064.000000,-00056.000000
>              Vertex   -00008.000000,+00032.000000,-00056.000000
>              Vertex   -00040.000000,+00032.000000,-00056.000000
>              Vertex   -00040.000000,+00064.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_floor1 Link=35
>              Origin   -00152.000000,-00112.000000,-00056.000000
>              Normal   +00000.000000,+00000.000000,-00001.000000
>              TextureU -00001.000000,+00000.000000,+00000.000000
>              TextureV +00000.000000,+00001.000000,+00000.000000
>              Vertex   +00104.000000,+00144.000000,-00056.000000
>              Vertex   +00104.000000,+00096.000000,-00056.000000
>              Vertex   -00040.000000,+00096.000000,-00056.000000
>              Vertex   -00040.000000,+00144.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_girder2 Link=36
>              Origin   -00152.000000,+00144.000000,-00056.000000
>              Normal   +00000.000000,+00001.000000,+00000.000000
>              TextureU +00001.000000,-00000.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00152.000000,+00144.000000,-00056.000000
>              Vertex   -00152.000000,+00144.000000,-00024.000000
>              Vertex   +00104.000000,+00144.000000,-00024.000000
>              Vertex   +00104.000000,+00144.000000,-00056.000000
>           End Polygon
>           Begin Polygon Texture=eb_pillar1 Link=37
>              Origin   -00040.000000,+00096.000000,-00424.000000
>              Normal   +00000.000000,+00001.000000,+00000.000000
>              TextureU +00001.000000,-00000.000000,+00000.000000
>              TextureV +00000.000000,+00000.000000,-00001.000000
>              Vertex   -00040.000000,+00096.000000,-00424.000000
>              Vertex   -00040.000000,+00096.000000,-00056.000000
>              Vertex   -00008.000000,+00096.000000,-00056.000000
>              Vertex   -00008.000000,+00096.000000,-00424.000000
>           End Polygon
>        End PolyList
>     End Brush
>      Brush=Model'MyLevel.Model1105'
>      PrePivot=(X=-152.000000,Y=144.000000,Z=-24.000000)
>      Name="Mover0"
> End Actor
> End Map

![crash](https://user-images.githubusercontent.com/72151582/97087843-68915500-1603-11eb-80fb-370da9ec1f36.png)

Pasted it in a empty level. Subtract a room 512 x 512 x 512. Copy polygons to brushbuilder and build a solid inside the room. When you click rebuild -> CRASH!

This crash also happened sometimes when I converted CSG subtractive / Additive back and forth on some brushes.

**Comment by Chamberly** [comment]
Ok I did this a bit differently. I subtracted a 512x512x512 brush, copied the brush and paste into the editor and then moved it into the 512's area. Selected the pasted brush> polygon to brush, click buildall and then I got this crash.

![image](https://user-images.githubusercontent.com/11419314/109382767-a7386400-78b0-11eb-95ad-2c6ffc97b62a.png)

**Comment by SeriousBuggie** [comment]
Will be good if there be attached map for this crash (just make map and save it, not build geom on it).

**Comment by SeriousBuggie** [comment]
Able reproduce on v469b, so there steps:
1. Start UnrealEd.
2. Open [crash_map.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8890422/crash_map.zip)
3. Press `build geometry`

Expected result: No crash.
Actual result crash:
```
Assertion failed: EdPoly->iLink<Model->Surfs.Num() [File:UnBsp.cpp] [Line: 234]

History: UEditorEngine::bspAddNode <- AddBrushToWorldFunc <- FilterLeaf <- FilterEdPoly <- BspFilterFPoly <- UEditorEngine::bspBrushCSG <- UEditorEngine::csgRebuild <- UEditorEngine::Exec <- (MAP REBUILD VISIBLEONLY=0) <- WEditorFrame::OnCommand <- WM_HSCROLL <- MessagePump <- MainLoop
```

On v469c preview no any crash.
So:

**Confirmed, issue fixed in latest v469c preview.**

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
