### ISSUE TITLE
[469c] Some maps store wrong value of TimeDilation

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1373]
Some maps, like MH-[WKA]SpaceMonsters, store wrong value for TimeDilation on LevelInfo.
In this case it is zero.
```ini
--- LevelInfo LevelInfo0 ---
  TimeDilation=0.000000
  Author="(WKA)Da_Owl"
  IdealPlayerCount="8"
  Summary=LevelSummary'MyLevel.LevelSummary'
  bHighDetailMode=False
  Song=Music'firebr.firebr'
  Screenshot=Texture'MyLevel.Screenshot'
  DefaultGameType=Class'MonsterHunt.MonsterHunt'
  NavigationPointList=InventorySpot'MyLevel.InventorySpot33'
  AIProfile(0)=10340722
  bCheckWalkSurfaces=True
  AmbientBrightness=8
  AmbientHue=255
  Level=LevelInfo'MyLevel.LevelInfo0'
  Tag="LevelInfo"
  Region=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=-1)
  bSelected=True
  Name="LevelInfo0"
```

Game must reset this value on map load for avoid glitches.

Exactly this MH-[WKA]SpaceMonsters very well known with unexplainable glitch with mouse, when mouse stop work, and start work only after press win key. It can be related.

**Comment by SeriousBuggie** [comment]
Player confirm fixed mouse glitch on "MH-[WKA]SpaceMonsters+SBFix" with TimeDilation=1.

**Comment by SeriousBarbie** [comment]
Download fixed map here: https://www.msdatec.de/projects/ut99/#MH_WKA_SpaceMonsters

**Comment by Marco888** [comment]
Could just make UGameEngine::LoadMap restore it to default before eventInitGame call on AGameInfo.
