### ISSUE TITLE
[469c] Texture Pan able stop after while

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1374]
Reproduce:
1. Start play or open in UnrealEd [TestPan.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/12579989/TestPan.zip)
2. If in UnrealEd - switch to 3d view and enable realtime preview:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/8f89ad60-d78d-4092-8b51-759e533b337d)
3. Wait 15 seconds.

Expected result: textures of flags still pan.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/3af93cef-b894-40c2-8185-774487836fb8)
Actual result: Textures of flags stop after while. Red flag stop on 12th second from map load, blue flag stop on 13 second from map load.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/e88b0516-8b96-476c-967d-08d46261a7df)

There on ZoneInfo set high pan speed
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/2b8edc52-b597-4a0c-8e5e-f60307f62a13)
But it only question of time when any pan stops.

On other long run map I got stop on pan 100. With time, lower bound of stop, goes lower.

Math behind pan:
```c++
			// Setup panning.
			FLOAT PanU = Surf->PanU;
			if( Surf->PolyFlags & PF_AutoUPan )
			{
				PanU += (appRound(Frame->Level->GetLevelInfo()->TimeSeconds * 35.f * Draw->Zone->TexUPanSpeed * 256.0f)&0x3ffff)/256.0f;
			}
			FLOAT PanV = Surf->PanV;
			if( Surf->PolyFlags & PF_AutoVPan )
			{
				PanV += (appRound(Frame->Level->GetLevelInfo()->TimeSeconds * 35.f * Draw->Zone->TexVPanSpeed * 256.0f)&0x3ffff)/256.0f;
			}
```
TimeSeconds is float. It grow up in time. So after while it goes too big, so overflow int32. On convert to which be max int. Which with mask produce zero forever.

**Comment by Marco888** [comment]
There is really no reason to perform that bitmask operation since you could just make pan out one direction forever (at least until floating point precision runs out).
