### ISSUE TITLE
[469a] Actors black in game in some cases

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#138]
Reproduce:
1. open [MH-TheFifthVortexBeta8_35.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5433935/MH-TheFifthVortexBeta8_35.zip) In UEd.
2. Switch to dynamic light view (any renderer) - all fine.
![scr_1603582834](https://user-images.githubusercontent.com/70026933/97095706-82ff1900-166b-11eb-9b28-4facfdecc781.png)
![scr_1603582867](https://user-images.githubusercontent.com/70026933/97095707-8eeadb00-166b-11eb-9c56-99717d732cdc.png)
3. start game.
![scr_1603582990](https://user-images.githubusercontent.com/70026933/97095734-de310b80-166b-11eb-8bc5-466da3697ca8.png)

Expected result: Actors are not black.
Actual result: Actors are black.

Rebuild light not help.

**Comment by CacoFFF** [comment]
This reminds me of a 227i bug where if you stood too close to the boundaries of the level cube you'd get no lighting... can you point out the location of those actors?

**Comment by SeriousBuggie** [comment]
Left down corner. Entire area. Castle and all near. 
This tree is dark cross on image:
![scr_1603659702](https://user-images.githubusercontent.com/70026933/97119028-36244c80-1716-11eb-9ce3-5ac60dd4ebc9.png)
But problem exists for all actors in this huge zone/area.

**Comment by stijn-volckaert** [comment]
I'm missing a package called Surface.

**Comment by SeriousBuggie** [comment]
Try this: [Surface.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5439726/Surface.zip)

**Comment by SeriousBuggie** [comment]
Look like this map badly built, and this area no linked light sources for some area. so in game it not lit.

**Comment by SeriousBuggie** [comment]
Bad build for map. If rebuilt it all fine.
Closed, until someone can get better example which reproduce issue after geom rebuild.
