### ISSUE TITLE
[469c] dumpint commandlet does not create object entries if no localized string variable in class

### ISSUE THREAD

**Issue by Deaod** [OldUnreal/UnrealTournamentPatches#1384]
As the title says, the dumpint commandlet does not create entries in the `[Public]` section for objects like Mutator classes, if the class in question does not have at least one localized string variable.

This did not happen with v469b.

**Comment by SeriousBuggie** [comment]
Did you test v469d? Can you make test case?
Exists very similar #1160 issue, which must be already fixed. It is what you mean?

**Comment by Deaod** [comment]
Already Fixed
