### ISSUE TITLE
[469d-RC2] Game crashes when trying to play a map if the map file or any of the required files/dependencies is empty (0 bytes)

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1389]
Inspired also by :
- `https://github.com/OldUnreal/UnrealTournamentPatches/issues/544`
- `https://github.com/OldUnreal/UnrealTournamentPatches/issues/733#issuecomment-1159811658` : 
"In fact this is broken uz file. But this not mean it is must crash game." (epic)

Game crashing when any of the criticial game files is empty (0 bytes) or corrupted, is reasonable and can be accepted, but maybe the game shouldn't crash when selecting an empty map or a map with empty dependency files,
instead it should act just similiar way as it currently acts if a map's dependency file is missing: to show an error message on a black screen ("`Failed lunching URL. Can't find a file for package XXX (package is empty))`", as detecting whether a file in UT is empty or not, should not be a hard thing, steps to reproduce:

1. Find any map (*.unr)
2. See what dependencies it has (*.utx, *.umx, *.uax, *.u)
3. Edit and clean in text editor or replace either the map file or any of the dependency files with an empty file (0 bytes), with same name.
4. Run the game ==> Menu Game ==> Start Practice session ==> Select the map ==> enjoy the game crash : 
"`Critical Error : ReadFile beyond EOF 0+4/0`"

Especially given a fact empty (0 bytes) files in UT are mostly a result of uz decompression silent failure (either a bad uz file, or a bug in UZ tool), where an user might be unaware of having 0 bytes empty files in his UT. 
And even if `# 733` gets fixed, the issue here is still valid because users also use UZ tools externally or download files from internet and put files manually in UT folder.

An example crash when selecting a map with an empty texture dependency  file:

![ss1b](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/2c4ae660-82e3-4fcb-9f6f-e3c18723eead)

**Comment by SeriousBuggie** [comment]
Simplest way for reproduce:
try load in actor browser: [ZeroSizePackage.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/13556734/ZeroSizePackage.zip)

Expected result: No crash.
Actual result: Crash:
```
ReadFile beyond EOF 0+4/0

History: ULinkerLoad::Serialize <- FUnrealfileSummary<< <- LoadSummary <- ULinkerLoad::ULinkerLoad <- 
UObject::GetPackageLinker <- UObject::LoadPackage <- UEditorEngine::Exec <- 
(CLASS LOAD FILE="\System\ZeroSizePackage.u") <- WBrowserActor::OnCommand <- WM_COMMAND
```
