### ISSUE TITLE
[469a] FMOD Music Crash

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#139]
Hi,
Several maps cause UT to just exit with no message.  I am able to play for a few minutes, but then UT just shuts down.  Here is a screenshot of the map.   DM-BunkbedsSD

![Shot00233](https://user-images.githubusercontent.com/59076225/97115532-8e832c00-16cd-11eb-9de1-faeaa29381ae.png)

**Comment by stijn-volckaert** [comment]
Can you give us some information about your setup? Which OS are you playing on? Which renderer and audio driver? What are your rendering and audio settings?

**Comment by stijn-volckaert** [comment]
Confirmed. FMOD crashes when it plays the music for this map. We'll report the bug upstream

**Comment by OMA-Bite-Me** [comment]
Thanks, just a note that it happens on several maps... Not just that one

**Comment by stijn-volckaert** [comment]
Post the names of the maps here please

**Comment by OMA-Bite-Me** [comment]
It only happens on a very few maps and I don't recall the names.  If/when it happens again, I'll post back here

**Comment by Chamberly** [comment]
I think this is related. Was trying out the issue from https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1599326577 and was easily able to reproduce it.
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/5511261/UnrealTournament.log)

**Comment by stijn-volckaert** [comment]
This should be fixed for the upcoming 469b release.
