### ISSUE TITLE
[469d rc2] The crosshair is not displayed correctly if its translucency is turned off.

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#1405]
This happens with all renders.

![_](https://github.com/OldUnreal/UnrealTournamentPatches/assets/10724977/3d1d9d64-3904-4ceb-b74a-5346067b3d62)

**Comment by SeriousBuggie** [comment]
Confirmed on clean local run UT. Not ACE issue.

**Comment by sn260591** [comment]
ChallengeHUD, line 1470:
```
if (bTranslucentCrosshair)
  Canvas.Style = ERenderStyle.STY_Translucent;
else
  Canvas.Style = ERenderStyle.STY_Normal;
```
Should use `STY_Masked` instead of `STY_Normal`.

**Comment by sn260591** [comment]
The hud settings section also needs fixing

![_](https://github.com/OldUnreal/UnrealTournamentPatches/assets/10724977/65607a24-de1f-4226-a154-2c568bf5279b)
