### ISSUE TITLE
[469c] UnrealEd build paths flood in log as crazy

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1413]
Reproduce:
1. Open Dm-Deck16][ in UnrealEd
2. Press "Build paths".
3. Look into Editor.log

Expected result: Log not overflooded.
Actual result: Log fill with lines for each NavigationPoint node:
```
DevPath: Add reachspecs
DevPath: Added reachspecs to PlayerStart1
DevPath: Added reachspecs to PlayerStart2
DevPath: Added reachspecs to PlayerStart5
DevPath: Added reachspecs to PlayerStart6
DevPath: Added reachspecs to PlayerStart7
DevPath: Added reachspecs to PlayerStart4
DevPath: Added reachspecs to PathNode0
DevPath: Added reachspecs to PathNode1
Log: WARNING: InventorySpot44 and PathNode2 may be too close!
DevPath: Added reachspecs to PathNode2
DevPath: Added reachspecs to PathNode3
DevPath: Added reachspecs to PathNode4
DevPath: Added reachspecs to PathNode5
DevPath: Added reachspecs to PathNode6
DevPath: Added reachspecs to PathNode7
DevPath: Added reachspecs to PathNode8
DevPath: Added reachspecs to PathNode9
```

This just insane. And slow down build path process.
My typical use case include 1000-2000 path nodes and constant rebuild it.
This dump in log make it slower.

Basically I need rebuild paths each time when correct them, for see if it properly linked.
Since there no partially built paths, it goes too slow and very annoying.
Typical VCTF map include 500-2000 paths actors, usually placed by hands. Count of rebuilt path easily can be more then hundreds.

**Comment by Marco888** [comment]
Can't you simply Suppress=DevPath?
But yeah for 227 I changed most of these useless path build log lines into debugfSlow.

**Comment by SeriousBuggie** [comment]
Yea. I can. But better not collect data for this calls at all.
