### ISSUE TITLE
[469d rc2] Disappearing texture of a tall palm tree

### ISSUE THREAD

**Issue by Sergiut99** [OldUnreal/UnrealTournamentPatches#1414]
An old game bug that wasn't fixed in the last original patch. If you go to a small palm tree and look at the root of the palm tree, then everything is fine. If you approach a tall palm tree and look down at the root of the palm, the lower part of the palm disappears.
Please fix this bug if possible.

Video on the DM-ArcaneTemple map:
https://youtu.be/l7DbEe4rwN0

**Comment by SeriousBuggie** [comment]
Visibility of meshes depends from mesh pivot. In this case pivot located in mid of tree. When pivot outside of screen, mesh can be not drawn, for reduce load.
