### ISSUE TITLE
[469c] Make LightMaps scale configurable for each level in UnrealEd

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1416]
Currently UnrealEd use next levels for scale lightmaps:
1. PF_HighShadowDetail = 2^4 = 16
2. Nothing = 2^5 = 32
3. PF_LowShadowDetail = 2^6 = 64
4. PF_LowShadowDetail + PF_HighShadowDetail = 2^7 = 128

Will be good if this levels be configurable. This allow make very detailed shadows, without use hack with DrawScale on texture properties and surfaces.
Or opposite - make some levels with very soft (blurry) shadow.

This levels set in FMeshIlluminator::SetupIndex.

**Comment by BerserkerBG** [comment]
This configurable option could be included in the Build Options window. Here is the concept idea with comparison:

![LightMap Scale Concept](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/31dbce79-c44d-4cb6-a896-1a89e907d34f)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/88a08d47-e7a9-438c-9a78-0bd695d63fad)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/fbacb4da-5e10-4c82-bd82-fb69463fa9e3)

**Comment by SeriousBuggie** [comment]
Example of use.
As before:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/c8d833c7-d869-4ef1-a9c9-b9cb94681eae)
More sharp shadows, for all levels:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/f637746d-778c-4ac3-9d0f-c7eaec28a1b5)
Even more sharp shadows (long build time):
This one can hurt FPS badly.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/08fefabf-6a72-4d80-81c8-3f3cf3447478)
Softer, from usual:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/4f4de5a2-5605-4bf6-83a3-8105e5e7af1e)
More soft:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/c231850c-9691-4adf-8b4d-bae567bfa223)
Even more soft:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/667f4f9b-5cc6-4a19-b1b2-f678ac4c8f98)
And more:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/18a6e7ee-14e6-4dba-8753-75fc2e3b49ca)

Some random variation:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/c484bee3-4e41-4cd7-afb1-d222bd2a4790)
And another:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/f986b8b8-37b8-4123-b55f-b11645d0f09b)
Last one:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/43e08ee5-0abd-446d-ad8e-d009e6723efd)
