### ISSUE TITLE
[469d] Coronas in XOpenGL are not shown properly

### ISSUE THREAD

**Issue by guitronimo** [OldUnreal/UnrealTournamentPatches#1434]
I leave you with an image. It is angle depending. Could any setting be wrong?

Oddly, this is just on some maps.... Some look absolutely phantastic
- Square box surrounding it
- More visible depending on angle

![Corona](https://github.com/OldUnreal/UnrealTournamentPatches/assets/78565208/308b8ee0-9901-4aac-a218-55ef1bcb7ad1)

**Comment by SeriousBuggie** [comment]
What wrong here? Can you add "proper" look and explain in words what you expect and what get instead?

**Comment by guitronimo** [comment]
Here is a more detailed image. The Coronas do have a square surrounding. This is unexpected.
![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/78565208/a68cdf99-dfff-4b5d-b7d0-202e2ecebde5)


This for example, same Install, different Map looks just nice
![nice](https://github.com/OldUnreal/UnrealTournamentPatches/assets/78565208/2b796cdc-7de7-49d3-8e1d-2220a1eb8004)


In OpenGL all maps look ok - there is no such issue

**Comment by guitronimo** [comment]
Here is same spot compraison

OpenGL
![scopeOpenGL](https://github.com/OldUnreal/UnrealTournamentPatches/assets/78565208/b70f9f6b-2e88-4097-a24d-8ee3ed81b223)

XOpenGL
![scopeXOpenGL](https://github.com/OldUnreal/UnrealTournamentPatches/assets/78565208/58182845-ae84-44ec-87f1-a061ec7ec7b4)

**Comment by guitronimo** [comment]
Hey there, 

i have done some research and i am glad to report that this may not be a issue. So im gonna close this.  
It appears that the used Texture here is not "sophisticated" enough to fit the job. 
In the example the used Texture is 
```
Texture'GenFX.LensFlar.3'
```

whereas on better looking Maps they have used: 
```
Texture'GenFX.LensFlar.new3'
```

There will be a reason why this new Texture exists in same package. 
Why XOpenGL Renders this differently and whether this is an issue thats fixable or not, only you guys will know. 
For now i can tell our community that this map may need some makeup for the future as it is one of the most played ones. 

Thanks anyway
