### ISSUE TITLE
[469c] Make lightmap scale independant from surface scale

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1435]
Lightmap scale is affected by surface scale. When a texture surface is scaled, then the lightmap also scales with it. Most maps have surfaces with different scales than 1.00, this will result in mismatched shadow detail between surfaces. Here is a visual example: 
![Screenshot_27](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/f2c25416-abab-4187-8aad-4c1e77bff4ac)

This example showcases what happens between surfaces that have different scale.

## Reproduce Steps:
1. Open example map in Ued [Lightmap_and_Texture_Surface_Scale.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/13209246/Lightmap_and_Texture_Surface_Scale.zip)
2. Rebuild Lights

## Expected Result:
![Screenshot_26](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/acb22df9-30ae-41bf-8809-dff42cb4c759)

Wall shadows must match the soft floor shadows.

## Actual Result:
![Screenshot_25](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/3fe15113-b460-4cec-8f1f-50e6a01b3109)

Wall shadows detail is not matching the floor shadows.

## Feature Request:
Make a checkbox in Build Options, which will make lightmap scale independant from surfaces scale. This will result in consistent lightmap scale between surfaces with different scale values. Some name ideas for this feature -  "Lightmap Surface Independant", "Ignore Surface Scale on Lightmaps" or "Uniform Lightmap Scale".

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1702157752](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/dd58fc0f-f806-40df-8f19-bea47090f085)
![scr_1702157779](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/6616bd3e-d1db-4b54-9be0-29de6069e395)
![scr_1702157792](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/a896b806-3894-44f5-8d54-812e216f8d75)
