### ISSUE TITLE
[469d-RC4] Cursor Mouse no longer working after changing screensize

### ISSUE THREAD

**Issue by guitronimo** [OldUnreal/UnrealTournamentPatches#1436]
When running in cursor mode and changing windowsize the mouse is not reacting anymore X and Y, only firing works. 

Reproduce: 
- Run Cursor Mode in Fullscreen
- Change to Window mode

This is also the case when starting in Window Mode and changing Width of game Window. 

Running on XOpenGL, Windows 11, 469D-RC4 - Other renderers same issue

In 469D RC3 and lower this seems to be fine.

**Comment by SeriousBuggie** [comment]
I check on Windows 7, there no such issue.

Try set 
```ini
[WinDrv.WindowsClient]
UseLegacyCursorInput=True
```
And reproduce it again.

**Comment by guitronimo** [comment]
If i set 
```
UseLegacyCursorInput=False
```

Then it appears to work. On True it definaltey has this problem on Windows 11. I can check windows 10 Tomorrow. 
UT and TO btw. So no mod required to check. Its even in practice session

**Comment by guitronimo** [comment]
Must correct this post: 
Does NOT happen in practice session. 

I tested now Windows 10 with same issue. 
When i connect to a server (UT - Some random leight weight CTF Server) i have same issue on Windows 11 and Windows 10. 
Just resizing of window and Mouse doesnt move anymore

**Comment by SeriousBuggie** [comment]
`UseLegacyCursorInput=True` can not work on Windows 10 after some update (Creators). So if you use Win!0+, you need set it to False. True can be glitchy.

**Comment by guitronimo** [comment]
Setting this to false works, at least it looks like. 

Setting this to true on Win10 and 11 i have the issue. In UT it doesnt even take a Resize of window. Enough to die and then respawn. Mouse not working anymore

**Comment by SeriousBuggie** [comment]
Value "True" is not issue on Win10+. This option introduce for preserve old input on Windows below 10. This can't be fixed.

**Comment by an-eternity** [comment]
> UseLegacyCursorInput=True can not work on Windows 10 after some update (Creators).

What is the date of that update?
I have tested v469d RC4 with Windows 10/11 21H2/22H2 and didn't see any cursor-related issues. Can't reproduce this current issues as well.

**Comment by SeriousBuggie** [comment]
https://en.wikipedia.org/wiki/Windows_10,_version_1709
> Windows 10 Fall Creators Update[[1]](https://en.wikipedia.org/wiki/Windows_10,_version_1709#cite_note-1) (also known as version 1709 and codenamed "Redstone 3") is the fourth major update to Windows 10 and the third in a series of updates under the Redstone codenames. It carries the build number 10.0.16299.
>
> The first preview was released to Insiders on April 7, 2017. The final release was made available to Windows Insiders on September 26, 2017, before being released to the public on October 17.[[2]](https://en.wikipedia.org/wiki/Windows_10,_version_1709#cite_note-2)
> 
> The update would have originally reached end of service on April 14, 2020 for Education and Enterprise editions, but this was postponed to October 13 of the same year due to "global health crisis", in reference to the [COVID-19 pandemic](https://en.wikipedia.org/wiki/COVID-19_pandemic), after the release of build 16299.2166.[[3]](https://en.wikipedia.org/wiki/Windows_10,_version_1709#cite_note-3)[[4]](https://en.wikipedia.org/wiki/Windows_10,_version_1709#cite_note-16299b2166-4)[[5]](https://en.wikipedia.org/wiki/Windows_10,_version_1709#cite_note-5)

**Comment by guitronimo** [comment]
Well in the meantime a friend of mine, from very different location, Install, Computer has confirmed same issue. 

Here again the conditions under which the problem occurs:

- Mouse set to Cursor Input
- Resizing of Screenwitdth
- UseLegacyCursorInput=True
- Windows 10 & 11 (win 11 22H2 - is mine)
- Connected to online server ONLY

It does NOT occur in Practice session nor it appears when start server and play on it with same install. 

We've checked that on random servers. Latest i have been using was 
CTF UT Pure 185.107.96.18:7777

**Comment by SeriousBuggie** [comment]
Again: "UseLegacyCursorInput=True" + Win10+ = not issue. This not consider as issue. So you can not waste time for investigate it. This combination will not work, and we cant fix it.

**Comment by guitronimo** [comment]
Sorry then this is a misundertstanding. 

I interpreted to set this true, which btw. is default. 

> I check on Windows 7, there no such issue.
> 
> Try set
> 
> ```ini
> [WinDrv.WindowsClient]
> UseLegacyCursorInput=True
> ```
> 
> And reproduce it again.

Indeed you corrected this by saying 

> can not work on Windows 10 after some update (Creators).

You need to understand that you have access to sources whereas we dont even know what which option does since nothing is really documented, at least not public - which is fine, but frustrating if you take dozens of hours supporting you guys with testing, even reproducing stuff over a game which i dont even play. 

All i am saying is there is an issue, if its fixable or not my business. But this post possibly helps others who run into the same problem. And this then should not be set default to true. Win 10 and 11 are the standards these days. 

Anyway, 

thanks for support, you do an incredibly great job. 

Then this is not an issue -> closed

**Comment by an-eternity** [comment]
Finally able to reproduce it - but only on some servers that use "UT Pure", and with `UseLegacyCursorInput=True` of course.
Couldn't reproduce it neither on my test servers nor on other servers before...

**Comment by guitronimo** [comment]
I think UT Pure may be just a sideeffect here. I also have this without UT Pure. I discovered it in Tactical Ops which clearly doesnt have any UT Pure installed. Also on my local UT Server which doesnt have any mod at all accept for Nexgen, ACE and MapVote. 
 
Again, mainly reported because of others may run into this aswell.
