### ISSUE TITLE
[469d] Trojan warning

### ISSUE THREAD

**Issue by sinjuangajan** [OldUnreal/UnrealTournamentPatches#1438]
Someone has reported a Trojan warning. I asked him for more details. I don't have that issue and cannot reproduce it. 

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/4011140/468f599b-81ae-46a7-8531-2337eb8028ae)

**Comment by SeriousBuggie** [comment]
It is bad joke from person which called DK Destroyer. It it s not real, just joke.
Closed, since it is not real issue.
