### ISSUE TITLE
Multiple Thighpads in Level do-not increase player Armour

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#144]
ok , if you have multiple Thighpads in a level and pick them up 1 by 1 they will not register beyond 50 Armour.
build a room add 3 thighpads (for maximum armour of 150) and play level.
Armour will not increase beyond 50 Armour.

hope this is clear.

Cheers.

**Comment by SeriousBuggie** [comment]
By design. You wear thighpads. You can wear only one thighpads. So you armor never be more than 50.

**Comment by alsosed** [comment]
this is as it should be, also and with Armor (cannot be more than 100)

**Comment by stijn-volckaert** [comment]
This is the intended behavior so we cannot/will not change this
