### ISSUE TITLE
Crosshair preview not working/broken 469d.rc4 on Windows/Linux

### ISSUE THREAD

**Issue by gugg305** [OldUnreal/UnrealTournamentPatches#1443]
Crosshair preview in preferences menu not showing selected crosshair when moving slider. patch version 469d.rc4 on Linux.
Running native resolution 1920x1080 Linux and Windows have the same problem.

**Comment by SeriousBuggie** [comment]
Need more info. Screenshot and steps for reproduce.

For me all work:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/4f506153-1b0f-4025-8c69-e9ddf417fd27)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/a8c834bf-802f-401b-a1d3-ffd0fdc4f27b)
