### ISSUE TITLE
Add in support for toggling on and off line occlusion in the editor, per viewport (for renderers that support it)

### ISSUE THREAD

**Issue by metallicafan212** [OldUnreal/UnrealTournamentPatches#1451]
A common complaint I've seen about the newer renderers (including my ICBINDx11 driver) is that lines are occluded by default in 3D views (which doesn't happen in DX7, Software, etc.). However: tons of people (myself included) find the occlusion very helpful for placing actors, lining up specific brushes, etc.

My suggestion: add a SHOW flag for toggling this on and off, which the render device can test for. A possible additional option (to make it easier for renderers to add) is to add a LINE flag that's added to the line when drawing, and the renderer can just do 

if(LineFlags & LINE_DrawOver)

In my HP2 editor, I implemented this as a button on the viewport bar, allowing the user to quickly turn this on and off.

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/5996243/6e183a65-65e7-4d7f-a810-7a3e28fd8267)

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/5996243/7fcc20ef-3e29-4009-b51e-d13ea32645e7)

**Comment by metallicafan212** [comment]
Here's what my button does in my UnrealEd. This is how I imagine it (should) work when added to the editor:

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/5996243/9a3fed73-71a5-4177-88d1-65927f9c50da)
![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/5996243/d35f4b19-3cad-47b6-b19c-b85f66798886)

If an icon is needed, Omega59 can help, he did all the icons for the HP2 editor, and he's good at matching the original style Epic had. We just went with a Windows 7 style as we liked it.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1726373409](https://github.com/user-attachments/assets/9644d5ea-b268-4ce2-b217-886d3e8f67c9)
`SHOW_OccludeLines  	= 0x00100000,	// Occlude 3D lines by geometry. Must be implemented inside rendevs.`

**Comment by metallicafan212** [comment]
Will this be saved into the config, or enabled by default?

**Comment by SeriousBuggie** [comment]
Enabled by default, loaded from config. If in config exist values -used this one, not default. All as usual.
