### ISSUE TITLE
[469a] Sound spatialization issues in Tactical Ops

### ISSUE THREAD

**Issue by lumi1776** [OldUnreal/UnrealTournamentPatches#146]
In relation to Tactical-ops
All sound optiions do not work as expected. 
All options AL, Cluster and Galaxy do not give acurate sound location in game especially compared to the old galxay audio
With cluster you may even loose all sounds entirely related to your player but hear everything else but with no locations. the sound is all around you.
AL audio cant seem to balance left right and middle accurately 
None can gauge distance or locations 
The old galaxy audio works in 451
Unfortunately not useable at present

Thanks guys for your efforts so far :D

**Comment by stijn-volckaert** [comment]
Already fixed for 469b

**Comment by lumi1776** [comment]
Thanks..also i sometimes loose all sounds related to my player. Eg gun sounds footsteps

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
