### ISSUE TITLE
Object property referencing the source actor will cause an infinite busy recursion loop in the properties window

### ISSUE THREAD

**Issue by metallicafan212** [OldUnreal/UnrealTournamentPatches#1462]
Video of this in action: https://www.youtube.com/watch?v=sQZ3eiE_UCg

Test class:

```Unrealscript
class TestPropRecursion extends actor;

// Metallicafan212:	This in of itself itsn't a problem, it's the sub object properties that cause issues
var() Array<TestPropRecursion> SubActors;
```

I have a in-progress fix for this, by reimplementing WProperties::ForceRefresh

Edit:
Easy instructions to reproduce (this will work with any other object properties, including the class I used)
1. Spawn two actors
2. Set the base of them to point to each other
3. Expand the base property, sub object property, and then navigate to the hidden actor section to see the base
4. Extend the base of the other actor and extend the fake object properties
5. Now the source actor has a sub object property of the other actor, which also has a sub object property of the parent object (recursive loop)
6. Click the other actor
7. UnrealEd enters a busy loop, infinitely adding properties

The properties window should look like this before clicking on the other actor:
![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/5996243/d01ec90d-3ad0-4754-9d96-92706859aa2a)

**Comment by SeriousBuggie** [comment]
Can you add test map, please? With easy instruction how reproduce this issue on it.

**Comment by metallicafan212** [comment]
Test map: [TestPropRecursion.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/13483189/TestPropRecursion.zip)
