### ISSUE TITLE
[469b] Game speed / framerate limit affects falling/boosting/dodging speed

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#147]
Reproduce: 
1. Start as spectator [dm-aaa_jump_test.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5495638/dm-aaa_jump_test.zip)
2. run `addbots 1` for add one bot.
3. Spectate on bot.
4. Enter command `slomo 10` and after few time `slomo 20`.

Expected result: Bot move like when SloMo = 1: jump to top, success pickup shield, return back and so on.
Actual result: On Slomo 10 bot near all time fail to jump to top. On Slomo 20 bot even not try jump to top, just pickup armor again and again.

Possible cause: rounding error.

v469b preview: bugged.
v436: bugged.

**Comment by SeriousBuggie** [comment]
This stuff depends on some other things, like total amount of actor, nodes, brushes, complexity map and so on. Because on DM-Deck16][ with changed paths difference visible even when SloMo = 2.

**Comment by stijn-volckaert** [comment]
This should be fixed in the latest 469c previews.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
