### ISSUE TITLE
[469c] mouse wanders off into background windows in "Windowed mode"

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#1472]
so i play predominantly in windowed mode.. because i switch back and forth between things.
when i try to play in this mode however .. the mouse will randomly click outside of the game window onto something on the desktop
taking me out of the game.

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72378011/c23672af-8c80-4c3d-8533-3423ba9d25e4)

**Comment by guitronimo** [comment]
I can confirm this issue - also in 469D-Release
- when the window is snapped top and bottom of screen that the problem doesnt occur for me. 
- also does not occur for me when window is not touching any of the windows screen borders

For me it it appears that fast movement in combination with click triggers the problem. There are times when i think its more the right click than the actual firebutton - but vague statement... 

Maybe helps. Cheers
