### ISSUE TITLE
[469d] Not launching on Intel Mac, MacOS 10.13.6 High Sierra. "Crashed unexpectedly" while 469dRC4 was running fine

### ISSUE THREAD

**Issue by caver01** [OldUnreal/UnrealTournamentPatches#1477]
Just grabbed latest release of 469d to update an existing setup that has been working great with 469dRC4 (Aug 21 preview). Launched, but after a moment, it crashes, UnrealTournament.log is ZERO bytes.

Mac mini (mid 2011), 2.7 GHz Core i7, 16GB RAM
MacOS 10.13.6 High Sierra (all patched and updated to latest this mini can run!)

This setup has been running flawlessly on 469dRC4, and for the last month or so, even working great as a dedicated server via UCC (command line batch).

Put the RC4 version back in the applications directory and everything works again.
I also tried swapping out my entire Unreal Tournament folder from ../Application Support directory with a barebones copy and the story is the same--RC4 launches fine, but the final release of 469d crashes at launch. Not sure what else I can look at, but happy to try things. . .

**Comment by stijn-volckaert** [comment]
I have just tried to reproduce this crash on my mac, but everything seems to work fine here. Could you check your console applications to see if there's anything in the crash logs?

Alternatively, could you try launching the UnrealTournament binary embedded in the application bundle from a terminal window?

**Comment by caver01** [comment]
I can try these things in a while but I should have added, 469d runs fine on my M1 Mac mini running Ventura. It’s just the older system that fails.

**Comment by caver01** [comment]
Checking console here are the events when I launched the app:
```
9638: 0x5a1da	default	14:43:01.513309 -0800	UnrealTournament	WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.6 instead of 10.13.6. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
Call location:
9638: 0x5a1da	default	14:43:01.513715 -0800	UnrealTournament	0   CarbonCore                          0x00007fff48f08378 ___Gestalt_SystemVersion_block_invoke + 112
9638: 0x5a1da	default	14:43:01.513762 -0800	UnrealTournament	1   libdispatch.dylib                   0x00007fff6fcc8db8 _dispatch_client_callout + 8
9638: 0x5a1da	default	14:43:01.513798 -0800	UnrealTournament	2   libdispatch.dylib                   0x00007fff6fcc8d6b dispatch_once_f + 41
9638: 0x5a1da	default	14:43:01.513833 -0800	UnrealTournament	3   CarbonCore                          0x00007fff48e98c30 _Gestalt_SystemVersion + 948
9638: 0x5a1da	default	14:43:01.513868 -0800	UnrealTournament	4   CarbonCore                          0x00007fff48e98476 Gestalt + 139
9638: 0x5a1da	default	14:43:01.513901 -0800	UnrealTournament	5   UnrealTournament                    0x0000000107f1e551 _Z18appPlatformPreInitv + 49
9638: 0x5a1da	default	14:43:01.513936 -0800	UnrealTournament	6   UnrealTournament                    0x0000000107f01874 _Z7appInitPKwS0_P7FMallocP13FOutputDeviceP18FOutputDeviceErrorP16FFeedbackContextP12FFileManagerPFP12FConfigCachevEi + 84
```

**Comment by caver01** [comment]
Tried opening the executable within the .app contents. . . here is what came through in terminal window:

```
Last login: Mon Dec 11 15:50:45 on ttys000
Intel-Mac-mini:~ mac$ /Applications/Games/UT/UnrealTournament.app/Contents/MacOS/UnrealTournament ; exit;
WARNING: using preference directory: /Users/mac/Library/Application Support/Unreal Tournament/System/
WARNING: Using system ini file: /Users/mac/Library/Application Support/Unreal Tournament/System/UnrealTournament.ini
WARNING: Using user ini file: /Users/mac/Library/Application Support/Unreal Tournament/System/User.ini
Segmentation fault: 11
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...3 completed.

[Process completed]
```

**Comment by caver01** [comment]
Here's a copy of the crash report:
[crashreport.txt](https://github.com/OldUnreal/UnrealTournamentPatches/files/13654114/crashreport.txt)

**Comment by caver01** [comment]
Looking at the console on a successful launch of 469dRC4, the above console items are also present, but instead of crashing, this follows:
```
10038: 0x5deca	default	15:20:56.876324 -0800	UnrealTournament	CVCGDisplayLink::setCurrentDisplay didn't find a valid display - falling back to 60Hz
```
I failed to mention that my system is running "headless" which is how it should be run I am using UCC to run a dedicated server, but with RC4 I can also just launch the game and actually play it via VNC or apple screen sharing. Not sure if something in latest release doesn't like a headless system now. . . or I am just grasping.

**Comment by stijn-volckaert** [comment]
Crash reproduced on macOS Catalina

**Comment by stijn-volckaert** [comment]
It looks like this was a compiler bug. Older versions of the macOS dynamic linker were no longer processing (some) of the weak bindings in the UCC and UnrealTournament binaries. This lead to a call through a null pointer on startup.

I've recompiled the binaries using the build tools for xcode 15.1 and the problem went away. The updated binaries are attached to the GitHub release post.

**Comment by caver01** [comment]
Thanks for finding it. Updated and works great. Much appreciated.
