### ISSUE TITLE
[469d] ChallengeBotInfo.AdjustSkill (used for Auto Ajust Bots Skill) not limited at all

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1489]
When you select "Auto Adjust Skill", skill of bots can grow up indefinitely, without any bounds.
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/1379b89f-f4f8-471f-ac1c-1f9ea89f818d)
```unrealscript
function AdjustSkill(Bot B, bool bWinner)
{
	local float BotSkill;

	BotSkill = B.Skill;
	if ( !b.bNovice )
		BotSkill += 4;

	if ( bWinner )
	{
		PlayerKills += 1;
		AdjustedDifficulty = FMax(0, AdjustedDifficulty - 2/Min(PlayerKills, 10));
		if ( BotSkill > AdjustedDifficulty )
			B.Skill = AdjustedDifficulty;
		if ( B.Skill < 4 )
		{
			B.bNovice = true;
			if ( B.Skill > 3 )
			{
				B.Skill = 3;
				B.bThreePlus = true;
			}
		}
		else
		{
			B.Skill -= 4;
			B.bNovice = false;
		}
	}
	else
	{
		PlayerDeaths += 1;
		AdjustedDifficulty += FMin(7,2/Min(PlayerDeaths, 10));
		if ( BotSkill < AdjustedDifficulty )
			B.Skill = AdjustedDifficulty;
		if ( B.Skill < 4 )
		{
			B.bNovice = true;
			if ( B.Skill > 3 )
			{
				B.Skill = 3;
				B.bThreePlus = true;
			}
		}
		else
		{
			B.Skill -= 4;
			B.bNovice = false;
		}
	}
	if ( abs(AdjustedDifficulty - Difficulty) >= 1 )
	{
		Difficulty = AdjustedDifficulty;
		SaveConfig();
	}
}
```
There no any check for top limit.
So this value can grow up beyond max level 7 (godlike) and ruin custom mods.
It even ruin own bots code.

Bot.Skill must never goes above 3.
If used godlike it must be `bNovice  = false` + `Skill = 3`.
But this code allow it grow up much more. I have recent logging, where it reach values like 15.

For example, some code in Bot.uc:
`aimerror = aimerror * (1.7 - 0.4 * (skill + FRand()));`
Which must be positive, since max normal value for skill is 3.
If pass here 15, then it be negative in most cases.

Skill also affect for distance of search inventory:
```unrealscript
		MaxDist = 500 + 70 * skill;
		foreach visiblecollidingactors(class'Inventory', Inv, MaxDist,,true)
```
So with enormous big skill bots just scan whole level for inventory, and can make server lags.

```unrealscript
		else if ( Level.TimeSeconds - LastInvFind < 3 - 0.5 * skill )
		{
			PickRegDestination(bNoCharge);
			return;
		}

		LastInvFind = Level.TimeSeconds;
		bGathering = false;
		MaxDist = 700 + 70 * skill;
		BestWeight = 0.5/MaxDist;
		foreach visiblecollidingactors(class'Inventory', Inv, MaxDist,,true)
```
Constantly search for inventory.

In hunting do too much checks and so on. I guess enough examples why it bad.

**Comment by SeriousBuggie** [comment]
Also code above act wrong if adjust not happen.
It set bNovice flag.
For example game only started, AdjustedDifficulty is zero, godlike bot killed by player.
This lead to set bNovice to true, which suddenly make bot from godlike to skilled.

**Comment by SeriousBuggie** [comment]
Possible proper way do this - call Bot.InitializeSkill, since change skill of bot, it is not only change variable Skill. It must update other things as well.
However, it can cause some side-effects if do reinit bot skills in mid-game. So need check it.

**Comment by no0nehere** [comment]
afaik theres no way to adjust bots skills midgame.. this would be awesome if there was a way.
also be nice if the autoadjust skill toggle worked on a server.

**Comment by SeriousBuggie** [comment]
You can write mutator for that. It relatively easy, there no any problems with that.
