### ISSUE TITLE
[469b-Preview-20201103] Weapons Factory Mod 106 does not work with 469

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#149]
in 469b, the Weapons Factory weapons don't appear when summoned in-game.  For example, summoning the Chaincannon results in this error :
ScriptLog: Fabricate wfcode.wfchaincannon
Log: Failed import: Function Function UMenu.UMenuBlueLookAndFeel.ControlFrame_Draw (file ../System/UMenu.u)
Warning: Failed to load "wfcode": Can't find Function in file "Function UMenu.UMenuBlueLookAndFeel.ControlFrame_Draw"..
Warning: Failed to load "Class wfcode.wfchaincannon": Can't find Function in file "Function UMenu.UMenuBlueLookAndFeel.ControlFrame_Draw"..

This happens with other WF weapons as well in 469 - works OK in 436 and 451.  I only use the weapons (I summon them, have them in StuffSwapper or have them assigned to ScriptedPawns) so have no idea about how well the mod works as a whole in 436 and 451.

The mod can be had from http://www.ut-files.com/index.php?dir=GameTypes/Weapons%20Factory/&file=wfut_beta_107.rar

**Comment by stijn-volckaert** [comment]
We'll have a fix for this in the next preview
