### ISSUE TITLE
libcurl.dll in OldUnreal-UTPatch469a-Windows.zip triggers BitDefender AV 

### ISSUE THREAD

**Issue by will514** [OldUnreal/UnrealTournamentPatches#15]
Extracting the OldUnreal-UTPatch469a-Windows.zip release triggers BitDefender AV with this message:

The file C:\Users\William\Downloads\OldUnreal-UTPatch469a-Windows\System\libcurl.dll is infected with Trojan.GenericKD.43825591 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

Probably a false positive, but worth looking into.

**Comment by stijn-volckaert** [comment]
Correct, this is the official libcurl.dll version 7.71.0 downloaded from https://curl.haxx.se/windows/

This is not the first time libcurl triggers malware protection and it won't be the last time either. If you're not comfortable with having this file on your machine, then feel free to delete it. It is only used as an optional server-side feature anyway. You can also download the new version from the website mentioned above and put that in your system folder.

**Comment by will514** [comment]
That's what I suspected. Thanks for the confirmation 👍

**Comment by Arkl1te** [comment]
I don't have any third-party antivirus software installed. SmartScreen warned me.
![image](https://user-images.githubusercontent.com/68290346/94195424-5cda3380-fe89-11ea-88c5-9e4b6738c383.png)

**Comment by Dr-Flay** [comment]
> I don't have any third-party antivirus software installed.
> SmartScreen warned me from the installer itself (OldUnreal-UTPatch469a-Windows.exe)
Yes if you understand what it says you would not be so worried.
Defender does not recognise it yet and it does not use a certificate so the publisher cannot be verified.
That isn't a malware warning, just an "I don't know what it is or what I should do" warning.
Defender does this with anything new because it is neophobic and is just a glorified white-list program.
