### ISSUE TITLE
[469b-Preview-20201102] Time demo show wrong FPS counter

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#150]
By my feelings in scene no lags at all. `stat fps` and `stat global` show data more like truth.
![screen](https://user-images.githubusercontent.com/70026933/98293959-cfc1e880-1fb7-11eb-8046-e3d0af1cff92.png)
Possible `stat global` wrong too.

If need steps for reproduce I can add later on request.

**Comment by stijn-volckaert** [comment]
I think this is the same issue as #1033. This should be fixed in 469d

**Comment by SeriousBuggie** [comment]
Yes. It is duplicate of #1033
