### ISSUE TITLE
[469d] UCC masterserver crashed if try exit from it with Ctrl+C

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#1504]
Reproduce:
1. Start `ucc masterserver`
2. Press Ctrl+C for exit.
3. Press it again.

Expected result: Ucc correctly shutdown. Possible after first press Ctrl+C.
Actual result: Ucc not do anything after first press Ctrl+C. On second press it crashed and show window message about APPCRASH.

**Comment by an-eternity** [comment]
Tried to reproduce, but no crash...
IIRC, Ctrl+C combo never used for exit in UT (some step in Reproduce missed?).
Ctrl+C is a default combo to copy selected text to clipboard and it works properly in v469d system console.

**Comment by SeriousBuggie** [comment]
It in system console, not in UT console. And it already fixed in test builds. You need check it on 469d, not on test build, on test build it already fixed.
It must crash on any windows version.

**Comment by an-eternity** [comment]
I tested it with v469d final release.
Probably, something differs in my case that makes this crash not occur...
