### ISSUE TITLE
MacOS Warning: Failed to Enter Entry: Can't find file Entry 

### ISSUE THREAD

**Issue by davidagnome** [OldUnreal/UnrealTournamentPatches#1505]
### Replication Steps
- Install 469d MacOS version to Applications
- Copy Maps, Music, Sounds, Textures Folder from Existing Windows Installation to ~/Library/Application Support/Unreal Tournament/
- Go into Textures folder and delete LadderFonts.utx and UWindowFonts.utx  

### System Info
Operating System macOS 14.2.1
CPU M1
RAM 16GB
Model ID Macmini9,1

### Screenshots
![Screenshot 2024-01-23 at 7 20 11 PM](https://github.com/OldUnreal/UnrealTournamentPatches/assets/5984719/13772783-e461-4257-8c34-484cae645394)

**Comment by SeriousBuggie** [comment]
What info appear in UnrealTournament.log file?

**Comment by davidagnome** [comment]
I found a fix. Instead of going into Library/Application Support, simply
opening the app package in Applications and adding the game content folders
to the MacOS subfolder will work

Thanks
David P
Personal Email

**Comment by deornoth** [comment]
I'm seeing this error as well. Tried it on an Intel Mac and an Apple Silicon Mac. 

davidagnome's fix didn't work for me.

Here are the errors in the log file:

Log: LoadMap: Entry
Warning: Failed to load Entry: Can't find file Entry..
Warning: Failed to load "Level None.MyLevel": Can't find file Entry..
Critical: appError called:
Critical: Failed to enter Entry: Can't find file Entry.
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing USDLClient::ShutdownAfterError
Critical: Propagating Error

**Comment by SeriousBuggie** [comment]
Check solution above. Also ensure you copy game content in uncompressed form.
In Maps folder must be Entry.unr, not Entry.unr.uz.

**Comment by deornoth** [comment]
Ok. I missed the part about decompressing I guess. That fixed it. Don't need the solution above.

**Comment by godzfire** [comment]
I hate to reopen this, but having this issue and none of the above works:
<img width="260" alt="image" src="https://github.com/OldUnreal/UnrealTournamentPatches/assets/2067820/15834db6-84e0-46c2-b868-cedd79f79dee">

- Mac Mini Intel 2018
- MacOS 12.7.4 (21H1123)
- Files in proper App Support / UT Folder
- Entry.unr in maps

Error log:
`Log: Log file open, Thu May 30 20:57:53 2024
Init: Name subsystem initialized
Init: Version: 469
Init: Revision: d (Release)
Init: Compiled: Dec 13 2023 14:47:24
Init: Command line: 
Init: Base directory: 
Init: Character set: Unicode
Init: Object subsystem initialized
Init: OS: MacOS 12.7.4
Init: CPU Detected: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (GenuineIntel)
Init: CPU Features: INVARIANT_TSC CMov FPU RDTSC PAE MMX SSE SSE2 SSE3 SSSE3 SSE4_1 SSE4_2 AVX AVX2
Init: CPU Processors=12
Init: Timer Frequency=3192.025120 MHz - Timing Source = gettimeofday
Log: Engine.Engine.RenderDevice was GlideDrv.GlideRenderDevice... Forcing use of OpenGLDrv instead.
Log: Engine.Engine.GameRenderDevice was SoftDrv.SoftwareRenderDevice... Forcing use of OpenGLDrv instead.
Log: Engine.Engine.AudioDevice was Galaxy.GalaxyAudioSubsystem... Forcing use of ALAudio instead.
Init: Unreal engine initialized
Warning: Failed to load "Class MacDrv.MacClient": Object not found: Class MacDrv.MacClient.
Warning: Object not found: Class MacDrv.MacClient
Init: Detected 0 joysticks
Init: SDLClient initialized.
Init: Lighting subsystem initialized
Init: Rendering initialized
Log: LoadMap: Entry
Warning: Failed to load Entry: Can't find file Entry..
Warning: Failed to load "Level None.MyLevel": Can't find file Entry..
Critical: appError called:
Critical: Failed to enter Entry: Can't find file Entry.
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing USDLClient::ShutdownAfterError
Critical: Propagating Error
Log: HandleError
Uninitialized: Log file closed, Thu May 30 20:57:55 2024
`

**Comment by SeriousBuggie** [comment]
`Init: Base directory:` - somehow it not see Base Directory. What about access rights? Can be it blocked for this app?

**Comment by godzfire** [comment]
> `Init: Base directory:` - somehow it not see Base Directory. What about access rights? Can be it blocked for this app?

I don't think so, how would I be able to check?

**Comment by SeriousBuggie** [comment]
Google tell me this: https://support.apple.com/en-en/guide/mac-help/mchlp1203/mac

**Comment by godzfire** [comment]
> Google tell me this: https://support.apple.com/en-en/guide/mac-help/mchlp1203/mac

<img width="224" alt="image" src="https://github.com/OldUnreal/UnrealTournamentPatches/assets/2067820/e93e8142-de35-4877-a064-fc1253a5d1e7">

I don't think it's this because I've never had issues with app privs before and I use a LOT of apps in different locations and drives.

**Comment by shadeglare** [comment]
> Ok. I missed the part about decompressing I guess. That fixed it. Don't need the solution above.

Hey. How to decompress uz files on Mac? Or I need a windows machine for it?

**Comment by godzfire** [comment]
Anyone have any ideas?

**Comment by godzfire** [comment]
Anyone?

**Comment by godzfire** [comment]
Hello? I still don't have an answer how to fix this.

**Comment by davidagnome** [comment]
> Hello? I still don't have an answer how to fix this.

Did you right click on the App, go into package contents, and follow these directions?

it’s what fixed my installation on an M1 Mac Mini.

**Comment by hejhugo** [comment]
I'm not sure if some of you are still searching for a solution to this, but despite what the documentation suggests, you have to place the game content folder in `/Applications/UnrealTournament.app/Contents/MacOS` this approach worked for me.

**Comment by RobS69** [comment]
I think i've solved this because I had the same problem.

You need to make sure you download the matching patch and assets folder. For me, I downloaded UT2004 but the old Unreal Installer. That doesn't work.
Basically ensure you download everything that has 2004 in the title and just install it as normal, you don't need to move anything then.
Hope that helps.

**Comment by SeriousBuggie** [comment]
That about UT99. And that likely not unpacked Entry map.
We add fix in 469e, so game will search for uz file and unpack all of them instead of crash. Crash happen only if uz not found or failed to unpack.

Likely that completely resolve that issue.

Also AFAIK we update MacOS install instructions, which too must prevent this issue.
