### ISSUE TITLE
[469d] Allow Undo after map Rebuild

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1506]
When you Rebuild a map in Ued, you can no longer Undo. This happens when you Build Geometry, Build Lighting, Build Paths and Build All.

## Reproduce steps:
1. Open any map in Ued like DM-Deck16][
2. Delete any actor in the map, like a weapon.
3. Press "Build Geometry" button.
4. Try Undo to restore the deleted actor.

## Expected result:
Actor is restored using Undo.

## Actual result:
Undo does not work after "Build Geometry".

**Comment by SeriousBuggie** [comment]
Unfortunately there can't be changed hanged anything. Rebuild is complicated thing, which can involve a lot changes. You can't undo one action on top of it. It need undo whole rebuild, which not what you want and great waste of the memory.

Rebuild can change a lot of things, so this goes be unsafe keep old undo history on it.

For example rebuild change region of actors. Change zone of actors Which mean it change actors byte data.

**Comment by SeriousBarbie** [comment]
Maybe disable the menu item when "Undo" is not available.

**Comment by SeriousBuggie** [comment]
Menu items will be disabled indeed. But about OP idea - we can't do that. Closed.
