### ISSUE TITLE
[469a] Can't join some maps

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#151]
The server (SOP) just switched to [AMLP]Bordeaux.  I just get the normal connecting screen, but it never connects and UT locks up.  Have to kill it from task manager to get out of UT.
I switched to my backup V436 version and joined immediately.

This does happen on other maps occasionally

win 10 Pro
V469a
D3D9 @ 3440 X 1440
Cluster 3d audio

**Comment by Chamberly** [comment]
I had one similar issue like that when I played on WildCard's server, it was the end of game frame and someone love to spam the firework gun and then my UT froze. Can't open up the task or anything but did manage to kill it. I have a huge large log file for that too. http://chamberly.dlfast.de/Files/UnrealTournamentWildCardGauntletCrash.log

**Comment by OMA-Bite-Me** [comment]
Is there a UT log that I can post when I have an issue?  If so, let me know where it is and I will add that in future..

**Comment by OjitroC** [comment]
In 469b, with D3D9 renderer, DM-[AMLP]Bordeaux crashes off-line with the following in the log :

Critical: FLightManager::FinishSurf
Critical: URender::DrawFrame
Critical: URender::DrawWorld
Critical: UGameEngine::Draw
Critical: UWindowsViewport::Repaint
Critical: UWindowsClient::Tick
Critical: ClientTick
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Exit: UGalaxyAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: UD3D9RenderDevice::ShutdownAfterError
Exit: Exiting.

The map can be downloaded here : https://unrealarchive.org/maps/unreal-tournament/deathmatch/A/dm-amlpbordeaux_1e962b69.html

I don't recall any problems with this map in 436/451.

**Comment by OjitroC** [comment]
It also crashes off-line with 469b/OpenGL - the same error lines in the log.

As I say works OK off-line with 436, didn't try 451 but pretty sure it runs OK with that version as well.

**Comment by Chamberly** [comment]
> Is there a UT log that I can post when I have an issue? If so, let me know where it is and I will add that in future..

Yes, once your game has crashed don't start it up but go to your UT folder, under System, and it should be in UnrealTournament.log by default unless you use a different startup batch or a shortcut that use a different log file name.

**Comment by stijn-volckaert** [comment]
This is another one of those maps that should never have worked, but somehow did work by accident. It triggered a serious bug in the v436 code. It will be fixed in the next v469b snapshot.
