### ISSUE TITLE
[469b-Preview-20201103] UEd 2.2 Edit Script Window - text not visible

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#152]
The issue - text added/inserted by me in the window is almost invisible and there is no formatting.

I create a new subclass of an Actor - say the UT minigun - the Edit Script window opens and I paste in some code in plain text and formatted, copied from a text (.txt) file.

The inserted text is shown in the window in black and so essentially invisible against the blue background. 

If the compile operation is successful then the text may (only 'may', it doesn't happpen always) appear in white but there is no formatting - the text is on a single line. If I export the changed script to a .uc file then the text in that is all on a single line.

I run UT in a Wineskin wrapper on an iMac which seems to have a Windows version that equates to XP - as far as I can tell the renderer for the Edit Script window is D3D9.

As an aside, it would help if, when there is an error in compliation, the line where the error occurs is actually highlighted, otherwise it is difficult if not impossible (for me) to work out where it is.  I don't use the Edit Script for inserting large chunks of code but for the odd 10/20 lines.

**Comment by SeriousBuggie** [comment]
After add double click on current script on left list. This reformat and recolor script text.

**Comment by OjitroC** [comment]
Oh - I didn't know that.  Tried it and it does change the colour.

HOWEVER it doesn't (for me anyway) change the format.  So the added code text is all on one line and if it starts with a // comment, then all the text is in green.

Do the same thing in UEd 2.1 and the text is inserted in the correct format - double clicking on the name in the list on the left changes the colour of the text from dark black to white.

For me then the formatting that happens in UEd 2.1 doesn't happen in UEd 2.2.

**Comment by SeriousBuggie** [comment]
> Could you try this again with 469c RC2? We switched to a new rich text editor backend

**Comment by OjitroC** [comment]
Works fine now in 469c Release.
