### ISSUE TITLE
[469d] Textures flickering on XOpenGL

### ISSUE THREAD

**Issue by CortexReaver** [OldUnreal/UnrealTournamentPatches#1521]
Weapon textures flickering, other models seems fine. A video example: https://youtu.be/V81O9Mlbal8 It seems like it is trying to change on other texture but very vast and then switching back.
GPU: RX 6600
OS: Windows 22H2
GPU Driver: v24.1.1 previous drivers has other bugs with dark flickering of bsp geometry. I don't remember how I fixed it. Probably with some options tweaking.

**Comment by CortexReaver** [comment]
Looks like I was wrong, textures are flickering everywhere, not only on 3d meshes: https://youtu.be/4mmqURdAa-w

**Comment by CortexReaver** [comment]
I think I've found the problem: it's the "Shader Draw Parameters". But after disabling it you need to restart the entire game to get the flickering gone.

**Comment by stijn-volckaert** [comment]
This is not the first time this option causes trouble for AMD users. We're going to disable it in the next preview build.
