### ISSUE TITLE
[469b-Preview-20201103] Shieldbelt display bug

### ISSUE THREAD

**Issue by deltabatonix** [OldUnreal/UnrealTournamentPatches#153]
**Clips below:** 

https://clips.twitch.tv/RespectfulMistyLEDDeIlluminati (469b server - 469a client)

https://clips.twitch.tv/NurturingCrepuscularCakeDoggo (469b server - 469a client)

https://www.twitch.tv/deltabatonix/clip/CogentPleasantWatercressPlanking (469 server - 469 client - not too sure on build, recorded 3-4 months ago)

I have never seen this on 436/451 version. 

This bug is present on all 469 builds.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
