### ISSUE TITLE
[469e] macOS Crash on Game Start Due to Faulty FullscreenViewportX

### ISSUE THREAD

**Issue by rxut** [OldUnreal/UnrealTournamentPatches#1531]
This bug occurs when you're in the game (fullscreen) and accidentally bring up another window. For example, If you press a Media or Search key on the Apple keyboard (e.g., Dictation or Search).

When you do that, the game minimizes, and you can't bring it up. A faulty resolution gets stored for **FullscreenViewportX** inside the **[SDLDrv.SDLClient]** in the UnrealTournament.ini file.
```
[SDLDrv.SDLClient]
WindowedViewportX=1728
WindowedViewportY=961
WindowedColorBits=32
FullscreenViewportX=100000
FullscreenViewportY=961
FullscreenColorBits=32
``` 
Next time you try to boot the game, you get this error:
<img width="320" alt="image" src="https://github.com/OldUnreal/UnrealTournamentPatches/assets/126023192/62654c0d-e01a-454c-b8b3-f5026d241d81">

To fix the error, one has to edit the UnrealTournament.ini manually and set **FullscreenViewportX** to a supported resolution.

Then the game will start again.

This bug was found and replicated using MacOS Sonoma 14.3.1 on a Macbook Pro M1.

**Comment by stijn-volckaert** [comment]
Confirmed. This will be fixed in the next 469e preview
