### ISSUE TITLE
[469d] Hidden brushes can still be selected with SHIFT+LMB

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1533]
When you hide brushes using "Hide Selected Actors" (ACTOR HIDE SELECTED) they can still be selected in the 3D viewport when using SHIFT+LMB. This is quite dangerous, because the selection itself is also not visible and the selected brushes can be accidentally deleted or moved without knowing.

Reproduce steps:
1. Open Ued and load any map, such as like DM-Deck16][
2. CTRL+A to select everything in the map
3. Apply "Hide Selected Actors" so all of the actors become hidden, including brushes.
4. In the 3D viewport find a surface and click on it using SHIFT+LMB.
5. Press Delete and Rebuild the map.

Expected result: Nothing is selected and the brush should not be deleted.

Actual result: The hidden brush was selected without any visual feedback and it was also deleted.

**Comment by SeriousBuggie** [comment]
CTRL+ALT+LMB?
Did you mean SHIFT+LMB?
Because for me CTRL+ALT+LMB not select anything, only ruin texture.

**Comment by BerserkerBG** [comment]
> CTRL+ALT+LMB? Did you mean SHIFT+LMB? Because for me CTRL+ALT+LMB not select anything, only ruin texture.

Yes, will update.
