### ISSUE TITLE
[469b-Preview-20201103] Armor/Shieldbelt/Thigh Pads 

### ISSUE THREAD

**Issue by deltabatonix** [OldUnreal/UnrealTournamentPatches#154]
I have noticed that armor/shieldbelt/thigh health (HUD - top right corner) is always displayed as 0 while spectating the game while health info is being constantly updated.

**Comment by SeriousBuggie** [comment]
Code for output this stuff:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ChallengeHUD.uc#L431
```
			ArmorAmount += Inv.Charge;
```
As listed at 
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ChallengeHUD.uc#L49
```
var Pawn PawnOwner;	// pawn currently managing this HUD (may be the viewtarget of the owner rather than the owner)
```
it can be not player self, but any person which he is spectate.
So problem about replicate Inventory.Charge field.
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Inventory.uc#L114
```
replication
{
	// Things the server should send to the client.
	reliable if( Role==ROLE_Authority && bNetOwner )
		bIsAnArmor, Charge, bActivatable, bActive, PlayerViewOffset, PlayerViewMesh, PlayerViewScale;
	unreliable if( Role==ROLE_Authority )
		FlashCount, bSteadyFlash3rd, ThirdPersonMesh, ThirdPersonScale;
}
```
Server send this stuff only if bNetOwner set to true.
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Actor.uc#L406
```
var const bool bNetOwner;         // Player owns this actor.
```
Obviously Spectator not owns Inventory of ViewTarget, so server not send to him this info.

Main consequences:
- even if fix will be applied, only new server allow that;
- for fix need change replication rules.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2

**Comment by W4yland3r** [comment]
Thank you! :)
