### ISSUE TITLE
[469d] Vertex Editing bug is destroying brushes

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1540]
Sometimes when you zoom out and zoom in while vertex editing, brushes will get completely destroyed.

![Screenshot_144](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/c829a4bb-6a8c-4400-a218-ac8a902c387e)

Reproduce steps:
1. Open VertexEditBug.unr in Ued. [VertexEditBug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/14422881/VertexEditBug.zip)
2. Make sure the 2 beam brushes are selected.
3. Go to the Top viewport and zoom out quite a bit.
4. Select the top part of the beams with the vertex edit tool.
5. Now, with the top vertices still selected, try to zoom all the way in (Top viewport)
6. Move the selected vertices.

Expected result: Vertices are moved without issues.

Actual result: Brushes are completely destroyed.

Video:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/23b4407d-f5b9-4fb1-b363-4003dbf1395a

**Comment by SeriousBuggie** [comment]
Not need zoom, just move cam:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/02e5d944-74e9-4f3e-be42-bb31ee818b51
