### ISSUE TITLE
[469d] Show All Actors should ignore actors that are Hidden in Group Browser

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1544]
![m7in568](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/8865a18e-fd5e-42d9-b93a-2d77b258dd4d)

If you have actors that are hidden in the Group Browser, once you press the "Show All Actors" button, it will reveal every single actor, including the hidden actors in the Group Browser. The eyeball icon in the Group Browser is also not updated when you "Show All Actors".

Suggestion:
Add an alternative flag setting which will make  "Show All Actors" ignore actors that are Hidden in Group Browser.

**Comment by SeriousBuggie** [comment]
I will rephrase your statement. 

Add an alternative flag setting which will make "Show All Actors" ignore actors which belong to any hidden group in Group Browser.
This mean if actor is part of any hidden group it will be ignored. Not matter if it participate in show group or no.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1713122152](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/2a3b8f6b-8c60-4627-ac7b-e05953a460e4)
![scr_1713122188](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/9c09f7fb-71f7-4a00-98a4-e0c36a28612f)
