### ISSUE TITLE
Game won't start after Sonoma 14.4 update

### ISSUE THREAD

**Issue by jozerozman** [OldUnreal/UnrealTournamentPatches#1549]
After updating to Mac OS  Sonoma 14.4 I've noticed the game won't start. I run it, the ut game icon briefly shows in the dock and then closes with no error.

**Comment by SeriousBuggie** [comment]
You need reapply patch 469d. Recently there be update for MacOS binaries.

**Comment by jozerozman** [comment]
Thank you! It's working now after I've reapplied the Sonoma 469d patch!
