### ISSUE TITLE
[469d] 2D editor - Insert New Shape From Surface Polygon

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1550]
2D editor lacks the option to insert objects from surface selection (polygon).  For example, I'd like to insert this surface (which has merged polys) in the 2D editor:
![Screenshot_155](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/16b864e5-76d2-4d6f-b00d-b7f68600fa2b)

The current method is to select the surface and in 2D editor to use Edit=>Insert New Shape=>From Selected Surface (BSP), however this fragments the shape, because of the bsp cuts:
![Screenshot_157](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/050e1fb6-65d6-471e-b593-aba39671e282)

## Suggestion:
Include an additional option, which will insert shape from selected surface polygon.

concept:
![Screenshot_159](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/f29b484a-1561-4187-bb8c-737f1987c45b)

expected result:
![Screenshot_158](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/f3d9a00c-95a1-4a21-8688-f3d1d432d250)

Example map:
[Insert_Shape_Polygon_Surface.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/14606560/Insert_Shape_Polygon_Surface.zip)

**Comment by SeriousBuggie** [comment]
There no such thing in BSP which you ask. What you see as surface polygon it merge of few nodes. Which is not actually merged, but grouped. It act as one piece, but still group of few items. And render as few ngons, not as one.

What you ask is basically merge. I guess it can be implemented as different action. You select few shapes and choose merge, and it merge them if they share at least one edge.

But this thing for sure can produce non-convex shapes. Like in your picture.
Such ngons in general produce broken and glitchy  BSP. Like this one:
https://github.com/OldUnreal/UnrealTournamentPatches/issues/1371

**Comment by BerserkerBG** [comment]
> But this thing for sure can produce non-convex shapes. Like in your picture.
> Such ngons in general produce broken and glitchy BSP. Like this one:

The point is to recover 2D Editor Shapes and work with them. If we do all of the work inside the 2D Editor, then it will not matter at all if the inserted shape is ngon or not, because ngons with non-convex shapes will always get triangulated when we place the actual brush from 2D Editor to Ued.

**Comment by SeriousBuggie** [comment]
Such info not stored in map. All what possible - try merge selected shapes. it can be separate tool.
And this possible must ignore cases, when triangles on merge create shape with hole inside.
