### ISSUE TITLE
[469d] Add Box Selection in 3D viewport for the Vertex Editing tool only

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1552]
Box selection with the Vertex Editing tool allows you to select multiple vertices within the box boundaries. Currently, box selection works only in 2D viewports. An useful idea would be to add Box Selection for the Vertex Editing tool **only** (Camera Movement tool and others should be excluded, because CTRL+ALT shortcuts are already taken for texture alignment).

In case someone doesn't know, you can make box selection by using the shortcut CTRL+ALT and dragging with LMB (Box selection currently works in 2D viewports only).

## Expected result:
Here is a concept GIF, which showcases my suggestion:
![Ued-Box-Select--3D-Viewport](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/09673a39-93cd-45df-860c-c3a3da5db94e)

**Comment by SeriousBuggie** [comment]
There exists conflict - Ctrl+Alt+LMB used for paste copied texture.
So such feature must work only in wireframe mode?

**Comment by BerserkerBG** [comment]
> There exists conflict - Ctrl+Alt+LMB used for paste copied texture. So such feature must work only in wireframe mode?

No, such feature should work only in Vertex Editing mode for every render mode. Texture alignment is for Camera and Texture Pan.
