### ISSUE TITLE
UnFPoly::RemoveColinears performance improvement

### ISSUE THREAD

**Issue by cmbasnett** [OldUnreal/UnrealTournamentPatches#1558]
In `UnFPoly::RemoveColinears`, the code is doing an unnecessary number of plane splitting operations in this section:

```
for( j=0; j<NumVertices; j++ )
{
  if (j != i)
  {
	  switch( SplitWithPlane (Vertex[i],SidePlaneNormal[i],NULL,NULL,0) )
	  {
		  case SP_Front: return 0; // Nonconvex + Numerical precision error
		  case SP_Split: return 0; // Nonconvex
		  // SP_BACK: Means it's convex
		  // SP_COPLANAR: Means it's probably convex (numerical precision)
	  }
  }
}
```

I don't know why it's like this exactly, but to my eye, the loop and index check can be eliminated entirely since the same check is run N-1 times, where N is the number of vertices in the poly. The `j` index is never used for anything.

**Comment by SeriousBuggie** [comment]
This check must be at end in separate loop against i.
