### ISSUE TITLE
[469d] OBJ Brush Export triangulates every brush surface

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1561]
## Reproduce steps:
1. Open Ued
2. Click on the Cube Brush
3. Select the Red Cube Brush
4. Brush -> Export -> Save as type: OBJ -> Ok
5. Brush -> Import -> Find and select the Brush we just exported -> Ok -> Ok

## Expected Result:
![Before1](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/fc37af17-f743-4bb6-99d4-945b4f8900ed)

## Actual Result:
![After](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/4d694a5b-5bba-47fc-85e7-c1c76b79f72d)

**Comment by SeriousBuggie** [comment]
Yes, exporter work in that way. :D 

I guess it can be fixed too.
