### ISSUE TITLE
[469b-Preview-20201103] UEd 2.2 Mesh Browser window

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#157]
Issue - with most (or all) of the Browser windows docked, viewing a mesh and then switching to another browser results in the mesh viewer/window (not the whole of the Mesh Browser) obscuring or being superimposed over the other browser.

To reproduce:
1 Dock all the Browsers (I have all except the Group Browser docked)
2 Go to the Mesh Browser and select a mesh with a lot of animations - say FCommando
3 Run the animations (click on the Play Animation button)
4 Then switch to another Browser, say the Actor Browser
5 The mesh viewer (the lower part of the Mesh Browser showing the mesh and animations) will still be visible, superimposed over the lower part of the Actor Browser.
6 Go back to the Mesh Browser and stop the animations playing - go back to the other browsers and the mesh view still obscures the lower part of the other Browsers.

This happens with any renderer - changing from the renderer of the Mesh Browser from Software to D3D to OpenGL to D3D9 makes no difference to this behaviour.

I have a screenshot showing the mesh view obscuring the Actor Browser but can't upload it - I don't think it adds much, if anything, to the description of the issue.

For me the issue also happens in 436 from time to time.

I have issues with the Texture Browser window as well but those are more complex and it is more difficult to determine a pattern to the 'odd' behaviour.

**Comment by stijn-volckaert** [comment]
Does this still happen with 469c and new versions of Wine?
