### ISSUE TITLE
[469d] Texture Browser can't delete unused textures

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1576]
Texture Browser is unable to delete unused textures in a map. When you remove brushes that use a specific texture, you will be unable to delete the texture from the Texture Browser:

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/5480c0b7-5914-41ec-966d-143ae8d1909b)
![Screenshot_233](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/bdc45b8e-f7e9-4e04-858c-bae55a5e27e1)

## Reproduce steps:
1. Open DeleteTexture.unr in Ued [DeleteTexture.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/15298600/DeleteTexture.zip)
2. Delete the brush cube with the brown grid texture.
3. Rebuild map.
4. Open the Texture Browser and select the texture called TextureGrid_Brown inside MyLevel package.
5. Right click and delete.

## Result:
Can't delete this texture from the texture browser
![Screenshot_232](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/7f6cecbe-0aed-44c2-8cd5-fc160fad0622)

## Current workaround:
After deleting the brush I have to save the map and close Ued, then reopen Ued and load the map again.

**Comment by SeriousBuggie** [comment]
You can type `OBJ GARBAGE` in console of editor, and after delete texture without restart editor if it not used anymore.
