### ISSUE TITLE
[macOS] Unable to start a multiplayer game due to de.u missing from the System folder

### ISSUE THREAD

**Issue by Jeffersonian** [OldUnreal/UnrealTournamentPatches#1578]
Using the following build:
[OldUnreal-UTPatch469d-macOS-Sonoma.dmg](https://github.com/OldUnreal/UnrealTournamentPatches/releases/download/v469d/OldUnreal-UTPatch469d-macOS-Sonoma.dmg)

When starting a multiplayer game, it crashes:

Failed to load De: Can't find file De..

History: UObject::SafeLoadError <- UObject::GetPackageLinker <- UGameEngine::BuildServerMasterMap <- ULevel::Listen <- Listen <- UGameEngine::LoadMap <- LocalMapURL <- UGameEngine::Browse <- ClientTravel <- UGameEngine::Tick <- UpdateWorld <- MainLoopIteration <- MainLoop <- main

Copying de.u (from a previous release, like OldUnreal-UTPatch469c) to the following path fixes it:

UnrealTournament.app/Contents/MacOS/System/de.u

**Comment by SeriousBuggie** [comment]
You can just remove line `ServerPackages=De` from your `UnrealTournament.ini`.

**Comment by Jeffersonian** [comment]
Thanks, that is a much better workaround.

**Comment by davestephens** [comment]
Same happens on the Linux amd64 version; the same fix of updating `UnrealTournament.ini` works, too.

UnrealTournament.ini lives in `$HOME/.utpg/System/`, to save you hunting around for it like I did.

**Comment by SeriousBuggie** [comment]
We sill include de.u into 469e release and remove line 
`ServerPackages=De`
from `Default.ini`

**Comment by dwt** [comment]
@SeriousBuggie Hey there, I'm working on the packaging of old unreal on nixos and nix-darwin.

For that I tried patching unreal tournament there, to fix this bug until you release the next major version.

However, I couldn't find the location where I can directly link to that file? Could you help me where the repo is where you manage the development of UT and where I can find and link to that file (or better yet to the commit that introduces it)?
