### ISSUE TITLE
What happened to CameraPoint?

### ISSUE THREAD

**Issue by VeganGreasel** [OldUnreal/UnrealTournamentPatches#1579]
I've been using UnrealEd 2.2 to mod DeusEx, and it works great, but the CameraPoint actor is missing. It was still present in UnrealEd 2.0, but in 2.2, it's gone, and any map containing one cannot be opened.

**Comment by SeriousBuggie** [comment]
Not sure what you talking about. In what package be such actor and what it do? First time hear about such.

**Comment by VeganGreasel** [comment]
I just realised this is Deus Ex specific. My bad.
