### ISSUE TITLE
[469b-Preview-20201103] UEd 2.2 Browser windows

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#158]
Issue - with the Browsers docked (Texture, Actors, Sounds, Music, Meshes), the Browsers only display properly with the renderer for the Texture and Mesh Browsers set to Software.

If I set the renderer for the Texture Browser to D3D9 to view HD textures, for example, and then switch to the Actor Browser, the Textures are superimposed over part of the Actor Browser.  

Similarly if I start with the Mesh Browser and change the renderer for that to D3D9 and then switch to another Browser, the mesh viewer is superimposed over part of that Browser.  I can even get the situation where part of the Texture Browser window and the mesh viewer are both superimposed over, say, the Actor Browser. 

In essence I can only use anything other than the Software renderer with the Texture and Mesh Browsers undocked.

**Comment by Chamberly** [comment]
Can you try it with any other render other than software?

**Comment by OjitroC** [comment]
The short answer is no.

With all the Browsers docked (in the order as in the first post) then, if the renderer for the Texture Browser is OpenGL, D3D9 or  D3D (the only ones I can use with my system), when I switch from the Texture Browser to one of the other Browsers (normally the Actor Browser) the textures in the TB window are partly superimposed over the other browser (and indeed over all the other docked browsers making them unusable basically).  The same thing happens with the Mesh Browser.

Only with the renderer set to Software for the Texture and Mesh Browsers do I not get this superimposition on the other Browsers.

There are no problems with superimposition with the TB and MB undocked (this is what I now do but I presume it is not supposed to be like that, otherwise why the ability to dock all the browsers?). 

I have noticed in UEd 2 in 436 the mesh viewer part of the Mesh Browser will be superimposed on the the other browsers if the animation of a mesh is playing and not stopped before switching to another browser.

**Comment by OjitroC** [comment]
The other thing that happens sometimes is that, opening UEd with the browsers docked and the Texture Browser using D3D9, the Texture Browser doesn't display any textures - normally some AmmoCount textures from Botpack are shown on opening the Editor with the TB open but starting with D3D9 they are not displayed.

**Comment by stijn-volckaert** [comment]
Does this still happen with 469c and new versions of Wine?
