### ISSUE TITLE
[469e] "Accessed None" issue in function 'Botpack.TournamentPlayer.EncroachingOn()'

### ISSUE THREAD

**Issue by an-eternity** [OldUnreal/UnrealTournamentPatches#1580]
In some cases function `TournamentPlayer.EncroachingOn()` gets called at the client side very soon after player login, when `GameReplicationInfo` does not yet exist at the client side.

In such cases script warnings appear:
`ScriptLog: Team 0`
`ScriptLog: Login: Test`
`ScriptWarning: TFemale1 Entry.TFemale1 (Function Botpack.TournamentPlayer.EncroachingOn:000C) Accessed None 'GameReplicationInfo'`

This function has to be redesigned...
First of all - check `GameReplicationInfo` for None.
Second - think, if it is really necessary to access GameReplicationInfo within that function client side in order to return the correct value.

**Comment by SeriousBarbie** [comment]
Where is that function called? I didn't find any call in the script sources.

**Comment by an-eternity** [comment]
I suspect it is called when just spawned pawn encroaches something in the level immediately, so that, apparently, engine calls this function in that case (because it is an event).

Issue occurs rarely and randomly, and always right after login. I don't have a test case for stable reproduce yet.

**Comment by SeriousBuggie** [comment]
Engine call it.
