### ISSUE TITLE
[469d] Advanced Video Properties have small boxes

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1585]
Advanced video properties have really small boxes:
![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/7bd01e38-7d50-4ca8-9fb5-69e609222bea)

When I highlight a box and put a number, it goes invisible because it clips on the left side
![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/425b1971-c8dc-404e-a7d8-b016cfec090f)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/631afc58-97c2-431b-831c-50ccd8898642)

**Comment by BerserkerBG** [comment]
> Possible implementation: ![img](https://private-user-images.githubusercontent.com/70026933/337829991-631afc58-97c2-431b-831c-50ccd8898642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDgyODQsIm5iZiI6MTcxNzk0Nzk4NCwicGF0aCI6Ii83MDAyNjkzMy8zMzc4Mjk5OTEtNjMxYWZjNTgtOTdjMi00MzFiLTgzMWMtNTBjY2Q4ODk4NjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDE1NDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlNGU1NTQzN2JkNDA0YTUwYTlkYWY4OGQ5NDliYjcwY2NmNTg1MzAwMjg2YzI4YTMxOGQ0NzI2NDY4NTUxMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fvCjBKihMIqpPvv2Yk6_NtfmtmRKTIsDbtbhp0HtcQg)

Yes, This is perfect! But It should be 0.00 because some options are more sensitive.
For example - sometimes I use 0.05 for Gamma offset Blue and 0.03 for Gamma offset Red to make some nice color correction.

**Comment by SeriousBuggie** [comment]
It strip all ending zeroes. Except one before dot. so your 0.05 will be 0.05. But 0.050000, turn to 0.05.
OFC it not touch numbers without dot.
