### ISSUE TITLE
[469d] Ued - Add new shortcut CTRL+SHIFT+Z for "Redo"

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1586]
The keyboard shortcut CTRL+SHIFT+Z is commonly used as the "Redo" command, which is an alternative to the CTRL+Y command for "Redo". This shortcut has become a standard in many software applications over the years, like in browsers, text editors, graphic design programs, etc. Every major software I know has it.

Ued still uses CTRL+Y, which is very outdated. It is quite annoying to stretch your fingers when you are trying to "Redo" with CTRL+Y. CTRL+SHIFT+Z can be a great addition to the Ued workflow.

## Suggestion:
Add new shortcut CTRL+SHIFT+Z for "Redo"

**Comment by SeriousBuggie** [comment]
It depends. Some soft use one scaheme, some another. However, we can use both, since, it not used for anything else.

I personally prefer Ctrl+Y and modern IDE usually use this way IIRC.

**Comment by SeriousBarbie** [comment]
A keymapper table Like _Preferences>Raw Key Bindings_ would satisfy this wish. In my case defining that in an INI file (without GUI) would be enough.

**Comment by SeriousBuggie** [comment]
Key mapper map single key. But you can do it now. Use command `TRANSACTION REDO` for any key what you like. Not all of it work in editor, but most work.
