### ISSUE TITLE
[469a] ut-bin crashed immediately

### ISSUE THREAD

**Issue by mmawhin** [OldUnreal/UnrealTournamentPatches#159]
OS: OpenSuse Tumbleweed
Shell: Bash and Zsh
Kernel: 5.9.1
Glibc: 2.32

When starting ut-bin i get following error:
Could not initialize iconvWARNING: preference directory not accessible: ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????/.utpg/System/
WARNING: Not using preference directory

?: appInit <- main

If set the homedirectory i get the following error:
melke@G5-lx:~> mkdir -p ~/.utpg/System
melke@G5-lx:~/Games/UT99/System> ./ut-bin -sethomedir=/home/melke/.utpg/System
Could not initialize iconvWARNING: preference directory not accessible: /home/melke/.utpg/System
WARNING: Not using preference directory
?

?????: appInit <- main

**Comment by senneschall** [comment]
I've seen this problem before when building a snap out of the game. It was a problem with the i386 version of libc-bin.

The game can't work with iconv, the rest are just the problems that result out of that. If you manage to find the created log file, you'll see find a rarely used encoding. For me it was UTF-32 for whatever reason. I was able to fix it with a clean install of libc:i386.

**Comment by stijn-volckaert** [comment]
I've modified the code so the game will just exit immediately if iconv doesn't initialize correctly. Without iconv, we cannot even send strings across the network, so there really is no point in even trying to boot the game. FYI: we need an iconv that supports the following conversions:

* WCHAR_T <=> WINDOWS-1252
* UTF-16LE <=> WINDOWS-1252
* WCHAR_T <=> UTF-16LE
* UTF-8 <=> WCHAR_T

**Comment by mmawhin** [comment]
Hi,

Thanks for your answers. I checked what was installed and glibc was installed correctly. I managed to solve the issue by installing these packages:
- glibc-locale-base-32bit
- glibc-devel-32bit

Thanks a lot for pointing me in the right direction
