### ISSUE TITLE
Monster stack

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1591]
I remember there was a fix for stacked monster in one of the latest patches, but could not find it. Problem: two Mantas are stacked and do not move: 
![SteckedNPCs](https://github.com/OldUnreal/UnrealTournamentPatches/assets/81397053/e12e7925-b516-4e78-a6ab-690837b95244)
Server is running 469d/linux.

**Comment by SeriousBuggie** [comment]
Duplicate of #652
