### ISSUE TITLE
[469d] Server Query String Conversion Issues

### ISSUE THREAD

**Issue by vanitysan** [OldUnreal/UnrealTournamentPatches#1593]
Dear Community,

Is there a Problem with the latest Windows Server 2022? If iam using special Characters (for example using ''§'' in the Server Name or Admin Name)  in the UT.ini or in any ini's for Mods, if the Text is visible on the UT Server i get weird Characters shown... i only know this behaviour from Linux Servers, and there was a patch (LinuxCharsetFix) for that. I havent had this issue on Windows before.

Setup: Windows Server 2022 Standard 21H2
CPU: Intel Core i9-14900k
UT: v469d Clean Installed

I first thought the Problem must be the new UT Patches, but i tried v436 and v469d (as Client and Server) and the Problem occurs on both, so it must be Windows Server which is handling some encoding false i guess?
Can anybody help out with this, or reproduce the Problem?

Kind Regards
HanNibaL / Philipp
![20240701_221035](https://github.com/OldUnreal/UnrealTournamentPatches/assets/154472754/8374d2b6-d9e8-4adb-a595-67c5a24781ac)
![20240701_221047](https://github.com/OldUnreal/UnrealTournamentPatches/assets/154472754/5c7b076d-aadb-4224-b0d9-ef824820ac3d)

**Comment by vanitysan** [comment]
Update: So what i found out is that all newer Windows Versions (Windows 11, Windows Server 2022) don't use UTF -8 as Default Codepage. That is whats casuing these Problems. However so i did change it on my Server aswell as an my Client to run UTF-8 Codepage... but the issue still persists. The only thing that showing now correctly is that .htm Server Info in the MapVote. The Server Browser still has these issues, also a mod called 1337-o-mat (where u can change you Playername to Special Chars) is also not working properly. So if i might suggest, is it possible to build in a workaround within the Game Engine for newer OS's? It seems like Microsoft is switching their Codepage around with every new OS Release. (BTW i dont know if only OS in Europe Region behave like this)

Kind Regards
Philipp

**Comment by stijn-volckaert** [comment]
Could you try saving your server ini file (and all other files that trigger encoding issues) as UTF-8 with BOM?

**Comment by vanitysan** [comment]
Thanks for the reply @stijn-volckaert, i did as you mentioned on both client and server (converted the .ini's and the server batch file to UTF-8 BOM with Notepad++) But didnt do anything. Maybe the UTF-8 Encoding is not working properly on Windows because its still in beta?
![NPP](https://github.com/OldUnreal/UnrealTournamentPatches/assets/154472754/195724f4-d94e-4351-8a91-0a1dfce135de)
![OS Settings](https://github.com/OldUnreal/UnrealTournamentPatches/assets/154472754/45c40467-8c36-4cac-88a8-310e53a83881)

**Comment by vanitysan** [comment]
So i got a little more information if that helps.

For All newer OS's (Windows10,11 ; Server 2019, Server 2022) -> OEM Codepage: 850, ACP: 1252 - Windows  West Europen ANSI Latein 1;


After i enabled the Beta Unicode UTF 8, i had following settings on my Windows Server:
OEM Codepage: 65001 ACP: 65001 Unicode (UTF-8)    ->But keep in mind this only solved the Problem within the MapVote .htm, The Server Browser still had the displaying issue

**Comment by vanitysan** [comment]
Update: 
The Problem lies within the OldUnreals Patch. I set up a new Machine with Windows XP SP3, Clean UT 432  Install, Added Patch 436 -> Dedicated the Server with Special Chars -> Viewing on my v469 in Windows 11; **Displaying correctly!!!**
After that added the Old Unreal Patch 469d to my XP Setup -> Dedicated the Server with Special Chars -> Viewing again on my v469 in Windows 11; **Displaying incorrectly**.  
![20240703_053357](https://github.com/OldUnreal/UnrealTournamentPatches/assets/154472754/8cbab7ba-3c83-4612-b81a-6a02630d4c9f)

I Also did the same as mentioned above just on my Windows Server 2022. Same as above.
**I Think i found the answer tho. v436 leaves the .inis as ANSI while v496b is in UTF-8 BOM that is the issue!**
![20240703_062030](https://github.com/OldUnreal/UnrealTournamentPatches/assets/154472754/3ec4727a-3db6-4f52-a046-c7ea89cb4511)

**Comment by vanitysan** [comment]
Hey Ya AnthraX, Thanks for the effort in looking up this issue!!!

Sure i'll hit you up at Discord as soon as i can, gotta fix my Server first... it died due to windows update....:(

*Issue with Mapvote can maybe be fixed by me with doing metacharset in the header... ill try as soon as the server is running again :O

Kind Regards 
Philipp

**Comment by vanitysan** [comment]
Update: The Mapvote Issue seems to be resolve for me. I converted the .htm into ANSI instead of UTF-8. This has done the trick.... i can't tell tho if its the its meant to be or if there is something just not working right within the UT Engine  ;)

Kind Regards
HanNibaL / Philipp

**Comment by stijn-volckaert** [comment]
I've pushed a fix that will be included in the next 469e preview
