### ISSUE TITLE
[469d] Graphical Glitches with XOpenGL Driver

### ISSUE THREAD

**Issue by bnied** [OldUnreal/UnrealTournamentPatches#1599]
I upgraded my 469c installation to 469d this morning, and the new patch introduced a ton of texturing issues on my setup.

Video: https://www.youtube.com/watch?v=ukBXuTdJMys

OS: Windows 11 x64, Version 23H2, OS build 22631.3958

GPU: AMD Radeon RX 7900 XTX, 24 GiB VRAM

Driver: 24.10.29.01-240714a-405203C-AMD-Software-Adrenalin-Edition / 32.0.11029.1008

UT: Unreal Tournament GOTY 469d, no extra mods installed.

**Comment by SeriousBuggie** [comment]
Please ensure in your UnrealTournament.ini in section 
`[XOpenGLDrv.XOpenGLRenderDevice]`
next values set to this values:
```ini
UseBindlessTextures=False
UseShaderDrawParameters=False
UsePersistentBuffers=False
```

**Comment by bnied** [comment]
That looks to have fixed the issue. Thanks!
