### ISSUE TITLE
[469b-Preview-20201103] - UnrealEd using outdated driver

### ISSUE THREAD

**Issue by Chamberly** [OldUnreal/UnrealTournamentPatches#160]
![image](https://user-images.githubusercontent.com/11419314/98561974-7f78ae00-2277-11eb-95bf-9aac24e0a5ea.png)
I got v469b from the old unreal forum. Tried to launch unrealed to test something and this shows up.
However unrealed still do launch and I could continue but I don't know how far it'll go.

**Comment by Snuggx** [comment]
Just delete this DLL.
Worked for me.

**Comment by Dr-Flay** [comment]
This renderer is for PowerVR cards so may rely on talking to libraries you don't have installed.

**Comment by CacoFFF** [comment]
The current behaviour of the editor is test the render device once and after it fails loading it won't ask a second time.
This render device should not work at all on any modern system unless there's a PowerVR wrapper/emulator, but the reason it's really failing to load in this case is a missing import from Core.dll which could be reimplemented in case someone actually wants to try said render device.

**Comment by stijn-volckaert** [comment]
The first time you launch UnrealEd after installing the 469 patch, it will enumerate all available renderdevices and try to load them one by one to see which ones can be used in the viewport windows. If a renderdevice seems usable, it will be added to the viewport dropdown list. If a renderdevice fails to load, UnrealEd will mark it as incompatible in Editor.ini. 

The problem with this approach is that if a renderdevice causes a crash during this initial test, UnrealEd will not be able to write the compatibility info into Editor.ini so the crash will happen again the next time you launch UnrealEd. We are changing how this works in 469c. When we test a renderdevice, we mark it as incompatible _before_ the test. If the renderer passes the test, we will update its compatibility entry in Editor.ini. This way, the renderer can still cause a crash once, but it will not be tested again in subsequent runs of UEd.

**Comment by NeonKnightOA** [comment]
> 
> 
> This renderer is for PowerVR cards so may rely on talking to libraries you don't have installed.
> 
> The startup.int does not have info for all the renderers. This should be more complete as the Linux versions won't have any info either.

Which renderers are missing? You should tag me whenever any change on the .int files is required.

**Comment by stijn-volckaert** [comment]
Issue mitigated in 469c-RC2. Every renderer will only be tried once. If the renderer crashes, UEd won't try to initialize it again in subsequent launches
