### ISSUE TITLE
[469d] Actor Browser: Allow more formats for "Load file into package"

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1602]
Load file into package is a Ued feature for the Actor browser, it allows you to load files into a chosen package. You need to open the Actor browser and enable View -> Show Packages in order to use it.

![Screenshot_285](https://github.com/user-attachments/assets/8e0c9d3f-4bef-4c90-b31d-c2d511d96a52) ![Screenshot_286](https://github.com/user-attachments/assets/8c12913d-5c6c-471d-9741-5a05b7d8e321)

The current load format for this feature is *.u packages only. It would be nice if it could also import other formats, such as - *.utx *.umx and *.uax

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://github.com/user-attachments/assets/c5103aee-863f-4e5a-8467-c9393d2bfe26)
