### ISSUE TITLE
[469a] Segfault with Wayland enabled in SDL2

### ISSUE THREAD

**Issue by TheComputerGuy96** [OldUnreal/UnrealTournamentPatches#161]
OS: Arch Linux
Shell: bash
Kernel: 5.9.2
glibc: 2.32
DE: GNOME 3.38.1
Mesa: 20.2.1

When I run the game with Wayland enabled (by renaming built-in SDL2 libraries, installing the ones from my package manager and using the SDL_VIDEODRIVER=wayland environment variable), I get this crash:
```
Developer Backtrace:
[ 1]  Core.so(_Z12HandleSignali+0x208) [0xf795cd08]
[ 2]  linux-gate.so.1(__kernel_sigreturn+0) [0xf7ef6560]
[ 3]  SDLDrv.so(_ZN12USDLViewport14ResizeViewportEjiii+0x19d) [0xf6c4d42d]
[ 4]  SDLDrv.so(_ZN12USDLViewport11UpdateInputEi+0x7da) [0xf6c4c85a]
[ 5]  Engine.so(_ZN6UInput10ResetInputEv+0x297) [0xf7c4bde7]
[ 6]  Engine.so(_ZN6UInput4InitEP9UViewport+0x52) [0xf7c4aa62]
[ 7]  Engine.so(_ZN11UGameEngine4InitEv+0x711) [0xf7c392a1]
[ 8]  ./ut-bin(main+0xb06) [0x804e656]
[ 9]  /usr/lib32/libc.so.6(__libc_start_main+0x10e) [0xf724d08e]
[10]  ./ut-bin() [0x804d8bf]
Signal: SIGSEGV [segmentation fault]
Aborting.

Signal: SIGSEGV [segmentation fault]

History: USDLViewport::ResizeViewport <- USDLViewport::UpdateInput <- UInput::ResetInput <- UInput::Init <- UGameEngine::Init <- InitEngine <- main

Exiting due to error
```

Running the game with SDL_VIDEODRIVER=x11 variable makes the game work

**Comment by stijn-volckaert** [comment]
Does this still happen with 469b and with the current version of Arch/SDL? If so, would you mind coming over to the OldUnreal Discord so we can make sure this gets fixed for 469c?

**Comment by TheComputerGuy96** [comment]
The game seems to work now on Wayland with SDL 2.0.22 (maybe it's an SDL update that fixed it or a code change?)

I think you still have to use the system SDL libraries though (a variable to use them or an SDL update to the version mentioned above with Wayland backend enabled would be nice)

I updated my game to commit 6b2c7d0f8e7524ad22d05a50ba83a5a154b5a7ac BTW
