### ISSUE TITLE
Add a screenshot key bind in the menu

### ISSUE THREAD

**Issue by t3r6** [OldUnreal/UnrealTournamentPatches#1611]
Please add a key bind to the game controls preferences to take a screenshot in the game.

**Comment by SeriousBarbie** [comment]
Doesn't the PRINT key work?

**Comment by BerserkerBG** [comment]
> Doesn't the PRINT key work? 

I think he means the "SShot" bind, which is usually the F9 key for taking screenshots in UT99. Print key doesn't save it as a file, it just copies it in clipboard. SShot saves a png screenshot inside UT/System/Screenshots (469).

**Comment by SeriousBuggie** [comment]
Possible Implementation:
![img](https://github.com/user-attachments/assets/7fd51def-353b-4ef3-bacb-132c493b6303)
