### ISSUE TITLE
Add a suicide key bind to the menu

### ISSUE THREAD

**Issue by t3r6** [OldUnreal/UnrealTournamentPatches#1613]
Since "suicide" is a very useful action on Bunnytrack maps and in some other UT99 gametypes and mods, please add a key bind for it to the game controls preferences.
It can be just below "Feign Death".

**Comment by SeriousBuggie** [comment]
Possible Implementation:
![img](https://github.com/user-attachments/assets/7fd51def-353b-4ef3-bacb-132c493b6303)
