### ISSUE TITLE
Spectator is affected by zones with damage over time substances

### ISSUE THREAD

**Issue by t3r6** [OldUnreal/UnrealTournamentPatches#1617]
I don't know whether it is a bug or a feature but when you spectate and dive into lava, for example, the spectator camera starts to shake as if you are taking a damage.
It's a trivial thing, but could be useful to turn off this effect somewhere in the settings.

**Comment by SeriousBuggie** [comment]
If you referring to XV server, it use custom xZones mod. Which make more effects from usual.

**Comment by t3r6** [comment]
> If you referring to XV server, it use custom xZones mod. Which make more effects from usual.

Yes, you are right. This bug is not present in the original game. I'm closing the issue.

**Comment by t3r6** [comment]
@SeriousBuggie I remembered one thing. Spectator is affected by the wormhole effect on DM-Hyperblast, which even makes you stuck out of the map. Probably, there are more things that can affect a spectator in the original game. Not sure, if this one can be fixed. Should I submit a new issue regarding it?

**Comment by SeriousBuggie** [comment]
Feel free open it. Indeed, spectators in moving zones affected, which annoying.
