### ISSUE TITLE
[469d] CTRL+ALT+LMB can accidentally trigger ALT+LMB properties shortcut while using Box select

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1619]
• ALT+LMB is a Ued shortcut, which brings up Actor Properties.
• CTRL+ALT+LMB is a Ued shortcut, which brings out Box Selection inside 2D Viewports.

If user is trying to Box Select multiple actors, or vertex edit brushes using CTRL+ALT+LMB, it would trigger the ALT+LMB shortcut if user accidentally clicks on an actor instead of empty space. This instantly brings up Actor Properties instead of making a Box Selection.

Here is a video example demonstrating the issue:

https://github.com/user-attachments/assets/34a3b21f-f953-4374-874a-b5d7b57114e1

This is a simple example, however, In complex maps with a lot of actors and brushes it is sometimes hard to find empty spot to click on in order to make Box Select work.

## Suggestion:
When user is making Box Selection with CTRL+ALT+LMB, it should temporarily ignore the ALT+LMB shortcut when user clicks on actors.

**Comment by SeriousBuggie** [comment]
Must be fixed via https://github.com/stijn-volckaert/UnrealTournament/commit/e0d7933a352ab4397b70504e3ef511ab075ad121
