### ISSUE TITLE
[469a] Transparency issue with compressed textures

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#162]
Import this transparent PNG as DXT3. See the white edge? It happens with any texture, right at the edges.
![Untitled-1](https://user-images.githubusercontent.com/72151582/98729222-5b04fa80-2379-11eb-8fd9-ea6ed9d5f2d6.png)
![Untitled-2](https://user-images.githubusercontent.com/72151582/98729224-5c362780-2379-11eb-9b82-f2b3ba2eccdf.png)

**Comment by CacoFFF** [comment]
Not a bug.
This is what the PNG looks like when you see what's "under" the alpha mask
![imagen](https://user-images.githubusercontent.com/15526924/102473359-5d680d80-4025-11eb-8c27-7cf5a7a380b9.png)

**Comment by sn260591** [comment]
What is the point in dxt3/dxt5 if alphablending is not available?

**Comment by CacoFFF** [comment]
STY_Masked uses the alpha channel, with values under 0.5 not being displayed.
Some renderers may implement options that change how some surfaces are displayed and do use alpha.
