### ISSUE TITLE
tacops 469a and 469b on v451 ace1.1f server. start a demo and loose footsteps and local gun sounds have repeated the behaviour

### ISSUE THREAD

**Issue by lumi1776** [OldUnreal/UnrealTournamentPatches#163]

**Comment by stijn-volckaert** [comment]
Can you try "mutate ace sftoggle" to see if that fixes it?

**Comment by lumi1776** [comment]
That’s seems to do the job thanks

Toggle to off and sounds are ok again


________________________________
