### ISSUE TITLE
[469b] Self Auto taunts not working online/server

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#164]
anyone else notice self auto taunts not working in 469?

work fine offline in practice session.

just not online.

**Comment by Chamberly** [comment]
I'm joining a 436 server with 469b and I hear them. Which server isn't working online for you?

**Comment by no0nehere** [comment]
if you set autotaunt = true on your client do you hear your taunts after killing players?

**Comment by Chamberly** [comment]
> if you set autotaunt = true on your client do you hear your taunts after killing players?
> 
> i hear other players taunts... just not my own.

Yes I do hear my own. Are there specific mod causing the conflict? I've been using it on and going across a few servers and I hear my own autotaunts.

**Comment by no0nehere** [comment]
for me only one taunt works... Ive got the flag! when i pickup the flag .. must be a client issue.

iam using gotty patched to 469b.
