### ISSUE TITLE
UnrealEd: ^A in window "Actor Text View"

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1640]
Only a small thing: the usual shortcut STRG+A doesn't work in UnrealEd's "Actor Text View"…

**Comment by SeriousBuggie** [comment]
Ctrl+Home and after Ctrl+Shift+End - current workaround.
Or any other way. Like 
Ctrl+End and after Ctrl+Shift+Home
