### ISSUE TITLE
[469d] starts on wrong monitor in Ubuntu 22.04

### ISSUE THREAD

**Issue by obibann** [OldUnreal/UnrealTournamentPatches#1649]
Hi all,

I've successfully installed UT from GOTY CDs using patch 469d on my Ubuntu 22.04.

However, when I launch the game, it is launched on the wrong monitor.

I have 2 monitors:

- Laptop screen (set as secondary)
- External monitor connected via HDMI (set as primary monitor)

For every other games an applications, they are correctly launched on the primary monitor.
But for UT, it is launched on the secondary monitor (laptop screen) and I want the game to be on the HDMI  monitor (primary).

Thank you for your help.

**Comment by SeriousBuggie** [comment]
Try switch to windowed mode, move window to desired screen and exit from game.
After that, game must open on desired screen.

**Comment by obibann** [comment]
Hi !

I was able to fix the issue, thanks to the documentation actually.

I have deleted the embedded  `libSDL2-2.0.so.0` so that the game will use the system one and it works :-)

Thank you for your help.

**Comment by obibann** [comment]
Resolved
