### ISSUE TITLE
[469b] Log doesn't finish

### ISSUE THREAD

**Issue by Chamberly** [OldUnreal/UnrealTournamentPatches#165]
I kept getting crashes on Wildcard's gauntlet server and I'm thinking it's related to the firework flak cannon as several time when I crashed I see the firework on the screen. Server IP: unreal://64.94.100.181:7777
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/5535043/UnrealTournament.log)

**Comment by Chamberly** [comment]
![Shot00051](https://user-images.githubusercontent.com/11419314/99038481-922f0380-2553-11eb-8c86-ffbab23c6b79.png)
And these bad boys are the massive flak firework party.

**Comment by an-eternity** [comment]
I noticed similar problem - client hangs/crashes when there are too many effects spawned by projectiles (though, i am unsure whether it is related to sounds or to graphics).
This also happens with v436, but less often.

**Comment by CacoFFF** [comment]
The only workaround to this is to start the game with the `-forcelogflush` in the command line, but mods that like to spam your log will probably lower your framerate due to the significant increase in file write operations every second.

**Comment by stijn-volckaert** [comment]
This happens when a thread causes a crash without invoking the game's exception-handling mechanism. We've fixed a few of these issues since 469b. Some external (native) mods can still cause this problem, but those are out of our control.
