### ISSUE TITLE
[469d] UnrealEd Surface Properties window does not display correctly

### ISSUE THREAD

**Issue by Napuntoki** [OldUnreal/UnrealTournamentPatches#1650]
On my system, the texts and buttons do not display correctly in the Surface Properties window, causing most of it to be cut off and inaccessible. This window is apparently the only one that can't be resized, so all of the settings in the cut-off portion can't be used at all.

Running 469d version of UnrealEd on Windows 10. Everything else seems to work as expected.

![surfaceproperty](https://github.com/user-attachments/assets/d8c273ab-7576-4851-a3d4-28e82ac0e940)

**Comment by SeriousBuggie** [comment]
What is your Windows font scale ratio? It appear somewhere in OS settings, like Display or something.

**Comment by Napuntoki** [comment]
I'm using 1920x1080, DPR is 1. Changing the scaling in the Windows display screen has no affect:

![surfaceprop](https://github.com/user-attachments/assets/db4fdb00-fc6e-4080-999a-dad4ea0011c2)

**Comment by SeriousBuggie** [comment]
Hmm. Anything specific about Windows theme, like enlarged font?
Try switch windows theme to one stock. Maybe even try Windows Classic one.

**Comment by Napuntoki** [comment]
Nope, I'm on the default Windows 10 theme. I tried changing the font scaling option under Ease of Access (it was already at default), but no effect. I also tried all the high DPI settings under the Compatibility tab just in case.

I did find out something interesting. I installed a fresh copy of UT99 436, and that version's UnrealEd has the same problem:
![ut99436](https://github.com/user-attachments/assets/160a8e16-7199-4b91-9899-f1dd80723c00)

The UnrealEd that comes with UT2004 does not:
![ut2004](https://github.com/user-attachments/assets/42a2d734-4bbf-4131-8eb1-9e9bad8d158c)

Judging from that, I have to assume this isn't a patch 469-specific problem and it either has something to do with my set-up or it was a bug that was already present from the old version of UnrealEd.

**Comment by SeriousBuggie** [comment]
You first who complain about such issues. So it look like something specific about your setup.
However this change affect only some stuff, which not affect UT2004.

**Comment by SeriousBarbie** [comment]
The font in your first post does not look like the Windows default font like here:
![UnrealEd-Surface-properties](https://github.com/user-attachments/assets/776d1f12-9354-4429-b137-1f65653eac20)
Maybe have a look at `[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts]` as explained here: https://answers.microsoft.com/en-us/windows/forum/all/change-my-windows-10-font-to-default/dc8d153f-7d7f-4234-91e7-2d1bca93371a

**Comment by Napuntoki** [comment]
Both of you are right, the problem indeed was that UnrealEd was defaulting to using the wrong font in that specific window.

Problem was solved after switching the language for non-Unicode programs from English to another language, then back to English. Since I use languages other than English on my setup, I assume something in the registry was messed up and doing that cleared it up.

Thank you both for the help!
