### ISSUE TITLE
Feature Request: Netspeed-independent FPS

### ISSUE THREAD

**Issue by Decifian** [OldUnreal/UnrealTournamentPatches#1657]
Hi, not sure if this is even theoretically feasible, but would it be possible to make it so that your netspeed setting does not cap your FPS in online matches? Some servers still don't allow a setting of more than 20,000 B/s which effectively results in a roughly ~310FPS cap. With 360 and even 480Hz monitors available these days, it's a bit disappointing to not be able to get the most out of them. Is it possible to remove this limitation so that you could still get higher FPS even when you can't raise netspeed? Or would that mess something up? I'm not sure why these servers limit the netspeed but if it's to reduce traffic then I don't think it makes much of a difference, I tested it and STAT NET shows the bytes out at 310FPS hovers around ~5650, but only increases to around ~6150 even at 1200FPS.

I don't know how this stuff works so maybe this is complete nonsense, sorry if I'm asking for the impossible.

**Comment by Calinou** [comment]
This would need separating the physics step from rendering, which is technically feasible (see Q2PRO's `cl_async`) but is a *lot* of work.

**Comment by Decifian** [comment]
> This would need separating the physics step from rendering, which is technically feasible (see Q2PRO's `cl_async`) but is a _lot_ of work. Doing so will also increase input lag a bit, since you will need physics interpolation which adds up to a frame of input lag (for things other than mouse aiming).
> 
> I would probably contact server admins to increase their maximum netspeed instead 🙂

I see, thanks for explaining what would go into doing something like this! It does sound like a lot of work for something so minor, so better indeed to just ask server admins to increase netspeed.
