### ISSUE TITLE
Video freeze on MBP M4 Max

### ISSUE THREAD

**Issue by PatDal81** [OldUnreal/UnrealTournamentPatches#1660]
Hi,

Got this weird issue where the video will freeze briefly and music will continue once in a while, without any ability to reproduce the issue constantly.  Ambient sound will stop but you can still hear the music playing.  The freeze last for 1 to 2 seconds and game will continue once it unfreeze.  I tried disabling Game Mode but I still have the same issue.

Specs are:

UT99 4.69d
Macbook Pro 14in with M4 Max, 36gb ram.  
Sequoia 15.1 

I was playing before (same instance as I copied over my UT99 folder to the new computer) flawlessly on a MBP M3 Pro and a MBP 2019 (Intel i9) without ever experiencing this issue.  This is why I think this issue is bound to the new M4 CPU.

Let me know if you need anything else to help debug this issue.

**Comment by PatDal81** [comment]
Anyone?

**Comment by 12sunflowers** [comment]
if you have money for M4, buy nomal PC and do not complain;)
arm totally different architecture that not compatible with x86 software, especially 25y old games, its true sorry:)

**Comment by stijn-volckaert** [comment]
We've optimized OpenGLDrv quite significantly since 469d. Come talk to us on Discord if you want to test a 469e preview.

**Comment by PatDal81** [comment]
@stijn-volckaert I confirm the bug is not present in 469e with the OpenGLDrv - thanks for the hint!  In addition to that bug, 469e has resolved the issue with fullscreen monitors on Mac.
