### ISSUE TITLE
Fails to start on Mac 14.4

### ISSUE THREAD

**Issue by RamakrishnanArun** [OldUnreal/UnrealTournamentPatches#1665]
I downloaded the Mac OS DMG release, copied it into Applications.
Then I replaced it with the Sonoma fix version.
I copied the data files into the Application Support folder and when I attempt to run, it fails with this error message
```
Failed to enter Entry: Can't find file Entry.

History: UGameEngine::Init <- InitEngine <- main
```

<img width="257" alt="image" src="https://github.com/user-attachments/assets/9f9ae610-9778-4fe0-9ed5-64db2faa8add">

**Comment by SeriousBuggie** [comment]
You can't run patch itself. You need apply patch to original game.

Read it here: https://github.com/OldUnreal/UnrealTournamentPatches?tab=readme-ov-file#macos-installation

You can grab game ISO here: https://archive.org/download/ut-goty/UT_GOTY_CD1.iso

Here detailed instructions:

To install the games on **macOS** systems (this is too complicated right now. We are working on a more elegant solution!): 
- Open a new Finder window
- Press ⇧⌘G to bring up the "Go to folder:" dialog
- Enter "~/Library/Application Support/" (without the quotes!) in the edit box and click ok
- Within the ~/Library/Application Support/ folder, create a new folder called "Unreal Tournament" (without the quotes!) if you want to install Unreal Tournament or "Unreal" (without the quotes!) if you want to install Unreal
- Mount the game disc by double-clicking the iso
- Copy the Maps, Sounds, Textures, and Music folders from the game disc into the folder you just created. Do not copy the System folder!
- If you are installing Unreal Tournament, then open the Textures folder and delete the "LadderFonts.utx" and "UWindowFonts.utx files.
- Download our latest patch from GitHub. That means https://github.com/OldUnreal/UnrealTournamentPatches/releases/latest for Unreal Tournament.
- Double-click the patch dmg file and drag the application bundle into the application folder
- Finally, if you are installing Unreal Tournament, open a terminal window and run the following commands:
```
for file in ~/Library/Application\ Support/Unreal\ Tournament/Maps/*.uz; do /Applications/UnrealTournament.app/Contents/MacOS/UCC decompress $file; done
mv ~/Library/Application\ Support/Unreal\ Tournament/System/*.unr ~/Library/Application\ Support/Unreal\ Tournament/Maps/
rm ~/Library/Application\ Support/Unreal\ Tournament/System/*.uz
```
- All Done!

**Comment by RamakrishnanArun** [comment]
Thanks for such a quick response on a Sunday too!
Let me give it a go. I must have missed some step.

**Comment by RamakrishnanArun** [comment]
That worked perfectly! I missed something in those commands at the end.
Can't wait to play, been over 20 years!

**Comment by SeriousBuggie** [comment]
Added this step into instruction.

**Comment by jdm0** [comment]
The second of the three commands is "mv", not "cp", so the third command "rm" is unnecessary.

**Comment by SeriousBuggie** [comment]
mv for .unr files.
rm for .uz files.
