### ISSUE TITLE
no unrealed in the sonoma latest release???

### ISSUE THREAD

**Issue by cbtenjoyer69420** [OldUnreal/UnrealTournamentPatches#1666]
its not in the both system folders pls i wanna make maps

**Comment by cbtenjoyer69420** [comment]
just because my nickname is different doesnt mean that im an troll

**Comment by SeriousBuggie** [comment]
Currently UnrealEd work only for Windows. So for run it on others platforms you need some kind of Windows emulator, like wine, proton and so on.

No Native editor for non-Windows platforms yet.

**Comment by cbtenjoyer69420** [comment]
so like, where i can download it then?

**Comment by cbtenjoyer69420** [comment]
oh, just remembered that it comes with ut99
