### ISSUE TITLE
[469a] Items have become smaller

### ISSUE THREAD

**Issue by edesimuh** [OldUnreal/UnrealTournamentPatches#167]
Items, such as weapons, ammo, flags in CTF, etc, now require you to come closer to them than before in order to pick them up.

This has been most noticeable with flags in CTF over the past months and reported by many players who have played on UTCTFpug's 469 servers.

Here is an example from a player's Twitch stream - he should definitely have picked up the flag after he had walked this close to it: https://clips.twitch.tv/OptimisticAgileSpindleLeeroyJenkins

There were also extreme examples where players had seemingly walked right through a flag and not picked it up, but I'm not sure that is the same issue. I submitted those examples, too, in my old bug report in the OldUnreal forums - https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1598741892

**Comment by Chamberly** [comment]
IMO it does not look like the actor has gotten smaller. There was a lag from the server and client and the server is saying the client did not pick it up...

What are all the mods loaded on it and what's the ping of these players? Might have to do internal debugging if the actors are not properly in order, and wonder if I need to raise such priority.

**Comment by edesimuh** [comment]
Server packages are: UTPureRC7H, Purestats, SmartCTF 4D Plus Plus, MapVoteLA13, ACE 1.2

The player in question had a ~50 ping, and most of the players playing on these servers are in the 10-90 range.

**Comment by Chamberly** [comment]
Mind if anyone can provide Purestats? I can't find it lol.

**Comment by edesimuh** [comment]
@Chamberly Of course, sorry you probably would have found it if I specified the version, PureStat7H.

Here it is: https://20yearsofut.in.rs/etc/PureStat7H.u

**Comment by stijn-volckaert** [comment]
Items definitely have not become smaller, but we have fixed a few problems that could make actors appear in the wrong location. I believe this might have been one of those cases.
