### ISSUE TITLE
GPF in map MH-Revenge][.unr

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1670]
Trying to run map [MH-Revenge][ ([available on unrealarchive.org/](https://unrealarchive.org/unreal-tournament/maps/monster-hunt/R/mh-revenge_eef6d347.html))  leads to instant GPF: ![MH-Revenge -GPF](https://github.com/user-attachments/assets/468243f6-6f7a-4eeb-a720-36e29a16c584)
Window 10 running OldUnreal-UTPatch469e-Windows-test831.
[UnrealTournament.log.zip](https://github.com/user-attachments/files/17910105/UnrealTournament.log.zip)

**Comment by Chamberly** [comment]
I've joined the Barbie MH test server and was able to join without crash. D3D9 render used. Unless there is something else I'm missing.

**Comment by SeriousBuggie** [comment]
It is about specific map. So you need vote for it you want test it.
Vote can be open by say `!vote` or console command `mutate bdbmapvote votemenu`.
