### ISSUE TITLE
Multiple hints for buggy movers 

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1673]
I guess the warning for movers with broken collision appears every time the map is (auto) saved and so the screen gets filled.
Suggestion: while message is displayed, don't display another one (use semaphore or modal window or ...)
![WindowWindowWindow](https://github.com/user-attachments/assets/e3e507f6-f1f2-4b71-a9eb-fecdf5227acd)

**Comment by SeriousBuggie** [comment]
Did you use autosave? Or how you make so many of them?

**Comment by SeriousBarbie** [comment]
Ofc auto save - UnrealEd crashes even in latest versions.

**Comment by SeriousBuggie** [comment]
Well, maps usually huge enough, so this make lags on save.
So I personally not use it.
Prefer manually save periodically with proper versioning.

Bug fixed in test build 836.

Also all editor crashes need report, so we can fix them.

**Comment by SeriousBarbie** [comment]
> Also all editor crashes need report, so we can fix them.

I was not able to reproduce the crash - it happened multiple times on deleting a brush.

**Comment by SeriousBuggie** [comment]
In latest test versions come nice crash logger. So sometimes even reproduce steps not need fix bug now. So feel free make issue and add crash message and crash log.
