### ISSUE TITLE
[469b] cant see projectiles in behindview players (spec mode)

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#168]
just wondering if its just my UT , but when i go into spec mode in 469 and into behindview, I cant see the players projectiles.
works fine in 436.
this problem is using 469 client on a 469 server.. specing real players.

**Comment by Chamberly** [comment]
What's the server IP? I haven't found anything locally.

**Comment by no0nehere** [comment]
116.251.192.212:7760 can only test when players online works fine with bots on server..

**Comment by scottadkin** [comment]
Yeah I noticed in spectator mode of the |uk| instagib server(newnet) that the beams don't spawn, you only see the ring impact in behindview mode while being a spectator.


185.107.96.18:7777

**Comment by stijn-volckaert** [comment]
Can you check if this still happens with the 469b release?

**Comment by scottadkin** [comment]
The bug while spectating in newnet servers seems to be fixed.
