### ISSUE TITLE
game crashes when trying to record demo using builded in demo manager

### ISSUE THREAD

**Issue by cbtenjoyer69420** [OldUnreal/UnrealTournamentPatches#1684]
error: Failed to load De: Can't find file De..

History: UObject::SafeLoadError <- UObject::GetPackageLinker <- UGameEngine::BuildServerMasterMap <- UDemoRecDriver::InitListen <- ULevel::Exec <- UPlayer::Exec <- UViewport::Exec <- USDLViewport::Exec <- APlayerPawn::execConsoleCommand <- UObject::ProcessEvent <- UEngine::InputEvent <- USDLViewport::CauseInputEvent <- USDLViewport::UpdateInput <- UViewport::ReadInput <- AbsorbedPaused <- ULevel::Tick <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- MainLoopIteration <- MainLoop <- main
also, why airfight maps dont appear?? i put everything in the right folders in the right places 
(tbh i dont know how do i add labels)

**Comment by SeriousBuggie** [comment]
Remove line from your UnrealTournament.ini file:
`ServerPackages=De'

We already remove it for Default.ini in 469e, however we not touch UnrealTournament.ini, so users msust edit it manually.

Also we include de.u into 469e patch.
So this issue must not happen on 469e.

**Comment by cbtenjoyer69420** [comment]
> Remove line from your UnrealTournament.ini file: `ServerPackages=De'
> 
> We already remove it for Default.ini in 469e, however we not touch UnrealTournament.ini, so users msust edit it manually.
> 
> Also we include de.u into 469e patch. So this issue must not happen on 469e.

thx
