### ISSUE TITLE
Unreal 99 Demo support 

### ISSUE THREAD

**Issue by actraiser30** [OldUnreal/UnrealTournamentPatches#1685]
Hello 

Is it possible to add support for the Unreal tournament 99 Demo ???

Thanks

**Comment by SeriousBuggie** [comment]
Please specify what you talk about.
In Title you say "Unreal", when in body you say "unreal tournament".

UT can't play Unreal demos. It is different games.

Or you talk not about demo files (record and playback gameplay), but about demo game version?

**Comment by actraiser30** [comment]
What I'm asking is to add to the game engine support for the unreal tournament 99 Demo game version.
