### ISSUE TITLE
[469b] Pulse gun altfire produces a whistling sound

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#169]
As the title says, in 469b with Galaxy/D3D9,  the Botpack.Pulsegun produces a (horrible) whistling sound when using the altfire - this happens in any map but only in certain locations which I assume to be where there are AmbientSound or ZoneInfo actors.

Needless to say, this doesn't happen in 436/451.

**Comment by CacoFFF** [comment]
Does it happen if you stay completely still when alt-firing?

**Comment by OjitroC** [comment]
Yes, almost exclusively when standing still and rarely when moving.  It doesn't happen every time I stand still.  The sound can still be heard for several seconds if I stop altfire and move away.  If I stop firing and don't move, the sound will continue for as long as I am standing in the spot where it happened - for up to a minute anyway, haven't tried it for longer than that as the sound becomes annoying.

The sound is like a whistle and a buzz combined and very noticeable.

**Comment by OjitroC** [comment]
UPDATE 
Another weapon that produces the same sound under the same circumstances noted in my earlier posts.

The whistling/buzzing noise also happens with the altfire of the SavagePackage.EARifle (from the Savage Lands Unreal/UT mod/sp campaign.

I've also heard the odd whistling sound in other circumstances but the sound is very brief and the circumstances too varied to provide any more detail.

**Comment by stijn-volckaert** [comment]
Does this still happen in the 469b release version?

**Comment by OjitroC** [comment]
Yes, it does - certainly with the PulseGun, I haven't tried the SavageLands EARifle yet.

**Comment by OjitroC** [comment]
To reproduce
1 Download this map https://www.mediafire.com/file/phx1vcp83e63opu/DM-Counterfeits.zip/file
2 Use Galaxy Audio and run the map
3 Seek out the Versace kiosk and the Pulse Gun
4 Stand outside the kiosk and fire the weapon using alt-fire 
5 I get the continuous whistling/buzzing sound - this noise persists for a while even if I move away

**Comment by stijn-volckaert** [comment]
Could you try this dll with the v469c-RC2 client please
[Galaxy.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9175397/Galaxy.zip)
?

**Comment by an-eternity** [comment]
> Could you try this dll with the v469c-RC2 client please [Galaxy.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9175397/Galaxy.zip) ?

Can not reproduce this issue if original Galaxy.dll in v469c-RC2 replaced by this one.

**Comment by OjitroC** [comment]
I can no longer reproduce the issue with the Pulse Gun using the replacement Galaxy.dll either and, indeed, don't get the issue with the SavagePackage.EARifle.

**Comment by stijn-volckaert** [comment]
The fix is included in v469-RC3
