### ISSUE TITLE
[469d] Server mods can alter .ini settings and cause side effects

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1690]
Some mods like UTPureDP2B will silently alter the ModMenuClass to UTPureDP2B.bbUMenuModMenu. If you join a server with this mod, it will alter your UT.ini settings without even knowing. In this specific example, your UT client will be dependent on the existence of this mod, which needs to be present either in the Cache folder, or System. If you decide to clean your Cache folder or delete the mod in System (if mod is installed normally), then it will cause side effects such as not being able to open your Mod menu anymore:

https://github.com/user-attachments/assets/6f323300-d590-4d6a-ba5b-5d8e993c53f8

Suggestion:
If specific ini values are not found, then they should fallback to the default ones. In this example `ModMenuClass=UMenu.UMenuModMenu` has been changed to `ModMenuClass=UTPureDP2B.bbUMenuModMenu`. If UT fails to load it, then it can revert to the default value, which is `UMenu.UMenuModMenu`.

**Comment by SeriousBuggie** [comment]
Fix pushed. Will appear in next build with updated script packages.
