### ISSUE TITLE
[469e] Missing Italian translations

### ISSUE THREAD

**Issue by Alby1987** [OldUnreal/UnrealTournamentPatches#1696]
I've noticed that some buttons of the UI are not translable ("Advanced" button on the Renders, the "Fix Network" button and associated window, "Toss Relic" key binding) and some Italian translations are missing (the most important are the misc/other key bindings).

I've translated the most important (I had trouble translating the _setting.int files)
https://github.com/OldUnreal/unreal-localization/pull/2

Don't know if that repository is still used for the localizations

**Comment by SeriousBuggie** [comment]
Yes, we still use this repo. I merge your PR for next RC of 469e.

**Comment by Alby1987** [comment]
Reopening because as rc7 this was not fixed

![Image](https://github.com/user-attachments/assets/2dbaf0b2-f84b-4b0d-9c8c-af6cb81a8088)

Missing in the int files are the tree Toggle (Scoreboard, Server Info, Objectives). Toss Relics is translated in Relicsbindings.itt, but still not showing.

Then I ask if is possible to enlarge the option window to let longer text to be shown.

Thanks!
