### ISSUE TITLE
[469e] restoreGamma

### ISSUE THREAD

**Issue by medorUT** [OldUnreal/UnrealTournamentPatches#1698]
update player 469d to 469e windows 10
I have the old restore gamma error back when closing UT player with d3d9 and the new 469e.

1/ Just try to set shader to never ....  not work for me.
2/ Remove the set D3D9 in UT.ini that work fine but put me on spectator and no color team when i start new practice session.

[D3D9Drv.D3D9RenderDevice]
ZRangeHack=True
NoAATiles=True
NumAASamples=0
UseAA=False
UseSoftwareVertexProcessing=False
UsePureDevice=True
UseTripleBuffering=False
MaskedTextureHack=True
SmoothMaskedTextures=False
SceneNodeHack=True
FrameRateLimit=389
SwapInterval=0
UseFragmentProgram=False
TexDXT1ToDXT3=False
DynamicTexIdRecycleLevel=100
CacheStaticMaps=False
UseTexPool=True
UseTexIdPool=True
UseSSE2=True
UseSSE=True
SinglePassDetail=True
SinglePassFog=True
ColorizeDetailTextures=False
DetailClipping=False
DetailMax=0
RefreshRate=240
MaxTMUnits=0
NoFiltering=False
MaxAnisotropy=0
Use565Textures=False
Use16BitTextures=True
UseS3TC=True
UseTrilinear=False
UsePrecache=False
UseMultiTexture=True
MaxLogTextureSize=8
MinLogTextureSize=0
OneXBlending=False
GammaCorrectScreenshots=True
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.600000
//LODBias=-4.000000
//LODBias=10.000000
LODBias=3.000000
DetailTextures=False
DescFlags=1
Description=
HighDetailActors=False
Coronas=False
ShinySurfaces=True
VolumetricLighting=False
SurfaceSelectionColor=(R=0,G=0,B=31,A=31)
UseShaderGamma=Never

**Comment by SeriousBuggie** [comment]
> Remove the set D3D9 in UT.ini that work fine but put me on spectator and no color team when i start new practice session.

Not get what you mean.  Remove d3d9 section from ini can't affect spectator/player or teams colors.

**Comment by SeriousBuggie** [comment]
> I have the old restore gamma error back when closing UT player with d3d9 and the new 469e.

How exactly you close game? Menu item, console command, "x" button on window?
In which mode be game, during exit? Fullscreen, windowed, borderless?

**Comment by medorUT** [comment]
UseFragmentProgram=True
UseShaderGamma=Always

fix it

> > Remove the set D3D9 in UT.ini that work fine but put me on spectator and no color team when i start new practice session.
> 
> Not get what you mean. Remove d3d9 section from ini can't affect spectator/player or teams colors.

but that do it

**Comment by medorUT** [comment]
> > I have the old restore gamma error back when closing UT player with d3d9 and the new 469e.
> 
> How exactly you close game? Menu item, console command, "x" button on window? In which mode be game, during exit? Fullscreen, windowed, borderless?

echap/game/quit

**Comment by medorUT** [comment]
UseFragmentProgram=True
UseShaderGamma=Always

fix the gamma

**Comment by SeriousBuggie** [comment]
> > > Remove the set D3D9 in UT.ini that work fine but put me on spectator and no color team when i start new practice session.
> > 
> > 
> > Not get what you mean. Remove d3d9 section from ini can't affect spectator/player or teams colors.
> 
> but that do it

What exactly do you do? Remove whole ini, or open INI in editor, search d3d9 section, and remove only this section?



> > > I have the old restore gamma error back when closing UT player with d3d9 and the new 469e.
> > 
> > 
> > How exactly you close game? Menu item, console command, "x" button on window? In which mode be game, during exit? Fullscreen, windowed, borderless?
> 
> echap/game/quit the game is CTF

Not game mode. Mode of screen. It can be only Fullscreen, windowed or borderless.

How you close game? Via menu item? Via run console command "quit"? Via press "X" button in window title?

**Comment by medorUT** [comment]
Just remove all set under this line ; i have keep [D3D9Drv.D3D9RenderDevice] line
[D3D9Drv.D3D9RenderDevice]

Fullscreen

![gh](https://github.com/user-attachments/assets/ccb49d43-e508-4ac1-aca9-0e77b8bc67d1)

**Comment by SeriousBuggie** [comment]
Can't reproduce it on Win10.
Please ensure you use latest graphics drivers.
Also if you end fullscreen before exit, with alt+enter and only after exit, gamma stay on screen or no?

**Comment by medorUT** [comment]
seems AnthraX found the error ...the .exe update make this but not the update with the x86.zip
.exe removed to download the time it's fixed
