### ISSUE TITLE
DirectX11 Renderer v.1.6.1 crash

### ISSUE THREAD

**Issue by cda963** [OldUnreal/UnrealTournamentPatches#1699]
Using the DirectX11 Renderer v.1.6.1 (https://www.gamepressure.com/download/unreal-directx11-renderer-v161-mod/ze12ae5), the game crashes ~30 seconds into the game.

**Comment by SeriousBuggie** [comment]
That render not supported. 469e come with two great D3D11 renders instead. You should use them instead.
