### ISSUE TITLE
Issues I've found so far

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#17]
- 1.) The FOV resets itself to the default value (90) when spectating with bots. This happens in every game type, with or without mutators. This does not happen online with real players. JSYK, the FOV that I use is a value of 105, or to be more precise, 106.25, which is the equivalent to 90 in a 16:9 resolution (1920x1080 is my resolution).

- 2.) I've noticed that when using the alternate fire of the Sniper Rifle (zoom in), the sniper's crosshair is of a bit higher quality in OpenGL and XOpenGL than of Direct3D 9 or Direct3D 11. Direct3D 11 also has blurry text in the menu and ingame, among a few other graphical issues. The first image is Direct3D 9/D3D 11, and the second image is OpenGL/XOpenGL.
![20200923192103_1](https://user-images.githubusercontent.com/71798183/94089279-6788c000-fdd8-11ea-8321-8e9eb318816c.jpg)
![20200923192140_1](https://user-images.githubusercontent.com/71798183/94089285-6c4d7400-fdd8-11ea-9681-b2fc2e5002ef.jpg)

- 3.) The Relics of Strength and Regeneration have some strange graphical issues, no matter which renderer I use -- they look like they have "holes" in them or something. Version 451 has also given me this problem in the past. When I was using version 451, I was also seeing these "holes" in a few other relics and in the "Nali WarCow" player model. 
![20200923193338_1](https://user-images.githubusercontent.com/71798183/94089300-766f7280-fdd8-11ea-93fd-2cc25b6d42aa.jpg)
![20200923193419_1](https://user-images.githubusercontent.com/71798183/94089320-7ec7ad80-fdd8-11ea-87d5-222068a84e6a.jpg)

- 4.) Some things, such as the Translocator module, gibs, or balls of acid from the Slith's ranged attack, appear brighter than usual. 
![20200923202004_1](https://user-images.githubusercontent.com/71798183/94090287-dbc46300-fdda-11ea-9ae9-0b29b2a02e7c.jpg)

- 5.) I frequently go to this certain Monster Hunt server whenever I can and feel like it. The server uses some sort of mutator to make the HUD and whole interface look different (I believe it is called NexGen?), including the scoreboard. For some reason, only a few names will appear on the scoreboard, and then no other names will appear on the scoreboard, even after someone else joins the server. 436 and 451 did not give me this problem. Notice in the two screenshots below how the game said a new player had joined, but the scoreboard hasn't been updated.
![20200923151533_1](https://user-images.githubusercontent.com/71798183/94090318-e8e15200-fdda-11ea-8311-cd6ac767eed6.jpg)
![20200923152003_1](https://user-images.githubusercontent.com/71798183/94090331-ee3e9c80-fdda-11ea-8df0-d0098d6cbf0a.jpg)

- 6.) On the same server, there is a mutator that enables a radar. The radar is surrounded by a bright purple square in XOpenGL. GitHub won't let me upload the damn picture, so, sorry -- no picture.

- 6.) XOpenGL also makes the drop-down options in the menu look somewhat weird. 
![20200923192233_1](https://user-images.githubusercontent.com/71798183/94090382-10381f00-fddb-11ea-95fc-af49f15ba041.jpg)

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by Dr-Flay** [comment]
You should make a separate issue thread for each issue so other people with that same issue can use that thread or be easily merged with it.
It's a pain when you have multiple issues, but it makes it easier for the devs to label and close when dealt with.

**Comment by stijn-volckaert** [comment]
Exactly, please split this issue into individual tickets. I'm going to close this one for now. I'll respond to the issues once you've split them up.
