### ISSUE TITLE
[469a] Progress bar is lying about reachspecs

### ISSUE THREAD

**Issue by ghost** [OldUnreal/UnrealTournamentPatches#170]
When you rebuild a map the progress bar might display a counter stating that your map has 8000 reachspecs. However, if you look at the log window, it counts something around "Added 1300 reachspecs".

I made a cube room with over 200 pathnodes. The progress bar would display ~300 reachspecs. It's a lie! The log window counts over 20k reachspecs.

**Comment by CacoFFF** [comment]
It's not the reachspec count you're seeing on the bar, it's the [actor count/actor list].
Well, the editor could clarify it's walking over the actor list when rebuilding paths.

**Comment by SeriousBuggie** [comment]
It must be inside UnPath.cpp
`GWarn->StatusUpdatef( i, Level->Actors.Num(), TEXT("%s (%d/%d)"), TEXT("Adding reachspecs"), i, Level->Actors.Num());`
I guess change it to
`GWarn->StatusUpdatef( i, Level->Actors.Num(), TEXT("Adding reachspecs to actor (%d/%d)"), i, Level->Actors.Num());`
will be fine.
This allow lower load to copy same string again and again. And make build faster.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/bf550c23-76da-426d-a547-15f5dd6ae863)
