### ISSUE TITLE
v469e-RC4@Win10: ALT+TAB switches weapon

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1701]
Operating system: Windows 10

0)  make sure that at least one window is open (explorer, notepad, whatever)
1) run UT in full screen having more than one weapon
2) press ALT+TAB (what switches to another window)
3) press ALT+TAB again (what switches back to UT)
Expected behaviour: nothing change in UT
Current behaviour: weapon switches

**Comment by SeriousBuggie** [comment]
Did you have some binds on Alt or Tab in game?

**Comment by SeriousBarbie** [comment]
I removed USER.INI, so that there cannot be any none default key bindings - same result as before.

**Comment by SeriousBuggie** [comment]
Win10, D3D9, Fullscreen. Can't reproduce.
If I use mine User.ini - nothing happens.
If I erase it and use stock, weapon fire, since by default Alt set to fire.

Please enable Utrace, reproduce bug, and upload log with utrace (in archive) here.

**Comment by SeriousBarbie** [comment]
(Haha, File.7z.zip was necessary because 7z is not allowed here.)
[INIs.zip](https://github.com/user-attachments/files/18219977/INIs.zip)
[UnrealTournament.log.7z.zip](https://github.com/user-attachments/files/18219980/UnrealTournament.log.7z.zip)

**Comment by Chamberly** [comment]
Something fishy in those files, it did the same to me but nothing shows up in the log. I didn't investigate long enough to find the cause.

**Comment by SeriousBuggie** [comment]
Log say there happen KeyEvent. And later engine call PrevWeapon.
PrevWeapon in ini bind only for MouseWheelUp.
Did you touch mouse scroll?

I see here Raw mouse input. Can you reproduce same use when choose Cursor or Direct input?

**Comment by SeriousBarbie** [comment]
It happens only with "Raw Input", not with "Cursor" neither with "DirectInput".
And no, I didn't even touch the mouse while using keyboard.

**Comment by SeriousBuggie** [comment]
Reproduced on Raw input Win10.

**Comment by SeriousBuggie** [comment]
Same issue for me if i goes from windowed to fullscreen via Alt+Enter.

**Comment by SeriousBuggie** [comment]
Such happen only for d3d9 and not for any other render.

**Comment by SeriousBuggie** [comment]
Somehow when d3d9 init fullscreen (after Alt+Tab or Alt+Enter) Windows 10 Post WM_INPUT event, which is broken. We will filter out such events in next 469e RC.

**Comment by SeriousBuggie** [comment]
What actually post OS is 
DevInput: WM_INPUT ignored (hDevice == NULL): 0 0, 0 30 00000000 0, 0 400 400 0, 0 0 0 0
which mean scroll be rotated to zero. MSDN say 0x78 (120) is min step for rotate scroll.
