### ISSUE TITLE
UnrealEd 469e-RC4: broken Texture when applying scale

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1707]
I put the steps into screenshots:
1) assign any texture to a surface
2) apply scale 2x
Result: Texture looks broken
(but can be fixed by choosing 'Unalign' and applying scale again)
Renderer in 3D-view:  Direct3D11
![UED#1](https://github.com/user-attachments/assets/fc742a28-1c0c-4b87-beec-096525842c50)
![UED#2](https://github.com/user-attachments/assets/7ecc3585-f4b0-4ac8-972f-ab131b7ab135)
![UED#3](https://github.com/user-attachments/assets/a4bb95b3-46eb-49b3-b85a-fc045ae45e60)

**Comment by SeriousBuggie** [comment]
That happen with any map? If not, please upload test sample.

**Comment by SeriousBuggie** [comment]
Can't reproduce on dm-deck16][

https://github.com/user-attachments/assets/c1fe9664-dddc-418d-9706-e21811a62816

**Comment by SeriousBarbie** [comment]
Try it with a a mover surface. Seems to happen only there.

**Comment by SeriousBarbie** [comment]
Just reproduced it with Mover3@DM-Codex.unr:
![Mover3@DM-Codex unr](https://github.com/user-attachments/assets/c9ff565e-ef00-4350-804c-11ed9f331354)
