### ISSUE TITLE
[469a] Server browser display/working with domain names

### ISSUE THREAD

**Issue by Chamberly** [OldUnreal/UnrealTournamentPatches#171]
![image](https://user-images.githubusercontent.com/11419314/100732210-6d7fbc00-339a-11eb-8377-23c46b7116a8.png)
I remember some people asking about this. Currently it doesn't work with the server browser, nor it does in xbrowser. It would be a popular request. It does work when you use the command 'open us.ut99fwb.com' and that server ask you to put in the password.

NFO server hosting does use a domain name system for the server as well. I'm not sure about other server hosts.

**Comment by SeriousBuggie** [comment]
Strictly speaking it is worked partially.
![scr_1615165254](https://user-images.githubusercontent.com/70026933/110261876-8eb80000-7fba-11eb-8be3-b2c8630d86fa.png)
As you can see players list loaded. Rules list loaded.
But main server info not loaded (or, possible, loaded but try link by IP name).

So this stuff can be fixed I think.

**Comment by SeriousBuggie** [comment]
For fix issue need replace line:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UBrowser/UBrowserServerPing.uc#L490
```
		if ( Server.IP != StripPort(Temp) )
			return;
```
to
```
		if ( StripPort(IpAddrToString(ServerIPAddr)) != StripPort(Temp) )
			return;
```
In short you compare IP with hostname and this obviously fail.

Now all work. 
localhost:
![scr_1615167122](https://user-images.githubusercontent.com/70026933/110263367-261f5200-7fbf-11eb-9809-c14424000ceb.png)
us.ut99fwb.com:
![scr_1615167222](https://user-images.githubusercontent.com/70026933/110263413-42bb8a00-7fbf-11eb-8b83-f20508721d26.png)
