### ISSUE TITLE
[469a] Bar for current ammo count doesn't go above 50% on HiDPI screen

### ISSUE THREAD

**Issue by akb825** [OldUnreal/UnrealTournamentPatches#173]
The bar below the gun icon on the HUD that shows how full you are doesn't go above 50% when playing at full resolution on a 4K monitor. Once you have more than 50% ammo, the bar won't move up or down until you deplete enough ammo to go below 50%, then it will decrease again. If I switch to a lower resolution, like 1080p, the ammo bar works as normal.

I am using the OpenGL renderer.

**Comment by AtifArshad1995** [comment]
Actually, even at 1080p, the weapon ammo bar doesn't completely go to 100%, it only goes to like 80%-ish. And I think this is independent from the renderer as I am using D3D9 renderer.

**Comment by stijn-volckaert** [comment]
Will be fixed in the next snapshot
