### ISSUE TITLE
[469a] "Tournament" setting for practice session does nothing.

### ISSUE THREAD

**Issue by akb825** [OldUnreal/UnrealTournamentPatches#174]
The "tournament" setting for a practice session is supposed to allow you to click when you're ready after moving to the next map, allowing you to browse around the map before starting the round. Toggling this currently does nothing, always immediately starting the round as soon as the map changes regardless of if it's set or not.

**Comment by CacoFFF** [comment]
Sounds like a problem with the game's input capture...
Does it stop happening if you do not press Fire to switch level? (wait or press jump).

**Comment by Chamberly** [comment]
Was this offline or on a server?

**Comment by akb825** [comment]
This is playing offline.

Pressing jump doesn't advance to the next level, but waiting for it to advance does prevent it from starting the match immediately.
