### ISSUE TITLE
[469a] FPS limiter doesn't work with limits over 500

### ISSUE THREAD

**Issue by scottadkin** [OldUnreal/UnrealTournamentPatches#176]
The FPS limiter acts like it's in unlimited mode if you use a value over 500.

Recreate:

type **fps 600** into console

Note: Don't have console open, it makes the fps limit unlimited.

**Comment by CacoFFF** [comment]
Windows?

**Comment by scottadkin** [comment]
Yes

**Comment by stijn-volckaert** [comment]
This is a limitation of the Win32 API, but we might be able to implement a more precise FPS limiter with different APIs.

**Comment by stijn-volckaert** [comment]
We've implemented a more precise limiter in 469d
