### ISSUE TITLE
[469b] UMOD installer broken

### ISSUE THREAD

**Issue by Dr-Flay** [OldUnreal/UnrealTournamentPatches#177]
UMODs were working in 469a but now show an error.
![UMOD-error](https://user-images.githubusercontent.com/43873202/101991871-5c428380-3ca7-11eb-8047-128fdab9eabe.jpg)

**Comment by stijn-volckaert** [comment]
Will be fixed in the next snapshot.

**Comment by IronManOz** [comment]
I had to download 
Unreal Tournament UMOD Extractor v2.0 
for now to extract the files.
