### ISSUE TITLE
Tournament progress not saved

### ISSUE THREAD

**Issue by mrzapp** [OldUnreal/UnrealTournamentPatches#18]
First of all, thank you for this amazing effort! I have so many fond memories of this game, and I'm thrilled to see it still going strong.

Whenever I restart the game, my progress in the single-player tournament is reset. All preferences are kept, though. I tried running the game through terminal, but unfortunately no error messages there.

**OS:** Fedora 32

**Comment by stijn-volckaert** [comment]
Your progress gets saved to User.ini whenever you complete a match. Can you open User.ini and check the contents of the [UTMenu.SlotWindow] section? If you see your progress there, then all you need to do is select the "Resume Saved Tournament" menu option when you restart the game. If you don't see any progress there, then there might be a permission problem.

**Comment by mrzapp** [comment]
@stijn-volckaert D'oy, that's just me forgetting how to operate the game. Sorry to take up your time, and again thank you for your hard work!
