### ISSUE TITLE
[469b] Invalid Actor Class

### ISSUE THREAD

**Issue by Chamberly** [OldUnreal/UnrealTournamentPatches#182]
I was connecting to servers and never did cache convert any files, some servers have some different files, I came across an issue on the OMA US Sniper Server due to Invalid Actor Classes in the log file, I could not connect to the server.

Report of the finding:
-Renamed Cache folder to Cache2
-Created a new Cache folder
Connected to the server just fine.
-2 files that have **different sizes** are:
25378BF44584EF794EAC6E86872140C4=WhoPushedMe.u
36393B8011D3E25E8000C1AE7129F8C6=Revenge.u
-Same GEN 1 packages.

WhoPushedMe.u's file inspection with the Hex Editor.
![image](https://user-images.githubusercontent.com/11419314/102715441-7bdb3c80-42a3-11eb-86c1-44a751ea1165.png)

[FileConflict.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5721012/FileConflict.zip)
The zip file contain 4 files, 2 from the OMA Server and 2 from unknown servers.

Note: Anthrax mentioned similar issue with EnhancedItems.u on Gustavo's Epic Showdown server.

**Comment by stijn-volckaert** [comment]
I don't think we can fix this. There are a couple of network-incompatible WhoPushedMe.u and EnhancedItems.u packages out there. They have matching GUIDs but are otherwise entirely incompatible.

**Comment by Chamberly** [comment]
Roger, I guess the idea now is to have someone datamine the rest of the conflict packages and add to this list.

Might as well mention the Won'tFix.txt containing issues and what should advise to use. I'll close this for time being and if anyone want to add to the list of file issue conflicts feel free to do so.
