### ISSUE TITLE
[469a] Uttitle.umx and Ending.umx not playing correctly after looping

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#185]
When Uttitle.umx is played in a second loop, the rhythm of the music slows down (with Ending.umx, the situation is similar, but playback is accelerated). Galaxy is not affected by this issue.
[Test map](https://github.com/OldUnreal/UnrealTournamentPatches/files/5759975/uttitle_bug.zip)

**Comment by stijn-volckaert** [comment]
This is already fixed in the 469b snapshots

**Comment by sn260591** [comment]
Can this be fixed for ALAudio? Or is it a libxmp issue?

**Comment by stijn-volckaert** [comment]
I suspect this is a libxmp problem
