### ISSUE TITLE
[469b-Preview-20201231] Monsterhunt scoreboard doesn't show all players

### ISSUE THREAD

**Issue by scottadkin** [OldUnreal/UnrealTournamentPatches#186]
On the destination unreal monsterhunt server some players are not shown on the scoreboard.

clip of it:
https://clips.twitch.tv/TenderRichToadShazBotstix

**Comment by Chamberly** [comment]
The same thing had happened to me when Hook's Deemer server was using Med's scoreboard.

![image](https://user-images.githubusercontent.com/11419314/106347837-7ce28f00-628f-11eb-9797-b2130b6551c1.png)

**Comment by sn260591** [comment]
This is the same problem as there  https://github.com/OldUnreal/UnrealTournamentPatches/issues/30. Server addresses is `89.163.162.10:7777` and `89.163.162.10:8888`.

**Comment by stijn-volckaert** [comment]
Confirmed and fixed for the next build
