### ISSUE TITLE
[469a] NPLoader crash after mapswitch

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#187]
Hi,
See the error message below that happened as the server just changed maps.

Win 10 Professional
v469a UT patch
D3D9 renderer
Cluster audio

![image](https://user-images.githubusercontent.com/59076225/104114230-ff4ee300-52cf-11eb-88ba-a7a94cf1b51f.png)

**Comment by stijn-volckaert** [comment]
Does your server turn ACE on and off?

**Comment by Chamberly** [comment]
I'm thinking he plays on some of these sniper servers in which they hardly turn it on and off. I used to get a ton of these crashes back in the days too.

**Comment by stijn-volckaert** [comment]
Noone has been able to reproduce this so I'm going to close the issue for now. Feel free to comment if you have any additional information
