### ISSUE TITLE
[469b-Preview-20201231] Setting AnnouncerVolume to 0 mutes the Player's 'voice'

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#188]
To reproduce 
1 Start UT and in the in-game menu go to Options->Preferences->Audio, move Announcer Volume slider to the left (0) - set the Sound Volume to whatever but ensure it is on 1 or more;
2 start a practice session - gametype DM - no bots;
3 activate Voice menu (V) - click on any sound (Ack, FF, Order, etc);
4 result - no sound/voice from the player is played and (obviously) there are no Announcer sounds (though I do get a start annoucement (One).

I'm using Galaxy and 2k4Sounds with a female Announcer .aux file. 

Do the same in 436 and the player's voice/sounds play OK. However the AutoTaunt on the Player killing something does not play. 

Text of what the Player says appears in the speech area in both 436 and 469b.

**Comment by stijn-volckaert** [comment]
This will be fixed in the next snapshot

**Comment by SeriousBuggie** [comment]
Fix confirmed for v469b RC6.
This issue need label `fixed for 469b`.
