### ISSUE TITLE
[469a] Music randomly stops

### ISSUE THREAD

**Issue by senneschall** [OldUnreal/UnrealTournamentPatches#19]
On Deck16][ the music on some rare occasion randomly stops and doesn't resume.
Here's all the log shows:
Log: ALAudio: playing Godown Go Down (Impulse Tracker 2.14v5 IT 1.00)
Warning: ALAudio: Musicbuffer error: Invalid Value
Dev: ALAudio: UpdateBufferThread terminated

**Comment by stijn-volckaert** [comment]
Is this on Windows or Linux?

**Comment by senneschall** [comment]
Linux, Ubuntu 20.04.1
I can't reproduce it on a constant basis, it happens on random and only very rarely

All log entries containing audio init:
`Log: Bound to ALAudio.so`
`Init: ALAudio: Trying to autodetect HRTF. Note: Autodetection may only work with USB headphones.`
`Init: ALAudio: We are using OpenAL device: OpenAL Soft `
`Init: ALAudio: OutputRateNum 5(44100 Hz) SampleRateNum 5 (44100 Hz)`
`Init: ALAudio: Audio hardware supports 255 mono (usually sound) and 1 stereo (usually music) sources.`
`Init: ALAudio: OpenALSoft extension ALC_SOFT_HRTF found.`
`Init: ALAudio: HRTF is enabled because it must be used on the device. This may be caused by a device that can only use HRTF, or other user configuration (like alsoft.ini or .alsoftrc) that forces HRTF to be used.`
`Init: OpenAL Effects extension version 1.0 found.`
`Init: ALAudio: EFX initialized.`
`Init: ALAudio: Version 1.1 ALSOFT 1.20.1 found`
`Init: ALAudio subsystem initialized.`

I'm using a compiled version of the latest libopenal1, but I report this error here because the log hints that ALAudio.so rather than libopenal1 contains the bug.

**Comment by sn260591** [comment]
It also sometimes happens on windows with the same log warnings on other maps.
