### ISSUE TITLE
[469a] Split ServerMove uses too recent ViewRotation

### ISSUE THREAD

**Issue by Deaod** [OldUnreal/UnrealTournamentPatches#190]
Function `SendServerMove` in PlayerPawn.uc uses `ViewRotation` when sending an update. `ReplicateMove` might call `SendServerMove` before `AutonomousPhysics`. `UpdateRotation` is called before `ReplicateMove`, so `ServerMove`s might occasionally receive a `ViewRotation` that doesnt match what the client was actually seeing.

Fix could be using `Move.SavedViewRotation` instead of `ViewRotation`.

**Comment by stijn-volckaert** [comment]
Fix merged
