### ISSUE TITLE
[469a] Map DM-FoT-Arken crash on directx10 renderer

### ISSUE THREAD

**Issue by Riccardoman** [OldUnreal/UnrealTournamentPatches#191]
![DM-FoT-Arken crash](https://user-images.githubusercontent.com/74624503/104811370-3c990080-57fb-11eb-84ca-fec93ae6b338.jpg)

Having this crash when I try to load the map with directx10 renderer (fresh install with only your patch applied and directx10 by kentie to get no texture filter look)
The map is loaded but after a few seconds the game crashes with this message

**Comment by stijn-volckaert** [comment]
This is almost certainly the same problem that caused D3D9Drv to crash. It is already fixed in the 469b snapshots.

**Comment by Riccardoman** [comment]
Nice ! Is there a link to the new version?

**Comment by Riccardoman** [comment]
Can't wait for the new patch! Thank you very much for your efforts OU team

**Comment by stijn-volckaert** [comment]
Does this still happen in 469b?

**Comment by Riccardoman** [comment]
No but I get huge stuttering while looking at certain parts of the map. Not sure if it's caused by my specs but I have other very detailed maps and they don't have the same frame drops that this map has

**Comment by stijn-volckaert** [comment]
The D3D10 renderer is far slower than the D3D9 and OpenGL renderers. Maybe you should try those instead.

**Comment by sn260591** [comment]
> No but I get huge stuttering while looking at certain parts of the map.

This is due to the very high detail of the bsp geometry.
