### ISSUE TITLE
[469a] if server is full then reconnect at spectator instead of kick?

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#194]
Just wondering if in case of Server being full , if instead of disconnecting client with a "Connection Failed" message perhaps we could attempt a reconnection as a Spectator?

**Comment by Chamberly** [comment]
Only if the server have enough slot left for allowed spectator. If the spectator slot is set to 0 or set to admin only, those permission are likely checked by Nexgen or ASC, etc. instead. Sometimes Nexgen give the user an option to automatically kick and to either leave or reconnect as a spectator.

**Comment by SeriousBuggie** [comment]
Doubtful change. For example I want play now and try connect to server. Currently I get message about server full. All ok.
With this change I goes as spectator which not I want. Maybe I want search another server for actaully play, not watch?
But now I need goes to player settings and disable spectator, and check another server. Very annoying.

Possible usage can be with popup dialog, "server full, try connect as spectator" which must appear (if possible) after check for free spectator slots). if not possible check it just be only prompt about that.

**Comment by stijn-volckaert** [comment]
There is no clean way to implement this without breaking behavior mods rely upon
