### ISSUE TITLE
[469a] Team color sometimes incorrect in HUD

### ISSUE THREAD

**Issue by jharrison03** [OldUnreal/UnrealTournamentPatches#196]
In CTF (possibly other team matches, but the only game type I've played thus far with this client), sometimes the team color of the silhouette in the upper-right of the HUD is the color of the opposite team.  ie.  If you're on the blue team, the silhouette displays as red, and vice-versa  This never happens when you initially join a server, but the color switchover can occur after a map change or when the teams are sometimes re-balanced mid-game.

EDIT:  This is with the Linux client, 469a, from here: https://github.com/OldUnreal/UnrealTournamentPatches/releases/download/v469a/OldUnreal-UTPatch469a-Linux.tar.bz2

**Comment by SeriousBuggie** [comment]
Need more info about issue. Possible screenshots with it.
Will be good if be exactly steps for reproduce it.

**Comment by stijn-volckaert** [comment]
We have not been able to reproduce this problem
