### ISSUE TITLE
[469a] black flash when hitting alt + a

### ISSUE THREAD

**Issue by nurps** [OldUnreal/UnrealTournamentPatches#197]
Screen flashes black when I press alt + a. Does it happen for anybody else?

**Comment by stijn-volckaert** [comment]
What are your ALT and a keys bound too?

**Comment by nurps** [comment]
a = moving forward, alt = strafe right

**Comment by stijn-volckaert** [comment]
That shouldn't cause any issues. I cannot reproduce the problem locally. Do you have any external tools running that react to the ALT+a shortcut?

**Comment by nurps** [comment]
Don't think so, it also only happens during gameplay, while a is doing the black frame if alt is pressed already, if I start with a and then add alt it doesn't happen.

Also if I have the text chat open alt + a ist als safe to press.

**Comment by stijn-volckaert** [comment]
We have not been able to reproduce this
