### ISSUE TITLE
[469a] Inconsistent local directory handling with Linux client

### ISSUE THREAD

**Issue by jharrison03** [OldUnreal/UnrealTournamentPatches#199]
On a Linux system, the home directory of the user that launches the client should be used to store locally accumulated data and configuration files, and that data should be stored in a single directory.

The following files and directories are of concern here --

```
~/.loki/ut/
        System  
                (469a client creates an empty directory here)
~/.utpg/
        Cache
                cache.ini
                *.uxx
        System
                udemo.ini
                UnrealTournament.log
                        (Both files created by client)
~/.local/games/ut/
        (The installation directory, on my system.  - This could be /usr/local/games/ut, as well)
        System 
                 UnrealTournament.ini
                 User.ini
                         (Both files exist after installation, but (should be) copied to user's "UT" directory upon first run).
                 ucc.log
                        (Created by client)
         

```
All of these files, should probably be under the ~/.utpg heierachy, I think -- User.ini and UnrealTournament.ini should probably be copied to ~/.utpg/System on first run.

**Comment by jharrison03** [comment]
What I recommend, is that ~/.loki/System directory is not created --

and --

UnrealTournament.ini and User.ini are copied into ~/.utpg/ on first run, and ucc.log is created in the same directory as the former two files.

**Comment by stijn-volckaert** [comment]
Are you using an external launcher that did not come with the 469 patch? The 469 client never created the .loki directory, and neither did the (unreleased) 468 client. I believe UTPG changed .loki into .utpg for the 440 patch but I do not have the full commit history so I can't confirm.

ucc.log does not get created by the client either. This is the log file for ucc-bin.

I agree that the handling of UnrealTournament.ini and User.ini is somewhat counterintuitive. Will see if we can do something about this without breaking tools that rely on the current behavior.

**Comment by stijn-volckaert** [comment]
The 469c client should behave exactly as you described
