### ISSUE TITLE
[469a] False-positive malware detection

### ISSUE THREAD

**Issue by Kenon2** [OldUnreal/UnrealTournamentPatches#20]
My antivirus found a Trojan in the archive https://github.com/OldUnreal/UnrealTournamentPatches/releases/download/v469a/OldUnreal-UTPatch469a-Windows.zip :

System\libcurl.dll - UDS:Trojan-Spy.Win32.Zbot

**Comment by senneschall** [comment]
This has been reported before, it's a known false alarm, see #15

**Comment by Dr-Flay** [comment]
I am wondering about that build of libcurl @stijn-volckaert 
It is half the size of the new build. Did you build from source or use their prebuild ?
The VT results for the 2 DLLs are worlds apart, and as both Bitdefender and Kaspersky think the last one was bad that puts me on edge, but when 24 AV are showing warnings it is worth dealing with it and changing the distro even if it is a false positive.
v7.71.1 with the patch
https://www.virustotal.com/gui/file/48a4f584ce9689f26d71d7845f1423225484e68af3f9b1b31992f087d7a9e948/detection
v7.72.0 from the site
https://www.virustotal.com/gui/file/09447d1df767b3c4a63167437af53095e42d48853ef73275534cff6658b52ade/detection

**Comment by rc6750** [comment]
For what it's worth Vipre AV also flipped out on this file.

**Comment by stijn-volckaert** [comment]
We used the pre-built version from the curl web site. I will update the patch to include the newer version of libcurl, which hopefully triggers fewer false positive detections

**Comment by stijn-volckaert** [comment]
Correction: I misremembered this. We did NOT use the pre-built version from the libcurl website as that one depends on a couple of libraries (such as libssl) that we do not need. I built the lib we distributed myself and only enabled WinSSL support. I just compiled libcurl 7.72.0 with the same settings and submitted the dll to virustotal. This one still gets flagged by Bkav, but does not trigger any other malware scanners.

**Comment by Dr-Flay** [comment]
That makes sense. Many of the AVs will claim that a new variant of something they know to be clean is a trojan.
This is becoming more of a pain regularly. For example just change 1 byte in a known clean file and many AVs will freak out.
It is likely that the new build will start showing more warnings on the VT page over the next few days as the actual AV get a sample.

All we can do is advise people of the situation and that this is known annoyance, and to feel free to submit false-positive reports to whatever vendor they are using.

It may help to give a link in the docs to the source used for curl in this repo, so people can examine it if they feel they need to.

**Comment by michkot** [comment]
So if I understand correctly, if I do not mind the file size, I can just use https://curl.se/windows/ built binaries as a replacement (using just the libcurl.dll and the curl-ca-bundle.crt)? ;)

**Comment by stijn-volckaert** [comment]
Indeed. You will need to install a couple of extra dependencies if you use the official version, though. The one we shipped with the patch uses windows' tls/crypto libraries. The official libcurl uses open-source alternatives

**Comment by michkot** [comment]
> 
> 
> Indeed. You will need to install a couple of extra dependencies if you use the official version, though. The one we shipped with the patch uses windows' tls/crypto libraries. The official libcurl uses open-source alternatives

Well, they say the build is " statically linked ". So I would assume the .dll should work out of the box. But! It it seems to be linked **dynamically** to OpenSSL (or maybe they somehow pack the OpenSSL dependency into the .exe) based on the DLL dependency inspection, so the 32bit version of OpenSSL's libs libcrypto and libssl (link to the binaries is included on the curl build page) is needed too ;). Thanks for the warning ;)
