### ISSUE TITLE
[469a/469b] WinXP GUI skin makes menus disappear completely

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#206]
I was messing around with the GUI skins yesterday, and I've noticed that the GUI skin "WinXP" makes all of the menus disappear completely: the main menu, the console, stuff like that. It becomes impossible to do anything in the game unless I change the "LookAndFeelClass" back to normal in the .ini.
![20210203173423_1](https://user-images.githubusercontent.com/71798183/106823361-6ac56f80-6646-11eb-9675-27cffcc2abd2.jpg)
![20210203173430_1](https://user-images.githubusercontent.com/71798183/106823366-6e58f680-6646-11eb-8f17-4b997f39ecec.jpg)
Notice how you can see the mouse pointer has changed in the second screenshot, as if the console was there.

I've tried changing my renderers, and I've switched consoles from XConsole to back to the original, and the problem persisted.

Windows 10 Home
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by stijn-volckaert** [comment]
Can you check if this still happens in 469b? If so, can you please upload your UnrealTournament.log file?

**Comment by SeriousBuggie** [comment]
Need add links for this very one version which cause problems.

I use version from here: http://www.koehler-homepage.de/Wormbo/download.html#GUI
[UnrealXP110.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6134732/UnrealXP110.zip)

All fine in v469b:
![scr_1615636905](https://user-images.githubusercontent.com/70026933/111029286-a94c0800-8404-11eb-9f8f-3327e0c33fe4.png)

**Comment by SeriousBuggie** [comment]
According to this post: https://forums.beyondunreal.com/threads/ut-forgotten-classics-bonus-pack-dev-thread-v2.191781/page-4#post-2470033
I find [FCBPAlphaMilestone5-ZIP.zip](http://www.ut-files.com/index.php?dir=ToStore/&file=FCBPAlphaMilestone5-ZIP.zip) here: http://www.ut-files.com/index.php?dir=ToStore/

For this huge ZIP (300 MB) I extract [RaBit.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6134755/RaBit.zip)
Now I can test and with WinXP skin all fine in v469b:
![scr_1615638468](https://user-images.githubusercontent.com/70026933/111029957-583e1300-8408-11eb-983a-cc0df5ce6f51.png)

**Comment by DarkBeemo** [comment]
> According to this post: https://forums.beyondunreal.com/threads/ut-forgotten-classics-bonus-pack-dev-thread-v2.191781/page-4#post-2470033
> I find [FCBPAlphaMilestone5-ZIP.zip](http://www.ut-files.com/index.php?dir=ToStore/&file=FCBPAlphaMilestone5-ZIP.zip) here: http://www.ut-files.com/index.php?dir=ToStore/
> 
> For this huge ZIP (300 MB) I extract [RaBit.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6134755/RaBit.zip)
> Now I can test and with WinXP skin all fine in v469b:
> ![scr_1615638468](https://user-images.githubusercontent.com/70026933/111029957-583e1300-8408-11eb-983a-cc0df5ce6f51.png)

It still doesn't work.

**Comment by SeriousBuggie** [comment]
You need provide more info about that, because for me all work.
Possible you miss textures or something. In any case need show your UnrealTournament.log file and window log after your change skin.

**Comment by DarkBeemo** [comment]
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6179396/UnrealTournament.log)
Here is my UnrealTournament.log file. I don't have a Window.log file, so I don't really know what else you need.

**Comment by SeriousBuggie** [comment]
```
Warning: Failed to load "osxBackgroundChanger": Can't find file for package "osxBackgroundChanger"..
Warning: Failed to load "RaBit": Can't find file for package "osxBackgroundChanger"..
Warning: Failed to load "Class RaBit.RBt_WinXP": Can't find file for package "osxBackgroundChanger"..
```
So package not load at all. Nothing wrong with path v469 - you just miss some files.
Look like you miss this file: https://unrealarchive.org/files/9d/9decf8d7df5cbb9a71840058d1783eaadcc7eebb.html

**Comment by DarkBeemo** [comment]
> ```
> Warning: Failed to load "osxBackgroundChanger": Can't find file for package "osxBackgroundChanger"..
> Warning: Failed to load "RaBit": Can't find file for package "osxBackgroundChanger"..
> Warning: Failed to load "Class RaBit.RBt_WinXP": Can't find file for package "osxBackgroundChanger"..
> ```
> 
> So package not load at all. Nothing wrong with path v469 - you just miss some files.
> Look like you miss this file: https://unrealarchive.org/files/9d/9decf8d7df5cbb9a71840058d1783eaadcc7eebb.html
> 
> Also: https://www.unrealsp.org/viewtopic.php?t=3334&p=64354
> And you even can just put "osxBackgroundChanger" in google search bar...

Well, installing that one file fixed the menus not appearing, except now the menu SFX sound "far away." Strangely, 469a does not give me the same problem, and the SFX sound "normal."

469b:
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6186279/UnrealTournament.log)

469a:
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6186280/UnrealTournament.log)

**Comment by SeriousBuggie** [comment]
Bad idea mess issues to one. Better create new one and this close with original title.

Any way, problem with sound cause by change from v469a:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UMenu/UMenuGoldLookAndFeel.uc#L965
```
simulated function PlayMenuSound(UWindowWindow W, MenuSound S)
{
	switch(S)
	{
	case MS_MenuPullDown:
		W.GetPlayerOwner().PlaySound(sound'WindowOpen', SLOT_Interface);
		break;
	case MS_MenuCloseUp:
		break;
	case MS_MenuItem:
		W.GetPlayerOwner().PlaySound(sound'LittleSelect', SLOT_Interface);
		break;
	case MS_WindowOpen:
		W.GetPlayerOwner().PlaySound(sound'BigSelect', SLOT_Interface);
		break;
	case MS_WindowClose:
		break;
	case MS_ChangeTab:
		W.GetPlayerOwner().PlaySound(sound'LittleSelect', SLOT_Interface);
		break;
	}
}
```
Here added `SLOT_Interface` to all `PlaySound` calls.
WinXP (and Unreal XP) skin do not extends exists default skin. It is re-implemented as new skin with own copy `PlayMenuSound` function. Copy from v436 which not contains this `SLOT_Interface` parameter. So sound play in default slot, not in interface slot.
