### ISSUE TITLE
[469a] Win95 GUI skin abnormalities

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#207]
The top left and right corners of the menu while using the Win95 GUI skin is black, or cut off, while the bottom left and right corners display correctly. The menu backgrounds are also completely black as well, making the black text unreadable. Switching renderers and consoles do not help. Also, the sound effects for scrolling over options/selecting/clicking do not play while using the skin.
![20210203173407_1](https://user-images.githubusercontent.com/71798183/106830226-41f7a700-6653-11eb-823b-c8379e8b893a.jpg)

Windows 10 Home
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by stijn-volckaert** [comment]
Can you check if this still happens in 469b? If so, can you please upload your UnrealTournament.log file?

**Comment by SeriousBuggie** [comment]
You talk about this: https://forums.beyondunreal.com/threads/ut-forgotten-classics-bonus-pack-dev-thread-v2.191781/ ?

> Win95
> 
> Author: Epic Games
> Description: Unfinished as of yet, hidden in game files, this makes UWindows look very, VERY basic (as in Windows 95, without the famous BSOD/DLL hell combo though). Still, this requires finishing.

Screenshot from this page:
![Screen](http://i261.photobucket.com/albums/ii46/RoninMastaFX/UT%20FCBP/Pictures/umenu_win95.jpg)

Look like this stuff not work even in v436 (and I think not work at all).
So it is not a v469b issue.

**Comment by SeriousBuggie** [comment]
See this: https://github.com/OldUnreal/UnrealTournamentPatches/issues/206#issuecomment-798288285_
Here you can find [RaBit.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6134755/RaBit.zip)
From which I get next screen:
![scr_1615638634](https://user-images.githubusercontent.com/70026933/111030028-b10dab80-8408-11eb-8a7f-00887b41e9f0.png)

But as Isay, it is not a patch issue. Skin is broken or unfinished.

**Comment by DarkBeemo** [comment]
> But as I say, it is not a patch issue. Skin is broken or unfinished.
Thanks for clearing everything up!
