### ISSUE TITLE
[469a] No URenderDevice function extensions possible (virtual functions and subclass inheritance)

### ISSUE THREAD

**Issue by ut99shadow** [OldUnreal/UnrealTournamentPatches#210]
Hey guys,
you're doing a great job with the new UT 469 patch so far, however - I have ONE huge problem:

Prior to 469a I could use an own base Render Device (still deriving from URenderDevice of course) to add new functionality before coding the actual Render Device implementation for OpenGL, DirectX and so on: 

My Subclass derivation was : 
URenderDevice -> UAnotherBaseRenderDevice (new function declarations) -> UImplementedRenderDevice

This simple mechanic has become impossible now. I always get a critical error, when trying to access UImplementedRenderDevice. I simply cant access virtual functions declared in UAnotherBaseRenderDevice anymore. I'm totally limited to the URenderDevice standard interface.

Critical Error, that appears when adding an Actor, which is accessing a new function of UAnotherBaseRenderDevice / UImplementedRenderDevice:
History: PushTriangle <- UEditorEngine::Draw <- (Cam=U2Viewport0, Flags=1993 <- UWindowsViewport::Repaint <- UEditorEngine::RedrawLevel ...

What's causing this - the render proxy mechanic? Why cant I access new virtual functions? How to fix this - or is there maybe any workaround?

Best regards,
Shadow

**Comment by CacoFFF** [comment]
We have implemented an extended render device interface for UT v469b, the render device proxy was created with the intention of allowing legacy render devices to run on the improved render interface (which requires the extended render device interface).
Because the proxy is a derivate of the v469 render device interface, it will not contain the additional virtual functions in your render implementation.

As a 'temporary' workaround you may have to iterate over the object list to find your UAnotherBaseRenderDevice typed renderer and keep it referenced to directly operate with it.

**Comment by stijn-volckaert** [comment]
Hi Shadow, you might need the 469 SDK to fix the problem. We will publish it soon. If you want to get access immediately, then please ping AnthraX on the ut99.org Discord.

**Comment by ut99shadow** [comment]
Thank you both for your swift and competent reply. I'm very very looking forward to this SDK! It can wait until it's officially released. Thank you :)

**Comment by stijn-volckaert** [comment]
Note that there are several custom renderers (D3D10Drv, D3D11Drv, VulkanDrv) that were not linked against 469b either and they work fine. This might, therefore, be somewhat of an edge case. I suspect our renderer proxy doesn't like the fact that your base renderer is also a proxy. Either way, the problem will probably fix itself if you do subclass URenderDeviceOldUnreal469. I am preparing a CMakeLists.txt for the SDK right now.

**Comment by stijn-volckaert** [comment]
We will publish an SDK along with the 469c release
