### ISSUE TITLE
[469a] DM-Coke][ critical error (not DM-Coke)

### ISSUE THREAD

**Issue by TankBeef** [OldUnreal/UnrealTournamentPatches#211]
I get this error when playing Helen's DM-Coke][ (The smaller version DM-Coke works fine so far)
![Coke  Critical Error](https://user-images.githubusercontent.com/78271695/108135246-2a2a1500-708e-11eb-8f68-c993bdc3dde4.jpg)

**Comment by OjitroC** [comment]
I get the same error in that map with 469b [snapshot 30/01/2021] using D3D9 - I don't get it with 436 using OpenGL.

**Comment by CacoFFF** [comment]
Are you using high res textures?

**Comment by TankBeef** [comment]
> Are you using high res textures?

Yes

**Comment by CacoFFF** [comment]
I applied a crashfix for high res textures, so this is likely to solve the problem then.
Will mark as fixed.

**Comment by TankBeef** [comment]
> I applied a crashfix for high res textures, so this is likely to solve the problem then.
> Will mark as fixed.

Great

**Comment by OjitroC** [comment]
Has the fix been applied to the 04 February 2021 snapshot? As the map crashes with that.

**Comment by CacoFFF** [comment]
No, this was done yesterday
