### ISSUE TITLE
[469b] Camera view attached to a mover no longer moves

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#213]
In the BunnyTrack map [CTF-BT-Ocarina_of_Time(EZ)](http://www.ut-files.com/index.php?dir=Maps/BunnyTrack/&file=ctf-bt-Ocarina_of_Time%28EZ%29.zip), there's a section which uses a Camera View actor attached to a large mover.

When entering the camera's trigger zone (or whatever) the player sees a top-down view of themselves from the camera. 

**Expected result:**
The camera moves along with a mover.

**Actual result:**
In server v469b, however, the camera actor no longer moves with the mover and remains static while the mover slides off-screen.

I set a checkpoint at the relevant location in the map, which is below:
`pLoc="-1928.453613,-11739.292969,-548.200012",pRot="128,46334,65536"`

**Comment by stijn-volckaert** [comment]
confirmed. We are investigating.

**Comment by Chamberly** [comment]
Just tested with Higor's update as of now, it works online but offline it does not work.
