### ISSUE TITLE
[469b-Preview-20201116] UnrealEd crashes with critical error when attempting to collapse properties

### ISSUE THREAD

**Issue by sapphire-bt** [OldUnreal/UnrealTournamentPatches#214]
Unfortunately I'm not able to replicate the exact steps, but it always seems to happen when I've expanded a few properties and then try to collapse them, like so:

![2021-02-25 00_40_44](https://user-images.githubusercontent.com/33162278/109085870-6569bb00-7702-11eb-875c-2165d8dbb6cd.png)

This frequently results in the following critical error:

![2021-02-25 00_38_17](https://user-images.githubusercontent.com/33162278/109085969-a366df00-7702-11eb-95a4-e71cc6655d55.png)

**Comment by stijn-volckaert** [comment]
Which build is this?

**Comment by sapphire-bt** [comment]
469b, Nov 16 2020 Preview.

**Comment by stijn-volckaert** [comment]
Ok, we already have a fix for this crash. It will be included in the 469b release.

**Comment by sapphire-bt** [comment]
Ah, great news. Apologies for any wasted time.
