### ISSUE TITLE
[469a][Linux] Using quickload command results in crash

### ISSUE THREAD

**Issue by gkepka** [OldUnreal/UnrealTournamentPatches#215]
Same result when trying to use `open ?load=1` command. Relevant log excerpt:

```Critical: appError called:
Critical: fread failed: BufferCount=1024 Error=1
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing USDLClient::ShutdownAfterError
Exit: ALAudio subsystem shut down.
Exit: UALAudioSubsystem::ShutdownAfterError
Exit: UOpenGLRenderDevice::ShutdownAfterError
Critical: Propagating Error
Warning: Failed to load '..\Save': Throwing C++ exception for error logging
Warning: Failed to load 'Level None.MyLevel': Throwing C++ exception for error logging
```
**Steps to reproduce**:
1. Open singleplayer map, e.g., Vortex2 from Unreal (remember to copy sound files too) using `open Vortex2?Difficulty=2?Class=UnrealI.MaleOne` (or use Oldskool mod according to [this](https://forums.beyondunreal.com/threads/linux-oldskool-load-game-fails.151594/) forum post)
2. Use `quicksave` command or `savegame 1`
3. Open saved game using `quickload` or `open ?load=1` (accordingly to previously used command)

**Comment by stijn-volckaert** [comment]
I wasn't able to reproduce this exact crash, but I fixed two other bugs that broke game loading/saving on Linux and macOS. Are you on Discord somewhere so I can link you to a test build?

**Comment by gkepka** [comment]
Dr.Strangehonk#8566, you can contact me on UT99.org server.
