### ISSUE TITLE
[469b-RC3] TacticalOps 3.5 Server crash

### ISSUE THREAD

**Issue by krisudxc** [OldUnreal/UnrealTournamentPatches#216]
Crash can occur when following gamemode files are present in server System folder: TOAS.u, TODM.u, TOMA2.u and Midnightassault.u.
I do not have any references to these .u files in my server.ini yet they get loaded just because they are present in System folder.

I'm not even sure if these game modes are supported by TO3.5 but wanted to report the issue since someone else might have similar issues with some game modes.

What I have found out is that ucc-bin handle count increase after every map change. Eventually handle count reaches around 1000+ and then the server crashes. 

I traced the issue on linux with: lsof -p PID_here | grep -c 'ucc-bin'

**Comment by stijn-volckaert** [comment]
Do you have any additional info on this? The crash log and lsof output would be useful.

Also, do you happen to have .int files that match the names of those game mode files you listed?

**Comment by krisudxc** [comment]
Hi

Please find log from: [https://drive.google.com/file/d/1RARcivIHGiugh5har3ZQzAJ3F09RgrMp/view?usp=sharing](url)
Just reviewed the log. It might be nexgen that is the problem and not the engine. 
I did not record any lsof output. Int files are present on server. 
The mutator pack in question can be found at: https://www.moddb.com/mods/tacticalops-assault-on-terror/downloads/to-mod-pack

**Comment by stijn-volckaert** [comment]
Indeed. This doesn't seem like an engine problem to me, but rather a mod that sends the server into a map switch loop. I'm going to close this one.
