### ISSUE TITLE
[469b RC4] Default music start play if press Escape when no music play during match

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#217]
If you press Escape on map without music or when music muted, start play default music "utmenu23.utmenu23".
This caused by UTConsole code:

	event Tick( float Delta )
	{
		local Music MenuSong;

		Super.Tick( Delta );
		if (Root == None)
			return;
		if (Root.GetPlayerOwner().Song == None)
		{
			MenuSong = Music(DynamicLoadObject("utmenu23.utmenu23", class'Music'));
			Root.GetPlayerOwner().ClientSetMusic( MenuSong, 0, 255, MTRAN_Fade );
		}
	}

I think need reduce this music reset to special cases, like this done here:

	if( !bQuickKeyEnable && 
	    ( Left(Viewport.Actor.Level.GetLocalURL(), 9) ~= "cityintro" || 
	      Left(Viewport.Actor.Level.GetLocalURL(), 9) ~= "utcredits") )
		Viewport.Actor.ClientTravel( "?entry", TRAVEL_Absolute, False );

It can be some thing like that:

		if (Root.GetPlayerOwner().Song == None && ( Left(Viewport.Actor.Level.GetLocalURL(), 9) ~= "cityintro" || 
	      Left(Viewport.Actor.Level.GetLocalURL(), 9) ~= "utcredits" || Left(Viewport.Actor.Level.GetLocalURL(), 5) ~= "entry" ) )
		{
			MenuSong = Music(DynamicLoadObject("utmenu23.utmenu23", class'Music'));
			Root.GetPlayerOwner().ClientSetMusic( MenuSong, 0, 255, MTRAN_Fade );
		}

Because is map author want silence on some part better prefer it even if user press Escape during game.

**Comment by TankBeef** [comment]
Yes, this happens to me also. Very annoying. Is it a 469 issue?

**Comment by SeriousBuggie** [comment]
No. This is issue exists even in v436.

**Comment by dizzy-egg** [comment]
Massive +1 for this issue being fixed! 

@SeriousBuggie Thank you for highlighting this long-standing issue.

A while ago we made a basic mod to "fix" this problem on our server but the fix no longer works properly with 469b so a proper solution would be vastly preferred.

@TankBeef If you want a short-term hacky solution to stop this happening then try the mod:
https://github.com/bunnytrack/BTNetNoMenuMusic

**Comment by TankBeef** [comment]
> Massive +1 for this issue to be fixed!
> 
> @SeriousBuggie Thank you for highlighting this long-standing issue.
> 
> A while ago we made a basic mod to "fix" this problem on our server but the fix no longer works properly with 469b so a proper solution would be vastly preferred.
> 
> @TankBeef If you want a short-term hacky solution to stop this happening then try the mod:
> https://github.com/bunnytrack/BTNetNoMenuMusic

Oh nice, thanks for sharing dizzy-egg, going to test it right now 😁

**Comment by Chamberly** [comment]
I remember there was a few map that doesn't have any UT music defined on it and pressing ESC played default music, very annoying.

Meanwhile it'd be great if it randomize music playlist and play those instead, straight outta Music folder.

**Comment by CacoFFF** [comment]
Applied

**Comment by TankBeef** [comment]
> Applied

Alright!!! Thanks 😁

**Comment by SeriousBuggie** [comment]
Fix confirmed for v469b RC6.

**Comment by an-eternity** [comment]
This bug was useful for some people in some cases/circumstances... But fixing it rather than preserving it was the right way.
Randomized playlist (with option to enable/disable) as suggested above would be nice solution...

**Comment by SeriousBuggie** [comment]
Randomize playlist is not a good. Music can changed during map play.
Not usual for DM, but usual for MH, for example.
And it can be silence for some map parts.

And because of that mod `BTNetNoMenuMusic` above can not work properly. it take in account only Song set in Level properties. not current actual Song.
