### ISSUE TITLE
[469b-RC4] OpenGL Canvas.DrawPortal often draw players model on full screen without respect portal size

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#219]
Reproduce:
1. Start any map. Team game, 7 bots, mutator CoopTranslocator:
https://ut99.org/viewtopic.php?f=7&t=14012
2. Select cooptranslocator (press 1).
3. Press fire for start preview translocate target.
4. You can see render of big player models periodically.

Video: https://streamable.com/0moxh9

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
