### ISSUE TITLE
[469a] Menus with duplicate entries

### ISSUE THREAD

**Issue by TrollDecker** [OldUnreal/UnrealTournamentPatches#22]
Heyo,

This new patch is an absolute godsend, and I've yet to run into any game-breaking issues yet, but there is a slight quirk that's baffling me, in the form of duplicate items in various menus such as player settings, match setup and mutator selection.

A few examples I've found are below:
![Screenshot_2020-09-24_16-47-46](https://user-images.githubusercontent.com/4513715/94169744-1552a800-fe87-11ea-8568-f919ca405f2f.png)
![Screenshot_2020-09-24_16-48-08](https://user-images.githubusercontent.com/4513715/94169745-1683d500-fe87-11ea-9c0b-b4b8cb8ed5c7.png)
![Screenshot_2020-09-24_16-48-42](https://user-images.githubusercontent.com/4513715/94169747-171c6b80-fe87-11ea-8d93-b46cff117c8b.png)
![Screenshot_2020-09-24_16-50-02](https://user-images.githubusercontent.com/4513715/94169754-184d9880-fe87-11ea-977a-57a3f08b64a7.png)

I'm using Debian Stretch and, of course, the Linux x64 version of the patch, if that helps. It's also a fresh install, extracted from the GOG GOTY installer before I dropped the patch in.

Again, nothing game-breaking, as far as I can tell, just a bit weird. :thinking:

**Comment by stijn-volckaert** [comment]
Doh! This is one of the unfortunate side-effects of developing a game on Windows. It looks like you have a couple of duplicate .int files in your system folder (i.e., they're the same int file but their names differ only in casing). On Windows, this wouldn't happen since the file system is case-insensitive and the duplicate .int files could not exist there. On Linux, you will have to clean up the duplicates yourself. We'll see if we can filter out duplicates ourselves for the next patch.

**Comment by TrollDecker** [comment]
Ah, that seems to have done the trick, thanks. :smile: :+1:

**Comment by shrimpza** [comment]
For what it's worth in case anyone else ends up here in the same situation, when I "converted" my Wine install to native by zapping the Windows files after copying in the Linux patch, I did the following to clean up the duplicate files:

```bash
$ find System/ -type f -printf "%T@\t%p\n" | sort -f -k2 -k1 | cut -f2 | uniq -id | xargs rm
```

GNU versions of all the above tools, running on Debian Sid.

Pretty much:
 - find all files in `System` and print them in "timestamp (tab) filename" format
 - sort them by name (`-k2`, insensitive) and them timestamp (`-k1`) 
 - identify the files with duplicates (hence the sort by name then timestamp - `-d` needs them to be adjacent)
 - delete the older of the two files

**Comment by kvbev** [comment]
This issue also happens for me when the game is installed to ~/.utpg, i have checked no duplicate files are present using above.

if i rename the game folder to .ut the issue goes away, but once I change the folder name back to .utpg the issue reappears.

no launch flags are being used.

**Comment by stijn-volckaert** [comment]
This will be fixed in 469b.

**Comment by gargul03** [comment]
Good, just wanted to add another person experiencing the same issue: [LINK](https://ut99.org/viewtopic.php?p=123270#p123270) :

> Raynor : I found other issues such as duplicate menu entires

**Comment by gargul04** [comment]
Good, I've just wanted to add another player  experiencing the same issue:

> https://ut99.org/viewtopic.php?p=123270#p123270 : Raynor : 
> I found other issues such as duplicate menu entires

**Comment by garry-ut99** [comment]
I've just wanted to add another person which has been experiencing the issue:

> https://ut99.org/viewtopic.php?p=123270#p123270 : Raynor : I found other issues such as duplicate menu entires
