### ISSUE TITLE
[469a] Add functionality to copy surface properties from a brush and paste them to a different brush

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#220]
Default UEd functionality allows you to "copy" and "paste" the *texture* of a brush face on to a different brush face using the `Alt` key plus left or right click. 

However, it does not copy any of the surface properties such as texture scale, directionality, etc. 

It would be extremely useful to add the ability to copy and paste all surface properties from one brush to another.

**Comment by SeriousBuggie** [comment]
Since #1220 resolved, I guess this one resolved too. You can copy surface with properties via CTRL+ALT + RMB/LMB in scope of loaded map. Can't copy that between editors run or different maps.
