### ISSUE TITLE
[469a] CTRL+SHIFT+D hotkey doesn't work in UnrealEd

### ISSUE THREAD

**Issue by LDinos** [OldUnreal/UnrealTournamentPatches#221]
Very minor issue, the Duplicate hotkey doesn't seem to work in 469a

**Comment by SeriousBuggie** [comment]
In v436 you can use `Ctrl+Shift+D` or `Ctrl+W` for Duplicate Actor.
![img](https://user-images.githubusercontent.com/70026933/111033674-0e125d00-841b-11eb-927b-dbadae031ae9.png)

In v469 you need use `Ctrl+D`.
![img](https://user-images.githubusercontent.com/70026933/111033647-efac6180-841a-11eb-9b2b-12712e9aacd4.png)

**Comment by SeriousBuggie** [comment]
Related to #12
