### ISSUE TITLE
[Mac][469b] Unable to launch

### ISSUE THREAD

**Issue by MLipfert1** [OldUnreal/UnrealTournamentPatches#226]
Hi,

today I tried to launch the new version 469b on macOS 11.2.3 Big Sur, but the startup attempt stops with the following message:

<img width="409" alt="Bildschirmfoto 2021-03-11 um 16 22 46" src="https://user-images.githubusercontent.com/63508182/110810653-4af91b00-8286-11eb-883e-eb07d990ecb1.png">

The message says, that the application is corrupted and cannot be started. It is recommended to move it to the trash.

The former version 469a works fine. My machine is a MacBook Pro 16" (Core i9, 16GB RAM, Radeon Pro 5500M).

Is there a known workaround?

Best regards,
Moritz

**Comment by stijn-volckaert** [comment]
Could you try to download the dmg file again please? It sounds like it got corrupted on the way from my hard drive to github.

**Comment by MLipfert1** [comment]
I downloaded it again from the release page - same result.

**Comment by MLipfert1** [comment]
This issue is related to Apple's GateKeeper. I am now able to start the application after typing in the following line in the console: "xattr -d com.apple.quarantine /path/to/app". Thanks anyway!

**Comment by stijn-volckaert** [comment]
It looks like this is happening because our app bundle isn't notarised. We'll get this fixed ASAP!

**Comment by stijn-volckaert** [comment]
I've notarized the app bundle, reuploaded the installer, and updated the installation instructions. Feel free to comment on the issue again if you run into any more trouble.

**Comment by MLipfert1** [comment]
Works fine now, thanks! One minor remark: The readme file inside the dmg should also be updated. It is still suggesting to copy the data files to the app bundle. ;-)
