### ISSUE TITLE
[469b] OpenAL version incompatibilities between OS

### ISSUE THREAD

**Issue by senneschall** [OldUnreal/UnrealTournamentPatches#227]
With 469b, you've upgraded libopenal to 1.21.1 for Windows, but kept it on 1.18.2 for Linux (can't test MacOS)

The problem is: openal changed the mhr file format (needed for HRTF) with the introduction of 1.19. So now you need two versions of the mhr files for win/linux.

Maybe just upgrade the linux version, too?

**Comment by stijn-volckaert** [comment]
Will do!

**Comment by stijn-volckaert** [comment]
Could you check if this binary works for you please? 
[libopenal.so.1.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6135126/libopenal.so.1.zip)

**Comment by senneschall** [comment]
Works without any problems for me (ubuntu20.04). Thanks!
