### ISSUE TITLE
[469b] still crashing when trying to use Team Orbit models as bots in normal DM or MH multiplayer/practice games

### ISSUE THREAD

**Issue by gattovicentino** [OldUnreal/UnrealTournamentPatches#229]
This issue should be related  to this one: [469a] UMenu.UMenuVideoClient.ScaleCombo missing #123, that was closed but the issue is still present in UT v.469b.
It crashes when I try to start a practice/multiplayer game where some of the bots are TeamOrbit NeoCairo models (it crashes when loading). 
(It works in v.436 and 451).
From the log:

Log: Failed import: ObjectProperty ObjectProperty UMenu.UMenuVideoClientWindow.ScaleCombo (file ../System/UMenu.u)
Critical: ULinkerLoad::VerifyImport
Critical: ValidateImports
Critical: ULinkerLoad::Verify
Critical: ULinkerLoad::ULinkerLoad
Critical: UObject::GetPackageLinker
Critical: UObject::StaticLoadObject
Critical: (Core.Class TeamOrbit.SelkBot NULL)
Critical: (DM-XC-EpicTownV2A.XBotsBotRandomInfo1 Botpack.ChallengeBotInfo.CHGetBotClass)
Critical: (DM-XC-EpicTownV2A.DeathMatchPlus0 Botpack.DeathMatchPlus.SpawnBot)
Critical: (DM-XC-EpicTownV2A.DeathMatchPlus0 Botpack.DeathMatchPlus.AddBot)
Critical: UObject::ProcessEvent
Critical: (DeathMatchPlus DM-XC-EpicTownV2A.DeathMatchPlus0, Function Botpack.DeathMatchPlus.PostLogin)
Critical: Accept
Critical: ULevel::SpawnPlayActor
Critical: MatchViewportsToActors
Critical: (DM-XC-EpicTownV2A.unr)
Critical: ClientInit
Critical: UGameEngine::LoadMap
Critical: LocalMapURL
Critical: UGameEngine::Browse
Critical: ClientTravel
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop

**Comment by stijn-volckaert** [comment]
No such issues here. Team Orbit: Neo Cairo works perfectly on 469b. Could it be that your UnrealTournament.ini points to the wrong System folder? Another possibility is that you accidentally installed 469a's UMenu.u on top of 469b's UMenu.u.

**Comment by gattovicentino** [comment]
I just tried to apply the patch again, but this time on the same HDD where the original v 469a folder was. (First try was on another HDD, different drive letter). So yes, it was a path matter. Everything is OK now, you can close this issue. Sorry and thank you :-)
