### ISSUE TITLE
[469a] OpenAL - TriggerLights with sound cause sound distortion

### ISSUE THREAD

**Issue by RoelerCoaster** [OldUnreal/UnrealTournamentPatches#23]
I was playing an old map of mine using OpenAL as audio renderer, when I suddenly noticed some strange sound distortion in one place of the map. Occasionally I would hear a loud, "crackling" buzz, mostly when moving around.

I tried tracking down the cause by extracting parts of the map and removing unnecessary stuff, and I think it may be caused by sounds added to TriggerLights. This is a technique where the sound is only emitted when the TriggerLight is on, so it is a nice way to turn a light and sound effect on/off at the same time, for example when creating something like lasers.

I created a small example map that shows this behavior when flying around:
[sound-distortion.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5278554/sound-distortion.zip)

It only happens with OpenAL, Cluster and Galaxy are fine.

Some other information that may be relevant:

**OS:** Windows 10
**UT version**: 469a (release)
**Soundcard**: Realtek ALC892 (on motherboard)

**Comment by CacoFFF** [comment]
Fixed for v469b
