### ISSUE TITLE
[469b] Opening ogg file in Music Browser causes crash

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#235]
The title says it all - the music file I tried to open comes from UB01-Xeops.unr (I think) - I have played quite a lot of the map and had no problems though I don't have the music volume up so can't confirm if it played).  I wasn't doing anything else in the Editor, just trying to open this music file. 

This is the crash entry in the log

Critical: UEditorEngine::UpdateBrushBuilders
Critical: UEditorEngine::SafeExec
Critical: (LOAD FILE="C:\UnrealTournament\Music\zClarity.ogg")
Critical: UEditorEngine::SafeExec
Critical: (OBJ LOAD FILE="C:\UnrealTournament\Music\zClarity.ogg")
Critical: UEditorEngine::Exec
Critical: (OBJ LOAD FILE="C:\UnrealTournament\Music\zClarity.ogg")
Critical: WBrowserMusic::OnCommand
Critical: WM_HSCROLL
Critical: MessagePump
Critical: MainLoop

**Comment by OjitroC** [comment]
The Editor also crashes trying to open a .mp3 - this music file certainly came with the map noted above.  

The crash entry in the log

DevLoad: Loading: Package Xeops-01-Xenofish-Submerge
Critical: appError called:
Critical: Assertion failed: InPos<=Size [File:C:\GameDev\utpg\Core\Inc\FFileManagerWindows.h] [Line: 90]
Critical: Windows GetLastError: Success. (0)
Exit: Executing UObject::StaticShutdownAfterError
Exit: UGalaxyAudioSubsystem::ShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
Log: DirectDraw End Mode
Exit: UD3D9RenderDevice::ShutdownAfterError
Exit: UD3D9RenderDevice::ShutdownAfterError
Exit: UD3D9RenderDevice::ShutdownAfterError
Exit: UD3D9RenderDevice::ShutdownAfterError
Exit: UD3D9RenderDevice::ShutdownAfterError
Exit: UD3D9RenderDevice::ShutdownAfterError
Critical: FArchiveFileReader::Seek
Critical: ULinkerLoad::Seek
Critical: FUnrealfileSummary<<
Critical: LoadSummary
Critical: ULinkerLoad::ULinkerLoad
Critical: UObject::GetPackageLinker
Critical: UObject::LoadPackage
Critical: UEditorEngine::SafeExec
Critical: (LOAD FILE="C:\UnrealTournament\Music\Xeops-01-Xenofish-Submerge.mp3")
Critical: UEditorEngine::SafeExec
Critical: (OBJ LOAD FILE="C:\UnrealTournament\Music\Xeops-01-Xenofish-Submerge.mp3")
Critical: UEditorEngine::Exec
Critical: (OBJ LOAD FILE="C:\UnrealTournament\Music\Xeops-01-Xenofish-Submerge.mp3")..
Critical: WBrowserMusic::OnCommand
Critical: WM_HSCROLL
Critical: MessagePump
Critical: MainLoop

**Comment by ZeroKhan1** [comment]
I guess. You have to import the OGG into UMX, you can't just expect it to play the OGG directly?

**Comment by OjitroC** [comment]
Could be - I assumed that this "Enabled Ogg Vorbis support in all audio drivers and in the UnrealEd music browser" in the Release Notes meant that Ogg could be opened and played.

**Comment by stijn-volckaert** [comment]
With the Ogg Orbis support code, all audio drivers can now play back ogg files embedded in umx packages. You cannot open ogg files directly, and you will never be able to do so. If you want to use ogg music in your level, you will have to import it into a umx package first.

That said, opening unsupported files should not crash UEd. It should simply show an error. Will fix ASAP.

**Comment by stijn-volckaert** [comment]
Update: opening unsupported files _IS_ supposed to crash UEd but the error you should be seeing is different from the one you posted. I restored the original error message for 469c.

As for using ogg music, see my comment above.
