### ISSUE TITLE
[469b] Voice menu broken for big voice packs + flood in log from UTMenu.SpeechChildWindow.BeforePaint

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#237]
Example of issue:
![scr_1615744359](https://user-images.githubusercontent.com/70026933/111079709-d4695100-8503-11eb-867e-31f77a171db6.png)

Voice pack for reproduce: https://www.mediafire.com/file/gl4nhdxeb5iufwg/BrasilTauntV1.zip/file

Fix:
Replace line https://github.com/Slipyx/UT99/blob/a26a3359704873df5a24d0b241a32ca5fc36a8b7/UTMenu/SpeechChildWindow.uc#L132
```
	for(i=OptionOffset; i<MinOptions+OptionOffset; i++)
```
to
```
	for(i=OptionOffset; i<Min(MinOptions+OptionOffset, NumOptions); i++)
```
Now all fine:
![scr_1615746664](https://user-images.githubusercontent.com/70026933/111079797-3aee6f00-8504-11eb-93f5-0563f4f4f8c1.png)

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
