### ISSUE TITLE
[469b] Escape in voice menu can produce strange state

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#239]
Reproduce:
1. Press and hold `V` on ut logo (for show voice menu).
2. Select any item for appear submenu.
3. Press `Escape`.
4. Release 'V`.

Expected result: Return back to initial state (mouse cursor not visible, `V` - open voice menu and so on).
Actual result: Mouse cursor visible, Click on screen do nothing. 

Exit from this state: press `Escape` again or press `Tilde` (for bring console).

**Comment by stijn-volckaert** [comment]
Returning to the initial state was not really practical. Instead, I just made the speech window absorb the escape key while it is open.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
