### ISSUE TITLE
[469a] Changes made to the game settings while UnrealEd is open are reverted when UnrealEd is closed

### ISSUE THREAD

**Issue by RoelerCoaster** [OldUnreal/UnrealTournamentPatches#24]
It appears that when you launch the game while UnrealEd is open and make changes to the settings, then these changes are kept as long as UnrealEd remains open, but they are all reverted once you close UnrealEd. 

I just did a little test by changing the following settings in-game while the editor was open:
- brightness
- volume
- selected gametype in "start practice session"
- selected mutators

All those changes were reverted when closing the editor.

I am not 100% sure if this is a new issue, because I do remember having the same/similar issue years ago on v436. But at some point the problem disappeared, but I don't know why exactly. It may have been related to upgrading to windows 10, because I saw in the release notes that windows 10 had a crash on UnrealEd shutdown.

Some information that may be relevant:
**OS:** windows 10
**UT version:** v469a (release)

**Comment by SeriousBuggie** [comment]
Bug exists in v436. 
Explanation is simple: UnrealEd store INI files in memory and when close, write them to disk with overwrite any changes, which can be here.

**Comment by stijn-volckaert** [comment]
I don't think we can fix this one without redesigning the config file system.

**Comment by SeriousBuggie** [comment]
Fixed in v469c. At least on some level.
