### ISSUE TITLE
Allow server game to start with only one player

### ISSUE THREAD

**Issue by jrmain** [OldUnreal/UnrealTournamentPatches#241]
As a server admin, I find it very helpful to be able to start a round when I'm the only person connected. It's also tough to be the first player to join a server if you can't do anything until a second player joins. In UT2004 this is possible, but not in UT99.

**Comment by scottadkin** [comment]
You can start a server game with only 1 player(I'm guessing not for LMS), some mods prevent you from being able to start a match without another person being in the server.

I just checked, if you have tournament checked, you can't start a team game without there being more than one player, if you untick the option you can start games anytime. I've never ran into the problem on my dev server but on a hunch I started a server with tournament mode enabled and it prevents me from starting a match on my own. 

![Shot00297](https://user-images.githubusercontent.com/25456246/111871400-bb3c2680-8981-11eb-8dc6-563bc146a528.png)

**Comment by jrmain** [comment]
Well holy crap, that worked. Thanks!! I feel really dumb, not knowing that for so many years.
