### ISSUE TITLE
Level Properties -> Song can not be selected

### ISSUE THREAD

**Issue by ClippingError** [OldUnreal/UnrealTournamentPatches#244]
When a new song is chosen as audio track of a map the Use button does not change the selected track. If the button is used nothing happens.

**Steps to reproduce:**
- Install Unreal Tournament v469b Patch Release
- Load any random stock map. 
- Open the music browser and and load any music file which is not the currently selected track for the opened map
- Select the loaded track 
- Go into the "Level Properties -> Audio" setting and select "Song"
- Make sure the loaded audio track is still selected in the Music browser and press "Use" in Level Properties

**Comment by OjitroC** [comment]
Not much help to you but that works fine for me - opened CTF-Coret, chose a umx named Dreams and added to 'Song' by pressing 'Use'.

Anything in the Editor.Log that might indicate why a .umx can not be added to a map?

**Comment by ClippingError** [comment]
I deleted the file and performed the described steps again. This is the log from just hits:

Log: Log file open, 03/17/21 22:33:30
Init: Name subsystem initialized
Init: Version: 469
Init: Compiled: Sep 22 2020 12:41:55
Init: Command line: 
Init: Base directory: C:\UnrealTournament-469\System\
Init: Character set: Unicode
Log: Bound to Editor.dll
Log: Bound to Core.dll
Log: Bound to Engine.dll
Log: Bound to Render.dll
Log: Bound to Window.dll
Init: Object subsystem initialized
Init: Computer: DESKTOPL8J6E1N
Init: User: Admin
Init: Memory total: Phys=4194303K Pagef=4194303K Virt=4194176K
Init: Working set: 32000 / 159000
Init: Timer Frequency=2793.548780 MHz - Timing Source = RDTSC
Init: CPU Page size=4096, Processors=8
Init: CPU Detected: PentiumPro-class processor (GenuineIntel)
Init: CPU Features: CMov FPU RDTSC PAE MMXSSE KNI
Init: Unreal engine initialized
Log: Bound to Cluster.dll
Init: Cluster initialized.
Init: Transaction tracking system initialized
Log: Bound to Fire.dll
Log: Bound to IpDrv.dll
Log: Bound to UWeb.dll
Log: Bound to WinDrv.dll
Init: Enhanced Pointer Precision Enabled - Mouse info: 6 10 1
Init: Initializing DirectDraw
Init: DirectDraw drivers detected:
Init:    display (Primärer Anzeigetreiber)
Init: DirectDraw: Enumerated Display Modes:
Init: DirectDraw initialized successfully
Init: Disabling DirectInput for Editor
Init: Client initialized
Init: Lighting subsystem initialized
Init: Rendering initialized
Init: Editor engine initialized
Log: Startup time: 1.814650 seconds
Log: Testing supported renderers for level Viewports
Init: Input system initialized for U2Viewport0
Log: Opened viewport
Warning: Failed to load 'NULL': Can't resolve package name
Warning: Failed to load 'Class None.': Can't resolve package name
Warning: Can't resolve package name
Warning: Can't resolve package name
Log: Bound to SoftDrv.dll
Log: This is a legacy render device.
Init: Input system initialized for U2Viewport1
Log: Opened viewport
Warning: Failed to load 'NULL': Can't resolve package name
Warning: Failed to load 'Class None.': Can't resolve package name
Warning: Can't resolve package name
Warning: Can't resolve package name
Log: This is a legacy render device.
Init: Input system initialized for U2Viewport2
Log: Opened viewport
Log: Bound to XOpenGLDrv.dll
Dev: XOpenGL: SetRes
Log: XOpenGL: Creating new OpenGL context.
Init: XOpenGL: Successfully initialized.
Init: XOpenGL: DesiredColorBits: 32
Init: XOpenGL: DesiredDepthBits: 24
Init: XOpenGL: Setting PixelFormat: 7
Init: GL_VENDOR     : NVIDIA Corporation
Init: GL_RENDERER   : Quadro K610M/PCIe/SSE2
Init: GL_VERSION    : 3.3.0 NVIDIA 385.73
Init: GL_SHADING_LANGUAGE_VERSION    : 3.30 NVIDIA via Cg compiler
Init: OpenGL 3.3 context initialized!
Log: XOpenGL: OpenGL debugging disabled.
Log: XOpenGL: WGL_EXT_swap_control found.
Log: XOpenGL: WGL_EXT_swap_control_tear found.
Log: XOpenGL: MaxTextureImageUnits: 32
Log: XOpenGL: MaxImageUnits: 8
Warning: OpenGL debugging extension not found!
Log: XOpenGL: MaxCombinedTextureImageUnits: 192
Log: XOpenGL: MaxElementsVertices: 1048576
Log: XOpenGL: MaxUniformBufferBindings: 84
Log: XOpenGL: MaxDualSourceDrawBuffers: 1
Log: XOpenGL: MaxTextureSize: 16384
Log: XOpenGL: MaxAnisotropy = (4.000000/16.000000)
Log: XOpenGL: NumAASamples: (0/64)
Log: XOpenGL: GL_NUM_EXTENSIONS found: 335
Log: XOpenGL: GL_MAX_CLIP_DISTANCES found: 8
Log: XOpenGL: Flush
Log: XOpenGL: Setting VSync: On
Log: XOpenGL: SyncToDraw disabled
Log: XOpenGL: No compiler messages for xopengl/DrawSimple.vert
Log: XOpenGL: No compiler messages for xopengl/DrawSimple.frag
Log: XOpenGL: No compiler messages for xopengl/DrawTile.vert
Log: XOpenGL: No compiler messages for xopengl/DrawTile.geo
Log: XOpenGL: No compiler messages for xopengl/DrawTile.frag
Log: XOpenGL: No compiler messages for xopengl/DrawGouraud.vert
Log: XOpenGL: No compiler messages for xopengl/DrawGouraud.geo
Log: XOpenGL: No compiler messages for xopengl/DrawGouraud.frag
Log: XOpenGL: No compiler messages for xopengl/DrawComplexSinglePass.vert
Log: XOpenGL: No compiler messages for xopengl/Draw

**Comment by stijn-volckaert** [comment]
The build date in your log file suggests that you installed the 469a patch and not the 469b patch. The bug you're describing was fixed for 469b

**Comment by ClippingError** [comment]
I downloaded the zip archive of the b patch and copied it over the existing a patch. 
How can I check what version I really have running?

**Comment by OjitroC** [comment]
Have a look at the date it was compiled - 469b should have the date as Mar  6 2021 16:04:23.

This is yours in the Editor log
Init: Version: 469
Init: Compiled: Sep 22 2020 12:41:55

Run the game and check the date in the log.  In-game the release version is given in the menu bar at the top - on the right of the bar.

**Comment by ClippingError** [comment]
I re installed the patch and now it works. My bad. Sorry for bothering. Thread can be closed
