### ISSUE TITLE
[469b] Log errors when opening in-game menu Options -> Preferences

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#245]
Using EXUOpenGL/OpenGL/D3D9, resolution 1920 x 1080, GUI scaling 1.5.

After opening the Options -> Preferences menu and perhaps altering a setting under one of the tabs or even just opening and closing the Preferences menu, I've noticed these two error lines in the log

Error: UTCustomizeClientWindow Transient.UTCustomizeClientWindow0 (Function UMenu.UMenuCustomizeClientWindow.Created:03DA) Accessed array 'LabelList' out of bounds (100/100)
Error: UTCustomizeClientWindow Transient.UTCustomizeClientWindow0 (Function UMenu.UMenuCustomizeClientWindow.Created:03E6) Accessed array 'LabelList' out of bounds (100/100)

Just the two lines and always those two lines when doing that action.  There's no visible or practical impact on the game however - nonetheless I thought it prudent to draw attention to them.

**Comment by SeriousBuggie** [comment]
At line https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UMenu/UMenuCustomizeClientWindow.uc#L111
```
LabelList[I] = Mid(LabelList[I], j+1);
```
Before that 
```
	for (I=0; I<ArrayCount(AliasNames); I++)
	{
		if(AliasNames[I] == "")
			break;
```
So if you have 100 filled aliases you face this issue.

Fix - delete line:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UMenu/UMenuCustomizeClientWindow.uc#L111
```
LabelList[I] = Mid(LabelList[I], j+1);
```
it is just copy paste thing from code above.

**Comment by stijn-volckaert** [comment]
Merged Buggie's fix for 469c.
