### ISSUE TITLE
[469b] XOpenGL Flash effects impairs visibility 

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#246]
Screenshots for comparison:

### D3D9
![Shot00043](https://user-images.githubusercontent.com/10724977/111646523-c755a600-8812-11eb-9cd2-e1aab0df333b.jpg)

### XOpenGL
![Shot00042](https://user-images.githubusercontent.com/10724977/111646577-d3416800-8812-11eb-9d64-87cf1d4d91bd.jpg)

**Comment by stijn-volckaert** [comment]
The Unreal guys made some adjustments to screen flash. Could you test the 469c release version to see if this solves your issue?

**Comment by sn260591** [comment]
I confirm the issue is solved.
