### ISSUE TITLE
[469b] SniperRifle toggle zoom when hold alt fire and use primary fire

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#249]
Reproduce:
1. Start any map in the practice mode.
2. Type in console `loaded`
3. Switch to the sniper rifle.
4. Press and hold alt fire.
5. Shoot with primary fire with big interval.

Expected result: Zoom stop at maximal value.
Actual result: Zoom toggled after each shot (after reach max value), like you press and hold alt fire again and again. One shot cancel zoom, second one enable it. And so on.

**Comment by stijn-volckaert** [comment]
We tried to fix this in the base SniperRifle class for 469c but had to revert the fix due to incompatibilities with custom sniperrifle mods. We will include our fixed class in the optional compatibility package that will ship with 469c instead.
