### ISSUE TITLE
[469a] FOV resets itself spectating offline with bots

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#25]
The FOV resets itself to the default value (90) when spectating with bots. This happens in every game type, with or without mutators. This does not happen online with real players. JSYK, the FOV that I use is a value of 105, or to be more precise, 106.25. I did not have this problem in 436 or 451.

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by Chamberly** [comment]
Ah, so when you are in spectate and left clicking or f5ing it does reset the fov on the bots. I got the same result as above. I'm a fov 110 user.

**Comment by SeriousBuggie** [comment]
If you see code for spectator https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/CHSpectator.uc#L30
You can see special function `FixFOV` which especially do described things. It is called on many place on this class. Nearly on each case when you spectate.
IDK for what that. But this is not accidental behavior. It is intended by some reasons.

**Comment by stijn-volckaert** [comment]
Indeed. This was done by design and it also happened in 436/451. You can easily override this behavior in a mod, however.
