### ISSUE TITLE
[469b] Skin FCommandoSkins_Negaverse_Titus not work

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#251]
Reproduce:
1. Start MP server when your skin [FCommandoSkins_Negaverse_Titus](https://github.com/OldUnreal/UnrealTournamentPatches/files/6175169/FCommandoSkins_Negaverse_Titus.zip) (with `ServerPackages=FCommandoSkins_Negaverse_Titus`) of course.
2. Use `behindview 1` for view your skin.

Expected result: Skin work fine.
Actual result: Skin not loaded. Loaded default skin. In the log appear message:
```
ScriptLog: Attempted to use illegal skin from package FCommandoSkins_Negaverse_Titus_fix for FCommando
ScriptLog: Failed to load FCommandoSkins_Negaverse_Titus_fix.ttus4Titus so load FCommandoSkins_Negaverse_Titus.ttus4
Warning: Failed to load "Texture FCommandoSkins_Negaverse_Titus.ttus4": Object not found: Texture FCommandoSkins_Negaverse_Titus.ttus4.
Warning: Failed to load "Texture FCommandoSkins_Negaverse_Titus.ttus2T_0": Object not found: Texture FCommandoSkins_Negaverse_Titus.ttus2T_0.
ScriptLog: Failed to load FCommandoSkins_Negaverse_Titus.ttus2T_0 so load FCommandoSkins_Negaverse_Titus.ttus2
ScriptLog: Attempted to use illegal skin from package FCommandoSkins_Negaverse_Titus.ttus for FCommando
ScriptLog: Failed to load FCommandoSkins_Negaverse_Titus.ttus.ttus1 so load FCommandoSkins.cmdo1
Warning: Failed to load "Texture FCommandoSkins.ttus4": Object not found: Texture FCommandoSkins.ttus4.
ScriptLog: Failed to load FCommandoSkins.ttus4 so load FCommandoSkins.cmdo4
```
v436 skin load fine with next log:
```
Warning: Failed to load 'Texture FCommandoSkins_Negaverse_Titus.ttus2T_0': Failed to find object 'Texture FCommandoSkins_Negaverse_Titus.ttus2T_0'
ScriptLog: Failed to load FCommandoSkins_Negaverse_Titus.ttus2T_0 so load FCommandoSkins_Negaverse_Titus.ttus2
```

Some discussion about that: https://ut99.org/viewtopic.php?f=13&t=14468

**Comment by OjitroC** [comment]
I don't know if this is of any help but the 'Attempted to use illegal skin' issue does not appear to be related solely to 469b but applies more generally - see these posts, some of which predate 469b - it appears to be more related to the server setup?
https://ut99.org/viewtopic.php?f=7&t=5640&p=72101&hilit=illegal+skin#p72101
https://ut99.org/viewtopic.php?f=64&t=5624&p=75054&hilit=illegal+skin#p75054
https://ut99.org/viewtopic.php?f=64&t=14146&p=123085&hilit=illegal+skin#p123085
https://ut99.org/viewtopic.php?f=13&t=903&p=7348&hilit=illegal+skin#p7348

**Comment by SeriousBuggie** [comment]
Related to:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Pawn.uc#L957
```
		bProscribed = !CheckValidSkinPackage(pkg, MeshName);
		if ( bProscribed )
			log("Attempted to use illegal skin from package "$pkg$" for "$Meshname);
```
CheckValidSkinPackage:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Pawn.uc#L305
```
native static final function bool CheckValidSkinPackage(string SkinPack, string MeshName);
```
So all goes to native side and I can not say exactly what happen here and why it not work anymore.

**Comment by SeriousBuggie** [comment]
I add debug output after line
`log("Attempted to use illegal skin from package "$pkg$" for "$Meshname);`
as:
`log("Dbg skin from package "$pkg$" for "$Meshname);`
What i get on v436 for this skin:
```
Dbg skin from package FCommandoSkins_Negaverse_Titus.ttus for FCommando
```
What I get on v436:
```
ScriptLog: Dbg skin from package FCommandoSkins_Negaverse_Titus for FCommando
ScriptLog: Dbg skin from package FCommandoSkins_Negaverse_Titus for FCommando
ScriptLog: Dbg skin from package FCommandoSkins_Negaverse_Titus for FCommando
ScriptLog: Dbg skin from package FCommandoSkins_Negaverse_Titus for FCommando
```
So problem in Group name which appear in pkg.

Solution: strip group name from package name.
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Pawn.uc#L955
```
		SkinItem = SkinActor.GetItemName(SkinName);
		pkg = Left(SkinName, Len(SkinName) - Len(SkinItem) - 1);
```
replace to
```
		pkg = Left(SkinName, InStr(SkinName, "."));
```
Now all fine:
```
ScriptLog: Dbg skin from package FCommandoSkins_Negaverse_Titus for FCommando
ScriptLog: Dbg skin from package FCommandoSkins_Negaverse_Titus for FCommando
```

**Comment by SeriousBuggie** [comment]
But it is not proper solution. It is only eliminate consequences.
Real reason is SkinName built with use Texture Group Name. What not happen before.
So this thing can break something else somewhere else.

**Comment by SeriousBuggie** [comment]
After further investigation I found v436 is fine when pass Group name to `CheckValidSkinPackage`. So problem in that function on native side.
Workaround above is fine because `CheckValidSkinPackage` used only here.

**Comment by SeriousBuggie** [comment]
As temporary solution you can install this fixed Engine.u on server:
[Engine_469b_fix_skins.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6309733/Engine_469b_fix_skins.zip)

**Comment by stijn-volckaert** [comment]
I would recommend not to do this since this could create problems for future package conformations. I'll upload updated .u files to the repo later today. They will also include this fix
