### ISSUE TITLE
[469b] UseAA has no effect with OpenGL

### ISSUE THREAD

**Issue by mkardi** [OldUnreal/UnrealTournamentPatches#260]
I have UseAA=True under OpenGLDrv.OpenGLRenderDevice and anti aliasing is not applied at all.
Also tested XOpenGL and same exact issue. Anisotropic filtering works fine though.
Is it bug or am I missing something? Running it under linux (debian 10)

**Comment by senneschall** [comment]
Can confirm this on Ubuntu 20.04
This issues was first reported on the oldunreal forums. Good to see it here, too.

**Comment by CacoFFF** [comment]
For v469c OpenGLDrv will allow the user to select how to apply color correction.
By default it'll use a framebuffer for postprocessing that.
The advantage is that framebuffers can also be used to apply anti-aliasing regardless of the platform the game is running on.
