### ISSUE TITLE
[469a/469b] Brock and Xan do not move in the CityIntro

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#261]
Brock and Xan do not move and make gestures at each other at the end of the CityIntro like intended.

Both versions of 469 give me this problem. In version 436, things work properly.

https://www.dropbox.com/s/t4qmlxu8qerx8bw/UnrealTournament.ini?dl=0
https://www.dropbox.com/s/u3h4bdhsav67dau/User.ini?dl=0
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6186591/UnrealTournament.log)
Above are my .inis and my .log.

Windows 10 Home
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by SeriousBuggie** [comment]
Can confirm issue for me.
v436 is fine for me too.

**Comment by SeriousBuggie** [comment]
Build second test map: [DM-!!!!!intro_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6187228/DM-.intro_bug.zip)
Here present original IntroBoss with IntroDude and MyIntroBoss with MyIntroDude. This classes simple stub expands original.
Both triggered by same trigger.
Stubs works. Original no.
So problem in original classes from Botpack.u.

**Comment by SeriousBuggie** [comment]
Reason:
State not work if use same name as class.
This work:
```
//=============================================================================
// MyIntroDude.
//=============================================================================
class MyIntroDude expands IntroDude;

Auto State() MyIntroDude1
{

function Trigger( actor Other, pawn EventInstigator )
{
	if (AnimSequence=='stand')
		GotoState( 'MyIntroDude1','shake');
	else
		GotoState( 'MyIntroDude1','stand');
}

shake: 
Log("shake");
	Disable('Trigger');
	PlayAnim('shake',1);
	FinishAnim();
	Enable('Trigger');	
	Stop;

stand:
Log("stand");
	Disable('Trigger');
	PlayAnim('stand',1);
	FinishAnim();
	Sleep(1.0);
	Enable('Trigger');
	Stop;
	
Begin:
Log("Begin");
	PlayAnim('stand',0.4);
}
```
This not work:
```
//=============================================================================
// MyIntroDude.
//=============================================================================
class MyIntroDude expands IntroDude;

Auto State() MyIntroDude
{

function Trigger( actor Other, pawn EventInstigator )
{
	if (AnimSequence=='stand')
		GotoState( 'MyIntroDude','shake');
	else
		GotoState( 'MyIntroDude','stand');
}

shake: 
Log("shake");
	Disable('Trigger');
	PlayAnim('shake',1);
	FinishAnim();
	Enable('Trigger');	
	Stop;

stand:
Log("stand");
	Disable('Trigger');
	PlayAnim('stand',1);
	FinishAnim();
	Sleep(1.0);
	Enable('Trigger');
	Stop;
	
Begin:
Log("Begin");
	PlayAnim('stand',0.4);
}

```

**Comment by mkardi** [comment]
Can confirm same with 469b

**Comment by CacoFFF** [comment]
Oh dear, this one was probably implemented back when UTPG backported some UE2 fixes into the game for v440/v451.

**Comment by CacoFFF** [comment]
@SeriousBuggie try this to see if it works:
```
	if (AnimSequence=='stand')
		GotoState( 'Auto','shake');
	else
		GotoState( 'Auto','stand');
```

**Comment by SeriousBuggie** [comment]
Yep. This is work.

**Comment by stijn-volckaert** [comment]
Confirmed. We will fix this natively

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
