### ISSUE TITLE
[469b] Minigun sounds weak

### ISSUE THREAD

**Issue by mkardi** [OldUnreal/UnrealTournamentPatches#263]
Minigun firing sound is low compared to other weapson sounds with OpenAL.
It is especialy noticeable when two or more players are firing them simultaneously so they kind of fade/blend.

**Comment by stijn-volckaert** [comment]
This was probably a side effect of a bug that caused the minigun primary fire sound to play from the wrong location. This should be fixed in the next patch.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
