### ISSUE TITLE
[469b] Error in enforcer, Line 821: Can't assign Const variables

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#266]
In 469b this part:
https://github.com/Slipyx/UT99/blob/a26a3359704873df5a24d0b241a32ca5fc36a8b7/Botpack/enforcer.uc#L770
```
		if ( SlaveEnforcer != None )
		{
			if ( SlaveEnforcer.bBringingUp )
			{
				SlaveEnforcer.bBringingUp = false;
				SlaveEnforcer.PlaySelect();
			}
			SlaveEnforcer.RenderOverlays(Canvas);
		}
```
Rewrite as:
```
		if ( SlaveEnforcer != None )
		{
			if ( SlaveEnforcer.bBringingUp )
			{
				SlaveEnforcer.bBringingUp = false;
				SlaveEnforcer.PlaySelect();
			}
			bSlaveCalcDrawOffsetFOV = SlaveEnforcer.bCalcDrawOffsetFOV;
			SlaveEnforcer.bCalcDrawOffsetFOV = bCalcDrawOffsetFOV;
			SlaveEnforcer.RenderOverlays(Canvas);
			SlaveEnforcer.bCalcDrawOffsetFOV = bSlaveCalcDrawOffsetFOV;
		}
```
But `bCalcDrawOffsetFOV` is const:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Inventory.uc#L23
```
var transient const bool bCalcDrawOffsetFOV;  // v469: set during player owner's RenderOverlays
```

So when I try compile Engine.u from UnrealEd I get 
`Log: Error in enforcer, Line 821: Can't assign Const variables`

**Comment by an-eternity** [comment]
There are many classes in various mods where constant is being used as a variable (for example, mods that contain fixes for the problem with Decal in Fog Zone in old UT versions...).
This means compiler has an option to bypass errors of this type...
