### ISSUE TITLE
New effects don't appear on some renderers

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#27]
I've noticed that when using the alternate fire of the Sniper Rifle (zooming in), the sniper's crosshair is a bit of a higher quality in OpenGL and XOpenGL than of Direct3D 9 or Direct3D 11. I assume this is supposed to be a new feature, but it seems to be bugged. The first image is the sniper crosshair in OpenGL/XOpenGL, and the second image is in Direct3D 9/Direct3D 11. 
![94089285-6c4d7400-fdd8-11ea-9681-b2fc2e5002ef](https://user-images.githubusercontent.com/71798183/94209632-60be8380-fe92-11ea-9842-79a21bfa0cba.jpg)
![94089279-6788c000-fdd8-11ea-8321-8e9eb318816c](https://user-images.githubusercontent.com/71798183/94209638-62884700-fe92-11ea-9343-eeb5faf5876f.jpg)

My .ini: [Beemo'sINI.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5279761/Beemo.sINI.zip)

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by stijn-volckaert** [comment]
Confirmed. The higher-quality sniper reticle uses a texture format which we don't support in all renderers yet. This will probably be fixed in 469b.

**Comment by DarkBeemo** [comment]
> Confirmed. The higher-quality sniper reticle uses a texture format which we don't support in all renderers yet. This will probably be fixed in 469b.
Thank you.
