### ISSUE TITLE
[469b] Players rotate on feign death if move look

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#271]
On dedicated server (Listen not tested) v469b players which do feign death another players see as rotate and look up and down.

Author player (if use `behindview 1`) see own body not movable, but another players - no.

Reproduce:
1. Enter on any 469b server.
2. Make Feign death.
3. Move look and please another player tell about move body or not.

Expected result: Body not move.
Actual result: Body rotate and look up or down.

**Comment by SeriousBarbie** [comment]
I noticed also rotating player on server 469b in end screen where all players should have been frozen.

**Comment by SeriousBuggie** [comment]
On server 469b you can even fire with redeemer on altfire and guide rocket after game end.

**Comment by SeriousBarbie** [comment]
> On server 469b you can even fire with redeemer on altfire and guide rocket after game end.

That was possible in v451, too.

**Comment by CacoFFF** [comment]
Fixed in next patch.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
