### ISSUE TITLE
[469b] UnrealEd does not keep selected grid size

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#272]
Open UnrealEd, change the grid size with the combo box on bottom bar and close UnrealEd. If you open the editor again, the grid size is at previous value. (I noticed that UnrealEd.ini has not changed.)

BTW: What entry in UnrealEd.ini describes the current grid size?

**Comment by SeriousBuggie** [comment]
> What entry in UnrealEd.ini describes the current grid size?

`UnrealTournament.ini`
```
[Editor.EditorEngine]
GridSize=(X=16.000000,Y=16.000000,Z=16.000000)
```

**Comment by SeriousBarbie** [comment]
Pfff. Thanks, I really expected all setting fur the editor in UnrealEd.ini. Because my UnrealTounament.ini is write protected, this setting couldn't be stored.
