### ISSUE TITLE
[469b] UnrealEd: Selecting a window should bring it to top if already open

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#274]
The subject tells it already: if I choose any item in UnrealEd from Menu>View that is assigned to a window, is should get on top of all shown windows if it is already open (BringWindowToTop).  (At least I expect this and code it in this way in my programs.)

V436 behaves the same.

**Comment by SeriousBuggie** [comment]
Duplicate of #3.

**Comment by stijn-volckaert** [comment]
Confirmed. This is a duplicate of #3 (which will be fixed in 469)
