### ISSUE TITLE
[469b] Voice menu target submenu not work properly for teams with more than 10 players

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#275]
![scr_1616797140](https://user-images.githubusercontent.com/70026933/112698376-39bd2a80-8e92-11eb-90b7-701731f84060.png)
Reproduce:
1. Start team game with 15 bots on same team.
2. Open voice menu as on screen.

Expected result: Menu paged by 10 items.
Actual result: See picture.

v469: bugged, started from 11 players in team.
v436: bugged, started from 9 players in team.

**Comment by OjitroC** [comment]
Another 'odd' thing is that you appear to have 24 bots on the same team - since you are giving orders to 24 bots?  Plus there is no no. 1 between 0 Aryss and 2 Arachne nor, indeed, a no. 1 above 2 Nikita.

**Comment by SeriousBuggie** [comment]
Actually on screen 31 bots on my team. But this need tune 
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TeamGamePlus.uc#L31
`var() config int MaxTeamSize;`
Which 16 by default and any other bots simple goes to another team.
So I not start mess with that in `Reproduce steps` because it is not relevant for this issue.

There a lot of little problems:
1. no `1 ` Before `All`
2. No '1' Bot after `0` bot because it draw under subme edge/bottom button.
3. Menu goes out of screen.
4. And so on.

All of this will be fixed in fix when I have time make it.

**Comment by OjitroC** [comment]
Oh, I see.

Your problem 1 isn't a problem as ALL should come at the top.  There is no '1 Name' after ALL and before 2 Nikita as 1 is the Player giving the orders, that is you (so you can't give an order to yourself).

**Comment by SeriousBuggie** [comment]
I know that. I mean first item must be written as `1 All` not as `All`.

**Comment by OjitroC** [comment]
Should it though?  The individuals (bots) have numbers before their names - putting a 1 before ALL could suggest that ALL is also an iindividual/a bot rather than the means of giving an order to 'everyone'?  

Do the numbers have a practical purpose related to what happens in the game?  Perhaps it would make more sense if the numbers were continuous up to the number of bots on a team (rather than going 0 or 1 up to 9 and then starting again at 0 or 1 (not sure which is the starting number)? 

Another thing I noticed from the screenshot - Defend and Attack have no fullstop (which is fine), the other orders do - possibly a need for consistency?  Suggest remove the fullstop.

**Comment by SeriousBuggie** [comment]
It is indicate what key you need press, for select this item from keyboard.

Generally I not use in voice menu mouse.

For example if I want say `Boom!` on `Female Two` voice inside battle I simple press and hold `V` and press `4` and `6` with my left hand. Right hand still on mouse aim and fire.

So `1 All` mean `press 1 for use this menu item`.

About dot at the end: all depends how this written in localization files. So definitely not related here.

**Comment by OjitroC** [comment]
Oh - right, I understand now the purpose of the numbers - and having tried it out, yes, that works very well!

Is it documented any where? Otherwise a lot of people, like me, won't know about it.

**Comment by SeriousBuggie** [comment]
IDK, documented or not, but this feature exists in original UT. Even in v436. I just add this numbers for make things more clear, visible and user friendly.

Possible this thing mentioned in UT tutorial which come with disc, but who read this tutorials?
