### ISSUE TITLE
[469b] MultiFlags in BTPlusPlus has stopped working

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#279]
The BunnyTrack mod BTPlusPlus contains a feature called MultiFlags which allows multiple players to grab the flag in BT/CTF games. When a player grabs the flag a copy of the flag is made and the "original" flag remains at the base. 

This MultiFlags feature has stopped working for some reason in UT v469.
Instead, when a player grabs a flag, the flag is removed from the flagbase completely.

The MultiFlags code is visible here:
* https://github.com/bunnytrack/BTPlusPlus/blob/3e67abd19113f422853ca94ba8ecc9c983d3f33f/src/BTPlusPlusv0991/Classes/BTPlusPlus.uc#L2791
* https://github.com/bunnytrack/BTPlusPlus/blob/3e67abd19113f422853ca94ba8ecc9c983d3f33f/src/BTPlusPlusv0991/Classes/FlagDisposer.uc#L247

**Comment by SeriousBuggie** [comment]
> CTF flags now automatically respawn and get returned to their flag base if they get destroyed. This allows CTF flags to work on maps with CloudZones or TriggeredDeath triggers. The fix is enabled by default but can be disabled by setting Botpack.CTFGame.bAutoRespawnFlags to false. 

So try set this option to false. In section `Botpack.CTFGame` or in section of your game type.

**Comment by dizzy-egg** [comment]
Just discovered it's related to the following changelog feature:

> CTF flags now automatically respawn and get returned to their flag base if they get destroyed. This allows CTF flags to work on maps with CloudZones or TriggeredDeath triggers. The fix is enabled by default but can be disabled by setting Botpack.CTFGame.bAutoRespawnFlags to false.
Changing the setting to true in the server's UT.ini fixes the issue.

**Comment by dizzy-egg** [comment]
> > CTF flags now automatically respawn and get returned to their flag base if they get destroyed. This allows CTF flags to work on maps with CloudZones or TriggeredDeath triggers. The fix is enabled by default but can be disabled by setting Botpack.CTFGame.bAutoRespawnFlags to false.
> 
> So try set this option to false. In section `Botpack.CTFGame` or in section of your game type.

I _just_ discovered the same thing! :smiley:  Thank you. I'll close this issue.

**Comment by stijn-volckaert** [comment]
We've changed the default value for bAutoRespawnFlags to false in 469d
