### ISSUE TITLE
[469a] Some things are brighter than usual

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#28]
I know it might sound kinda nitpicky, but I've noticed that some things are brighter than usual, such as gibs, the Translocator module, the Slith's balls of acid, shell casings, etc. This happens on all renderers on version 469.
![94090287-dbc46300-fdda-11ea-9ae9-0b29b2a02e7c](https://user-images.githubusercontent.com/71798183/94211324-c3b21980-fe96-11ea-9e75-30a97b694733.jpg)

My .ini: [Beemo'sINI.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5279785/Beemo.sINI.zip)

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by stijn-volckaert** [comment]
Can you try to generate the same screenshot in 436?

**Comment by DarkBeemo** [comment]
> Can you try to generate the same screenshot in 436?
![20200924200229_1](https://user-images.githubusercontent.com/71798183/94215084-11cc1a80-fea1-11ea-8d9e-b44903f98a39.jpg)
Here you go.

**Comment by DarkBeemo** [comment]
![20200924192913_1](https://user-images.githubusercontent.com/71798183/94215412-307ee100-fea2-11ea-998d-8ffee308b703.jpg)
Some other things like the Shock Rifle also have a strange "shimmer" effect from afar.

**Comment by stijn-volckaert** [comment]
See #209

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
