### ISSUE TITLE
[469b] UnrealEd: Group item visibility changes when leaving property field with TAB (Win10)

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#285]
Usually I add Actors to a group by editing Properties>Object>Group directly. (In previous version 436 of UnrealEd I had to add the group additionally in the group browser; in 469b it seems to be added automatically.) When I leave the edit field with TAB, the Actor gets invisible, because the visibility of that group items has changed to FALSE. This behaviour is only for the first Actor in the group; when other Actors are added to the group by editing the "Group" field, behaviour when leaving the edit field is as expected changing focus to the next edit field.

Steps to reproduce:
1) add any Actor to a map (I tried Light, FlashLight, AmbientSound)
2) type in a none existing, valid group name in Properties>Object>Group
3) switch to next field with TAB

Result: Actor gets hidden

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1709996916](https://github.com/stijn-volckaert/UnrealTournament/assets/70026933/aeb39d6a-5b5d-4d39-b6fa-85456a7dd15c)
![scr_1709996927](https://github.com/stijn-volckaert/UnrealTournament/assets/70026933/70a33e54-36de-4773-8369-eb164a84867e)
![scr_1709996935](https://github.com/stijn-volckaert/UnrealTournament/assets/70026933/51e3c825-963f-414e-a0c7-ebecfb918f4d)
