### ISSUE TITLE
[469b] When closing, UnrealEd asks for saving although the map was just saved manually before

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#289]
When I finish mapping with UnrealEd, I save the map with the disk button in the tool bar and close UnrealEd. Then it often happens that UnrealEd asks to save the map although nothing has changed (at least in my opinion) since the last save just before.
Sadly I cannot reproduce this.

**Comment by SeriousBuggie** [comment]
```
Begin Actor Class=LevelInfo Name=LevelInfo0
     TimeSeconds=355.708588
```
This value constantly update, so map change every second. So need ask for save "changes".

**Comment by SeriousBarbie** [comment]
If this is the case, that property should be ignored for the "modified" status of a map, because it is complete useless for mapping. But I doubt that that value is taken into account, because it also happens that I am NOT asked for saving the map.

**Comment by stijn-volckaert** [comment]
Confirmed. TimeSeconds is not the culprit, however. The dialog appears whenever you close the current map while there are transactions in the undo buffer. The updated TimeSeconds value would not appear in the undo buffer, but transactions such as selecting a surface would be in it. We'll try to make the dialog a bit more clever.

**Comment by SeriousBarbie** [comment]
It also happened when nothing was changed in the map, not even a selection. As I already wrote: first clicked button "Save", then the "X" to close window.

**Comment by SeriousBuggie** [comment]
Possible cause of map modification:
1. You select/deselect any actor. It is change actor properties because actor selection is just flag bSelected.
2. You hide/show any actor. Too just flag bHiddenEd.
Another possible changed flags:
````
//Editing flags
var(Advanced) bool        bHiddenEd;     // Is hidden during editing.
var(Advanced) bool        bDirectional;  // Actor shows direction arrow during editing.
var const bool            bSelected;     // Selected in UnrealEd.
var const bool            bMemorized;    // Remembered in UnrealEd.
var const bool            bHighlighted;  // Highlighted in UnrealEd.
var bool                  bEdLocked;     // Locked in editor (no movement or rotation).
var(Advanced) bool        bEdShouldSnap; // Snap to grid in editor.
var transient bool        bEdSnap;       // Should snap to grid in UnrealEd.
var transient const bool  bTempEditor;   // Internal UnrealEd.
```

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Open any map.
2. Select or deselect any actor (for make change).
3. Press `Save`.
4. Press `New Map`.

Expected result: Created new map without ask about save current map.
Actual result: Appear dialog about save current map.
