### ISSUE TITLE
[469a] Strange effects in XOpenGL

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#29]
XOpenGL makes the drop-down options in menus look somewhat weird. 
![94090382-10381f00-fddb-11ea-95fc-af49f15ba041](https://user-images.githubusercontent.com/71798183/94211605-7e421c00-fe97-11ea-9e9a-9869bb690fdb.jpg)

I also went to a custom Monster Hunt server with the XOpenGL renderer -- this certain server has a mutator that enables a radar, and XOpenGL makes a bright purple square appear around this radar. This only happens on XOpenGL. 
![20200923201901_1](https://user-images.githubusercontent.com/71798183/94211702-d0833d00-fe97-11ea-8bee-af4418d2c856.jpg)

My .ini: [Beemo'sINI.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5279802/Beemo.sINI.zip)

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by stijn-volckaert** [comment]
Fixed for v469b

**Comment by SeriousBuggie** [comment]
Can confirm fix in v469b output text fields and selects with shadow in left.
Radar not tested.
