### ISSUE TITLE
[469b] [macOS] icon alpha is not displaying properly 

### ISSUE THREAD

**Issue by shinra-electric** [OldUnreal/UnrealTournamentPatches#294]
The macOS icon is not displaying correctly. 

This is what it looks like with the 469b release: 

![Screenshot 2021-04-01 at 17 46 59](https://user-images.githubusercontent.com/50119606/113327335-bf1d6080-9312-11eb-9090-e34df944f352.png)

An online converter like [cloudconvert](https://cloudconvert.com/png-to-icns) should be able to convert a high quality image to a supported .icns file.

**Comment by MLipfert1** [comment]
It is maybe possible for someone to create an icon for macOS, that fits to the macOS Big Sur app icon [design guide](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)? Especially a rounded rectangle border around the unreal logo would be nice.

**Comment by shinra-electric** [comment]
What about this one from [Deviantart](https://www.deviantart.com/djgyre/art/Unreal-Tournament-Icon-176236907)?

![Unreal](https://user-images.githubusercontent.com/50119606/142454289-b5c83e37-e737-48d0-ad34-05c862d7886f.png)

**Comment by stijn-volckaert** [comment]
469c-RC2 has a new logo with proper alpha
