### ISSUE TITLE
[469b] Flood in logs in some cases when Pawn.bIsPlayer == True, but Pawn.PlayerReplicationInfo == None

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#296]
`VoiceMaleTwo MH-Vale_Evelyn.VoiceMaleTwo0 (Function Botpack.ChallengeVoicePack.PlayerSpeech:010B) Accessed None 'PlayerReplicationInfo'`
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ChallengeVoicePack.uc#L395
```
					for ( P=Level.PawnList; P!=None; P=P.NextPawn )
						//if ( P.bIsPlayer && (P.PlayerReplicationInfo.TeamId == Callsign)
						if ( (P.PlayerReplicationInfo.TeamId == Callsign)
```
I think there must be check `P.PlayerReplicationInfo` is not None before get `TeamId` field on it.

**Comment by an-eternity** [comment]
Usually, some Pawn classes (ScriptedPawn, FlockPawn, ...) have PlayerReplicationInfo==None.
These script warnings happen, for example, when the player assigns an order for the bot in the MonsterHunt GameType.

**Comment by SeriousBuggie** [comment]
As Barbie note, 

> Probably this is because SkaarjTrooper get temporary bPlayer=true (to pick up weapon AFAIR), and they don't have a PRI.

https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UnrealI/SkaarjTrooper.uc#L168
```
		bIsPlayer = true; // temporarily, till have weapon
		if ( WeaponType != None )
		{
			bIsPlayer = true;
			myWeapon = Spawn(WeaponType);
			if ( myWeapon != None )
				myWeapon.ReSpawnTime = 0.0;
		}
```

**Comment by SeriousBuggie** [comment]
Also by same reason flood in logs:
`DeathMatchPlus Autoplay.DeathMatchPlus0 (Function Botpack.DeathMatchPlus.ChangeName:0085) Accessed None 'PlayerReplicationInfo'`
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/DeathMatchPlus.uc#L1266
```
	While ( APlayer != None )
	{	
		if ( APlayer.bIsPlayer && (APlayer.PlayerReplicationInfo.PlayerName~=S) )
		{
			Other.ClientMessage(S$NoNameChange);
			return;
		}
		APlayer = APlayer.NextPawn;
	}
```
