### ISSUE TITLE
Localize UTmenu.UTExtraKeyBindings

### ISSUE THREAD

**Issue by NeonKnightOA** [OldUnreal/UnrealTournamentPatches#299]
In the class `UTMenu.UTExtraKeyBindings`, the following lines:
```
var string SectionName;
var string LabelList[30];
var string AliasNames[30];
```
Should be:
```
var localized string SectionName;
var localized string LabelList[30];
var string AliasNames[30];
```
This way the extra bindings (such as those in relicsbindings.u and other mods) can be localized.

**Comment by SeriousBuggie** [comment]
You check this changes for backward compatibility? All tested and work properly?

**Comment by NeonKnightOA** [comment]
I don't see how this little change could break compatibility. At worst, it would add more strings when `ucc editor.dumpint` is ran over a certain .u file. Which is the desired output TBH, as, for example, relicsbindings.u cannot be localized.

**Comment by SeriousBuggie** [comment]
We need to run tests.

Change the implementation of `UTMenu.UTExtraKeyBindings`, in `UnrealEd`, recompile, save `UTMenu` and check that everything works with the unchanged `relicsbindings.u`.

And also check to see if the `INT` file with changes handles as intended.

**Only tests can show the true nature of things.**

I don't know how everything works there internally. Therefore, I can think of many implementations that can be broken by this change.

For example:
- this modifier changes the sorting order of fields.
- this modifier results in a different data type for the fields. For example `localized string` not compatible with `string`.
- this modifier is built into the signature of the base package when building a package, which makes it impossible to share them.
- this modifier is built into the child package when building the package, which makes the specified change useless - the `INT` file will not work.
- and so on.

**Comment by NeonKnightOA** [comment]
Well, what a bummer. Just tried doing the change I suggested and it didn't change anything, indeed. Closing.
