### ISSUE TITLE
[469a] Hidden windows.

### ISSUE THREAD

**Issue by Snuggx** [OldUnreal/UnrealTournamentPatches#3]
Sometimes you want to work with a window that is already open, but completely hidden behind others. 
I think it would be helpful if a click on the button for "Add Special Brush" would bring the window to the front.
And maybe a fast double-click on a actor could bring the properties window to the front..
![wind](https://user-images.githubusercontent.com/8658549/89106517-c4947500-d42a-11ea-906d-f097fefe0c2c.jpg)

**Comment by SeriousBuggie** [comment]
Still not fixed in 469b and very annoying. You try open Actor properties. Click- nothing. Click again nothing.
You need dig from all open Browser and child windows of UnrealEd for find where is located this Actor properties.

With search window all even worse because it is small.

**Comment by stijn-volckaert** [comment]
Pushed a fix for 469c
