### ISSUE TITLE
NexGen?

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#30]
I frequently go to a custom Monster Hunt server whenever I can and whenever I feel like it. This particular server uses a mutator that makes the whole HUD and interface different -- I believe it is called "NexGen." For some reason, the scoreboard is really big even when there isn't a lot of players, only a few names will appear on the scoreboard, and then no other names will appear on the scoreboard even after someone else joins the server. This happens on all renderers. This did not occur in 436 or 451. 
![94090331-ee3e9c80-fdda-11ea-8df0-d0098d6cbf0a](https://user-images.githubusercontent.com/71798183/94212275-55bb2180-fe99-11ea-9d18-a102f16ababf.jpg)
![94090318-e8e15200-fdda-11ea-8311-cd6ac767eed6](https://user-images.githubusercontent.com/71798183/94212277-5784e500-fe99-11ea-980d-d03c4b026c7f.jpg)

Notice in the two screenshots how the game said a new player had joined, but the scoreboard hasn't been updated.

My .ini: [Beemo'sINI.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5279823/Beemo.sINI.zip)

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by stijn-volckaert** [comment]
nexgen doesn't replace the scoreboard. This scoreboard looks like a derivative of SmartCTF. Several mod authors are updating their SmartCTF-based scoreboards to work better in v469a. I suspect that this is one of them.

**Comment by DarkBeemo** [comment]
> nexgen doesn't replace the scoreboard. This scoreboard looks like a derivative of SmartCTF. Several mod authors are updating their SmartCTF-based scoreboards to work better in v469a. I suspect that this is one of them.
Thank you!

**Comment by sn260591** [comment]
> This scoreboard looks like a derivative of SmartCTF. Several mod authors are updating their SmartCTF-based scoreboards to work better in v469a. I suspect that this is one of them.

This server uses dumhv5_208. Based on the date of the file in my cache, it hasn't changed for at least 4 years.

**Comment by stijn-volckaert** [comment]
Confirmed and fixed for the next build
