### ISSUE TITLE
[469b] Music speedup during match

### ISSUE THREAD

**Issue by TankBeef** [OldUnreal/UnrealTournamentPatches#302]
Ok, I still do not know how to reproduce the issue. But I have experienced during some matches a sudden framerate drop, and when it recovers, the music plays at double speed. Does not always occur, but has anyone else experienced it? I am on OpenAL btw.

**Comment by mkardi** [comment]
I have not noticed it myself besides other issues with OpenAL.
Did it happen in botmatch or online?

**Comment by TankBeef** [comment]
> I have not noticed it myself besides other issues with OpenAL.
> Did it happen in botmatch or online?

Both. Although the online server had bots. I should had saved the log, next time it occurs I will post it.

**Comment by TankBeef** [comment]
I decided to close this issue. If I find a proper way to reproduce it and confirm that it is 469b related, I may reopen. Has not come up again in a while.
