### ISSUE TITLE
[469b] UnrealEd: Ctrl+W has changed to Ctrl+D

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#303]
Duplicate a selection in UnrealED:
Version 436: Ctrl+W
Version 469b: Ctrl+D
Is that intended?

**Comment by SeriousBuggie** [comment]
Related to #12 and #221

**Comment by stijn-volckaert** [comment]
Confirmed. We are planning to make the keybind scheme configurable
