### ISSUE TITLE
[469a] "about" menu just opened a terminal with an error message

### ISSUE THREAD

**Issue by legluondunet** [OldUnreal/UnrealTournamentPatches#31]
Hello,
if I choose "About Epic Games" in menu, I just obtained a terminal with an error message:
`/usr/bin/xterm/: Can't execvp links : no file or folder found`
Same result for "Technical support".
Perhaps just deactivate them?

config: Ubuntu 20.04, NVidia

**Comment by senneschall** [comment]
I can't reproduce this. I'm also on Ubuntu 20.04, but when I click on "About Epic Games", nothing but a sound effect happens and this appears in my log file:

`Log: Browse: https://www.epicgames.com/`
`Log: Tried to view URL but BROWSER environment var isn't set!`
`Log:  URL to view was [https://www.epicgames.com/].`
`Log:  Trying some standard browsers...`
`Log: Couldn't find any browser to launch!`
`Log: Please set the environment variable BROWSER next time.`

Do you have this variable set? Put `echo $BROWSER` in a terminal, what's the output?

**Comment by legluondunet** [comment]
var $BROWSER is not defined on my Ubuntu 20.04

**Comment by legluondunet** [comment]
```
Log: utglr: Loading fragment program "Detail texture"
Log: utglr: Loading fragment program "Detail texture two layer"
Log: utglr: Loading fragment program "Complex surface single texture and detail texture"
Log: utglr: Loading fragment program "Complex surface single texture and detail texture two layer"
Log: utglr: Loading fragment program "Complex surface dual texture and detail texture"
Log: utglr: Loading fragment program "Complex surface dual texture and detail texture two layer"
Log: BufferActorTris: 1
Log: UseDetailAlpha: 1
Log: Browse: https://www.epicgames.com/
Log: Tried to view URL but BROWSER environment var isn't set!
Log:  URL to view was [https://www.epicgames.com/].
Log:  Trying some standard browsers...
Log: Spawning browser: /usr/bin/xterm -e links https://www.epicgames.com/
Log: URL: Adding default option Name=Player
Log: URL: Adding default option Class=Botpack.TMale2
Log: URL: Adding default option team=255
Log: URL: Adding default option skin=SoldierSkins.blkt
Log: URL: Adding default option Face=SoldierSkins.Othello
Log: Browse: UTCredits.unr?Name=Player?Class=Botpack.TMale2?team=255?skin=SoldierSkins.blkt?Face=SoldierSkins.Othello
Log: LoadMap: UTCredits.unr?Name=Player?Class=Botpack.TMale2?team=255?skin=SoldierSkins.
```

**Comment by senneschall** [comment]
OK, I don't have xterm installed on my machine.
I wonder if `xdg-open` would be better for opening standard programs than using this terminal. In the end, it was intended to be a standard for every OS using X.

**Comment by stijn-volckaert** [comment]
Yes, we already had an issue on the 469 private forum where one of the testers recommended using xdg-open. We'll try to make that happen in an upcoming build.
