### ISSUE TITLE
[469b] creates a lot of "Warning: !! (WhatEver) finished playing." on client

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#313]
V469b creates lot of _Warning: !! (WhatEver) finished playing_-log entries (log file UnrealTournament.log on client while connected to a 469b server):
> ...
> Log: Bound to udemo.dll
> udemo: Startup hack successful!
> Log: UDEMO: Successfully got list of demos
> ScriptLog: CCS--> 
> ScriptLog: VER--> 3.4.8
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Warning: !! AmbientSound Botpack.Translocator.targethum finished playing.
> Log: appRequestExit(0)
> ...

These messages do not occur on server.

**Comment by SeriousBarbie** [comment]
Probably this happens when a none looping AmbientSound is set. To reproduce the issue, copy in UnrealEd the following into any map (Ofc you have to load the sound file _AmbAncient.uax_ first):
```
Begin Map
Begin Actor Class=AmbientSound
    AmbientSound=Sound'AmbAncient.OneShot.drip04'
End Actor
End Map
```

Result when running this map:

> Warning: !! AmbientSound AmbAncient.OneShot.drip04 finished playing.
> Warning: !! AmbientSound AmbAncient.OneShot.drip04 finished playing.
>

**Comment by stijn-volckaert** [comment]
Confirmed. This is a debug message that never got removed. Will fix for the next patch

**Comment by SeriousBarbie** [comment]
> Will fix for the next patch
I still get it with 469c RC6 on client; on server 469c RC4 is running.

**Comment by stijn-volckaert** [comment]
Fixed for 469d
