### ISSUE TITLE
[469b] Accessed None's of udemo.AutoRecorder 

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#314]
On every map change on server with a v469b client:

> ScriptWarning: AutoRecorder Transient.AutoRecorder0 (Function udemo.AutoRecorder.NotifyLevelChange:0043) Accessed None 'PlayerReplicationInfo'
> ScriptWarning: AutoRecorder Transient.AutoRecorder0 (Function udemo.AutoRecorder.NotifyLevelChange:004B) Attempt to assign variable through None

**Comment by SeriousBuggie** [comment]
https://github.com/stijn-volckaert/udemo/blob/af69c40cf3ac4ffd2b5ccf3999410de68a6201eb/Classes/AutoRecorder.uc#L53
`GetPlayerOwner().PlayerReplicationInfo.PlayerName = GetPlayerOwner().GetDefaultURL("name");`
IDK for what this so I can not suggest fix.
Possible enough simple check for `GetPlayerOwner().PlayerReplicationInfo != None`, but need see full picture.

In any case this @stijn-volckaert baby, so he should know how fix it.

**Comment by NeonKnightOA** [comment]
Your best bet for this is to either [open an issue](https://github.com/stijn-volckaert/udemo/issues) or [create a pull-request](https://github.com/stijn-volckaert/udemo/pulls) in [the udemo repo](https://github.com/stijn-volckaert/udemo).
