### ISSUE TITLE
[469b] D3D9 Crash

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#316]
Hi,
While joining DM-(ASC)BigBrotherTown I get the following crash.

![image](https://user-images.githubusercontent.com/59076225/114649302-445b2a80-9cae-11eb-9757-9b83b5e26aa0.png)

Windows 10 machines running 469b patch and D3D9.

Thanks

**Comment by stijn-volckaert** [comment]
Could you upload the map please?

**Comment by SeriousBuggie** [comment]
Try get it here:
https://unrealarchive.org/maps/unreal-tournament/deathmatch/A/dm-ascbigbrothertown_9f02d318.html

**Comment by OMA-Bite-Me** [comment]
That's the right one... so I won't upload it.  Let me know if you need anything else.

**Comment by stijn-volckaert** [comment]
Can you please double check to confirm that you have the 469b release patch? This crash does not happen for me

**Comment by OMA-Bite-Me** [comment]
Confirmed
It only happened one time.... I can try to duplicate it again.

I'll let you know the results.

**Comment by OMA-Bite-Me** [comment]
Cache cleaner no longer works on windows 10 for me.  I can try to find a
download link
