### ISSUE TITLE
[469b] Intermittent minigun sound when using Galaxy driver

### ISSUE THREAD

**Issue by TankBeef** [OldUnreal/UnrealTournamentPatches#317]
Ok, so I have seen a few suggestions on using Galaxy over OpenAL, despite the "deprecated" warning. I have to admit that under Galaxy the sounds are brighter and louder, but then I get this intermittent muting sounds issue, most noticeable with the minigun. Some instrument tracks go "missing" too, I have tried for example modifying the number of channels with no luck.

**Comment by stijn-volckaert** [comment]
I cannot reproduce this problem. Can you post your Galaxy settings here? Does this happen online, offline, or both? Does this also happen when there are no other sounds playing in the background?

**Comment by TankBeef** [comment]
> I cannot reproduce this problem. Can you post your Galaxy settings here? Does this happen online, offline, or both? Does this also happen when there are no other sounds playing in the background?

As soon as I get home I will post the settings. Meanwhile, I can tell they are not much different from the default. I have set to False the surround, reverb, filter, modified latency, the issue is still there. Yes, I have only tested offline, and does happen mostly with background sounds, so I assumed it was a channel thing maybe, but I modified the channel values also, and the sound actually gets worse when I do that.
I also played a map with the mayhem.umx, with both OpenAL and Galaxy. Starting at the 1:30 mark, in Galaxy some instruments are missing. You can tell cause when you play the umx with VLC, all the instruments are there.
