### ISSUE TITLE
[469a] Cage in Dark Arena looks "cut off"

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#32]
![20200924191623_1](https://user-images.githubusercontent.com/71798183/94216903-40002900-fea6-11ea-8c53-65007b0b7453.jpg)
I was playing online earlier when I came across this in MH-DKdark, which is a MH conversion of the Dark Arena map from the original _Unreal._ It fixed itself when I moved the lever and lowered the cage into the lava, and then when I began switching renderers to test it again, it went back to normal. I was using Direct3D 9 at the time it first happened, version 469a.

.INI: https://github.com/OldUnreal/UnrealTournamentPatches/files/5279802/Beemo.sINI.zip

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by CacoFFF** [comment]
This is the moving brush tracker being unable to push all of the mover's surfaces into the level's 'dynamic geometry'.
There isn't much to do about the moving brush tracker itself (design limitations) other than to completely get rid of it and render movers more like UE2 would do it. 

Except that UE2 uses static meshes, so we'd have to come up with a completely new solution to that.
The moving brush tracker also ensures visibility checks don't go through movers, which means we have to make sure whatever replacement we come up with has the ability to block these traces too.

The advantage of this is that we'd be able to block these visibility checks in dedicated servers.
