### ISSUE TITLE
[469b] UEd Realtime Preview does not remain enabled after playing a map from the Editor

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#322]
In v436 Unreal Editor, with four viewpoints, if one opens a map, enables Real time Preview for each viewpoint, plays the map. and then returns to the Editor, the RealTime Preview will remain enabled for each viewpoint.  In 469b Editor this is not the case.

To reproduce
1 Open the Editor and open a map
2 Enable the RealTime preview for each viewpoint
3 Play the map from the Editor
4 Exit the map and UT and return to the Editor

Expected result : the RealTIme Preview remains enabled for each viewpoint
Actual result : RealTime Preview is disabled for each viewpoint

**Comment by SeriousBuggie** [comment]
I think it is by design. Because if you use D3D render you can get error of init it if any other app use it.

Possible this disable stuff must work only if viewport use render != software.

**Comment by OjitroC** [comment]
Or make it an option for the user choose what the behaviour will be?

**Comment by SeriousBuggie** [comment]
> Smirftsch (author of this patch)
> because it caused trouble (at least back then yet) when realtime was enabled and Unreal was started up together with it
> not entirely sure anymore ,I think it messed up the viewport then
> perhaps nowadays may work, but better safe then sorry (for now at least)

**Comment by SeriousBuggie** [comment]
Starting from 469e:
For keep realtime option, when launch game, need set in UnrealEd.ini
```
[Options]
KeepRealtimePreviewOnPlay=True
```

**Comment by BerserkerBG** [comment]
Alternative idea - turn off real-time preview while playing your map from Ued (which is current default behavior), after you close UT and go back to Ued then real-time preview could enable back. Is this possible?

**Comment by SeriousBuggie** [comment]
We currently not track if game run from editor. Before we do, and this lead to a lot problems and bugs.

Anyway user can want minimize game and continue work in editor. I often do such.
