### ISSUE TITLE
[469b] Warning: ALAudio: alureBufferDataFromMemory failed: Unsupported type

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#324]
Map [MH-DinoPlanet2011[THUNDERBOLT]FIX02](https://unrealarchive.org/maps/unreal-tournament/monster-hunt/D/mh-dinoplanet2011thunderboltfix02_63d90887.html) 
produce endless flood in logs:
```
Warning: ALAudio: alureBufferDataFromMemory failed: Unsupported type
```
You need run to middle of the map for get this flood in the log.
Possible because there located some sound source of it.

**Comment by SeriousBuggie** [comment]
Source of problem: [MyLevel.Ambient2.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6783127/Ambient2.zip)
Audio: IMA ADPCM 8000Hz mono 32kbps [A: adpcm_ima_wav, 8000 Hz, 1 channels, s16, 32 kb/s]

**Comment by SeriousBuggie** [comment]
Cluster3D play this sound fine.

**Comment by SeriousBuggie** [comment]
Another file which ALAudio not able play and trigger fllod in log
`Warning: ALAudio: alureBufferDataFromMemory failed: Unsupported type`:
[DS9Activate.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7110276/DS9Activate.zip)
Extracted WAV:
[activ_01.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7110277/activ_01.zip)
Info same:
`Audio: IMA ADPCM 22050Hz mono 88kbps [A: adpcm_ima_wav, 22050 Hz, 1 channels, s16, 88 kb/s]`

Reproduce:
1. Load in UnrealEd `DS9Activate.uax` and try play sound from it.

Expected result: Sound play, no log messages.
Actual result: Sound not play, in log appear message.

**Comment by SeriousBuggie** [comment]
alure and openal-soft support IMA ADPCM. But only when nBlockAlign = 65 and wSamplesPerBlock = 36.
> /* AL_EXT_IMA4 only supports 36 bytes-per-channel block
> * alignment, which has 65 uncompressed sample frames */

In file from DS9Activate.uax nBlockAlign = 512 and wSamplesPerBlock = 1017.

**Comment by SeriousBuggie** [comment]
Map with embed sounds for tests: [SoundGroupNone.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9006006/SoundGroupNone.zip)

**Comment by stijn-volckaert** [comment]
We fixed this in 469d by enabling OpenAL-Soft's libsndfile backend
