### ISSUE TITLE
[469b] Relics HUD mutator incompatible with other HUD mutators

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#325]
Well known problem:
https://wiki.beyondunreal.com/Legacy:HUDMutator

Problems:
1. can call Destroy and all next HUD mutators stop work
2. own chain of HUD mutators which compatible with self only
3. not mark self as bHUDMutator 

Fix:
```
simulated function RegisteraHUDMutator()
{
	local PlayerPawn P;

	ForEach AllActors(class'PlayerPawn', P)
		if ( P.myHUD != None )
		{
			NextRHUDMutator = HUDMutator(P.myHud.HUDMutator);
			NextHUDMutator = P.myHud.HUDMutator;
			P.myHUD.HUDMutator = Self;
			PlayerOwner = P;
			bIsHUDMutator = True;
			bHUDMutator = True;
		}	
}
```
and
```
simulated function PostRender(canvas C)
{
	local float Scale;
	local Inventory inv;
	local int i;

	if ( PlayerOwner != None && PlayerOwner == ChallengeHUD(PlayerOwner.MyHUD).PawnOwner )
	{
// skip some relics related stuff
	}

	if ( NextHUDMutator != None )
		NextHUDMutator.PostRender( C );
}
```
```
simulated function CheckForHUDMutator()
{
	local Mutator M;
	local RelicHUDMutator RHM;
	local PlayerPawn P;

	ForEach AllActors(class'PlayerPawn', P)
		if ( P.myHUD != None )
		{
			// check if it already has a RelicHUDMutator
			M = P.myHud.HUDMutator;
			while ( M != None )
			{
				if ( M.IsA('RelicHUDMutator') )
					return;
				if ( M.NextHUDMutator == None && HudMutator(M) != None )
					M = HudMutator(M).NextRHUDMutator;
				else
					M = M.NextHUDMutator;
			}
```

1. We not call Destroy.
2. We use UT chain and duplicate info just for case of use old mutator targeted for relics. Also we travel to old chain if usual empty.
3. Set bHUDMutator to true.

Because of client-side nature of HUD mutators, this issue can not be fixed for old clients on new servers.
Client must be new or use fixed relics.u.

Fixed relics.u of course not compatible with v400.

**Comment by NeonKnightOA** [comment]
I remember the existance of a "RelicsHUDPatch" mutator. Is it related to this?

http://www.ut-files.com/index.php?dir=Patches/&file=RelicsHUDPatch.zip
