### ISSUE TITLE
[469b] Illegal Array sizes over 2048

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#326]
Hi we just tried compiling MapVoteUltimate which has a MapList array size of 8192 and get the following error;
https://cdn.discordapp.com/attachments/633791922862948362/832758821133877308/dz4GWgi.png
both 436/451 compilers have no problem with compiling this.

**Comment by SeriousBuggie** [comment]
IDK about limit 1024. For me it is 2048. I compile UserMute mutator with 2048 items in struct array:
```
struct MuteEntry {
	var string Name;
	var string HashIP;
	var string HashID;
	var bool bBroadcast;
};

var config MuteEntry Muted[2048];
```
All above 2048 produce compiler error. At v469b.
```
var config MuteEntry Muted[655360];
```
at v436 compile fine.
IDK about access items on it, but at least compile.

**Comment by stijn-volckaert** [comment]
Confirmed. UTPG backported this change from UE2. We will revert it.

**Comment by stijn-volckaert** [comment]
Reverted in 469c-RC2

**Comment by SeriousBuggie** [comment]
For info: 16384 is max now.
