### ISSUE TITLE
[469b] HUD armor limited by value 150

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#328]
Reproduce:
1. Start [DM-!!!!!hud_bug](https://github.com/OldUnreal/UnrealTournamentPatches/files/6329531/DM-.hud_bug.zip)
2. Pickup up Shield belt.

Expected result: Armor display as 1500.
Actual result: Armor display as 150.

This is because:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ChallengeHUD.uc#L573
```
DrawBigNum(Canvas, Min(150,ArmorAmount), X + 4 * Scale, Y + 16 * Scale, 1);
```
For fix suggest remove this limit.

**Comment by SeriousBarbie** [comment]
Similar is with health above 9999.

**Comment by SeriousBuggie** [comment]
9999 is reasonable limitation. 150 - no. Possible output into HUD must be limited to prevent destroy HUD by very long numbers.
