### ISSUE TITLE
[469b] Pulse gun able spawn projectiles behind thin walls

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#329]
Reproduce:
1. Start [DM-!!!!!pulse_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6330306/DM-.pulse_bug.zip)
2. Pick up pulse and try hit Cow with primary or alt fire.

Expected result: Cow can not be hit.
Actual result: You can kill cow if stay close to glass and fire with primary fire. Alt fire not work.
![scr_1618706586](https://user-images.githubusercontent.com/70026933/115130513-084eff00-9ff9-11eb-8d33-a31368528b8e.png)
![scr_1618706558](https://user-images.githubusercontent.com/70026933/115130517-0e44e000-9ff9-11eb-8a58-c6c8f937aebd.png)

In v436 Cow can be killed with both primary and secondary fire.
In v469b Secondary fire look like fixed. Primary - not.

Possible need check by FastTrace between spawned projectiles and Owner. Or spawn it close to Owner.

**Comment by SeriousBuggie** [comment]
fix:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/PulseGun.uc#L279
```
		Start = Start - Sin(Angle)*Y*4 + (Cos(Angle)*4 - 10.78)*Z;
```
replace to:
```
		Start = Start - Sin(Angle)*Y*4 + (Cos(Angle)*4 - 10.78)*Z;
		if (!Owner.FastTrace(Start))
			Start = Owner.Location + Normal(Start - Owner.Location) * Owner.CollisionRadius*0.9;
```
Fixed gun: [DM-!!!!!pulse_bug_fix.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6330998/DM-.pulse_bug_fix.zip)

**Comment by Chamberly** [comment]
I can recall a lot of people abused this in other game especially in Siege to destroy 'builds'.

The other hand to answer that was to make the wall thicker... but I'm not sure if the fire offset was too much ahead of the location or what.
