### ISSUE TITLE
[469b] Shot that does not come out in the same place as the crosshair...

### ISSUE THREAD

**Issue by thiagoobr** [OldUnreal/UnrealTournamentPatches#330]
Hi,

in relation to the old bug, shooting does not come out where your aim is, can you fix it?

the correct thing would be for the shot to come out exactly where it was aimed... 

![123](https://user-images.githubusercontent.com/82742656/115133153-68837800-9fdc-11eb-8d22-458e08e1c670.PNG)
https://i.ibb.co/7t2nhqT/123.png

**Comment by stijn-volckaert** [comment]
This was done by design. The enforcer is one of the weapons that is not 100% accurate. The game adds a small offset to all shots you fire.

**Comment by sn260591** [comment]
The OP did not mean the accuracy of the weapon, but the mismatch between the center of the crosshair and the hit. Even with a large number of shots, the bullets always hit lower and to the right. The same thing happens with the minigun (and some other weapons):

![Shot00080](https://user-images.githubusercontent.com/10724977/185659082-62774562-27d4-412c-ae62-cbf4c69ce31f.jpg)

With a sniper rifle, the shift is already in the other direction:

![Shot00083](https://user-images.githubusercontent.com/10724977/185661031-acf4b61c-c8f7-424a-a35d-3a73b470ecd3.jpg)
