### ISSUE TITLE
[469b] "OpenGL Error: GL_INVALID_ENUM" line on log

### ISSUE THREAD

**Issue by TankBeef** [OldUnreal/UnrealTournamentPatches#333]
I am getting this often on my log, sometimes once, sometimes flood: "OpenGL Error: GL_INVALID_ENUM (please report this bug)." So I am "reporting the bug", like it says. Otherwise, the OpenGL is working fine so far.

**Comment by xenoxaos** [comment]
Adding my output. I can trigger it by toggling fullscreen mode

Ending fullscreen mode by request.
SDLDrv SwapInterval = 0
GL_VENDOR     : NVIDIA Corporation
GL_RENDERER   : NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
GL_VERSION    : 4.6.0 NVIDIA 465.31
Device supports: GL_ARB_texture_compression
Device supports: GL_EXT_texture_compression_s3tc
Device supports: GL_ARB_texture_compression_rgtc
Device supports: GL_ARB_texture_compression_bptc
Device supports: GL_EXT_texture_shared_exponent
Device supports: GL_EXT_texture_filter_anisotropic
Device supports: GL_ARB_texture_filter_anisotropic
Device supports: GL_NV_texture_env_combine4
Device supports: GL_EXT_texture_lod_bias
Device supports: GL_EXT_secondary_color
Device supports: GL_ARB_multitexture
Device supports: GL_EXT_multi_draw_arrays
Device supports: GL_ARB_vertex_program
Device supports: GL_ARB_fragment_program
Device supports: GL_ARB_texture_non_power_of_two
Device supports: GL_ARB_framebuffer_object
Device supports: GL_ARB_sampler_objects
Device supports: GL_ARB_clip_control
Depth bits: 16
4 Texture Mapping Units found
32 Shader Texture Mapping Units found
BufferActorTris: 1
UseDetailAlpha: 1
SDLDrv SwapInterval = 0
GL_VENDOR     : NVIDIA Corporation
GL_RENDERER   : NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
GL_VERSION    : 4.6.0 NVIDIA 465.31
Device supports: GL_ARB_texture_compression
Device supports: GL_EXT_texture_compression_s3tc
Device supports: GL_ARB_texture_compression_rgtc
Device supports: GL_ARB_texture_compression_bptc
Device supports: GL_EXT_texture_shared_exponent
Device supports: GL_EXT_texture_filter_anisotropic
Device supports: GL_ARB_texture_filter_anisotropic
Device supports: GL_NV_texture_env_combine4
Device supports: GL_EXT_texture_lod_bias
Device supports: GL_EXT_secondary_color
Device supports: GL_ARB_multitexture
Device supports: GL_EXT_multi_draw_arrays
Device supports: GL_ARB_vertex_program
Device supports: GL_ARB_fragment_program
Device supports: GL_ARB_texture_non_power_of_two
Device supports: GL_ARB_framebuffer_object
Device supports: GL_ARB_sampler_objects
Device supports: GL_ARB_clip_control
Depth bits: 16
4 Texture Mapping Units found
32 Shader Texture Mapping Units found
BufferActorTris: 1
UseDetailAlpha: 1
OpenGL Error: GL_INVALID_ENUM (please report this bug)

**Comment by stijn-volckaert** [comment]
This should be fixed in 469c-RC2
