### ISSUE TITLE
[469b] Bug in UnrealShare.DynamicAmbientSound

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#338]
Instead of `numSounds=6;` should be used `numSounds=16;` in [line 23 in DynamicAmbientSound](https://github.com/Slipyx/UT99/blob/master/UnrealShare/DynamicAmbientSound.uc#L23).

Bug exists in v436 and 469b. See also my comment in [BeyondUnreal Wiki](https://wiki.beyondunreal.com/Legacy_talk:DynamicAmbientSound).

**Comment by SeriousBuggie** [comment]
Strictly speaking it must be `ArrayCount(Sounds)`. And in next line too `ArrayCount(Sounds)`, not `16`.
