### ISSUE TITLE
[469b] Use Space key as Enter in dialog boxes

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#339]
If in dialog box defined default action you can use `Enter` for use default answer.

Will be good if `Space` too trigger default action.

Changes:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UWindow/UWindowMessageBoxCW.uc#L24
```
	if(Key == GetPlayerOwner().EInputKey.IK_Enter && EnterResult != MR_None)
```
replace to
```
	if((Key == GetPlayerOwner().EInputKey.IK_Enter || Key == GetPlayerOwner().EInputKey.IK_Space) && EnterResult != MR_None)
```

**Comment by SeriousBarbie** [comment]
Usual behaviour in Windows is that SPACE presses the **selected** button; ENTER presses the **default** button.

**Comment by SeriousBuggie** [comment]
In UT not exists thing `selected button`.
