### ISSUE TITLE
[469b] Crash on MH-!!![Space-Port]

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#342]
Reproduce:
1. Vote for map `MH-!!![Space-Port]` on Barbie server (81.169.240.101)
2. Try play with open log window.

Expected result: All fine.
Actual result: On some moment log flooded with messages like:
```
Log: 18 [88]: Stale
Log: 30 [360]: Stale
Log: 1D [500]: Stale
Log: 1D [208]: Stale
Log: 18 [56]: Stale
Log: 18 [128]: Stale
Log: 30 [204]: Stale
Log: 18 [52]: Stale
Log: 31 [128]: Stale
Log: 1D [128]: Stale
Log: 18 [364]: Stale
Log: 18 [360]: Stale
Log: 18 [148]: Stale
Log: 18 [212]: Stale
Log: 30 [284]: Stale
Log: 18 [72]: Stale
Log: 18 [96]: Stale
Log: 18 [96]: Stale
Log: 18 [48]: Stale
Log: 30 [204]: Stale
Log: 18 [152]: Stale
Log: 31 [40]: Stale
[...]
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
Log: 17 [1040]: Locked
[...]
Log: 1D [496]: Stale
Log: 1D [4648]: Stale
Log: 31 [44]: Stale
Log: 17 [1040]: Stale
Log: 17 [1040]: Stale
Log: 17 [2832]: Stale
Log: 1D [820]: Stale
Log: 1D [488]: Stale
Log: 17 [1044]: Stale
Log: 18 [6511880]: Locked
```
In total 4095 lines.
And after that UT crash:
```
---------------------------
Critical Error
---------------------------
Create 0000be05.00040031 failed: Size=163852 Pad=98304 Align=16 NumLocked=154 BytesLocked=6692212/8388608

History: FMemCache::Create <- DynamicLight <- FLightManager::SetupForSurf <- 
URender::DrawFrame <- URender::DrawWorld <- UGameEngine::Draw <- 
UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- 
UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```

You can restart UT, go to server again and face same crash. Or not. Previous time for me be 2 crashes. After that I end map.
Now I get one crash and make this issue.

On map present `BPak.BEightball` which actively used. But such crash only on this map. On other maps with `BPak.BEightball` i do not see this crash.

I not able reproduce this crash on Practice session, so steps contains usage Barbie server.

**Comment by SeriousBuggie** [comment]
Crash is random or hard to reproduce condition. Play again 3 times - no crash.

**Comment by an-eternity** [comment]
Does this happen only if the Log window is opened? (I can not reproduce this, but my server has 'BPak.BEightball' class replaced to another class always...)

**Comment by SeriousBuggie** [comment]
`BPak.BEightball` added to map by Barbie in runtime. Originally this weapon not exists on this map.

I not see anything connected with Log window.
In general, Log window only make small delay when something output into it.
Before crash nothing output to Log, so it can not be reason.

Of course I try next time without it, but I think this not related for log window.

**Comment by SeriousBuggie** [comment]
Without open log window crash too.
```
Log: 1F [128]: Fresh
Log: 18 [76]: Stale
Log: 31 [128]: Stale
Log: 18 [56]: Stale
Log: 18 [72]: Stale
Log: 18 [204]: Stale
Log: 18 [52]: Stale
Log: 31 [44]: Stale
Log: 31 [48]: Stale
[...]
Log: 18 [1568]: Stale
Log: 1D [2828]: Stale
Log: 1D [432]: Stale
Log: 1D [432]: Stale
Log: 1D [432]: Stale
Log: 30 [304]: Stale
Log: 30 [240]: Stale
Log: 1D [1224]: Stale
Log: 31 [44]: Stale
Log: 18 [64]: Stale
Log: 18 [6322900]: Locked
```
Again 4095 lines.
```
Critical: appError called:
Critical: Create 0000c5d7.00040031 failed: Size=163852 Pad=98304 Align=16 NumLocked=154 BytesLocked=6492604/8388608
Critical: Windows GetLastError: There is not enough memory to process the command. (8)
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
```
```
---------------------------
Critical Error
---------------------------
Create 0000c5d7.00040031 failed: Size=163852 Pad=98304 Align=16 NumLocked=154 BytesLocked=6492604/8388608

History: FMemCache::Create <- DynamicLight <- FLightManager::SetupForSurf <- 
URender::DrawFrame <- URender::DrawWorld <- UGameEngine::Draw <- 
UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- 
UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```

**Comment by SeriousBuggie** [comment]
Also this happens when Redemeer WarLord fire on me. I not fire at this moment.

**Comment by stijn-volckaert** [comment]
This crash happens when the game tries to allocate a chunk of data that can't fit in the cache. With a cache size of 8Mb, this rarely ever happens. However, you seem to have at least one _huge_ item in your cache at the time of the crash. In both crash logs, I see an item that is over 6Mb big. We will have to figure out what exactly this large cache item is. The top suspects, ordered from most likely to least likely are: vertex data for a LODMesh, vertex data for a normal Mesh, lightmap data, shadowmap data.

I have not been able to reproduce this myself (yet), but hopefully this information will help you narrow down the cause.

**Comment by SeriousBuggie** [comment]
This happen because of low count of cache memory item. On some point free items in ache ended, and game allocate new item on free chunk, but can't split left free space from what used, because no free items left. This look as use whole free space.
Next allocation, which not fit in cache, fail.

In 469e count items and cache increased. Also make some rework of ways how cache allocate memory. So this issue must never happen again.
