### ISSUE TITLE
[469b] NewNet - Received unwanted function in server log

### ISSUE THREAD

**Issue by alsosed** [OldUnreal/UnrealTournamentPatches#344]
DevNet: Received unwanted function ServerForceFire in ST_UT_Eightball DM-Malevolence.ST_UT_Eightball29
DevNet: Received unwanted function ServerForceAltFire in ST_UT_Eightball DM-Malevolence.ST_UT_Eightball29
DevNet: Received unwanted function ServerFireRockets in ST_UT_Eightball DM-Malevolence.ST_UT_Eightball29

DevNet: Received unwanted function ServerForceFire in ST_ut_biorifle DM-Meridia.ST_ut_biorifle5
DevNet: Received unwanted function ServerForceAltFire in ST_ut_biorifle DM-Meridia.ST_ut_biorifle7
DevNet: Received unwanted function ServerShootLoad in ST_ut_biorifle DM-Tempest.ST_ut_biorifle5

DevNet: Received unwanted function xxExplodeOther in bbTMale1 DM-Nitro.bbTMale1
DevNet: Received unwanted function xxNN_ProjExplode in bbTMale1 DM-Nitro.bbTMale3

**Comment by SeriousBarbie** [comment]
What package is that "ST_UT_Eightball" in? I guess it is bad or wrong coded.

**Comment by SeriousBuggie** [comment]
`Received unwanted function` usually mean server and client use conformed packages which not network compatible. (It can be even just simple damaged.)
Or package use some dirty hacks like create names in runtime from strings, so network stuff based on names index in tables goes to hell.

**Comment by alsosed** [comment]
> 
> 
> What package is that "ST_UT_Eightball" in? I guess it is bad or wrong coded.
Can you fix it? Here are the classes where the problem occurs
[Classes.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6375754/Classes.zip)

**Comment by alsosed** [comment]
> 
> 
> `Received unwanted function` usually mean server and client use conformed packages which not network compatible. (It can be even just simple damaged.)
> Or package use some dirty hacks like create names in runtime from strings, so network stuff based on names index in tables goes to hell.
> 
> Also this is can be some dirty hacks include messing with network roles. Because this message triggered from native when replication conditions not met. For example actor make Authoritative on client where it must not be Authoritative.
Can you take a look and suggest a fix?
[Classes.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6375779/Classes.zip)

**Comment by SeriousBuggie** [comment]
>  Function replication always implies bNetOwner, i.e. function call are only replicated if the executing actor is owned by a client, and the call will only be replicated to/from that owning client.

https://wiki.beyondunreal.com/Everything_you_ever_wanted_to_know_about_replication_(but_were_afraid_to_ask)#Function_call_replication_-_Sending_messages_between_server_and_client

So when Client send function call to server it think `I own this actor` but when message arrive server (ping delay) it is not true. And server refuse process this function call and write warning in the log.

For example you press Fire on client, but on server you already die and your gun not own by you anymore. It is destroyed or throw as pickup item.

It usually sign of bad network design for classes if its not aware of possibility desync between server and client.
This can not be fixed easily by edit few lines. This need review full hierarchy of weapon usage, chains of events and produced calls.

You can ignore this flood in the log. Or heavily modify all classes. For example use for RPC actors which can not lost owner.

**Comment by CacoFFF** [comment]
From having coded LCWeapons myself I will give my input.

Unwanted function means: a client issued an illegal RPC, plain and simple.
Your client wants to call a function that will fail the replication statement on the server.

The replication statement on client-to-server RPC's have an implicit ownership test.
This is why you should NOT code RPC's on weapons, not even for lag compensation.
ZeroPing develpoer understood this way before I did myself.

The warning itself is an indicator of something going wrong in a mod, or in a client trying to inject RPCs.
It could be modified to be more verbose while not spamming the server log... but the log itself has to stay.
