### ISSUE TITLE
What's the probability that support for the Original 1998 Unreal could be added?

### ISSUE THREAD

**Issue by sxflynn** [OldUnreal/UnrealTournamentPatches#357]
Unreal and UT99 are based off the same engine. What's the chance that the work done to update UT99 could be applied to Unreal98?

Edit: I'm a Mac user running MacOS Mojave.

**Comment by stijn-volckaert** [comment]
Very little work needs to be done to build Unreal for recent versions of macOS, but we never got permission to release Unreal on the mac. We can ask again to see if things have changed.

**Comment by stijn-volckaert** [comment]
I'm going to close this issue since it doesn't really belong on this bug tracker. We will probably build Unreal 227j for macOS, but we will need Epic's permission before we can release it.
