### ISSUE TITLE
[469b] Minigun Alt Fire still fire when use Feign Death

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#361]
Reproduce:
1. Start any map in `Practice mode`.
2. `loaded` in console.
3. Switch to `Minigun`.
4. Hold `Alt fire`.
5. Press `Feign Death` button.

Expected result: Fire stop on moment of `Feign Death`.
Actual result: You can still fire from `Feign Death` mode until ammo not ended or `Alt Fire` button not released.

If you not release `Alt Fire` button select other weapon, (sniper for example) and press `Primary fire`, then you wake up from `Feign Death` mode still fire with minigun. But also you switch to second weapon and can use it too.
For example simultaneously fire with minigun alt fire and pulse alt fire.
Or sniper + minigun.

**Comment by SeriousBuggie** [comment]
Example video:
https://user-images.githubusercontent.com/70026933/116730739-86e06f00-a9f1-11eb-9e90-40cae17d0053.mp4

**Comment by SeriousBuggie** [comment]
Fire from Pulse, Minigun, Flak at one time:
https://user-images.githubusercontent.com/70026933/116748944-dbdbaf80-aa08-11eb-97e6-78a0ba06d844.mp4
Also use bug #358

**Comment by SeriousBuggie** [comment]
Fire from **FIVE** weapons at once:
1. Old ripper.
2. Old minigin
3. New minigun.
4. Pulse Gun.
5. Flak.

https://user-images.githubusercontent.com/70026933/116752053-9b326500-aa0d-11eb-9f89-142185171390.mp4

**Comment by NeonKnightOA** [comment]
So feigning death can lead to the most overpowering combination of attacks possible. I'm surprised it wasn't explited THAT much all these years. I'd like to think that the limited ammo available for all weapons is the only thing preventing this from becoming game breaking.

**Comment by SeriousBuggie** [comment]
For fix need at
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/PlayerPawn.uc#L3994
```
	function ServerFeignDeath()
	{
		local Weapon W;

		W = Weapon;
		PendingWeapon = None;
		if ( Weapon != None )
			Weapon.PutDown();
		PendingWeapon = W;
		GotoState('FeigningDeath');
	}
```
replace to
```
	function ServerFeignDeath()
	{
		local Weapon W;

		W = Weapon;
		PendingWeapon = None;
		if ( Weapon != None ) {
			Weapon.PutDown();
			if (!W.IsInState('DownWeapon'))
				W.GotoState('DownWeapon');
		}
		PendingWeapon = W;
		GotoState('FeigningDeath');
	}
```
Now we force weapon into state `DownWeapon` if it not this state after `PutDown`.
If weapon not try delay turn to this state our change do nothing.
If weapon try delay - we force it to this state.
Problem solved. Checked on most bugged weapons:
Old ripper, old minigun, minigun, pulse, chainsaw.

I believe it solve problem for all weapons.

Also this solve flood in log: #358, #359.
But not solve sniper zoom: #360.

**Comment by SeriousBuggie** [comment]
Know drawback of fix:
- if you charge weapon with some ammo (bio, rockets, etc) then you simple lost this ammo when use feign death. It is not thrown, it just vanished.

Not a big deal.

**Comment by SeriousBuggie** [comment]
Flood in log related for weapon fire from `Feign Death` state:
```
ScriptWarning: UDamageSB MH-Scout.UDamageSB0 (Function Botpack.UDamage.FireEffect:006D) Accessed None 'Weapon'
ScriptWarning: UDamageSB MH-Scout.UDamageSB0 (Function Botpack.UDamage.FireEffect:006D) Accessed None 'Weapon'
ScriptWarning: UDamageSB MH-Scout.UDamageSB0 (Function Botpack.UDamage.FireEffect:006D) Accessed None 'Weapon'
```
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/UDamage.uc#L58
