### ISSUE TITLE
[469b] SuperShockRifle use same AIRating as ShockRifle

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#365]
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/SuperShockRifle.uc#L128
in defaultproperties not set AIRating, this mean usage of parent class value: ShockRifle
Which set 
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ShockRifle.uc#L425
to 
`AIRating=0.630000`

So bot prefer UT_FlakCannon (AIRating=0.750000) if carry both.

I think it must be same as for WarheadLauncher: `AIRating=1.000000`.

**Comment by sn260591** [comment]
Is it worth changing the default values of class fields at all? This can change the original idea of the authors of the maps/mods, or cause unpredictable behavior, as here https://github.com/OldUnreal/UnrealTournamentPatches/issues/89

**Comment by stijn-volckaert** [comment]
Indeed. A higher AIRating on the super shock rifle would have made sense when the game released but it does not make sense to apply the change at this point imo. This doesn't fix anything that is _obviously_ broken, but there might be side effects for mods.
