### ISSUE TITLE
[469b] "AdvancedTrigger" does not work

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#373]
"AdvancedTrigger" is from package "AdvancedTrigger.u" and is used for example in package "MH-JfF-Dalkove.WIP". I have prepared a small test map with that AdvancedTrigger which should raise the events "SpecialEvent0" and "Mover0". In v436 all works as expected, in 469b happens nothing - perhaps because the coder has stripped the code?
The control group consisting of a Trigger and Dispatcher, what does the same, works as expected.
[AdvancedTriggerTest.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6418290/AdvancedTriggerTest.zip)
![AdvancedTrigger](https://user-images.githubusercontent.com/81397053/116944364-a8518d00-ac75-11eb-8541-540dd16d47b2.jpg)

**Comment by SeriousBuggie** [comment]
When I touch AdvancedTrigger in v469b log:
```
Error: AdvancedTrigger Autoplay.AdvancedTrigger0 (Function AdvancedTrigger.AdvancedTrigger.Trigger:0032) GotoState (None Begin_Trigger): Label not found
```
On v436 all work without any entries in the log.

**Comment by sn260591** [comment]
@SeriousBuggie 
The script can be decompiled using UTPT.

**Comment by SeriousBuggie** [comment]
You try that? I try.
Anyway, main problem not about decompile, but about backward compatibility which breaks here.

**Comment by SeriousBarbie** [comment]
Don't overestimate backward compatibility; in my collection of more than 700 MH maps only one uses this AdvanceTrigger.

**Comment by SeriousBuggie** [comment]
Maniacs are caught with parking tickets.
The fact that this is a bad package does not mean that the reason why it stopped working.

At the moment I have a working theory that this is corrupted working with default states in v469b.

**Comment by SeriousBuggie** [comment]
Possible this already fixed in native https://github.com/OldUnreal/UnrealTournamentPatches/issues/261#issuecomment-820385638
But because @stijn-volckaert not make yet test build with latest changes I can not check this assumption.

**Comment by SeriousBuggie** [comment]
Tested in v469c preview. Bug fixed. Issue can be closed.
