### ISSUE TITLE
[469b] Movers with ReturnGroup = None linked in one big ReturnGroup which break game flow

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#380]
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Engine/Mover.uc#L510
```
// Immediately after mover enters gameplay.
function PostBeginPlay()
{
```
```
		if ( Leader == None )
		{	
			Leader = self;
			ForEach AllActors( class'Mover', M )
				if ( (M != self) && (M.ReturnGroup == ReturnGroup) )
				{
					M.Leader = self;
					M.Follower = Follower;
					Follower = M;
				}
		}
```
No any check for None (default value).
```
	// Stop, return, or whatever.
	if( MoverEncroachType == ME_StopWhenEncroach )
	{
		Leader.MakeGroupStop();
		return true;
	}
	else if( MoverEncroachType == ME_ReturnWhenEncroach )
	{
		Leader.MakeGroupReturn();
```
```
function MakeGroupStop()
{
	// Stop moving immediately.
	bInterpolating = false;
	AmbientSound = None;
	GotoState( , '' );

	if ( Follower != None )
		Follower.MakeGroupStop();
}

function MakeGroupReturn()
{
	// Abort move and reverse course.
	bInterpolating = false;
	AmbientSound = None;
	if( KeyNum<PrevKeyNum )
		GotoState( , 'Open' );
	else
		GotoState( , 'Close' );

	if ( Follower != None )
		Follower.MakeGroupReturn();
}
```
So when happens something, near ALL movers on level start move to different position which completely destroy game flow.

Possible solutions:
1. Check for same `Tag` if `ReturnGroup` is `None`. Fix problem only partially, because default `Mover` has `Tag` `Mover`and all of them make one big group.
2. Not make group if `ReturnGroup` is `None`.
3. Same as 1, but not make group if `Tag` is same as default tag for used class.

**Comment by SeriousBuggie** [comment]
```
simulated function BeginPlay()
{
```
```
	// find movers in same group
	if ( ReturnGroup == '' )
		ReturnGroup = tag;
```
I miss that. 

So All movers with default tag in one big ReturnGroup. And some maps rely on that. So we can not fix this.

**Comment by SeriousBarbie** [comment]
See also [this thread on UT99.org](https://ut99.org/viewtopic.php?t=11347).
On my server runs for every mover:
```
if (M.ReturnGroup == '') M.ReturnGroup = M.Name;
```

**Comment by SeriousBuggie** [comment]
it is wrong.
Need operate for Tag, not for ReturnGroup, because if ReturnGroup is empty it set to tag.
So if some two mover set tag to MyDoor, Then ReturnGroup fine for both even if empty.
If you replace with name, then you break this door in two groups.
You need do this stuff only if `M.Class.Name == M.Tag`.
But better edit Tag, not ReturnGroup (if this possible in runtime).
Because a lot of Mover with Tag `Mover` can fire in something other place.
