### ISSUE TITLE
[469b] UnrealEd crash "Case 3 <- UnLine <- URender::Draw2DLine"

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#393]
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: Case 3 <- UnLine <- URender::Draw2DLine <- 
UEditorEngine::DrawWireBackground <- UEditorEngine::Draw <- 
(Cam=U2Viewport0,Flags=8137 <- UWindowsViewport::Repaint <- 
UWindowsClient::Tick <- UEditorEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```
Rare crash while try drag map in wireframe viewport. IDK how reproduce it.

**Comment by stijn-volckaert** [comment]
This is a SoftDrv issue. Let me know if you find any way to reproduce this.

**Comment by SeriousBuggie** [comment]
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: Case 3 <- UnLine <- URender::Draw2DLine <- UEditorEngine::DrawWireBackground <- UEditorEngine::Draw <-
 (Cam=U2Viewport0,Flags=4041 <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- UEditorEngine::Tick
SE(C0000005) @ 6447C45B
fl=0 rec=0 n=0 i[0]=0 i[1]=800ff54
eax=ffffffc9 ebx=230d9130 ecx=1091e660 edx=00000004 esi=08010030 edi=ffc90000 eip=6447c45b
ebp=0133e5b8 esp=0133de08 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010286
 <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```
Not way for reproduce but additional info which can give some clues,

**Comment by SeriousBuggie** [comment]
Crash on 3D view `Dynamic light`. So this possible for draw Mover.

**Comment by SeriousBuggie** [comment]
```
History: Case 3 <- UnLine <- URender::Draw2DLine <- UEditorEngine::DrawWireBackground <- UEditorEngine::Draw <- 
(Cam=U2Viewport0,Flags=6091 <- UWindowsViewport::Repaint <- UEditorEngine::Tick
SE(C0000005) @ 6A9E06E3
fl=0 rec=0 n=17552980 i[0]=0 i[1]=800ff54
eax=ffffffc9 ebx=fffffffe ecx=162da5c0 edx=00000723 esi=08010030 edi=ffc90000 eip=6a9e06e3
ebp=010be378 esp=010bdb08 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010286
 <- UpdateWorld
```

**Comment by SeriousBuggie** [comment]
> Crash on 3D view `Dynamic light`. So this possible for draw Mover.

Oh no.

```c++
//
// Draw worldbox and groundplane lines, if desired.
//
void UEditorEngine::DrawWireBackground( FSceneNode* Frame )
```

It is about draw lines on background.

**Comment by SeriousBuggie** [comment]
On crash i can ignore it (on test build only OFC). It trigger until cam not moved.
So next time I wanna save map and log all Camera Rotation and position for try reproduce it by use exactly map with exactly same Camera position and rotation.

**Comment by SeriousBuggie** [comment]
```
  Player=WindowsViewport'Transient.WindowsClient0.U2Viewport0'
  ShowFlags=6091
  RendMap=6
  bAdmin=True
  FootRegion=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=-1)
  HeadRegion=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=-1)
  ViewRotation=(Pitch=49152,Yaw=91812)
  Level=LevelInfo'MyLevel.LevelInfo0'
  Tag="U2Viewport0"
  Region=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=-1)
  Location=(X=-1020.071960,Y=-13297.201172,Z=1666.808472)
  Rotation=(Pitch=49152,Yaw=91812)
  OldLocation=(X=-500.000000,Y=-300.000000,Z=300.000000)
  bSelected=True
  Name="Camera6"
```
If I change ViewRotation.Yaw to 91811 crash disappear. Or to 91820.
But all values between 91812-91819 make crash.

**Comment by SeriousBuggie** [comment]
Location 
Z coordinate if goes 1656 or lower - crash gone.
Y must be between -13295 and -13308.
X between -1011 and -1022.

ViewRotation Pitch between 49152 and 49155.

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Start UnrealEd.
2. Set Software render for viewport.
3. Use game mode for viewport.
4. Select camera of 3D viewport. I use one-cam layout and select Camera0 via search. On proper selection you must see red cylinder always on same place if `Radii view` turn on.
5. Open Actor properties.
6.  In `Movement` section set `Location` to: (X=-1020,Y=-13297,Z=1666)
7. In `Hidden` - `Pawn` set `ViewRotation` to: (Pitch=49152,Yaw=91812)

Expected result: no crash.
Actual result: crash:
```
History: Case 3 <- UnLine <- URender::Draw2DLine <- UEditorEngine::DrawWireBackground <- 
UEditorEngine::Draw <- (Cam=U2Viewport0,Flags=8139 <- UWindowsViewport::Repaint <- 
UEditorEngine::RedrawLevel <- UEditorEngine::NotifyPostChange <- FObjectsItem::SetProperty <- 
FTreeList::SetProperty <- FTreeList::SetProperty <- FTreeList::SetProperty <- FTreeList::SetProperty <- 
FPropertyItem::SetValue <- FPropertyItem::SendToControl <- FPropertyItem::OnKillFocus <- 
WProperties::SetItemFocus <- WListBox::InterceptControlCommand <- WM_COMMAND
```

Possible render space too matter. I use FullHD 1920*1080 resolution of screen. UnrealEd open to full screen. Viewport in fixed layout too open on full area.

**Comment by SeriousBuggie** [comment]
Yes. If I make window smaller issue not appear. So it must be single viewport maximized, and UnrealEd must be maximized too.

**Comment by SeriousBuggie** [comment]
Viewport rectangle: (119, 96)-(1917, 969), 1798x873

**Comment by SeriousBuggie** [comment]
Finally solved in https://github.com/OldUnreal/UnrealTournamentSDK/issues/264#issuecomment-1120286051

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Start UnrealEd.
2. Switch to Soft render, 3d view.
3. Open [Case3CrashBug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8656484/Case3CrashBug.zip)
4. Press new builder button.
5. Close message about move cameras.

Expected result: No crash.
Actual result: crash.
```
History: Case 3 <- UnLine <- URender::Draw2DLine <- UEditorEngine::DrawWireBackground <- 
UEditorEngine::Draw <- (Cam=U2Viewport0,Flags=1995 <- UWindowsViewport::Repaint <- 
UEditorEngine::RedrawLevel <- UEditorEngine::Exec <- (LEVEL REDRAW)
SE(C0000005) @ 0B2406E3
fl=0 rec=0 n=18464052 i[0]=0 i[1]=800ff54
eax=ffffffc9 ebx=07cf2064 ecx=227c9590 edx=00000703 esi=08010030 edi=ffc90000 eip=0b2406e3
ebp=0119ca58 esp=0119c1e8 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010286
 <- WButtonGroup::ButtonClicked <- WButtonGroup::OnCommand <- WM_COMMAND
```

**Comment by SeriousBuggie** [comment]
Also I use on Windows 7 classic Theme. So it make small headers and buttons. like this:
![IMG](https://user-images.githubusercontent.com/70026933/167528107-18df0beb-097c-4cd7-a7a5-03b7eedf1900.png)
It can be answer why hard reproduce it, even in same screen size. If header bigger, need another coordinates for camera, for trigger bug.

Bug trigger crash only when try draw very small line. Near 1-3 pixels long. And in very special conditions.

In all other conditions it just write random bytes in random memory without crash.

Which can lead to some consequences, but with very low chances.

**Comment by SeriousBuggie** [comment]
Reason on crash - fail render outer space cube edge.
here image from XOpenGL:
![img](https://user-images.githubusercontent.com/70026933/167530343-45e46f94-3a26-47b0-b314-b7a1685d75ec.png)
One edge goes top right corner.
Now bugged pos:
![img](https://user-images.githubusercontent.com/70026933/167530506-4e5b8ac3-bc17-43cf-b9fb-663b4db1c8f1.png)
Now this edge too small and draw on viewport edge. So there need draw 1-3 pixel line. With insane coordinates in 3D world.
So additional iteration goes far away from stack and hit unallocated memory.

**Comment by SeriousBuggie** [comment]
Here video with reproduce:

https://user-images.githubusercontent.com/70026933/167532002-034c810f-d4e4-4295-a31b-4cf5c26e55b2.mp4

I just make corner on viewport edge.
After that I move camera up/down for find spot where corner render on edge.
