### ISSUE TITLE
[469b] UnrealEd flood in the log "Localization: No localization: Unreal.General.Product (int)"

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#394]
Reproduce:
1. Start UnrealEd.
2. Open Log window.
3. Enable game mode on viewport.
4. Click on viewport.
5. Click on UnrealEd main toolbar.

Expected result: log is clear.
Actual result: On each switch focus inside/outside viewport with enabled game mode in log appear line:
`Localization: No localization: Unreal.General.Product (int)`

I think this is because Engine here search not for `UnrealTournament.int`, but for `Unreal.int`.
Somewhere typo on native. Or forget change when import code from Unreal.

**Comment by SeriousBuggie** [comment]
Not fixed.
Now flood with
`Localization: No localization: UnrealEd.General.Product (int)`

**Comment by SeriousBuggie** [comment]
Still not fixed on latest v469c preview.

**Comment by NeonKnightOA** [comment]
We could also add a `[General]` section to UnrealEd.int with a `Product="UnrealEd"` line.

Then again, I've been told it's a bad idea to localize dev tools, so...

**Comment by SeriousBuggie** [comment]
Yea. It can be as workaround. But proper way fix code, since it look like not need stuff at all.

**Comment by SeriousBuggie** [comment]
Issue return back in v469d Preview 10.
