### ISSUE TITLE
title bar name bug

### ISSUE THREAD

**Issue by legluondunet** [OldUnreal/UnrealTournamentPatches#40]
Hello,
like you can see on this picture, the name on the title bar is not correct.

![Capture d’écran de 2020-09-25 10-41-41](https://user-images.githubusercontent.com/325405/94246267-d3277600-ff1b-11ea-9529-6d2b153b46b3.png)

Ubuntu 20.04
Desktop Environment: Gnome 3

**Comment by SeriousBuggie** [comment]
> The window title is localized. You're seeing this weird and cryptic name because you don't have the UnrealTournament.int file in your System folder. This file came with the original game and we didn't make any changes to it so it's not part of our patch.

**Comment by stijn-volckaert** [comment]
Indeed. You are missing the UnrealTournament.int file which came with the original game. It should be in the UT/System folder.

**Comment by legluondunet** [comment]
Effectively I just copied system folder from CD without install the game.
It works now, thank you.
