### ISSUE TITLE
[469b] macOS UZ decompression

### ISSUE THREAD

**Issue by 8cH9azbsFifZ** [OldUnreal/UnrealTournamentPatches#404]
Hi there, I have a couple of fresh installer scripts (running in docker) for copying the original game data files (and uncompressing them before ;)). Do you have any plans to integrate with UZ for decompressing the maps?

**Comment by stijn-volckaert** [comment]
I'm not sure what you're asking for. Would you like us to include the ucc decompress tool with the client? If so, would this have to be an app bundle or could it be a standalone executable?

**Comment by 8cH9azbsFifZ** [comment]
Both would be possible. I think integration of the ucc decompress tool (i.e. running in wine) or the new version provided in UZ would be great. So far I have a docker container with wine running ucc to extract the maps. This could be "shipped". A better way is of course to use UZ. But so far I was not able to compile the tool.

**Comment by SeriousBuggie** [comment]
I thought you need directly mention when you mean https://github.com/SeriousBuggie/UZ because currently I suspect you use "UZ" word for different things.

**Comment by 8cH9azbsFifZ** [comment]
Yes, the mentioned UZ repo was meant.

**Comment by stijn-volckaert** [comment]
The app bundle for the 469d version will include the UCC binary. If you're interested in testing, then please come talk to us on Discord.
