### ISSUE TITLE
[469b] Strg+Tab does not work in Windows when UT is in full screen

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#407]
Steps to reproduce:
1) Start an application that uses the [MDI](https://en.wikipedia.org/wiki/Multiple-document_interface) and open at least two documents where you can switch between with STRG+TAB.
2) Start UT in full screen.
3) Switch back to the Windows application and try to switch between documents with STRG+TAB - it does not work.

In v436 it works fine.

**Comment by SeriousBuggie** [comment]
IDK what you mean by `STRG`. Tested now.
Reproduce:
1. Start UT.
2. Press Win key when on fullscreen.
3. On windows try use `Alt+Tab` or `Ctrl+Tab`.

Expected result: `Alt+Tab` bring task switch panel. `Ctrl+Tab` switch between tabs or child windows in MDI.
Actual result: Nothing happen.

**Comment by SeriousBarbie** [comment]
Oh, sorry, STRG is the German shortcut for "Steuerung" what means "Control".

**Comment by an-eternity** [comment]
When UT is minimized from the full screen, Alt+Tab does not work, but Alt+Shift+Tab works.
Same way for MDI forms - Ctrl+Tab does not work, Ctrl+Shift+Tab works.
Sometimes, in this state it also limits the mouse cursor from moving outside of some region in the center of the screen.

I've checked out D3D9, D3D, Vulkan, OpenGL, XOpenGL drivers.
This issue happens only with D3D9 driver.

**Comment by SeriousBuggie** [comment]
Possible related to Nvidia drivers only:
https://www.reddit.com/r/techsupport/comments/2gv5tg/ctrl_tab_not_working/

Possible need disable ShadowPlay (Or it option "Allow desktop capture") in `Nvidia GeForce Experience` app.

**Comment by SeriousBuggie** [comment]
Well. This is RegisterHotKey calls from WinDrv.dll. Very weird.

**Comment by SeriousBuggie** [comment]
Just leave it there. Just in case.
```
	guard(UnregisterHotkeys);
		if (UnregisterHotKey(m_hWnd, 0xC095))
			debugf(TEXT("Unregistered WinDrv hook for Alt+Tab"));
		if (UnregisterHotKey(m_hWnd, 0xC0A0))
			debugf(TEXT("Unregistered WinDrv hook for Ctrl+Tab"));
		if (UnregisterHotKey(m_hWnd, 0xC08D))
			debugf(TEXT("Unregistered WinDrv hook for Alt+Esc"));
		if (UnregisterHotKey(m_hWnd, 0xC0A0))
			debugf(TEXT("Unregistered WinDrv hook for Ctrl+Esc"));
	unguard;
```

**Comment by SeriousBuggie** [comment]
Fixed of v469c Jul 20 2021.
