### ISSUE TITLE
[469x] [Request] - XCGE_DynLoader

### ISSUE THREAD

**Issue by esnesi** [OldUnreal/UnrealTournamentPatches#409]
Description:
Nested ServerPackages within other INI's then UnrealTournament.ini are not being loaded into game without XCGE.

Requirements:
Mapvote MVE2b
469b

Reproduction:
Apply ServerPackages in MVE_Config.ini (Packages="")

Workaround:
Put ServerPackages in UnrealTournament.ini, or enable XCGE.

Request:
Implement DynLoader part of XCGE into 469x, so that nested packages in other INI's are being read.

1601 │     if ( int(ConsoleCommand("get ini:Engine.Engine.GameEngine XC_Version")) >= 11 ) //Only XC_GameEngine contains this variable^M
1602 │     {^M
1603 │         bXCGE_DynLoader = true;^M
1604 │         default.bXCGE_DynLoader = true; //So we get to see if it worked from clients!^M
1605 │         AddToPackageMap( ClientPackage);^M
1606 │     }^M

**Comment by CacoFFF** [comment]
Unreal 227 has such a function built in, I re-created it on XC_Engine using the same opcode number (but with the name AddToPackageMap as seen in UE2), not AddToPackagesMap.
Theoretically, code compiled to work in 227/XC_Engine calling that function would work in UT if said opcode was implemented.

Then two important points:
1: How it handles packages internally.
The 'packagemap' object at one point must be locked into a read-only object, unless clients somehow support in-game downloads.
Older XC_Engine builds would lock it after level initialization, newest will lock it after the first tick though.
In the end where it's locked matters little, but what really matters is that it has to be locked before the first player joins the server.

2: How can modders safely utilize the function.
Call a function with a fixed opcode number (as implemented in 227, XCGE) can cause servers that don't have said opcode implemented, calling a function without a fixed opcode number will add a dependency that will prevent the package from being loaded in older clients (not good for networking).
In the end, mods/mutator makers would have to run checks before calling the function on a server just like XC_Engine dependent does, which means a couple more console commands...
A warning comment should be added to said functions if implemented.

**Comment by CacoFFF** [comment]
One could abstract the pushing of packages to the PackageMap in a less package dependent way by using ConsoleCommand or by implementing it on Mutator class's initialization events.
As a simple default property in mutator could force a v469c server to register the package containing the mutator into the PackageMap, for example.

**Comment by esnesi** [comment]
Issue has been resolved by setting the following in MVE_Config.ini

bOverrideServerPackages=True
MainServerPackages=

**Comment by CacoFFF** [comment]
Note that the AddToPackageMap function has been silently added to can't recall if (v469c or v469d)

**Comment by SeriousBuggie** [comment]
After 30 Dec 2021, so it v469c.
