### ISSUE TITLE
[469b] Decoration can produce Event twice on destroy

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#417]
If you set Event to decoration you can get call this event twice in some cases.
In [Decoration](https://github.com/Slipyx/UT99/blob/a26a3359704873df5a24d0b241a32ca5fc36a8b7/Engine/Decoration.uc) exists 3 places where called Event:
1. function Destroyed()
2. simulated function skinnedFrag(
3. simulated function Frag(

Last two call Destroy at end so call Destroyed and produce call event again.

For example if you add event to WoodenBox:
https://github.com/Slipyx/UT99/blob/a26a3359704873df5a24d0b241a32ca5fc36a8b7/UnrealShare/WoodenBox.uc#L42
```
		if (Health <0) 	
			Frag(Class'WoodFragments',Momentum,FragSize,FragChunks);
```
So firstly will be called Frag(, which produce Event. And call Destroy().
After that will be called Destroyed(). And produce event again.

For fix need nullify Event field after trigger Event from skinnedFrag and Frag.

**Comment by SeriousBuggie** [comment]
Also I am not sure need this fix at all or no.
Destroyed call this:
```
	if( Event != '' )
		foreach AllActors( class 'Actor', A, Event )
			A.Trigger( Self, None );
```
Frag and SkinnedFrag call this:
```
	if ( Event != '' )
		ForEach AllActors( class 'Actor', A, Event )
			A.Trigger( Toucher, pawn(Toucher) );
```
Different parameters send to targets.
So possible both events need and some maps rely on first event and some on second.

**Comment by SeriousBuggie** [comment]
Oh. I look deeply at code.
Frag and SkinnedFrag:
```
	local int i;
	local actor A, Toucher;
	local Fragment s;

	if ( bOnlyTriggerable )
		return; 

	if ( Event != '' )
		ForEach AllActors( class 'Actor', A, Event )
			A.Trigger( Toucher, pawn(Toucher) );
```
It is dumb code.
Toucher is always None here.

Destroyed call is simpler:
```
	if( Event != '' )
		foreach AllActors( class 'Actor', A, Event )
			A.Trigger( Self, None );
```

So firstly we call trigger as Trigger(None, None).
Secondly as Trigger(Decoration(self), None).

So better remmve calls from Frag at all. Call from Destroyed contains more information.
But, exists possibility some map can use this bug in Event chain. And this fix break it. Or some code wait for Both None, and not get it after fix.

**Comment by stijn-volckaert** [comment]
We reviewed the proposed fix but have decided not to accept it because it might break maps/mods that rely on the current behavior and the fix doesn't bring any clear benefits other than a marginal performance improvement.
