### ISSUE TITLE
[469a] Add fullscreen button in menu

### ISSUE THREAD

**Issue by ut99fan** [OldUnreal/UnrealTournamentPatches#42]
I simply see no button to force full screen on Linux/Ubuntu 18.04 I was able to force it with the following config change:

I edited **UnrealTournament.ini** section **[SDLDrv.SDLClient]** with the following settings:
```
StartupFullscreen=True
FullscreenColorBits=32
FullscreenViewportY=1080
FullscreenViewportX=1920
```

This solved the issue for me but average user might struggle with this.

System: Ubuntu 18.04 LTS x64
Theme: Default
Video: 1920x1080 on nVidia Quadro M2200 4GB, driver version 390.138
Four monitors 1920x1080 each. Expanded desktop.

**Comment by stijn-volckaert** [comment]
There are three options to go fullscreen in the game:
1) click the little button in the top-right corner of the in-game menu bar
2) use ALT+ENTER
3) use the togglefullscreen console command

**Comment by ut99fan** [comment]
Thank you for the followup - all useful somehow I didn't notice the "1. option" adding it to the Options-Preferences as button probably still makes sense.

**Comment by stijn-volckaert** [comment]
The next preview build of UT v469e will include a window mode selection dropbox in the in-game preferences menu
