### ISSUE TITLE
[469b] Directx10 Crash after loading map

### ISSUE THREAD

**Issue by Riccardoman** [OldUnreal/UnrealTournamentPatches#432]
![Screenshot (1351)](https://user-images.githubusercontent.com/74624503/120105923-2d3ba380-c15b-11eb-9910-ba8532c3c03a.jpg)
I get this error with both CTF-BT-II-FuriumMineCE and CTF-BT-II-FuriumMineCB3

Using DX 10 render

**Comment by SeriousBarbie** [comment]
With v436 the editor crashes after some camera movements. With 469b I got no issues.

**Comment by SeriousBarbie** [comment]
I also got this error:
![DrawComplexSurface](https://user-images.githubusercontent.com/81397053/120122446-0d32d100-c1a9-11eb-850e-516f01c47ab3.jpg)

**Comment by Riccardoman** [comment]
I just tried reinstalling the patch v469b via archive, not the installer
The crash is still present

**Comment by stijn-volckaert** [comment]
Based on these two crash logs, I would guess that the map has at least one corrupted texture file (likely with a size of 0 bytes). Try loading the map and then open UnrealTournament.log to see which packages the map depends on. Then check the size of each package in their respective folders (keep in mind that some files might be in the Cache folder).

For the next patch, I'll improve the error message and I'll try to include the name of the offending file in the message.

**Comment by Riccardoman** [comment]
![Screenshot (1353)](https://user-images.githubusercontent.com/74624503/121321150-23a9fc80-c90e-11eb-9598-ec590515f0ee.jpg)

Getting a crash also after loading JB-EpicBoy

**Comment by Riccardoman** [comment]
What info do you need to look for the issue?

**Comment by NeonKnightOA** [comment]
[JB-EpicBoy](https://unrealarchive.org/maps/unreal-tournament/jailbreak/E/jb-epicboy_10bc752a.html) is based on CTF-EpicBoy, which has a known issue with certain renderers and which was fixed in a previous version.

**Comment by SeriousBuggie** [comment]
In title stated D3D10. IIRC - it is not well supported.

> D3D10Drv: D3D10Drv has some rendering glitches and does not work in Unreal Editor 2.2

So better try check on D3D9.

Also I suspect this thing not connected with used renderer at all.
So need test it on OpenGL and XOpenGL for determine this,

**Comment by Riccardoman** [comment]
I would love to change render, I'm stuck with DX10 only because the nearest neightbour filter

Is there a way i could enable the nearest neightbour filter on the opengl render?

**Comment by Riccardoman** [comment]
Got another crash, this time probably unrelated to the render

![Screenshot (1354)](https://user-images.githubusercontent.com/74624503/121518675-0ac64780-c9f1-11eb-8166-754565d70062.png)

Map JB-Construction-III

**Comment by NeonKnightOA** [comment]
That's a problem with udemo. [udemo has a separate repository](https://github.com/stijn-volckaert/udemo)

**Comment by Riccardoman** [comment]
I posted the issue on the other repository

Still, is there any possible way to activate the nearest neightbour filter for the textures on opengl? Without messing up the shadows?

**Comment by CacoFFF** [comment]
OpenGLDrv has NoFiltering option (soon to be replaced with ForceNoSmooth), it does not affect lightmaps.

**Comment by Riccardoman** [comment]
That's great ne

**Comment by Riccardoman** [comment]
That's great news! Can't wait to test the new filter with a decent render!

**Comment by Riccardoman** [comment]
That's great news! Can't wait to test the new filter with a decent render!
