### ISSUE TITLE
[469b] Enabling SmartSB v102L unticks font scaling override

### ISSUE THREAD

**Issue by TankBeef** [OldUnreal/UnrealTournamentPatches#433]
Steps to reproduce:
1-Install SmartSB v102L
2-Start UT
3-Go to options, preferences, video, and tick "override font scaling"
4-Go to Start Practice Session, Click on mutators and choose the SmartSB v102L
5-Start game
6-Go back to options preference, video

Expected result:
"Override font scaling" remains ticked
Actual result:
"Override font scaling unticked"

So each time the mutator is disabled, the tiny letters are back, and one has to retick again to get the desired font size back.

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/120743757-48fbcc80-c502-11eb-8a6a-4fedad0c74e5.png)
https://ut99.org/viewtopic.php?f=7&t=13754

Possible this mutator mess with internal variables of UT and disable or override 
> tick "override font scaling"

Try ask author.

**Comment by SeriousBuggie** [comment]
This checkbox:
```
	// In-game font scaling
	InGameFontScalingCheck = UWindowCheckbox(CreateControl(class'UWindowCheckbox', CenterPos, ControlOffset, CenterWidth, 1));
	InGameFontScalingCheck.bChecked = bool(GetPlayerOwner().ConsoleCommand("get Botpack.FontInfo bEnableInGameScaling"));
	InGameFontScalingCheck.SetText(InGameFontScalingText);
```
`	InGameFontScalingText="Override Font Scaling"`

Mutator source is cut. But I found this inside `SmartSB102m.u`:
`set Botpack.FontInfo bEnableInGameScaling False`
So this is make intentionally.
Not an v469b issue. Talk with mutator author.
"Issue" can be closed.

**Comment by TankBeef** [comment]
Ok, thanks Buggie. I apologize, will write to ProAsm. Closing thread.
