### ISSUE TITLE
[469b] Cyrillic support

### ISSUE THREAD

**Issue by cynodesmus** [OldUnreal/UnrealTournamentPatches#434]
When trying to add translation files into Russian, Cyrillic characters are not displayed.
Latin, numbers and punctuation marks are displayed.
Instead of translation - empty.
Checked in Windows.

I tried to look for information in the discussions of gog and steam, but they mention the successful russification of earlier versions: 436 and 451.
 
There should probably be locale support in Engine.u

![rus](https://user-images.githubusercontent.com/16974509/120716380-0670ca80-c4d7-11eb-8182-25f07a312071.png)

**Comment by NeonKnightOA** [comment]
Unreal v227 has Russian localization, and [the localization project](https://github.com/NeonKnightOA/unreal-localization) has Russian among the supported languages (though it needs A LOT of work). So yeah, this should be beared in mind for the next release.

**Comment by stijn-volckaert** [comment]
We internally support pretty much any character set, but the font textures that come with the patch don't contain cyrillic glyphs yet, so any cyrillic character currently shows up as a space. We'll put this on the TODO list for 469c.

**Comment by cynodesmus** [comment]
> Unreal v227 has Russian localization.....
Yes. And, in the Russian-language segment, you can find localization based on text translations of "GSC Game World" (they also dubbed in Russian) and "Oldunreal", with edits by other fans of this game.
Unfortunately, I do not know why there is no close cooperation between the authors of the translations on GitHub.

**Comment by cynodesmus** [comment]
> We'll put this on the TODO list for 469c.

Well, I hope you won't have to wait very long for the next update.
Thank you.

**Comment by stijn-volckaert** [comment]
469c will have several fixes for cyrillic locales.

**Comment by NeonKnightOA** [comment]
And now UT has a proper Russian localization, for which we need testing.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
