### ISSUE TITLE
[469b] Extend fetch info from server in server browser

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#439]
We can get more info from all servers include old if use 
`\level_property\`
`\game_property\`
`\player_property\`
commands.

Some useful things:
Get Health for each player.
Get Spree for each player.
Get current count of spectators.
Get max allowed count of spectators.
Get Remaining time for game.
Get Elapsed Time for game.
Get Author of level.
Get Ideal players count (map property set by mapper).

**Comment by SeriousBuggie** [comment]
For example: send instead of simple `\\status\\`
`\\status\\\\\\game_property\\NumSpectators\\\\game_property\\MaxSpectators\\\\game_property\\RemainingTime\\\\game_property\\ElapsedTime\\\\level_property\\Author\\\\level_property\\IdealPlayerCount\\\\player_property\\Health\\\\player_property\\Spree\\`
And add handling for new data.
Spectators info show near players. 
Players data add to players table. 
All other - into rules table.

**Comment by SeriousBuggie** [comment]
Also Game.GameSpeed is too valuable info. Can be added into rules.

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/174688580-ed53db0a-837f-4656-ac2c-e87287d08e42.png)
Stats logging really useless field now.
There can be version before it, and count spectators on server.

**Comment by SeriousBuggie** [comment]
Also instead of map title there always must be map name (filename). Since map title usually vague and not provide need info. more over it can be same for many maps.

On opposite side map name (filename) exactly describe game type and usually unique.

**Comment by SeriousBuggie** [comment]
For example:
![img](https://user-images.githubusercontent.com/70026933/174689322-59a5edc0-d64e-4781-81fa-8cf0b15a5402.png)

**Comment by sn260591** [comment]
>Also instead of map title there always must be map name (filename). Since map title usually vague and not provide need info. 

It's better to have both fields or a property in the config to bring back the old behavior. The map name can sometimes be long and confusing, like CTF-=AUTHOR=-LongNameV2+fix1.

**Comment by SeriousBuggie** [comment]
Good example of pointless Map title: `Dedicated to Dexie, Edwin and Dem` Good luck figure map name.

**Comment by sn260591** [comment]
> 1. status world log move to last column.

Maybe it's better to move it to the rule table, too?

**Comment by SeriousBuggie** [comment]
Already in rules. Not see any harm for this column here. Plus this is additional compatibility with some 3rd party code.

**Comment by NeonKnightOA** [comment]
> Good example of pointless Map title: `Dedicated to Dexie, Edwin and Dem` Good luck figure map name.

LMAO! Looks like the guy wantes to place that in `LevelEnterText` and put that in `Title` instead. We even had a problem like that in v227j with DmStomp, the map's title was placed in `LevelEnterText`.

I agree totally with the idea of using actual map names rather than Map titles.

**Comment by SeriousBuggie** [comment]
This guy, for one second, THUNDERBOLT. And map in revision 16.
![img](https://user-images.githubusercontent.com/70026933/177038499-eedb8f6d-ba25-43b5-9f57-3bc7e2931bd8.png)
If so experienced mapper able make such easy mistakes, I am silent about other mappers.

**Comment by SeriousBuggie** [comment]
Need add XServerQuery support, since it allow get additional info from it, and since XServerQuery block additional types of queries.
Info about XServerQuery additions can be found at: https://wiki.beyondunreal.com/XServerQuery

**Comment by sn260591** [comment]
My suggestion: a table with servers should have a greater height than tables with players and information. At the moment (with a resolution of 1280x1024), the space is used irrationally:

![s](https://user-images.githubusercontent.com/10724977/180605942-2f0ab422-aac0-4be0-8c10-cdd1478b8fac.png)
