### ISSUE TITLE
[469b] Assertion failed: GetPropertiesSize()>=sizeof(UObject) on macOS

### ISSUE THREAD

**Issue by Refalm** [OldUnreal/UnrealTournamentPatches#453]
While trying to start Unreal Tournament with patch v469b for macOS, the following error appears:
```
Assertion failed: GetPropertiesSize()>=sizeof(UObject) [File:/Users/stijn/utpg/Core/Src/UnClass.cpp] [Line: 1200]

History: UClass::Serialize <- LoadObject <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::CreateExport <- IndexToObject <- ULinkerLoad<<UObject <- ULevelBase::Serialize <- ULevel::Serialize <- LoadObject <- ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- LoadLevel <- UGameEngine::LoadMap <- UGameEngine::Init <- InitEngine <- main
```

Running on i7 Macbook Pro with macOS Big Sur.

The file ~/Library/Application Support/Unreal Tournament/System/UnrealTournament.log is empty.

**Comment by stijn-volckaert** [comment]
This error indicates that one of the .u files your client attempts to use does not match its C++ counterpart. The fact that your log file is empty means the most likely suspects are Core.u and Engine.u. Did you follow the installation steps listed here?

https://github.com/OldUnreal/UnrealTournamentPatches#macos-installation

My guess would be that you accidentally copied over at least one of the .u packages that came with the older patches.

**Comment by Refalm** [comment]
Thanks, it works now :)
