### ISSUE TITLE
[469b] 436 clients cannot see mesh "Missile" on a 469c beta server

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#454]
When I set up a 451 UT server years ago, I customized the WarheadAmmo in order to see that ammo:
```
class WarheadAmmoSB extends WarheadAmmo;

defaultproperties
{
	AmmoAmount=1
	Mesh=LodMesh'BotPack.Missile'
	PickUpMessage="You picked up a Redeemer missile."
	PickupViewMesh=LodMesh'BotPack.Missile'
	UsedInWeaponSlot(0)=1
	bCollideActors=True
}
```
and "WarheadAmmo" is replaced with "WarheadAmmoSB" in BaseMutator's CheckReplacement() function. I'm sure that clients could see the ammo on that 451 server for years. Recently I updated the server to v469b and then to 469c beta. Now when joining with a 469b client, the WarheadAmmoSB is visible, but when joining with a 436 client, its not.

Did anything change with Mesh replication?

**Comment by SeriousBuggie** [comment]
In v469a changed defaultproperties:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/WarHeadAmmo.uc#L6
```
defaultproperties
{
      MaxAmmo=2
      PickupViewMesh=LodMesh'Botpack.missile'
      Mesh=LodMesh'Botpack.missile'
}
```
Server replicate only data which different from assumed defaults.
On v451 difference from base class defaults exists in PickupViewMesh and Mesh. So it is replicated.
Now, starting from v469a server assume PickupViewMesh and Mesh not change from base class. So not replicate it.
But v436 use different defaults. So this create desync.

**Comment by SeriousBarbie** [comment]
Thanks. Any hints to solve this? I'd like to keep WarheadAmmoSB a child of WarheadAmmo.

**Comment by SeriousBuggie** [comment]
You can try make intermediate class with defaults which 100% not match with anything and extends `WarheadAmmoSB` from it.
For example:
```
class WarheadAmmoFix extends WarheadAmmo;

defaultproperties
{
      PickupViewMesh=LodMesh'Botpack.hbox'
      Mesh=LodMesh'Botpack.hbox'
}
```
`class WarheadAmmoSB extends WarheadAmmoFix;`

Or try set values of `PickupViewMesh` and `Mesh` later on run-time, when defaults be different:
```
class WarheadAmmoSB extends WarheadAmmo;

function PreBeginPlay()
{
      PickupViewMesh=LodMesh'Botpack.missile';
      Mesh=LodMesh'Botpack.missile';
}

defaultproperties
{
	AmmoAmount=1
	Mesh=LodMesh'BotPack.hbox'
	PickUpMessage="You picked up a Redeemer missile."
	PickupViewMesh=LodMesh'BotPack.hbox'
	UsedInWeaponSlot(0)=1
	bCollideActors=True
}
```

Or set values inside simulated call:
```
class WarheadAmmoSB extends WarheadAmmo;

simulated function PostNetBeginPlay()
{
      PickupViewMesh=LodMesh'Botpack.missile';
      Mesh=LodMesh'Botpack.missile';
}

defaultproperties
{
	AmmoAmount=1
	Mesh=LodMesh'BotPack.Missile'
	PickUpMessage="You picked up a Redeemer missile."
	PickupViewMesh=LodMesh'BotPack.Missile'
	UsedInWeaponSlot(0)=1
	bCollideActors=True
}
```

Not sure about each method. Possible some not work.

**Comment by stijn-volckaert** [comment]
We are reverting this change in 469c
