### ISSUE TITLE
[469a][ALAudio] The redeemer rocket does not emit a flight sound when controlled in alternative mode

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#46]

**Comment by SeriousBuggie** [comment]
You sure? For me sound stay on fire point and not follow by rocket, but if I am return rocket and fly near I can hear it from my player model.
Cluster and Galaxy - fine.

**Comment by sn260591** [comment]
> For me sound stay on fire point and not follow by rocket, but if I am return rocket and fly near I can hear it from my player model.
Yes, this is a more accurate description of the problem.

**Comment by CacoFFF** [comment]
Fixed for v469b

**Comment by gargul03** [comment]
I have had a similiar issue yesterday on Face server, my minigun didn't emit any shooting sounds, it was just silent, again it was an occasional glitch, just like there:
`https://github.com/OldUnreal/UnrealTournamentPatches/issues/78#issuecomment-703267626`

**Comment by SeriousBuggie** [comment]
Fixed in v469b. Confirmed.
