### ISSUE TITLE
[469b] Queen produce shield without respect DrawScale factor

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#462]
![img](https://user-images.githubusercontent.com/70026933/122675042-61493800-d1e0-11eb-8041-2d90f4d5fdb0.png)
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UnrealI/Queen.uc#L99
```
function SpawnShield()
{
	Shield = Spawn(class'QueenShield',,,Location + 150 * Vector(Rotation));
	if (Shield != None)
	    Shield.SetBase(self);
}
```

Fix (Thanks Barbie for code):
![img](https://user-images.githubusercontent.com/70026933/122675219-18de4a00-d1e1-11eb-950e-8c215eaa86c7.png)
```
function SpawnShield()
{
	Shield = Spawn(class'QueenShield',,,Location + 150 * DrawScale * Vector(Rotation));
	if (Shield != None)
	{
		if (self.default.DrawScale != DrawScale)
		{
			Shield.DrawScale = DrawScale;
			Shield.SetCollisionSize(Shield.CollisionRadius * DrawScale, Shield.CollisionHeight * DrawScale);
		}
	    Shield.SetBase(self);
	}
}
```

**Comment by SeriousBarbie** [comment]
Also shield should be destroyed when Queen teleports.

**Comment by SeriousBuggie** [comment]
> Also shield should be destroyed when Queen teleports.

Already fixed in v469a:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UnrealI/Queen.uc#L442
```
				if ( Shield != None && !Shield.bDeleteme )
					Shield.Destroy();
```
