### ISSUE TITLE
UT crashing when Saving game in Unreal

### ISSUE THREAD

**Issue by digrizzle** [OldUnreal/UnrealTournamentPatches#470]
Mac OS 10.15.7 UT 439b.
UT crashes in Unreal single player when saving a game.
It has been fine for a few days, but it's started to crash again and no idea what's causing it. Attached crash log if any use.
It was working fine. I then installed the RtNP HD single player game which played fine but then crashed on saving. I removed all RtNP HD files and now UT crashes when saving single player unreal.
99% sure it's the sound system...

Love the work on UT as only just reawaken my love for it since the update to 64bit, not been able to play UT for a long long time.

Log: Log file open, Mon Jun 21 20:48:06 2021
Init: Name subsystem initialized
Init: Version: 469
Init: Compiled: Feb 28 2021 11:10:45
Init: Command line: -psn_0_12077956
Init: Base directory: 
Init: Character set: Unicode
Init: Object subsystem initialized
Init: OS: MacOS 10.9.7
Init: CPU Detected: Unknown processor ()
Init: CPU Features:
Init: Timer Frequency=-18099.370910 MHz - Timing Source = gettimeofday
Init: Unreal engine initialized
Init: Detected 0 joysticks
Init: SDLClient initialized.
Init: Lighting subsystem initialized
Init: Rendering initialized
Log: LoadMap: Entry
Log: Game class is 'UTIntro'
Log: Bringing Level Entry.MyLevel up for play (0)...
ScriptLog: InitGame: 
ScriptLog: Base Mutator is Entry.Mutator0
Log: Browse: UT-Logo-Map.unr?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
Log: LoadMap: UT-Logo-Map.unr?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
Log: Collecting garbage
Log: Purging garbage
Log: Unloading: Package Render
Log: Garbage: objects: 15988->15987; refs: 178766
Log: Game class is 'UTIntro'
Log: Bringing Level UT-Logo-Map.MyLevel up for play (0)...
ScriptLog: InitGame: ?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
ScriptLog: Base Mutator is UT-Logo-Map.Mutator0
Init: Initialized moving brush tracker for Level UT-Logo-Map.MyLevel
Log: Created and initialized a new SDL viewport.
ScriptLog: Team 3
ScriptLog: Login: DiGriz
Log: Possessed PlayerPawn: TMale2 UT-Logo-Map.TMale0
Init: Input system initialized for SDLViewport0
Log: TTS: No output filename specified.
Log: TTS: Native MacOS X text-to-speech is NOT enabled.
Log: Opening SDL viewport.
Log: Loaded render device class.
Log: Initializing OpenGLDrv...
Log: binding /System/Library/Frameworks/OpenGL.framework/Libraries/libGL.dylib
Log: SDLDrv SwapInterval = 0
Init: GL_VENDOR     : NVIDIA Corporation
Init: GL_RENDERER   : NVIDIA GeForce GTX 680MX OpenGL Engine
Init: GL_VERSION    : 2.1 NVIDIA-14.0.32 355.11.11.10.10.143
Init: Device supports: GL_ARB_texture_compression
Init: Device supports: GL_EXT_texture_compression_s3tc
Init: Device supports: GL_ARB_texture_compression_rgtc
Init: Device supports: GL_EXT_texture_shared_exponent
Init: Device supports: GL_EXT_texture_filter_anisotropic
Init: Device supports: GL_ATI_texture_env_combine3
Init: Device supports: GL_EXT_texture_lod_bias
Init: Device supports: GL_EXT_secondary_color
Init: Device supports: GL_ARB_multitexture
Init: Device supports: GL_EXT_multi_draw_arrays
Init: Device supports: GL_ARB_vertex_program
Init: Device supports: GL_ARB_fragment_program
Init: Device supports: GL_ARB_texture_non_power_of_two
Init: Device supports: GL_ARB_framebuffer_object
Init: Depth bits: 16
Log: 8 Texture Mapping Units found
Log: 16 Shader Texture Mapping Units found
Init: MaxAnisotropy: 16
Log: BufferActorTris: 1
Log: UseDetailAlpha: 1
Init: ALAudio: Trying to autodetect HRTF. Note: Autodetection may only work with USB headphones.
Init: ALAudio: Trying to use default device
Init: ALAudio: We are using OpenAL device: OpenAL Soft 
Init: ALAudio: OutputRateNum 6(48000 Hz) SampleRateNum 5 (44100 Hz)
Init: ALAudio: Audio hardware supports 255 mono (usually sound) and 1 stereo (usually music) sources.
Init: ALAudio: OpenALSoft extension ALC_SOFT_HRTF found.
Init: ALAudio: HRTF is disabled.
Init: OpenAL Effects extension version 1.0 found.
Init: ALAudio: EFX initialized.
Init: ALAudio: Version 1.1 ALSOFT 1.20.0 found
Init: ALAudio subsystem initialized.
Init: Game engine initialized
Log: Startup time: 1.456255 seconds.
Log: Entering main loop.
Log: ALAudio: playing utmenu23 Unreal Tournament Menu (Impulse Tracker 2.14v5 IT 1.00)
ScriptLog: Creating root window: olroot.oldskoolrootwindow
ScriptLog: Using Configured GUI Scale: 1.500000
udemo: Startup hack successful!
Log: UDEMO: Successfully got list of demos
Log: Export travel for: DiGriz
Log: Exporting travelling actors for UT-Logo-Map.TMale0
Log: URL: Adding default option Name=DiGriz
Log: URL: Adding default option Class=BotPack.TMale2
Log: URL: Adding default option team=3
Log: URL: Adding default option skin=SoldierSkins.hkil
Log: URL: Adding default option Face=SoldierSkins.Tensor
Log: URL: Adding default option Voice=BotPack.VoiceMaleTwo
Log: Browse: UT-Logo-Map.unr?Game=Botpack.LadderLoadGame?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
Log: LoadMap: UT-Logo-Map.unr?Game=Botpack.LadderLoadGame?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
Dev: ALAudio: UpdateBufferThread terminated
Log: UDEMO: Successfully got list of demos
Init: Shut down moving brush tracker for Level UT-Logo-Map.MyLevel
Log: Collecting garbage
Log: Purging garbage
Log: Unloading: Package SoldierSkins
Log: Unloading: Package OpenGLDrv
Log: Unloading: Package ALAudio
Log: Unloading: Package OldModelsMenus
Log: Unloading: Package OldModels
Log: Unloading: Package GenFluid
Log: Unloading: Package Male1Skins
Log: Unloading: Package NWUltraGoreSSEb
Log: Garbage: objects: 23616->22839; refs: 264051
Log: Game class is 'LadderLoadGame'
Log: Bringing Level UT-Logo-Map.MyLevel up for play (0)...
ScriptLog: InitGame: ?Game=Botpack.LadderLoadGame?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
ScriptLog: Base Mutator is UT-Logo-Map.Mutator1
Log: Spawning new actor for Viewport SDLViewport0
ScriptLog: Team 3
ScriptLog: Login: DiGriz
Log: Possessed PlayerPawn: TMale2 UT-Logo-Map.TMale20
Log: Incoming travelling actor of class Botpack.TMale2
Init: Initialized moving brush tracker for Level UT-Logo-Map.MyLevel
Log: ALAudio: playing utmenu23 Unreal Tournament Menu (Impulse Tracker 2.14v5 IT 1.00)
Log: URL: Adding default option Name=DiGriz
Log: URL: Adding default option Class=BotPack.TMale2
Log: URL: Adding default option team=3
Log: URL: Adding default option skin=SoldierSkins.hkil
Log: URL: Adding default option Face=SoldierSkins.Tensor
Log: URL: Adding default option Voice=BotPack.VoiceMaleTwo
Log: Browse: Index.unr?load=22?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo
Log: LoadMap: ../Save/Save22.usa?Game=Botpack.LadderLoadGame?Name=DiGriz?Class=BotPack.TMale2?team=3?skin=SoldierSkins.hkil?Face=SoldierSkins.Tensor?Voice=BotPack.VoiceMaleTwo?load
Dev: ALAudio: UpdateBufferThread terminated
Log: UDEMO: Successfully got list of demos
Init: Shut down moving brush tracker for Level UT-Logo-Map.MyLevel
Log: Collecting garbage
Log: Purging garbage
Log: Unloading: Package UT-Logo-Map
Log: Unloading: Package utmenu23
Log: Garbage: objects: 33696->33184; refs: 679934
Log: Spawning new actor for Viewport SDLViewport0
ScriptLog: Team 3
ScriptLog: Login: DiGriz
Log: Possessed PlayerPawn: TMale2 Save22.TMale20
ScriptLog: All inventory from DiGriz is accepted
Init: Initialized moving brush tracker for Level Save22.MyLevel
Log: ALAudio: playing digsh Shared Dig (Impulse Tracker 2.14v3 S3M)
ScriptLog: Q= 1
Init: Shut down moving brush tracker for Level Save22.MyLevel
Log: Unloading: Package Save22
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing USDLClient::ShutdownAfterError
Exit: ALAudio subsystem shut down.
Exit: UALAudioSubsystem::ShutdownAfterError
Exit: UOpenGLRenderDevice::ShutdownAfterError
Log: HandleError
Exit: Exiting.
Uninitialized: Log file closed, Mon Jun 21 20:48:49 2021

**Comment by digrizzle** [comment]
Okay stranger and stranger, it's working now can save. Not changed anything I played the UT ladder for a bit then tried SP Unreal and it worked. Only thing different was the game had reset the skin to Necris when it was on Warbot. Tried again with Warbot and still saved so issue is not HD skins.

**Comment by stijn-volckaert** [comment]
Feel free to reopen this ticket if you find any way to reproduce this!
