### ISSUE TITLE
[469b] UnrealEd crash on save map after add array of classes to the custom actor

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#475]
Reproduce:
1. Start new map in UnrealEd.
2. Create new `Actor` `MyLevel.MyActor`.
3. Compile `MyActor` code.
4. Save map.
5. Add line into `MyActor` code:
`var class<Inventory> Classes[100];`
6. Compile `MyActor`.
7. Save map.

Expected result: Map saved.
Actual result: UnrealEd crash:
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: FArchiveSaveTagExports<<Obj <- FPropertyTag::SerializeTaggedProperty <- SaveStream <- 
UStruct::SerializeTaggedProperties <- (Classes[0]) <- UObject::Serialize <- (MyActor2 MyLevel.MyActor0) 
<- AActor::Serialize <- FArchiveSaveTagExports<<Obj <- ULevelBase::Serialize <- ULevel::Serialize <- 
FArchiveSaveTagExports<<Obj <- TagExports <- UObject::SavePackage <- UEditorEngine::Exec <- 
(MAP SAVE FILE="Maps\DM-!!!!test_mover.unr") <- WEditorFrame::OnCommand <- 
WM_HSCROLL <- MessagePump <- MainLoop
---------------------------
ОК   
---------------------------
```

If you remove MyActor from map before modify - no crash.

**Comment by SeriousBuggie** [comment]
Same crash if you add Array of any actors:
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: FArchiveSaveTagExports<<Obj <- FPropertyTag::SerializeTaggedProperty <- SaveStream <- UStruct::SerializeTaggedProperties <- (History[7]) <- UObject::Serialize <- (MyWarpZoneInfo MyLevel.MyWarpZoneInfo51) <- AActor::Serialize <- FArchiveSaveTagExports<<Obj <- FPropertyTag::SerializeTaggedProperty <- SaveStream <- UStruct::SerializeTaggedProperties <- (markedWarpZone[0]) <- UObject::Serialize <- (WarpZoneMarker MyLevel.WarpZoneMarker2941) <- AActor::Serialize <- FArchiveSaveTagExports<<Obj <- FPropertyTag::SerializeTaggedProperty <- SaveStream <- UStruct::SerializeTaggedProperties <- (NavigationPointList[0]) <- UObject::Serialize <- (LevelInfo MyLevel.LevelInfo0) <- AActor::Serialize <- FArchiveSaveTagExports<<Obj <- ULevelBase::Serialize <- ULevel::Serialize <- FArchiveSaveTagExports<<Obj <- TagExports <- UObject::SavePackage <- UEditorEngine::Exec <- (MAP SAVE FILE="DM-!!!ripper_warp_bug.unr") <- WEditorFrame::OnCommand <- WM_HSCROLL <- MessagePump <- MainLoop
---------------------------
ОК   
---------------------------
```

**Comment by SeriousBuggie** [comment]
Also Editor crash if you add any new properties (except primitives, like int) at all, since it fill with garbage. And if this pointer produce crash.

**Comment by SeriousBuggie** [comment]
I think need store object size before recompile class, and compare it with new one after compile class. If size bugger, hen need walk over all exists objects of this class and set default value to new fields.
Since you can not set specific default value on first compile new field, there possible enough fill memory with zeroes.

**Comment by SeriousBuggie** [comment]
Also related thing: on reorder fields data mess too.

Reproduce:
1. Start UnrealEd.
2. Make Actor MyActor with next code:
```js
class MyActor expands Actor;
var() int A;
var() int B;
```
3. Compile it.
4. Place on map.
5. Fill values as : A = 10, B = 20
6. Edit class as (reorder fields):
```js
class MyActor expands Actor;
var() int B;
var() int A;
```
7. Compile it and check actor on map.

Expected result: A = 10, B = 20
Actual result: A = 20, B = 10

Reason is same as for original issue - data still same, even if object layout changed.

So possible need save old object layout before compile, later compare it with new one. If there notable difference, need walk over all objects of this class, export all properties for old layout, fill with defaults and import properties back.

**Comment by SeriousBuggie** [comment]
Again blow up self and my work since add to class new Sound property, while actor of this subtype be paced on map.
On attempt save all goes to hell.
I even not able replace actor with fresh one. Or reopen map. All screwed.

**Comment by stijn-volckaert** [comment]
v469-RC3 includes a fix for this issue. This fix needs to be enabled manually since it might have side effects. Please refer to the change log for further details
