### ISSUE TITLE
[469a] Progress messages disappear when the voice menu is open

### ISSUE THREAD

**Issue by FrancescoBis** [OldUnreal/UnrealTournamentPatches#48]
As you can see from these two attached screenshots, the progress message (the message which in this case is yellow and states "You have the flag, return to base!") disappears when the player opens the voice menu.
![pm_visible_no_voice_menu](https://user-images.githubusercontent.com/11650573/94345436-08b88600-0026-11eb-9e3a-d83835c826d4.png)
![pm_hidden_voice_menu](https://user-images.githubusercontent.com/11650573/94345435-06562c00-0026-11eb-85b8-bdb22ccae410.png)

I believe the issue is related to unrealscript. The issue is there in patch versions 469 and 436, not sure about the other ones. I was using D3D12 when those screenshots were taken.

**Comment by gargul2** [comment]
> disappears when the player opens the voice menu.

Another vocie menu glitch, perhaps related https://github.com/OldUnreal/UnrealTournamentPatches/issues/44 ?

**Comment by racing-online** [comment]
It is not the bug, rather done to avoid overlapping of progress messages with voice menu. Developers may change it though, if they think it is no longer supposed to run with 640x480 screens.

**Comment by SeriousBuggie** [comment]
Wrong title. Not "disappear" - "hidden when voice menu on the screen".
Because "disappear" can be understand as "disappear and not return anymore after one single draw voice menu".

And yes it is not a bug. It is make intentionally. So big question - allowable change or no.

**Comment by FrancescoBis** [comment]
I consider it an issue since it can lead to not being able to read important notifications like the one in the screenshot, and may negatively affect the end result of a match.

**Comment by SeriousBuggie** [comment]
As far I understand agreement with Epic allow not all changes.
@stijn-volckaert can answer more specifically.

**Comment by FrancescoBis** [comment]
Thanks, I didn't know it.

**Comment by SeriousBuggie** [comment]
You better argue your point of view here. It is increase chance of fix. Without that it look like unreasonable desire.
> When I play CTF I usually stand on the flag base when nobody is around, so that when the flag appears it gets grabbed automatically, I also use a low volume when playing games with a lot of sound FX, it has happened a few times that I was using the voice menu to send orders to my teammates and I couldn't know I grabbed the flag.

**Comment by stijn-volckaert** [comment]
This was definitely done on purpose, as you can see in UTMenu/UTConsole.uc:

```
 268 │ function ShowSpeech()
 269 │ {
 270 │     if ( bUWindowActive )
 271 │         return;
 272 │     bShowSpeech = True;
 273 │     if(!bCreatedRoot)
 274 │         CreateRootWindow(None);
 275 │ 
 276 │     Root.SetMousePos(0, 132.0/768 * Root.WinWidth);
 277 │     SpeechWindow.SlideInWindow();
 278 │     if ( ChallengeHUD(Viewport.Actor.myHUD) != None )
 279 │         ChallengeHUD(Viewport.Actor.myHUD).bHideCenterMessages = true;
 280 │ }
 281 │ 
 282 │ function HideSpeech()
 283 │ {
 284 │     bShowSpeech = False;
 285 │     if ( ChallengeHUD(Viewport.Actor.myHUD) != None )
 286 │         ChallengeHUD(Viewport.Actor.myHUD).bHideCenterMessages = false;
 287 │ 
 288 │     if (SpeechWindow != None)
 289 │         SpeechWindow.SlideOutWindow();
 290 │ }
```

I agree that this design decision may no longer make sense at screen resolutions higher than 640x480, but I'm not sure if this is something that should be changed in the base game since mods like XConsole could easily make the necessary change. I'll leave this ticket open while I discuss this with the other devs.

**Comment by FrancescoBis** [comment]
Thanks, I didn't know the progress messages general visibility was set from UTConsole.
I think the actual problem if nothing is hidden would be the overlapping between the voice menu and the progress messages, that's only because the voice message menu extends towards the bottom and the progress messages are usually displayed at the bottom. Maybe to change this behavior the voice menu needs to be able to extend just in a limited space that won't overlap any progress messages on screen, after all the voice menu supports scrolling through menu items when they exceed the menu boundaries.
