### ISSUE TITLE
[469b] Cluster3D play music outside proper range of patterns

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#481]
Cluster3D:

https://user-images.githubusercontent.com/70026933/124010961-2d43f300-d9e8-11eb-97a5-a5acf92bee7e.mp4

OpenAL:

https://user-images.githubusercontent.com/70026933/124011011-36cd5b00-d9e8-11eb-99f2-8b6a90c944d8.mp4

Reproduce:
1. Place file: [Mech8.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6743120/Mech8.zip)
2. Start DM-Zeto and wait near 5:30.

Expected result: Cluster3D on end of loop start play track from begin.
Actual result: Cluster3D play which must not play. only after that restart loop.

**Comment by stijn-volckaert** [comment]
There's not much we can do about this. Cluster just hands the music track to FMOD and FMOD takes it from there. There is no FMOD API that allows us to skip empty patterns such as the one at the end of Mech8
