### ISSUE TITLE
[469b] bWorldLog=True saves utstats log files in wrong directory

### ISSUE THREAD

**Issue by scottadkin** [OldUnreal/UnrealTournamentPatches#482]
I've just noticed that if bWorldLog is set to True it will save the log files in C:/ instead of C:/UnrealTournament/Logs. I have been telling people since 469 to put both bLocalLog=False(always been the case), and bWorldLog=False(since 469) to have utstats/node utstats to savelog files, think I've just missed this bug, only found out after having problems with monsterhunt saving logs in different place.

Expected behaviour (451 and below):
- UTStats log file saved to UnrealTournament/Logs

Current 469B behaviour:
- UTStats log file saved to Driver root directory e.g C:/

Temporary fix:
Set bWorldLog to False.

**Comment by stijn-volckaert** [comment]
I definitely see a 469-specific problem with world logs, but they shouldn't break UTStats... On my Windows system, UTStats still works and it logs into the correct directory with bWorldLog=true.

Could you check what you have under [Engine.StatLog] and [UTStatsBeta4_2.UTStats] in UnrealTournament.ini ?

**Comment by scottadkin** [comment]
Spotted the problem, WorldLogDir=, I guess when I let UT create a new UnrealTournament.ini that was the default value.

```
[Engine.StatLog]
LocalBatcherURL=
LocalBatcherParams=
LocalStatsURL=
WorldBatcherURL=
WorldBatcherParams=
WorldStatsURL=
LocalLogDir=../Logs
WorldLogDir=
bLogTypingEvents=False
bWorldBatcherError=False
```

I do not have UTStatsBeta4_2.UTStats in my UnrealTournament.ini

**Comment by stijn-volckaert** [comment]
Indeed. This explains why the world log is written into the root folder. This is likely our fault so I've pushed a fix for 469c.

Even with this bug, UTStats should still create its logs in UT/Logs, however. Are you sure that no logs are written there at all? With UTStats + bLocalLog=False + bWorldLog=True, you're supposed to see _two_ log files. One is the world log file, which currently gets written to the root folder, and the other is the local log/utstats file, which gets written to the local log folder (UT/Logs in your case).

**Comment by scottadkin** [comment]
I changed to bLocalLog=False and bWorldLog=True and the files have been created in both directories like you said.

**Comment by stijn-volckaert** [comment]
ok so then the only issue is that I wiped the default value for WorldLogDir in 469a. I will undo that change and also reset empty in values to the original default value. I'll close this report since this probably won't need any follow-up discussion.
