### ISSUE TITLE
[469b] Add filters for Server browser

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#489]
Filter bar. You can filter here by player name, server name, mutator, admin name/email and so on.

![img](https://user-images.githubusercontent.com/70026933/124813400-82927e00-df6d-11eb-892f-2b581c6b7e1c.png)

Mutator:
![img](https://user-images.githubusercontent.com/70026933/124813617-c4bbbf80-df6d-11eb-8cc2-03c4057189b3.png)
![img](https://user-images.githubusercontent.com/70026933/124813837-fcc30280-df6d-11eb-9375-3ad93953b72d.png)
![img](https://user-images.githubusercontent.com/70026933/124814181-5c211280-df6e-11eb-8690-4b12885f2509.png)

Email:
![img](https://user-images.githubusercontent.com/70026933/124814300-81158580-df6e-11eb-8a43-8bbf5704bd43.png)

Player:
![img](https://user-images.githubusercontent.com/70026933/124814419-a4d8cb80-df6e-11eb-9ebb-06f775454813.png)

Bot skill:
![img](https://user-images.githubusercontent.com/70026933/124814759-11ec6100-df6f-11eb-8ac1-3ad6c7ebf708.png)

Game type:
![img](https://user-images.githubusercontent.com/70026933/124814920-406a3c00-df6f-11eb-821e-745367149f86.png)

And you can use checkboxes for exclude full, empty, or password-protected servers.

**Comment by NeonKnightOA** [comment]
Giving it a bump!

I suppose these changes require a lot of new code, isn't it?

**Comment by SeriousBuggie** [comment]
Code already written. But need resolve some possible compatibility issues with possible exists code.

**Comment by an-eternity** [comment]
Very nice idea.
And it is important to use a case-insensitive search (or make it optional / user selectable), because in the current UBrowser filtering code it is case-sensitive which brings some problems...

**Comment by SeriousBuggie** [comment]
Search case-insensative. 
Changes accepted for next version.
