### ISSUE TITLE
[469b] Gamma in fullscreen mode D3D9 not implemented for windowed mode

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#491]
Will be good if gamma visible in fullscreen mode can be applied to windowed mode and taken screenshots.

Currently windowed mode and screenshots too dark in comparison with fullscreen mode.

IDK possible this at all or not.

**Comment by SeriousBuggie** [comment]
For screenshots I found option GammaCorrectScreenshots for D3D9. Work fine if you take sshot from UT.

**Comment by stijn-volckaert** [comment]
Gamma correction would need to be implemented in the shaders to get it to work in windowed mode. I agree this would be nice to have, but we don't have anyone actively working on D3D9Drv. The main renderers we do development for are XOpenGLDrv and OpenGLDrv.

**Comment by SeriousBuggie** [comment]
Added shader gamma into d3d9. 
Activated by UseShaderGamma in render settings (in game via command `preferences`, via advanced render settings or via INI file). Can be 0 - Never, 1 - Only for non-fullscreen modes and 2 - Always.
For mode 0 and 1 in fullscreen mode will be used gamma ramp as before.

![img](https://github.com/user-attachments/assets/4c9d73c9-3852-418f-bfeb-7ab9f5f299ad)
![img](https://github.com/user-attachments/assets/d18e53db-299f-480f-8824-d9b9c5094a81)
