### ISSUE TITLE
[469b] Mac OS Monterey DB4

### ISSUE THREAD

**Issue by Ubsefor** [OldUnreal/UnrealTournamentPatches#495]
<details>
<summary>Crash:</summary>

```
WARNING: Using system ini file: /Applications/Unreal Tournament.app/Contents/MacOS/System/UnrealTournament.ini
WARNING: Using user ini file: /Applications/Unreal Tournament.app/Contents/MacOS/System/User.ini
2021-07-19 22:05:49.457 UnrealTournament[15970:433791] -[__NSCFData _fastCharacterContents]: unrecognized selector sent to instance 0x7fcd39d39f20
General protection fault!

History: 

Exiting due to error
Saving session...completed.
```

</details>

**Comment by stijn-volckaert** [comment]
Could you give us some details about your hardware? What kind of machine are you trying to run this on? What is your exact version of Monterey?

**Comment by Ubsefor** [comment]
Possibly related to this: [crossover issue](https://www.codeweavers.com/support/forums/general/?t=27;msg=240166#c3)

I’m running a hackintosh, Monterey developer beta 3. The hardware is working, integrated graphics support metal/opengl frameworks, the libraries are OK and update. 

If there’s a way I can capture logs – I’m willing to help.

**Comment by Ubsefor** [comment]
UT seems to be working correctly on Monterey DB2. Don’t know what the reason is, but it seems like DB3 is kinda buggy in many aspects. Closing this issue until I test it on DB4 .

**Comment by Ubsefor** [comment]
Reopening this issue, as it now migrated to Monterey Developer Beta 4. The culprit is System Integrity Protection, as when it is turned off, the game launches and works just fine.

**Comment by Ubsefor** [comment]
It appears, the connected airpods are actually causing the issue, not the SIP: [same error in bug report of other software](https://forum.shadow.tech/bug-reporting-56/client-crashes-on-macos-monterey-beta-4-3001?postid=16805#post16805)

Will write a bug report to Apple, hope they fix it.

**Comment by Ubsefor** [comment]
Fixed in newer versions, so closing
