### ISSUE TITLE
[469b] Crashes at startup on MacOS

### ISSUE THREAD

**Issue by DQKrait** [OldUnreal/UnrealTournamentPatches#497]
Hello guys, first of all, thanks for your great efforts in maintaining the game!!

I'm trying to run the MacOS version for the first time. It crashes when trying to load CityIntro.unr:

```
History: ULinkerLoad::Serialize <- FUnrealfileSummary<< <- LoadSummary <- ULinkerLoad::ULinkerLoad <-  
UObject::GetPackageLinker <- ULinkerLoad::VerifyImport <- ValidateImports <- ULinkerLoad::Verify <- 
ULinkerLoad::ULinkerLoad <- UObject::GetPackageLinker <- UObject::StaticLoadObject <- VerifyPackages <- 
UGameEngine::LoadMap <- LocalMapURL <- UGameEngine::Browse <- UGameEngine::Init <- InitEngine <- main
```
```
ScriptLog: InitGame: 
ScriptLog: Base Mutator is Entry.Mutator0
Log: Browse: CityIntro.unr?Name=Player?Class=Botpack.TMale2?team=255?skin=SoldierSkins.blkt?Face=SoldierSkins.Othello
Log: LoadMap: CityIntro.unr?Name=Player?Class=Botpack.TMale2?team=255?skin=SoldierSkins.blkt?Face=SoldierSkins.Othello
Critical: appError called:
Critical: fread failed: BufferCount=672 Error=1
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing USDLClient::ShutdownAfterError
Critical: Propagating Error
Warning: Failed to load "city": Throwing C++ exception for error logging.
Warning: Failed to load "CityIntro.unr": Throwing C++ exception for error logging.
Warning: Failed to load "Level None.MyLevel": Throwing C++ exception for error logging.
Critical: Error reentered: Failed to enter CityIntro.unr: Throwing C++ exception for error logging
```
[Full UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6858236/UnrealTournament.log)

I followed installation instructions from the README: copied the app package to ~/Applications/, then copied Maps, Music, Sounds, Textures to ~/Library/Application Support/. 

Game folders are taken from my old trusty v436 GOTY Windows installation.

I've also tried putting game folders inside of the application package instead of Application Support. It had no effect.

I run macOS Mojave 10.14.6 (18G6020) on a MacBook Pro Mid 2014.

**Comment by stijn-volckaert** [comment]
Hi @DQKrait . The Maps/Music/Sounds/Textures folders should go into ~/Library/Application Support/Unreal Tournament/

The game won't find the files if they're simply in ~/Library/Application Support/

**Comment by DQKrait** [comment]
Hi @stijn-volckaert. Sorry if I was unclear, the folders are indeed in `~/Library/Application Support/Unreal Tournament/`, as specified in README. I'm pretty sure the path is correct because when I try to launch the game a `System` folder gets created in `~/Library/Application Support/Unreal Tournament/`, same place where I have my other game folders.

**Comment by stijn-volckaert** [comment]
If this is still happening, would you mind uploading the city.utx file from your Textures folder so I can take a look at it?

**Comment by DQKrait** [comment]
Hi @stijn-volckaert,

I just tried again, this time re-installing UT GOTY from the original installer and taking the data folders from the clean installation, instead of my old Windows installation. This time it worked, the game is running just fine!

Here's the city.utx from the game version where the mod **didn't** work, just in case you want to look further into the problem. Otherwise, feel free to close the issue :)
[city.utx.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7281616/city.utx.zip)

**Comment by ejdanderson** [comment]
For anyone else visiting this issue - the .iso of the original GOTY cd come with compressed map files. Either you need to install the game and then move the maps or decompress them using the `UCC` utility included in the launcher.

For example:

`/Applications/UnrealTournament.app/Contents/MacOS/UCC decompress ~/Library/Application\ Support/Unreal\ Tournament/Maps/Entry.unr.uz` then move Entry.unr into the `~/Library/Application\ Support/Unreal\ Tournament/Maps/` directory (it will likely decompress into the `~/Library/Application\ Support/Unreal\ Tournament/System` directory)
