### ISSUE TITLE
[469a] XOpenGL - Minigun rendered ontop of hud:

### ISSUE THREAD

**Issue by Hyzoran** [OldUnreal/UnrealTournamentPatches#5]
Only in the XOpenGL renderer, and only with the Minigun, it seems to render ontop of everything else on the canvas:
![Shot00000](https://user-images.githubusercontent.com/71726640/93922861-886dea00-fce0-11ea-8219-8cff3dc46f1b.png)
![Shot00001](https://user-images.githubusercontent.com/71726640/93922863-899f1700-fce0-11ea-8f09-9bb50214b5f8.png)

**Comment by stevenstrike** [comment]
Hi,
Same problem for the flak cannon on XOpenGL.
Windows 10 x64 - AMD Fury - Latest drivers to date.

**Comment by subenji** [comment]
I have found that this is more prominent if DefaultFOV is increased. It does not happen under Kentie's D3D10 renderer, which I was using before this patch recommended switching to XOpenGL.

**Comment by shrimpza** [comment]
Confirming that this happens on Linux as well, both natively and via Wine, and applies to Mingun, Flak Cannon and Redeemer. FOV at 100.

The issue existed prior to 469 with XOpenGL as well, so I think it's a long-standing issue with the driver.

**Comment by racing-online** [comment]
Old issue, enabled ZRangeHack was a usual fix for this.

**Comment by Chamberly** [comment]
I got the same from biogun, minigun, flak and redeemer. Using fov 110 here.

I did try to add the ZRangeHack=False into the xopengl entry but it did not make any changes, so I went ahead and undo it.

**Comment by racing-online** [comment]
> I did try to add the ZRangeHack=False into the xopengl entry but it did not make any changes

Same here. Looks like XOpenGL doesn't have fix for this ZRange problem. With OpenGL and D3D9 this option works fine.

**Comment by stijn-volckaert** [comment]
Should be fixed in the 469c release version
