### ISSUE TITLE
Windown version installed on top of Ubuntu 18.04 version - unable to start [can't find SDLDrv]

### ISSUE THREAD

**Issue by ut99fan** [OldUnreal/UnrealTournamentPatches#50]
Hello Community,

**I wanted to have a version that works on both - Linux/Ubuntu 18.04 and Windows 7 sharing the configuration** (UnrealTournament.ini) etc so I tried updating/overwriting all dlls&exe files in /System from the zip file OldUnreal-UTPatch469a-Windows.zip

**The game would not start and only giving the following error:**
![ut99_win](https://user-images.githubusercontent.com/71790348/94346945-c06b8900-0062-11eb-917f-ce33757a0196.png)

**Later out of desperation I overwrote the entire UT99 folder with the contents of OldUnreal-UTPatch469a-Windows.zip and the Windows version would still not start.**

**Even after this the game still works fine from the Ubuntu 18.04 environment.**

Any tips on what is missing in the Windows 7 environment?
Is it even possible to have single folder version that works on both systems? Or is it better to keep it in separate folders ie. UT99-windows and UT99-linux?

Thank you very much in advance.

System: Windows 7 x64 Pro / Ubuntu 18.04 LTS x64
Theme: Default both
Video: 1920x1080 on nVidia Quadro M2200 4GB
Four monitors 1920x1080 each. Expanded desktop.

**Comment by NeonKnightOA** [comment]
That should be solved by modifying a line in `UnrealTournament.ini`: in the section `[Engine.Engine]` from `SDLDrv.SDLClient` to `WinDrv.WindowsClient`.

**Comment by stijn-volckaert** [comment]
This is not really a bug, but we'll update the launcher so it doesn't attempt to use SDLDrv on Windows.

**Comment by legluondunet** [comment]
I have the same goal: Windows and Linux install in the same folder.
And I obtained a similar issue:
![Capture d’écran de 2020-09-27 22-12-52](https://user-images.githubusercontent.com/325405/94374798-efd7cf80-010e-11eb-9240-1a2f83006cbc.png)
This issue appearing only with Windows version.
If config file UnrealTrounament contains:
`ViewportManager=WinDrv.WindowsClient`
Windows version launched ok
Linux version launched ok
but if you launch Linux version it modified config file and replaced:
`ViewportManager=WinDrv.WindowsClient` by `ViewportManager=SDLDrv.SDLClient`
Then Windows version can not launch any more.
Linux binary knows how to modify ViewportManager value to SDLDrv.SDLClient.
But Windows binary do not knows how to modify ViewportManager value to WinDrv.WindowsClient.

**Comment by CacoFFF** [comment]
Fixed for v469b

**Comment by legluondunet** [comment]
@CacoFFF do I need to open another issue for my report or it was the same issue?

**Comment by CacoFFF** [comment]
It's the same, what I did is add a platform specific fallback.
In Windows, if the viewport manager fails to load, it'll "try" to default to the WinDrv one.
In Unix systems it'll try to default to the SDL one.

So that should allow ppl on dual boot (i'm one of them) to run the same UT installation without requiring more than one INI file.

**Comment by legluondunet** [comment]
Very nice, I can't wait to test.
