### ISSUE TITLE
[469b] Add option "Select Matching Surfaces" into context menu for texture in UnrealEd Texture Brower

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#506]
![img](https://user-images.githubusercontent.com/70026933/126939979-4022c88b-a515-4294-bb9a-7c8f9f547d40.png)
There can be special item for select all surfaces on level with this texture.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/173331108-4ffa0500-fffe-48f8-877a-af358051cf4a.png)
![img](https://user-images.githubusercontent.com/70026933/173331141-36c88dc1-4acb-4c8f-a784-495bb64e5bd3.png)

**Comment by NeonKnightOA** [comment]
I support this totally. It helps to work with development textures (i.e. make the layout with dev textures, then replace them with final textures once you finish).

**Comment by SeriousBuggie** [comment]
For this better use Replace textures tool:
![img](https://user-images.githubusercontent.com/70026933/173351912-081ffe16-f2ff-4039-a26f-d5073a93fc59.png)
![img](https://user-images.githubusercontent.com/70026933/173351939-7424b563-4334-48d2-a271-1d89fd139acd.png)
