### ISSUE TITLE
[469b] Remove the Query Port Number bar when entering a New Favorite server

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#507]
![Screenshot_1374](https://user-images.githubusercontent.com/58362332/127187504-c78596cc-ee21-4c45-991d-b7761302d0f0.png)

In my many years of playing UT, I always see a lot of people having problems adding servers to their Favorite list, even in 2021. But how can you blame them? How are they supposed to know that the Query Port Number has to be +1 from the Server Port Number? In my opinion, the Query Port Number bar is an unnecessary and complicated step and it should be removed in order to make it more user friendly for everyone, especially for new players.

**Comment by SeriousBarbie** [comment]
Or fill in automatically the query port when its textbox gets the focus, server port is given but query port empty.
