### ISSUE TITLE
[win][469a] Failed import: Palette Palette UnrealShare.Skins.Palette634 (file ../System/UnrealShare.u)

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#51]
Failed enter to map MH-SkyTownAK3.
![scr_1601155554](https://user-images.githubusercontent.com/70026933/94350599-5817aa00-0058-11eb-800f-9d462cccca1c.png)
```
DevNet: PendingLevel received: WELCOME LEVEL=MH-SkyTownAK3 LONE=0
DevNet: Welcomed by server: LEVEL=MH-SkyTownAK3 LONE=0
Log: LoadMap: 81.169.240.101/MH-SkyTownAK3?Name=Buggie?Class=Botpack.TFemale1?Team=0?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=?UEFID=?Checksum=NoChecksum
Log: Failed import: Palette Palette UnrealShare.Skins.Palette634 (file ../System/UnrealShare.u)
NetComeGo: Close TcpipConnection3 09/27/20 00:25:47
Exit: WinSock shut down
```
Same if I try start it via practice session.
[mh-skytownak3.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5287366/mh-skytownak3.zip)
v436 load this map fine.

**Comment by stijn-volckaert** [comment]
I can't open your attachment. Can you re-upload please?

**Comment by SeriousBuggie** [comment]
Odd. I can open it.
[mh-skytownak3.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5288664/mh-skytownak3.zip)
https://en.ds-servers.com/gf/mh-skytownak3-zip-2.html
http://medor.no-ip.org/index.php?dir=Maps/MonsterHunt/&file=MH-SkyTownAK3.rar

**Comment by CacoFFF** [comment]
This very likely occurs due to a fractal texture using one of UnrealShare textures as a source. (my bet is on a WetTexture)
The editor will 'set' the new fractal texture's palette to that of the source texture, generating an import.

In theory there is a case where the import wouldn't be necessary if the game knew that if a WetTexture comes with source and no palette, it should fetch the palette from the source at load time.
But v436 isn't doing neither of both, so not saving the palette on v469 editor will cause those clients to crash.

Another idea is to have a `PALETTE=palette_name` directive on the texture importer and add those all over UnrealShare.

**Comment by aheilesen** [comment]
I have a similar problem with attempting to enter a match on the map DM-Hyperion by Revelation:

![error](https://user-images.githubusercontent.com/15849832/95037256-65581880-0698-11eb-8bc3-abcf392f9661.jpg)

The map can be downloaded here: https://unrealarchive.org/maps/unreal-tournament/deathmatch/H/dm-hyperion_928d6cbb.html

It worked on another computer with v436.

**Comment by an-eternity** [comment]
Tested this map with v469a server - works, it seems, with no problems.
But if server is running XC_Engine v25 then it can not startup...
Log:
`Log: Failed import: Palette Palette UnrealShare.Skins.Palette634 (file ../System/UnrealShare.u)`
`Warning: Failed to load 'MH-SkyTownAK3.unr': Can't find Palette in file 'Palette UnrealShare.Skins.Palette634'`
`Warning: Failed to load 'Level None.MyLevel': Can't find Palette in file 'Palette UnrealShare.Skins.Palette634'`
`XC_Engine: === Last line repeats 4653151 times.`
`Critical: UGameEngine::Init`
`Critical: UXC_GameEngine::Init`
`Critical: UServerCommandlet::Main`
`Exit: Executing UObject::StaticShutdownAfterError`
`Exit: Exiting.`

**Comment by CacoFFF** [comment]
As of v469b package conformal will also attempt to make palettes use the same names as previous versions.
So any mod/map that requires loading a specific palette form Botpack, UnrealI, UnrealShare (and maybe others?) would have no problems anymore.

**Comment by an-eternity** [comment]
Tested preview from Nov. 10 (client and server) with this map just now - no problem with palette import anymore.

**Comment by SeriousBuggie** [comment]
Fixed in v469b 10 nov. Confirmed for both mentioned above maps.

**Comment by garry-ut99** [comment]
Another case, for map CTF-Incinerator1b.unr : https://ut99.org/viewtopic.php?p=124122#p124122

**Comment by SeriousBuggie** [comment]
Check CTF-Incinerator1b.unr on v469b 10 Nov - all fine.

**Comment by SeriousBuggie** [comment]
I rebuilt uscript files for v469c and issue appear again. v469b fine. Need some special actions on rebuild scripts for avoid this issue?
