### ISSUE TITLE
[469b] Remember passwords history with server

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#510]
Currently `PasswordHistory` implemented in `UTMenu/Classes/UTPasswordCW.uc` as just list of strings which not linked with servers.

Suggestion store and use pairs server/password.
So if dialog appear on server when you previously enter password, there already be last input password. Not just last password for any server.
General drop down stay common for all servers, but last input use passwords for this server if found in history.

**Comment by stijn-volckaert** [comment]
UTMenu.UTConsole.SavedPasswords already does this.
