### ISSUE TITLE
[469b] General protection fault: FWaveModInfo::ReadWaveInfo

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#512]
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: FWaveModInfo::ReadWaveInfo <- FSoundData::GetPeriod <- FSoundData::Load <- 
UALAudioSubsystem::RegisterSound <- RegisterSounds <- UALAudioSubsystem::SetViewport <- 
ClientInit <- UGameEngine::LoadMap <- LocalMapURL <- UGameEngine::Browse <- ClientTravel <- 
UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```
This crash happen to me in UnrealEd and UT when I work on [Wolf3D map](https://unrealarchive.org/maps/unreal/single-player/W/wolfenstein-3d-e1m1-singleplayer_365ad1c4.html)

Possible somehow related to [wolfsounds.uax](https://github.com/OldUnreal/UnrealTournamentPatches/files/6909056/wolfsounds.zip)

Used OpenAL driver.

**Comment by SeriousBuggie** [comment]
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: FWaveModInfo::ReadWaveInfo <- FSoundData::GetPeriod <- FSoundData::Load <- 
TLazyArray<< <- USound::Serialize <- LoadObject <- 
(Sound DoomPawns.Imp.DSFIRXPL 245422==245422/9154665 245416 11770) <- 
ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- 
(Engine.Level None.MyLevel MH-Wolf3DBeta0_5.unr) <- LoadLevel <- UGameEngine::LoadMap <- 
LocalMapURL <- UGameEngine::Browse <- ClientTravel <- UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```
[DoomPawns.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6910446/DoomPawns.zip)
[DSFIRXPL.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6910447/DSFIRXPL.zip)
Audio: PCM 11025Hz mono 88kbps [A: pcm_u8, 11025 Hz, 1 channels, s8, 88 kb/s]

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Extract [DoomPawns.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6910446/DoomPawns.zip) into System
2. Run in UnrealEd (once or twice)
`obj load file=DoomPawns.u package=MyLevel`

Expected result: No crash.
Actual result: Crash.

Reproduced in v469c, c469b, v436.
Even with selected `Cluster` in v469c.

in v436 different text:
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: UFireTexture::ConstantTimeTick <- UTexture::Tick <- (FireTexture UnrealShare.Effect18.FireEffect18) <- 
UTexture::Update <- URender::DrawLodMesh <- (LodMesh UnrealShare.8Ball3rd) <- DrawMesh <- 
URender::DrawActorSprite <- URender::DrawActor <- REN_MeshView <- UEditorEngine::Draw <- 
(Cam=MeshViewer,Flags=8832 <- UWindowsViewport::Repaint <- UEditorEngine::RedrawLevel <- 
UEditorEngine::SafeExec <- (LOAD file=DoomPawns.u package=MyLevel) <- UEditorEngine::SafeExec <- 
(obj load file=DoomPawns.u package=MyLevel) <- UEditorEngine::Exec <- 
(obj load file=DoomPawns.u package=MyLevel) <- DispatchMessage <- 
00380EDA 256 <- MessagePump <- MainLoop
---------------------------
ОК   
---------------------------
```

**Comment by SeriousBuggie** [comment]
Possible reason: this package build for Unreal, not for UT.
`function PlayHit(float Damage, vector HitLocation, name damageType, float MomentumZ)`
Last param must be vector.
Also import SpriteSmokePuff.PostBeginPlay which not exists,

**Comment by SeriousBuggie** [comment]
Finally, after recode wave and reimport all goes fine. So reason in wav file. UT not able handle such wav files. Somewhere exists bug.

**Comment by stijn-volckaert** [comment]
Will be fixed in 469c. UnrealEd couldn't handle the fact that the wav files in this package don't have sample chunks.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
