### ISSUE TITLE
[469b] Mesh zoom gets reset when an Actor is selected by Search window

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#516]
Select any mesh in Mesh Browser and zoom into (you have to do that to see anything useful). Then open Edit>Search and doubleclick any entry to select that Actor.
Expected result: Mesh Browser view stays at is it
Current result: Mesh Browser zoom is reset

**Comment by SeriousBuggie** [comment]
`"CAMERA ALIGN NAME=%ls"` must ignore Meshbrowser viewport.
