### ISSUE TITLE
[469b] UnrealEd not able fill sound from group "(all)"

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#518]
Reproduce:
1. Start UnrealEd.
2. Open [DukeNukemVoice.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/6988912/DukeNukemVoice.zip)
3. Select sound `Groovy02`.
4. Place on map SpecialEvent.
5. Edit field `Sound`.
6. Press `Use` button. or input `Sound'DukeNukemVoice.(All).Groovy02'` or `DukeNukemVoice.(All).Groovy02`

Expected result: in field appear `Sound'DukeNukemVoice.(All).Groovy02'`.
Actual result: In filed appear `None`.

Reason: UProperty::Importtext not able handle group name `(All)`. if this part erased all work.

But you can not erase this part when use `Use` button. This button just stop work.

**Comment by SeriousBuggie** [comment]
Also this lead to lost properties when used `Replace With ... (keep properties)` because properties after import turn into None.

**Comment by stijn-volckaert** [comment]
Fix pushed for RC3

**Comment by stijn-volckaert** [comment]
RC3 is now available
