### ISSUE TITLE
[469a] Masterserver info updates/errata

### ISSUE THREAD

**Issue by Dr-Flay** [OldUnreal/UnrealTournamentPatches#52]
I am thoroughly regretting not contributing sooner

1) Current config still uses fallback mode so it only uses 1 master at a time, moving onto the next if failed (this is intended for modem users)
`FallbackFactories=False` will allow all masters to be queried at the same time so the full list is available (intended for broadband users).
As 333networks includes the results from epic, when used in fallback mode a 333NW master should be used first, so all servers can be found. Epic does not include the results from uplinks only made to 333NW.

2) Wrong port number in the down-link entry for 333networks. It is missing a 0.
(Current config, if epic fails 333NW will be used as the final backup, but obviously wont work anyway).

Lacking uplinks to Qtracker and Telefragged/GameRanger (Mac client)
`ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.qtracker.com MasterServerPort=27900`
`ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.telefragged.com MasterServerPort=27500`
(Uplinks only as they provide server lists via a desktop client)

3) mplayer is of doubtful use for up or down links. The domain is registered to IGN but they no longer provide masterserver services or a client.
Test for yourself. Using only mplayer for a server list will fail

4) OldUnreal or master.errorist.tk master should be in the config as the fallback for occasions when 333networks is offline

**Comment by gargul2** [comment]
Excuse me, I'm not in topic, is this issue responsible for displaying only a half of UT99 servers (about 300) as visible on the second screenshoot: https://github.com/OldUnreal/UnrealTournamentPatches/issues/49#issuecomment-699619351 . In 436 it shows twice as many, (over 600 servers).

**Comment by stijn-volckaert** [comment]
> 
> I am thoroughly regretting not contributing sooner

Better late than never ;)

> 
>     1. Current config still uses fallback mode so it only uses 1 master at a time, moving onto the next if failed (this is intended for modem users)
>        `FallbackFactories=False` will allow all masters to be queried at the same time so the full list is available (intended for broadband users).
>        As 333networks includes the results from epic, when used in fallback mode a 333NW master should be used first, so all servers can be found. Epic does not include the results from uplinks only made to 333NW.
> 
>     2. Wrong port number in the down-link entry for 333networks. It is missing a 0.
>        (Current config, if epic fails 333NW will be used as the final backup, but obviously wont work anyway).

Is this what the UBrowserAll section should look like?
```
[UBrowserAll]
ListFactories[0]=UBrowser.UBrowserGSpyFact,MasterServerAddress=master.333networks.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[1]=UBrowser.UBrowserGSpyFact,MasterServerAddress=utmaster.epicgames.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[2]=UBrowser.UBrowserGSpyFact,MasterServerAddress=master0.gamespy.com,MasterServerTCPPort=28900,Region=0,GameName=ut
bHidden=True
bFallbackFactories=false
```

> 
> Lacking uplinks to Qtracker and Telefragged/GameRanger (Mac client)
> `ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.qtracker.com MasterServerPort=27900`
> `ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.telefragged.com MasterServerPort=27500`
> (Uplinks only as they provide server lists via a desktop client)
> 

The patch installer scripts cannot really add new server actors but I've added these to Default.ini

>     3. mplayer is of doubtful use for up or down links. The domain is registered to IGN but they no longer provide masterserver services or a client.
>        Test for yourself. Using only mplayer for a server list will fail

Removed from Default.ini.

>     4. OldUnreal or master.errorist.tk master should be in the config as the fallback for occasions when 333networks is offline

Are we talking about the uplinks or browserqueries here? Or both?

**Comment by Dr-Flay** [comment]
If FallbackFactories is off then it doesn't matter what order they are in, but we should consider that some people may want to enable it to specify 1 master, which should we have first ?
With respect to Epic we should have theirs first, but it shows less results (not by much).
However players may obviously prefer 333NW first if they use the fallback mode.
There is no right or wrong here, just what we think the community would find more useful.

The gamespy domain is also owned by IGN and kept registered, but no master lives behind that door.
It needs to go silently into the night unless they are willing to hand over the domain to us.

master.oldunreal.com and master.errorist.eu (the 333NW backup) both use the new master system so can sync with 333networks, so should always show the full list even if servers are not uplinked to them.
They can all be used for both up and down links.

If you are saying that only the existing 3 lines can be updated not added to, then I think we should have Epic, 333NW and OldUnreal.
The default.ini could have all the multimasters displayed above the forum at OldUnreal and on the front of Newbiesplayground (they also host one of our masters).
