### ISSUE TITLE
[469b] Botpack.Stukka not set DrawType=DT_Mesh

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#528]
![img](https://user-images.githubusercontent.com/70026933/130791278-aba86389-052e-46e9-8edc-40a244d677f2.png)
https://github.com/Slipyx/UT99/blob/master/Botpack/Stukka.uc
Mesh set. DrawType=DT_Mesh not set.

**Comment by stijn-volckaert** [comment]
The fix will be included in the optional compatibility package that will ship with 469c. We cannot fix this in the base class.
