### ISSUE TITLE
[UnrealEd 469c]find line with compile error

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#530]
If an error occurs when compiling code in UnrealEd, the error message contains the line number, but there is no indicator for the line numbers so that I have to count the lines myself from the beginning.

Suggestion: set the cursor to the line with the error.

**Comment by SeriousBuggie** [comment]
Need more info about error + steps for reproduce.
For me all work fine and on error cursor goes to the line of error:
![img](https://user-images.githubusercontent.com/70026933/131252181-c978a0f7-ea65-40cf-932f-a8d9f855e447.png)

**Comment by SeriousBarbie** [comment]
I cannot remember the exact circumstances I tried, and in a test UnrealEd sets the cursor to the line with the error. ¯\_(ツ)_/¯
I'll close here and reopen, if I can reproduce it.
