### ISSUE TITLE
[469c]UnrealEd does not show same property values for multiple Actors

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#533]
Select multiple Actors in UnrealEd and look at the properties that have the same value (e.g Location or Tag).
Expected result: property text fields contains the value
Current result: property text fields are empty (see pic)
![SameLocation](https://user-images.githubusercontent.com/81397053/131684525-ddef1aaa-6f36-4c0d-8981-7d2d448b5464.jpg)
[Test map 'SameLocation.unr.zip'](https://github.com/OldUnreal/UnrealTournamentPatches/files/7091618/SameLocation.unr.zip)

**Comment by SeriousBuggie** [comment]
Duplicate of #270

**Comment by SeriousBarbie** [comment]
Whow, I've forgotten that I already had reported this half a year ago. What about this issue report then? Delete? Remove? Close?

**Comment by SeriousBuggie** [comment]
Close.
