### ISSUE TITLE
[469b] Native function lookups can fail due to case-insensitive FNames

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#534]
I tried to join my server that run the map "MH-UM-Zippy-beta1" and got the following Critical Error on client (same happens if I play the map locally):

> Can't find "intUudnativeexecKill" in library "udemo.dll".
>
>History: UPackage::GetDllExport <- UFunction::Bind <- UField::PostLoad <- UStruct::PostLoad <- UFunction::PostLoad <- UObject::ConditionalPostLoad <- (Function udemo.udnative.Kill) <- PostLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- (Core.Class udemo.UDmodItem NULL) <- (Transient.UMenuMenuBar0 UMenu.UMenuMenuBar.LoadMods) <- (Transient.UMenuMenuBar0 UMenu.UMenuMenuBar.Created) <- (Transient.UMenuRootWindow0 UWindow.UWindowWindow.CreateWindow) <- (Transient.UMenuRootWindow0 UMenu.UMenuRootWindow.Created) <- (Transient.XConsole0 UWindow.WindowConsole.CreateRootWindow) <- (Transient.XConsole0 UTMenu.UTConsole.CreateRootWindow) <- (MH-UM-Zippy-beta1.NexgenClient0 Nexgen112N.NexgenClient.initializeConsoleWindow) <- (MH-UM-Zippy-beta1.NexgenClient0 Nexgen112N.NexgenClient.initializePopupWindow) <- (MH-UM-Zippy-beta1.NexgenClient0 Nexgen112N.NexgenClient.clientLogin) <- UObject::ProcessEvent <- (NexgenClient MH-UM-Zippy-beta1.NexgenClient0, Function Nexgen112N.NexgenClient.Timer) <- AActor::Tick <- TickAllActors <- ULevel::Tick <- (NetMode=3) <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- MainLoop

With v436 I could join without problems.

**Comment by SeriousBuggie** [comment]
Possible you not install udemo.dll from test build. Try again install latest zip from test github repo.

**Comment by SeriousBarbie** [comment]
Removing that UDEMO.DLL makes that map playable, and I've never used a demo playing or recording feature. Anyway

**Comment by SeriousBuggie** [comment]
IDK. I start UT, Type `open MH-UM-Zippy-beta1.unr` - map start fine.
Open map in UnrealEd - press play - map start fine. But if now press Escape for bring menu game crash with your message.

Mapper add in package `Engine.u`, `MyLevel.utx`: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/U/mh-um-zippy-beta1_ebfdeb05.html
But miss `Evil-Lair-1.utx`.

`SeriousSam.u` 1 MB added just for use one sound in 17.2 KB.

So possible this map contains some errors.

**Comment by SeriousBuggie** [comment]
> Can't find "intUudnativeexecKill" in library "udemo.dll".
> 
> History: UPackage::GetDllExport <- UFunction::Bind <- UField::PostLoad <- UStruct::PostLoad <- UFunction::PostLoad <- UObject::ConditionalPostLoad <- (Function udemo.udnative.Kill) <- PostLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- (Core.Class udemo.UDmodItem NULL) <- (Transient.UMenuMenuBar0 UMenu.UMenuMenuBar.LoadMods) <- (Transient.UMenuMenuBar0 UMenu.UMenuMenuBar.Created) <- (Transient.UMenuRootWindow0 UWindow.UWindowWindow.CreateWindow) <- (Transient.UMenuRootWindow0 UMenu.UMenuRootWindow.Created) <- (Transient.UTConsole0 UWindow.WindowConsole.CreateRootWindow) <- (Transient.UTConsole0 UTMenu.UTConsole.CreateRootWindow) <- (Transient.UTConsole0 UWindow.WindowConsole.RenderUWindow) <- UObject::ProcessEvent <- (UTConsole Transient.UTConsole0, Function UWindow.WindowConsole.UWindow.PostRender) <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop

**Comment by SeriousBuggie** [comment]
`class udnative expands Object native;`
`native final static function bool kill(string file);`
Pay attention on case of function. `kill` - all lowercase.
Map load first. And load into table of names new name `Kill`. So now used version of name with first uppercase.
For C++ case matters so link native lib failed.
If export map you can see a lot monsters with `AlarmTag="Kill"`.
Enough rename all to smth other and all must be ok after reload map.

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Start UnrealEd.
2. Paste
```
Begin Map
Begin Actor Class=Brush Name=Brush1
     CsgOper=CSG_Subtract
     MainScale=(SheerAxis=SHEER_ZX)
     PostScale=(SheerAxis=SHEER_ZX)
     Level=LevelInfo'MyLevel.LevelInfo0'
     Tag="Brush"
     Region=(Zone=LevelInfo'MyLevel.LevelInfo0',ZoneNumber=1)
     bSelected=True
    Begin Brush Name=Model2
       Begin PolyList
          Begin Polygon
             Origin   -00128.000000,-00128.000000,-00128.000000
             Normal   -00001.000000,+00000.000000,+00000.000000
             TextureU +00000.000000,+00001.000000,+00000.000000
             TextureV +00000.000000,+00000.000000,-00001.000000
             Vertex   -00128.000000,-00128.000000,-00128.000000
             Vertex   -00128.000000,-00128.000000,+00128.000000
             Vertex   -00128.000000,+00128.000000,+00128.000000
             Vertex   -00128.000000,+00128.000000,-00128.000000
          End Polygon
          Begin Polygon
             Origin   -00128.000000,+00128.000000,-00128.000000
             Normal   +00000.000000,+00001.000000,+00000.000000
             TextureU +00001.000000,-00000.000000,+00000.000000
             TextureV +00000.000000,+00000.000000,-00001.000000
             Vertex   -00128.000000,+00128.000000,-00128.000000
             Vertex   -00128.000000,+00128.000000,+00128.000000
             Vertex   +00128.000000,+00128.000000,+00128.000000
             Vertex   +00128.000000,+00128.000000,-00128.000000
          End Polygon
          Begin Polygon
             Origin   +00128.000000,+00128.000000,-00128.000000
             Normal   +00001.000000,+00000.000000,+00000.000000
             TextureU +00000.000000,-00001.000000,+00000.000000
             TextureV +00000.000000,+00000.000000,-00001.000000
             Vertex   +00128.000000,+00128.000000,-00128.000000
             Vertex   +00128.000000,+00128.000000,+00128.000000
             Vertex   +00128.000000,-00128.000000,+00128.000000
             Vertex   +00128.000000,-00128.000000,-00128.000000
          End Polygon
          Begin Polygon
             Origin   +00128.000000,-00128.000000,-00128.000000
             Normal   +00000.000000,-00001.000000,+00000.000000
             TextureU -00001.000000,-00000.000000,-00000.000000
             TextureV +00000.000000,+00000.000000,-00001.000000
             Vertex   +00128.000000,-00128.000000,-00128.000000
             Vertex   +00128.000000,-00128.000000,+00128.000000
             Vertex   -00128.000000,-00128.000000,+00128.000000
             Vertex   -00128.000000,-00128.000000,-00128.000000
          End Polygon
          Begin Polygon
             Origin   -00128.000000,+00128.000000,+00128.000000
             Normal   +00000.000000,+00000.000000,+00001.000000
             TextureU +00001.000000,+00000.000000,+00000.000000
             TextureV +00000.000000,+00001.000000,+00000.000000
             Vertex   -00128.000000,+00128.000000,+00128.000000
             Vertex   -00128.000000,-00128.000000,+00128.000000
             Vertex   +00128.000000,-00128.000000,+00128.000000
             Vertex   +00128.000000,+00128.000000,+00128.000000
          End Polygon
          Begin Polygon
             Origin   -00128.000000,-00128.000000,-00128.000000
             Normal   +00000.000000,+00000.000000,-00001.000000
             TextureU +00001.000000,+00000.000000,+00000.000000
             TextureV +00000.000000,-00001.000000,+00000.000000
             Vertex   -00128.000000,-00128.000000,-00128.000000
             Vertex   -00128.000000,+00128.000000,-00128.000000
             Vertex   +00128.000000,+00128.000000,-00128.000000
             Vertex   +00128.000000,-00128.000000,-00128.000000
          End Polygon
       End PolyList
    End Brush
     Brush=Model'MyLevel.Model2'
     Name="Brush1"
End Actor
Begin Actor Class=PlayerStart Name=PlayerStart0
     bDynamicLight=True
     Level=LevelInfo'MyLevel.LevelInfo0'
     Tag="PlayerStart"
     Event="Kill"
     Region=(Zone=LevelInfo'MyLevel.LevelInfo0',ZoneNumber=1)
     Location=(Z=-87.900002)
     OldLocation=(Z=-87.900002)
     bSelected=True
     Name="PlayerStart0"
End Actor
End Map
``` 
Cube map with player start with Event `Kill`.
3. Build geom.
4. Play map.
5. Press escape for open menu.

Expected result: menu open.
Actual result: UT crash.

OFC if udemo not used or version not use native `kill` then no any crash.

**Comment by SeriousBarbie** [comment]
Nice finding! Unfortunately it cannot be avoided by changing that AlarmTag by my MapPatcher when the map is loaded. Is direct access to the name table possible by UScript?

**Comment by SeriousBuggie** [comment]
No any direct access. And you not need it. You enough load any package with name `kill` before map package loaded.
IDK possible this or no. Depends from order of load packages. Maybe if you add in ServerPackages any package with proper name it load before map and fx issue. Try add it into BarbiesWorld.u.

**Comment by an-eternity** [comment]
> Maybe if you add in ServerPackages any package with proper name it load before map and fx issue.

A few months ago i tried to do it this way to fix similar problem with the GameType name that is defined in the map, but unfortunately it did not work, or maybe i did something wrong way...

**Comment by stijn-volckaert** [comment]
Thanks, this will be fixed in 469c

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
