### ISSUE TITLE
[469b] Provide Linux 64bit builds

### ISSUE THREAD

**Issue by uralets** [OldUnreal/UnrealTournamentPatches#535]
Thought I'll just create an issue for this, hoping it could be looked into eventually (sooner rather than later :)).

Would be greatly appreciated. TIA.

**Comment by uralets** [comment]
Cross-referencing #587 (and bumping)

**Comment by CacoFFF** [comment]
I'm all for it

**Comment by uralets** [comment]
Would be great to have some sort of feedback on this.

**Comment by an-eternity** [comment]
We are testing 64-bit build for Linux at the moment - everything is working fine so far.

**Comment by stijn-volckaert** [comment]
64bit Linux binaries are now available
