### ISSUE TITLE
[469a] config file errata and updates

### ISSUE THREAD

**Issue by Dr-Flay** [OldUnreal/UnrealTournamentPatches#54]
There are a few missing default.ini entries for the renderers.
DX9 defaults are missing.
D3D7 and OpenGL have the old shorter defaults for the original renderers.
As you can see they have more settings for users to mess up.
![Vrenderers](https://user-images.githubusercontent.com/43873202/94388269-64793100-0144-11eb-9b46-5d7f20630f1b.jpg)
Compressed and AGP texture options should be enabled whenever possible, as nobody today uses GFX cards without support.

**ALAudio.int** problem
The OpenAL renderer is mounting in the root audio branch.
It should be a subsection like the others.
![ALaudio](https://user-images.githubusercontent.com/43873202/94388310-8f638500-0144-11eb-975c-2845d53b84a8.png)

I know that Galaxy is deprecated but it may still be worth upgrading the defaults from their current half values.
It would be worth bumping the Galaxy and generic renderer sections to 44kHz and 32 channels, and enabling 3D Hardware  and reverb. It is unlikely in the extreme that anyone will be using such an old sound card it cannot handle 44kHz, and 32 channels is as high as they go.

**Startup.int** could do with support for other renderers so they will be able to be chosen with a useful description in the start window (Cluster and XOpenGL are missing).
The section I have in my old install is adapted from the original but contains most of the renderers I found. May be useful for reference;

> [Descriptions]
> SoftDrv.SoftwareRenderDevice=Unreal Tournament's built-in software renderer.  Compatible with all video cards.
> GlideDrv.GlideRenderDevice=3dfx Glide support, the optimal choice for 3dfx owners.  3dfx card required.
> D3DDrv.D3DRenderDevice=Use Direct3D hardware rendering. Compatible with Win9x era video cards, like the Riva TNT, ATI Rage 128, Matrox G400, and S3 Savage4.  Not recommended for use with earlier video cards--use the Software Renderer if you have an ATI Rage Pro, Riva 128, Intel i740, or Rendition V2200.
> D3D8Drv.D3D8RenderDevice=Use DirectX 8 hardware rendering. Compatible with Win9x/ME/2000 era video cards.  High resolution S3TC texture support. - Compatible with ENB bloom mod.
> D3D9Drv.D3D9RenderDevice=Use DirectX 9 hardware rendering. Compatible with most video cards.  High resolution S3TC texture support - Compatible with ENB bloom mod.
> D3D10Drv.D3D10RenderDevice=Use DirectX 10 hardware rendering. Compatible with Windows Vista and upwards with newer video cards. High resolution S3TC texture support.
> D3D11Drv.D3D11RenderDevice=Use DirectX 11 hardware rendering. Compatible with newest video cards and Windows Seven upwards. High resolution S3TC texture support.
> OpenGLDrv.OpenGLRenderDevice=Use advanced OpenGL support. Provides best performance and support for most high-end grafix cards (ATI and intel cards may perform better with the D3D renderers). High resolution S3TC texture support.
> sdkOpenGLDrv.OpenGLRenderDevice=Experimental SDK OpenGL support. This is provided for testing and experimentation, High resolution S3TC texture support.
> MetalDrv.MetalRenderDevice=For users with S3 Savage4 video cards.
> 

I suggest an extra config entry which server admin should like.
We can have all the game mode settings available for quick configuration with this line;
`Preferences=(Caption="Game Types",Parent="Advanced Options")`
I chose to put it in my botpack.int as that lists the game types.
Many things can be exposed for configuration in the advanced options window.
The advantage of using this window to change many of the settings is they can be done live while a game is playing.
Some things will update immediately like GFX and others the next time the config is referenced.

**Comment by NeonKnightOA** [comment]
Try with my language pack to see if this is fixed. I've moved OpenAL out of Audio and made it its own separate folder.

https://www.dropbox.com/s/qnu4ck2cm79bzl4/ut99-i18n-int-est-v1.08a.zip?dl=0

**Comment by Dr-Flay** [comment]
Yep the OpenAL edit looks good. that works.
The extra line in botpack now shows all installed game types, but one seems to be mounting itself in the game types root.
Will have to track it down.

Just spotted another change needed to startup.int
`Direct3DWebPage="http://www.microsoft.com/directx"` is no good as it will open the xbox site.
For a working DX9 link it needs to be either
`http://go.microsoft.com/fwlink/?LinkID=56511&clcid=0x409`
or
`https://www.microsoft.com/download/details.aspx?id=8109`

However to avoid the links becoming obsolete we should probably point to a page we can maintain here or at the Oldunreal wiki
(The original page for reference)
`Direct3DWebPage=https://web.archive.org/web/20090930075309/http://unreal.epicgames.com:80/Direct3D.htm`
As you see it wasn't just about downloading DirectX, but a page of useful info relating to the use of the various renderers.

**Comment by NeonKnightOA** [comment]
Noted. I'll be updating the Wiki and the files soon.

**Comment by NeonKnightOA** [comment]
Fixed in latest [unreal-localization](https://github.com/NeonKnightOA/unreal-localization) and the Wiki. Fixed also in PR #53.

**Comment by Dr-Flay** [comment]
Main engine settings are being mounted in the editor section.
Both the editor.int prefs and the engine.int prefs are using a section called "Advanced" so being mixed together and being duplicated.
![engine](https://user-images.githubusercontent.com/43873202/95029081-8a02bf00-069d-11eb-97ee-f81b4764f4c1.png)
You cannot reuse the names of sections in different branches.

**Comment by NeonKnightOA** [comment]
Noted, fixing right now.

**Comment by NeonKnightOA** [comment]
#82 fixes this issue.

**Comment by Dr-Flay** [comment]
Do we have extra sections in the UEd defaults that should not be there, or have not been setup properly in the configs ?
I also see Sektor complaining about the brush builder line.
https://ut99.org/viewtopic.php?t=14118&p=123027#p123021

**Comment by NeonKnightOA** [comment]
I'm tempted to do a separate issue only for the localizations. I was worried I did something wrong!

**Comment by Dr-Flay** [comment]
I know what you mean and I am in 2 minds as they relate to each other explicitly, so often an issue in an int effects an ini
