### ISSUE TITLE
[469b] All trophies visible in the trophy room in single player

### ISSUE THREAD

**Issue by zbyram** [OldUnreal/UnrealTournamentPatches#542]
A particular trophy should appear (with a small animation) only after completing part of the campaign e.g. Deatchmatch or Domination. Now all trophies are visible from the start as if they were already unlocked. Issue is only visible after you get the first trophy, as that is when the trophy room is first shown.

**Comment by SeriousBuggie** [comment]
Confirmed.
```ini
[UTMenu.SlotWindow]
Saves[4]=5\1\6\15\0\0\0\0\0\0\0\0\M\1\TestTrophy
```
produce in Trophy room (map EOL_Statues) all meshes for rewards.

**Comment by SeriousBuggie** [comment]
This happens because `class TrophyGame extends UTIntro;` define own
`var LadderInventory LadderObj;` and not bother init it at all.
So this shadowed `var LadderInventory LadderObj;` from `class UTIntro extends TournamentGameInfo;` and never be loaded, so always `None`.
