### ISSUE TITLE
[469b] UnrealEd cannot save files that have the "N" attribute

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#548]
It is only a guess because I cannot reproduce it because I don't know how to set the file attribute "N" manually. Sometimes a UNR file has this attribute after I extracted it from a 7zip archive, and when I open, modify and then try to save this file, UnrealEd throws an error message like "cannot save file".

I should mention that I noticed that seldom and that the files were on a samba network share.

**Comment by SeriousBuggie** [comment]
[What is N attribute](https://superuser.com/questions/516709/what-is-the-n-folder-attribute-on-windows)

I think problem not in this attribute. For me all fine save with it.

Also UnrealEd never try save in file. It write all into Save.tmp and move it as replacement.
So file attributes doesn't matter until not prevent delete original file during move.

I suspect something wrong with your samba network right or file locked from outside, so UnrealEd not able remove it.

What written in the log?

**Comment by SeriousBarbie** [comment]
> What written in the log?

Sadly the log was overwritten with the next start of UnrealEd but as I remember it gave only the information that saving didn't work, without any error number or reason.
Until now I was not able to reproduce this issue; I'll add log lines when it occurs next time.

**Comment by SeriousBuggie** [comment]
This error can be before write to Save.tmp or after (fail to move) - this usually clearly state in the log.

**Comment by SeriousBuggie** [comment]
Can't be reproduced. So I closed it now. If you found way of reproduce, feel free open it again.
