### ISSUE TITLE
[469b] UnrealEd not provide detail about bad actor if import failed

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#549]
I import big t3d file for exported map (18 MB of text) and get UnrealEd crash:

> Assertion failed: Actor [File:UnEdFact.cpp] [Line: 1513]
> 
> History: ParseActor <- ULevelFactory::FactoryCreateText <- UFactory::StaticImportObject <- UEditorEngine::Exec <- (MAP IMPORT FILE="map_t3d.).. <- WEditorFrame::OnCommand <- WM_COMMAND <- MessagePump <- MainLoop

No any info where import failed. UnrealEd try spawn Actor, actor not spawned, the check throw exception, Unrealed crashes with lost any unsaved change.

**Comment by SeriousBuggie** [comment]
In this case error cased by
```
Begin Actor Class=Ladder Name=Ladder0
    FootRegion=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=1296,ZoneNumber=14)
    HeadRegion=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=1296,ZoneNumber=14)
    ViewRotation=(Yaw=-32576)
    Level=LevelInfo'MyLevel.LevelInfo0'
    Tag=Ladder
    Region=(Zone=LevelInfo'MyLevel.LevelInfo0',iLeaf=1296,ZoneNumber=14)
    Location=(X=-3345.289,Y=-5951.302,Z=1957.036)
    Rotation=(Yaw=-32576)
    OldLocation=(X=-896,Y=-496,Z=-168.4)
    DrawScale=1.5
    AmbientGlow=20
    CollisionRadius=48
    CollisionHeight=100
    Name=Ladder0
End Actor
```
Because `Ladder` in UT abstract class which can not be placed on map.
T3D exported from game where `Ladder` is just decoration with usual wood ladder.

Will be good if there be no crash - just note in Log with name of actor + line from input T3D and some description like:
`Failed spawn actor Ladder0 from line 1234567`.

**Comment by SeriousBarbie** [comment]
Maybe additional add package name to class name in T3D. But then such T3Ds cannot be imported by older Editors. Would this really be a problem?

**Comment by SeriousBuggie** [comment]
Package can not be added because this violate T3D idea as exchange format between UEds different games. Possible even between some plugins for 3D software.
