### ISSUE TITLE
[469b] MercenaryElite able stuck in shielded state forever

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#551]
In MH MercenaryElite able stuck in shielded state forever if some conditions met.
This happen not often.
Usually Health in this state negative, but MercenaryElite still alive, shoot and can not be killed.

**Comment by SeriousBuggie** [comment]
```
function TakeDamage( int Damage, Pawn instigatedBy, Vector hitlocation, 
						Vector momentum, name damageType)
{
	if ( !bIsInvulnerable )
		Super.TakeDamage(Damage, instigatedBy, hitlocation, momentum, damageType);
	else if ( Damage > 0 )
	{
		InvulnerableCharge = InvulnerableCharge - Damage/100;
		PainTime = 0.3;
		//change to take-damage invulnerable skin
	}
}
```
So if bIsInvulnerable, then set PainTime for call PainTimer:
```
function PainTimer()
{
	if ( Health <= 0 || bDeleteMe )
		return;
	if ( !bIsInvulnerable )
	{
		if ( bHasInvulnerableShield && Region.Zone.bPainZone && (Region.Zone.DamagePerSec > 0) )
			BecomeInvulnerable();
		Super.PainTimer();
		if ( bIsInvulnerable )
			PainTime = 1.0;
		return;
	}
	
	InvulnerableCharge -= 1.0;
	if ( (InvulnerableCharge < 0) || (Level.TimeSeconds - InvulnerableTime > 4 + 5 * FRand()) )
		BecomeNormal();
	else
		PainTime = 1.0;

}
```
But there id health <= 0 then no action at all. Dead end,

So if in some way Merc get negative health - any TakeDamage will be blocked. And this state never ends.

TakeDamage at pawn responsible for death. So death never happen.

**Comment by an-eternity** [comment]
Some related things... In past with v451 there was an issue where any pawn was stuck (for some else reasons) in dead zones with negative health. We fixed it by the simple script in GameType. Then after time it was also fixed in v469.

If i understand correctly, even if MercenaryElite will stuck with negative health because of this bug in its script, then with v469 it must get automatically destroyed. Is this correct?

Anyway, even if this bug does not produce any problems because of another fixes, it is better to fix it.

**Comment by SeriousBuggie** [comment]
> If i understand correctly, even if MercenaryElite will stuck with negative health because of this bug in its script, then with v469 it must get automatically destroyed. Is this correct?

No. Action can be any. We just need call `Super.TakeDamage` in this case and it follow usual flow. There can be anything. For example monster can be fat instead of destroy. Or turn into ghost. Or turn into statue. Or fall asleep for reborn like zombie.

**Comment by SeriousBuggie** [comment]
Test map from Barbie for reproduce bug:
[TestInvulnerableMercenary.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7877603/TestInvulnerableMercenary.zip)
1. Touch trigger and try kill mercenary.

Expected result: merc can be killed.
Actual result: merc ignore any damage and can nor be killed.
