### ISSUE TITLE
[469b] bad choice for visibility info for group display on and off

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#553]
I think the new icons to display the state of the visibility of a group are a bad choice: What stands for "display it" and what for "not display it"? That is not obvious.
The checkboxes in older versions were much better.
![BadIcon](https://user-images.githubusercontent.com/81397053/134054346-eb478e1d-27a5-4d65-a7b1-a184d6d95f4e.jpg)

**Comment by stijn-volckaert** [comment]
The colored eye means visible. The greyed out eye means invisible. This is consistent with the behavior of several other two-state icons in the editor, but I agree the icons could be improved.

**Comment by SeriousBuggie** [comment]
v469c preview use better icons:
![img](https://user-images.githubusercontent.com/70026933/173325080-0aa3c52f-965e-434a-9691-ccaf6ff778fa.png)

**Comment by NeonKnightOA** [comment]
Additionally, add an option to switch icons with checkboxes, i.e. `"bIconsOnGroupTab=true/false"`.

There are people who come from other editors or dev tools that may be used to see icons rather than checkboxes.

**Comment by SeriousBuggie** [comment]
Icons is much more informative. Anyway we goes from checkboxes, since there are need two switches.

**Comment by SeriousBuggie** [comment]
What about current look in v469d RC2? If it fine, please consider close issue.

**Comment by SeriousBarbie** [comment]
Although I prefere checkboxes, open and closed eye is distinguishable now. Closed.
