### ISSUE TITLE
[469b] Hammer charge (loop) breaks during demoplay

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#560]
https://user-images.githubusercontent.com/58362332/135852296-8445301c-3e8b-4ff1-906a-3ac502743598.mp4

Both sound and visuals of the hammer are breaking, while charging. This is a long time issue present in every demo manager.

**Comment by NeonKnightOA** [comment]
If it's related to the demo recorder, you might need to open an issue in the respective repository:

https://github.com/stijn-volckaert/udemo

**Comment by BerserkerBG** [comment]
Thank you I will post it there
