### ISSUE TITLE
[469b] UnrealEd enhancement, add maximize/minimize icon on each window

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#562]
Idea for adding additional maximize/minimize icons on each window. (possibly keep the old maximize/minimize icon at the bottom bar as well)

Here is how it could look like:

![Screenshot_1587](https://user-images.githubusercontent.com/58362332/137501788-fadc93c2-49e2-48d1-be1c-579c6bd57d2c.png)
![Screenshot_1586](https://user-images.githubusercontent.com/58362332/137501792-eaae3281-3377-4163-9d71-51b023e86046.png)

**Comment by SeriousBuggie** [comment]
I suggest make double-click only implementation. I think it be better and exclude miss-click when you wanna activate window or use drag, but instead open it on full screen.
