### ISSUE TITLE
[469b] Add to UnrealEd configuration of viewport with one single viewport

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#572]
Suggestion add here:
![img](https://user-images.githubusercontent.com/70026933/138559971-ec2a78aa-f1b4-4173-9ca6-863c7c609586.png)
5th button for make only one single viewport.

Not sure for others users, but as for me it is most useful configuration. Maybe be useful for other.

**Comment by Snuggx** [comment]
Same here. Always used only 1 viewport.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/164059101-47ced098-ff6c-4069-b27d-9cd74eea55af.png)
