### ISSUE TITLE
[469b] OpenGL Brightness error

### ISSUE THREAD

**Issue by UBIr4** [OldUnreal/UnrealTournamentPatches#576]
On my notebook I'm running Windows 8.1 and the video card is Intel(R) HD Graphics 3000.
(I was going to ask you if it could be because of the video card that the new OpenGL doesn't look good)

I'm travelling. At home I have a Windows 10 + Geforce RTX 2080 SUPER/PCIe/SSE2, I don't remember the model. Hope the new OpenGL works there.

i did the reinstall right now just added the 436 patch, then the 469b. With everything I had to put on.
(I notice that if I leave it dark it doesn't have the words in black).The problem is that of course I prefer to play with more brightness for a better perception of the image
In patch 469 this does not occur, in 469a and 469b it does
https://www.youtube.com/watch?v=YgGv5j5T54k
But with utglr36 what the video shows doesn't happen.What can it be?

**Comment by stijn-volckaert** [comment]
OpenGLDrv's original brightness control doesn't work well on modern systems. @CacoFFF is working on a major update that, among other things, applies brightness using shaders. This will probably fix the problem.

**Comment by CacoFFF** [comment]
In v469c you'll be able to select how brightness is applied out of 3 different ways.

**Comment by stijn-volckaert** [comment]
New options added in 469c-RC2
