### ISSUE TITLE
[win][469a] Installer select Low resolution when you change 3D device to software render

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#58]
![scr_1601293615](https://user-images.githubusercontent.com/70026933/94428519-7802b700-0199-11eb-9140-2a11e811e1f2.png)

It is mean:
```
[WinDrv.WindowsClient]
WindowedViewportX=640
WindowedViewportY=480
WindowedColorBits=32
FullscreenViewportX=800
FullscreenViewportY=600
FullscreenColorBits=32
```
If you use more then one monitor and `StartupFullscreen=True` this break all other open windows, its size position, monitor where its located, order of buttons on task bar and so on.

Software render is safe for any resolution, so it must use native screen monitor resolution for fullscreen mode by default.
Window mode resolution can be any - this not affect other windows.
But I advice something more then 640x480 - we are not in 2000 anymore. Of course it must be less from real desktop size, in any case.

**Comment by stijn-volckaert** [comment]
SoftDrv is not safe at all resolutions. It has all kinds of hardcoded limits which are not easy to remove unless we rewrite hundreds (if not thousands) of lines of assembly code. The current maximum resolution is 2048x1200.

I do agree, however, that the default resolutions the game uses for SoftDrv are too low. We will see if we can do something about this in the next patch.

**Comment by SeriousBuggie** [comment]
> The current maximum resolution is 2048x1200.

It can be upper bound with prefer screen ratio. Possible choose from exists resolution for current setup, but lower from this limit.

**Comment by Dr-Flay** [comment]
If you look in the default.ini with the patch you should see these settings

> [WinDrv.WindowsClient]
> WindowedViewportX=1024
> WindowedViewportY=768
> WindowedColorBits=32
> FullscreenViewportX=1024
> FullscreenViewportY=768
> FullscreenColorBits=32

> [SDLDrv.SDLClient]
WindowedViewportX=1024
WindowedViewportY=768
WindowedColorBits=32
FullscreenViewportX=1024
FullscreenViewportY=768
FullscreenColorBits=32

This should be in your default.ini if the install went correctly

**Comment by SeriousBuggie** [comment]
Yes.
```
[WinDrv.WindowsClient]
WindowedViewportX=1024
WindowedViewportY=768
WindowedColorBits=32
FullscreenViewportX=1024
FullscreenViewportY=768
FullscreenColorBits=32
```
But obviously this not used by SoftDrv when init values, because values different. Its listed above.

**Comment by Chamberly** [comment]
I looked at this as well and got the defaulted low video resolution as well. However I find this coming from the 436 patch as 469a did not come with a ut.ini nor default.ini to overwrite.

**Comment by SeriousBuggie** [comment]
Partially fixed in v469b. Still same info in setup step:
```
High sound quality
High detail player skins
High detail textures
Low video resolution
```
But in result it set high resolution as must be.

**Comment by stijn-volckaert** [comment]
Pushed a fix. I won't keep this one open since it's only a minor issue.
