### ISSUE TITLE
[469b] Big triggers produce heavy lags in some cases (FCollisionHash issue)

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#582]
Reproduce:
1. Start [MH-AMC-MorpheusUnboundedV5.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7514108/MH-AMC-MorpheusUnboundedV5.zip)
2. Remove monsters: `killall scriptedpawn`
3. Goes to left side and pickup CS weapon:
![img](https://user-images.githubusercontent.com/70026933/141147729-062a21ba-4775-4c64-84b2-cd97ba11e818.png)
4. Point gun up right and shoot here:
![img](https://user-images.githubusercontent.com/70026933/141148033-72564a72-5da3-461b-bbd2-3dcede33532b.png)

Expected result: No lags.
Actual result: Heavy lags.
![FPS](https://user-images.githubusercontent.com/70026933/141148235-80eb74d4-32cb-4c51-bd5e-5a4c812a771d.png)
![STAT GLOBAL](https://user-images.githubusercontent.com/70026933/141148331-2a330fa8-1835-4619-8f5a-9df5b1c045d0.png)

In UnrealEd you can find few big actors:
```
ScriptLog: bCollideActors with big collision size can produce high load:
ScriptLog: TriggeredDeath0 CollisionHeight = 256.000000 CollisionRadius = 25000.000000
ScriptLog: Trigger138 CollisionHeight = 256.000000 CollisionRadius = 25000.000000
ScriptLog: SaveMonsters0 CollisionHeight = 256.000000 CollisionRadius = 20000.000000
```
If you remove it - no any lags.

As I see, it is FCollisionHash issue.
This actors appear near in each hash basket. And CS weapons able penetrate walls and use very wide range of shoot.
So on some directions, collision check constantly iterate over hash baskets with this few actors, which cause lags,

OFC I fix this actors in next map version, but hope this info will be useful for optimize FCollisionHash for such cases.

**Comment by an-eternity** [comment]
Same problem was with the map "MH-ShootingGuys(Obnoxious)" that has very large collision size trigger.
Any weapon that calls `Trace`/`TraceActors` functions frequently (10 and more times per second) and uses a very long trace distances, if pointed into the appropriate direction in that map - was able even to take the server offline for a while.
It affects all versions from 436 to 469. Some older v469 builds affected more due to existed FCollisionHash issues... Latest 469c builds have them fixed so that its performance is quite acceptable, at least not worse than with v451.

This problem was already mentioned somewhere in another issue...

**Comment by an-eternity** [comment]
It was issue # 371, there was also some information that may be useful for further FCollisionHash optimizations/improvements.

**Comment by SeriousBuggie** [comment]
> Latest v469c builds have them fixed so that its performance is quite acceptable, at least not worse than with v451.

In this issue sshots taken on near latest v469c builds. Drop from 60 to 3-4 fps locally.

**Comment by an-eternity** [comment]
Did you compare it with v436-v451? Need to do if no... If performance drop will be significantly less than with v469c, this would mean we have missed something when tested FCollisionHash...
In my test cases performance drop with v469c was almost same as with v451 (for this reason i used the word "acceptable"), though it was also very much - latency was reaching over 1 second up to complete hanged state until the test stopped.

**Comment by SeriousBuggie** [comment]
436
![img](https://user-images.githubusercontent.com/70026933/141311117-4d780044-8cc3-494d-ae31-94606a342022.png)
![img](https://user-images.githubusercontent.com/70026933/141311184-617378df-4b44-4794-8707-5d0f741fba08.png)
469b
![img](https://user-images.githubusercontent.com/70026933/141310860-a2e85fe8-3339-43f7-830c-8035c16fca4f.png)
![img](https://user-images.githubusercontent.com/70026933/141310819-5391f4a6-455b-4a53-abd6-3016877f69be.png)
469c
![img](https://user-images.githubusercontent.com/70026933/141311558-61b28315-b6bd-400e-bd5c-93e7ac7e681d.png)
![img](https://user-images.githubusercontent.com/70026933/141311667-65717b70-eed8-4635-a8a8-aa145a28494c.png)

I not see any improvement. Maybe even opposite. Maybe this is just floating mistake. Load not always same.

**Comment by an-eternity** [comment]
Yes, these results look the same as in my tests - performance drop was almost equal in all versions from v436 to v469c (except some old v469 builds).
There is an improvement only in comparison with older v469 builds where FCollisionHash issue caused too high performance drop in such test cases as this one.

**Comment by stijn-volckaert** [comment]
This is the reason UT200x switched to an octree-based collision system. Collision hashes are easy to implement but they are horribly slow when the level has large objects. We might be able to backport the octree system from 2k4 or 227, but this is not a priority at the moment.
