### ISSUE TITLE
[469b] M1 support for Mac

### ISSUE THREAD

**Issue by sxflynn** [OldUnreal/UnrealTournamentPatches#583]
Will there be a universal build that includes support for Apple Silicon M1 processors?

**Comment by stijn-volckaert** [comment]
We have a build for 469c running internally but we're not sure if we will release a universal build. The app bundles for x86 and M1 will probably remain separate

**Comment by naymapl** [comment]
So any chance to create build for arm64 apple silicon ? This will handy for all new macs. Thank you for any info.

**Comment by stijn-volckaert** [comment]
M1 native support is now available in v469-RC2. The client has a few bugs, but those will be fixed in RC3
