### ISSUE TITLE
Doesn't start on Fedora 35

### ISSUE THREAD

**Issue by CommonLoon102** [OldUnreal/UnrealTournamentPatches#589]
I get the following error message:
`./ut-bin: error while loading shared libraries: libfreetype.so.6: cannot open shared object file: No such file or directory`
Despite that it is there: `/usr/lib64/libfreetype.so.6`.
I copied it to the game's `System` folder but still no luck.
Any advice?

**Comment by CommonLoon102** [comment]
OK, the solution was this:
`sudo dnf install libfreetype.686`

Reason: I had the 64 bit version (it was in the `lib64` folder). `ut-bin` needs the 32 bit version of libfreetype.

**Comment by uralets** [comment]
the binary is 32 bit thought you knew that

**Comment by CommonLoon102** [comment]
Yeah I just should have used my brain :D
