### ISSUE TITLE
[469b] Make new fonts optional

### ISSUE THREAD

**Issue by lafoxxx92** [OldUnreal/UnrealTournamentPatches#599]
Some prefer default sharp fonts, your ones are very blurred and hard to read

**Comment by stijn-volckaert** [comment]
The old font textures didn't scale to higher resolutions so we had to regenerate them. Unfortunately, we cannot reproduce the original textures on modern Windows systems. If you absolutely want the old fonts, then I recommend switching back to 436

**Comment by sn260591** [comment]
@lafoxxx92 For older fonts, restore the original LadderFonts.utx and UWindowFonts.utx files in the Textures folder.
