### ISSUE TITLE
UCC Make Hangs

### ISSUE THREAD

**Issue by Deaod** [OldUnreal/UnrealTournamentPatches#6]
Steps to reproduce: 

1. Navigate to your UT99 installation folder in a command line window (please make sure the path does not contain spaces for now)
2. `git clone https://github.com/Deaod/InstaGibPlus.git InstaGibPlus5`
3. `cd InstaGibPlus5 & git checkout v469-compat`
4. `build` (will invoke `ucc make -ini=<YourPath>\InstaGibPlus5\make.ini`)

Heres a partial log that UCC spits out (incomplete, process doesnt terminate): [UCC.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/5265083/UCC.log)

**Comment by stijn-volckaert** [comment]
This doesn't happen for me. What kind of terminal are you using to run this? Are you seeing the prompts that warn about compatibility problems? Could you use Process Explorer to generate a call stack and/or memory dump? This would be very useful for debugging.

**Comment by Deaod** [comment]
Hi,

I am using cmd.exe as my shell. I havent seen any warnings about compatibility issues.

[See here for dump](https://deaod.de/UCC.7z)

**Comment by stijn-volckaert** [comment]
The dump shows that ucc hangs because it displayed a compatibility warning and it is waiting for you to answer yes or no. Are you piping the output of your build command to a file? Or is there some other reason you can think of that would break the prompts?

**Comment by Deaod** [comment]
I was using SublimeText to build. It doesnt show the prompt i see when i invoke ucc make on a command line manually. I guess that solves this. Thanks.
