### ISSUE TITLE
[469a][win] XOpenGL - no crosshair visible in the display preference > HUD menu

### ISSUE THREAD

**Issue by Chamberly** [OldUnreal/UnrealTournamentPatches#60]
![image](https://user-images.githubusercontent.com/11419314/94452611-ba1dff80-017d-11eb-8d7f-3b380f4db806.png)
When I tried to change it by moving the scale slider left or right it doesn't appear.

<details>
  <summary>XOpenGL Entry : Click to expand and view</summary>

  ```
 [XOpenGLDrv.XOpenGLRenderDevice]
UseBufferInvalidation=False
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
NoBuffering=False
UseOpenGLDebug=False
DebugLevel=2
UseBindlessTextures=False
UsePersistentBuffers=False
SyncToDraw=False
GenerateMipMaps=False
NoAATiles=True
BumpMaps=True
MacroTextures=True
GammaCorrectScreenshots=True
UseAA=True
UseTrilinear=True
UsePrecache=True
AlwaysMipmap=False
ShareLists=True
NoFiltering=False
MaxAnisotropy=4.000000
LODBias=0.000000
GammaOffsetScreenshots=0.700000
NumAASamples=4
RefreshRate=60
UseVSync=Off
OpenGLVersion=Core
DetailTextures=True
DescFlags=1
Description=GeForce GTX 1050 Ti/PCIe/SSE2
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
UseHWClipping=False
UseHWLighting=False
  ```
</details>
Log:
[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/5293371/UnrealTournament.log)

Windows OS Server R2 2012
GeForce GTX 1050 Ti

**Comment by SeriousBuggie** [comment]
Try uncheck Automatic Crosshair Scaling. When it checked slider do nothing.

**Comment by stijn-volckaert** [comment]
Most likely the same issue as #44 #29 #38. Should be fixed in v469b.

**Comment by Chamberly** [comment]
> Try uncheck Automatic Crosshair Scaling. When it checked slider do nothing.

Yeah that made it appear.

Woo, so many references to other issues!

**Comment by SeriousBuggie** [comment]
As I see not an issue at all. @Chamberly confirm that if it is true. And close issue if need.

**Comment by Chamberly** [comment]
Kind of. Now it show partially.
![image](https://user-images.githubusercontent.com/11419314/98570500-84425f80-2281-11eb-9414-f67de9dd70de.png)
