### ISSUE TITLE
[469b] Bad FPS, stuttering on Soft Rendering

### ISSUE THREAD

**Issue by lafoxxx92** [OldUnreal/UnrealTournamentPatches#604]
Game is unplayable at higher res, slows down when you use Pulse Gun Alt.fire
Works great on v436

**Comment by stijn-volckaert** [comment]
This is a fundamental limitation of SoftDrv. Won't fix

**Comment by lafoxxx92** [comment]
Seems resolved. Tested in 469e, but on another PC.

**Comment by lafoxxx92** [comment]
Issue resolved in Windowed mode, even Hires.
In Fullscreen persists even in Lowres.
469e latest
