### ISSUE TITLE
[469b] Add option to filter only Textures (no Lightmaps)

### ISSUE THREAD

**Issue by lafoxxx92** [OldUnreal/UnrealTournamentPatches#609]
Some prefer game to look pixelated. 
Use NoFilter helps, but Lightmaps get pixelated too. 
Software Mode isn't an option (low framerate)

**Comment by CacoFFF** [comment]
In v469c the OpenGLDrv render device replaces NoFiltering with ForceNoSmooth, it's a simplification in how the 'nearest neighbor' filter is applied.
It will simply tell the render device to treat all surfaces as 'No Smooth', which will make lightmaps look non-pixelated in the end.

**Comment by Riccardoman** [comment]
Can you also implement super sampling to avoid extensive jittering in maps with high contrast textures?

**Comment by Riccardoman** [comment]
Very happy with the performance boost on opengl xopengl. I'm using the nearest filter on opengl (in xopengl it doesn't work in xopengl) but i noticed that the anisotropic filter gets disabled while using nearest?

**Comment by stijn-volckaert** [comment]
The updated opengldrv is now available

**Comment by metallicafan212** [comment]
DX9 is not planned to receive updates like that as it's "holy ground" for many of our users. We are only making feature changes when things absolutely require it (like shader gamma to make gamma work on 8.1+, line occlusion).

Changing how an option works (even for the better) in DX9 will encoure wrath from a subset of our community.

**Comment by lafoxxx92** [comment]
> DX9 is not planned to receive updates like that as it's "holy ground" for many of our users. We are only making feature changes when things absolutely require it (like shader gamma to make gamma work on 8.1+, line occlusion).
> 
> Changing how an option works (even for the better) in DX9 will encoure wrath from a subset of our community.

What about DX11 then?
