### ISSUE TITLE
[469a] Wrong ammunition count on weapon model

### ISSUE THREAD

**Issue by joranm1** [OldUnreal/UnrealTournamentPatches#61]
Hi, I just found out that when you pick a weapon up, it sometimes show the wrong ammunition count, examples below:
![Capture d’écran de 2020-09-28 22-20-17](https://user-images.githubusercontent.com/64244522/94483106-aa80d400-01da-11eb-8762-901519e9b553.png)
![Capture d’écran de 2020-09-28 22-16-09](https://user-images.githubusercontent.com/64244522/94483074-989f3100-01da-11eb-90e4-3141326eb9c0.png)
![Capture d’écran de 2020-09-28 22-16-42](https://user-images.githubusercontent.com/64244522/94483078-9a68f480-01da-11eb-93c9-be3e64d2379d.png)

**Comment by CacoFFF** [comment]
Fixed on v469b
