### ISSUE TITLE
[469b] UnrealEd does not set the "modified-state" of a map when only code was changed

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#615]
When only editing and compiling code in an existing map, UnrealEd does not ask for saving the map when closing it. So the "I-was-modified-flag" of a map seems not be set. (But it asks when just another Actor was selected. Wired.)

**Comment by SeriousBuggie** [comment]
No such flag. Current implementation very simple - if undo history not empty - then ask. Undo history cleared on any build. And no any undo history for change or compile scripts.

**Comment by SeriousBarbie** [comment]
Yes, that may be an explanation for it but my expectation is that if something was changed by the user, that thing has to be marked as modified and a program must ask if that should be saved persistently.
