### ISSUE TITLE
[469a] Touch event detection differs from previous versions

### ISSUE THREAD

**Issue by Deaod** [OldUnreal/UnrealTournamentPatches#62]
v469a calls Actor.Touch events more accurately than previous versions. This causes desynchronisation between a v469a server and older clients (v436 through some v469 private beta build).

Heres a short video demonstrating the issue: https://youtu.be/oFR3lHswUNI  
To see the debug messages, type "EnableDebugData 1" on console, use 0 instead of 1 to disable again, or reconnect.

The following two packages demonstrate a workaround:

1. [IGPlus5-TouchDesync.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5299875/IGPlus5-TouchDesync.zip)
2. [IGPlus5-TouchFixed.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5299632/IGPlus5-TouchFixed.zip)

The .int contains two mutators that are necessary to reproduce the issue: InstaGibPlus5.UTPure and InstaGibPlus5.ST_Mutator. Only works with dedicated server and client. Standalone and ListenServer are not supported. 

The workaround is contained within NN_Kicker.uc and verifies that a Touch event is only triggered for an Actor that is actually colliding with the kicker, rejecting those where the collision cylinders are not touching/overlapping.

**Comment by CacoFFF** [comment]
The physics engine internally adds 2 units of distance to player movement to avoid floating point math errors, then scales down and discards those results at or beyond said 2 units.

The bug? The discarding only happened with solid objects and I extended this to all objects.

**Comment by Deaod** [comment]
This should be noticeable around teleporters as well, it was just easier to reproduce with kickers.

**Comment by CacoFFF** [comment]
You will not have to worry about this on v469b
