### ISSUE TITLE
[469b] Loading a savegame can fail due to missing Dynamic Fonts

### ISSUE THREAD

**Issue by stijn-volckaert** [OldUnreal/UnrealTournamentPatches#624]
Issue transfered from OldUnreal.com
[Save141.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7660241/Save141.zip)

**Comment by CacoFFF** [comment]
Dynamic fonts could be created with PF_Transient flag on them, and the code that creates them could verify that the fonts exist before using them (or create again).

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
