### ISSUE TITLE
[469b] Are the patches free open source software similar to gzdoom?

### ISSUE THREAD

**Issue by ghost** [OldUnreal/UnrealTournamentPatches#627]

**Comment by SeriousBuggie** [comment]
No. Read [LICENSE.md](https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/LICENSE.md).

**Comment by stijn-volckaert** [comment]
Some parts of the game were open sourced as part of the UT v432 SDK. The UT v469 SDK will also contain parts of UnrealEd. Most of the core packages (e.g., Core, Engine, Render) are not open source, however.
