### ISSUE TITLE
[Mac] Unable to launch: GetPropertiesSize

### ISSUE THREAD

**Issue by lochlainn** [OldUnreal/UnrealTournamentPatches#63]
I'm using the latest version of OldUnreal, with a fresh GOG install copied from a Windows machine.
Here's the error I get when trying to run the game:

<img width="532" alt="Screen Shot 2020-09-29 at 1 20 58 PM" src="https://user-images.githubusercontent.com/3210509/94591971-c9bd4700-0256-11eb-8c34-ec1642f1be25.png">

Some more info about my setup:
MacOS 10.14.6
Intel graphics
I tried both putting the files in Application Support, and placing them within the .app itself.

**Comment by lochlainn** [comment]
Strangely enough, a reinstall fixed the issue. Closing.

**Comment by WilczekCK** [comment]
Well, it happened to me now - exactly the same issue, on the same line as on screenshot.
Reinstall did not give any effect.

MacOS 11.0.1 (Big Sure)

**Comment by stijn-volckaert** [comment]
This error triggers when the size of an UnrealScript class does not match the size of its C++ counterpart. I suspect you may have copied some of the .u files from your Windows/Linux installation into the app bundle or into the Application Support folder. All of the necessary .u files came with the bundle so there is no need to copy any over from an existing installation. If you can't manage to fix the problem, then please come talk to me on Discord (AnthraX @ the ut99.org server) or send me a PM on the OldUnreal forum (anth @ oldunreal.com) so I can give you a bundle for the upcoming 469b version.

**Comment by WilczekCK** [comment]
I tested it with Steam version of the UT99 and files from this topic:
https://www.reddit.com/r/unrealtournament/comments/evv9hd/unreal_tournament_99_for_macos/

Both of them does not work. I assume, that I use wrong files for MacOS to work.
