### ISSUE TITLE
[469b] Paste default properties eat slashes

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#633]
Reproduce:
1. Copy Default properties on PulseGun. Paste in some text compare tool.
![img](https://user-images.githubusercontent.com/70026933/147603554-f8911b4f-a071-4f51-83e7-0302012e81b1.png)
2. Paste it back.
![img](https://user-images.githubusercontent.com/70026933/147603603-cbd0c47f-0e30-4d84-9447-0e7c490ce80e.png)
3. Copy again. Paste in some text compare tool.

Expected result: Properties still same as in first time.
Actual result: WeaponDescription lost slashed escape sequences:

before: `WeaponDescription="Classification: Plasma Rifle\n\nPrimary Fire: Medium sized, fast moving plasma balls are fired at a fast rate of fire.\n\nSecondary Fire: A bolt of green lightning is expelled for 100 meters, which will shock all opponents.\n\nTechniques: Firing and keeping the secondary fire's lightning on an opponent will melt them in seconds."`

after: `WeaponDescription="Classification: Plasma RiflenPrimary Fire: Medium sized, fast moving plasma balls are fired at a fast rate of fire.nSecondary Fire: A bolt of green lightning is expelled for 100 meters, which will shock all opponents.nTechniques: Firing and keeping the secondary fire's lightning on an opponent will melt them in seconds."`

Workaround: Double any slash before paste.
If you want paste `"\n"` - paste `"\\n"`.

**Comment by SeriousBuggie** [comment]
Look like problem not in paste but in copy, because in .uc files slashes doubled. So need make copy double them too.

**Comment by stijn-volckaert** [comment]
This will be fixed in 469c. The string property exporter did not escape special characters. This bug also exists in UE2, UE3 and in the current version of 227j.

**Comment by SeriousBuggie** [comment]
Confirmed, fixed in v469c preview.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
