### ISSUE TITLE
[469b] Meshes disappearing while walking towards it

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#637]
Hi, in DM-Deck16][ when i walk towards a Flak gun pickup, halfway the gun disappears, and a bit further on it appears again. Due to this bug people may think that someone else took the gun already, so it's impacting the regular gameplay quite badly.

At the end of the video you can see my settings. I didn't modify any settings after the patch installation.

Thanks for the good work on keeping this game alive in any case!

https://user-images.githubusercontent.com/22099136/145677476-603a89a2-2322-423b-92a0-c881df83e7f3.mp4

.

**Comment by stijn-volckaert** [comment]
This will be fixed in 469c. If you want the fix right now, you can use this XOpenGLDrv instead:
https://oldunreal.com/betatesting/XOpenGL-469b-Fix2.zip

**Comment by Engineer9736** [comment]
Thank you! :)

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
