### ISSUE TITLE
[469a] UsePrecache=True causes textures to display incorrectly

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#64]
This was also observed in version 436 and is clearly visible at the beginning of the Dig level.
On **D3D7**, **OpenGL** and **D3D9**, some textures are rendered without smooth:

![Shot00002](https://user-images.githubusercontent.com/10724977/94684064-2b9daf80-0330-11eb-9aef-487e10105c8e.jpg)
![Shot00003](https://user-images.githubusercontent.com/10724977/94684074-32c4bd80-0330-11eb-89a9-f37691042fd9.jpg)
_________________________________________________________________
On **XOpenGL**, this happens with some lightmaps:

![Shot00001](https://user-images.githubusercontent.com/10724977/94684177-5e47a800-0330-11eb-85fd-d49fd6abbd3f.jpg)

**Comment by sn260591** [comment]
It was also noticed that precache can make surfaces full of holes, as if they had the Masked flag turned on (in the screenshot [DM-Aberrance](https://unrealarchive.org/maps/unreal-tournament/deathmatch/A/dm-aberrance_be38e9ac.html)):
![Shot00018](https://user-images.githubusercontent.com/10724977/98352510-274f6b00-202f-11eb-9712-2b0d0b7a292c.jpg)

**Comment by CacoFFF** [comment]
This was the result of an extremely ugly legacy fix surrounding No Smooth/Masked flags, if it found a surface with those flags, it directly applied it to the texture (and therefore to every other surface without said flags).
