### ISSUE TITLE
[469b] Make settings to adjust the chat transparency and/or size

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#640]
Sometimes maps are so bright that the chat is hard to read. It would be helpful if there was an option in the menu to adjust the transparency of the chat. I tried all the transparency sliders but none affect the chat area. An option to adjust the chat area font size could be helpful as well.

I want to keep all the other GUI elements the size and transparency level as they are, so a combined setting for everything is not preferable.

![ut99-chat-badly-readable](https://user-images.githubusercontent.com/22099136/145713964-555b81a0-8443-439e-ba1d-9fb62669c6de.png)

The GUI drawing functions for this are in Botpack.ChallangeHUD in the function DrawSpeechArea.

The is this line: Canvas.Style = ERenderStyle.STY_Translucent;

I guess some line has to be added after it which sets the specific transparency.

**Comment by stijn-volckaert** [comment]
The HUD transparency slider also sets the transparency of the chat area. Somewhat confusingly, however, you have to slide it all the way to the right to make the chat area opaque.

**Comment by Engineer9736** [comment]
I have the slider all the way to the right, but it's still transparent. Maybe some other setting needs to be on a specific position as well to make it opaque?

![Untitled](https://user-images.githubusercontent.com/22099136/147597248-47b8aa82-cffd-4567-b40b-0d035ed80eaa.png)

**Comment by SeriousBuggie** [comment]
Possible bug of old nexgen. it is always draw chat area translucent.
Class NexgenHUD, function renderMessageBox:
```
	c.style = ERenderStyle.STY_Translucent;
```
But must be (Nexgen112N):
```
	c.style = ERenderStyle.STY_Translucent;
	if ( (ChallengeHUD(player.myHUD).Opacity == 16) || !Level.bHighDetailMode )
		C.Style = ERenderStyle.STY_Normal;
```
Check nexgen version used on this server.

**Comment by SeriousBuggie** [comment]
Can not be solved in easy way. need modify textures.
Textures for render chat area:
![img](https://user-images.githubusercontent.com/70026933/174543865-3035bb95-925c-4ab4-a8e3-9970fa4b518e.png)
ERenderStyle.STY_Masked or ERenderStyle.STY_Normal produce black area:
![img](https://user-images.githubusercontent.com/70026933/174544150-ba05626e-fb61-4e2b-a8c5-dbee26faaf9d.png)
![img](https://user-images.githubusercontent.com/70026933/174544197-dbe48df3-e9ff-4faf-8114-bbc9d390774b.png)
So need remake textures for black be first color in pallete (transparent for Masked output. But even with that it can be look dirty, since border be sharp on corners.

**Comment by SeriousBuggie** [comment]
Nexgen us edifferent approach and draw chat area from many calls and small texture:
![img](https://user-images.githubusercontent.com/70026933/174545747-89dac913-37c4-4d33-8827-27326d044026.png)
```js
	// Borders.
	c.drawColor = baseHUDColor * 0.8;
	c.setPos(0.0, 0.0);
	c.drawTile(Texture'base', msgBoxWidth, 1.0, 0.0, 0.0, 1.0, 1.0);
	c.setPos(0.0, msgBoxHeight - 1.0);
	c.drawTile(Texture'base', msgBoxWidth, 1.0, 0.0, 0.0, 1.0, 1.0);
	c.setPos(msgBoxWidth - 1.0 - panelWidth, panelHeight + 1.0);
	c.drawTile(Texture'base', panelWidth, 1.0, 0.0, 0.0, 1.0, 1.0);
	c.setPos(0.0, 1.0);
	c.drawTile(Texture'base', 1.0, msgBoxHeight - 2.0, 0.0, 0.0, 1.0, 1.0);
	c.setPos(msgBoxWidth - 1.0, 1.0);
	c.drawTile(Texture'base', 1.0, msgBoxHeight - 2.0, 0.0, 0.0, 1.0, 1.0);
	c.setPos(msgBoxHeight - 1.0, 1.0);
	c.drawTile(Texture'base', 1.0, msgBoxHeight - 2.0, 0.0, 0.0, 1.0, 1.0);
	c.setPos(msgBoxWidth - 2.0 - panelWidth, 1.0);
	c.drawTile(Texture'base', 1.0, msgBoxHeight - 2.0, 0.0, 0.0, 1.0, 1.0);
	
	// Panels.
	renderPanel(serverState, c, panelHeight, msgBoxWidth - panelWidth - 1.0, 1.0);
	renderPanel(clientState, c, panelHeight, msgBoxWidth - panelWidth - 1.0, panelHeight + 2.0);
```
```js
/***************************************************************************************************
 *
 *  $DESCRIPTION  Renders a panel with the specified contents at the given location.
 *  $PARAM        pInf         Panel contents.
 *  $PARAM        c            Canvas object that provides the drawing capabilities.
 *  $PARAM        panelHeight  Vertical space available for the panel (in pixels).
 *  $PARAM        x            Horizontal offset.
 *  $PARAM        y            Vertical offset.
 *  $REQUIRE      pInf != none && c != none && panelHeight > 0
 *
 **************************************************************************************************/
simulated function renderPanel(PanelInfo pInf, canvas c, float panelHeight, float x, float y) {
	local float separatorWidth;
	local float cx;
	local float cy;
	local float iconHeight;
	local float lifeTime;
	local float blinkFactor;
	local float blinkIntensity;
	
	if (pInf.bBlink) {
		blinkFactor = (1.0 + cos(timeSeconds * 2 * pi * panelBlinkRate)) / 2.0;
		blinkIntensity = (1.0 - blinkFactor) * 255.0;
	}
			
	separatorWidth = int(baseFontHeight * 0.4);
	
	// Draw icon.
	cx = x + separatorWidth;
	if (pInf.icon != none) {
		if (iconSize > panelHeight) {
			iconHeight = panelHeight;
			cy = y;
		} else {
			iconHeight = iconSize;
			cy = y + int((panelHeight - iconSize) / 2.0);
		}
		
		c.style = ERenderStyle.STY_Translucent;
		
		if ( (ChallengeHUD(player.myHUD).Opacity == 16) || !Level.bHighDetailMode )
		   C.Style = ERenderStyle.STY_Normal;




		c.drawColor = blankColor;
		c.setPos(cx, cy);
		c.drawTile(pInf.icon, iconHeight, iconHeight, 0.0, 0.0, iconSize, iconSize);
		if (pInf.solidIcon != none) {
			c.style = ERenderStyle.STY_Normal;
			c.setPos(cx, cy);
			c.drawTile(pInf.solidIcon, iconHeight, iconHeight, 0.0, 0.0, iconSize, iconSize);
		}
		
		cx += separatorWidth + iconHeight;
	}
	
	// Draw the text.
	cy = y + (panelHeight - baseFontHeight) / 2.0;
	c.style = ERenderStyle.STY_Normal;
	c.drawColor = pInf.textCol;
	if (pInf.bBlink) {
		c.drawColor = c.drawColor * blinkColorDamp;
		c.drawColor.r = int(float(c.drawColor.r) * blinkFactor + blinkIntensity);
		c.drawColor.g = int(float(c.drawColor.g) * blinkFactor + blinkIntensity);
		c.drawColor.b = int(float(c.drawColor.b) * blinkFactor + blinkIntensity);
	}
	c.setPos(cx, cy);
	c.font = baseFont;
	c.drawText(pInf.text, false);
}
```

**Comment by SeriousBuggie** [comment]
As solution we can goes nexgen way and build chat area from thousand pieces. And rule by turn on/off transparency for it.
Not sure if this work with set level of transparency.

As second approach - introduce another set of textures, make it same as of original, but use as masked.

Third approach - edit existing textures, make them black color masked and try out as masked texture.

**Comment by SeriousBuggie** [comment]
Third way without touch textures and masked output - draw solid black background before draw this crappy transparent textures.
Look as possible PR.
