### ISSUE TITLE
[469b] Wrong ReducedDamageType for Queen

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#641]
Queen.uc contain mistake in `ReducedDamageType`:
```
	 ReducedDamageType='shot'
	 ReducedDamagePct=+0.5
```
So in game it turn to None.
Need fix something. Or make 
```
	 ReducedDamageType=None
	 ReducedDamagePct=0
```
Or make
```
	 ReducedDamageType=shot
	 ReducedDamagePct=+0.5
```

**Comment by SeriousBarbie** [comment]
Hmm, my Queen.uc shows just an apostrophe for that (see [_ReducedDamageType of UnrealI.Queen_ on UT99.org](https://ut99.org/viewtopic.php?f=5&t=11302))

**Comment by SeriousBuggie** [comment]
You look on decompiled source. I look into original source.
OFC `ReducedDamageType='shot'` not able compile in something good. so you see `None` or `'` when decompile result.
`defaultproperties` not store original source, from which compile, only result.

**Comment by Marco888** [comment]
Changing that now would change game balance with queens, so I would just leave it as None.

**Comment by stijn-volckaert** [comment]
We had an internal discussion about this one and the consensus is that this should be considered a "good bad bug".

**Comment by SeriousBuggie** [comment]
You can't `wontfix` this. Need choose one fix or another. 

Or make
```
	 ReducedDamageType=None
	 ReducedDamagePct=0
```
Or make
```
	 ReducedDamageType=shot
	 ReducedDamagePct=+0.5
```

Now 
```
	 ReducedDamageType=None
	 ReducedDamagePct=0.5
```
Which is nonsense.
