### ISSUE TITLE
[469b] Flying pawns able stuck in air

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#652]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4501

Reproduce:
1. Start map [DM-!!!!!fly_monsters_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7791950/DM-.fly_monsters_bug.zip)

Expected result: Flies fly to you and attack you.
Actual result: Flies stuck in air.

You can kill top fly. Corpse stay in place and prevent lower fly to move. Until not vanished or destroyed.

So this stuff actual not only for flying creatures. But for them it is actual because normally hardly fit condition for not flying creatures.
Or (possible) only flying physics affected by this bug.

Here properties from accidentally collide without special start condition:
![img](https://user-images.githubusercontent.com/70026933/147731872-d8508e9b-7193-4fea-bfd0-b29cf0944e0b.png)
Here as it look from test map on UnrealEd:
![img](https://user-images.githubusercontent.com/70026933/147731905-02861868-5f53-4148-8c12-df7945ed1541.png)
After I increase Z distance flies unstuck and goes attack me as usual.

So I think this issue happens when distance on Z coordinate exactly fit both collision height.

It happens rare because need met some conditions - Z-distance must be exactly as CollisionHeight*2.
Also possible need additional conditions:
- on calculate it must produce round error, so engine think about overlap collision cylinders.
- or maybe it must produce clear float zero.

All of this typical for check equality float to zero in code. Possible implicit via use ">=" instead ">" or vice versa.

**Comment by SeriousBarbie** [comment]
(Your URL links to the top page of the BBS, not the thread.)

**Comment by SeriousBuggie** [comment]
> (Your URL links to the top page of the BBS, not the thread.)
Forum not public. Link proper. No any mistake. Possible you not have rights for see it.

**Comment by an-eternity** [comment]
Same happens with 'NWCybotLauncherVIII.CybDrone'...
Still unclear why only some of flying classes affected, and with rest this never happens...

**Comment by SeriousBarbie** [comment]
I noticed that as well with Flies and with Mantas, but never with Gasbags or Warlords.

**Comment by SeriousBuggie** [comment]
I think this connected with math and collision height.
Possible Gasbags and Warlords use collision height which not allow exact match float math.
