### ISSUE TITLE
[469a] unrealed viewport bug

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#66]
![bug](https://user-images.githubusercontent.com/72151582/94707139-77912a00-0319-11eb-9d9e-d89e84d0e41a.png)

Maximize the 3D viewport and close editor. Next time you open you are forced to reset all viewports because of that. This is one of the oldest bugs.

**Comment by zero-khan** [comment]
It also happens by alt + tab and minimize unrealed.

**Comment by ZeroKhan1** [comment]
Not fixed in 469b.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
