### ISSUE TITLE
[469b] UnrealEd: Move active brush to current point via context menu

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#663]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4427

Will be helpful if added item "Move Brush here" near "Add Actor here" and "Add Light here" to context menu in the viewport.

**Comment by Snuggx** [comment]
Indeed.

**Comment by SeriousBuggie** [comment]
Also if right click on actor - command able use too - for move active brush to selected actor location.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/173407910-cd6caa1b-cd24-4d1c-8475-86cabd799cf1.png)
![img](https://user-images.githubusercontent.com/70026933/173407958-b0159e36-58a6-41c2-93a1-24d8d358639f.png)
![img](https://user-images.githubusercontent.com/70026933/173407997-b06eb469-8750-4737-af3e-48cb94fea9d7.png)
