### ISSUE TITLE
[469b] UnrealEd: make right edge of left toolbar draggable

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#665]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4443

If you make right edge of left toolbar draggable then that allow show 3 (or 4) buttons per row. Which useful for show all buttons if you have a lot additional buttons on that panel.
And avoid use scroll for this.

![img](https://user-images.githubusercontent.com/70026933/147737974-773e4f36-4a67-4444-9f55-db63fc918df3.png)

**Comment by Snuggx** [comment]
Ye, that scrolling nervs sometimes.

**Comment by SeriousBuggie** [comment]
Possible implementation (editable via UnrealEd.ini - [Options] - ToolBarWidth - [1-6]):
![scr_1650100832](https://user-images.githubusercontent.com/70026933/163671117-e966802d-3467-4073-9b35-9e1426274437.png)
![scr_1650102641](https://user-images.githubusercontent.com/70026933/163671119-b7750be7-e7df-4cbb-8f48-29bc1f9a6ddf.png)
