### ISSUE TITLE
[469b] UnrealEd show mover polys properly

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#671]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4463

Currently Movers exists in parallel reality. You can not watch polys of it. Can not edit it.

Of course you can do "Show Polys" command. Which break BSP and after that you need rebuild level from scratch. Which problem for huge levels.

IDK what really do "show polys", but you can use it and move Mover near. Start game and you see mover and strange copy of mover where you apply "show polys".

It is look like bad attempt add Additive Brush into BSP tree.
But what about remove it? Why for fix this "thing" need fully rebuild all geometry? Which can take 30 minutes.

---

For example:
Need remove "Special Lit" flag from one surface from mover. How to do that?

1. Polys to brush.
2. Save Brush.
3. Run second UEd.
4. Make big empty cube.
5. Load Brush.
6. Make additive brush.
7. Select surface.
8. Remove flag.
9. Polys to brush.
10. Save Brush.
11. Exit second UEd.
12. Load Brush.
13. Copy polys from brush.

or

1. Copy brush to text.
2. Edit in text editor. Of course if you able do this and this possible at all. For clear flag you need know bitmasks, value of flag and so on. Not for regular mapper.
3. Paste back.
4. Remove weird shift to 32uu on each axis.
5. Remove old brush.

As possible solution - draw movers over world. Like currently draw as wireframe, but same as textured brush. Surfaces on it can be selected and edited.
By default draw it as wireframe. By option you can toggle draw it as solid brush.
It is better from nothing.

---

It can be sprite for each poly.

As workaround can be dots on wireframe select which can select desired surface.
This can not allow visually align, pan or resize texture, but better from nothing.

Or mover can be converted to static brush in temp model and render above exists render surface with actual level.

Or even embed into existing bsp tree. But create two copy of bsp tree - for map which will be actually saved, and second one for render in editor.

**Comment by CacoFFF** [comment]
The only real fix is to improve the rendering system to draw polygons straight off their brushes like static meshes, much easier to do with Z buffering and unfortunately won't work with SoftDrv

**Comment by SeriousBuggie** [comment]
Another reason rid of from SoftDrv. Or use few renders.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1722934745](https://github.com/user-attachments/assets/1d3a0126-a630-4257-9f34-99d01179e24f)
![scr_1722934760](https://github.com/user-attachments/assets/28e0244b-88b3-46a1-9cee-0c7bfca32797)
Work per render:
Software - bad.
OpenGL - good
XOpenGL - bad
D3D - good
D3D9 - good
D3D11 - good
ICBIND - good
