### ISSUE TITLE
[469b] UnrealEd not recognize LOG= or ABSLOG= cmd params

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#673]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4472

Reproduce:
1. start UEd with param:
`UnrealEd LOG=Editor2.log`
or
`UnrealEd ABSLOG=Editor2.log`

Expected result: As log used System\Editor2.log
Actual result: As log used System\Editor.log

v436: bugged.
v469: bugged.
v469c: bugged.

**Comment by stijn-volckaert** [comment]
will be fixed in 469c

**Comment by SeriousBuggie** [comment]
Confirmed, fixed for v469c preview.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
