### ISSUE TITLE
[469a] Minor DLL discrepancies

### ISSUE THREAD

**Issue by Dr-Flay** [OldUnreal/UnrealTournamentPatches#68]
While testing the DLLs in VirusTotal I noticed a few minor things that need fixing but are low priority.
libcurl and OpenAL32 are both marked with "invalid-rich-pe-linker-version"

ALAudio.dll still contains the text "OpenAL for Unreal 227j"

**Comment by stijn-volckaert** [comment]
This should be fixed in 469c. Since this is only a minor issue, I'm going to close this ticket immediately.
