### ISSUE TITLE
[469b] UnrealEd: Add options to Brush Order menu

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#681]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4446

Add options to Brush Order menu (To First, To Last):

1. Memorize brush.
2. Before memorized brush.
3. After memorized brush.

It is allow insert brushes into specified position before or after known one.

**Comment by Snuggx** [comment]
That would be very handy.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![scr_1677411541](https://user-images.githubusercontent.com/70026933/221414197-abff10e1-3aef-4a62-94e1-c0f506fbc33e.png)
