### ISSUE TITLE
[469b] Smart join zones if their count more then 63

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#690]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4435

If you have more then 63 zone, then some of them will be joined.
Currently it work really blindly. If engine need zone 64, then it simply use index 1. For 65 - index 2 and so on.
I suggest in this case join water zone together, lava zones - together.
If this still not produce free number of zones - then use old algorithm.

It is allow avoid (if possible) join water/lava zone with usual zones.

Also another zone also can be take to account, like Tar zone, or space zone.

Higor:

> I'll add to this, zones containing no actors should be merged to zone 0 (LevelInfo) if count goes above 63

**Comment by CacoFFF** [comment]
This falls under 'undefined' behaviour category, the mapper HAS to be aware of these issues.
Still keep my idea of joining zones without actors (likely inaccessible substractions) in the level, then outputting a warning that zone count has gone above 63.

**Comment by SeriousBuggie** [comment]
Reproduce:
1. load into UnrealEd: [ZonesLimit.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/12925446/ZonesLimit.zip)
2. Build geometry.
3. Start play.

Expected result: You not die on start game.
Actual result: You die, since you appear be in Slime zone.

On map 160 zone. And 10 z0ne actors
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/6ba11b13-d018-422d-baf9-9cae386404ff)
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/394bcaf2-8730-4ace-a232-8e80e8e28c1b)
