### ISSUE TITLE
[469b] UnrealEd not listed all properties in default properties for class

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#696]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4413

If you call "Copy properties" on class then you get full list of properties.
But if you call "Default properties", then new window contains only properties define via from "var()" notation. No "var" notation.

Reproduce:
1. Right click on Object - Console in Actor browser.
2. Choose "Default properties" - window with only "Object" appear.
3. Do same for "Copy properties" and paste text somewhere - there a lot of properties.

**Comment by stijn-volckaert** [comment]
Added in 469c-RC2
