### ISSUE TITLE
[469b] Use 'MyLevel' as default package for new classes

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#697]
Moved from: https://www.oldunreal.com/phpBB3/viewtopic.php?f=42&t=4469

> When I go to create a new script or class it's on MyPackage, could we do it in MyLevel by default?
> 
> Just a thought.

**Comment by BerserkerBG** [comment]
Big ups for this, I had many issues where I forgot to check MyPackage to MyLevel since they are similar in name and if you're not careful you will mess things up, speaking from experience.

**Comment by SeriousBuggie** [comment]
Well. There possible two solution:
1. Make it `MyLevel`. Possible drawbacks
 - accidentally place in map scripts.
 - or save MyLevel.u and think it is OK
2. Make it `Package` or something other which not similar to `MyLevel`. Possible drawback:
 - need type more if want embed things into map.

**Comment by SeriousBarbie** [comment]
Why not simply disable saving packages with name "Mylevel" or "MyPackage" or show at least a warning? A help screen or a link to a help page would be useful, too.

**Comment by SeriousBuggie** [comment]
> Why not simply disable saving packages with name "Mylevel" or "MyPackage" or show at least a warning? A help screen or a link to a help page would be useful, too.

Disable not an option, because it can be useful: #707
Warning possible fine.
