### ISSUE TITLE
Decals are not visible in zones with bFogZone set to True

### ISSUE THREAD

**Issue by FrancescoBis** [OldUnreal/UnrealTournamentPatches#70]
Decal projections are not visible when inside zones of which the main ZoneInfo's variable bFogZone is set to True. They are visible otherwise.

Tested on:
Video drivers: D3D9, D3D10 and D3D11
Patch version: 436

This issue can be reproduced in 2 ways:
1. By placing a decal in editor, setting the zone main ZoneInfo's variable bFogZone to True and rebuilding the lighting.
2. By placing a decal in editor, [rebuilding the lighting] and set the zone main ZoneInfo's variable bFogZone to True at runtime while playing the map.

**Comment by racing-online** [comment]
When checking the scripts often can see they use to off bFogZone right before spawning the decal and then turn it back on when decal spawned. Looks like an old problem.

**Comment by FrancescoBis** [comment]
It is an old problem, I forgot to mention that I tested it on 436 and not 469.

**Comment by racing-online** [comment]
There were also another bugs with decals, they are fixed already. This one could be also fixed already, need to test.

**Comment by FrancescoBis** [comment]
Thanks, didn't know it. Most of the reports and suggestions I'll post on here were posted on a different forum, so some of them may have already been fixed/implemented.

**Comment by stijn-volckaert** [comment]
Indeed. We fixed this a while back. Decals are visible in fog zones now but they might look a bit weird as they have to be rendered differently if you apply fog to them. Please open another ticket if you think they don't look right in 469a. I'm going to close this one for now.
