### ISSUE TITLE
Going from fly or ghost back to walk on multiplayer doesn't work properly

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#703]
This is quite a well known bug i think. Not sure if there was a report about it already or even a conclusion.

If you are on a multiplayer server and have been flying or ghosting around, and then do 'walk' to go walk again, your player only slowly starts to move down and all the controls still seem to be working like flying mode. As soon as you touch the ground, you're stuck to the ground. Only suicide will fixes this situation, but then you'll respawn on a completely other location which is not preferred.

Would be great if the walk command would just do what the tin says.

**Comment by SeriousBuggie** [comment]
Duplicate of #257

**Comment by Engineer9736** [comment]
I see it will be fixed in the next version, then my issue report is not needed anymore i guess. I'll close it. Thanks for the information! 🙂
