### ISSUE TITLE
[469b] Update instructions for Linux - installation via Wine isn't necessary

### ISSUE THREAD

**Issue by uralets** [OldUnreal/UnrealTournamentPatches#704]
Could we update the installation instructions Readme section for Linux so it mentions that one doesn't have to presumably install the game through Wine first?
It's not hard to unpack the patch first then just mount the cd/image and copy over everything that's needed.
Only the maps have to be unpacked - and that only requires running ucc unpack in a trivial shell loop.
(I haven't checked what's inside the Gog release archive - if the maps are already unpacked there, well even better then)

But that's mild (or even minor) compared to having to resort to Wine mostly just to get the directory structure and layout which is already there within the distribution.
The only major (sort of) hurdle is map unpacking and that's easily doable as well, just need to provide the shell one liner that people could run.

Ofc there's always the option to have it installed "properly" via the old Loki installer (32 bit only obviously) which actually works with some light persuasion.

**Comment by stijn-volckaert** [comment]
We'd be happy to accept pull requests and/or installer scripts!

**Comment by uralets** [comment]
> We'd be happy to accept pull requests and/or installer scripts!
> 
> 

Think I'll do it.

But a couple of questions first

1) Isn't a 64bit Linux build on the horizon per chance? If it is, I'd
like to test it out while I'm composing the installation manual

2) The ucc unpacks the maps by default to .utpg/System. Could we
somehow tell it where to put them instead?

**Comment by uralets** [comment]
Well anyway https://github.com/OldUnreal/UnrealTournamentPatches/pull/747
