### ISSUE TITLE
[469c] UnrealEd displays code chopped up

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#705]
Sometimes UnrealEd (02. Jul 2021) displays the code really messy (see pic). Sadly I don't know how to reproduce that. Only the display is chopped up, the text itself is ok: I can select all, copy it to another editor and there it looks fine. When I close UnrealEd's code window and reopen it, the text looks ok then.
![UnrealEd-CodeDisplayCorrect](https://user-images.githubusercontent.com/81397053/148620195-6464468f-6158-4fce-9b3f-7056818c5f1a.jpg)
![UnrealEd-CodeDisplayBroken](https://user-images.githubusercontent.com/81397053/148620198-6dda1a02-9bfb-431b-bdc5-4f117578f43d.jpg)

**Comment by SeriousBuggie** [comment]
Need way for reproduce. And sshot where bugged text visible from start class. And same class from start without bug, for comparison.

What about v469b? Such happen?

**Comment by SeriousBarbie** [comment]
Both screen shots show complete content from editor window.
When I know a way to reproduce I'll tell.

**Comment by SeriousBuggie** [comment]
Second look like scrolled down. It is not?

**Comment by Engineer9736** [comment]
I just found a solid way to reproduce it.

1. Close the class if you have it open
2. Minimize the code editor
3. Right click the actor in the level and click Edit Script

Perhaps there are shorter/other ways to reproduce it, but this is at least one of them.

https://user-images.githubusercontent.com/22099136/150638736-c43c7893-3705-46e2-abfd-b589b24ea0c6.mp4

**Comment by SeriousBuggie** [comment]
Not able reproduce it. What build you use? What windows version?

**Comment by Engineer9736** [comment]
It's UnrealEd 2.2 on Windows 10.

Here i have an even shorter reproduction procedure, from startup of UnrealEd on:
1. Start Unrealed 2.2
2. Go to actor browser
4. Double click Inventory to open it
5. Minimize the code editor
6. Double click Navigation Point to open it
7. Scrambled up

Note: This does not seem to happen if the class is in the top of the list.


https://user-images.githubusercontent.com/22099136/150642643-eb441595-f947-4389-9847-31f37f8b32b7.mp4

**Comment by SeriousBuggie** [comment]
I think it is Windows 10 component issue, because still not able reproduce it on Windows 7 even with v469b.

**Comment by Engineer9736** [comment]
I've tried launching UnrealEd with compatibility mode on Windows 7 on, but that doesn't take the bug away for me. But maybe the compatibility mode doesn't emulate Windows 7 that far.

Perhaps some other people can try reproducing the bug on different Windows versions.

**Comment by Engineer9736** [comment]
Apparently when this issue happens, the code editor is using the line lengths of the most upper script that happens to be open, on the script that's actually open.

https://user-images.githubusercontent.com/22099136/150651049-4d2be2ad-1dd8-41d4-be67-3cf5712bacda.mp4

**Comment by SeriousBarbie** [comment]
It was reproducible on Win 10x64 prof, Version 21H2. I also tried it in a VM with Win7x64 Enterprise, but could NOT reproduce it there.

**Comment by SeriousBuggie** [comment]
> Apparently when this issue happens, the code editor is using the line lengths of the most upper script that happens to be open, on the script that's actually open.

Wow. Great finding. Anyway we use Windows standard RichEdit component currently. So possible no any way fix it. Only some workarounds.

**Comment by Engineer9736** [comment]
Thank you!

Yes, i think it's no big issue, one double click on the class name and the issue is gone.

**Comment by SeriousBuggie** [comment]
Able reproduce in VM with win10. So this related to win10 Richedit implementation for sure. I will search way for fix that.
