### ISSUE TITLE
469 on Mac (Native): Missing Class in file Error

### ISSUE THREAD

**Issue by cHiPiRoN** [OldUnreal/UnrealTournamentPatches#706]
With patch 469 for Mac, connecting to a server for some maps results in Error `Can't find Class in file 'Class Editor.TransBuffer'`. 

Tested with a fresh install of UT99, 469, e.g. on the map 'Ancient Antalius' on server barbiesmonsterhunt.

**Comment by SeriousBuggie** [comment]
Check of `Editor.u` CRC32. It must be 473EB747 if you use v469b patch.

**Comment by cHiPiRoN** [comment]
CRC32 was wrong, my bad. Sorry and thanks, now 469b is working perfectly for me!
