### ISSUE TITLE
[469b] Not able enter to network server after start Listen server

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#708]
Reproduce:
1. Start UT.
2. Start Listen server: new multiplayer game - start.
3. Try connect to any server.

Expected result: Connect to desired server.
Actual result: Can be some.
1. Crash:
```
Assertion failed: !Pending [File:C:\GameDev\UnrealTournament\Engine\Src\UnGame.cpp] [Line: 1330]

History: CancelPendingForListen <- Listen <- UGameEngine::LoadMap <- AttemptLoadPending <- 
TickPending <- UGameEngine::Tick <- UpdateWorld <- MainLoop
```
2. nothing with some records on the log appeared once:
```
Log: Browse: 176.9.104.176:2310/Index.unr?Game=Botpack.DeathMatchPlus?Mutator=MapVoteUpdater.MapVoteUpdater,MapVoteULv1_2.BDBMapVote?Listen?Checksum=NoChecksum?Name=   ?Class=MultiMesh.TCow?team=255?skin=tcowmeshskinscc.Gree?Face=?Voice=MultiMesh.CowVoice?OverrideClass=Botpack.CHSpectator
Init: WinSock: Socket queue 32768 / 32768
DevNet: Game client on port 0, rate 20000
DevNet: PendingLevel received: CHALLENGE VER=469 CHALLENGE=1858790068 STATS=0
DevNet: Control channel bunch overflowed - tried sending LOGIN RESPONSE=-526836576 URL=:2310/Index.unr?Game=Botpack.DeathMatchPlus?Mutator=MapVoteUpdater.MapVoteUpdater,MapVoteULv1_2.BDBMapVote?Listen?Checksum=NoChecksum?Name=   ?Class=MultiMesh.TCow?team=255?skin=tcowmeshskinscc.Gree?Face=?Voice=MultiMesh.CowVoice?OverrideClass=Botpack.CHSpectator
```
3. nothing with endless flood in the log about need password:
```
Log: Browse: SERVER_IP_WITH_PASSWORD:PORT/Index.unr?Mutator=MapVoteUpdater.MapVoteUpdater,MapVoteULv1_2.BDBMapVote?Listen?Checksum=NoChecksum?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator?password=PASSWORD
Init: WinSock: Socket queue 32768 / 32768
DevNet: Game client on port 0, rate 25000
DevNet: PendingLevel received: CHALLENGE VER=469 CHALLENGE=-491762564 STATS=0
DevNet: PendingLevel received: FAILURE You need to enter a password to join this game.
DevNet: PendingLevel received: FAILCODE NEEDPW
Log: Pending connect to "SERVER_IP_WITH_PASSWORD:PORT/Index.unr?Mutator=MapVoteUpdater.MapVoteUpdater,MapVoteULv1_2.BDBMapVote?Listen?Checksum=NoChecksum?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator?password=PASSWORD" failed; Rejected by server
NetComeGo: Close TcpipConnection31 01/11/22 22:50:48
Exit: WinSock shut down
Log: Browse: SERVER_IP_WITH_PASSWORD:PORT/Index.unr?Mutator=MapVoteUpdater.MapVoteUpdater,MapVoteULv1_2.BDBMapVote?Listen?Checksum=NoChecksum?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator?password=PASSWORD
Init: WinSock: Socket queue 32768 / 32768
DevNet: Game client on port 0, rate 25000
DevNet: PendingLevel received: CHALLENGE VER=469 CHALLENGE=-28121680 STATS=0
DevNet: PendingLevel received: FAILURE You need to enter a password to join this game.
DevNet: PendingLevel received: FAILCODE NEEDPW
Log: Pending connect to "SERVER_IP_WITH_PASSWORD:PORT/Index.unr?Mutator=MapVoteUpdater.MapVoteUpdater,MapVoteULv1_2.BDBMapVote?Listen?Checksum=NoChecksum?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator?password=PASSWORD" failed; Rejected by server
NetComeGo: Close TcpipConnection32 01/11/22 22:50:48
Exit: WinSock shut down
```
This non stop flood in log.

v436 affected too (crash).
Reproduce on v469b, v469c.

If you disconnect from Listen before connect to new server - it is not help.

Also if you need download some packages - you download it and after that crash.

**Comment by SeriousBuggie** [comment]
As I see simple `open IP:PORT` command reuse current options for URL, so later when try load map:
`URL.HasOption(TEXT("Listen"))` return true because there actually such param.
Which lead to problems (crash).
Possible other options too not exactly same as for usual enter to server.

Here I start DM-Deck16][ Listen:
`ScriptLog: InitGame: ?Game=Botpack.DeathMatchPlus?Mutator=?Listen?Checksum=NoChecksum?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator`

Here I try after that connect to Barbie server: `open 81.169.240.101` and get crash
`81.169.240.101/MH-Sk_Godz?Mutator=?Listen?Checksum=NoChecksum?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator`

Here I try enter to Barbie server from clean run UT:
`81.169.240.101/MH-(dU)AS-ImperialBaseFinal?Name=Buggie?Class=BotPack.TFemale1?team=255?skin=FCommandoSkins_NeoCop.copi?Face=FCommandoSkins_NeoCop.Ashley?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator?UEFID=SOME_HEX_NUMBER`

As easy see there different url when enter on clean run.

**Comment by CacoFFF** [comment]
FURL::RemoveOption added to the API, any attempt to connect to a remote URL will now remove the ?Listen option from the pending level.

**Comment by stijn-volckaert** [comment]
The fix is included in RC3
