### ISSUE TITLE
[469b] Map list limited to 32 entries

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#709]
Reproduce:
1. Start UT.
2. Open `Start Practice Session` Dialog.
![img](https://user-images.githubusercontent.com/70026933/149125941-59b614eb-9c27-44a0-a345-b23f197b5741.png)
3. Push button `Map List`
![img](https://user-images.githubusercontent.com/70026933/149125988-72f46a98-dcf2-42f6-8107-53a1cb68c9a1.png)
4. Make double click on left list until not fill right list with more than 32 items.
![img](https://user-images.githubusercontent.com/70026933/149126274-935b06c7-6f50-4721-b94a-e441c756fc08.png)
5. Press `Close`
6. Open `Map List` again

Expected result: List items preserved.
Actual result: Only first 32 items preserved.
![img](https://user-images.githubusercontent.com/70026933/149126518-51023a2e-6571-498c-9286-123f17ea773e.png)

Reason: 
```
class MapList extends Info;

var(Maps) config string Maps[32];
```

**Comment by Engineer9736** [comment]
I guess this bug will always persist in some way, as it's afaik impossible to make variable length arrays. The size could be increased to 1024 or so but then if you add 2000 maps the same issue will happen again 🙂

But a little bit larger than 32 would be better indeed.

Nice job on finding this! Perfectionizing UT99 😅

**Comment by SeriousBuggie** [comment]
`ServerPackages` and `ServerActors` is variable length arrays. So exists 2 solution:

1. Easy - make some bug number like 4096 for maps count.
 
2. Hard - make on native side variable length array.
