### ISSUE TITLE
[469a][UEd] Decals should be visible in the editor

### ISSUE THREAD

**Issue by FrancescoBis** [OldUnreal/UnrealTournamentPatches#71]
Decal projections are not visible in the editor, this makes positioning decals puzzling.

Patch: 451
Renderer: Software Renderer
UnrealEd Version: 2.1 (unofficial)

To reproduce the issue add a decal in editor and try to project a texture on a BSP.

**Comment by Dr-Flay** [comment]
Can you please install the patch from this project "v469" and report current bugs if they still exist ?

NOTE: UEd in v451 is broken and not to be used.
v451 is recommended for server hosts, not for players and mappers
Also if you use software rendering in any version of UEd, any large or compressed textures will not display correctly in the texture browser.

**Comment by racing-online** [comment]
v451 also has broken compiler. So it isn't recommended not for mapping nor for building any packages at all. Looks like it shouldn't be used for anything other than a dedicated server.

**Comment by FrancescoBis** [comment]
Yes, I can try using 469. I said I was using 451 because UnrealEd 2.1 is a standalone version based on 451, although I play UT on 436.

**Comment by Chamberly** [comment]
I'm trying to take a look at this and I'm confused here. I tried most of the decals and then toggled through different renders but I did not see any of those show up on floor and the wall.

I also looked in 436, I didn't see anything on that either. I looked in the game as well and they are not there. So the idea here is that I may not have an idea what is suppose to be going on here but hey Fran tell me what decal you was using so I can make sure I'm checking correctly. Are you using the Decal actors?

**Comment by FrancescoBis** [comment]
It still doesn't work using D3D11, to replicate it try this:
1. Run the game;
2. Play DM-Fetid;
3. Shoot on the walls;
You'll see that the bullets holes (decals) won't be visible.

**Comment by stijn-volckaert** [comment]
Decals never worked with SoftDrv. Adding decal support would require a substantial engineering effort. Given the relatively modest benefits, the complexity of SoftDrv in general, and the fact that we're trying to phase SoftDrv out, we decided not to fix this issue.
