### ISSUE TITLE
[469b] 2D Shape Editor add XYZ orientation when placing brush

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#711]
2D Shape editor is lacking a functionality, which will allow you to place the 2D Shape brush in a XYZ orientation. Currently, you have no option to change the orientation when placing the brush:

![Screenshot_1871](https://user-images.githubusercontent.com/58362332/149167380-ff154203-80b7-478a-aaba-9b860fbdb8b7.png)
![Screenshot_1872](https://user-images.githubusercontent.com/58362332/149167375-c226d506-948f-4c6e-895e-631049650749.png)
[2Dshape.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7855605/2Dshape.zip)

**Comment by SeriousBuggie** [comment]
As current workaround - rotate brush after.
In general it can be done as in 2k4 editor:
![img](https://user-images.githubusercontent.com/70026933/183269530-ea9af4c1-443e-4289-b003-f2711ee5d679.png)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/216570230-b191464e-b5e2-4826-9e39-d658bbee931a.png)

**Comment by BerserkerBG** [comment]
> Possible implementation: ![img](https://user-images.githubusercontent.com/70026933/216570230-b191464e-b5e2-4826-9e39-d658bbee931a.png)

Small change request. XY button places arches upside down:

![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/49208623-6710-44a8-bf25-7fd42e1512f9)

Can we make XY button place the brush like this instead:

![Screenshot_19](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/35a2fc3e-fd43-4731-af61-3aa802de6bb5)

XY will be mainly used for arches anyway, this change would be very convenient, otherwise you are forced to mirror the brush on Z axis after you place it with the 2D shape editor.
