### ISSUE TITLE
[469b] UnrealEd code editor, add tab / shift-tab for indentation adjustment

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#715]
Almost any modern programming IDE these days supports tab/shift tab to move the code indentation to the right and left. UnrealEd just replaces the selected code for the actual tab. It would be nice if this feature could be added.
![Untitled](https://user-images.githubusercontent.com/22099136/149636541-a6750bbf-92b1-464b-a9cc-75ad0d95fd3d.png)

**Comment by SeriousBuggie** [comment]
Already implemented in v469c.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
