### ISSUE TITLE
[469b] UnrealEd code editor, add Ctrl+F shortcut

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#716]
Ctrl+F in de code editor of UnrealEd does nothing currently. This shortcut is so standard in any text editor for decades already, even in Windows's Notepad, that i don't even look if the search screen appeared already and i just start typing my search term. Resulting in typing in the code that happened to be open. I guess it would be a very easy fix to make Ctrl+F work.

Perhaps also Ctrl+R for search-and-replace and mass-replace could be added, although that would require new functionality in UnrealEd.

**Comment by SeriousBuggie** [comment]
`Ctrl+F` - already implemented in v469c.

**Comment by Engineer9736** [comment]
Oh that's nice 👍

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
