### ISSUE TITLE
[469b] Add all video settings to video settings menu

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#726]
For a lot of video settings you have to go through the UnrealTournament.ini manually, while i think the ingame menu should be the way to configure all these things.

For my exact case i wanted to turn Coronas off as they block my entire view. But i guess just all of these settings can go into the settings menu. Optionally with some more human readable explanations for each item.

![Untitled](https://user-images.githubusercontent.com/22099136/151416293-47eea99d-00ff-4b36-8cfd-547eabb21af2.png)

The specific video settings window class is this one:

Object.UWindowBase.UWindowWindow.UWindowClientWindow.UWindowDialogClientWindow.UWindowPageWindow.UMenuPageWindow.UMenuVideoClientWindow
![Untitled](https://user-images.githubusercontent.com/22099136/151602263-de2500d5-be0d-4e93-b8a7-60672a00c7c5.png)

**Comment by alsosed** [comment]
I think it's enough to add a "preferences" button

**Comment by stijn-volckaert** [comment]
Have you tried the "preferences" console command?

**Comment by Engineer9736** [comment]
It does give a lot of the driver settings to configure indeed, and ingame which is good, but:

- The coronas setting is not in there
- It's still quite a hidden and technical solution which the average user probably never thinks about

I'm able to manage to adjust the setting via the ini fine, but my intention was more to make it easy accessible for the regular user. This by adding GUI controls to the menu.

I see that each driver has it's own variables so maybe it's difficult to add this to the video settings screen. Alternatively a button could be added in the video settings screen which executes the "preferences" console command?

![Untitled](https://user-images.githubusercontent.com/22099136/154034766-f85f8ec0-3f23-490f-a2bb-adc809379567.png)

![Untitled](https://user-images.githubusercontent.com/22099136/154033168-9b9c9ff9-72b6-4013-ba62-7d83890475e9.png)

**Comment by SeriousBuggie** [comment]
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/461ce9fe-773f-4d02-b000-79002546ab5c)
Implemented in v469d.
