### ISSUE TITLE
[469b] OSX 10.14, patch does not work at all, Assertion Failed Get Properties,etc

### ISSUE THREAD

**Issue by cash68** [OldUnreal/UnrealTournamentPatches#727]
![image](https://user-images.githubusercontent.com/98610048/151595113-064b18ab-3575-4c8b-ad0a-007bc351841e.png)

**Comment by stijn-volckaert** [comment]
This happens when the game uses .u files that do not match their native C++ counterparts. Did you accidentally copy the .u files from UT432/436 to your Application Support folder?

There's some additional info in #63
