### ISSUE TITLE
[469b] High velocity kickers causing heavy screen shakes

### ISSUE THREAD

**Issue by Melle4x** [OldUnreal/UnrealTournamentPatches#728]
Hi guys,

Kickers with high KickVelocity are causing heavy screen shakes on 469b and 469c clients.
This behavior is not experienced on 436 clients.

Please see the following clip by Soupy, explaining the issue: https://clips.twitch.tv/BoldHumbleMushroomOSfrog-bmNjELdp4X70rzgi

**Comment by CynicusRex** [comment]
This happens when entering quickly exiting slime volumes as well. At least on some maps such as CTF-BT-(BK)Sewearth-v3b.
