### ISSUE TITLE
[469a] Very slow UED 2.2

### ISSUE THREAD

**Issue by WhiteyAU** [OldUnreal/UnrealTournamentPatches#73]
Since downloading 469a. I've noticed a huge slow down in process when rebuilding all in the editor.

Most specifically when it comes to "Illuminating Occlusion" It went from taking 30 seconds to over 5 minutes on maps that aren't very BSP intense.

Even when i started a map from scratch this section of the Rebuild still takes a long time compared to before 469.

**Comment by stijn-volckaert** [comment]
Do you have a specific test case?

**Comment by stijn-volckaert** [comment]
Closing because the ticket seems inactive
