### ISSUE TITLE
[469b] Game crash (General Protection Fault) when invoking GetNextIntDesc with obscure class string

### ISSUE THREAD

**Issue by 1337GameDev** [OldUnreal/UnrealTournamentPatches#730]
I was writing some code to search for all weapons at runtime (once at prebegin play), and encountered an odd issue.

The relevant function is:

`Actor.uc: native final function GetNextIntDesc( string ClassName, int Num, out string Entry, out string Description );`

If you enter an unknown class for the ClassName parameter, and 0 for Num, the game crashes (instead of just returning "" for Entry+Description) as expected. 

A reproducible case is this (when trying to look at Wormbo's mod for Enhanced Weapons): 

```
class TestActor1 extends Actor {

function PreBeginPlay() {
    local string WeaponClass, WeaponClassDescr;
    local class<Weapon> LoadedClass;
    local int WeaponNum;

    Log("Before call");

    //uncomment the below line to prevent the crash
    //LoadedClass = Class<Weapon>(DynamicLoadObject("EnhancedItems.EnhancedWeapon" , class'Class'));
    WeaponNum = 0;
    self.GetNextIntDesc("EnhancedItems.EnhancedWeapon",WeaponNum,WeaponClass,WeaponClassDescr);
    Log("After call");
}

}
```

The resulting crash is just: 
`General Protection Fault`

This happens on map load with the actor running the code, and happens as well if you substitute in "ObscurePkg.ObscureClass" in for the ClassName parameter too. 

In the above, if you uncomment the dynamicload then the crash is avoided, and it loads fine, but is odd behavior.
I would assume that if no matching class is found, it'll return "" for the resulting strings.

Can a fix be applied to avoid this crash and return "" instead? (code using this method will check for empty string anyways in a loop, with a max number index) like the following: 

   ```
 while((WeaponClass != "") && (WeaponNum < 255)) {
        //do something with loaded info
        WeaponNum++;
        self.GetNextIntDesc("EnhancedItems.EnhancedWeapon",WeaponNum,WeaponClass,WeaponClassDescr);
    }
```

Any code that doesn't, and the crash happens, will just not work anyways, so the use case is not a big issue changing this functionality imho.

Thoughts?

Technically this can be avoiding by doing a dynbamicload before invoking the method with the class string, but that is not ideal.

**Comment by stijn-volckaert** [comment]
Thanks for the report. Two things went wrong here:
* Failures to resolve the class you pass as the first argument to GetNextIntDesc were fatal. I've pushed a change that will make these failures non-fatal in v469c.
* Certain types of errors were not being logged by UCC. I've pushed a fix that enables logging for these errors.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
