### ISSUE TITLE
[469b] On exit from UT witn D3D9 all windows redraw

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#731]
Reproduce:
1. Start UT with D3D9.
2. Exit from UT.

Expected result: no total redraw for all screens.
Actual result: after each exit start total redraw of all screens, which awful slow.

**Comment by SeriousBuggie** [comment]
XOpenGL - same story, but worse: total redraw happen even on start UT.
On D3D9 start is not redraw second monitor.

**Comment by stijn-volckaert** [comment]
This is probably a Windows feature

**Comment by SeriousBuggie** [comment]
Workaround - go to windowed mode before exit (Alt+Enter).

**Comment by an-eternity** [comment]
I can't reproduce this issue with slow total redraw after exit. Does this happen with Nvidia only?
There was an issue with AMD where driver sometimes stops responding on start or on exit (with XOpenGL even more often than with D3D9), but it was with old drivers and with old v469c builds, with latest v469c build and latest stable AMD driver i can't reproduce this too.

**Comment by SeriousBuggie** [comment]
Can't really say. Possible this even related to specific nvidia drivers. So possible it can be optional feature. Anyway  I not see harm  from it.
