### ISSUE TITLE
[469b] UnrealEd: For surafce edit flags, need add all possible flags

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#735]
https://wiki.beyondunreal.com/Legacy:PolyFlags
Currently you can not set/unset some flags via dialog. For example  `PF_NotSolid` or `PF_Semisolid`.

Obviously you can copy brush, edit flags in it and paste back, but it is very messy way for do that.

Be very good if in current list appear all possible flags, for not need do copy/paste hack.

**Comment by SeriousBarbie** [comment]
I always use Actor Properties > Brush > PolyFlags when I want to change that. Mostly I do that for changing solid -> semisolid. In seldom cases I have to split an existing PolyFlag number like 1234567890 into its different flags - yes, checkboxes for that would it make easier. 
![PolyFlags](https://user-images.githubusercontent.com/81397053/153847572-252b7ff6-17e9-4833-96cc-27a8edcbe35a.jpg)

**Comment by SeriousBuggie** [comment]
I talk about flags for polygon itself, not entire brush.
I faced weird brushes, which semisolid and disappear if changed to solid.
This happen because one poly use flag semisolid in it. So if brush solid, one edge is nonsolid and volume not closed.

**Comment by SeriousBuggie** [comment]
Example of possible usage for change solidity for windows on map AS-RTrain:
![img](https://user-images.githubusercontent.com/70026933/163653374-d9554163-5b38-4f7f-9209-8f169f41b631.png)
