### ISSUE TITLE
[469b] Make the commands killall and set produce feedback

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#737]
For example during monsterhunt, some maps go crazy with creaturefactories, so i run killall creaturefactory (not a good choice to solve that specific issue, but that aside).

The command doesn't say anything back so it's not right away clear if anything happened.

It would be nice if it said something like:
```

> killall creaturefactory
Killed 325x CreatureFactory.
```

Same for the set command. If the set command was successful then it doesn't say anything. It would be nice if it confirmed what it has done. Like:

```
> set deathmatchplus fraglimit 999
DeathMatchPlus.FragLimit has been set to 999.
```

If the user types a variable wrong, then it does give an error already, but only in the console, not in the chat. It would be nice if it also showed the error in the chat without having to open the console.

![Untitled](https://user-images.githubusercontent.com/22099136/154108372-baa89f17-69fc-4564-b041-9eb783d5512b.png)

**Comment by SeriousBarbie** [comment]
I didn't find a way to send a PM, so I ask here: in what MH maps did such happen?

**Comment by Engineer9736** [comment]
> I didn't find a way to send a PM, so I ask here: in what MH maps did such happen?

MH-PoL1-Frigid is a good example. Endless pupea's in the beginning and at some point there is a zigzagging ice bridge where you don't get a chance to get across it without cheating.

And at the beginning of MH-Canals][ it keeps spawning Kralls, which gets a bit pointless, though it's a pretty map.

It's better to admin set the spawncount to 2 or something instead of killing the creaturefactory completely. Though i think some levels work with counters to open doors and such, so it would need some unrealscript to properly adjust those spawncounts (Creaturefactory + counter).

![Shot00032](https://user-images.githubusercontent.com/22099136/154436439-92bd2ce4-a16c-4512-a1a8-98d9ca9b873b.png)

**Comment by SeriousBuggie** [comment]
I split issue because `KillAll` is unreal script stuff, but `set` is engine command.
So fix first simple close this issue, and second can be lost.
