### ISSUE TITLE
Hello OldUnreal

### ISSUE THREAD

**Issue by madrina4** [OldUnreal/UnrealTournamentPatches#744]
This patch is compatible with TacticalOps 3.4.0 and 3.5.0 ?

**Comment by stijn-volckaert** [comment]
Even though we do not and cannot officially support TO, the patch is partially compatible. You should be able to use 469b with TO's versions of Botpack.u and UTMenu.u. I'm going to close this issue, but feel free to join our Discord server if you want to talk to other people who use 469 in TO
