### ISSUE TITLE
[469a] unrealed flush mylevel

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#75]
unrealed could flush mylevel when you open a new level. If you happen to open many levels with content in mylevel, you start to include content in later levels that belong to other levels.

**Comment by SeriousBuggie** [comment]
It must be optional or ask user about that, because this often used for move things between maps.
And as I know, unused items from MyLevel vanished on save.

**Comment by stijn-volckaert** [comment]
I'm reviewing some old tickets and saw that this one is still open. We've (mostly) addressed this in 469b and 469c. Several editor commands now flush the internal caches and unload unnecessary resources. Feel free to comment/reopen if you have concrete use cases where we're not flushing properly.
