### ISSUE TITLE
[469b] UT not switch audio output device if it changed

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#751]
Reproduce:
1. Start game.
2. Connect bluetooth headphones.

Expected result: Sound now use another device and properly played at headphones.
Actual result: Sound not redirected to headphones.

Tested OpenAL.

UT2004 able fine deal with change audio devices.

**Comment by stijn-volckaert** [comment]
Have you tried setting your playback device to system default?

**Comment by SeriousBuggie** [comment]
It is already set to `System default`.
In fact if I change Audio device UT goes to total lags so better restart it.

**Comment by SeriousBuggie** [comment]
```
Warning: ALAudio: Musicbuffer error: Invalid Value
DevMusic: ALAudio: Unregister music: Music Godown.Godown
DevMusic: RegisterMusic Music Godown.Godown
```
Log entries if i change audio source (turn off BT headphones).
if I turn other BT headphones on (and this change default device again), no any messages in log.

Game very high lagged while device switched. After some time all stabilized, but no any sound/music in any output channel.

**Comment by SeriousBuggie** [comment]
look like related to kcat/openal-soft/issues/555

**Comment by SeriousBuggie** [comment]
Also I make few test and can note: if I use speakers and change output to headphones as new default device - sound still play in speakers.

Usual real case is opposite - headphones turn down, so device go off. Look like UT continue try output info in it.

**Comment by SeriousBuggie** [comment]
After I use 'ALSOFT_LOGLEVEL=3`:
```
[ALSOFT] (II) Created context 03389830
// last ok message. all below goes after device switch
[ALSOFT] (EE) WaitForSingleObjectEx error: 0x102
[ALSOFT] (EE) Failed to get padding: 0x88890004
[ALSOFT] (WW) Error generated on context 03389830, code 0xa001, "Invalid source ID 2"
[ALSOFT] (WW) Error generated on context 03389830, code 0xa001, "Invalid source ID 2"
```

**Comment by SeriousBuggie** [comment]
Another useful issue: kcat/openal-soft/issues/533

**Comment by SeriousBuggie** [comment]
Possible need update headers of OpenAL soft + start use latest binary:
> OpenAL Soft 1.22.0 is now available!
> The changes from 1.21.1 include:
>
>    Implemented the [ALC_SOFT_reopen_device](https://openal-soft.org/openal-extensions/SOFT_reopen_device.txt) extension.
>    This allows for moving devices to different outputs without losing object state.
