### ISSUE TITLE
[469b] Load any package with ripped (strip) sources completely break compiling scripts in UnrealEd until restart

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#753]
Reproduce:
1. Load any package with ripped (strip) source. XConsole for example.
2. Press `compile changed scripts`.

Expected result: Message about "Everything id up to date".
Actual result: UnrealEd want compile every class without sources.
No any way unload package or avoid compiling empty sources.

In fact, classes with ripped source must be ignored for recompile, until this classes not need explicit for compile something.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
