### ISSUE TITLE
[469b] Make the commands set produce feedback

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#755]
> The command doesn't say anything back so it's not right away clear if anything happened.
> 
> It would be nice if it said something like:
> 
> ```
> 
> > set deathmatchplus fraglimit 999
> DeathMatchPlus.FragLimit has been set to 999.
> ```
> 
> If the set command was successful then it doesn't say anything. It would be nice if it confirmed what it has done. 
> 
> If the user types a variable wrong, then it does give an error already, but only in the console, not in the chat. It would be nice if it also showed the error in the chat without having to open the console.
> 
> ![Untitled](https://user-images.githubusercontent.com/22099136/154108372-baa89f17-69fc-4564-b041-9eb783d5512b.png)

_Originally posted by @Engineer9736 in https://github.com/OldUnreal/UnrealTournamentPatches/issues/737#issue-1138947950

**Comment by SeriousBarbie** [comment]
Duplicate to [#737](https://github.com/OldUnreal/UnrealTournamentPatches/issues/737)?

**Comment by SeriousBuggie** [comment]
Possible implementation:
```
> set ctfgame lightradius 42.3
Property Botpack.CTFGame.LightRadius modified to "42.3", final result is "42".
> set ctfgame lightradius WonderLand
Property Botpack.CTFGame.LightRadius modified to "WonderLand", final result is "42".
> set ctfgame lightradius 123456.769
Property Botpack.CTFGame.LightRadius modified to "123456.769", final result is "64".
> set ctfgame lightradius 255
Property Botpack.CTFGame.LightRadius modified to "255", final result is "255".
> set ctfgame lightradius 256
Property Botpack.CTFGame.LightRadius modified to "256", final result is "0".
> set ctfgame lightradius 45.68t68
Property Botpack.CTFGame.LightRadius modified to "45.68t68", final result is "45".
> set ctfgame Multiskins 1 RReticle
Property Botpack.CTFGame.MultiSkins[1] modified to "RReticle", final result is "Texture'Botpack.Icons.RReticle'".
> set ctfgame skin RReticle
Property Botpack.CTFGame.Skin modified to "RReticle", final result is "Texture'Botpack.Icons.RReticle'".
```
