### ISSUE TITLE
[469a][linux] version `GCC_7.0.0' not found

### ISSUE THREAD

**Issue by AntiSol** [OldUnreal/UnrealTournamentPatches#76]
Hi. Thanks for the patch, I've been looking forward to it, but unfortunately it's not working for me. 

I suspect the issue is that I'm running xubuntu 16.04 and that maybe you're unnecessarily targeting a very recent version of gcc?

````
$ ut
./ut-bin: /lib/i386-linux-gnu/libgcc_s.so.1: version `GCC_7.0.0' not found (required by ./libopenal.so.1)
./ut-bin: /usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./libopenal.so.1)
````

````
$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
````
If anything can be done about this that would be awesome. It'd be nice to be able to run this on a not-bleeding-edge distro.

If there's anything I can do to help / test, please let me know!

Thanks!

**Comment by stijn-volckaert** [comment]
Could you try to replace our libopenal.so.1 by Ubuntu's version of libopenal-soft?

**Comment by AntiSol** [comment]
That did the trick:

I did:
````
$ mv libopenal.so.1 libopenal.so.1.ut469
$  ln -s /usr/lib/x86_64-linux-gnu/libopenal.so.1.16.0 libopenal.so.1
````

Looks like it works OK now, except that it is ignoring settings stored in ~/.loki. I'll file a separate ticket about that.
