### ISSUE TITLE
[469c] Editing USER.INI leads to sections loss on next UT start

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#765]
If I manually edit a value in USER.INI, nearly all sections are lost after UT has started.

Steps to reproduce:
1) Take a text editor and edit a value in USER.INI, for example change the value of _Name_ in section _DefaultPlayer_.
2) Start UT.
Expected result: only name has changed.
Actual result: name is reset to Player, nearly all sections of USER.INI are gone

Client is v469c, UnrealTournament.exe has date stamp of 02 Jul 2021.
With v436 it works as expected.

Attached the new (broken) written USER.INI.
[User.ini.txt](https://github.com/OldUnreal/UnrealTournamentPatches/files/8310979/User.ini.txt)

**Comment by SeriousBuggie** [comment]
Be sure of encoding before/after edit and BOM presence.
Possible your edit make file not readable for UT. So BOM goes as name of first section. Which effectively mean no such section.

Need more info about file before edit, and after edit before load UT. I think HEX edit can tell you difference.

**Comment by SeriousBarbie** [comment]
Ah, thanks. I switched from UTF8 LE BOM to ANSI format and now it works as expected.
