### ISSUE TITLE
[469b] ucc.exe GPF while exporting scripts from Mutant.u

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#766]
I tried to export the scripts from package "Mutant.u":
```
D:\>D:\Programme\UT.469\System\UCC.exe batchexport "D:\Programme\UT.469\System\3rd\Mutant.u" class uc D:\Programme\UTStuff\Mutant.u
=======================================
ucc.exe: UnrealOS execution environment
Copyright 1999 Epic Games Inc
=======================================

Loading package D:\Programme\UT.469\System\3rd\Mutant.u...
Exported Class Mutant.MutantPlayer to D:\Programme\UTStuff\Mutant.u\MutantPlayer.uc
General protection fault!

History: UTextBufferExporterTXT::ExportText <- UExporter::ExportToOutputDevice <- UClassExporterUC::ExportText <- UExporter::ExportToOutputDevice <- UExporter::ExportToFile <- UBatchExportCommandlet::Main

Exiting due to error
```
UCC.EXE: 02 Jul 2021 11:35, 509440 bytes

With v436 it works fine.
(As I didn't find a download source for the map MH-VallesMarineris][.unr nor for the file Mutant.u, here is the compressed version on my UT server: [Mutant.u.uz](http://h2490700.stratoserver.net:46139/Mutant.u.uz).)

EDIT: Maybe related to [#423](https://github.com/OldUnreal/UnrealTournamentPatches/issues/423)

**Comment by SeriousBarbie** [comment]
As I noticed, v436 didn't export correct: most files contain only the defaultproperties section, for example MutantRocket2.uc:
```
defaultproperties {
     Skin=Texture'Mutant.jrocket4'
}

```
While UTPT shows some code:
![MutantRocket2 uc@UTPT](https://user-images.githubusercontent.com/81397053/159159675-cde0f4a0-6a76-4bcf-8d0d-3bcbec6fb7e2.jpg)

**Comment by SeriousBuggie** [comment]
UTPT you watch decompilation. Need watch TextBuffer which below on your image. UCC not produce decompilation. 
It write TextBuffer and append decoded defaultproperties.

Here decoded from uz [Mutant.u](https://github.com/OldUnreal/UnrealTournamentPatches/files/8311180/Mutant.zip)

MutantRocket2 TextBuffer is empty. So source stripped.

**Comment by SeriousBarbie** [comment]
I didn't take into account that source could have been stripped :-o Maybe an error message "text code was stripped and is not available any more" instead of a GPF would be more helpful.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
