### ISSUE TITLE
[469b] Brightness level not consistent over renders

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#772]
Currently Engine use same abstract level of Brightness for each renders.
It is totally not consistent.
SoftDrv 0.5:
![scr_1648134014](https://user-images.githubusercontent.com/70026933/159948066-277470a6-f707-44ba-97e8-a48aa136311c.png)
XOpenGL 0.5:
![scr_1648133996](https://user-images.githubusercontent.com/70026933/159948201-58ce6e61-d427-49b7-97d0-a194f60a4131.png)
SoftDrv 0.5:
![scr_1648133903](https://user-images.githubusercontent.com/70026933/159948079-5c43977f-0014-4997-a824-42f7ada59672.png)
XOpenGL 0.5:
![scr_1648133967](https://user-images.githubusercontent.com/70026933/159948206-47ef43b8-9a0b-4a73-9b9a-f652c531facd.png)
In D3D9 in game 0.5 is too dark.

So need ar adjust each render for make it on same level of Brightness, or make some render specific Brightness, or make render specific scale and/or offset for overall Brightness level.

**Comment by stijn-volckaert** [comment]
I don't think it is feasible to make the brightness level consistent across all renderers because they all use different APIs/mechanisms to apply brightness. D3D9 is probably too dark because it uses SetDeviceGammaRamp to apply brightness and gamma correction. This API doesn't work well on modern versions of Windows.

**Comment by an-eternity** [comment]
Compared D3D9 vs OGL, with default settings: first one has not only lower brightness than latter, but also lower saturation, in windowed mode brightness appears even much lower than in full screen.
