### ISSUE TITLE
[469b] Pawn without bCollideActors able Touch (and pickup) Inventory

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#773]
```
/* moveToward()
move Actor toward a point.  Returns 1 if Actor reached point
(Set Acceleration, let physics do actual move)
*/
int APawn::moveToward(const FVector &Dest)
{
```
```
	if ( MoveTarget && MoveTarget->IsA(AInventory::StaticClass()) 
		 && (Abs(Location.Z - MoveTarget->Location.Z) < CollisionHeight)
		 && (Square(Location.X - MoveTarget->Location.X) + Square(Location.Y - MoveTarget->Location.Y) < Square(CollisionRadius))
	   )
		 MoveTarget->eventTouch(this);
```
no any check for bCollideActors. just direct call `eventTouch`.

This bug lead to collect items by bots when they drive vehicles.

If need reproduce I can make simple cube map.

**Comment by NeonKnightOA** [comment]
For the record, UT2004 had a Vehicle Pickups mutator that allowed players in vehicles to get pickups. Can't remember if, in multi-passenger vehicles, all the passengers got the item or only one of them.

**Comment by SeriousBuggie** [comment]
This thing can affect many-many mods, where used bots in "ghost" mode. Not only vehicles.
