### ISSUE TITLE
[469b] UnrealEd on export package still use package name in default properties

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#778]
Reproduce:
1. Make class `Test` in package `Tmp` with field `var() class<Actor> cls;`;
2. Set default value of field to class self.
3. Export class.

Expected result: Class name exported without package, which allow easy rename package source.
Actual result: Class name exported with package name, which lead to problems if you not notice that. Or dependency from old package or silent turn to none.

OFC we talk only about same package. If link external,there must be package name.

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Export [Tmp.u](https://github.com/OldUnreal/UnrealTournamentPatches/files/10611332/Tmp.zip)

Expected result:
```unrealscript
defaultproperties
{
	cls=Class'Test'
	Cls2=(cls=Class'Test')
	Cls3(0)=(cls=Class'Test')
	Cls3(1)=(cls=Class'Test')
	Cls5=(Cls3=(cls=Class'Test'),Cls4[0]=(cls=Class'Test'),Cls4[1]=(cls=Class'Test'))
	Cls6(0)=(Cls3=(cls=Class'Test'),Cls4[0]=(cls=Class'Test'),Cls4[1]=(cls=Class'Test'))
	Cls6(1)=(Cls3=(cls=Class'Test'),Cls4[0]=(cls=Class'Test'),Cls4[1]=(cls=Class'Test'))
}
```
Actual result:
```unrealscript
defaultproperties
{
	cls=Class'Test'
	Cls2=(cls=Class'Tmp.Test')
	Cls3(0)=(cls=Class'Tmp.Test')
	Cls3(1)=(cls=Class'Tmp.Test')
	Cls5=(Cls3=(cls=Class'Tmp.Test'),Cls4[0]=(cls=Class'Tmp.Test'),Cls4[1]=(cls=Class'Tmp.Test'))
	Cls6(0)=(Cls3=(cls=Class'Tmp.Test'),Cls4[0]=(cls=Class'Tmp.Test'),Cls4[1]=(cls=Class'Tmp.Test'))
	Cls6(1)=(Cls3=(cls=Class'Tmp.Test'),Cls4[0]=(cls=Class'Tmp.Test'),Cls4[1]=(cls=Class'Tmp.Test'))
}
```

**Comment by stijn-volckaert** [comment]
fixed in the next build
