### ISSUE TITLE
[win][469a][server] Pickup sounds

### ISSUE THREAD

**Issue by alsosed** [OldUnreal/UnrealTournamentPatches#78]
Problem with pickup sounds. Pickup sounds from one player are heard where the other player should not hear them (in the distance, in another map room). I will give an example on the well-known DM-Agony map.
The first player stands here:
![1](https://user-images.githubusercontent.com/5718162/95014094-3ff1ed00-064d-11eb-871e-701dbd1a8762.png)
The second player picks up the vials here:
![2](https://user-images.githubusercontent.com/5718162/95014117-631c9c80-064d-11eb-9660-a1e1bb523769.png)
As a result, the first player hears the sounds of the second player picking up vials. 
I've tested on 436 and 469 windows clients. It's the same everywhere. Therefore, I think that the problem is in the server.

**Comment by gargul2** [comment]
I can swear I had similiar issue several days ago, but with Grapple Hook online, some glitch happened, and I heard some other players's Grapple Hook during long time, even they were too away to hear them.

**Comment by stijn-volckaert** [comment]
Are you using Galaxy audio by any chance?

**Comment by alsosed** [comment]
> 
> 
> Are you using Galaxy audio by any chance?

On client 469a I tested with Cluster3D Audio. On client 451a - Galaxy. It's the same everywhere. I think the problem is on the server side.
How I tested. I have installed a clean server without mods version 451. I tested it. It's okay. Then I updated to 469a. The result is in the topic.

**Comment by alsosed** [comment]
UPD. Tested on 469 client with OpenAL Audio. Everything is normal. So there is a problem with Cluster3D Audio, Cluster3D Audio Windows and Galaxy. Thus, 451 clients will have a problem with pickup sounds.

**Comment by stijn-volckaert** [comment]
This will be fixed in 469b
