### ISSUE TITLE
[469b] UnrealEd change mover position and some properties after select mover

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#783]
Reproduce:
1. Open in UnrealEd [MH-Chizra_LUCKY.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8456734/MH-Chizra_LUCKY.zip)
2. Click on empty place for select nothing.
3. Run `ACTOR SELECT OFCLASS CLASS=Engine.Mover` for select all mover.
4. Click on empty place for select nothing.

Expected result: map stay same as be on open.
![img](https://user-images.githubusercontent.com/70026933/162568395-e9fa0c0a-c551-4825-a20c-6f617ec7b865.png)
Actual result: some movers jumps to another location.
![img](https://user-images.githubusercontent.com/70026933/162568411-cf9afe93-ea2b-4a3b-8deb-6413dd20a89f.png)

Another way to reproduce:
1. Open in UnrealEd [MH-Chizra_LUCKY.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8456734/MH-Chizra_LUCKY.zip)
2. Search actor `Mover86`
![img](https://user-images.githubusercontent.com/70026933/162568485-16aea11d-3147-4545-a4fa-291e08824517.png)
3. Double click on found result.

Expected result: mover on old place.
Actual result: mover jump in new place (you need game mode or refresh viewport for see that)
![img](https://user-images.githubusercontent.com/70026933/162568533-8bc3fe4b-920f-4d7f-8050-b6b84f24e813.png)

**Comment by SeriousBuggie** [comment]
Another way for trigger same bug in worse way:
1. Open this map.
2. Press `Ctrl+A` for select actors.
3. Turns game mode for see changes immediately.
4. Start move cam via hold left mouse drag grid and release it.

Expected result: All stay on same place.
Actual result: On end each (!) drag some movers jump to right down on top view. So fast it goes off grid.

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/162572909-65acdb85-5957-4346-8335-8076f35c5cf4.png)
Changes affect BasePos, BaseRot, Location.

**Comment by SeriousBuggie** [comment]
v469c (preview), v469b, v436 affected as well.

**Comment by SeriousBarbie** [comment]
At least Mover86's crazy moving happens also in original Unreal map "Chizra.unr".

**Comment by SeriousBuggie** [comment]
This happen basically everywhere for any mover.

Here simplest test case:
!. Set in UnrealEd grid size to 256.
2. Open [mover_select_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/12842009/mover_select_bug.zip)
3. Select mover.
4. Start play map from editor.

Expected result: Cube rotate around one corner/ You can see this, if set grid to 1, before open and select.

https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/99f89037-12cb-458e-8294-07301fe78583

Actual result: cube rotate very different, because pivot moved away, after simple select mover:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/6c2f1c79-63f1-4bdc-a1c3-a95e18274fdb

**Comment by SeriousBuggie** [comment]
Fixed in 469d.
