### ISSUE TITLE
[469b] Package version mismatch

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#785]
Reproduce:
1. Place in System: [NWCoreVIII.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8466973/NWCoreVIII.zip)
2. Run ut and type in console `start 176.9.104.176:6000`

Expected result: Server open.
Actual result: Message about mismatch package NWCoreVIII. Which not listed anywhere. So v469b/c fixes must ommit this mismatch and use version from cache.
```
Log: LoadMap: 176.9.104.176:6000/MH-XV-LaserV0?Name=Buggie?Class=Botpack.TFemale1?team=0?skin=FCommandoSkins.cmdo?Face=FCommandoSkins.anna?Voice=BotPack.VoiceFemaleTwo?OverrideClass=Botpack.CHSpectator
DevMusic: ALAudio: Unregister music: Music utmenu23.utmenu23
Log: File NWCoreVIII.u with GUID 7D927E974BB983E3896D64B9B9B426D2 was already loaded but is incompatible with requested GUID 42E724474FC4B639F83BED85116265F1 - Attempting reload
Log: Package is not empty - reload failed
Warning: Failed to load "NWCoreVIII": Package "NWCoreVIII" version mismatch..
```

**Comment by an-eternity** [comment]
Isn't it the same as issue 178?

This problem existed in all UT99 versions always, for this reason players had to use additional client copy ('clean' one, with no any custom files installed) to avoid such issues in online.

**Comment by SeriousBuggie** [comment]
Look similar but not really same. But related. #178 mean not unloaded package prevent load proper from cache.
This mean load some dependency trigger load package, which loaded not from cache.
#178 about proper unload packages.
This about proper load stuff.
Maybe can be make fix which close both issues, IDK.

**Comment by an-eternity** [comment]
Understood.
Hope both issues might be fixed.
Though, the fact it is well known problem and still not fixed means that solution must be complicated...

Both issues can be bypassed (by client restart, and by using 'clean' client), so at least it is not critical, just adds some inconveniences...

**Comment by SeriousBuggie** [comment]
```js
function bool LoadMods()
{
	local int NumModClasses;
	local string NextModClass, NextModDesc;
	local int i;
	local UMenuModMenuList NewItem;
	local UMenuModMenuItem TempItem;

	GetPlayerOwner().GetNextIntDesc("UMenu.UMenuModMenuItem", 0, NextModClass, NextModDesc);

	if(NextModClass == "")
		return False;

	ModItems = New class'UMenuModMenuList';
	ModItems.SetupSentinel();

	while( (NextModClass != "") && (NumModClasses < 50) )
	{
		NewItem = UMenuModMenuList(ModItems.Append(class'UMenuModMenuList'));
		NewItem.MenuItemClassName = NextModClass;
		if(NextModDesc != "")
		{
			i = InStr(NextModDesc, ",");
			if(i==-1)
				NewItem.MenuCaption = NextModDesc;
			else
			{
				NewItem.MenuCaption = Left(NextModDesc, i);
				NewItem.MenuHelp= Mid(NextModDesc, i+1);
			}
		}
		else
		{
			TempItem = New class<UMenuModMenuItem>(DynamicLoadObject(NextModClass, class'Class'));
			TempItem.Setup();
			NewItem.MenuCaption = TempItem.MenuCaption;
			NewItem.MenuHelp = TempItem.MenuHelp;		
		}

		NumModClasses++;
		GetPlayerOwner().GetNextIntDesc("UMenu.UMenuModMenuItem", NumModClasses, NextModClass, NextModDesc);
	}
	
	return True;
}
```
Just because Description not set - loaded entire packge and prevent enter on any server with same package.

**Comment by an-eternity** [comment]
Yesterday noticed strange issue with *.unr file mismatch...
In client cache existed old map file 'MH-Trials.unr' with checksum 'DF1168E811D57ABFC000D8AEDD7AF1DF'.
On attempt to join to a server that was running a different version of this map, this new map with checksum '130257CE11D4F379C00090A838B3C5DF' has been downloaded and saved to cache, but the client anyway tried to load old map version. Even after client restart, it anyway was trying to load old map version on attempt to connect to a server. Only when old map version entry was removed from cache.ini, client was able to connect to the server.
Usually v469 work with no problems in such cases, even if cache contains a lot of different versions of the corresponding package name. What could be so special about this file?

Entries from cache.ini in the:
```DF1168E811D57ABFC000D8AEDD7AF1DF=MH-Trials.unr
130257CE11D4F379C00090A838B3C5DF=MH-Trials.unr```

(Both file versions from cache added in attachment in zip-archive)

[MH-Trials.uxx.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8956649/MH-Trials.uxx.zip)

**Comment by SeriousBuggie** [comment]
How you enter to server? `start ip:port`? If via browser, then it load preview of map and load any version from cache AFAIK.

**Comment by an-eternity** [comment]
Via GUI, from the tab Favorites or from the tabs where items are received from the Master Server.

**Comment by NeonKnightOA** [comment]
MH-Trials is a default Monster Hunt map. Be aware that Monster Hunt has been updated for quite some time lately, including the maps getting objectives (a new post-503 feature), which involved the maps being modified and thus causing mismatches in clients older than v469b.

**Comment by SeriousBuggie** [comment]
From GUI map loaded for show sshot. It stay in memory. It is issue: #178

**Comment by an-eternity** [comment]
Understood... So, to display map's picture it loads the first matching map from the cache list, regardless its version/checksum, and then it becomes usual problem - once object is loaded, another version of it can not be loaded unless previously loaded version is unloaded...

**Comment by stijn-volckaert** [comment]
Confirmed duplicate
