### ISSUE TITLE
[469b] Decals in fog appear wrong in OpenGLDrv.

### ISSUE THREAD

**Issue by Slipyx** [OldUnreal/UnrealTournamentPatches#786]
Not sure if related to #70 .

OpenGLDrv no fog:
![ut99regdec](https://user-images.githubusercontent.com/694193/163102626-f54fd844-ca17-43e2-bcb5-2b2d674900db.jpg)

OpenGLDrv with fog:
![ut99fogdec](https://user-images.githubusercontent.com/694193/163102685-3b032900-5962-4528-8ec5-76ab749a425e.jpg)

And in XOpenGLDrv they appear correct in fog:
![ut99fogdecxgl](https://user-images.githubusercontent.com/694193/163102736-b0475789-262a-45e5-84f1-d6f51b2dca40.jpg)

**Comment by stijn-volckaert** [comment]
This will most likely be fixed in 469c

**Comment by stijn-volckaert** [comment]
Should be fixed. Feel free to comment if it doesn't look right
