### ISSUE TITLE
[469b] All renderers apart from Direct3D 9 have mouse input lag

### ISSUE THREAD

**Issue by HalfWayLambda** [OldUnreal/UnrealTournamentPatches#795]
For some reason on my machine, all the renderers have quite a noticable mouse input lag, even with VSync disabled in the game's settings, and in Nvidia's control panel. The **Direct3D 9** is the only one that doesn't have this problem. I've also made sure that the **Mouse Input** setting is set to **Raw Input**, and i've tried **DirectInput** too but that didn't make a difference. And i've tested **XOpenGL** too, it suffers from the same problem. Even the outdated **Direct3D 7** renderer also does this. The frame rate limit is set to 0 on all the renderers i've tested.

I'm assuming this has something to do with how the renderers handle fullscreen mode? Using the night light mode in Windows 10 i've noticed that this night light effect (which decreases blue light) usually gets cancelled out when playing any fullscreen game. This is also true for UT99 under **Direct3D 9**. However, in all the other renderers the effect is still applied. So, do all the renderers except **Direct3D 9** run the game in some sort of borderless fullscreen mode? When I make the game run through a window by pressing the small button on the top-right in UT's menu, the input lag feels exactly the same as before (except for **Direct3D 9**, where the problem gets created only if you run it in a window).

Obviously this isn't a huge issue for me since I can just play in **Direct3D 9**, but I think it's worth mentioning regardless. I haven't seen anyone else have a similar problem, so I have no idea why something like this even happens. Finally (and obviously it wouldn't change anything), setting the compatibility mode to **Windows XP SP2** didn't do anything. Rather, it made some lag spikes even worse when opening menus.

If this changes anything, here's a couple of extra info for my machine:
**_OS_**: Windows 10, Version 2004, OS Build 19041.450
**_Graphics Card_**: GTX 1050 TI, driver version 511.79

**Comment by BerserkerBG** [comment]
I wouldn't recommend using xOpenGL if you prioritize high-performance and input. For that you need to stick with D3D9 and OpenGL (not X). Perhaps D3D11 could be good for you as well, but you will need a bit of ini tweaking to get rid of the re-shade crap and make it resemble D3D9 without input lag.

Could you try OpenGL (not X) with different settings?

[OpenGLDrv.OpenGLRenderDevice]
ShaderType=SHADER_ARB
ZRangeHack=True
NoAATiles=True
NumAASamples=4
UseAA=True
SceneNodeHack=True
UseShaderGamma=False
ShaderGammaCorrectHUD=False
FrameRateLimit=0
UseMultiDrawArrays=True
UseDrawGouraud469=True
ShaderAlphaHUD=True
UseSSE2=True
UseSSE=True
BufferTileQuads=True
SinglePassDetail=True
SinglePassFog=False
ColorizeDetailTextures=False
DetailMax=1
RefreshRate=0
MaxTMUnits=0
NoFiltering=False
MaxAnisotropy=16
Use16BitTextures=False
UseHDTextures=True
UseTrilinear=True
UsePrecache=True
UsePalette=True
UseSamplerObjects=False
OneXBlending=True
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=1.300000
LODBias=0.000000
DescFlags=1
Description=
DebugBits=-1
VolumetricLighting=False
ShinySurfaces=True
Coronas=False
HighDetailActors=True
DetailTextures=True
AlwaysMipmap=True
SwapInterval=0
UseLightmapAtlas=True
ShaderMasking=True

**Comment by Henrik4665** [comment]
The directx 7 input lag issue is due to how microsoft made DirectPlay on windows 10. They depreciated anything prior to dx9 basically, and made that weird DirectPlay layer. Look into dx8todx9 wrappers for anything below dx9. It's not the patch. v436 will exhibit the same issues with both your xgl and dx7 and 8 on windows 10

**Comment by HalfWayLambda** [comment]
I tried the OpenGL settings you provided, but unsurprisingly nothing changed. And I am using the updated versions of the renderers in the 469b patch. And Henrik that's really interesting, I don't have any mouse input lag on Half-Life, which was made in 1998 and does use OpenGL, so I don't know if it's an issue specific to Windows 10.
Anyway I also tested the custom **Direct3D 10** and **Direct3D 11** renderers. Surprisingly **Direct3D 11** does have the same mouse input lag, whereas **Direct3D 10** doesn't feel like it does. So basically only **Direct3D 9** & **10** are the ones that don't have this issue for me.

**Comment by CacoFFF** [comment]
Set SwapInterval=0 in OpenGLDrv

**Comment by stijn-volckaert** [comment]
Input latency in OpenGL games is slightly higher than in D3D games on Windows 10, but the difference should be too small to notice.
Would you mind testing https://www.capframex.com/ with the RTSS Overlay to measure the latency difference on your machine?

**Comment by Henrik4665** [comment]
Apart from directx 7 and 8, it shouldnt be win10 specific. From my experience there might be a general openGL issue on win10. With a TN panel, im still having some delay issues with opengl in original versions of UT, half-life 2 and quake 3, that might be win10 specific. Dx10, 11 and vulkan always had input lag issues in UT for me. Even on win7 with dx11 hardware. Dx9 in UT has a problem with non-linearity or smoothing. OpenGL and dx8 are the only renderers that works flawless on win7 v436 for me. It's generally a hot mess, with "raw input", drivers, windows versions, hardware etc since multi core, desktop composition, CPU speeds and timings regarding games made for win9x and fixed speed CPUs and dx7-9 hardware

**Comment by stijn-volckaert** [comment]
Problem confirmed. A bug in the Windrv code dating back to at least v432 broke exclusive fullscreen support for non-d3d renderers.

**Comment by stijn-volckaert** [comment]
[WinDrv-469c-Hotfix.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9945669/WinDrv-469c-Hotfix.zip)

This should fix the problem
