### ISSUE TITLE
[469b] Mac Server, cannot access Web Admin service

### ISSUE THREAD

**Issue by dotHTM** [OldUnreal/UnrealTournamentPatches#798]
I have tested the same configuration in my local network on a Mac Mini (2014) using both the Windows and Mac versions, with an identical config. The Windows server lets me log in and the web server is available on the configured port: I can change mods, game mode, and the current map.

The Mac version however, allows me to enter the log in, but then the browser complains the connection was dropped/reset. I have tested with both Safari and Firefox.

FYI, The Windows test that works is within a Crossover bottle (aka WINE) so is technically running under the Mac OS. As a workaround, running the server this way seems to make the machine lock up after some time (I know it's very old), so I can't leave it unattended for long otherwise it needs a physical hard reboot the next day.

**Comment by stijn-volckaert** [comment]
This should be fixed in 469c. Feel free to comment/reopen if it still doesn't work
