### ISSUE TITLE
[469a] UnrealEd 2.2 - When closing the editor, "cancel" does the same thing as "no"

### ISSUE THREAD

**Issue by cybernaut4** [OldUnreal/UnrealTournamentPatches#8]
![Screenshot_4](https://user-images.githubusercontent.com/68290346/94012632-6f684600-fd7f-11ea-9d3a-b9604319ad3d.jpg)

It's supposed to prevent the program from closing, but it does the same thing as "No" (the editor closes anyway).

**Comment by Arkl1te** [comment]
Furthermore, UnrealEd closes the map before this very prompt.

**Comment by SeriousBuggie** [comment]
Fixed in v469b. Confirmed.
