### ISSUE TITLE
[469a] ExplosionChain can be blowed up before trigger by another ExplosionChain

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#80]
Look at this code:
https://github.com/Slipyx/UT99/blob/a26a3359704873df5a24d0b241a32ca5fc36a8b7/UnrealShare/ExplosionChain.uc#L25
```
singular function TakeDamage( int NDamage, Pawn instigatedBy, Vector hitlocation, 
						Vector momentum, name damageType)
{
	if (bOnlyTriggerable && DamageType!='Detonated') Return;
	
	Instigator = InstigatedBy;
	MakeNoise(1.0);
	GoToState('Exploding');
}

function Trigger( actor Other, pawn EventInstigator )
{
	TakeDamage(10, EventInstigator, Location, Vector(Rotation), 'Detonated');
}

//////////////////////////////////////////////////////////////
state Exploding
{
	ignores TakeDamage;

	function Timer()
	{
		local SpriteBallExplosion f;
		
		bExploding = true;
 		HurtRadius(damage, Damage+100, 'Detonated', MomentumTransfer, Location);
 		f = spawn(class'SpriteBallExplosion',,,Location + vect(0,0,1)*16,rot(16384,0,0)); 
 		f.DrawScale = (Damage/100+0.4+FRand()*0.5)*Size;
		Destroy();
	}
```
If bOnlyTriggerable is True, then only 'Detonated' damage type take in account.
Now look down to line:
https://github.com/Slipyx/UT99/blob/a26a3359704873df5a24d0b241a32ca5fc36a8b7/UnrealShare/ExplosionChain.uc#L47
```
 		HurtRadius(damage, Damage+100, 'Detonated', MomentumTransfer, Location);
```
If something spawn near another ExplosionChain, blow up it and all ExplosionChain which located near blow up too. Even hidden one with bOnlyTriggerable is True.

Possible solution:
Add new variable bTriggered = false by default.
On trigger set it to true.
On TakeDamage add check to it:
`if (bOnlyTriggerable && !bTriggered) Return;`

Here handful search for issue: https://github.com/Slipyx/UT99/search?q=Detonated
All lines visible at once.

**Comment by SeriousBuggie** [comment]
I can blow up hidden explosion chains by shock combo on bpak bshock. Look like it is implemented via explosion chains too. So use bpak can destroy map logic in scripted events.

**Comment by an-eternity** [comment]
Is this some bug of BPak? I check the script but don't understand how this happens... Those classes have MyDamageType==jolted defined in Botpack parent classes. Maybe BPak version i have is not the same... (there are many...)

**Comment by SeriousBuggie** [comment]
No this is bug of UT. Bpak is easy way for illustrate this.

I can make test map without bpak where by button triggered one explosion chain and near located another explosion chain intended be trigger only by button. But both trigger by first button. because detonate.

**Comment by CacoFFF** [comment]
Looks like it was done to have the main ExplosionChain cause the other ExplosionChains to go off as well.
Would not 'fix'

**Comment by SeriousBuggie** [comment]
I do not think so. If you need chain you not set ExplosionChain as trigger only by action via bOnlyTriggerable.

**Comment by stijn-volckaert** [comment]
I'm reviewing some old tickets and saw this one is still open. This seems like a "good bad bug" to me, so we're not going to fix this in the base game.
