### ISSUE TITLE
[469a] UnrealEd crash on try change property of actor

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#81]
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: WM_CHAR <- MessagePump <- MainLoop
---------------------------
ОК   
---------------------------
```
This crash happens too often for me, but I not find yet easy way to reproduce it.
Typical it is look like that:
Enter some strings in Actor property and press Enter. Crash!

**Comment by SeriousBuggie** [comment]
Reproduce:
1. Open [DM-Warps](https://github.com/OldUnreal/UnrealTournamentPatches/files/5413473/DM-Warps.zip)
2. Enter command `EDITACTOR name=warpzonemarker0`
3. Navigate to Null category, Item markedWarpZone. 
4. Replace 1 to 2 in value `WarpZoneInfo'MyLevel.WarpZoneInfo1'` and press Enter.

Expected result: no crash.
Actual result: crash:
---------------------------
Critical Error
---------------------------
General protection fault!
History: WM_CHAR <- MessagePump <- MainLoop
---------------------------
ОК   
---------------------------

v469a: bugged.
v436: not bugged.

**Comment by SeriousBuggie** [comment]
Also if you not press Enter - no crash. So better avoid press Enter after edit field until bug not fixed.

**Comment by SeriousBuggie** [comment]
Also I try reproduce crash on UT (editactor command), not in UEd - no crash.
v469b 10 Nov in UEd crashed.

**Comment by SeriousBuggie** [comment]
Fixed in v469b 16 Nov. Confirmed.

**Comment by an-eternity** [comment]
I tried to reproduce (with client v469b Nov. 16) that crash described in "[469a] Actor properties window. # 105" - no crash anymore.
Maybe it was the same bug?
So, it seems to be fixed.

**Comment by SeriousBuggie** [comment]
It not same. Please not mess bugs in one. # 105 already tested and fixed.
Use page of # 105 bug for post comment about it.
