### ISSUE TITLE
[469b] Muzzle flash draw on wrong place if fov not 90

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#813]
Reproduce:
1. Start play any map.
2. Use in console `summon enforcer`, `loaded`, `all ammo`, for get double enforcer, all weapons and all ammo.
3. Use `fov 70` or `fov 120` in console for change FOV.
4. Try shoot with enforcer or minigun.

Expected result: Muzzle flash draw near weapon end. Same as for fov 90:
![img](https://user-images.githubusercontent.com/70026933/165376176-dd23ec44-d5a5-4892-aa5b-ddf01af772a1.png)
![img](https://user-images.githubusercontent.com/70026933/165376922-1f7b3766-3a06-43fb-9b58-41b7148ec49d.png)
![img](https://user-images.githubusercontent.com/70026933/165376969-22afd1d8-54b0-49aa-b400-3230cb49cd28.png)

Actual result: Muzzle flash draw not near weapon end:
fov 70
![img](https://user-images.githubusercontent.com/70026933/165376339-0487b806-13f0-4d32-a0e3-2091c3762395.png)
![img](https://user-images.githubusercontent.com/70026933/165376813-62b55825-d1eb-43e7-80a5-7b2365e57815.png)
![img](https://user-images.githubusercontent.com/70026933/165376781-2b14d3a9-4cd7-4418-90e9-fba2b5c4954c.png)

fov 120
![img](https://user-images.githubusercontent.com/70026933/165376470-1abdce8f-1ac2-466a-baca-ce29b6acbd8d.png)
![img](https://user-images.githubusercontent.com/70026933/165376623-9267f8a5-ed06-4616-a9b0-5adc6e2db2b4.png)
![img](https://user-images.githubusercontent.com/70026933/165376676-30bbe693-fa12-45b6-96e0-cacb9051d22a.png)

**Comment by Masterkent** [comment]
A suggested resolution:

In Engine.Weapon.RenderOverlays, add

`local float FovScale;`

and use the following code:
```
	if ( (bMuzzleFlash > 0) && bDrawMuzzleFlash && Level.bHighDetailMode && (MFTexture != None) )
	{
		FovScale = 1.0 / Tan(FClamp(PlayerOwner.DesiredFOV, 1.0, 179.0) / 360.0 * Pi);
		MuzzleScale = Default.MuzzleScale * Canvas.ClipX/640.0 * FovScale;
		if ( !bSetFlashTime )
		{
			bSetFlashTime = true;
			FlashTime = Level.TimeSeconds + FlashLength;
		}
		else if ( FlashTime < Level.TimeSeconds )
			bMuzzleFlash = 0;
		if ( bMuzzleFlash > 0 )
		{
			if ( Hand == 0 )
				Canvas.SetPos(
					Canvas.ClipX/2 - 0.5 * MuzzleScale * FlashS + Canvas.ClipX * (-0.2 * Default.FireOffset.Y * FlashO) * FovScale,
					Canvas.ClipY/2 - 0.5 * MuzzleScale * FlashS + Canvas.ClipY * (FlashY + FlashC) * FovScale);
			else
				Canvas.SetPos(
					Canvas.ClipX/2 - 0.5 * MuzzleScale * FlashS + Canvas.ClipX * (Hand * Default.FireOffset.Y * FlashO) * FovScale,
					Canvas.ClipY/2 - 0.5 * MuzzleScale * FlashS + Canvas.ClipY * FlashY * FovScale);

			Canvas.Style = 3;
			Canvas.DrawIcon(MFTexture, MuzzleScale);
			Canvas.Style = 1;
		}
	}
	else
		bSetFlashTime = false;
```

**Comment by dov910** [comment]
This code is helped when changing the fov, but still the screen resolution is changed and the muzzle flash is still showing in the wrong area.

**Comment by stijn-volckaert** [comment]
This should be fixed in the next preview build
