### ISSUE TITLE
[469b] macOS version info absent in Info.plist

### ISSUE THREAD

**Issue by MaddTheSane** [OldUnreal/UnrealTournamentPatches#815]
The macOS app bundle's Info.plist file is missing `CFBundleVersion` and `CFBundleShortVersionString`, which would show version info in Finder's Get Info window. So in order to check the version of the app, you need to launch the game to see the version number.

There are also other entries in the Info.plist that would help, such as `CFBundleIdentifier` (I'd recommend `com.epicgames.UnrealTournament`), `LSApplicationCategoryType` (`public.app-category.action-games`), `CFBundleName` ("Unreal Tournament"), `CFBundleGetInfoString`, to name a few.

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
