### ISSUE TITLE
[469b] Hard select actors in UnrealEd when placed near and used not software render

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#822]
Reproduce:
1. Start UnrealEd.
2. Open [ClickRenderBug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8646876/ClickRenderBug.zip)
3. Select not software render.
4. Try select one light, by click on it.
5. Try select another light by click on it.

Expected result: Both lights easy select, same as in Software render:
![img](https://user-images.githubusercontent.com/70026933/167293970-63adcfbb-0276-42cf-b88a-6f61c02a1548.png)
Actual result: One light hard or not able select:
OpenGL:
![img](https://user-images.githubusercontent.com/70026933/167294020-507f1e40-ac5a-4653-843e-377885841d63.png)
XOpenGL:
![img](https://user-images.githubusercontent.com/70026933/167294079-38d133a4-6a50-471e-9659-5b3d8f92b410.png)
Direct3D9:
![img](https://user-images.githubusercontent.com/70026933/167294086-b38baee1-a4e7-4fe5-b404-5b6e37924007.png)

**Comment by BerserkerBG** [comment]
Also cant select surfaces behind the lights

**Comment by SeriousBuggie** [comment]
It get any click for self, so it all sort of this, include impossibility clear selection and so on.

**Comment by BerserkerBG** [comment]
![OpenGL-Ued-Issue](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/11636920-4123-4518-8edd-b64024ed6710)

**Comment by SeriousBuggie** [comment]
It work via detect triangles which hit. Not take in account in account pixel data from textures, since it be too slow (2k4 editor show, i can be sometimes 30-60 seconds freeze after each click).

Only possible way do this with take in account pixel data - shaders.
So OpenGL and XOpenGL possible can be fixed, since shaders already here.

About D3D9 - technically there can be added shaders implementation, it appear in DirectX since version 8, but it doubtful if be done one day. So look like D3D9 out of question here.

**Comment by SeriousBuggie** [comment]
Current state:

XOpenGL, ICBIND, D3D11 - fine, at least since 469d.
OpenGL - fine, since v469e.
D3D12, Vulkan - must be fine too, not test it.
D3D9 - affected, but too hard for fix and not worth it.

So I goes close issue. You need use modern render, and all be fine.
Since most changes come on 469d - it marked as resolved in that patch.
