### ISSUE TITLE
[436-469c] UnrealEd: wrong map name in window title bar

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#825]
1) Open any map in UnrealEd.
2) Try to open a map that UnrealEd cannot open because of missing dependent files.

Expected: the name of the map opened in (1) stays in window title bar, because that map is still loaded.
Actual: The map name of (2) is displayed in window title bar.

**Comment by SeriousBarbie** [comment]
v436 as well as 469c

**Comment by SeriousBuggie** [comment]
This need fix engine part. `MAP LOAD` must return FALSE if map load failed.
