### ISSUE TITLE
ucc-bin and ucc-bin-x86 are equal?

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#827]
`cmp ucc-bin ucc-bin-x86 && echo equal`

> equal

Is there any reason for these duplicate? Can I remove (or hardlink) it?

**Comment by SeriousBuggie** [comment]
Read answer here: https://github.com/OldUnreal/UnrealTournamentPatches/issues/587#issuecomment-976239407
