### ISSUE TITLE
[469a] Automatic crosshair scaling doesn't change how the crosshair is rendered in the menu

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#83]
I'm using the D3Dv9 renderer and play at 2560x1440 resolution.

My crosshair won't automatically scale. 

It looks fine in the HUD options menu with the auto-scale checkbox checked (i.e. nice and small) but in game it looks enlarged as per UT's default buggy crosshair. 

This happens both in local practice mode with no mutators and online with no mods/mutators on a 469a server.

**Comment by stijn-volckaert** [comment]
Auto scaling is the default (pre-469) behavior. Have you tried turning auto scaling off and moving the slider?

**Comment by dizzy-egg** [comment]
Ah, so when auto-scaling is enabled the crosshair should actually be the default (large, poorly-scaled) crosshair?

That isn't really clear from the menu options.

Here's what my crosshair setup looks like in the menu:
![image](https://user-images.githubusercontent.com/28424385/95149832-ce19c080-077e-11eb-8bec-457a8d437f4d.png)

And here's what it looks like in game:
![image](https://user-images.githubusercontent.com/28424385/95149876-e2f65400-077e-11eb-922b-0e7051dd90d9.png)

You can see there is a disparity between the two.

I assumed that ticking "auto scaling" would activate some new feature from the patch to properly scale the crosshair at high resolutions.

If the above is correct can I please suggest:

1. Changing the checkbox label to something like "Default (UT) Scaling" to make it clear it's not a new type of scaling.
2. When the checkbox is ticked, disable (fade out) the crosshair preview... or...
3. Make the crosshair preview box scale "correctly" (i.e. the default huge scaling if the checkbox has been ticked)

**Comment by stijn-volckaert** [comment]
This will be fixed in the 469c patch

**Comment by stijn-volckaert** [comment]
Fixed in 469c-RC2
