### ISSUE TITLE
[469b] PNG import is broken

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#834]
When you import PNG textures, they seem to have broken mipmaps. Here is a quick example of a texture exported in PCX and PNG, then imported into UEd. Both PCX and PNG textures have the same import settings - Gen MipMap flags with None DXT compression.

![Screenshot_2176](https://user-images.githubusercontent.com/58362332/169649156-474373aa-d1da-4aff-a34f-3c6db165194a.png)
![Screenshot_2175](https://user-images.githubusercontent.com/58362332/169649162-c48ec719-c1d9-40fa-99ad-7dfa7d6afb18.png)

Here are both PCX and PNG texture files, as well as a map file for reproduce:
[PCX-vs-PNG_Import.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8747473/PCX-vs-PNG_Import.zip)

**Comment by stijn-volckaert** [comment]
Could you test this with the 469c release candidate please?

**Comment by BerserkerBG** [comment]
> Could you test this with the 469c release candidate please?

Tested on RC2, problem is fixed.
