### ISSUE TITLE
[469b] linux, radeon, XOpenGLDrv, Steam Proton Experimental: rendering bugs

### ISSUE THREAD

**Issue by xDShot** [OldUnreal/UnrealTournamentPatches#841]
Copy-pasted from mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6542

### Description

Unreal Tournament (1999) with 469b patch installed: https://github.com/OldUnreal/UnrealTournamentPatches played on Steam with Proton Experimental with XOpenGLDrv (OpenGL 4-based 3d renderer) enabled.

There are rendering artifacts in game menus:

![20220522194815_1](https://user-images.githubusercontent.com/4261659/169707497-e0e7f078-1838-4f6e-8225-8ffd7681f034.jpg)
![20220522194821_1](https://user-images.githubusercontent.com/4261659/169707500-2718513d-07c9-4ec1-9856-0ee9743155fb.jpg)
![20220522194727_1](https://user-images.githubusercontent.com/4261659/169707507-388f2101-7cb8-4577-9b1a-c952f6728cd3.jpg)

There is also wireframe rendering on world objects behind glow effects (found on first tutorial level):

![20220522195110_1](https://user-images.githubusercontent.com/4261659/169707525-dc4a6124-b9a4-474a-8b28-5802cef575ba.jpg)

No such bugs on vanilla 436 with (older) OpenGL renderer:

![20220522195558_1](https://user-images.githubusercontent.com/4261659/169707530-90d7aaac-3224-4d14-b2c7-94a02bce6ae4.jpg)
![20220522195521_1](https://user-images.githubusercontent.com/4261659/169707534-4a3bfff5-42de-4a51-9ae3-0bddafc820af.jpg)

### System information

- OS: NAME="Arch Linux"
- GPU: 29:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c4)
- Kernel version: 5.17.9
- Mesa version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.0.4
- Desktop environment: XDG_CURRENT_DESKTOP=GNOME

#### If applicable
- Xserver version: wayland 1.20.0-2
- DXVK version:
- Wine/Proton version: Proton Experimental

### Further information (optional)

Does the issue reproduce with the LLVM backend (`RADV_DEBUG=llvm`) or on the AMDGPU-PRO drivers? **Yes**

Does your environment set any of the variables `ACO_DEBUG`, `RADV_DEBUG`, and `RADV_PERFTEST`? **No**

**Comment by NeonKnightOA** [comment]
With OldUnreal/UnrealTournamentPatches it happens the same?

**Comment by xDShot** [comment]
This is on 469b. Or what patch you talking about?

**Comment by SeriousBuggie** [comment]
![img](https://user-images.githubusercontent.com/70026933/169718089-9d98e2ef-558d-470b-9e1b-0fe318b3fea6.png)
https://github.com/OldUnreal/UnrealTournamentPatches/releases/download/v469b/XOpenGL-469b-Fix2.zip

**Comment by xDShot** [comment]
Yes, i tried this one. Same.

**Comment by uralets** [comment]
Proton? я чёто не пойму или сир знает толк в извращениях
релаьно не слежу за этими прокладками но зачем в вайне запускать то что этим же прожэктом в нативе есть???

**Comment by xDShot** [comment]
Besides, graphical glitches are here. So OldUnreal or mesa should take a look and fix it.

**Comment by uralets** [comment]
В Пн, 23/05/2022 в 09:01 -0700, xDShot пишет:
> > 
> I want Steam features be integrated like overlay and hours tracking,
> showing friends i play, etc. Unfortunately Steam doesn't allow change
> what binary should be launched for game (apart of replacing
> UnrealTournament.exe but it still feeds binary to proton).
> 

pls devs DON'T YOU DARE SPEND YOUR TIME ON THIS CRAP. thx.

**Comment by xDShot** [comment]
Worth to mention that UT99 is practically only legally purchasable on Steam and GOG, both provide only Windows version.

**Comment by uralets** [comment]
а ты убейся нафиг в свой компост под названием лорчик сиди там среди
навозных опарышей бля
В Пн, 23/05/2022 в 09:01 -0700, xDShot пишет:

**Comment by xDShot** [comment]
> В Пн, 23/05/2022 в 09:01 -0700, xDShot пишет:
> > I want Steam features be integrated like overlay and hours tracking, showing friends i play, etc. Unfortunately Steam doesn't allow change what binary should be launched for game (apart of replacing UnrealTournament.exe but it still feeds binary to proton).
> pls devs DON'T YOU DARE SPEND YOUR TIME ON THIS CRAP. thx.

Look, if you don't care and can't provide something meaningful, you can just step away. No one gonna listen to you just because you have penguinophobia or some other psychological traumas.

**Comment by uralets** [comment]
> penguinophobia
> 
hope the devs see who's the village idjit here

**Comment by stijn-volckaert** [comment]
Could you test the 469c release candidate?

**Comment by xDShot** [comment]
Unfortunately visual glitches are still there

![20220725213705_1](https://user-images.githubusercontent.com/4261659/180850071-c371fac0-26cb-49ad-b90c-6efd9c43e37b.jpg)
![20220725213727_1](https://user-images.githubusercontent.com/4261659/180850077-2f931a04-28a5-4bf7-94f0-35adc9bdc771.jpg)

**Comment by xDShot** [comment]
I gonna give up on this idea. Right now I play on native linux client.
The XOpenGL has same graphical issues. I switched to regular OpenGL render device. It still has (although much less) some wireframes behind transparent projectiles and glows, but these are eliminated by wrapping to zink ogl to vulkan translator.
Plus, I made script that wraps Steam API so it shows everyone I play UT99 and adds Steam overlay.

**Comment by stijn-volckaert** [comment]
This is probably the same bug as #971

**Comment by stijn-volckaert** [comment]
Could anyone test if this still happens with the latest 469d preview? Come talk to us on Discord if you don't have access to preview builds

**Comment by stijn-volckaert** [comment]
This should be fixed in the next build
