### ISSUE TITLE
[469b] Add Save button to UnrealEd script editor and Ctrl+S hotkey for it

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#846]
For reduce possibility lost work via UnrealEd crash need add Save button To UnrealEd code editor.

When you press it, current script text save to class (without compile) and package of this script saved too.
Of this script embed into level, then there possible options:
- save level too (possible side effects, even crashes, like in #475)
- Ask about save level.
- not save anything.

Another possible solution - not save packages, but on press this button save current open class text to TempScript.uc located in System directory.

This solution can work with any class and allow later manually load code from this file.

**Comment by an-eternity** [comment]
If package binary data does not match text data it is not quite good, especially if then such package appears available/shared for public use...
For this reason, i think solution that saves script in an external temporal *.uc file would be preferable, so that text data in a package is updated only on compile.

**Comment by SeriousBuggie** [comment]
Data already save independent from binary form. You can write anything close script in editor and save package without compile.
Text saved in class be not same as actual compiled form.

But I think you right by other reasons. Too many pitfulls here, so better make save in fail-safe file. Possible even some sort of autosave with timer. You can force autosave by manual call it it can be called by timer.

**Comment by SeriousBuggie** [comment]
look like change in external .uc not option at all. It is produce false expectation.

Let's say user change one class, press Save butoon. Now he goes to next class and press Save button again.
He expect both classes be saved when he open editor again. But it is not true.
If we use same file, user lost first class. if different files, we just flood UT folder with files. Who clear it? Who look in it?
It is not acceptable.

So I think need goes save package or map (if script in MyLevel package). Wothout prompt. So it can easy been toggled by hotkey during work.

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/174455225-3dc465ab-5678-4c83-a517-f333b65cc628.png)

![img](https://user-images.githubusercontent.com/70026933/174455230-728f345d-811b-4f1f-bd48-a027db6dfeda.png)
