### ISSUE TITLE
[469b] Bigger collision size on actor sometimes produce hit invisible walls

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#866]
Reproduce:
1. Start map [MH-XV-GiranTown2021v1_dbg.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8904107/MH-XV-GiranTown2021v1_dbg.zip) (All assets for it you can find in full map: https://ut99.org/viewtopic.php?f=5&t=15020 )
2. After exit from start house, on left side exists way:
![img](https://user-images.githubusercontent.com/70026933/173694912-3a267191-277c-45c0-bc6a-52c88d8f50db.png)
3. You can go here forward to left house and not see any invisible wall.
3. Now enter in console: `set playerpawn collisionradius 135`.

Expected result: You able walk here as before.
Actual result: You stuck into invisible wall.
![img](https://user-images.githubusercontent.com/70026933/173695436-9497b12f-f3cb-4590-b7dd-a3de20bb74df.png)

If you use smaller values, like 40, invisible wall be smaller in width:
![img](https://user-images.githubusercontent.com/70026933/173695763-d9e026e2-6e25-4119-9031-6481a9758ede.png)

If you use bigger values like 200, invisible wall prevent walk you even on bright road far away from building:
![img](https://user-images.githubusercontent.com/70026933/173696020-a8b91363-feba-4826-b790-3d64bdb3fba7.png)

Practical meaning of this issue:
Player able run where jeep or tank hit invisible wall.

**Comment by SeriousBarbie** [comment]
Typical BSP cut obstacle
![MH-XV-GiranTown2021v2-BSP_cut](https://user-images.githubusercontent.com/81397053/173769779-075a3b1a-ecce-4a46-b39c-9b51d531f1d3.jpg)
That map exists in various versions:

- Parent of all: MH-(dU)Giranbeta.unr (without monster, with brushes, without BSP error)
- Version of Red_Fist: MH-GiranTown.unr (with monster, with brushes, without BSP error)
- My fixed version of Red_Fist's version: MH-GiranTown+SBFix1.unr (with monster, with brushes, BSP error not tested)
- Thunderbolts version: MH-(dU)GiranTown(2021)V16.unr (with monster, without brushes, with BSP error)
- (unknown)'s version: MH-XV-GiranTown2021v2.unr  (with monster, without brushes, with BSP error)

Sadly brushes were remove in map version in question, so a rebuild is not possible.
Also this is no answer to the question why smaller collision radii are not affected by the BSP cut. :-o

**Comment by NeonKnightOA** [comment]
This looks less a problem of the game and more a problem of the map itself.

**Comment by SeriousBuggie** [comment]
Game must be consistent. If there bad spot on map, there must be invisible wall for all size actors. And width must be same for any CollisionRadius.

**Comment by SeriousBuggie** [comment]
Bug in engine collision code. Will be fixed in 469e.
