### ISSUE TITLE
[469b] Add white box for UV panning for Surface Properties

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#867]
Currently the Surface Properties has Rotation and Scaling white boxes, where it allows you to enter any custom value. But it is missing for UV pan as well. Here is a quick concept of how it could look like:

Before:
![Screenshot_2211](https://user-images.githubusercontent.com/58362332/173711268-e2b826e2-2260-4e22-96d6-8d16f33961e8.png)

After:
![Screenshot_2213](https://user-images.githubusercontent.com/58362332/173711353-4c7268c9-30fe-45ff-ac24-a5a2bd1436ee.png)

**Comment by SeriousBuggie** [comment]
Possible implementation:
![img](https://user-images.githubusercontent.com/70026933/173784444-f30a6efb-abed-4f1e-ac94-dad3453344f6.png)

**Comment by BerserkerBG** [comment]
> Possible implementation: ![img](https://user-images.githubusercontent.com/70026933/173784444-f30a6efb-abed-4f1e-ac94-dad3453344f6.png)

This is great. I like this better, it fits properly.

**Comment by SeriousBuggie** [comment]
You can already test it in test69.
