### ISSUE TITLE
[469b] Keyboard navigate not work in Recovery mode dialogs

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#870]
Reproduce:
1. Make empty text file `System/Running.ini`
2. Start UT.
3. Try use keyboard navigation on dialog.
![scr_1655453483](https://user-images.githubusercontent.com/70026933/174281632-f651d7f5-6a09-4e28-abf0-6b0636e7fee0.png)

Expected result: Simple press Enter start game. Tab or arrows allow select next item.
Actual result: Enter not work, Tab and arrows able transfer focus to button cancel and focus stay here.

Same store if you choose change 3d device. You able work with dialog only with mouse, not via keyboard.

**Comment by SeriousBarbie** [comment]
Nearly all Windows standard key commands (PgUp, PgDn, End, Home, Tab, Ctrl+Tab, ...) do NOT work in all (?) dialog windows. I get annoyed by that mostly in the "Search for Actors" window.

**Comment by SeriousBuggie** [comment]
You should make separate issue for 
> "Search for Actors" window.

(or any other)
This issue very specific and can be related only to wizard dialogs.
