### ISSUE TITLE
[469b] Double-click on unknow state combobox no change value on it

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#871]
Reproduce:
1. Start UnrealEd.
2. Add 2 Lights.
3. On one set bHidden = true.
4. Select both Lights.
5. Double click on empty bHidden value.
![img](https://user-images.githubusercontent.com/70026933/174294103-bc230540-0e73-4e97-bca4-964b7c32758b.png)

Expected result: Value changed to first value in combo box - `False`.
Actual result: Value not changed. Need goes open combobox and select value.

**Comment by SeriousBarbie** [comment]
Hmm, other interpretations are possible when doing a double click:
1) TRUE switches to FALSE, FALSE to TRUE, so property of both toggles
2) both are set to TRUE
3) both are set to FALSE

**Comment by SeriousBuggie** [comment]
Yes, possible, but 1 not really expected. 2- Almost same as 3. But 3 is best, since can be apply to any combo box, even for enum.

**Comment by SeriousBuggie** [comment]
Map for test: [UnknownStateComboBox.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8934364/UnknownStateComboBox.zip)
