### ISSUE TITLE
[469b] Fast console not able edit message

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#875]
Reproduce:
1. Start UT.
2. Press talk key (Usually `T`)
3. Press backspace.
4. Enter `123456`
![img](https://user-images.githubusercontent.com/70026933/174322077-f05d378e-692a-4db4-905c-09826c9e08a8.png)

Expected result: Exist way add space after `Say` not erase input text.
Actual result: No any way edit text, without erase whole text.

Typical case - screwed up command `Say `,Not notice and write big text. no any way fix it and sent again.

**Comment by SeriousBarbie** [comment]
Reminds me to EDLIN *lol
