### ISSUE TITLE
[469b] `Load Entire Package` not refresh all browsers

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#879]
Reproduce:
1. Open DM-XVehiclesTestMap from [XVehicles](https://ut99.org/viewtopic.php?f=34&t=14936)
2. Select XVehicles package in Texture Browser.
3. Use Edit - `Load Entire Package` from menu.
4. Go to Actor Browser and open Actor - VActor - Vehicle in tree.

Expected result: Listed all Phys classes:
![img](https://user-images.githubusercontent.com/70026933/174452405-155944a6-edc7-48b6-be4c-d4a5dd8d1122.png)

Actual result: Listed only part of Phys classes:
![img](https://user-images.githubusercontent.com/70026933/174452386-5ad44a29-888c-41dc-8aa8-6f290109450a.png)

Same can be done in any browser with `Load Entire Package` feature.

**Comment by stijn-volckaert** [comment]
Fix merged for 469c RC3
