### ISSUE TITLE
[win][469a] Inconsistent collision/movement while dodging with uncapped frame rate

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#88]
Just noticed some strange collision behaviour while playing online on a 469a server with a 469a client running D3Dv9 renderer.

There's a map called CTF-BT-Recon.unr which at one point requires to cross a gap by side dodging into a ramp and sliding along it.

* With `FrameRateLimit=0` I am unable to dodge across this ramp - I am stopped halfway across by some invisible collision.
* With `FrameRateLimit=144`, I am able to dodge across the ramp no problem.

![Screenshot](https://i.imgur.com/6OIgXNn.jpg)

**Comment by Chamberly** [comment]
I played with FrameRateLimit=0 on D3D9 and made it across several times but often times I do get stopped in random area but that depends on how I am performing my dodges. My frame rate on screen was showing I was getting around 280-330 FPS in the area. Tested offline.

For other who wanted to test, go to CTF gametype and load up this map and additional mutators if you wish:
http://medor.no-ip.org/Maps/BunnyTrack/CTF-BT-%28JJ%29Recon.zip The map. You can fly, ghost through the walls but go left and forward.
http://medor.no-ip.org/GameTypes/BunnyTracks/BTCheckPoints.zip Type in Console **Mutate Checkpoint** so you don't have to start at the start spawn point.
http://medor.no-ip.org/GameTypes/BunnyTracks/BTPlusPlusv0994.zip BT++ mod if wanted to test with the mod, only difference is the HUDs.

**Comment by dizzy-egg** [comment]
@Chamberly Did you try the same dodge with your frame rate capped to e.g. 144? It should be much easier and you won't get stopped as often.

**Comment by Chamberly** [comment]
I noticed I do a bit better with 144 than 0.
