### ISSUE TITLE
[469b] Weapon list not resized on drag splitter

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#883]
Reproduce:
1. Start UT.
2. Menu - Options - Weapons.
![img](https://user-images.githubusercontent.com/70026933/174503467-fd50912c-350a-465d-9c22-72e7cc3b407a.png)
3. Try drag splitter between weapon and list on left side.

Expected result: Weapon list width changed.
Actual result: Weapon list width remain same:
![img](https://user-images.githubusercontent.com/70026933/174503911-3176776e-ccab-4273-8f0e-c612f922b943.png)

**Comment by stijn-volckaert** [comment]
Patch merged for 469c RC3
