### ISSUE TITLE
[469a] Rockets Appearing in Speciffic spots on some maps post 469 OpenGL

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#89]
Having a weird issue (not really a problem) but these `Rockets` are popping up in some maps
in specific spots not random. 
- Problem only started happening post 469.
- Not appearing in 436/451

![uF8VL33](https://user-images.githubusercontent.com/72378011/95146736-27afd880-07db-11eb-97b3-a94646d49632.png)

http://medor.no-ip.org/index.php?dir=Maps/DeathMatch/&file=DM-1on1-AugustMoon.zip

**Comment by Chamberly** [comment]
That was a change I suggested before 469a released. Several maps have warhead ammo which has been shown invisible by lack of mesh being set to the property so it was a uscript change so now it will be visible.

The map have the warhead ammo laying around and if you go around to pick it up, you actually pick it up but I didn't find the redeemer in the map lol.

**Comment by stijn-volckaert** [comment]
We are going to revert this change in 469c because it has some other side effects we did not anticipate.

**Comment by stijn-volckaert** [comment]
Reverted in 469c-RC2
