### ISSUE TITLE
[469b] Turn on by default utpg implementation for \teams\ query.

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#895]
By default UdpServerQuery.bTeamInfo is False. So `\teams\` query not work. Need turn it on by defaults, for more servers able work without additional config, like this:
```ini
[IpServer.UdpServerQuery]
GameName=ut
bTeamInfo=True
```

**Comment by stijn-volckaert** [comment]
Fix merged for 469c RC3
