### ISSUE TITLE
[linux] ut469 ignores settings from older versions

### ISSUE THREAD

**Issue by AntiSol** [OldUnreal/UnrealTournamentPatches#90]
It looks like v469 is ignoring all my existing settings that I have in ~/.loki/ut. This is pretty annoying for someone with many mods and customisations installed

I see the following in the output from ut:
````
WARNING: using preference directory: /home/antisol/.utpg/System/
WARNING: Using system ini file: /usr/local/games/ut/System/UnrealTournament.ini
WARNING: Using user ini file: /usr/local/games/ut/System/User.ini
````
It seems to me that it should at least look in the old ~/.loki/ut directory if it can't find anything in ~/.utpg, i.e use a fallback order: check in ~/.utpg, and if that fails look in ~/.loki/ut

**Comment by AntiSol** [comment]
note that copying ~/.loki/ut/* into ~/.loki/utpg/ gives me my settings back

**Comment by stijn-volckaert** [comment]
Confirmed. UTPG changed the default location of the "preferences directory" from ~/.loki/ut/ to ~/.utpg/. They did not add an automatic fallback option and neither did we. We did, however, add a new command line option (-sethomedir=) which you can use to tell your UT binaries to use the loki folder instead.

**Comment by AntiSol** [comment]
Hmmm. Am I correct in thinking that v451 was from utpg? I was on 451 before updating to 469 and it was using the .loki directory.

the -sethomedir option is useful, thanks, but it's still not ideal as you'd then need to use that argument every time you launch the game. The typical way these things are handled in Linux-land is by using fallback. It's pretty trivial to implement. Maybe worth looking at.

I read somewhere you were looking for a Linux installer. Are you still interested in that? If I wrote an installer I could look for this situation and migrate settings from ~/.loki unti ~/.utpg. could be a workable option.

**Comment by CacoFFF** [comment]
We picked up UT on v468, which was never publicly released. It was already `~/.utpg` on those builds.

**Comment by stijn-volckaert** [comment]
And yes, we are still looking for an installer :)

**Comment by AntiSol** [comment]
What's the best way for me to to get on board WRT building an installer and to chat with you guys? do you have a community / chat somewhere I can join? I'll have many questions and there will probably be discussion that's not really appropriate for the issue tracker.

**Comment by stijn-volckaert** [comment]
How/where can I send you private messages?

**Comment by AntiSol** [comment]
how does email suit you? myusername  a t  myusername   d o t    o r g
