### ISSUE TITLE
[469b] Missing localization titles for compatibility dialogs

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#900]
Reproduce:
1. Open unrealEd 
2. Search and open script for class UTFadeTextArea.
3. Add space in any place.
4. Press recompile.
5. If issue not appear do it again from step 3.

Expected result: Compatibility dialogs properly load localization info.
Actual result:
![img](https://user-images.githubusercontent.com/70026933/175618350-6dcd407e-5660-4379-8a1d-2bd00c8337cb.png)
```
---------------------------
<?int?Core.Errors.Question?>
---------------------------
The package you are trying to save calls function Botpack.TournamentGameInfo.LadderTransition. 
This function was not present in UT v436, so this package will not work on UT v436 clients or servers. 
Are you sure you want to continue?
---------------------------
Да   Нет   
---------------------------
```
idk why `<?int?Core.Errors.Question?>` not resolved.
I look into Core.int, there in section `[Errors]` present line `Question="Question"`

**Comment by SeriousBuggie** [comment]
Also in background:
![img](https://user-images.githubusercontent.com/70026933/175618904-b2fdbd0a-00e0-47bb-b925-3873f8bf6817.png)
Core.int:
```ini
[Progress]
Saving="Saving file "%ls"..."
Loading="Loading file "%ls"..."
Closing="Closing"
```

**Comment by NeonKnightOA** [comment]
Then it isn't a problem with the .int files or its coding, I reckon?

**Comment by SeriousBuggie** [comment]
Hm. it is something broken. Since after clean run I not able get this issue. but if I try compile second time - issue happen.

**Comment by SeriousBuggie** [comment]
This happen because on compilation current working dir changed to package folder.
![img](https://user-images.githubusercontent.com/70026933/175774165-58087fea-e8b0-4c03-91f7-7cd6d9760a6e.png)
So attempt load int file from it fail.

**Comment by stijn-volckaert** [comment]
This was a bug in the new localization code we wrote for 227j/469c. I've pushed a fix for 469c RC3

**Comment by stijn-volckaert** [comment]
RC3 is now available
