### ISSUE TITLE
[469b] Need make more descriptive text for `Cleanup Level` tool

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#904]
![img](https://user-images.githubusercontent.com/70026933/175799884-3f0e26d7-91ba-4525-8fed-ff2ec0dde001.png)
![img](https://user-images.githubusercontent.com/70026933/175799889-83ba898b-07ad-4a24-99bb-45e9977398c6.png)
```
---------------------------
Question
---------------------------
This will cleanup some map garbage, but you can not undo this operation! 
Note: You should ALWAYS save before executing this, are you sure you want to proceed?
---------------------------
Да   Нет   
---------------------------
```
There must be list of performed actions.
For example:
```
---------------------------
Question
---------------------------
This will cleanup some map garbage, but you can not undo this operation! 
Performed actions:
- remove duplicate actors
- log almost same actors
Note: You should ALWAYS save before executing this, are you sure you want to proceed?
---------------------------
Да   Нет   
---------------------------
```

**Comment by NeonKnightOA** [comment]
> This tool will remove duplicate actors as well as actors placed in the same spot. It's recommended that you save your level before this operation takes place. Are you sure you want to proceed?

**Comment by SeriousBuggie** [comment]
Look fine, if this exactly what this tool do. I not have access to source code of it, so can not really tell what it is do and what not.
