### ISSUE TITLE
[469b] CTFFlag able be lost if bot or player exit while carry flag

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#910]
In some cases CTFFlag still left on bot removed from game.
Both cases happens when bot be on flag base. Debug show Flag still in game but Holder bDeleteMe = true.
Need add such check for prevent this situation happens.

Not able reproduce it on regular basis, but this happen at least two times for me.

**Comment by stijn-volckaert** [comment]
Fix pulled for inclusion in 469c RC3
