### ISSUE TITLE
[469b] Server Browser clear game port if not able ping server

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#911]
Reproduce:
1. Open UT.
2. Open Favorites tab in Server Browser.
3. Add new favorite: 8.8.8.8:7777
4. Ping all servers (F5)
5. Edit added favorite again.

Expected result: Port still 7777.
Actual result: Port is 0.

**Comment by SeriousBuggie** [comment]
Possible we not able solve this without break compatibility with exists mods, since it often use in stock code as flag for unsuccessful ping.

**Comment by SeriousBuggie** [comment]
Also in rules grid it show zero port:
![img](https://user-images.githubusercontent.com/70026933/177056559-2a6bbe80-bc9a-490d-91cd-768988082a66.png)

**Comment by stijn-volckaert** [comment]
Fixes pulled for inclusion in 469c RC3
