### ISSUE TITLE
[469b] Not able delete config item in dynamic array

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#913]
Reproduce:
1. Start UnrealEd.
2. Open Advanced Properties.
3. Navigate to Networking - TCP/IP Network Play - DownloadManagers
4. Press `Add` for make new item.
5. Set Value to `123`
6. Delete added item.
7. Collapse DownloadManagers
8. Expands DownloadManagers

Expected result: There no item `123`
Actual result: After collapse/expand item `123` appear again, as never deleted.

**Comment by SeriousBuggie** [comment]
After 
```c++
			// stijn: this does not work... it calls saveconfig on the default object of a StrProperty class. 
			//Property->GetClass()->GetDefaultObject()->SaveConfig();
			Array->GetOuterUField()->GetOwnerClass()->GetDefaultObject()->SaveConfig();
```
`Addr->Num()` return to original size before delete items.

So there possible mistake in Core for save dynamic arrays. possible on TMultiMap called Remove instead of RemoveMulti.
Somewhere in `UObject::SaveConfig`, like this:
```c++
				TMultiMap<FString,FString>* Sec = GConfig->GetSectionPrivate( Section, 1, 0, Filename );
				check(Sec);
				Sec->Remove( Key );
```

**Comment by stijn-volckaert** [comment]
Fix backported from 227j. This will be included in 469c RC3

**Comment by stijn-volckaert** [comment]
RC3 is now available
