### ISSUE TITLE
[469b] XOpenGL Literally Unplayable!

### ISSUE THREAD

**Issue by noskill24** [OldUnreal/UnrealTournamentPatches#919]
All items/players are invisible/underground/flickering on middle distances. XOpenGL rendering is completely broken.

![image](https://user-images.githubusercontent.com/35011774/177033849-142735c5-c318-48d2-b818-461af8be100b.png)
![image](https://user-images.githubusercontent.com/35011774/177033855-4d26a926-ed26-47be-a581-d3cd738e2a79.png)
![image](https://user-images.githubusercontent.com/35011774/177033865-88518a3b-ca77-4955-9e19-697558760e5f.png)

**Comment by NeonKnightOA** [comment]
Does this happen even with XOpenGL Fix2?

**Comment by noskill24** [comment]
ZRangeHack - [True/False] - doesn't fix this issue.

ut436 xopengl 1.1.0.0 - doesn't fix this issue.
ut436 xopengl 1.1.0.1 - doesn't fix this issue.

With XOpenGL Fix2 - 1.1.0.0 - issue seems to be resolved.

Why this fix isn't included in this path?

**Comment by SeriousBuggie** [comment]
Because this fix out after patch.

**Comment by noskill24** [comment]
XOpenGL Fix2 - seems have a large input lag and micro freeze. A lot of frames didn't draw. Unplayable. I have latest Nvidia Drivers Installed.

**Comment by stijn-volckaert** [comment]
What kind of GPU do you have?

**Comment by stijn-volckaert** [comment]
We can continue the discussion about performance in #954. The vanishing mesh problem is fixed in 469c RC2 and was also reported in #637
