### ISSUE TITLE
[469b] Actor with bMovable = False and Phys_None on shoot goes to endless Phys_Falling with some Velocity

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#925]
Reproduce:
1. Start map [TestDecoDamage.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9036462/TestDecoDamage.zip)
2. Shoot chest with insta.
3. Use `editactor class=chest` for look on actor Physics and Velocity

Expected result: Phys_None and zero velocity.
Actual result: Phys_Falling and not zero velocity.
![img](https://user-images.githubusercontent.com/70026933/177085164-47448341-d99e-4243-863c-4e9fcb973ed5.png)

This lead to kill pawns which try to jump on such deco:
https://ut99.org/viewtopic.php?f=12&t=15294

Workaround: walk over all bMovable = false on some interval and reset Velocity to zero.

Possible solution: Modify Phys_Falling implementation in next way:
If bMovable == false, then set velocity to zero and switch Physics to Phys_None.

**Comment by stijn-volckaert** [comment]
I suspect that some people consider this a feature...
