### ISSUE TITLE
[469b] UT not show map scrrenshot if it named not as MyLevel.Screenshot.

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#926]
Reproduce:
1. Install map [CTF-TestSshot.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9044252/CTF-TestSshot.zip)
2. Start UT.
3. Select Practice session.
4. Select this map.

Expected result: Map screenshot loaded and show.
![img](https://user-images.githubusercontent.com/70026933/177276412-1add0b27-5baf-497b-88f4-fff04ab0c5a7.png)
Actual result: Map screenshot not show:
![img](https://user-images.githubusercontent.com/70026933/177274917-20f7fb6b-9a42-445a-a3c0-df8396d70385.png)
![img](https://user-images.githubusercontent.com/70026933/177275009-f9a04e1e-3ec7-4dae-8982-5e0bed31aa1e.png)

Reason: UT load only MyLevel.Screenshot, and ignore actual texture name in LevelInfo.Screenshot field:
UMenuScreenshotCW
```unrealscript
function SetMap(string MapName)
{
	local int i;
	local LevelSummary L;

	i = InStr(Caps(MapName), ".UNR");
	if(i != -1)
		MapName = Left(MapName, i);

    if (MapName != "")
	{
		Screenshot = Texture(DynamicLoadObject(MapName$".Screenshot", class'Texture'));
		L = LevelSummary(DynamicLoadObject(MapName$".LevelSummary", class'LevelSummary'));
		if(L != None)
		{
			MapTitle = L.Title;
			MapAuthor = L.Author;
			IdealPlayerCount = L.IdealPlayerCount;
		}
		else
		{
			MapTitle = "";
			MapAuthor = "";
			IdealPlayerCount = "";
		}
	}
}
```

Suggestion: If load screenshot fail, try load LevelInfo and get Texture name from it.

**Comment by SeriousBuggie** [comment]
Solution:
```unrealscript
function SetMap(string MapName)
{
	local int i;
	local LevelSummary L;
	local LevelInfo LevelInfo;

	i = InStr(Caps(MapName), ".UNR");
	if(i != -1)
		MapName = Left(MapName, i);

    if (MapName != "")
	{
		Screenshot = Texture(DynamicLoadObject(MapName$".Screenshot", class'Texture'));
		if (Screenshot == None)
		{
			LevelInfo = LevelInfo(DynamicLoadObject(MapName$".LevelInfo0", class'LevelInfo'));
			if (LevelInfo == None)
				LevelInfo = LevelInfo(DynamicLoadObject(MapName$".LevelInfo1", class'LevelInfo'));
			if (LevelInfo != None && LevelInfo.Screenshot != None)
				Screenshot = LevelInfo.Screenshot;
		}
		L = LevelSummary(DynamicLoadObject(MapName$".LevelSummary", class'LevelSummary'));
		if(L != None)
		{
			MapTitle = L.Title;
			MapAuthor = L.Author;
			IdealPlayerCount = L.IdealPlayerCount;
		}
		else
		{
			MapTitle = "";
			MapAuthor = "";
			IdealPlayerCount = "";
		}
	}
}
```

**Comment by SeriousBarbie** [comment]
> Suggestion: If load screenshot fail, try load LevelInfo and get Texture name from it.

My expectation would be: if a screenshot texture is set in LevelInfo, that should be used. If not set, search for Texture'MyLevel.ScreenShot'.

**Comment by SeriousBuggie** [comment]
Yes, this is more proper way and this is how it must work, but...
Old clients already has implementation based on MyLevel.ScreenShot, so if you make map where exists MyLevel.ScreenShot and set LevelInfo.Screenshot to Another textures, then:
1. on old clients show MyLevel.ScreenShot
2. on new clients show LevelInfo.Screenshot

Which lead to difference between new and old clients.

If we use less proper approach, then it display same - MyLevel.ScreenShot
Only if old client fail, new client able load LevelInfo.Screenshot.

So there no mismatch, only enhancement.
