### ISSUE TITLE
[469b] UnrealEd PCX texture import bug

### ISSUE THREAD

**Issue by peterekepeter** [OldUnreal/UnrealTournamentPatches#928]
I found a case where importing a PCX texture will results in distorted/corrupt image with 469 whereas the same PCX loads fine with 436. 

Here is the PCX file (zipped to be able to upload into the issue)

[CTF-FaceShot.pcx.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9049581/CTF-FaceShot.pcx.zip)

As loaded in 469's editor (look close at bottom of image):

![image](https://user-images.githubusercontent.com/7863124/177413175-9e9c2ae6-6896-4d9f-9a35-d5227b83b933.png)

As loaded in 436's editor:

![image](https://user-images.githubusercontent.com/7863124/177413250-e75a5391-0e4b-4044-a38c-1ace19bb13f3.png)

It also loads just fine in GIMP:

![image](https://user-images.githubusercontent.com/7863124/177415426-353095b3-3f38-422d-ae7d-7da6e1a8eeca.png)

I managed to track down the issue it's related to the binary encoding of the RLE data. On 469 PCX loader seems to require all RLE pairs to not span over scanlines. All pixels that go beyond the scanline get discarded. The 436 version does allows a RLE pair to start on one scanline and finish on the next scanline. 

Fixing this I estimate is deleting a few lines of code of change. I guess what 469 does is that it has extra logic to check and discard pixels that are beyond the scanline. And my best guess is that 436 simply does not keep track of the scanline it just unpacks all RLE pairs into bitmap memory which results in a behavior that is compatible with both encodings.

But if this change would break other PCX files that I don't know about, then it's possible to make this fix conditional by checking whether the bitmap is filled up or not when scanline pixels are discarded and switch to a decoding strategy where no pixels are discarded.

**Comment by stijn-volckaert** [comment]
The fix will be included in 469c RC3

**Comment by stijn-volckaert** [comment]
RC3 is now available
