### ISSUE TITLE
Renderer version mismatch

### ISSUE THREAD

**Issue by prime6809** [OldUnreal/UnrealTournamentPatches#93]
Hi all 

On connecting to some servers I get "Package 'Renderer' version mismatch." and the connection is refused 

The odd things is it worked connecting to the same server the first time after I installed the V3.69 patch. But then I clicked on the 'Change video driver' button to restart in driver selection mode, selected XOpenGL (which had been auto selected when the patch was installed). Now I get the mismatch error.

I've also tried the old OpenGL and DirectX renderers but still get the same problem.

Server address is : unreal://176.9.104.176:2310

Oddly other servers run by the same people don't seem to have this problem.....

Cheers.

Phill.

**Comment by stijn-volckaert** [comment]
The exe version of our patch mistakenly installed a file called Render.u in the UT/System folder. Deleting this file will likely fix this problem. We will also fix this in the 469b installer.

**Comment by prime6809** [comment]
Yep deleting Renderer.u has fixed it.

Thanks.

Phill.
