### ISSUE TITLE
All trophies unlocked even after making new game - patch 469b

### ISSUE THREAD

**Issue by SafreQ45** [OldUnreal/UnrealTournamentPatches#938]
I unlocked the Trophy room before patching and there was one trophy unlocked, as it should be.

Then I installed the OldUnreal 469b patch and I checked the trophy room and all of the trophies were unlocked.

After starting a new game and beating the Deathmatch mode, the trophy room was unlocked but all of the trophies were still there, even after making a new game. This is an issue because this "bug" makes playing and beating the game redundant.

**Comment by SeriousBuggie** [comment]
Possible duplicate of OldUnreal/UnrealTournamentPatches/issues/542

**Comment by stijn-volckaert** [comment]
Confirmed duplicate. The fix will be included in 469c
