### ISSUE TITLE
Mover.(Player)BumpEvent does not reach SpecicalEvent to apply damage

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#944]
Map setup: A mover with (Player)BumpEvent equal to a SpecicalEvent's Tag; SpecicalEvent is setup for DamageInstigator:

```
Begin Actor Class=SpecialEvent Name=SpecialEvent0
     Damage=1
     DamageType="Burned"
     InitialState="DamageInstigator"
     Level=LevelInfo'MyLevel.LevelInfo0'
     Tag="Mover0"
     ...
End Actor
```

```
Begin Actor Class=Mover Name=Mover0
     PlayerBumpEvent="Mover0"
     Tag="Mover0"
     InitialState="TriggerOpenTimed"
     ...
End Actor
```
Expected: player gets damage if he bumps the mover
Current: no damage
[TestMoverPlayerBumpEvent.unr.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9159842/TestMoverPlayerBumpEvent.unr.zip)

**Comment by SeriousBuggie** [comment]
```js
// Damage the instigator who caused this event.
state() DamageInstigator
{
	function Trigger( actor Other, pawn EventInstigator )
	{
		local vector HitLocation;

		Global.Trigger( Self, EventInstigator );
		if ( Other.IsA('PlayerPawn') )
			Level.Game.SpecialDamageString = DamageString;
		if (EventInstigator != None)
			HitLocation = EventInstigator.Location;
		Other.TakeDamage( Damage, EventInstigator, HitLocation, Vect(0,0,0), DamageType);
	}
}
```
Other is Mover. EventInstigator is PlayerPawn.
So on bump you damage mover.

Unfortunately too late change something. Too many code rely to Mover pass self as Other, or  DamageInstigator accept Other as Damage victim.

So you need use custom class for proper work with that.
