### ISSUE TITLE
[469c-RC2] Game will only start once

### ISSUE THREAD

**Issue by MLipfert1** [OldUnreal/UnrealTournamentPatches#945]
I tried the new release candidate on macOS 12.5 ARM64 and I was able to start the new build once. When I execute the game binary now, the following error is shown:

![image](https://user-images.githubusercontent.com/63508182/180492962-4d5fe24e-75be-414d-b9df-f08a2ce7ddb2.png)

I am able to start it again for just one time, when I delete the UnrealTournament.ini. The ini file itself looks like it was not written properly on exiting 469c RC2. It does not contain human readable content, just random symbols and characters (binary code?).

**Comment by stijn-volckaert** [comment]
Could you upload the UnrealTournament.ini file your game writes to disk please?

**Comment by MLipfert1** [comment]
[UnrealTournament.ini.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9169978/UnrealTournament.ini.zip)

Here is the ini files as zip. It is happening on a Mac mini M1 with two monitors connected. However a few minutes ago I also tested a MacBook Pro 16" M1 Pro and there the new version runs flawlessly. Both systems are running macOS 12.5.

**Comment by SeriousBuggie** [comment]
Look like encode to UTF-16 twice. 
![img](https://user-images.githubusercontent.com/70026933/180505982-bc8128f5-e4c6-491d-9a05-769af0b90411.png)

**Comment by MLipfert1** [comment]
Very interesting, how can that happen? The software setup of both tested computers is nearly the same. 🤷‍♂️

**Comment by SeriousBuggie** [comment]
Something related to iconv I guess.

**Comment by stijn-volckaert** [comment]
RC3 should fix this and is now available

**Comment by MLipfert1** [comment]
Unfortunately this issue is not fixed with the RC3 release. Now the UnrealTournament.ini is empty after the first start on the affected system. But that will lead to the same issue on the following attempts to run the game.

**Comment by stijn-volckaert** [comment]
Could you upload your UnrealTournament.log please?

**Comment by MLipfert1** [comment]
[Archiv.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9274529/Archiv.zip)

This archive contains two log files and the ini file.

The first log file was created after the first successful attempt to start the application. I changed the in-game resolution to 4k and adjusted the GUI and font scaling factors.

The second log file was then created after the second unsuccessful starting attempt that failed because the ini file was not filled with content (0 bytes).

**Comment by stijn-volckaert** [comment]
Would you mind coming over to our Discord server so we can try a few test builds?

**Comment by MLipfert1** [comment]
I will do that 👍

**Comment by MLipfert1** [comment]
This issue has been fixed in version 469c-RC4.
