### ISSUE TITLE
[469c-RC2] Wizard dialog for select mouse input hangs

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#947]
Reproduce:
1. Start `UnrealTournament.exe -changevideo -forceflush`
2. Select D3D9 (not matter). And press next.
3. Click on any place of mouse input type selection listbox.

Expected result: Wizard not hangs.
Actual result: Wizard hangs, not respond to any clicks.

**Comment by SeriousBuggie** [comment]
Workaround:
1. Not click on list box. Press `Next`.
2. Set desired options in game:
![img](https://user-images.githubusercontent.com/70026933/180599924-c2d9d6b8-517f-4f99-b7ff-66675f368dd8.png)
![img](https://user-images.githubusercontent.com/70026933/180599938-7f0357c2-4cdd-44dd-bf4f-f57339559d4c.png)

**Comment by unrealtitle99** [comment]
I can also confirm this bug and that the workaround does work.

**Comment by stijn-volckaert** [comment]
The fix will be included in RC3

**Comment by stijn-volckaert** [comment]
The fixed version is now available
