### ISSUE TITLE
Unplayable with oldskool amp enable

### ISSUE THREAD

**Issue by VirgileVILE** [OldUnreal/UnrealTournamentPatches#95]
Why did you make this patch incompatible with the oldskool amp? Did you think it would be funny to ruin my setup?
I can no longer use my game without having to deactivate the oldskool in unrealtournament.ini!
Yeah I'm talking about the game menu which is totally invisible when you enable Oldskool, making it impossible to navigate the menus and play single player mods, how, couldn't you test this extremely used mod ?!

**Comment by stijn-volckaert** [comment]
Which version of oldskool are you using? I have been testing 469 with oldskool 2.39 for nearly a year now and the only issue I'm aware of is that it keeps restarting the menu music when you're playing regular UT games. This issue was also present in 436, however.

**Comment by VirgileVILE** [comment]
I have Oldskool 2.39 ...
Don't tell me i have a bug that no one else has and is supposed to have? -_-'

**Comment by stijn-volckaert** [comment]
Since you're the first one reporting issues with oldskool, that might indeed be the case. Could you start your game, enable oldskool, exit, and then upload oldskool.ini and UnrealTournament.log?

**Comment by VirgileVILE** [comment]
I wrongly accused the developers and I apologize. (My personal problems do not excuse my behavior to see evil everywhere.)

It seems that the problem comes from Oldskool at the level of the line "LookAndFeelClass =" which got stuck on AirFightUT, AirFightUT which seems incompatible with this patch.

**Comment by stijn-volckaert** [comment]
Okay. That makes sense. I'm going to close this one for now. Feel free to open another ticket if you want us to look into AirFight.
