### ISSUE TITLE
[469c-RC2] Resolution reset when switching Renderers

### ISSUE THREAD

**Issue by chris-mcc** [OldUnreal/UnrealTournamentPatches#951]
I've been testing a few different renderers and have noticed that when I'm on say Xopengl and go back to the vulkan renderer when coming back to XopenGL it resets the resolution to 1080p instead of the 1440p it was at.

Then on the XopenGL when I set the correct resolution and start a match the fps is 23/24 fps instead of the usual 135 fps until I shutdown the game and startup again.

**Comment by an-eternity** [comment]
Confirmed. Full screen resolution resets to lower resolution each time on render device switch.
Also, windowed resolution previously saved in `WindowedViewportX` and `WindowedViewportY` in `[WinDrv.WindowsClient]` appears also reset to that new resolution.

If switched to Direct3D 9 render device and then try to restore full screen resolution to normal from menu, it restores and shows up a confirmation dialog which can not be used as mouse X-axis control appears blocked (issue 284), to click the button in that confirmation dialog player switches into windowed mode and gets this crash in that moment:

```
Log: Enter SetRes()
Critical: appError called:
Critical: EndScene failed
Critical: Windows GetLastError: Not enough memory resources are available to process this command. (8)
Exit: Executing UObject::StaticShutdownAfterError
Exit: Executing UWindowsClient::ShutdownAfterError
DevMusic: Unregister music: Music utmenu23.utmenu23
DevMusic: glxStopMusic music: Music utmenu23.utmenu23
Exit: UGalaxyAudioSubsystem::ShutdownAfterError
Log: DirectDraw End Mode
Exit: UD3D9RenderDevice::ShutdownAfterError
Critical: UD3D9RenderDevice::Unlock
Critical: UViewport::Unlock
Critical: UWindowsViewport::Unlock
Critical: UGameEngine::Draw
Critical: UWindowsViewport::Repaint
Critical: UWindowsClient::Tick
Critical: ClientTick
Critical: UGameEngine::Tick
Critical: UpdateWorld
Critical: MainLoop
Exit: Exiting.
```

**Comment by stijn-volckaert** [comment]
Confirmed. This will be fixed in 469c RC3

**Comment by stijn-volckaert** [comment]
The fixed version is now available
