### ISSUE TITLE
[469c-RC2] OpenGL Colors seem to be off in Tactical Ops

### ISSUE THREAD

**Issue by guitronimo** [OldUnreal/UnrealTournamentPatches#953]
I hope this shows up in the images. 
One is taken from 469b and the other from 469c both with open GL Renderer and as far as possible exactly same settings, nothing unusual. Brighness setting is same for both at full brightness. 

Image 2  is taken from 469C RC2. Some parts ingame, especially red colored ones become a pinkish teint to them. So the laserdot of guns for example. Allthough at first look it had a wow effect to it, i would like to either have it switchable or back to defaults. In my eyes there is some gamma problem possibly?! 

In XopenGL all look fine, unfortunately there is an issue with that. I open a separate issue for that. 

![OpenGL469b](https://user-images.githubusercontent.com/78565208/180645606-afdebdd1-1e28-405c-90ad-297a70f07a1c.png)
![OpenGL469C](https://user-images.githubusercontent.com/78565208/180645604-1e2f7829-03a0-4f26-a701-193a44577155.png)

Here are my settings 469b
```
[OpenGLDrv.OpenGLRenderDevice]
DetailTextures=True
UseTrilinear=True
LODBias=0.000000
UseMultiTexture=True
UsePalette=True
UseAlphaPalette=False
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
MaxAnisotropy=16
AlwaysMipmap=False
UsePrecache=True
SupportsLazyTextures=0
ZRangeHack=True
AAFilterHint=0
NoAATiles=True
NumAASamples=2
UseAA=True
RequestHighResolutionZ=True
MaskedTextureHack=True
SmoothMaskedTextures=False
SceneNodeHack=False
FrameRateLimit=300
SwapInterval=1
UseVertexProgram=False
UseMultiDrawArrays=False
DynamicTexIdRecycleLevel=100
UseSSE2=False
UseSSE=True
BufferTileQuads=False
BufferClippedActorTris=True
SinglePassDetail=False
SinglePassFog=True
ColorizeDetailTextures=False
DetailClipping=False
UseDetailAlpha=True
DetailMax=0
RefreshRate=144
MaxTMUnits=0
NoFiltering=False
NoMaskedS3TC=False
Use16BitTextures=False
AutoGenerateMipmaps=False
ShareLists=False
UseZTrick=False
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.000000
DescFlags=0
Description=
ShaderMasking=True
ShaderType=SHADER_ARB
UseLightmapAtlas=True
UseShaderGamma=False
ShaderGammaCorrectHUD=False
UseDrawGouraud469=True
ShaderAlphaHUD=True
UseHDTextures=True
UseSamplerObjects=False
```
Here are my Settings 469C
```

[OpenGLDrv.OpenGLRenderDevice]
DetailTextures=True
UseTrilinear=True
LODBias=0.000000
UseMultiTexture=True
UsePalette=True
UseAlphaPalette=False
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
MaxAnisotropy=16
AlwaysMipmap=False
UsePrecache=True
SupportsLazyTextures=0
AAFilterHint=0
NoAATiles=True
NumAASamples=2
UseAA=True
MaskedTextureHack=True
SmoothMaskedTextures=False
FrameRateLimit=300
SwapInterval=1
UseVertexProgram=False
UseMultiDrawArrays=False
DetailClipping=False
UseDetailAlpha=True
DetailMax=0
RefreshRate=144
Use16BitTextures=False
AutoGenerateMipmaps=False
ShareLists=False
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.000000
DescFlags=0
Description=
UseLightmapAtlas=True
UseShaderGamma=False
UseDrawGouraud469=True
ShaderAlphaHUD=True
UseHDTextures=True
SmoothMasking=True
ColorCorrectionMode=UseFramebuffer
ContextType=AutoDetect
UseStaticGeometry=False
ForceNoSmooth=False
```

**Comment by sn260591** [comment]
Try with `ColorCorrectionMode=UseGammaRamp`

**Comment by guitronimo** [comment]
> Try with `ColorCorrectionMode=UseGammaRamp`

Unluckily this does not solve the issue. Its getting worse there. It only darkens the actual game but transparent HUD Elements stay as they are. Also with GammaRamp the brightness doesnt work anymore which i suppose is a bug on its own. 

![Shot00122](https://user-images.githubusercontent.com/78565208/180657022-19ae771a-dd89-481d-aa68-fa3644a19e66.png)

**Comment by CacoFFF** [comment]
Try:
ColorCorrectionMode=InShader

**Comment by guitronimo** [comment]
This issue seems to be regardless of the CollorCorrectionMode. All three settings have this issue. 
Maybe it helps looking at the codes here. 


Scoreboard Player Background
```
	// background
	if (pri.Team < 2)
	{
		Canvas.SetPos(MyX+2, ypos);
		//Canvas.Style = OwnerInterface.ERenderStyle.STY_Normal;
		Canvas.Style = OwnerInterface.ERenderStyle.STY_Translucent;
		
		if(TOPRI!=none){
			if(TOPRI.bTOPlayerReady)
			{
				Canvas.DrawColor = OwnerInterface.Design.ColorTeam[pri.Team] * colormod;
			} else {
				Canvas.DrawColor =  OwnerInterface.Design.ColorDarkgrey;
			}
		} else {
			Canvas.DrawColor = OwnerInterface.Design.ColorTeam[pri.Team] * colormod;
		}
		Canvas.DrawTile(Texture'tilewhite', Width/2-3, BoxHeight, 0, 0, 16.0, 16.0);
	}
```
Colormod is either 0.4 or 0.7 so no exessive overdrive (if even possible)

The DesignInfo:
```
	ColorTeam(0)=(R=229,G=60,B=60)
	ColorTeam(1)=(R=90,G=160,B=229)
	ColorTeam(2)=(R=229,G=229,B=46)
	ColorTeam(3)=(R=160,G=160,B=160)
```

I am not entirely sure if this is really a an issue although it looks terrible, i would not wonder if back in the day the designers modified numbers until it fit. The problem is just that now the contrast is broken between Text and color, not that it was good before.

**Comment by guitronimo** [comment]
Yeah that fixed it. Thanks. I was sure i had checked for Alpha. I noticed that sometimes settings do require restart (at least some) Maybe i became confused at some point. 
Thanks!

**Comment by CacoFFF** [comment]
For a description on the option, what it does is turn usual UT transparency (additive) into hacky alpha transparency.
Makes the colors more vivid, but at the same time they're able to be displayed on top of bright pixels, one ideal use case is for being able to see the UT hud and crosshair when aiming at very bright surfaces/lights such as the world in CTF-Face.

**Comment by guitronimo** [comment]
Yeah i thought there would be some sense behind this. It just lead into confusion because of the terrible choice of teamcolors within Tactical Ops. It was always hard to read especially in bright maps and then suddenly almost impossible to figure any letter in the scoreboard. 

Working well now! Still think about tweaking teamcolors to match that option, gives it a new polish.
