### ISSUE TITLE
[469c RC2] UT crash on `UALAudioSubsystem::Update`

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#956]
Reproduce:
1. Open in UnrealEd map: [DM-Manhunter](https://unrealarchive.org/maps/unreal-tournament/deathmatch/M/dm-manhunter_ea26d0bd.html)
2. Press Play button.

Expected result: Game start play.
Actual result: Game crash:
```
General protection fault!

History: UALAudioSubsystem::Update <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- 
ClientTick <- UGameEngine::Tick
SE(C0000005) @ 0F73C895
fl=0 rec=0 n=19785036 i[0]=0 i[1]=48
eax=00000000 ebx=045f9e04 ecx=d09cc2a0 edx=0cda5575 esi=0fe04b10 edi=0d48a6f4 eip=0f73c895
ebp=012dec18 esp=012dea00 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010216
 <- UpdateWorld <- MainLoop
```

Audio: OpenAL.

v469b work fine.
Cluster, Galaxy - work fine.

**Comment by SeriousBuggie** [comment]
If run UT normally and type on console `start autoplay` - map load fine.

**Comment by SeriousBuggie** [comment]
I use this [Blank.umx](https://github.com/OldUnreal/UnrealTournamentPatches/files/9176123/Blank.zip)
Not which come in archive.

**Comment by stijn-volckaert** [comment]
The fix will be included in RC3
