### ISSUE TITLE
[469c-RC2] Ued - Texture properties issues in texture browser

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#959]
Here is a quick example id like to show about an issue with the texture browser in 469c compared to 469b.
When importing textures (for this example: png), 469c Ued generates really long property name:
![Screenshot_24](https://user-images.githubusercontent.com/58362332/180670794-45bdd9a1-01b8-4a40-9446-0423aa4a193e.png)

This creates a lot of issues, where the texture browser does not align the texture previews, it is spacing them with a very big distance. 469c import test:
![Screenshot_23](https://user-images.githubusercontent.com/58362332/180671135-a4f2afa7-68d0-4c1b-94ea-dc585a4e596a.png)

Here is a comparison with 469b import, property names are shorter and look a lot better:
![Screenshot_26](https://user-images.githubusercontent.com/58362332/180671188-8baa57fd-731a-459c-8e82-01e145561d94.png)

It would be great if we could revert to the shorter property names just like we had it in 469b

**Comment by SeriousBuggie** [comment]
Suggestion move compmips info to second line:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/c6058bfa-3907-4743-a527-b9a21038f39e)
