### ISSUE TITLE
[469a][UEd] Missing buttons

### ISSUE THREAD

**Issue by Dr-Flay** [OldUnreal/UnrealTournamentPatches#96]
So busy looking at the configs and menus I forgot to look at the main interface.
Some buttons are missing and 1 is in the wrong place.
(EXE Installer used with GoG edition)
![UEd-buttons](https://user-images.githubusercontent.com/43873202/95401496-43170280-0905-11eb-88d2-bced8adf2e1a.jpg)

**Comment by stijn-volckaert** [comment]
![afbeelding](https://user-images.githubusercontent.com/10390414/95462647-12bc7c00-0978-11eb-853a-b8ebdc256081.png)
Can you check your UT/System/edittorres folder? Do you have all of these bitmaps in there?

**Comment by Dr-Flay** [comment]
![UEd-buttons](https://user-images.githubusercontent.com/43873202/95647661-27f4f000-0ac9-11eb-99d9-ddd4affa996c.jpg)

**Comment by stijn-volckaert** [comment]
This was a bug in the installer script. Will be fixed in 469b.
