### ISSUE TITLE
[469c-RC2] Small font in TeamScoreBoard

### ISSUE THREAD

**Issue by Reorn** [OldUnreal/UnrealTournamentPatches#960]
Class TeamScoreBoard, Line 60
`Canvas.Font = font'SmallFont';`
This line calls the font 'SmallFont' directly from the file 'Engine.u '
This font is very small and has no Unicode letters.
Need a scalable font, as exsample, MyFonts.GetSmallestFont( Canvas.ClipX );

Also, Engine.SmallFont does not visible in some localizations - it is advisable to replace it with font from external file.
Or font replacement feature, as Unreal 227i / 227j
![1](https://user-images.githubusercontent.com/108881415/180731020-dc65a548-382f-4863-a8c7-d7c7ec5d1e9f.jpg)
![2](https://user-images.githubusercontent.com/108881415/180731995-83eb510d-1f76-493c-a91e-50ff7af758c3.jpg)

**Comment by SeriousBuggie** [comment]
For my FHD screen without scaling I got next sizing:
- original
![scr_1658768872](https://user-images.githubusercontent.com/70026933/180835979-85e59c29-d198-453a-b004-17a28af7527a.png)

- GetAReallySmallFont
![img](https://user-images.githubusercontent.com/70026933/180836168-5ed79a00-5f76-4282-8f25-5a2c39761bf7.png)

- GetSmallestFont
![изображение](https://user-images.githubusercontent.com/70026933/180836262-1493147f-b9fc-4e1d-9d1e-6a4b571f8a56.png)

So it must be GetAReallySmallFont

**Comment by Luvbrothel** [comment]
I've got tiny menu fonts I can't read and giant loading fonts.  It's all whack.

**Comment by stijn-volckaert** [comment]
469d should fix both problems. No ETA on the first testing builds yet, though
