### ISSUE TITLE
[469c-RC2] Dedicated server - unable to save map rotation

### ISSUE THREAD

**Issue by gen-angry** [OldUnreal/UnrealTournamentPatches#961]
Hello,

I have the latest 469c-RC2 (x86) installed in a ubuntu server 2204 VPS. When I try to set a custom map rotation under "Defaults -> Map List", it will not save this rotation in the ini causing it to revert back to the default settings after restarting (and sometimes at random, ie: changing game modes).

**Steps to reproduce:**
Go to `\root?Group=defaults` page.
Set a custom map rotation for DM.
Go to `root?Group=current` page.
Set server to DM and see map list. Custom map rotation is there.
Set server to whichever map.
Close admin page. 
Restart server.
Reopen admin page.
Set server to DM if not already there and see map list. Map rotation is back to defaults.

With 469b, it would save the maplist (first 32 maps) under `[Botpack.TDMmaplist]` in `UnrealTournament.ini`. With 469c-RC2, it does not.

Other settings such as bots, etc all save and update in the ini correctly.

**Expected behaviour:** 
Custom map rotation would save after editing as it shows up in the current maplist after immediately changing.

Maybe add a manual 'save custom maplist' button?

Thanks :)

Edit to add: after playing on it a bit, it seems to save the rotation after a map has been played through once on the intended mode and it's successfully changed the map on it's own. But only for that intended mode so if an admin wishes to save a maplist for all modes, every mode would have to be played at least once. Any changes afterwards will require a map playthrough to save as well.

**Comment by SeriousBuggie** [comment]
Confirmed.
