### ISSUE TITLE
[469c-RC2] Dedicated server - Firefox pops up resend confirmation after map change

### ISSUE THREAD

**Issue by gen-angry** [OldUnreal/UnrealTournamentPatches#962]
**Steps to reproduce:**
Log into web admin panel. 
Change map, doesn't matter which.
After the countdown, Firefox will pop up a dialog:
![image](https://i.imgur.com/bRjqJMd.png)
Clicking `refresh` repeats the last action. Clicking `cancel` causes it to fail to load the map list.

**Expected behaviour:** no dialog, goes back into maplist. 

Does not do it with 469b.

**Comment by SeriousBuggie** [comment]
Confirmed.
