### ISSUE TITLE
[469b/469c-RC2] Rendering performance regression

### ISSUE THREAD

**Issue by chris-mcc** [OldUnreal/UnrealTournamentPatches#963]
It seems like 469B introduced a performance regression for 432 renderdevices.

https://github.com/dpjudas/UT99VulkanDrv/issues/2 details that when trying to achieve the fastest fps perf is taking a hit in 469B but perf was as expected in 469A.

Another player playing map https://www.unrealsp.org/forums/viewtopic.php?f=4&t=4681

Sees a drop to 9 fps from 20 fps with XopenGL when running 469C RC2.

**Comment by stijn-volckaert** [comment]
For best performance, vulkandrv should be rebuilt with 469c's SDK. We'll talk to dpjudas

**Comment by stijn-volckaert** [comment]
For VulkanDrv, the 2.0 release should fix these performance issues.
As for XOpenGLDrv: we fixed a few performance issues (mostly for Intel GPU users) between 469c-RC2 and the 469c release version. Could you check if the problems are fixed on your end?
