### ISSUE TITLE
[469c-RC2] Badlands HUD is broken

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#967]
Hello,

I've just tried the mod Badlands on 469c-RC2. Unfortunately most of the HUD is not showing up and the weapons don't seem to work either (or maybe i just don't see what i have selected and clicking with a knife or so).

Singleplayer on 469c-RC2 works good.
![UnrealTournament_KjFrUsJ84v](https://user-images.githubusercontent.com/22099136/181048370-83a3f939-8430-40b1-a251-a749b7be7ed6.jpg)

Multiplayer, 469b client on 469b server works good.
![UnrealTournament_Ae1pxjjNXs](https://user-images.githubusercontent.com/22099136/181048450-ff64c994-b2e3-4c5a-bb82-360d77a0d462.jpg)

Multiplayer, 469c-RC2 client on 469c-RC2 server is broken.
![UnrealTournament_QA75lT1FPY](https://user-images.githubusercontent.com/22099136/181048486-337808c4-9620-45cd-b920-89e49620d046.jpg)

My 469c-RC2 install is an exact copy of 469b with the patch installed over it, so the ini and all the files (except the patched ones) are identical.

This is the server log file (hopefully you can see something through all the messages of the extra mods i have on)
[badlands-multiplayer-on-v469c-rc2-log.txt](https://github.com/OldUnreal/UnrealTournamentPatches/files/9191163/badlands-multiplayer-on-v469c-rc2-log.txt)

Maybe this has something to do with it?
`Failed to load "Texture TexxSkins.1": Object not found: Texture TexxSkins.1.`

I think for debugging it would be necessary that one of the developers installs this mod to debug the issue.

Link: https://www.moddb.com/mods/unreal-badlands1/downloads

Thanks for helping out!

**Comment by Engineer9736** [comment]
469c-RC2 client on 469b server is functional.
469b client on 469c-RC2 server is broken.

So it seems to be a server issue in 469c-RC2.

**Comment by SeriousBuggie** [comment]
Need exact version of Badland where such problem appear. v110 or v120?

**Comment by SeriousBuggie** [comment]
I check on BadLand v120. Can for sure say this mod badly written. It alter canvas property.
Label must be on left side. Dot must be at screen center.
![scr_1658862122](https://user-images.githubusercontent.com/70026933/181091015-94c2fcff-d047-4ec3-aefb-b2a71471f9c2.png)
Nexgen message broken (first attempt run server be with nexgen).
![scr_1658862106](https://user-images.githubusercontent.com/70026933/181091022-c2045cb1-adde-4c7b-b650-d8a3b3f7a804.png)
Also with nexgen I able start game by press fire and spawn with weapons.
Only first time. reconnect goes as on your screen.
Without nexgen you not able start game at all.

**Comment by Engineer9736** [comment]
Thanks for checking! I also noticed that the entire chat sometimes sits at like a quarter into the screen horizontally, probably the same issue as you’re seeing on your first screenshot. I hope it will be possible to get it to work with some minor tweaking.

Otherwise Badlands would have to be rewritten of which i doubt that that will become a success, if i’m at it at least. Or i would have to stick to 469b which would be a waste of all the amazing improvements of 469c.

I’ll check back on any further updates on this issue tomorrow.

**Comment by SeriousBuggie** [comment]
This happen because PlayerRestartState set to PickLoadout during WantedGame.Login. After call super.
But some how it reset to PlayerWalking. So later Player goes to State PlayerWalking, instead of PickLoadout.
So when client choose loadout (item in weapon selection window) it called on server Global.SelLoadout, not from state PickLoadout.SetLoadout. Global function almost do nothing. No get you weapon and other.

This is current state of investigation. Why PlayerRestartState change to PlayerWalking I not figure yet.

**Comment by SeriousBuggie** [comment]
Current workaround, run on server this two commands:
```
set BadMale PlayerRestartState PickLoadout
set TexX PlayerRestartState PickLoadout
```
It can be even easy mutator which set defaults:
```unrealscript
class'BadMale'.default.PlayerRestartState = 'PickLoadout';
class'TexX'.default.PlayerRestartState = 'PickLoadout';
```

Since this fix work, obviously some where called such code:
`NewPlayer.PlayerRestartState = NewPlayer.Default.PlayerRestartState`

**Comment by SeriousBuggie** [comment]
Found reason.
```unrealscript
function StartWalk()
{
    local ENetRole OldRole;
	
	UnderWaterTime = Default.UnderWaterTime;
	SetCollision(true, true , true);
	SetPhysics(PHYS_Walking);
	bCollideWorld = true;
	ClientReStart();

	// OldUnreal fix: ClientReStart only runs on the client side if we call this on a dedicated server
	// The server _tries_ to call the function, but ProcessRemoteFunction absorbs the call because RemoteRole==ROLE_AutonomousProxy
	// This horrible hack ensures the server also calls ClientReStart so the client and server sync up
	//
	// Without this fix, the player gets stuck in state CheatFlying and PHYS_Falling when switching from ghost/fly to walk
    if ( NetConnection(Player) != None )
    {
        OldRole = RemoteRole;
        RemoteRole = ROLE_None;
        ClientReStart();
        RemoteRole = OldRole;
    }
}
```
On first call `ClientReStart();` PlayerPAwn goes to state `PickLoadout`.
On this state defined next code:
```unrealscript
      event BeginState()
      {
      		//log("Entering PickLoadout: "$Level.NetMode );
		Mesh= None;

		if ( PlayerReplicationInfo != None )
		{
			PlayerReplicationInfo.bIsSpectator = true;
			PlayerReplicationInfo.bWaitingPlayer = true;
		}

		bDidChooseLoadout = False;
		EyeHeight = BaseEyeHeight;
		SetCollision( false, false, false );
		SetPhysics( PHYS_None );
            	PlayerRestartState=default.PlayerRestartState;

		// If we are on the server show the loadout selectionwindow
		if ( Role == ROLE_Authority )
		{
			ShowLoadoutSelectionMenu();
		}
      }
```
So it reset `PlayerRestartState=default.PlayerRestartState;` back to defaults.

And there on v469c we call PlayerRestartState second time. And this switch PlayerPawn to State PlayerWalking, which is default.
On v469b we call it only once `ClientReStart();` so this is fine.

**Comment by SeriousBuggie** [comment]
Much better workaround: type `suicide` after enter to game.

**Comment by SeriousBuggie** [comment]
So problem there in next:
Fix is right, but exist edge case. When player not still logged in, NetConnection(Player) != None, but all calls still not suppressed. So it call `ClientReStart` twice. So I think need more fine tune for second call and problem gone.

**Comment by SeriousBuggie** [comment]
`log(Player @ NetConnection(Player) @ GetPropertyText("RemoteRole") @ GetPropertyText("Role") @ RemoteRole @ Role);`
On login:
`ScriptLog: Transient.TcpipConnection2 Transient.TcpipConnection2 ROLE_SimulatedProxy ROLE_Authority 2 4`
After:
```
admin fly
admin walk
```
`ScriptLog: Transient.TcpipConnection2 Transient.TcpipConnection2 ROLE_AutonomousProxy ROLE_Authority 3 4`
So RemoteRole must be check against ROLE_AutonomousProxy.

**Comment by Engineer9736** [comment]
Thanks for the research! I'll check out the solutions coming evening (over like 10 hours or so) 👍

**Comment by stijn-volckaert** [comment]
I've merged the fix for RC3

**Comment by stijn-volckaert** [comment]
The fixed version is now available
