### ISSUE TITLE
[469c-RC2] Quick console does not remember history

### ISSUE THREAD

**Issue by guitronimo** [OldUnreal/UnrealTournamentPatches#970]
Usual players wont notice this but when you do alot of admin commands the best ever implemented function was to be able to switch between the commands you already entered with arrow keys up and down. 

In 469c RC2 i experience that this sometimes works but most of the time it doesnt. 

In the console window however everything seems to work fine.

**Comment by SeriousBuggie** [comment]
You need specify exact test case. I check now - for me it work fine. So need specific test case (step-by-step) on which it work not as expected.

Please fill it in form:
- Reproduce steps.
- Expected result.
- Actual result.

**Comment by guitronimo** [comment]
I literally just do this: 
- Start game
- Quick Console
- Type 1234
- Enter
- Quick Console
- Arrow Up 
-> No history 

I found the issue and fixed for now but i dont know what causes this. 

In the UnrealTournament.ini appears to be this section, obviously HistoryTop, Bot and Cur are wrong:
```
[Engine.Console]
HistoryTop=103
HistoryBot=102
HistoryCur=102
History[0]=say Working great for me
History[1]=preferences
History[2]=endround
History[3]=preferences
History[4]=say Lets test that spot again
History[5]=rwer
History[6]=Say where?
History[7]=Say hard time for terrorists nowadays
History[8]=Say !v
History[9]=scopemode
History[10]=admin set TOST43.TOST_SWATGame bExtendedHitboxes false
History[11]=admin set TOST43.TOST_SWATGame bExtendedHitboxes true
History[12]=admin set TOST43.TOST_SWATGame bExtendedHitboxes true 0.75
History[13]=Say in 3.4 it would have been hossie headshot xD
History[14]=say upss sorry
History[15]=admin set TOST43.TOST_SWATGame bTraceProjectiles true 20
```

**Comment by SeriousBuggie** [comment]
It use cyclic buffer. Such numbers is normal. For me it
```
HistoryTop=10970
HistoryBot=10985
HistoryCur=10984
```
And your test case is work for me fine,

**Comment by SeriousBuggie** [comment]
HistoryTop must be always smaller from HistoryBot. In your setting it is somehow bigger.
So this mean no history. So if you press UP it not work.
After you type strings and type enter it goes to normal state, when HistoryTop behind.

IDK how you get bad state, but stock code look like work normally.
Possible it is your mods screwed settings of console.

**Comment by SeriousBuggie** [comment]
WindowConsole extends Console and use same stuff in 3 different places. In fact there copy of same code.
Which not used by stock code. But can be used for other code.

And yes. History preserved only starting from v469.
