### ISSUE TITLE
[469c-RC2] XOpenGLDrv menu corruption

### ISSUE THREAD

**Issue by uralets** [OldUnreal/UnrealTournamentPatches#971]
Corruption at monitor's native 3840x2160 or at 1920x1080
227j - current Git. XOpenGL.
Linux x86_64. Xorg. No compositing.
Ubuntu 22.04. Kernel 5.18.3-051803-generic. Mesa 22.1.2. LLVM 14 (kisak PPA).
![Снимок экрана в 2022-07-27 09-13-30](https://user-images.githubusercontent.com/45916341/181161155-c7afc5aa-b14a-45cf-b846-7ee34063bb92.png)
![Снимок экрана в 2022-07-27 09-12-02](https://user-images.githubusercontent.com/45916341/181161178-23962711-0b48-45d0-b6e2-2adf5e05b2e7.png)

The same issue with Unreal 227j https://github.com/OldUnreal/Unreal-testing/issues/260

<details>
[URL]
Protocol=unreal
ProtocolDescription=Unreal Protocol
Name=Player
Map=Index.unr
LocalMap=CityIntro.unr
Host=
Portal=
MapExt=unr
SaveExt=usa
Port=7777
Class=Botpack.TMale1

[FirstRun]
FirstRun=469

[PackageRemap]
UnrealShare=UnrealI

[Engine.Engine]
GameRenderDevice=XOpenGLDrv.XOpenGLRenderDevice
AudioDevice=Cluster.ClusterAudioSubsystem
NetworkDevice=IpDrv.TcpNetDriver
DemoRecordingDevice=Engine.DemoRecDriver
Console=UTMenu.UTConsole
Language=int
GameEngine=Engine.GameEngine
EditorEngine=Editor.EditorEngine
WindowedRenderDevice=OpenGLDrv.OpenGLRenderDevice
RenderDevice=OpenGLDrv.OpenGLRenderDevice
DefaultGame=Botpack.DeathMatchPlus
DefaultServerGame=Botpack.DeathMatchPlus
ViewportManager=SDLDrv.SDLClient
Render=Render.Render
Input=Engine.Input
Canvas=Engine.Canvas
CdPath=G:

[Core.System]
PurgeCacheDays=30
SavePath=../Save
CachePath=../Cache
CacheExt=.uxx
Paths=../System/*.u
Paths=../Maps/*.unr
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Suppress=DevLoad
Suppress=DevSave
Suppress=DevNetTraffic
Suppress=DevGarbage
Suppress=DevKill
Suppress=DevReplace
Suppress=DevSound
Suppress=DevCompile
Suppress=DevBind
Suppress=DevBsp
Suppress=DevMD5
Suppress=DevAudio
Suppress=DevMusic

[Engine.GameEngine]
CacheSizeMegs=16
UseSound=True
MinClientVersion=432
MD5PostJoinCheck=true
ServerActors=IpDrv.UdpBeacon
ServerActors=IpServer.UdpServerQuery
ServerActors=IpServer.UdpServerUplink MasterServerAddress=unreal.epicgames.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.mplayer.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.333networks.com MasterServerPort=27900
ServerActors=UWeb.WebServer
ServerPackages=SoldierSkins
ServerPackages=CommandoSkins
ServerPackages=FCommandoSkins
ServerPackages=SGirlSkins
ServerPackages=BossSkins
ServerPackages=Botpack
ServerPackages=MultiMesh
ServerPackages=Relics
ServerPackages=EpicCustomModels
ServerPackages=TCowMeshSkins
ServerPackages=TNaliMeshSkins
ServerPackages=TSkMSkins
ServerPackages=De

[WinDrv.WindowsClient]
WindowedViewportX=1024
WindowedViewportY=768
WindowedColorBits=32
FullscreenViewportX=1024
FullscreenViewportY=768
FullscreenColorBits=32
Brightness=0.500000
MipFactor=1.000000
UseDirectDraw=True
UseJoystick=False
CaptureMouse=True
StartupFullscreen=True
CurvedSurfaces=False
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
SlowVideoBuffering=True
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.0
ScaleRUV=2000.0
MinDesiredFrameRate=30.0
Decals=True
NoDynamicLights=False

[SDLDrv.SDLClient]
WindowedViewportX=1024
WindowedViewportY=768
WindowedColorBits=32
FullscreenViewportX=1920
FullscreenViewportY=1080
FullscreenColorBits=32
Brightness=0.500000
MipFactor=1.000000
UseJoystick=False
CaptureMouse=True
StartupFullscreen=True
CurvedSurfaces=False
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
SlowVideoBuffering=True
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.0
ScaleRUV=2000.0
MinDesiredFrameRate=30.000000
Decals=True
NoDynamicLights=False
MacNativeTextToSpeech=False
TextToSpeechFile=
MacKeepAllScreensOn=False
AllowCommandQKeys=False
AllowUnicodeKeys=False
IgnoreUngrabbedMouse=False
IgnoreHat=False
ScaleJBY=0.000000
ScaleJBX=0.000000
JoystickHatNumber=0
JoystickNumber=0
ParticleDensity=0
NoFractalAnim=False
FrameRateLimit=0.000000
SkinDetail=High
TextureDetail=High

[Engine.Player]
ConfiguredInternetSpeed=10000
ConfiguredLanSpeed=20000

[ALAudio.ALAudioSubsystem]
UseHRTF=Autodetect
ViewportVolumeIntensity=1.000000
DetailStats=False
ReverbIntensity=1.000000
UseReverb=True
OldReverbIntensity=1.000000
EmulateOldReverb=True
MusicAmplify=0
MusicStereoAngle=30
MusicStereoMix=70
MusicPanSeparation=50
MusicDsp=DSP_ALL
MusicInterpolation=SPLINE
ProbeDevicesOnly=False
UseAutoSampleRate=False
OutputRate=44100Hz
DopplerFactor=0.100000
bSoundAttenuate=True
AmbientFactor=0.700000
UseDigitalMusic=True
EffectsChannels=64
UseSpeechVolume=True
MusicVolume=0
SpeechVolume=208
SoundVolume=64
SampleRate=44100Hz
PreferredDevice=
DetectedDevices=CA0108/CA10300 [Sound Blaster Audigy Series] (SB1550 Audigy 5/Rx) Ð
DetectedDevices=Navi 21 HDMI Audio [Radeon RX 6800/6800 XT / 6900 XT] Digital Stereo (HDMI 2)

[Galaxy.GalaxyAudioSubsystem]
UseDirectSound=True
UseFilter=True
UseSurround=False
UseStereo=True
UseCDMusic=False
UseDigitalMusic=True
UseSpatial=False
UseReverb=True
Use3dHardware=False
LowSoundQuality=False
ReverseStereo=False
Latency=40
OutputRate=22050Hz
EffectsChannels=16
DopplerSpeed=9000.000000
MusicVolume=160
SoundVolume=200
AmbientFactor=0.700000

[IpDrv.TcpNetDriver]
AllowDownloads=True
ConnectionTimeout=15.0
InitialConnectTimeout=150.0
AckTimeout=1.0
KeepAliveTime=0.2
MaxClientRate=20000
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=50
LanServerMaxTickRate=50
DownloadManagers=IpDrv.HTTPDownload
DownloadManagers=Engine.ChannelDownload
MaxConnPerIPPerMinute=5
LogMaxConnPerIPPerMin=False
AllowPlayerPortUnreach=True
LogPortUnreach=False
MaxFileDownloadRate=-1

[IpDrv.HTTPDownload]
RedirectToURL=
ProxyServerHost=
ProxyServerPort=3128
UseCompression=True

[Engine.DemoRecDriver]
DemoSpectatorClass=Botpack.CHSpectator
MaxClientRate=25000
ConnectionTimeout=15.0
InitialConnectTimeout=500.0
AckTimeout=1.0
KeepAliveTime=1.0
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=60
LanServerMaxTickRate=60

[Engine.GameReplicationInfo]
ServerName=Another UT Server
ShortName=UT Server
AdminName=
AdminEmail=
Region=0
MOTDLine1=
MOTDLine2=
MOTDLine3=
MOTDLine4=

[IpDrv.TcpipConnection]
SimPacketLoss=0
SimLatency=0

[IpServer.UdpServerQuery]
GameName=ut

[IpDrv.UdpBeacon]
DoBeacon=True
BeaconTime=0.50
BeaconTimeout=5.0
BeaconProduct=ut

[SoftDrv.SoftwareRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=False
Coronas=False
HighDetailActors=False
HighResTextureSmooth=True
LowResTextureSmooth=False
FastTranslucency=True

[GlideDrv.GlideRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailBias=-1.500000
RefreshRate=60Hz
DetailTextures=True
FastUglyRefresh=False
ScreenSmoothing=True
Resolution=Default

[MetalDrv.MetalRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=False

[OpenGLDrv.OpenGLRenderDevice]
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=True

[D3DDrv.D3DRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
UseMipmapping=True
UseTrilinear=False
UseMultitexture=True
UsePageFlipping=True
UsePalettes=True
UseFullscreen=True
UseGammaCorrection=True
DetailTextures=False
Use3dfx=False
UseTripleBuffering=True
UsePrecache=True
Use32BitTextures=False

[SglDrv.SglRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=False
Coronas=True
HighDetailActors=False
ColorDepth=16
DetailTextures=False
FastUglyRefresh=False
TextureDetailBias=Near
VertexLighting=False

[Editor.EditorEngine]
UseSound=True
CacheSizeMegs=6
GridEnabled=True
SnapVertices=True
SnapDistance=10.000000
GridSize=(X=16.000000,Y=16.000000,Z=16.000000)
RotGridEnabled=True
RotGridSize=(Pitch=1024,Yaw=1024,Roll=1024)
GameCommandLine=-log
FovAngleDegrees=90.000000
GodMode=True
AutoSave=False
AutoSaveTimeMinutes=5
AutoSaveIndex=6
C_WorldBox=(R=0,G=0,B=107,A=255)
C_GroundPlane=(R=0,G=0,B=63,A=255)
C_GroundHighlight=(R=0,G=0,B=127,A=255)
C_BrushWire=(R=255,G=63,B=63,A=255)
C_Pivot=(R=0,G=255,B=0,A=255)
C_Select=(R=0,G=0,B=127,A=255)
C_AddWire=(R=127,G=127,B=255,A=255)
C_SubtractWire=(R=255,G=192,B=63,A=255)
C_GreyWire=(R=163,G=163,B=163,A=255)
C_Invalid=(R=163,G=163,B=163,A=255)
C_ActorWire=(R=127,G=63,B=0,A=255)
C_ActorHiWire=(R=255,G=127,B=0,A=255)
C_White=(R=255,G=255,B=255,A=255)
C_SemiSolidWire=(R=127,G=255,B=0,A=255)
C_NonSolidWire=(R=63,G=192,B=32,A=255)
C_WireGridAxis=(R=119,G=119,B=119,A=255)
C_ActorArrow=(R=163,G=0,B=0,A=255)
C_ScaleBox=(R=151,G=67,B=11,A=255)
C_ScaleBoxHi=(R=223,G=149,B=157,A=255)
C_Mover=(R=255,G=0,B=255,A=255)
C_OrthoBackground=(R=163,G=163,B=163,A=255)
C_Current=(R=0,G=0,B=0,A=255)
C_BrushVertex=(R=0,G=0,B=0,A=255)
C_BrushSnap=(R=0,G=0,B=0,A=255)
C_Black=(R=0,G=0,B=0,A=255)
C_Mask=(R=0,G=0,B=0,A=255)
C_WireBackground=(R=0,G=0,B=0,A=255)
C_ZoneWire=(R=0,G=0,B=0,A=255)
EditPackages=Core
EditPackages=Engine
EditPackages=Editor
EditPackages=UWindow
EditPackages=Fire
EditPackages=IpDrv
EditPackages=UWeb
EditPackages=UBrowser
EditPackages=UnrealShare
EditPackages=UnrealI
EditPackages=UMenu
EditPackages=Botpack
EditPackages=IpServer
EditPackages=UTServerAdmin
EditPackages=UTMenu
EditPackages=UTBrowser

[UMenu.UnrealConsole]
RootWindow=UMenu.UMenuRootWindow
UWindowKey=IK_Esc
ShowDesktop=True

[UMenu.UMenuMenuBar]
ShowHelp=True
GameUMenuDefault=UTMenu.UTGameMenu
MultiplayerUMenuDefault=UTMenu.UTMultiplayerMenu
OptionsUMenuDefault=UTMenu.UTOptionsMenu
ModMenuClass=UMenu.UMenuModMenu

[Botpack.ChallengeBotInfo]
Difficulty=1

[Botpack.DeathMatchPlus]
bNoviceMode=True
bHardCoreMode=True
bUseTranslocator=False
bCoopWeaponMode=False
MinPlayers=0
AirControl=0.350000
bChangeLevels=True
bMegaSpeed=False
bAltScoring=False
bTournament=False
NetWait=10
RestartWait=15
InitialBots=5

[Botpack.CTFGame]
bUseTranslocator=True
bCoopWeaponMode=True
GoalTeamScore=3

[Botpack.Domination]
bDumbDown=True
bUseTranslocator=True
bCoopWeaponMode=True
GoalTeamScore=100

[Botpack.Assault]
bUseTranslocator=False
bCoopWeaponMode=True

[Botpack.TeamGamePlus]
bBalanceTeams=True
GoalTeamScore=30.000000
bPlayersBalanceTeams=True
bNoTeamChanges=False
FriendlyFireScale=0.000000
MaxTeams=2
MaxTeamSize=16
FragLimit=30
TimeLimit=0
bMultiWeaponStay=True
bForceRespawn=False
bUseTranslocator=False
MaxCommanders=2
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0
bFixMultiWeaponBug=True
bFixFeignDeathZoomBug=True

[Engine.GameInfo]
bLowGore=False
bVeryLowGore=False
AdminPassword=
GamePassword=
bMuteSpectators=False
bNoCheating=True
bAllowFOV=False
bExternalBatcher=False
AutoAim=0.930000
GameSpeed=1.000000
MaxSpectators=2
MaxPlayers=16
ServerLogName=server.log
bLocalLog=False
bWorldLog=True
bBatchLocal=False
DemoBuild=0
DemoHasTuts=0
PlayerViewDelay=1.000000
PlayerSpeechDelay=0.300000
PlayerTauntDelay=2.000000
NoLockdown=1
bLogAdminActions=False
LoginDelaySeconds=0.000000
MaxLoginAttempts=0
ActionToTake=DO_Nothing
IPPolicies[0]=ACCEPT,*
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0
bFixMultiWeaponBug=True
bFixFeignDeathZoomBug=True

[UnrealShare.UnrealGameOptionsMenu]
bCanModifyGore=True

[UBrowser.UBrowserMainClientWindow]
LANTabName=UBrowserLAN
ServerListNames[0]=UBrowserUT
ServerListNames[1]=UBrowserLAN
ServerListNames[2]=UBrowserPopulated
ServerListNames[3]=UBrowserDeathmatch
ServerListNames[4]=UBrowserTeamGames
ServerListNames[5]=UBrowserCTF
ServerListNames[6]=UBrowserDOM
ServerListNames[7]=UBrowserAS
ServerListNames[8]=UBrowserLMS
ServerListNames[9]=UBrowserAll
ServerListNames[10]=None
ServerListNames[11]=None
ServerListNames[12]=None
ServerListNames[13]=None
ServerListNames[14]=None
ServerListNames[15]=None
ServerListNames[16]=None
ServerListNames[17]=None
ServerListNames[18]=None
ServerListNames[19]=None
ServerListNames[20]=None
ServerListNames[21]=None
ServerListNames[22]=None
ServerListNames[23]=None
ServerListNames[24]=None
ServerListNames[25]=None
ServerListNames[26]=None
ServerListNames[27]=None
ServerListNames[28]=None
ServerListNames[29]=None
ServerListNames[30]=None
ServerListNames[31]=None
ServerListNames[32]=None
ServerListNames[33]=None
ServerListNames[34]=None
ServerListNames[35]=None
ServerListNames[36]=None
ServerListNames[37]=None
ServerListNames[38]=None
ServerListNames[39]=None
ServerListNames[40]=None
ServerListNames[41]=None
ServerListNames[42]=None
ServerListNames[43]=None
ServerListNames[44]=None
ServerListNames[45]=None
ServerListNames[46]=None
ServerListNames[47]=None
ServerListNames[48]=None
ServerListNames[49]=None
bKeepMasterServer=False

[UBrowserUT]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserLAN]
ListFactories[0]=UBrowser.UBrowserLocalFact,BeaconProduct=ut
URLAppend=?LAN
AutoRefreshTime=10
bNoAutoSort=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserPopulated]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,MinPlayers=1,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserDeathmatch]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=DeathMatchPlus,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserTeamGames]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=TeamGamePlus,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserCTF]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=CTFGame,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserDOM]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=Domination,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserAS]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=Assault,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserLMS]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=LastManStanding,bCompatibleServersOnly=True
ServerListTitle=
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowserAll]
ListFactories[0]=UBrowser.UBrowserGSpyFact,MasterServerAddress=utmaster.epicgames.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[1]=UBrowser.UBrowserGSpyFact,MasterServerAddress=master.333networks.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[2]=UBrowser.UBrowserGSpyFact,MasterServerAddress=master.errorist.eu,MasterServerTCPPort=28900,Region=0,GameName=ut
bHidden=True
bFallbackFactories=True
ServerListTitle=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UTMenu.UTLadder]
bGOTY=true

[UWeb.WebServer]
Applications[0]=UTServerAdmin.UTServerAdmin
ApplicationPaths[0]=/ServerAdmin
Applications[1]=UTServerAdmin.UTImageServer
ApplicationPaths[1]=/images
DefaultApplication=0
bEnabled=False

[UBrowser.UBrowserHTTPClient]
ProxyServerAddress=
ProxyServerPort=

[UTServerAdmin.UTServerAdmin]
AdminUsername=admin
AdminPassword=admin

[UTMenu.UTConsole]
SpeechKey=86
SavedPasswords[0]=
SavedPasswords[1]=
SavedPasswords[2]=
SavedPasswords[3]=
SavedPasswords[4]=
SavedPasswords[5]=
SavedPasswords[6]=
SavedPasswords[7]=
SavedPasswords[8]=
SavedPasswords[9]=
RootWindow=UMenu.UMenuRootWindow
MouseScale=0.600000
ShowDesktop=True
bShowConsole=False
UWindowKey=IK_None

[UWindow.WindowConsole]
ConsoleKey=192

[Engine.Console]
HistoryTop=0
HistoryBot=0
HistoryCur=0
History[0]=
History[1]=
History[2]=
History[3]=
History[4]=
History[5]=
History[6]=
History[7]=
History[8]=
History[9]=
History[10]=
History[11]=
History[12]=
History[13]=
History[14]=
History[15]=

[Botpack.UTIntro]
CityIntroHUDClass=
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0
bFixMultiWeaponBug=True
bFixFeignDeathZoomBug=True

[UMenu.UMenuRootWindow]
ConfiguredGUIScale=1.000000
AutoGUIScale=True
LookAndFeelClass=UMenu.UMenuBlueLookAndFeel

[XOpenGLDrv.XOpenGLRenderDevice]
;UseBindlessTextures=False
SyncToDraw=False
UseVSync=On
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
NoBuffering=False
UseOpenGLDebug=False
UseHWClipping=False
UseHWLighting=False
UsePersistentBuffers=False
GenerateMipMaps=False
UseBufferInvalidation=False
NoAATiles=True
DetailTextures=True
MacroTextures=True
BumpMaps=True
GammaCorrectScreenshots=True
UseAA=True
UseTrilinear=True
UsePrecache=True
AlwaysMipmap=False
ShareLists=True
NoFiltering=False
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
MaxAnisotropy=4.000000
LODBias=0.000000
GammaOffsetScreenshots=0.700000
DebugLevel=2
NumAASamples=4
RefreshRate=0
DescFlags=1
OpenGLVersion=Core
Description=AMD Radeon RX 6600 XT (dimgrey_cavefish, LLVM 14.0.5, DRM 3.46, 5.18.3-051803-generic)
MaxBindlessTextures=4096
UseShaderDrawParameters=True
ParallaxVersion=None
SimulateMultiPass=False
UseLightmapAtlas=True
UseBindlessTextures=True
UseBindlessLightmaps=True
UseSRGBTextures=False
GammaMultiplierUED=1.000000
GammaMultiplier=1.000000
DetailMax=0

[Cluster.ClusterAudioSubsystem]
UseCDMusic=True
UseDigitalMusic=True
AudioDeviceGuid=
CDMusicVolumeFactor=1.000000
MusicVolume=160
SoundVolume=160
EffectsChannels=16
EmulateGalaxyMusic=True

[RocketArena.RocketArenaGame]
NewVoiceThemeName=RocketArena.RAVoiceMale
HUDTeamDisplay=1
Force1on1=False
ForceInstantRocketFire=False
DisallowSpectatorSpeech=False
BouncyHeight=2.250000
FallingDamage=False
PreferredPickupClass=Class'RocketArena.ArenaGame_Clan'
FragLimit=0
TimeLimit=20
bMultiWeaponStay=True
bForceRespawn=False
bUseTranslocator=False
MaxCommanders=0
bNoMonsters=True
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0
bFixMultiWeaponBug=True
bFixFeignDeathZoomBug=True

[UTMenu.UTMenuBotmatchCW]
Map=DM-Agony.unr
GameType=Botpack.TeamGamePlus
MutatorList=
bKeepMutators=False

[Botpack.TDMmaplist]
Maps[0]=DM-Codex.unr
Maps[1]=DM-turbine.unr
Maps[2]=DM-Phobos.unr
Maps[3]=DM-barricade.unr
Maps[4]=DM-Liandri.unr
Maps[5]=DM-Morpheus.unr
Maps[6]=DM-Gothic.unr
Maps[7]=DM-Tempest.unr
Maps[8]=DM-HyperBlast.unr
Maps[9]=DM-Grinder.unr
Maps[10]=DM-Kgalleon.unr
Maps[11]=DM-Zeto.unr
Maps[12]=DM-Pressure.unr
Maps[13]=DM-Conveyor.unr
Maps[14]=DM-Peak.unr
Maps[15]=DM-Curse][.unr
Maps[16]=DM-Deck16][.unr
MapNum=3

[UTBrowserFavoriteServers0]
ServerListTitle=
ListFactories[0]=UBrowser.UBrowserFavoritesFact
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[RABrowserWindow0]
ServerListTitle=Rocket Arena
ListFactories[0]=RocketArena.UBrowserModFact,GameType=RocketArenaGame,bCompatibleServersOnly=True,MasterServerAddress=master0.gamespy.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[RABrowserWindowAll0]
ServerListTitle=Rocket Arena: All Maps
ListFactories[0]=RocketArena.UBrowserModFact,GameType=AnyMapRocketArenaGame,bCompatibleServersOnly=True,MasterServerAddress=master0.gamespy.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[1]=
ListFactories[2]=
ListFactories[3]=
ListFactories[4]=
ListFactories[5]=
ListFactories[6]=
ListFactories[7]=
ListFactories[8]=
ListFactories[9]=
URLAppend=
AutoRefreshTime=0
bNoAutoSort=False
bHidden=False
bFallbackFactories=False
FilterString=
bNoEmpty=False
bNoFull=False
bNoLocked=False

[UBrowser.UBrowserIRCSetupClient]
IRCServerHistory[0]=irc.utchat.com
IRCServerHistory[1]=
IRCServerHistory[2]=
IRCServerHistory[3]=
IRCServerHistory[4]=
IRCServerHistory[5]=
IRCServerHistory[6]=
IRCServerHistory[7]=
IRCServerHistory[8]=
IRCServerHistory[9]=
IRCChannelHistory[0]=#utgames
IRCChannelHistory[1]=#utchat
IRCChannelHistory[2]=#utmods
IRCChannelHistory[3]=#utlevels
IRCChannelHistory[4]=#uthelp
IRCChannelHistory[5]=
IRCChannelHistory[6]=
IRCChannelHistory[7]=
IRCChannelHistory[8]=
IRCChannelHistory[9]=
bHasReadWarning=False
</details>

**Comment by sashaaaaaaaaa** [comment]
i get this with 469b

**Comment by stijn-volckaert** [comment]
Several other users have confirmed this bug. Unfortunately, none of our developers has an AMD card that suffers from this problem. I'll try to get my hands on an AMD card soon.

If you happen to be a C++ dev: XOpenGLDrv is now open source and included in the 469c SDK.

**Comment by uralets** [comment]
I aint a 3d dev, but I'll be happy to at least to try and look into this when I get around to it.

31 октября 2022 г. 19:58:53 GMT+05:00, stijn-volckaert ***@***.***> пишет:

**Comment by risusinf** [comment]
Had this on 469c with Ryzen 5300G embedded graphics, got it fixed by turning off "UseBindlessTextures"

**Comment by an-eternity** [comment]
> Had this on 469c with Ryzen 5300G embedded graphics

What was driver version for AMD graphics?

**Comment by risusinf** [comment]
> What was driver version for AMD graphics?

amdgpu shipped with 6.1.4 kernel

Garbled menu is reproducible by switching that "bindless" thing on and off.

There is also terrible texture flickering going on with in-game rendering, alas i coudnt get around that by tinkering with ini options. Had to go back to regular opengl, it works like a charm.

**Comment by stijn-volckaert** [comment]
Could anyone test if this still happens with the latest 469d previews? Come talk to us in Discord if you don't have access to preview builds

**Comment by stijn-volckaert** [comment]
This will be fixed in the next build
