### ISSUE TITLE
[469c-RC2] Random Crashes with OSX

### ISSUE THREAD

**Issue by digrizzle** [OldUnreal/UnrealTournamentPatches#978]
Hi, with a M1 MacBook Air running OSX 12.4 I'm getting random crashes whilst playing. I've attached the unreal tournament log and a screenshot of the error message.

<img width="518" alt="Screenshot" src="https://user-images.githubusercontent.com/86264262/181240550-a01de863-5ac9-49dd-ac1c-370c9b9dce55.png">

[UnrealTournament.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/9198348/UnrealTournament.log)

**Comment by stijn-volckaert** [comment]
Should be fixed in RC3

**Comment by digrizzle** [comment]
Yep, no issues to report, all good. Many thanks
