### ISSUE TITLE
[469c-RC2] Voices in player setup don't always play

### ISSUE THREAD

**Issue by chris-mcc** [OldUnreal/UnrealTournamentPatches#979]
I've noticed that if I launch UT99 and select a different voice it plays a taunt.

But if I'm mid game and decide to change the voice it does not play a taunt.

**Comment by OjitroC** [comment]
I think you need to describe in detail what steps you go through - the expected result and the actual result.

You mean that in the Main Game Menu you go to Options -> Player Setup and in the voice menu you left click/highlight a voice and an acknowledgement will play.  Once you start a map and then do the same thing, no acknowledgement plays? 

It doesn't for me in 469c but then it doesn't either in 436.

**Comment by chris-mcc** [comment]
Mm, yup, options -> player setup.

Could of swore it worked before.

Figured out I have to resume saved save touranment and return to player setup and it'll work.
