### ISSUE TITLE
[469a] Hide TO servers?

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#98]
Can all TO servers be hidden? UT can't join them, why not just hide them from the list?

**Comment by CacoFFF** [comment]
The best way to deal with such a thing would be to add a gametype filter to the main UT browser, and let the user tick and untick the gametypes that should show up.

**Comment by SeriousBuggie** [comment]
I try make solution, but suddenly found near each server think good screw up field GameType with something. 
So picture look like this:
![img](https://user-images.githubusercontent.com/70026933/119241378-92413900-bb5e-11eb-8a94-fba8e31538da.png)

**Comment by SeriousBuggie** [comment]
Screenshots for fix:
![img](https://user-images.githubusercontent.com/70026933/119248241-8a9e8600-bb98-11eb-827c-91835f2989e5.png)
![img](https://user-images.githubusercontent.com/70026933/119248255-968a4800-bb98-11eb-82db-c82a478aa29d.png)
![img](https://user-images.githubusercontent.com/70026933/119248266-adc93580-bb98-11eb-8b0b-7c47998f9a87.png)
![img](https://user-images.githubusercontent.com/70026933/119248416-aeae9700-bb99-11eb-8f1f-a8f69fb9ce0f.png)
![img](https://user-images.githubusercontent.com/70026933/119248427-ba9a5900-bb99-11eb-97a7-9a6a3c305044.png)

Settings stored per tab separately. Up to 256 hidden GameTypes.
Filters grid visible all time. Even if empty or there only one type.
Possible select row with arrows. And toggle status by Enter/Space.
Context menu allow `Show all`/`Hide all`.
Menu items, columns names, state names - localized.
Browser window max width on open increase from 620 to 730.
Size of some fields of server grid reduced.
Possible some log records about PingDone if you use hide types. But nothing critical - items not in PingedList.
Possible sort game types by count servers. Or by state.
Possible resize splitter between server grid and GameTypes grid. But splitter position separate for each tab and not restore after game restart.
Iterating over items far from optimal. For 627 server can be near 20k calls of inner loop body in worse enough case. But it is acceptable. I do not think we hit limit of iterations for uscript.
Where can be servers without info (in favorites for example) - you can see empty game type.

**Comment by NeonKnightOA** [comment]
That solution of yours is awesome @SeriousBuggie ! Can it be extended to filter mutators/serveractors as well or is it too much?

**Comment by SeriousBuggie** [comment]
Yep. I have few some ideas for extends but it not make sense until I not know this changes will be accepted.
