### ISSUE TITLE
[469c-RC2] [OpenGL] Incorrect rendering of translucent meshes in fog

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#980]
Test map: [_fog_test.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9208979/_fog_test.zip)
 
OpenGL:
![](https://user-images.githubusercontent.com/10724977/181496520-c32720a6-82e6-4fc9-a7cc-fcd2dacbaafe.jpg)

Other renderers:
![](https://user-images.githubusercontent.com/10724977/181496601-78d43212-4d80-48bb-be8b-7b37a8675370.jpg)

**Comment by stijn-volckaert** [comment]
Does this still happen in the latest 469d previews?

**Comment by stijn-volckaert** [comment]
Bug confirmed
