### ISSUE TITLE
[469c-RC2] [OpenGL] Meshes have offset UV coordinates

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#981]
Test map: [_mesh_uv.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9209579/_mesh_uv.zip)

OpenGL on the left, other renderers on the right:
![](https://user-images.githubusercontent.com/10724977/181508222-543fb256-bc91-4a9e-a4e4-f7730645663b.jpg)

Gif:
![](https://user-images.githubusercontent.com/10724977/181510467-cb3c00bf-2eb8-42ca-b22d-817665b88174.gif)

**Comment by stijn-volckaert** [comment]
I think @CacoFFF fixed this one quite recently, so 469d should no longer be affected by this issue

**Comment by SeriousBuggie** [comment]
Still happen on v469d preview 10 based builds:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/2d06cbd0-1e6c-4e0b-981b-e235b1450286

**Comment by stijn-volckaert** [comment]
Should be fixed in the next build
