### ISSUE TITLE
Failed to preallocate initial textures, 1024x1024: DDERR_OUTOFVIDEOMEMORY

### ISSUE THREAD

**Issue by gamerz31w** [OldUnreal/UnrealTournamentPatches#987]
Failed to preallocate initial textures, 1024x1024: DDERR_OUTOFVIDEOMEMORY

History: Alloc Textures <- UD3DRenderDevice::SetRes <-
UD3DRenderDevice::Init <- UWindowsViewport::TryRenderDevice <-
UWindowsViewport::OpenWindow <- UGameEngine::Init <- InitEngine

**Comment by SeriousBuggie** [comment]
D3D render outdated and not supported. You should use D3D9 render.

**Comment by gamerz31w** [comment]
Well it looks like I cannot even change video settings like it should show me such options automatically. At least I tried.

**Comment by SeriousBuggie** [comment]
Edit UnrealTournament.ini
Or start it as `UnrealTournament.exe -changevideo`
or after crash, on recovery dialog select `change video`.

**Comment by gamerz31w** [comment]
Well thanks it helped. Can you tell me how to swap any original Unreal Tournament game playable character with Jazz Jackrabbit,please? Let's hope it didn't turn into off-topic matters.
