### ISSUE TITLE
[469a] "override GUI scaling" messes with single player menus

### ISSUE THREAD

**Issue by AntiSol** [OldUnreal/UnrealTournamentPatches#99]
If I enable "override GUI scaling" in preferences -> video, the menus for the single player game are not scaled correctly, cutting off the top and bottom of the menu:
![Screenshot_2020-10-09_03-22-53](https://user-images.githubusercontent.com/351169/95486898-58f8f600-09df-11eb-96bc-71cb65c5099b.jpg)

If I turn off "override GUI scaling", the menus aren't scaled to fill the screen at all (which might be intended?)
![Screenshot_2020-10-09_03-24-33](https://user-images.githubusercontent.com/351169/95486947-6dd58980-09df-11eb-88ad-0468af0bd5e6.jpg)

Note that it seems that setting the gui scaling factor has an effect on these menus, but if I set the scaling factor very high (i.e a very large gui), the menus seem to stretch to fill the screen but maintaining aspect ratio, i.e what I'd expect them to do.

I think that maybe these menus should just be stretched to fill the screen but maintain aspect ratio, ignoring the gui scaling factor?

(I'm running on ubuntu 16.04, not sure if this is just a linux thing or if it's all platforms)

**Comment by AntiSol** [comment]
surely the menus should never be bigger than the screen, yes?

**Comment by SeriousBuggie** [comment]
Problem not connected with `override GUI scaling`. This option only expose main problem: wrong calculate sizes for ladder windows.

For fix nedd replace code at:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UTMenu/UTLadderStub.uc#L26
```
	if (RootWin.WinWidth > 1024)
	{
		Win.WinWidth = 1024;
		Win.WinHeight = 768;
		Win.WinLeft = (RootWin.WinWidth - 1024) / 2;
		Win.WinTop = (RootWin.WinHeight - 768) / 2;
	} else {
		Win.WinWidth = (RootWin.WinHeight / 3) * 4;
		Win.WinHeight = RootWin.WinHeight;
		Win.WinTop = 0;
		Win.WinLeft = (RootWin.WinWidth - Win.WinWidth) / 2;
	}
```
to
```
	local float KW, KH;

	KW = RootWin.WinWidth/1024;
	KH = RootWin.WinHeight/768;

	if (KW > KH) KW = KH;
	if (KW > 1) KW = 1;

	Win.WinWidth = KW*1024;
	Win.WinHeight = KW*768;
	Win.WinLeft = (RootWin.WinWidth - Win.WinWidth) / 2;
	Win.WinTop = (RootWin.WinHeight - Win.WinHeight) / 2;
```
And all be fine in any resolution.

**Comment by stijn-volckaert** [comment]
Merged Buggie's patch for 469c
