### ISSUE TITLE
[469b] 2D Shape Editor: Grid render with awful precision

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#994]
Open 2D shape editor and just zoom in out with mouse scroll. Look where placed points. They must be on same place, relative to grid, on any zoom.
Good (rare):
![img](https://user-images.githubusercontent.com/70026933/182549419-74d8f759-53ee-4a2e-8ba2-8152dc574d00.png)
![img](https://user-images.githubusercontent.com/70026933/182549563-904b404e-250c-4d5f-8015-df6c026a2110.png)

Miss (often):
![img](https://user-images.githubusercontent.com/70026933/182549486-b62ac56c-8c9b-466e-b105-031b1e157868.png)
![img](https://user-images.githubusercontent.com/70026933/182549528-a81bc5cf-e65e-41e2-8ca8-4772f3dc6b39.png)
![img](https://user-images.githubusercontent.com/70026933/182549586-50a5e79a-cd6e-49bd-8c66-b8ca22bb3d59.png)
![img](https://user-images.githubusercontent.com/70026933/182549629-0e8e1746-8eba-4eaa-9d95-7694c444d37a.png)
![img](https://user-images.githubusercontent.com/70026933/182549664-eff8a52a-42e2-4953-af16-b5408b834e73.png)
![img](https://user-images.githubusercontent.com/70026933/182549697-00ed614f-e68c-40f2-ac9c-e5292f1eabb6.png)
![img](https://user-images.githubusercontent.com/70026933/182549728-79afd220-19a3-4a8c-9895-17de392d048b.png)
![img](https://user-images.githubusercontent.com/70026933/182549761-7235c0e6-a7fd-45a4-9531-dcfe71a6969e.png)
![img](https://user-images.githubusercontent.com/70026933/182549900-d5917e52-4edf-4fa9-8284-af6e094778ce.png)
![img](https://user-images.githubusercontent.com/70026933/182549932-0e6aa7d3-5760-4587-b97d-29be643cb3c9.png)
![img](https://user-images.githubusercontent.com/70026933/182549959-ba12df24-f430-436c-9318-cd24d4b4b1ec.png)
![img](https://user-images.githubusercontent.com/70026933/182549977-4a81e6f1-4afb-4d48-961a-81d7b12482a1.png)

**Comment by SeriousBuggie** [comment]
It is caused by scroll zoom.
Originally there be only menu item scroll. And it work as 0.5x or 2x.
Now here 1.1x or 0.91x zoom by scroll. so Paint grid not able do this because designed used int values.
Regression of v469.

**Comment by BerserkerBG** [comment]
When using lower grid sizes, like 8. You can still see misalignment and it changes when you keep zooming. 2D Shape Editor has strange issues with grid zooming, will make new issue.
![Screenshot_23](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/4eddbbd8-de76-459a-8746-50ce119649ff)
