### ISSUE TITLE
[469c-RC3] [OpenGL] First person view inventory is being drawn improperly...

### ISSUE THREAD

**Issue by an-eternity** [OldUnreal/UnrealTournamentPatches#996]
Expected behavior: First person view inventory is being drawn behind of the HUD and in front of everything else.
Actual behavior: First person view inventory is being drawn behind of everything else except some objects (such as Coronas).

Reproduceable only in test environments that use AMD GPU (with NVidia GPU - can not reproduce, with Intel GPU - have not tested yet). 
Reproduceable with clean/default UnrealTournament.ini and User.ini.

![v469c_ogl_fpinv-draw-bug](https://user-images.githubusercontent.com/72374425/183240146-e60da1b9-8145-4266-a682-25c1785a65a5.png)

**Comment by CacoFFF** [comment]
So AMD 'updates' their drivers and everything starts breaking...

**Comment by stijn-volckaert** [comment]
Does this still happen in the latest 469d previews?

**Comment by stijn-volckaert** [comment]
I just tested this with an AMD GPU and default inis and cannot reproduce the bug (anymore?). Feel free to reopen if this still happens in 469d
