### ISSUE TITLE
[469c-RC3] PulseGun ammo counter triggers crash on Intel Macs

### ISSUE THREAD

**Issue by e20norr** [OldUnreal/UnrealTournamentPatches#997]
Shortly after starting an offline game against bots, the app seems to crash randomly. I'm currently using a Macbook Pro 2017 to play the game. I do have a Mac with the M1-chip as well, which I haven't tried yet, but I'm guessing the game should work the same on both systems since the new app is universal. But as far as I can tell before the app crashes, this version seems to run way smoother than RC 2 did (which also seemed to crash randomly in a similar fashion).
<img width="459" alt="Skärmavbild 2022-08-06 kl  11 01 32" src="https://user-images.githubusercontent.com/110334156/183248114-d9bf4973-5391-4427-87e6-39a3c7ca72c5.png">

**Comment by stijn-volckaert** [comment]
Do you recall which map you were playing and the weapon you were holding?

**Comment by e20norr** [comment]
I just tried again and it crashed (with the same error message) just as I picked up the Pulse Gun on the map Curse.

**Comment by e20norr** [comment]
I just tried a few more maps and they also crash as soon as I switch to the Pulse Gun. The issue seems to be connected to the Pulse Gun.

**Comment by stijn-volckaert** [comment]
Okay that makes sense. The ammo counter you see on the pulse gun (and a few other weapons) is a scripted texture. That's probably what's causing the crash. Could you try setting your weapon hand to hidden to see if that fixes the problem?

**Comment by e20norr** [comment]
Yeah! Setting the weapon hand to hidden seems to fix the issue.

**Comment by stijn-volckaert** [comment]
Confirmed. This crashes immediately on Intel macs. I've also tested the Apple _and_ Intel binaries on an M1, and the crash doesn't happen there

**Comment by stijn-volckaert** [comment]
Fixed in the 469c release version
