### ISSUE TITLE
[469c-RC3] XOpenGLDrv shadows in combo boxes

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#998]
I tested the patch469c RC3 and I see that shadows appear in the menu and that the basic settings are probably too dark, you almost have to put a full lumunosity while it worked better with the previous RC2.  os Windows11 on 64bits 

Render is XOpengl

**Comment by SeriousBuggie** [comment]
You need specify, what render you use.

**Comment by stijn-volckaert** [comment]
I suspect you're using XOpenGLDrv. 469c-RC3 includes some new fixes and changes to make XOpenGLDrv's colors and brightness levels closer to the other renderers. I agree that even at max brightness, XOpenGLDrv is too dark. You can increase the brightness by adding

```
GammaMultiplier=2.0
```

to the [XOpenGLDrv.XOpenGLRenderDevice] section of your game in. I've also noticed the shadow on the left-hand side of combo boxes. This might be the result of a texture filtering change. We're currently investigating this.

**Comment by stijn-volckaert** [comment]
This should be fixed in the final v469c version
